define(
   ({
    _widgetLabel: "Imprimir",
    title: "Título do Mapa",
    format: "Formato",
    layout: "Layout",
    settings: "Avançado",
    mapScaleExtent: "Escala/extensão do mapa",
    preserve: "Preservar",
    mapScale: "escala do mapa",
    mapExtent: "extensão do mapa",
    forceScale: "Forçar escala",
    getCurrentScale: "atual",
    mapMetadata: "Metadados do layout",
    author: "Autor",
    copyright: "Copyright",
    fullLayoutOptions: "Opções completas do layout",
    scaleBarUnitsMetric: "Unidades de barra de escala métricas",
    scaleBarUnitsNonMetric: "Unidades de barra de escala não-métricas",
    unitsMiles: "Milhas",
    unitsKilometers: "Quilômetros",
    unitsMeters: "Metros",
    unitsFeet: "Pés",
    unitsYards: "Jardas",
    unitsNauticalMiles: "Milhas Náuticas",
    lncludeLegend: "Incluir legenda",
    printQualityOptions: "Qualidade de impressão",
    dpi: "DPI",
    mapOnlyOptions: "Tamanho MAP_ONLY",
    width: "Largura (px)",
    height: "Altura (px)",
    print: "Imprimir",
    clearList: "Limpar Impressões",
    creatingPrint: "Criando Impressão",
    printError: "Erro, tente novamente"
  })
);