define(
   ({
    _widgetLabel: "Analýza událostí",
    incident: "Událost",
    weather: "Počasí",
    locate_incident: "Vyhledat událost",
    clear_incidents: "Vymazat události",
    reverse_geocoded_address: "Nejbližší adresa",
    reverse_geocoded_error: "Není k dispozici",
    miles: "Míle",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    now: "NYNÍ",
    wind: "OKNO",
    SUN: "NE",
    MON: "PO",
    TUE: "ÚT",
    WED: "ST",
    THU: "ČT",
    FRI: "PÁ",
    SAT: "SO",
    defaultTabMsg: "Nebyly identifikovány žádné incidenty.",
    actionLabel: "Nastavit jako incident",
    useMapExtent: "Použít současný rozsah mapy",
    noFeaturesFound: "Nebyly nalezeny žádné prvky.",
    downloadCSV: "STÁHNOUT CSV",
    sum: "SUMA",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "POČET",
    area: "PLOCHA",
    length: "DÉLKA"
  })
);
