define(
   ({
    _widgetLabel: "รายงานข้อมูล",
    select: "เลือก",
    draw: "วาด",
    chooseALayer: "เลือกแผนที่หรือรายการฟีเจอร์เซอร์วิส",
    clickAFeature: "คลิกที่ข้อมูลในแผนที่เพื่อเลือก",
    loadingFeatures: "รับรายละเอียดข้อมูลที่เลือก…",
    errorTitle: "ข้อผิดพลาด",
    errorIdentify: "ระบุคุณสมบัติข้อผิดพลาด กรุณาตรวจสอบการรายละเอียดด้วย console log",
    infoWindowTitle: "รายละเอียด",
    layerLabel: "ชื่อชั้นข้อมูล",
    reviewStatusLabel: "สำรวจสถานะ",
    selectReviewStatusAdd: "เพิ่มข้อมูล",
    selectReviewStatusDelete: "ลบฟีเจอร์",
    selectReviewStatusMove: "ย้ายฟีเจอร์",
    selectReviewStatusReshape: "เปลี่ยนฟีเจอร์",
    drawReviewStatusMissing: "ฟีเจอร์ที่ไม่พบ",
    drawReviewStatusPosition: "ตำแหน่งผิดพลาด",
    drawReviewStatusShape: "รูปร่างผิดพลาด",
    drawReviewStatusAttribute: "แอดทริบิวต์ผิดพลาด",
    notesLabel: "บันทึก",
    severityLabel: "ความรุนแรง",
    reportedByLabel: "รางานโดย",
    reportedByDefault: "ไม่ระบุชื่อ",
    reportButton: "รายงาน",
    reportMessage: "รับรายงานแล้ว",
    errorReportMessage: "มีข้อผิดพลาดในการสร้างรายงานของคุณ",
    drawErrorInstructions: "เลือกจุด เส้น หรือ รูปปิด และวาดรูปที่ข้อผิดพลาดบนแผนที่:",
    errorMapService: "มีข้อผิดพลาดในการรับข้อมูลแซอร์วิสแผนที่",
    noFeatureSelected : "ไม่พบฟีเจอร์ในตำแหน่งที่มีการคลิก",
    selectFeatureMapPoint: "คลิกเพื่อเลือกฟีเจอร์",
    drawFeatureMapPoint: "คลิกเพิ่มจุด",
    popupMessage:"ข้อความ",
    popupError:"ข้อผิดพลาด",
    manyFeaturesSelected: "มีฟีเจอร์มากกว่าหนึ่งฟีเจอร์ กรุณาซูมเข้าและเลือกฟีเจอร์ที่ต้องการรายงาน"
  })
);
