define(
   ({
    _widgetLabel: "Αναφορά στοιχείου",
    select: "Επιλογή",
    draw: "Σχεδίαση",
    chooseALayer: "Επιλέξτε θεματικό επίπεδο",
    clickAFeature: "Κάντε κλικ σε ένα στοιχείο στο χάρτη για να το επιλέξετε.",
    loadingFeatures: "Λήψη λεπτομερειών για το επιλεγμένο στοιχείο...",
    errorTitle: "Σφάλμα",
    errorIdentify: "Προσδιορίστε το σφάλμα στοιχείου. Ελέγξτε το αρχείο καταγραφής κονσόλας για λεπτομέρειες.",
    infoWindowTitle: "ΛΕΠΤΟΜΕΡΕΙΕΣ",
    layerLabel: "Όνομα επιπέδου",
    reviewStatusLabel: "Κατάσταση ανασκόπησης",
    selectReviewStatusAdd: "Προσθήκη στοιχείου",
    selectReviewStatusDelete: "Διαγραφή στοιχείου",
    selectReviewStatusMove: "Μετακίνηση στοιχείου",
    selectReviewStatusReshape: "Επανασχεδίαση στοιχείου",
    drawReviewStatusMissing: "Στοιχεία που λείπουν",
    drawReviewStatusPosition: "Σφάλμα θέσης",
    drawReviewStatusShape: "Σφάλμα σχήματος",
    drawReviewStatusAttribute: "Σφάλμα γνωρίσματος",
    notesLabel: "Σημειώσεις",
    severityLabel: "Σοβαρότητα",
    reportedByLabel: "Αναφέρθηκαν κατά",
    reportedByDefault: "ανώνυμος",
    reportButton: "Αναφορά",
    reportMessage: "Η αναφορά λήφθηκε",
    errorReportMessage: "Παρουσιάστηκε σφάλμα κατά την αναφορά του στοιχείου σας",
    drawErrorInstructions: "Επιλέξτε το σημείο, τη γραμμή ή το πολύγωνο και σχεδιάστε τη γεωμετρική θέση του σφάλματος στον χάρτη:",
    errorMapService: "Παρουσιάστηκε σφάλμα κατά τη λήψη των πληροφοριών της υπηρεσίας χάρτη",
    noFeatureSelected : "Δεν βρέθηκαν έγκυρα στοιχεία στη θέση που επιλέχθηκε",
    selectFeatureMapPoint: "Κάντε κλικ, για να επιλέξετε ένα στοιχείο",
    drawFeatureMapPoint: "Κάντε κλικ για προσθήκη σημείου",
    popupMessage:"Μήνυμα",
    popupError:"Σφάλμα",
    manyFeaturesSelected: "Βρέθηκαν περισσότερα από ένα στοιχεία. Μεγεθύνετε και επιλέξτε ένα στοιχείο για αναφορά."
  })
);
