define({
  settings: "Paramètres",
  addSearch: "Ajouter une couche de recherche",
  updateSearch: "Mise à jour de la couche de recherche",
  addBuffer: "Ajouter des valeurs par défaut à la zone tampon",
  updateBuffer: "Mise à jour des valeurs par défaut à la zone tampon",
  addSearchExpr: "Ajouter une expression",
  updateSearchExpr: "Mise à jour de l\'expression",
  addExpressionValue: "Ajouter une valeur à l\'expression",
  updateExpressionValue: "Mise à jour de la valeur de l\'expression",
  addExpression: "Ajouter une expression",
  addLink: "Ajouter un lien",
  updateLink: "Mise à jour du lien",
  searchTitle: "Titre de la recherche",
  expressionsTitle: "Expression(s) de recherche",
  linksTitle: "Lien(s) depuis la recherche",
  bufferUnitTitle: "Unité de la zone tampon",
  spatialRelationshipTitle: "Relation(s) spatiale(s)",
  linkAlias: "Alias du lien",
  disablenulllink: "Désactivé le lien si Nul",
  disablelinkinpopup: "Désactivé le lien dans la PopUp",
  popuplinktype: "Lien de type",
  linktext: "Texte",
  linkimage: "Image",
  linkiconcontent: "Icône du lien vers les contenus",
  linkcontent: "Lien vers les contenus",
  linkiconcontenthint: "L’icône du lien vers le contenu peut être du texte, des champs attributaires,  ou une combinaison des  deux, qui permet de créer un chemin URL \\ valide vers l’image de l’icône des liens. Pour ajouter des champs attributaires cliquer sur le bouton plus bleu sur la droite de la zone de saisie.",
  linkcontenthint: "L’icône du lien vers le contenu peut être du texte, des champs attributaires,  ou une combinaison des  deux, qui permet de créer un chemin URL \\ valide vers les contenus liés . Pour ajouter des champs attributaires cliquer sur le bouton plus bleu sur la droite de la zone de saisie.",
  valuesTitle: "Valeur(s) de l'expression de recherche",
  actions: "Actions",
  zoomScale: "Echelle du Zoom",
  back: "Retour",
  sum: "Résumer cela valeurs des champs",
  sumlabel: "somme Étiquette",
  searchUrl: "URL de recherche",
  browse: "Naviguer",
  title: "Titre",
  definitionexpr: "Expression de définiton",
  expression: "Expression",
  searchLabel: "Nom de la Recherche",
  searchHint: "Indice pour la rechcerche",
  availableFields: "Champs disponibles",
  name: "Nom",
  alias: "Alias",
  includedFields: "Champs inclus",
  cancel: "Annuler",
  ok: "OK",
  addSearch2: "Ajouter une recherche",
  operationalLayerTip: "Ajouter les résultats dans une  couche opérationnelle",
  initialView: "Vue de départ",
  disableTabs: "Modifier Tab Désactivé",
  selectFeatures: "Par Forme",
  selectByAttribute: "Par Attribut",
  editDefaultSym: "Modifier les symboles par défaut pour la recherche",
  editDefaultBuffer: "Modifier les propriétés par défaut de la zone tampon",
  editDefaultGraphical: "Modifier graphiques d'options de recherche",
  point: "Symbole ponctuel par défaut",
  line: "Symbole linéaire par défaut",
  poly: "Symbole par défaut pour les polygones",
  includeall: "Tout inclure",
  include: "Inclus",
  useMultiGraphics: "Autoriser les graphiques mulit-parties par défaut",
  addTolerance: "Ajouter, par défaut, une tolérance de recherche à la sélection par point",
  keepGraphicalEnabled: "Conserver les outils de recherche graphique après chaque dessin",
  autoZoom: "Zoom auto sur les résultats de la recherhce",
  pointTolerance: "Tolérance à ajouter à une recherche par graphique de type point",
  searchExpressions: "Expressions de recherche",
  expressionAlias: "Alias des l\'expression",
  addValue: "Ajouter une valeur à l\'expression",
  valuePrompt: "Demande",
  valueSQL: "Requête SQL",
  valueDefault: "Valeur par défaut",
  textSearchHint: "Info rechcerche (Exemple de Valeur)",
  none: "Aucun",
  string: "Chaîne",
  number: "Nombre",
  date: "Date",
  stringOperatorIn: "dans", // e.g. <stringFieldName> in ('California', 'Arizona')
  stringOperatorIs: "est", // e.g. <stringFieldName> is 'California'
  stringOperatorIsNot: "n\'est pas",
  stringOperatorStartsWith: "commence par",
  stringOperatorEndsWith: "finit par",
  stringOperatorContains: "contient",
  stringOperatorDoesNotContain: "ne contient pas",
  stringOperatorIsBlank: "est vide",
  stringOperatorIsNotBlank: "n\'est pas vide",
  dateOperatorIsOn: "est le", // e.g. <dateFieldName> is on '1/1/2012'
  dateOperatorIsNotOn: "n\'est pas le",
  dateOperatorIsBefore: "est avant",
  dateOperatorIsAfter: "est après",
  dateOperatorDays: "jours",
  dateOperatorWeeks: "semaines", // e.g. <dateFieldName> is the last 4 weeks
  dateOperatorMonths: "mois",
  dateOperatorInTheLast: "dans le dernier",
  dateOperatorNotInTheLast: "n'est pas dans le dernier",
  dateOperatorIsBetween: "est entre",
  dateOperatorIsNotBetween: "n\'est pas entre",
  dateOperatorIsBlank: "est vide",
  dateOperatorIsNotBlank: "n'est pas vide",
  numberOperatorIn: "dans", // e.g. <stringFieldName> in (1000,2000)
  numberOperatorIs: "est", // e.g. <numberFieldName> is 1000
  numberOperatorIsNot: "n'est pas",
  numberOperatorIsAtLeast: "est au moins égale à",
  numberOperatorIsLessThan: "est inférieur à",
  numberOperatorIsAtMost: "est au plus de",
  numberOperatorIsGreaterThan: "est supérieur à",
  numberOperatorIsBetween: "est entre",
  numberOperatorIsNotBetween: "n\'est pas entre",
  numberOperatorIsBlank: "est vide",
  numberOperatorIsNotBlank: "n\'est pas vide",
  valueField: "Champ",
  valueOperation: "Opération",
  valueMethod: "Méthode",
  all: "Tout",
  any: "N\'importe quelle valeur",
  value: "Valeur",
  field: "Champ",
  unique: "Unique",
  and: "et",
  operator: "Opérateur",
  valueTooltip: "Entrer une valeur",
  fieldTooltip: "Choisir dans un champ existant",
  uniqueValueTooltip: "Choisir une valeur unique dans le champ sélectionné",
  friendlyDatePattern: "MM/dd/yyyy",
  askForValues: "Besoin d'une valeur",
  prompt: "Prompt",
  hint: "Suggestion",
  strMatchMsgPart1: "Obtenir des entités de la couche qui correspondent à ",
  strMatchMsgPart2: " A partir de cela et des critères précédents de l\'expression",
  userListMsg: "Demander une valeur depuis une liste de valeurs prédéfinies",
  predefinedValue: "Valeur(s) prédéfinie(s)",
  list: "Liste:",
  addListValue: "Ajouter une liste de valeurs",
  predefinedTooltip: "Choisir dans la liste de valeurs prédéfinies",
  predefined: "Prédéfini",
  error: {
    invalidParams: "Paramètres invalides.",
    invalidUrl: "URL invalide.",
    noFilterFields: "La couche n\'a pas de champ qui peut être utiliser comme filtre.",
    invalidSQL: "Expression SQL invalide.",
    cantParseSQL: "Analyse impossible de la requête SQL."
  },
  edit: "Edition du format du champ",
  dateformat: "Format de date",
  dayShortMonthYear: "Jour Mois Année",
  longDate: "Date longue",
  longMonthDayYear: "Mois long Jour Année",
  longMonthYear: "Mois long Année",
  shortDate: "Date courte",
  shortDateLongTime: "Jour court Heure Longue",
  shortDateLongTime24: "Jour court Heure Longue 24",
  shortDateShortTime: "Jour court Heure Courte",
  shortDateShortTime24: "Jour court Heure Courte 24",
  shortMonthYear: "Mois court Année",
  year: "Année",
  custom: "Personnalisé",
  useutc: "Format UTC",
  currencyfield: "Champ monétaire",
  currencySymbol: "Symbole monétaire",
  examplecurrency: "€",
  precision: "Précision",
  exampleprecision: ".",
  usethousandssep: "Utilser un séparateur de milliers",
  examplethousands: ",",
  overrideSQL: "Override",
  editBufferUnit: "Ajouter ou Supprimer les unités de la zone tampon",
  defaultBufferValue: "Valeur par défaut de la zone tampon",
  defaultBufferWKID: "Réf. spatiale par défaut de la zone tampon, WKID",
  bufferSymbol: "Symbole de la zone tampon (cliquer pour modifier)",
  addbufferunit: "Sélectionner les unités de la zone tampon",
  addspatalrelationships: "Sélectionner la ou les relation(s) spatiale(s) disponible(s)",
  addUnit: "Ajouter\\Supprimer les Unités",
  addRemove: "Ajouter\\Supprimer",
  warning: "Aucune unité sélectionnée pour la zone tampon",
  addSymbol: "Ajouter une couche de symbologie spécifique",
  pointSymbol: "Symbole pontuel: ",
  lineSymbol: "Symbole Linéaire: ",
  polySymbol: "Symbole polygone: ",
  symbologyTooltip: "Cliquer sur le symbole que vous souhaitez modifier.",
  spatialSearchLayer: "Couche de recherche spatiale",
  editDefaultSpatial: "Modifier les propriétés de recherche spatiale",
  layerSymbology: "Symboles des couches",
  symbolServer: "Depuis le serveur",
  symbolConfig: "Depuis la config défaut",
  requiredfield: "champ obligatoire",
  isempty: "est vide",
  showinattributetable: "Afficher en widget table attributaire",
  showattachments: "Afficher les pièces jointes",
  andor: "et ou",
  tobeenabled: "oit activé",
  graphicalSearchOptions: "Graphical Search Options",
  addgraphicalsearchoptions: "Choisissez Disponible graphique Option de recherche",
  editdisabledtaboptions: "Choisissez Recherche Tab(s) pour Désactiver",
  graphictab: "Recherche Graphique Tab",
  attributetab: "attribut Rechercher Tab",
  spatialtab: "Recherche spatiale Tab",
  resultstab: "Résultats Tab",
  availabletabs: "Désactivé Tab(s)",
  popuponly: "Popup seulement",
  graphicInteract: "Affichage contextuel sur la recherche de la souris sur graphique",
  limit2mapextent: "Activer résultats de limites pour cartographier mesure par les défaut",
  addbuffertolegend: "Ajouter la couche tampon à la légende de cartes",
  enableExportSearchURL: "Activer URL de la Recherche Export",
  uniqueValues: 'Récupération des valeurs uniques',
  processingUnique: 'Traitement des valeurs uniques: ',
  of: ' de ',
  showResultsPopup: "Affichage contextuel lorsque les résultats fiche cliqué",
  resultItemSorting: "Tri de l\'élément de résultat",
  configureFieldsTip: "Configurez les champs en fonction desquels le résultat de la requête sera trié.",
  addNew: "Ajouter une requête",
  sortingOrder: "",
  ascending: "Croissant",
  descending: "Décroissant",
  sortBy: "Trier par",
  thenBy: "Puis par",
  sortDisabledMsg: "Handicapés: couche de service doit soutenir possibilités d'interrogation avancée: OrderBy",
  editSortBy: "Modifier Trier par",
  showuseMultiGraphics: "Afficher activer l'option multi-parties graphiques",
  showaddTolerance: "Afficher Ajouter tolérance de recherche à l'option de sélection du collimateur",
  showaddsqltext: "Afficher inclure du texte requête dans option critères de sélection",
  showbuffergraphic: "Afficher les options Tampon graphiques",
  buffergraphicbydefault: "Activer tampon graphique par défaut",
  expressionValueRequired: "Valeur doit être saisi pour permettre la recherche",
  enableelocateselect: "Graphics Widget eLocate",
  defExprPlaceholder: "En option (voir widgets aider pour plus de détails)",
  zoomscaletip: "Échelle de zoom sera applicable à tous les types de géométrie, et pas seulement des points",
  forceScale: "force de l'échelle",
  editResultFormat: "Edit Result Formating",
  fromatTooltip: "The formtting set here will affect the result popups and widget result text",
  attribTitleLbl: "Result Attribute Title:",
  attribTitleExample: "Name",
  attribValueLbl: "Result Attribute Value:",
  attribValueExample: "John Doe",
  color: "Color",
  insertbold: "Bold",
  insertitalic: "Italic",
  insertunderline: "Underline",
  preview: "Format Preview"
});
