define(
   ({
    _widgetLabel: "Situation Awareness (Beta)",
    locate_incident: "尋找事件點",
    clear_incidents: "清除事件點",
    reverse_geocoded_address: "最近的地址",
    reverse_geocoded_error: "無法使用",
    miles: "英里",
    kilometers: "公里",
    feet: "英呎",
    meters: "公尺",
    yards: "碼",
    nauticalMiles: "海浬",
    now: "目前",
    wind: "風力",
    SUN: "星期日",
    MON: "星期一",
    TUE: "星期二",
    WED: "星期三",
    THU: "星期四",
    FRI: "星期五",
    SAT: "星期六",
    defaultTabMsg: "未識別任何事件點。",
    actionLabel: "設為事件點",
    drawPoint: "繪製點",
    drawLine: "繪製線",
    drawPolygon: "繪製面",
    saveIncident: "儲存事件點",
    clearIncident: "清除事件點",
    useMapExtent: "使用目前地圖範圍",
    noFeaturesFound: "未找到任何圖徵。",
    downloadCSV: "下載 CSV",
    editComplete: "已成功儲存圖徵!",
    updateComplete: "圖徵已更新成功！",
    deleteComplete: "圖徵已刪除成功！",
    sum: "總和",
    min: "最小值",
    max: "最大值",
    avg: "平均值",
    count: "計數",
    area: "區域",
    length: "長度",
    notPolySave: "請於儲存之前指定緩衝執行個體。",
    update_btn: "更新",
    delete_btn: "刪除"
  })
);
