define(
   ({
    addDistance: "Ajouter une unité de longueur",
    addArea: "Ajouter une unité de surface",
    label: "Etiquette",
    abbr: "Abréviation",
    conversion: "Conversion",
    actions: "Actions",
    areaUnits: "Unités de surface",
    distanceUnits: "Unités de longueur",
    kilometers: "Kilomètres",
    miles: "Miles",
    meters: "Mètres",
    feet: "Pieds",
    yards: "Yards",
    squareKilometers: "Kilomètres carrés",
    squareMiles: "Miles carrés",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Mètres carrés",
    squareFeet: "Pieds carrés",
    squareYards: "Yards carrés",
    distance: "Distances",
    area: "Surfaces",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "pi",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "mi²",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "pd²",
    squareYardsAbbreviation: "yd²",
    defineUnits: "Définissez les unités de mesure.",
    operationalLayer: "Ajoutez le dessin en tant que couche opérationnelle de la carte."
  })
);