define(
   ({
    _widgetLabel: "Gráfico",
    executeChartTip: "Clique num dos seguintes itens de tarefa para executar o gráfico.",
    invalidConfig: "Configuração inválida.",
    noneChartTip: "Não foi configurada qualquer de gráfico para este widget.",
    chartParams: "Opções",
    charts: "GRÁFICOS",
    apply: "Aplicar",
    useSpatialFilter: "Utilizar filtro espacial para limitar elementos",
    useCurrentMapExtent: "Apenas elementos intersectam área de mapa actual",
    drawGraphicOnMap: "Apenas elementos intersectam uma área definida por utilizador",
    chartResults: "Resultados dos Gráficos",
    clearResults: "Limpar Resultados",
    noPermissionsMsg: "Não possui permissões para aceder a este serviço.",
    specifySpatialFilterMsg: "Por favor especifique um filtro espacial para esta tarefa.",
    queryError: "A consulta falhou.",
    noResults: "Nenhum resultado",
    category: "Categoria",
    count: "Contagem",
    label: "Rótulo",
    horizontalAxis: "Eixo Horizontal",
    verticalAxis: "Eixo Vertical",
    dataLabels: "Rótulos de Dados",
    color: "Cor",
    colorful: "Colorido",
    monochromatic: "Monocromático",
    tasks: "Tarefas",
    results: "Resultados",
    applySpatialFilterToLimitResults: "Aplique um filtro espacial para limitar os resultados",
    useCurrentExtentTip: "Parcialmente ou totalmente no contido na atual extensão de mapa",
    useDrawGraphicTip: "Parcialmente ou totalmente no contido na forma desenhada no mapa",
    useFeaturesTip: "Baseado nas respetivas localizações em relação a elementos noutra camada",
    noSpatialLimitTip: "Não limita resultados espacialmente",
    applySearchDistance: "Aplique uma distância de pesquisa",
    spatialRelationship: "Relação Espacial",
    relatedLayer: "Camada Relacionada",
    clear: "Limpar",
    bufferDistance: "Distância do Buffer",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    back: "Retroceder",
    execute: "Executar"
  })
);