define({
  root: ({
    _widgetLabel: 'Chart',
    executeChartTip: 'Click one of the following task items to execute chart.',
    invalidConfig: 'Invalid configuration.',
    noneChartTip: 'No preconfigured chart tasks available.',
    chartParams: 'Options',
    charts: 'CHARTS',
    apply: 'APPLY',
    useSpatialFilter: 'Use spatial filter to limit features',
    useCurrentMapExtent: 'Only features touching the current map extent',
    drawGraphicOnMap: 'Only features touching a user defined area',
    chartResults: 'Chart Results',
    clearResults: 'Clear Results',
    noPermissionsMsg: 'You do not have permissions to access this service.',
    specifySpatialFilterMsg: 'Please specify spatial filter for this task.',
    queryError: 'Query failed.',
    noResults: "No feature found.",
    category: "Category",
    count: "Count",
    label: "Label",
    horizontalAxis: "Horizontal Axis",
    verticalAxis: "Vertical Axis",
    dataLabels: "Data Labels",
    color: "Color",
    colorful: "Colorful",
    monochromatic: "Monochromatic"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});