define(
   ({
    taskUrl: "URL задачи",
    serviceURLPlaceholder: "Введите URL задачи геообработки",
    ok: "OK",
    cancel: "Отмена",
    layer: "Слой",
    action: "Действие",
    input: "Входные данные",
    output: "Выходные данные",
    name: "Имя",
    type: "Тип",
    required: "Обязательно",
    layerOrder: "Порядок слоев",
    options: "Опции",
    defaultValue: "Значение по умолчанию",
    inputFeatureBy: "Входные объекты по",
    renderer: "Метод отображения",
    displayType: "Тип отображения",
    label: "Надпись",
    tooltip: "Подсказка инструментов",
    visible: "Видимый",
    helpUrl: "URL Справки",
    useResultMapService: "Используйте опции рисования полученного картографического сервиса",
    drawOnMap: "Интерактивное рисование на карте",
    selectLayer: "Выбор слоя карты",
    url: "URL-адрес",
    symbol: "Символ",
    shareResults: "Добавить результат как операционный слой",
    popup: "Popup",
    setTask: "Задать",
    setTaskTitle: "Задать задачу геообработки",
    enablePopup: "Включить всплывающее окно"
  })
);