define(
   ({
    _widgetLabel: "استعلام",
    executeQueryTip: "انقر على أحد عناصر المهمة التالية لتنفيذ الاستعلام.",
    invalidConfig: "تكوين غير صحيح. الرجاء استخدام صفحة إعدادات الاستعلام للحصول على التكوين الصحيح.",
    queryParams: "خيارات",
    parameters: "خيارات",
    queries: "استعلامات",
    apply: "تطبيق",
    queryResults: "نتائج",
    clear: "مسح",
    noResults: "لم يتم العثور على أية معالم",
    queryError: "فشل الاستعلام!",
    numberFound: "عدد المعالم التي تم إيجادها",
    mapExtentTip: "حدود نتائج نطاق الخريطة الحالي.",
    noValue: "لا توجد قيمة",
    and: "و",
    stringOperatorIs: "هو", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ليس",
    stringOperatorStartsWith: "البدء بـ",
    stringOperatorEndsWith: "الانتهاء بـ",
    stringOperatorContains: "يحتوي على",
    stringOperatorDoesNotContain: "لا يحتوي على",
    stringOperatorIsBlank: "فارغ",
    stringOperatorIsNotBlank: "ليس فارغًا",
    dateOperatorIsOn: "هو", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ليس",
    dateOperatorIsBefore: "قبل",
    dateOperatorIsAfter: "بعد",
    dateOperatorDays: "يوم",
    dateOperatorWeeks: "أسبوع", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "شهر",
    dateOperatorInTheLast: "في آخر",
    dateOperatorNotInTheLast: "ليس في الآخر",
    dateOperatorIsBetween: "بين",
    dateOperatorIsNotBetween: "ليس بين",
    dateOperatorIsBlank: "فارغ",
    dateOperatorIsNotBlank: "ليس فارغًا",
    numberOperatorIs: "هو", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ليس",
    numberOperatorIsAtLeast: "على الأقل",
    numberOperatorIsLessThan: "أقل من",
    numberOperatorIsAtMost: "في الغالب",
    numberOperatorIsGreaterThan: "أكبر من",
    numberOperatorIsBetween: "بين",
    numberOperatorIsNotBetween: "ليس بين",
    numberOperatorIsBlank: "فارغ",
    numberOperatorIsNotBlank: "ليس فارغًا",
    operationalLayerTip: "أضف النتيجة باعتبارها طبقة تشغيلية",
    queryResult: "نتائج الاستعلام",
    specifyParamsTip: "حدد المعلمات للمهمة الحالية",
    useSpatialFilter: "استخدام عوامل التصفية المكانية لتقييد المعالم",
    useCurrentMapExtent: "تلمس المعالم نطاق الخريطة الحالي فقط",
    drawGraphicOnMap: "تلمس المعالم منطقة المستخدم المُعرفة فقط.",
    specifySpatialFilterMsg: "يرجى تحديد عامل التصفية المكاني للمهمة الحالية.",
    clearResults: "مسح النتائج",
    operationalTip: 'مع الخيار الحالي المُحدد، ستبقى النتائج على الخريطة حتى النقر على زر "${clearResults}".',
    noneQueryTip: "لا توجد أي مهام استعلام مُعرفة مُسبقًا متاحة.",
    noPermissionsMsg: "ليس لديك أي اذونات للوصول إلى هذه الخدمة."
  })
);