define({
  root: ({
    routeUrl: "Route URL",
    locatorUrl: "Geocoder URL",
    geocoderOptions: "Geocoder options",
    autoComplete: "Autocomplete",
    maxLocations: "Maximum locations",
    minCharacters: "Minimum characters",
    searchDelay: "Search delay",
    placeholder: "Placeholder",
    routeOptions: "Route options",
    directionsLanguage: "Directions language",
    directionsLengthUnits: "Directions length units",
    directionsOutputType: "Directions output type",
    impedanceAttribute: "Impedance attribute",
    kilometers: "Kilometers",
    miles: "Miles",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    parametersTip: "Please set parameters correctly !",
    complete: "Complete",
    completeNoEvents: "Complete No Events",
    instructionsOnly: "Instructions Only",
    standard: "Standard",
    summaryOnly: "Summary Only",
    travelModesUrl: "Travel Modes URL",
    searchPlaceholder: "Find address or place",
    trafficLayerUrl: "Traffic Layer URL"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});