define(
   ({
    selectAnalysisTools:"Selecione ferramentas de análise para utilizar no widget.",
    selected: "selecionado",
    name: "Nome",
    graphicalDisplay:"Visualização gráfica",
    usage: "Uso",
    settings: "Configurações",
    toolSetting: "Configurar detalhes da ferramenta",
    toolLabel: "O nome de visualização da ferramenta",
    showHelpTip: "Mostrar links de ajuda no widget",
    showCurrentMapExtent: "Mostrar opção para utilizar a extensão de mapa atual",
    showCredits: "Exibir a opção <b>Mostrar créditos</b>",
    saveAsFeatureService: "Salva o resultado na conta de usuário",
    showReadyToUseLayers: "Mostrar camadas prontas para uso de altas do mundo em tempo real do ArcGIS Online",
    toolNotAvailable: "Esta ferramenta não está disponível, pois o mapa não contém as camadas de feição exigidas.",
    aggregatePoints:"Agregar Pontos",
    aggregatePointsUsage:"Agrega os pontos em polígonos onde os pontos são localizados.",
    calculateDensity:"Calcular Densidade",
    calculateDensityUsage:"Cria um mapa de densidade a partir das feições de ponto ou linha ao espalhar quantidades conhecidas de algum fenômeno (representados como atributos de pontos ou linhas) ao longo do mapa.",
    connectOriginsToDestinations: "Conectar Origens aos Destinos",
    connectOriginsToDestinationsUsage: "Mede a distância ou tempo de percurso entre os pares de pontos.",
    createBuffers:"Criar Buffers",
    createBuffersUsage:"Cria polígonos de buffer a partir das feições de entrada.",
    createDriveTimeAreas:"Criar Áreas de Tempo do Percurso",
    createDriveTimeAreasUsage:"Cria polígonos de tempo do percurso (ou distância do percurso) ao redor dos pontos de entrada para os valores de tempo do percurso fornecidos.",
    createViewshed:"Criar Panorama",
    createViewshedUsage:"Cria áreas que são visíveis baseadas em locais que você especifica.",
    createWatersheds:"Criar Vertentes",
    createWatershedsUsage:"Cria áreas de captação baseadas em locais que você especifica.",
    deriveNewLocations:"Derivar Novos Locais",
    deriveNewLocationsUsage:"Deriva novas feições a partir das camadas de entrada que atenderem uma consulta que você especificar",
    dissolveBoundaries:"Dissolver Limites",
    dissolveBoundariesUsage:"Dissolve polígonos que sobrepõem ou compartilham um limite em comum.",
    enrichLayer:"Enriquecer Camada",
    enrichLayerUsage:"Enriquece feições de entrada com pessoas, lugares e fatos de negócios sobre áreas de proximidade.",
    extractData:"Extrair Dados",
    extractDataDesc:"Extrai dados de uma ou mais camadas dentro de uma extensão fornecida",
    findExistingLocations:"Encontrar Locais Existentes",
    findExistingLocationsUsage:"Seleciona feições na camada de entrada que atendem uma consulta de atributo e/ou espacial que você especificou",
    findHotSpots:"Localizar Valor Alto de Incidência",
    findHotSpotsUsage:"Localiza agrupamentos da feição de entrada estatísticamente significativos ou valores altos/baixos.",
    findNearest:"Localizar Mais Próximo",
    findNearestUsage:"Para cada feição em uma camada de entrada, localize sua feição mais próxima em outra camada",
    findSimilarLocations:"Encontrar Locais Semelhantes",
    findSimilarLocationsUsage:"Mede a semelhança de locais de candidatos para um ou mais locais de referência.",
    interpolatePoints:"Interpolar Pontos",
    interpolatePointsUsage:"Prevê valores em novos locais baseado em medidas de uma coleta de pontos.",
    mergeLayers:"Juntar Camadas",
    mergeLayersUsage:"Junta as feições de múltiplas camadas em uma nova camada",
    overlayLayers:"Sobrepor Camadas",
    overlayLayersUsage:"Combina múltiplas camadas em uma única camada com informações de camadas originais preservadas.",
    planRoutes:"Planejar Rotas",
    planRoutesUsage:"Determina como dividir eficazmente tarefas entre uma mão-de-obra móvel.",
    summarizeNearby:"Resumir Mais Próximo",
    summarizeNearbyUsage:"Para cada feição em uma camada de entrada, resuma os dados dentro de uma distância das feições em outra camada.",
    summarizeWithin:"Resumir Dentro",
    summarizeWithinUsage:"Para cada polígono em uma camada de polígono de entrada, resuma os dados localizados dentro dela a partir das feições em outra camada.",
    traceDownstream:"Traçar Jusante",
    traceDownstreamUsage:"Determina os caminhos de fluxo em uma direção da jusante a partir de locais que você especifica."
  })
);
