define({
  root: {
    showArcgisBasemaps: "Include Portal's basemaps",
    settings: "Settings",
    add: "Click to Add a New Basemap",
    edit: "Properties",
    title: "Title",
    titlePH: "Basemap Title",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click image to update",
    url: "URL",
    urlPH: "Layer URL",
    addlayer: "Add Basemap",
    actions: "Actions",
    warning: "Incorrect input",
    save: "Back and Save",
    back: "Back and Cancel",
    addUrl: "Add URL",
    autoCheck: "Auto Check",
    checking: "Checking...",
    ok: "OK",
    cancel: "Cancel",
    result: "Saved successfully",
    spError: "All basemaps added to the gallery require same spatial references.",
    invalidTitle1:"A basemap '",
    invalidTitle2:"' exists already. Please choose another title.",
    invalidBasemapUrl1: "This type of layer cannot be used as a basemap.",
    invalidBasemapUrl2: "Different spatial reference with current map.",
    addBaselayer: "Add Basemap Layer"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});