define(
   ({
    selectAnalysisTools:"Selectaţi instrumentele de analiză care vor fi enumerate în widget.",
    selected: "selectat",
    name: "Nume",
    graphicalDisplay:"Afişare grafică",
    usage: "Utilizare",
    toolNotAvailable: "Acest instrument nu este disponibil deoarece harta nu conţine straturile tematice necesare.",
    aggregatePoints:"Însumare puncte",
    aggregatePointsUsage:"Însumare puncte în poligoane acolo unde sunt localizate punctele.",
    aggregatePointsInputTip: "Specificaţi stratul tematic de obiecte spaţiale din puncte care va fi însumat în poligoane în stratul tematic de obiecte spaţiale din poligoane.",
    calculateDensity:"Calcul densitate",
    calculateDensityUsage:"Creaţi o hartă de densitate din obiecte spaţiale punctuale sau liniare, răspândind cantităţi cunoscute ale unui anumit fenomen (reprezentate ca atribute ale punctelor sau liniilor) în hartă.",
    calculateDensityInputTip:"Specificaţi obiectele spaţiale punctuale sau liniare din care se calculează densitatea.",
    connectOriginsToDestinations: "Conectare origini cu destinaţii",
    connectOriginsToDestinationsUsage: "Măsuraţi durata de călătorie sau distanţa dintre perechi de puncte.",
    connectOriginsToDestinationsInputTip: "Specificaţi punctul de pornire sau punctele rutelor care vor fi generate.",
    createBuffers:"Creare buffere",
    createBuffersUsage:"Creare poligoane buffer din obiecte spaţiale introduse.",
    createBuffersInputTip:"Specificaţi stratul tematic de obiecte spaţiale punctuale, liniare sau poligonale care va fi cuprins în buffer.",
    createDriveTimeAreas:"Creare suprafeţe pentru timpul de conducere",
    createDriveTimeAreasUsage:"Creaţi poligoane pentru timpul de condus (sau distanţa de condus) în jurul punctelor introduse pentru valorile date ale timpului de condus.",
    createDriveTimeAreasInputTip:"Specificaţi punctele în care vor fi trasate suprafeţele pentru timpul de condus.",
    createViewshed:"Creare rază vizuală",
    createViewshedUsage:"Creează zone care sunt vizibile în funcţie de locaţiile pe care le specificaţi.",
    createViewshedInputTip:"Specificaţi locaţiile observatorilor pentru a identifica suprafeţele vizibile.",
    createWatersheds:"Creare cumpene de ape",
    createWatershedsUsage:"Creează zone de captare în funcţie de locaţiile pe care le specificaţi.",
    createWatershedsInputTip:"Specificaţi obiectele spaţiale punctuale pentru calculul cumpenelor de ape.",
    deriveNewLocations:"Derivare locaţii noi",
    deriveNewLocationsUsage:"Derivaţi obiecte spaţiale noi din straturile tematice introduse care se potrivesc cu o interogare specificată",
    deriveNewLocationsInputTip:"Specificaţi stratul tematic de analiză care va fi utilizat ca intrare.",
    dissolveBoundaries:"Dizolvare graniţe",
    dissolveBoundariesUsage:"Dizolvaţi poligoanele care se suprapun sau au o graniţă comună.",
    dissolveBoundariesInputTip:"Specificaţi stratul tematic ce conţine obiecte spaţiale poligonale care va fi dizolvat.",
    enrichLayer:"Îmbogăţire strat tematic",
    enrichLayerUsage:"Îmbogăţiţi obiectele spaţiale introduse cu date despre persoane, locuri şi companii din zonele din apropiere.",
    enrichLayerInputTip:"Specificaţi obiectele spaţiale care vor fi îmbogăţite cu date noi.",
    extractData:"Extragere date",
    extractDataDesc:"Extrageţi date din unul sau mai multe straturi tematice într-o anumită măsură",
    extractDataInputTip:"Specificaţi stratul tematic de obiecte spaţiale introduse care va fi extras.",
    findExistingLocations:"Găsire locaţii existente",
    findExistingLocationsUsage:"Selectaţi obiecte spaţiale din stratul tematic introdus care se potrivesc cu un atribut şi/sau interogare spaţială specificată de dvs.",
    findExistingLocationsInputTip:"Specificaţi straturile tematice de analiză care vor fi utilizate ca intrare.",
    findHotSpots:"Găsire puncte de interes",
    findHotSpotsUsage:"Găsiţi grupări de obiecte spaţiale introduse sau valori ridicate/scăzute semnificative din punct de vedere statistic.",
    findHotSpotsInputTip:"Specificaţi obiectul spaţial punctual sau poligonal pentru care vor fi calculate punctele de interes.",
    findNearest:"Găsire cele mai apropiate",
    findNearestUsage:"Pentru fiecare obiect spaţial dintr-un strat tematic introdus, găsiţi cel mai apropiat obiect spaţial de pe un alt strat tematic",
    findNearestInputTip:"Specificaţi obiectele spaţiale punctuale, liniare sau poligonale pentru care se găsesc cele mai apropiate locaţii.",
    findSimilarLocations:"Găsire locaţii similare",
    findSimilarLocationsUsage:"Măsuraţi gradul de similaritate al locaţiilor candidate cu una sau mai multe locaţii de referinţă.",
    findSimilarLocationsInputTip:"Specificaţi un strat tematic de obiecte spaţiale care conţine una sau mai multe locaţii de referinţă faţă de care obiectele spaţiale din stratul tematic de căutare vor fi evaluate pentru a determina gradul de similaritate.",
    interpolatePoints:"Interpolare puncte",
    interpolatePointsUsage:"Preziceţi valori în locaţii noi pe baza măsurătorilor dintr-o colecţie de puncte.",
    interpolatePointsInputTip:"Specificaţi obiectele spaţiale punctuale care vor fi interpolate.",
    mergeLayers:"Unificare straturi tematice",
    mergeLayersUsage:"Unificaţi obiecte spaţiale din straturi tematice multiple într-un strat tematic nou",
    mergeLayersInputTip:"Specificaţi stratul tematic de obiecte spaţiale care va fi unificat cu stratul tematic destinat unificării.",
    overlayLayers:"Suprapunere straturi tematice",
    overlayLayersUsage:"Combinaţi straturi tematice multiple într-un singur strat tematic cu informaţii din straturile tematice originale conservate.",
    overlayLayersInputTip:"Specificaţi stratul tematic de obiecte spaţiale care va fi suprapus cu stratul tematic destinat suprapunerii.",
    planRoutes:"Planificare rute",
    planRoutesUsage:"Determinaţi modul de alocare eficientă a operaţiilor în cadrul unei forţe de muncă mobile.",
    planRoutesInputTip:"Specificaţi punctele prin care ar trebui să treacă vehiculele, şoferii sau rutele.",
    summarizeNearby:"Rezumat în apropiere",
    summarizeNearbyUsage:"Pentru fiecare obiect spaţial dintr-un strat tematic introdus, rezumaţi datele aflate la o anumită distanţă de obiectele spaţiale din alt strat tematic.",
    summarizeNearbyInputTip:"Specificaţi stratul tematic cu obiecte spaţiale punctuale, liniare sau poligonale de la care vor fi măsurate distanţele către obiectele spaţiale din stratul tematic de rezumare.",
    summarizeWithin:"Rezumat în",
    summarizeWithinUsage:"Pentru fiecare poligon dintr-un strat tematic cu poligoane, rezumaţi datele aflate la distanţa specificată de obiectele spaţiale dintr-un alt strat tematic.",
    summarizeWithinInputTip:"Specificaţi stratul tematic de obiecte spaţiale poligonale către care se va face rezumarea.",
    traceDownstream:"Urmărire în aval",
    traceDownstreamUsage:"Determinaţi căile de curgere în aval din locaţiile specificate de dvs.",
    traceDownstreamInputTip:"Specificaţi obiectele spaţiale punctuale utilizate pentru locaţia de pornire a unei urmăriri în aval."
  })
);
