define(
   ({
    selectAnalysisTools:"Selectaţi instrumentul de analiză care va fi utilizat în widget.",
    selected: "selectat",
    name: "Nume",
    graphicalDisplay:"Afişare grafică",
    usage: "Utilizare",
    settings: "Setări",
    toolSetting: "Setare detalii instrumente",
    toolLabel: "Setare nume afişat instrument",
    showHelpTip: "Afişare linkuri ajutor în widget",
    showCurrentMapExtent: "Afişare opţiune de utilizat pe extinderea curentă de hartă",
    showCredits: "Afişare opţiune <b>Afişare credite</b>",
    saveAsFeatureService: "Salvare rezultat în contul utilizatorului",
    showReadyToUseLayers: "Afişare straturi tematice gata de utilizat din atlasul actualizat al lumii din ArcGIS Online",
    toolNotAvailable: "Acest instrument nu este disponibil deoarece harta nu conţine straturile tematice necesare.",
    aggregatePoints:"Însumare puncte",
    aggregatePointsUsage:"Însumare puncte în poligoane acolo unde sunt localizate punctele.",
    calculateDensity:"Calcul densitate",
    calculateDensityUsage:"Creaţi o hartă de densitate din obiecte spaţiale punctuale sau liniare, răspândind cantităţi cunoscute ale unui anumit fenomen (reprezentate ca atribute ale punctelor sau liniilor) în hartă.",
    connectOriginsToDestinations: "Conectare origini cu destinaţii",
    connectOriginsToDestinationsUsage: "Măsuraţi durata de călătorie sau distanţa dintre perechi de puncte.",
    createBuffers:"Creare buffere",
    createBuffersUsage:"Creare poligoane buffer din obiecte spaţiale introduse.",
    createDriveTimeAreas:"Creare suprafeţe pentru timpul de conducere",
    createDriveTimeAreasUsage:"Creaţi poligoane pentru timpul de condus (sau distanţa de condus) în jurul punctelor introduse pentru valorile date ale timpului de condus.",
    createViewshed:"Creare rază vizuală",
    createViewshedUsage:"Creează zone care sunt vizibile în funcţie de locaţiile pe care le specificaţi.",
    createWatersheds:"Creare cumpene de ape",
    createWatershedsUsage:"Creează zone de captare în funcţie de locaţiile pe care le specificaţi.",
    deriveNewLocations:"Derivare locaţii noi",
    deriveNewLocationsUsage:"Derivaţi obiecte spaţiale noi din straturile tematice introduse care se potrivesc cu o interogare specificată",
    dissolveBoundaries:"Dizolvare graniţe",
    dissolveBoundariesUsage:"Dizolvaţi poligoanele care se suprapun sau au o graniţă comună.",
    enrichLayer:"Îmbogăţire strat tematic",
    enrichLayerUsage:"Îmbogăţiţi obiectele spaţiale introduse cu date despre persoane, locuri şi companii din zonele din apropiere.",
    extractData:"Extragere date",
    extractDataDesc:"Extrageţi date din unul sau mai multe straturi tematice într-o anumită măsură",
    findExistingLocations:"Găsire locaţii existente",
    findExistingLocationsUsage:"Selectaţi obiecte spaţiale din stratul tematic introdus care se potrivesc cu un atribut şi/sau interogare spaţială specificată de dvs.",
    findHotSpots:"Găsire puncte de interes",
    findHotSpotsUsage:"Găsiţi grupări de obiecte spaţiale introduse sau valori ridicate/scăzute semnificative din punct de vedere statistic.",
    findNearest:"Găsire cele mai apropiate",
    findNearestUsage:"Pentru fiecare obiect spaţial dintr-un strat tematic introdus, găsiţi cel mai apropiat obiect spaţial de pe un alt strat tematic",
    findSimilarLocations:"Găsire locaţii similare",
    findSimilarLocationsUsage:"Măsuraţi gradul de similaritate al locaţiilor candidate cu una sau mai multe locaţii de referinţă.",
    interpolatePoints:"Interpolare puncte",
    interpolatePointsUsage:"Preziceţi valori în locaţii noi pe baza măsurătorilor dintr-o colecţie de puncte.",
    mergeLayers:"Unificare straturi tematice",
    mergeLayersUsage:"Unificaţi obiecte spaţiale din straturi tematice multiple într-un strat tematic nou",
    overlayLayers:"Suprapunere straturi tematice",
    overlayLayersUsage:"Combinaţi straturi tematice multiple într-un singur strat tematic cu informaţii din straturile tematice originale conservate.",
    planRoutes:"Planificare rute",
    planRoutesUsage:"Determinaţi modul de alocare eficientă a operaţiilor în cadrul unei forţe de muncă mobile.",
    summarizeNearby:"Rezumat în apropiere",
    summarizeNearbyUsage:"Pentru fiecare obiect spaţial dintr-un strat tematic introdus, rezumaţi datele aflate la o anumită distanţă de obiectele spaţiale din alt strat tematic.",
    summarizeWithin:"Rezumat în",
    summarizeWithinUsage:"Pentru fiecare poligon dintr-un strat tematic cu poligoane, rezumaţi datele aflate la distanţa specificată de obiectele spaţiale dintr-un alt strat tematic.",
    traceDownstream:"Urmărire în aval",
    traceDownstreamUsage:"Determinaţi căile de curgere în aval din locaţiile specificate de dvs."
  })
);
