define(
   ({
    taskUrl: "タスク URL",
    serviceURLPlaceholder: "ジオプロセシング タスク URL を入力してください",
    ok: "OK",
    cancel: "キャンセル",
    layer: "レイヤー",
    action: "対応",
    input: "入力",
    output: "出力",
    name: "名前",
    type: "タイプ",
    required: "必須",
    layerOrder: "レイヤーの順序",
    options: "オプション",
    defaultValue: "デフォルト値",
    inputFeatureBy: "フィーチャの入力方法:",
    renderer: "レンダリング",
    displayType: "表示タイプ",
    label: "ラベル",
    tooltip: "ツールチップ",
    visible: "表示",
    helpUrl: "ヘルプ URL",
    useResultMapService: "結果マップ サービスの描画オプションを使用",
    drawOnMap: "マップ上での対話的な描画",
    selectLayer: "マップからレイヤーを選択",
    url: "URL",
    symbol: "シンボル",
    shareResults: "操作レイヤーとして結果を追加",
    popup: "ポップアップ",
    setTask: "設定",
    setTaskTitle: "ジオプロセシング タスクの設定",
    enablePopup: "ポップアップの有効化",
    unSupportGeometryType: "ジオメトリ タイプが不明なため、レンダラーを設定できません。",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "ファイルのアップロード",
    selectFileToUpload: "ファイルの選択...",
    upload: "アップロード",
    rasterFormat: "ラスター データ形式",
    noFileSelected: "ファイルが選択されませんでした。",
    uploadSuccess:"ファイルが正常にアップロードされました。",
    showLayerContent: "レイヤー コンテンツの表示",
    Feet: "フィート",
    Yards: "ヤード",
    Miles: "マイル",
    NauticalMiles: "海里",
    Meter: "メートル",
    Kilometers: "キロメートル",
    urlPlaceholder: "フィーチャ セット URL",
    allowToExport: "結果のエクスポートを許可"
  })
);
