define(
   ({
    _widgetLabel: "Consapevolezza situazionale (Beta)",
    locate_incident: "Individua incidente",
    clear_incidents: "Cancella incidenti",
    reverse_geocoded_address: "Indirizzo più vicino",
    reverse_geocoded_error: "Non disponibile",
    miles: "Miglia",
    kilometers: "Chilometri",
    feet: "Piede",
    meters: "Metri",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    now: "ORA",
    wind: "VENTO",
    SUN: "DOM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MER",
    THU: "GIO",
    FRI: "VEN",
    SAT: "SAB",
    defaultTabMsg: "Nessun incidente identificato.",
    actionLabel: "Imposta come incidente",
    drawPoint: "Disegna punto",
    drawLine: "Disegna linea",
    drawPolygon: "Disegna poligono",
    saveIncident: "Salva incidente",
    clearIncident: "Cancella incidente",
    useMapExtent: "Usa estensione mappa corrente",
    noFeaturesFound: "Nessuna feature trovata.",
    downloadCSV: "SCARICA CSV",
    editComplete: "Feature salvata",
    updateComplete: "Feature aggiornata",
    deleteComplete: "Feature eliminata",
    sum: "SOMMA",
    min: "MIN",
    max: "MAX",
    avg: "MEDIA",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH",
    notPolySave: "Specificare una distanza di buffer prima del salvataggio.",
    update_btn: "Aggiorna",
    delete_btn: "Elimina"
  })
);
