define(
	 ({
		queries: "쿼리 작업",
		addNew: "새로 추가",
		setSource: "설정",
		setDataSource: "데이터 원본 설정",
		name: "이름",
		querySource: "데이터 원본",
		queryName: "작업 이름",
		queryDefinition: "필터 정의",
		resultsSetting: "결과 설정",
		symbolSetting: "심볼 설정",
		resultSettingTip: "출력 결과에 표시할 것과 표시 방법을 정의합니다.",
		resultItemTitle: "결과 항목 제목",
		resultItemContent: "결과 항목 콘텐츠",
		fieldsSetTip: "표시할 필드를 선택합니다. 별칭을 업데이트하고, 순서를 정하고, 형식을 지정할 필드를 선택하세요.",
		addField: "필드 추가",
		visibility: "가시성",
		alias: "별칭",
		specialType: "특별 유형",
		actions: "작업",
		none: "없음",
		link: "링크",
		image: "이미지",
		noField: "필드 없음",
		operationalLayerTip: "결과를 운영 레이어로 추가",
		setLayerSymbolTip: "쿼리 결과에 대한 심볼 설정: ",
		setSelectedSymbolTip: "선택한 피처의 심볼을 설정합니다.",
		notUseFilter: "필터 사용 안 함",
		setSourceTip: "쿼리 원본을 설정하세요.",
		setFilterTip: "필터를 올바르게 설정하세요.",
		ok: "확인",
		cancel: "취소",
		noFilterTip: "필터 식이 정의되지 않으면 이 쿼리 작업은 지정된 데이터 원본의 모든 피처를 나열합니다."
  })
);