define(
	 ({
		queries: "쿼리 작업",
		addNew: "새로 추가",
    queryLayer: "쿼리 레이어",
		setSource: "설정",
		setDataSource: "데이터 원본 설정",
		name: "이름",
		querySource: "데이터 원본",
		queryName: "작업 이름",
		queryDefinition: "필터 정의",
		resultsSetting: "결과 설정",
		symbolSetting: "심볼 설정",
		resultSettingTip: "출력 결과에 표시할 것과 표시 방법을 정의합니다.",
		resultItemTitle: "결과 항목 제목",
		resultItemContent: "결과 항목 콘텐츠",
		fieldsSetTip: "표시할 필드를 선택합니다. 별칭을 업데이트하고, 순서를 정하고, 형식을 지정할 필드를 선택하세요.",
		addField: "필드 추가",
		visibility: "가시성",
		alias: "별칭",
		specialType: "특별 유형",
		actions: "작업",
		none: "없음",
		link: "링크",
		image: "이미지",
		noField: "필드 없음",
		operationalLayerTip: "결과를 운영 레이어로 추가",
		setLayerSymbolTip: "쿼리 결과에 대한 심볼 설정: ",
		setSelectedSymbolTip: "선택한 피처의 심볼을 설정합니다.",
		notUseFilter: "필터 사용 안 함",
		setSourceTip: "쿼리 원본을 설정하세요.",
		setFilterTip: "필터를 올바르게 설정하세요.",
		ok: "확인",
		cancel: "취소",
		noFilterTip: "필터 식이 정의되지 않으면 이 쿼리 작업은 지정된 데이터 원본의 모든 피처를 나열합니다.",
    relationships: "릴레이션십",
    addRelationshipLayer: "새 릴레이션쉽 추가",
    relatedTo: "릴레이트됨",
    selectOption: "선택하세요.",
    resultItemSorting: "결과 항목 정렬",
    field: "필드",
    sortingOrder: "순서",
    configureFieldsTip: "쿼리 결과가 정렬될 필드를 구성하세요.",
    setSortingFields: "정렬 필드 설정",
    ascending: "오름차순",
    descending: "내림차순",
    sortBy: "정렬 기준",
    thenBy: "다음 기준",
    addTask: "태스크 추가",
    noTasksTip: '태스크가 없습니다. \"${addTask}\"을(를) 클릭하여 시작하세요.',
    infoText: "정보",
    filters: "필터",
    results: "결과",
    optionsText: "옵션",
    summaryText: "요약",
    attributeFilter: "속성 필터",
    attributeFilterTip: "쿼리 레이어를 필터링하는 위젯에서 사용하기 위해 속성 식을 정의합니다.",
    noExpressionDefinedTip: "정의된 식이 없습니다.",
    needInputValuesTip: "런타임 시 입력 값 필요",
    setExpressions: "식 설정",
    spatialFilter: "공간 필터",
    spatialFilterTip: "결과를 제한하는 위젯에 사용되는 공간 필터를 선택합니다.",
    defaultOption: "기본값",
    useCurrentExtentTip: "현재 맵 범위 내 일부 또는 전체",
    useDrawGraphicTip: "맵에 그려진 모양 내 일부 또는 전체",
    useFeaturesTip: "다른 레이어의 피처로부터의 상대적인 위치를 기반으로 함",
    noSpatialLimitTip: "결과를 공간적으로 제한하지 않음",
    drawingTools: "그리기 도구",
    bufferSettings: "버퍼 설정",
    defaultDistance: "기본 거리",
    bufferDistance: "버퍼 거리",
    defaultUnit: "기본 단위",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    availableSpatialRelationships: "사용 가능한 공간 릴레이션십",
    setSpatialRelationships: "공간 릴레이션십 설정",
    availability: "사용 가능 여부",
    relationship: "릴레이션십",
    label: "레이블",
    intersect: "교차",
    contain: "포함",
    areContainedIn: "은(는) 다음에 포함됨:",
    cross: "건너감",
    envelopeIntersect: "엔빌롭 교차",
    overlap: "겹치기",
    areOverlapped: "이(가) 겹침",
    touche: "접함",
    within: "내",
    areWithin: "이(가) 다음 내에 있음:",
    indexIntersect: "색인 교차",
    itemTitle: "항목 제목",
    displayFields: "디스플레이 필드",
    sortingFields: "정렬 필드",
    setDisplayFields: "디스플레이 필드 설정",
    symbol: "심볼",
    setSymbol: "심볼 설정",
    serviceSymbolTip: "레이어가 정의한 심볼 사용",
    exportTip: "내보내기 버튼 보기",
    keepResultsTip: "위젯이 닫힌 후에 맵에 결과 보기 유지",
    queryRelatedRecords: "쿼리 관련 레코드",
    createLayerForTaskTip: "태스크가 레이어를 생성하는 방법 지정",
    oneLayerForTaskTip: "이 태스크에 레이어 하나만 생성",
    multipleLayerForTaskTip: "이 태스크가 실행될 때마다 새 레이어 생성"
  })
);
