define(
   ({
    "tabs_section_Label": "علامات تبويب",
    "addTab": "إضافة جدول...",
    "layerName": "الطبقة",
    "layerType": "نوع عملية التحليل",
    "layerLabel": "التسمية",
    "actions": "إجراءات",
    "closest": "أقرب معلم",
    "proximity": "المقاربة",
    "summary": "الملخص",
    "select_lbl": "-- تحديد --",
    "general_setting_Label": "إعدادات عامة",
    "units_text_lbl": "وحدات المسافة",
    "miles": "ميل",
    "kilometers": "كيلومترات",
    "feet": "قدم",
    "meters": "متر",
    "yards": "ياردة",
    "nauticalMiles": "الأميال البحرية",
    "maximum_distance_lbl": "المسافة القصوى لأقرب معلم",
    "buffer_text_lbl": "تسمية النطاق",
    "buffer_lbl": "مسافة النطاق",
    "buffer_max_lbl": "مسافة النطاق القصوى",
    "buffer_min_lbl": "مسافة النطاق الدُنيا",
    "routing_checkBox": "تمكين التوجيه",
    "weather_Label": "خيارات الطقس",
    "weather_checkBox": "تضمين معلومات الطقس",
    "selectLayers": "تحديد طبقات الطقس",
    "currentlySelectedLayer": "طبقات الطقس المُحددة حاليًا",
    "missingTabLabel": "تفقد على الأقل علامة تبويب واحدة تسميتها",
    "cancel": "إلغاء الأمر",
    "ok": "موافق",
    "missingLayerInWebMap": "لا توجد طبقات تشغيلية",
    "selectFields": "Select Fields",
    "addField": "إضافة حقل",
    "sum": "مجموع",
    "min": "الحد الأدنى",
    "max": "MAX",
    "avg": "المعدل",
    "count": "عدد",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "عرض التعداد",
    "area_checkBox": "عرض المنطقة",
    "length_checkBox": "عرض الطول",
    "max_records": "تم الوصول إلى الحد الأقصى",
    "save_label": "خيارات الحفظ",
    "save_checkbox": "تمكين الحفظ",
    "csv_label": "خيارات CSV",
    "csv_checkbox": "تصدير كل الحقول في الطبقة.",
    "display_label": "خيارات العرض",
    "display_checkbox": "عرض مميزات الملخص",
    "must_select_template": "يرجى تحديد أحد قوالب التحرير في خيارات الحفظ."
  })
);
