define(
   ({
    "tabs_section_Label": "karta",
    "addTab": "Dodaj kartę",
    "layerName": "Warstwa",
    "layerType": "Rodzaj analizy",
    "layerLabel": "Label",
    "actions": "Działania",
    "closest": "Najbliższy obiekt",
    "proximity": "Bliskość",
    "summary": "Summary",
    "select_lbl": "-- Wybierz --",
    "general_setting_Label": "Ustawienia ogólne",
    "units_text_lbl": "Jednostki odległości",
    "miles": "Mile",
    "kilometers": "Kilometry",
    "feet": "Stopy",
    "meters": "Metry",
    "yards": "Jardy",
    "nauticalMiles": "Mile morskie",
    "maximum_distance_lbl": "Odległość maksymalna najbliższego obiektu",
    "buffer_text_lbl": "Etykieta buforowania",
    "buffer_lbl": "Odległość buforowania",
    "buffer_max_lbl": "Maksymalna odległość buforowania",
    "buffer_min_lbl": "Minimalna odległość buforowania",
    "routing_checkBox": "Włącz wyznaczanie tras",
    "weather_Label": "Opcje pogodowe",
    "weather_checkBox": "Dołącz informacje pogodowe",
    "selectLayers": "Wybierz warstwy pogodowe",
    "currentlySelectedLayer": "Aktualnie wybrane warstwy pogodowe",
    "missingTabLabel": "Brak etykiety w przynajmniej jednej zakładce",
    "cancel": "Anuluj",
    "ok": "OK",
    "missingLayerInWebMap": "Nie znaleziono warstw operacyjnych.",
    "selectFields": "Wybierz pola",
    "addField": "Dodaj pole",
    "sum": "SUMA",
    "min": "MIN.",
    "max": "MAKS.",
    "avg": "ŚRED.",
    "count": "LICZBA",
    "area": "POWIERZCHNIA",
    "length": "DŁUGOŚĆ",
    "count_checkBox": "Wyświetl liczbę obiektów",
    "area_checkBox": "Wyświetl powierzchnię",
    "length_checkBox": "Wyświetl długość",
    "max_records": "Osiągnięto limit maksymalny"
  })
);
