define(
   ({
    _widgetLabel: "統計圖",
    executeChartTip: "按一下以下其中一個任務項目執行統計圖。",
    invalidConfig: "無效的配置。",
    noneChartTip: "未針對此 widget 配置圖表任務。",
    chartParams: "選項",
    charts: "統計圖",
    apply: "套用",
    useSpatialFilter: "使用空間篩選器限制圖徵",
    useCurrentMapExtent: "僅與目前地圖區域相交的圖徵",
    drawGraphicOnMap: "僅與使用者自訂區域相交的圖徵",
    chartResults: "統計圖結果",
    clearResults: "清除結果",
    noPermissionsMsg: "您沒有存取此服務的權限。",
    specifySpatialFilterMsg: "請為此任務指定空間篩選器。",
    queryError: "查詢失敗。",
    noResults: "未找到任何圖徵。",
    category: "類別",
    count: "計數",
    label: "標籤",
    horizontalAxis: "水平軸",
    verticalAxis: "垂直軸",
    dataLabels: "資料標籤",
    color: "顏色",
    colorful: "彩色",
    monochromatic: "單色",
    tasks: "任務",
    results: "結果",
    applySpatialFilterToLimitResults: "套用空間篩選器以限制結果",
    useCurrentExtentTip: "部分或全部位於目前的地圖範圍內",
    useDrawGraphicTip: "部分或全部位於地圖上繪製的形狀內",
    useFeaturesTip: "根據其與另一個圖層中圖徵的相對位置",
    noSpatialLimitTip: "不限制空間結果",
    applySearchDistance: "套用搜尋距離",
    spatialRelationship: "空間關係",
    relatedLayer: "相關圖層",
    clear: "清除",
    bufferDistance: "緩衝距離",
    miles: "英里",
    kilometers: "公里",
    feet: "英呎",
    meters: "公尺",
    yards: "碼",
    nauticalMiles: "海浬",
    back: "返回",
    execute: "執行"
  })
);