define(
   ({
    taskUrl: "Görev URL\'si",
    serviceURLPlaceholder: "Coğrafi İşleme görevi URL\'si girin",
    ok: "Tamam",
    cancel: "İptal",
    layer: "Katman",
    action: "İşlem",
    input: "Girdi",
    output: "Çıktı",
    name: "Ad",
    type: "Tür",
    required: "Gerekli",
    layerOrder: "Katman sırası",
    options: "Seçenekler",
    defaultValue: "Varsayılan Değer",
    inputFeatureBy: "Detay girme ölçütü",
    renderer: "Canlandırıcı",
    displayType: "Görüntüleme türü",
    label: "Etiket",
    tooltip: "Araç ipucu",
    visible: "Görünür",
    helpUrl: "Yardım URL\'si",
    useResultMapService: "Sonuç haritası servisinin çizim seçeneklerini kullan",
    drawOnMap: "Haritada etkileşimli olarak çizme",
    selectLayer: "Haritadan katman seçme",
    url: "URL",
    symbol: "Sembol",
    shareResults: "Sonucu işlem katmanı olarak ekle",
    popup: "Açılır Menü",
    setTask: "Ayarla",
    setTaskTitle: "GP Görevi Belirle",
    enablePopup: "Açılan pencereyi etkinleştir"
  })
);