define(
   ({
    taskUrl: "Görev URL\'si",
    serviceURLPlaceholder: "Coğrafi İşleme görevi URL\'si girin",
    ok: "Tamam",
    cancel: "İptal",
    layer: "Katman",
    action: "İşlem",
    input: "Girdi",
    output: "Çıktı",
    name: "Ad",
    type: "Tür",
    required: "Gerekli",
    layerOrder: "Katman sırası",
    options: "Seçenekler",
    defaultValue: "Varsayılan Değer",
    inputFeatureBy: "Detay girme ölçütü",
    renderer: "Canlandırıcı",
    displayType: "Görüntüleme türü",
    label: "Etiket",
    tooltip: "Araç ipucu",
    visible: "Görünür",
    helpUrl: "Yardım URL\'si",
    useResultMapService: "Sonuç haritası servisinin çizim seçeneklerini kullan",
    drawOnMap: "Haritada etkileşimli olarak çizme",
    selectLayer: "Haritadan katman seçme",
    url: "URL",
    symbol: "Sembol",
    shareResults: "Sonucu işlem katmanı olarak ekle",
    popup: "Açılır Menü",
    setTask: "Ayarla",
    setTaskTitle: "GP Görevi Belirle",
    enablePopup: "Açılan pencereyi etkinleştir",
    unSupportGeometryType: "Bilinmeyen geometri türü nedeniyle işleyici ayarlanamıyor.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Dosya yükle",
    selectFileToUpload: "Dosya seç...",
    upload: "Yükle",
    rasterFormat: "Raster veri formatı",
    noFileSelected: "Dosya seçilmedi!",
    uploadSuccess:"Dosya başarıyla yüklendi!",
    showLayerContent: "Katman içeriğini göster",
    Feet: "Fit",
    Yards: "Yarda",
    Miles: "Mil",
    NauticalMiles: "Deniz Mili",
    Meter: "Metre",
    Kilometers: "Kilometre",
    urlPlaceholder: "detay kümesi URL\'si",
    allowToExport: "Sonuçları aktarmaya izin ver"
  })
);
