define(
   ({
    selectAnalysisTools:"Vali analüüsitööriistad vidinas kasutamiseks.",
    selected: "valitud",
    name: "Nimi",
    graphicalDisplay:"Graafiline kuva",
    usage: "Kasutus",
    settings: "Seaded",
    toolSetting: "Seadista tööriista detailid",
    toolLabel: "Tööriista kuvanimi",
    showHelpTip: "Näita vidinas spikri linke",
    showCurrentMapExtent: "Näita praeguse kaardi kuvaulatuse sätet",
    showCredits: "Kuvamine<b>Näita krediite</b> suvand",
    saveAsFeatureService: "Salvesta tulemus kasutajâ€™a kontos",
    showReadyToUseLayers: "Näita kasutusvalmidusega kihte ArcGIS Online elukoha atlases",
    toolNotAvailable: "See tööriist pole saadaval, kuna kaart ei sisalda nõutavaid objektikihte.",
    aggregatePoints:"Agregeeri punktid",
    aggregatePointsUsage:"Agregeeri punktid polügoonideks, kus punktid asuvad.",
    calculateDensity:"Arvuta tihedus",
    calculateDensityUsage:"Punkt- või joonobjektidest tiheduskaardi loomiseks saate hajutada mõne nähtuse teadaolevad hulgad (esitatud punktide või joonte atribuutidena) üle kogu kaardi.",
    connectOriginsToDestinations: "Ühenda algpunktid sihtpunktidega",
    connectOriginsToDestinationsUsage: "Saate mõõta reisiaja või vahemaa punktipaaride vahel.",
    createBuffers:"Loo puhvrid",
    createBuffersUsage:"Saate sisendobjektide põhjal luua puhveralad.",
    createDriveTimeAreas:"Loo sõiduaja pinnad",
    createDriveTimeAreasUsage:"Saate etteantud sõiduaja väärtuste põhjal luua sisendpunktide ümber sõiduaja (või sõiduvahemaa) pinnad.",
    createViewshed:"Loo vaateväli",
    createViewshedUsage:"Loob alad, mis on teie määratud asukohtadest nähtavad.",
    createWatersheds:"Loo valgalad",
    createWatershedsUsage:"Loob Teie määratud asukohtadel põhinevad valgalad.",
    deriveNewLocations:"Tuleta uued asukohad",
    deriveNewLocationsUsage:"Saate tuletada uued objektid sisendkihtide põhjal, mis vastavad Teie määratud päringule.",
    dissolveBoundaries:"Sulanda piirid",
    dissolveBoundariesUsage:"Saate sulandada polügoonid, mis omavahel kattuvad või millel on ühine piir.",
    enrichLayer:"Rikasta kihti",
    enrichLayerUsage:"Saate sisendobjekte rikastada teabega lähedalasuvate alade ettevõtete, kohtade ja inimeste kohta.",
    extractData:"Andmete väljavõte",
    extractDataDesc:"Saate andmed ekstraktida ühest või mitmest teatud kindlas ulatuses asuvast kihist.",
    findExistingLocations:"Leia olemasolevad asukohad",
    findExistingLocationsUsage:"Saate sisendkihis valida objektid, mis vastavad Teie määratud atribuudi- ja/või ruumilisele päringule.",
    findHotSpots:"Leia tulipunktid",
    findHotSpotsUsage:"Saate otsida sisendobjektide või suurte/väikeste väärtuste statistiliselt olulisi klastreid.",
    findNearest:"Leia lähim",
    findNearestUsage:"Iga sisendkihil asuva objekti jaoks leitakse talle lähim objekt mõnel teisel kihil.",
    findSimilarLocations:"Leia sarnased asukohad",
    findSimilarLocationsUsage:"Saate mõõta kandidaatasukohtade sarnasust ühe või mitme viiteasukohaga.",
    interpolatePoints:"Interpoleeri punktid",
    interpolatePointsUsage:"Saate prognoosida uute asukohtade väärtusi punktikogumike mõõtmiste põhjal.",
    mergeLayers:"Ühenda kihid",
    mergeLayersUsage:"Saate mitme kihi objektid üheks uueks kihiks ühendada",
    overlayLayers:"Kattuvad kihid",
    overlayLayersUsage:"Saate mitu kihti ühendada üheks kihiks nii, et algsete kihtide teave jääb alles.",
    planRoutes:"Kavanda marsruudid",
    planRoutesUsage:"Saate määratleda, kuidas ülesanded välitöötajate vahel efektiivselt jagada.",
    summarizeNearby:"Summeeri ligidusest",
    summarizeNearbyUsage:"Iga sisendkihil asuva objekti jaoks saate summeerida andmed, mis asuvad mõnel teisel kihil objektidest teatud raadiuses.",
    summarizeWithin:"Summeeri piirides",
    summarizeWithinUsage:"Iga sisendpolügoonkihil asuva polügooni jaoks saate summeerida andmed, mis asuvad mõnel teisel kihil objektidest selles raadiuses.",
    traceDownstream:"Allavoolu jälitus",
    traceDownstreamUsage:"Aitab määratleda voolusuuna Teie määratud asukohtades allavoolu suunas."
  })
);
