define(
   ({
    _widgetLabel: "Geoprocessamento",
    execute: "Executar",
    help: "Ajuda",
    input: "Entrada",
    output: "Saída",
    executing: "Executando",
    requiredInfo: "é exigido.",
    drawnOnMap: "O resultado está desenhado no mapa.",
    clear: "Limpar",
    error: "Erro",
    noToolConfig: "Nenhuma tarefa de geoprocessamento pré-configurada disponível.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Carregar arquivo",
    selectFileToUpload: 'Selecionar arquivo...',
    upload: 'Fazer Upload',
    rasterFormat: 'Formato de dados raster',
    noFileSelected: 'Nenhum arquivo selecionado!',
    uploadSuccess:'Arquivo carregado com sucesso!',
    url: "URL",
    showLayerContent: "Mostrar conteúdo da camada",
    invalidUrl: "Url de serviço da feição inválido",
    Feet: "Pés",
    Yards: "Jardas",
    Miles: "Milhas",
    NauticalMiles: "Milhas Náuticas",
    Meter: "Metros",
    Kilometers: "Quilômetros",
    urlPlaceholder: "URL de conjunto da feição"
  })
);
