define(
   ({
    layerSelect: "选择影像图层",
    displayMeasureResultInPopup: "在弹出窗口中显示测量结果",
    angularUnitSelect: "默认角度单位",
    linearUnitSelect: "默认线性单位",
    areaUnitSelect: "默认面积单位",
    displayOperationSelect: "选择测量操作",
    errorSectionMeasage: "图层均不支持测量功能",
    unitLabel: {
      esriInches: "英寸",
      esriFeet: "英尺",
      esriYards: "码",
      esriMiles: "英里",
      esriNauticalMiles: "海里",
      esriMillimeters: "毫米",
      esriCentimeters: "厘米",
      esriDecimeters: "公寸",
      esriMeters: "米",
      esriKilometers: "公里",
      esriDURadians: "弧度",
      esriDUDecimalDegrees: "度",
      esriSquareInches: "平方英寸",
      esriSquareFeet: "平方英尺",
      esriSquareYards: "平方码",
      esriAcres: "英亩",
      esriSquareMiles: "平方英里",
      esriSquareMillimeters: "平方毫米",
      esriSquareCentimeters: "平方厘米",
      esriSquareDecimeters: "平方分米",
      esriSquareMeters: "平方米",
      esriAres: "公亩",
      esriHectares: "公顷",
      esriSquareKilometers: "平方千米"
    },
    operationLabel: {
      esriMensurationPoint: "磅",
      esriMensurationDistanceAndAngle: "距离和角度",
      esriMensurationAreaAndPerimeter: "面积和周长",
      esriMensurationHeightFromBaseAndTop: "底部至顶层",
      esriMensurationHeightFromBaseAndTopShadow: "底部至顶部阴影",
      esriMensurationHeightFromTopAndTopShadow: "顶部至顶部阴影",
      esriMensurationCentroid: "质心",
      esriMensurationPoint3D: "点(3D)",
      esriMensurationDistanceAndAngle3D: "距离和角度(3D)",
      esriMensurationAreaAndPerimeter3D: "面积和周长(3D)",
      esriMensurationCentroid3D: "质心(3D)"
    }
  })
);