define(
   ({
    taskUrl: "Adres URL zadania",
    serviceURLPlaceholder: "Wprowadź adres URL zadania geoprzetwarzania",
    ok: "OK",
    cancel: "Anuluj",
    layer: "Warstwa",
    action: "Operacja",
    input: "Dane wejściowe",
    output: "Dane wynikowe",
    name: "Nazwa",
    type: "Typ",
    required: "Wymagane",
    layerOrder: "Kolejność warstw",
    options: "Opcje",
    defaultValue: "Wartość domyślna",
    inputFeatureBy: "Wprowadź obiekt poprzez",
    renderer: "Moduł renderowania",
    displayType: "Typ wyświetlania",
    label: "Etykieta",
    tooltip: "Etykieta narzędzia",
    visible: "Widoczne",
    helpUrl: "Adres URL Pomocy",
    useResultMapService: "Użyj opcji wyświetlania wynikowej usługi mapowej",
    drawOnMap: "Interaktywne wyświetlanie na mapie",
    selectLayer: "Wybór warstwy mapy",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Dodaj wynik jako warstwę operacyjną",
    popup: "Okno podręczne",
    setTask: "Ustaw",
    setTaskTitle: "Ustaw zadanie geoprzetwarzania",
    enablePopup: "Włącz okno podręczne",
    unSupportGeometryType: "Nie można skonfigurować modułu renderowania geometrii nieznanego typu.",
    useUrlForGPInput: "Adres URL",
    useUploadForGPInput: "Wczytaj plik",
    selectFileToUpload: "Wybierz plik...",
    upload: "Prześlij",
    rasterFormat: "Format danych wynikowych",
    noFileSelected: "Nie wybrano pliku!",
    uploadSuccess:"Pomyślnie przesłano plik!",
    showLayerContent: "Wyświetl zawartość warstwy",
    Feet: "Stopy",
    Yards: "Jardy",
    Miles: "Mile",
    NauticalMiles: "Mile morskie",
    Meter: "Metry",
    Kilometers: "Kilometry",
    urlPlaceholder: "adres URL zestawów obiektów",
    allowToExport: "Udostępnij wyniki do eksportowania"
  })
);
