define(
	 ({
		queries: "Forespørgselsopgaver",
		addNew: "Tilføj ny",
		setSource: "Indstil",
		setDataSource: "Angiv datakilde",
		name: "Navn",
		querySource: "Datakilde",
		queryName: "Navn på opgave",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Indstilling for resultat",
		symbolSetting: "Indstilling for symbol",
		resultSettingTip: "Angiv, hvad og hvordan output-resultaterne skal vise.",
		resultItemTitle: "Resultatobjektets titel",
		resultItemContent: "Resultatobjektets indhold",
		fieldsSetTip: "Markér de felter, der skal vises. Markér et felt for at opdatere dets alias, sortere og formatere.",
		addField: "Tilføj felt",
		visibility: "Synlighed",
		alias: "Alias",
		specialType: "Speciel type",
		actions: "Handlinger",
		none: "Ingen",
		link: "Link",
		image: "Billede",
		noField: "Intet felt",
		operationalLayerTip: "Tilføj resultat som operationelt lag",
		setLayerSymbolTip: "Angiv symbolet for forespørgselsresultater: ",
		setSelectedSymbolTip: "Angiv symbolet for markeret objekt.",
		notUseFilter: "Brug ikke filter",
		setSourceTip: "Angiv forespørgselskilde.",
		setFilterTip: "Angiv filteret korrekt.",
		ok: "OK",
		cancel: "Annuller",
		noFilterTip: "Defineres der ikke et filterudtryk, viser denne forespørgsel alle objekter i den angivne datakilde."
  })
);