define(
	 ({
		queries: "Forespørgselsopgaver",
		addNew: "Tilføj ny",
    queryLayer: "Forespørgselslag",
		setSource: "Indstil",
		setDataSource: "Angiv datakilde",
		name: "Navn",
		querySource: "Datakilde",
		queryName: "Navn på opgave",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Indstilling for resultat",
		symbolSetting: "Indstilling for symbol",
		resultSettingTip: "Angiv, hvad og hvordan output-resultaterne skal vise.",
		resultItemTitle: "Resultatobjektets titel",
		resultItemContent: "Resultatobjektets indhold",
		fieldsSetTip: "Markér de felter, der skal vises. Markér et felt for at opdatere dets alias, sortere og formatere.",
		addField: "Tilføj felt",
		visibility: "Synlighed",
		alias: "Alias",
		specialType: "Speciel type",
		actions: "Handlinger",
		none: "Ingen",
		link: "Link",
		image: "Billede",
		noField: "Intet felt",
		operationalLayerTip: "Tilføj resultat som operationelt lag",
		setLayerSymbolTip: "Angiv symbolet for forespørgselsresultater: ",
		setSelectedSymbolTip: "Angiv symbolet for markeret objekt.",
		notUseFilter: "Brug ikke filter",
		setSourceTip: "Angiv forespørgselskilde.",
		setFilterTip: "Angiv filteret korrekt.",
		ok: "OK",
		cancel: "Annuller",
		noFilterTip: "Defineres der ikke et filterudtryk, viser denne forespørgsel alle objekter i den angivne datakilde.",
    relationships: "Relationer",
    addRelationshipLayer: "Tilføj ny relation",
    relatedTo: "Relateret til",
    selectOption: "Vælg venligst...",
    resultItemSorting: "Sortering af resultatelement",
    field: "Mark",
    sortingOrder: "Rækkefølge",
    configureFieldsTip: "Konfigurér de felter, som forespørgselsresultatet skal sorteres efter.",
    setSortingFields: "Indstil sorteringsfelter",
    ascending: "Stigende",
    descending: "Faldende",
    sortBy: "Sortér efter",
    thenBy: "Dernæst efter",
    addTask: "Tilføj opgave",
    noTasksTip: 'Ingen opgaver, klik på \"${addTask}\" for at starte!',
    infoText: "Info",
    filters: "Filtre",
    results: "Resultater",
    optionsText: "Indstillinger",
    summaryText: "Oversigt",
    attributeFilter: "Attributfilter",
    attributeFilterTip: "Definér attributudtryk til brug i widget\'en for at filtrere forespørgselslaget.",
    noExpressionDefinedTip: "Der blev ikke defineret noget udtryk.",
    needInputValuesTip: "Der skal indsættes værdier ved runtime",
    setExpressions: "Angiv udtryk",
    spatialFilter: "Spatialt filter",
    spatialFilterTip: "Vælg det/de spatiale filtre, der anvendes i widget\'en til at begrænse resultater.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Delvist eller helt inden for den aktuelle kortudstrækning",
    useDrawGraphicTip: "Delvist eller helt inden for den form, der et tegnet på kortet",
    useFeaturesTip: "Baseret på deres positioner i forhold til objekterne i et andet lag",
    noSpatialLimitTip: "Begræns ikke resultaterne spatialt",
    drawingTools: "Tegneværktøjer",
    bufferSettings: "Bufferindstillinger",
    defaultDistance: "Standardafstand",
    bufferDistance: "Bufferafstand",
    defaultUnit: "Standardenhed",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    availableSpatialRelationships: "Tilgængelige spatiale relationer",
    setSpatialRelationships: "Angiv spatiale relationer",
    availability: "Tilgængelighed",
    relationship: "Relation",
    label: "Mærke",
    intersect: "gennemskærer",
    contain: "indeholder",
    areContainedIn: "er indeholdt i",
    cross: "kors",
    envelopeIntersect: "indkredset gennemskæring",
    overlap: "overlapper",
    areOverlapped: "er overlappet",
    touche: "berører",
    within: "inden for",
    areWithin: "er inden for",
    indexIntersect: "indeksgennemskæring",
    itemTitle: "Elementtitel",
    displayFields: "Visningsfelter",
    sortingFields: "Sorterer felter",
    setDisplayFields: "Angiv visningsfelter",
    symbol: "Symbol",
    setSymbol: "Angiv symbol",
    serviceSymbolTip: "Brug de symboler, der er defineret af laget",
    exportTip: "Vis eksport-knap",
    keepResultsTip: "Behold resultater på kortet, når widget\'en lukkes",
    queryRelatedRecords: "Forespørg på relaterede poster",
    createLayerForTaskTip: "Angiv, hvordan opgaven skal oprette lag",
    oneLayerForTaskTip: "Opret kun ét lag for denne opgave",
    multipleLayerForTaskTip: "Opret et nyt lag, hver gang denne opgave udføres"
  })
);
