define(
   ({
    taskUrl: "Åtgärds-URL",
    serviceURLPlaceholder: "Ange URL för geobearbetningsåtgärden",
    ok: "OK",
    cancel: "Avbryt",
    layer: "Lager",
    action: "Åtgärd",
    input: "Indata",
    output: "Utdata",
    name: "Namn",
    type: "Typ",
    required: "Obligatoriskt",
    layerOrder: "Lagerordning",
    options: "Alternativ",
    defaultValue: "Standardvärde",
    inputFeatureBy: "Ange geoobjekt efter",
    renderer: "Renderare",
    displayType: "Visningstyp",
    label: "Etikett",
    tooltip: "Tipsruta",
    visible: "Synlig",
    helpUrl: "Hjälp-URL",
    useResultMapService: "Använd ritåtgärderna för den resulterande karttjänsten",
    drawOnMap: "Rita interaktivt på kartan",
    selectLayer: "Välja ett lager från kartan",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Lägg till resultat som funktionslager",
    popup: "Popup-fönster",
    setTask: "Ange",
    setTaskTitle: "Ange geobearbetningsåtgärd:",
    enablePopup: "Aktivera popup-fönster"
  })
);