define(
   ({
    taskUrl: "Åtgärds-URL",
    serviceURLPlaceholder: "Ange URL för geobearbetningsåtgärden",
    ok: "OK",
    cancel: "Avbryt",
    layer: "Lager",
    action: "Åtgärd",
    input: "Indata",
    output: "Utdata",
    name: "Namn",
    type: "Typ",
    required: "Obligatoriskt",
    layerOrder: "Lagerordning",
    options: "Alternativ",
    defaultValue: "Standardvärde",
    inputFeatureBy: "Ange geoobjekt efter",
    renderer: "Renderare",
    displayType: "Visningstyp",
    label: "Etikett",
    tooltip: "Tipsruta",
    visible: "Synlig",
    helpUrl: "Hjälp-URL",
    useResultMapService: "Använd ritåtgärderna för den resulterande karttjänsten",
    drawOnMap: "Rita interaktivt på kartan",
    selectLayer: "Välja ett lager från kartan",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Lägg till resultat som funktionslager",
    popup: "Popup-fönster",
    setTask: "Ange",
    setTaskTitle: "Ange geobearbetningsåtgärd:",
    enablePopup: "Aktivera popup-fönster",
    unSupportGeometryType: "Det går inte att ställa in renderaren på grund av att geometritypen är okänd.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Överför fil",
    selectFileToUpload: "Välj fil ...",
    upload: "Överför",
    rasterFormat: "Rasterdataformat",
    noFileSelected: "Ingen fil har valts!",
    uploadSuccess:"Filen har överförts!",
    showLayerContent: "Visa lagrets innehåll",
    Feet: "Fot",
    Yards: "Yard",
    Miles: "Engelska mil",
    NauticalMiles: "Nautiska mil",
    Meter: "Meter",
    Kilometers: "Kilometer",
    urlPlaceholder: "URL till geoobjektsuppsättning",
    allowToExport: "Tillåt export av resultat"
  })
);
