define(
   ({
    selectAnalysisTools:"Chọn các công cụ phân tích được liệt kê trong tiện ích.",
    selected: "đã chọn",
    name: "Tên",
    graphicalDisplay:"Hiển thị đồ họa",
    usage: "Sử dụng",
    toolNotAvailable: "Công cụ này không khả dụng vì bản đồ không chứa (các) lớp đối tượng yêu cầu.",
    aggregatePoints:"Các Điểm Tổng hợp",
    aggregatePointsUsage:"Tích hợp các điểm vào vùng chứa những điểm này.",
    aggregatePointsInputTip: "Chỉ định lớp đối tượng điểm sẽ được tổng hợp vào các vùng trong lớp đối tượng vùng.",
    calculateDensity:"Tính toán Mật độ",
    calculateDensityUsage:"Tạo bản đồ mật độ từ các đối tượng điểm hoặc đường bằng cách đưa ra số lượng cho trước của một số hiện tượng (thể hiện dưới dạng thuộc tính điểm hoặc đường) trên bản đồ.",
    calculateDensityInputTip:"Chỉ định các đối tượng điểm hoặc đường dùng để tính toán mật độ.",
    connectOriginsToDestinations: "Kết nối Điểm đầu Với Điểm đến",
    connectOriginsToDestinationsUsage: "Đo lường thời gian đi lại hoặc khoảng cách giữa các cặp điểm.",
    connectOriginsToDestinationsInputTip: "Chỉ định điểm bắt đầu hoặc các điểm trên các tuyến đường được tạo.",
    createBuffers:"Tạo Vùng đệm",
    createBuffersUsage:"Tạo vùng đệm từ các đối tượng đầu vào.",
    createBuffersInputTip:"Chỉ định lớp đối tượng điểm, đường, hoặc vùng để được tạo vùng đệm.",
    createDriveTimeAreas:"Tạo Khu vực Thời gian Lái xe",
    createDriveTimeAreasUsage:"Tạo các vùng thời gian lái xe (hoặc khoảng cách lái xe) xung quanh các điểm đầu vào cho các giá trị thời gian lái xe cho trước.",
    createDriveTimeAreasInputTip:"Chỉ định các điểm sẽ vẽ khu vực thời gian lái xe.",
    createViewshed:"Tạo tầm nhìn",
    createViewshedUsage:"Tạo các khu vực có thể nhìn thấy dựa trên các vị trí bạn chỉ định.",
    createViewshedInputTip:"Chỉ định các vị trí của người quan sát để xác định các khu vực có thể nhìn thấy.",
    createWatersheds:"Tạo các lưu vực sông",
    createWatershedsUsage:"Tạo các khu vực lưu vực dựa trên các vị trí bạn chỉ định.",
    createWatershedsInputTip:"Chỉ định các đối tượng điểm được sử dụng cho tính toán các lưu vực sông.",
    deriveNewLocations:"Phát sinh các Địa điểm Mới",
    deriveNewLocationsUsage:"Rút ra các đối tượng mới từ các lớp đầu vào phù hợp với truy vấn bạn chỉ định",
    deriveNewLocationsInputTip:"Chỉ định lớp phân tích để dùng làm đầu vào.",
    dissolveBoundaries:"Phân rã các Đường biên",
    dissolveBoundariesUsage:"Xóa bỏ các vùng chồng chéo hoặc chia sẻ một ranh giới chung.",
    dissolveBoundariesInputTip:"Chỉ định lớp chứa các đối tượng vùng sẽ được xóa bỏ.",
    enrichLayer:"Bổ sung thông tin lớp",
    enrichLayerUsage:"Bổ sung các đối tượng đầu vào với số liệu về con người, địa điểm và kinh doanh cho khu vực lân cận.",
    enrichLayerInputTip:"Chỉ định các đối tượng để bổ sung dữ liệu mới.",
    extractData:"Trích xuất Dữ liệu",
    extractDataDesc:"Trích xuất dữ liệu từ một hoặc nhiều lớp trong một phạm vi cho trước",
    extractDataInputTip:"Chỉ định lớp đối tượng đầu vào để trích xuất.",
    findExistingLocations:"Tìm các Vị trí Hiện tại",
    findExistingLocationsUsage:"Chọn các đối tượng trong lớp đầu vào phù hợp với thuộc tính và/hoặc truy vấn không gian bạn chỉ định",
    findExistingLocationsInputTip:"Chỉ định các lớp phân tích để dùng làm đầu vào.",
    findHotSpots:"Tìm Điểm Nóng",
    findHotSpotsUsage:"Tìm các cụm có ý nghĩa thống kê của các đối tượng đầu vào hoặc các giá trị cao/thấp.",
    findHotSpotsInputTip:"Chỉ định lớp đối tượng điểm hoặc vùng cho các điểm nóng sẽ được tính toán.",
    findNearest:"Tìm Vị trí Gần nhất",
    findNearestUsage:"Đối với từng đối tượng trên một lớp đầu vào, tìm đối tượng gần nhất trên một lớp khác",
    findNearestInputTip:"Chỉ định các đối tượng điểm, đường, hoặc vùng từ đó tìm thấy các vị trí gần nhất.",
    findSimilarLocations:"Tìm các Vị trí Tương tự",
    findSimilarLocationsUsage:"Đo lường đặc tính tương tự của các vị trí ứng viên với một hoặc nhiều vị trí tham chiếu.",
    findSimilarLocationsInputTip:"Chỉ định lớp đối tượng có chứa một hoặc nhiều vị trí tham chiếu so với các đối tượng trong lớp tìm kiếm sẽ được đánh giá đặc tính tương tự.",
    interpolatePoints:"Các điểm Nội suy",
    interpolatePointsUsage:"Dự đoán các giá trị tại các vị trí mới dựa trên đo lường từ một bộ sưu tập điểm.",
    interpolatePointsInputTip:"Chỉ định các đối tượng điểm sẽ được nội suy.",
    mergeLayers:"Trộn Lớp",
    mergeLayersUsage:"Trộn các đối tượng từ nhiều lớp vào một lớp mới",
    mergeLayersInputTip:"Chỉ định lớp đối tượng được trộn với lớp trộn.",
    overlayLayers:"Phủ Lớp",
    overlayLayersUsage:"Kết hợp nhiều lớp vào một lớp đơn với thông tin từ các lớp gốc được lưu giữ.",
    overlayLayersInputTip:"Chỉ định lớp đối tượng sẽ được chồng lớp với lớp chồng lớp.",
    planRoutes:"Kế hoạch Định tuyến",
    planRoutesUsage:"Xác định cách thức phân chia tác vụ hiệu quả giữa một lực lượng lao động di động.",
    planRoutesInputTip:"Chỉ định các điểm mà phương tiện, người lái, hoặc tuyến đường, cần ghé thăm.",
    summarizeNearby:"Tóm tắt Vị trí Lân cận",
    summarizeNearbyUsage:"Đối với mỗi đối tượng trên lớp đầu vào, tóm tắt dữ liệu trong một khoảng cách từ đối tượng trên một lớp khác.",
    summarizeNearbyInputTip:"Chỉ định lớp đối tượng điểm, đường, hoặc vùng từ đó sẽ đo khoảng cách đến các đối tượng trên lớp tóm tắt.",
    summarizeWithin:"Tóm tắt trong Phạm vi",
    summarizeWithinUsage:"Đối với từng vùng trên lớp vùng đầu vào, tóm tắt dữ liệu nằm bên trong nó từ các đối tượng trên lớp khác.",
    summarizeWithinInputTip:"Chỉ định lớp đối tượng vùng cần tóm tắt.",
    traceDownstream:"Theo dõi Hạ lưu",
    traceDownstreamUsage:"Xác định đường phân luồng theo hướng hạ lưu từ các vị trí bạn chỉ định.",
    traceDownstreamInputTip:"Chỉ định các đối tượng điểm được sử dụng cho vị trí bắt đầu cho việc theo dõi hạ lưu."
  })
);
