define(
   ({
    selectAnalysisTools:"Chọn các công cụ phân tích để sử dụng trong tiện ích.",
    selected: "đã chọn",
    name: "Tên",
    graphicalDisplay:"Hiển thị đồ họa",
    usage: "Sử dụng",
    settings: "Thiết lập",
    toolSetting: "Thiết lập thông tin chi tiết công cụ",
    toolLabel: "Tên hiển thị của công cụ",
    showHelpTip: "Hiện liên kếp trợ giúp trong tiện ích",
    showCurrentMapExtent: "Hiển thị tùy chọn để sử dụng kích thước bản đồ hiện tại",
    showCredits: "Hiển thị tùy chọn <b>Hiển thị Credit</b>",
    saveAsFeatureService: "Lưu kết quả trong tài khoản người sử dụngâ€™",
    showReadyToUseLayers: "Hiện các lớp sẵn sàng sử dụng từ bộ Atlas thế giới sống động trên ArcGIS Online",
    toolNotAvailable: "Công cụ này không khả dụng vì bản đồ không chứa (các) lớp đối tượng yêu cầu.",
    aggregatePoints:"Các Điểm Tổng hợp",
    aggregatePointsUsage:"Tích hợp các điểm vào vùng chứa những điểm này.",
    calculateDensity:"Tính toán Mật độ",
    calculateDensityUsage:"Tạo bản đồ mật độ từ các đối tượng điểm hoặc đường bằng cách đưa ra số lượng cho trước của một số hiện tượng (thể hiện dưới dạng thuộc tính điểm hoặc đường) trên bản đồ.",
    connectOriginsToDestinations: "Kết nối Điểm đầu Với Điểm đến",
    connectOriginsToDestinationsUsage: "Đo lường thời gian đi lại hoặc khoảng cách giữa các cặp điểm.",
    createBuffers:"Tạo Vùng đệm",
    createBuffersUsage:"Tạo vùng đệm từ các đối tượng đầu vào.",
    createDriveTimeAreas:"Tạo Khu vực Thời gian Lái xe",
    createDriveTimeAreasUsage:"Tạo các vùng thời gian lái xe (hoặc khoảng cách lái xe) xung quanh các điểm đầu vào cho các giá trị thời gian lái xe cho trước.",
    createViewshed:"Tạo tầm nhìn",
    createViewshedUsage:"Tạo các khu vực có thể nhìn thấy dựa trên các vị trí bạn chỉ định.",
    createWatersheds:"Tạo các lưu vực sông",
    createWatershedsUsage:"Tạo các khu vực lưu vực dựa trên các vị trí bạn chỉ định.",
    deriveNewLocations:"Phát sinh các Địa điểm Mới",
    deriveNewLocationsUsage:"Rút ra các đối tượng mới từ các lớp đầu vào phù hợp với truy vấn bạn chỉ định",
    dissolveBoundaries:"Phân rã các Đường biên",
    dissolveBoundariesUsage:"Xóa bỏ các vùng chồng chéo hoặc chia sẻ một ranh giới chung.",
    enrichLayer:"Bổ sung thông tin lớp",
    enrichLayerUsage:"Bổ sung các đối tượng đầu vào với số liệu về con người, địa điểm và kinh doanh cho khu vực lân cận.",
    extractData:"Trích xuất Dữ liệu",
    extractDataDesc:"Trích xuất dữ liệu từ một hoặc nhiều lớp trong một phạm vi cho trước",
    findExistingLocations:"Tìm các Vị trí Hiện tại",
    findExistingLocationsUsage:"Chọn các đối tượng trong lớp đầu vào phù hợp với thuộc tính và/hoặc truy vấn không gian bạn chỉ định",
    findHotSpots:"Tìm Điểm Nóng",
    findHotSpotsUsage:"Tìm các cụm có ý nghĩa thống kê của các đối tượng đầu vào hoặc các giá trị cao/thấp.",
    findNearest:"Tìm Vị trí Gần nhất",
    findNearestUsage:"Đối với từng đối tượng trên một lớp đầu vào, tìm đối tượng gần nhất trên một lớp khác",
    findSimilarLocations:"Tìm các Vị trí Tương tự",
    findSimilarLocationsUsage:"Đo lường đặc tính tương tự của các vị trí ứng viên với một hoặc nhiều vị trí tham chiếu.",
    interpolatePoints:"Các điểm Nội suy",
    interpolatePointsUsage:"Dự đoán các giá trị tại các vị trí mới dựa trên đo lường từ một bộ sưu tập điểm.",
    mergeLayers:"Trộn Lớp",
    mergeLayersUsage:"Trộn các đối tượng từ nhiều lớp vào một lớp mới",
    overlayLayers:"Phủ Lớp",
    overlayLayersUsage:"Kết hợp nhiều lớp vào một lớp đơn với thông tin từ các lớp gốc được lưu giữ.",
    planRoutes:"Kế hoạch Định tuyến",
    planRoutesUsage:"Xác định cách thức phân chia tác vụ hiệu quả giữa một lực lượng lao động di động.",
    summarizeNearby:"Tóm tắt Vị trí Lân cận",
    summarizeNearbyUsage:"Đối với mỗi đối tượng trên lớp đầu vào, tóm tắt dữ liệu trong một khoảng cách từ đối tượng trên một lớp khác.",
    summarizeWithin:"Tóm tắt trong Phạm vi",
    summarizeWithinUsage:"Đối với từng vùng trên lớp vùng đầu vào, tóm tắt dữ liệu nằm bên trong nó từ các đối tượng trên lớp khác.",
    traceDownstream:"Theo dõi Hạ lưu",
    traceDownstreamUsage:"Xác định đường phân luồng theo hướng hạ lưu từ các vị trí bạn chỉ định."
  })
);
