define({
  root: ({
    _widgetLabel: "Draw",
    selectDrawMode: "Select drawing mode",
    clear: "Clear",
    point: "Point",
    line: "Line",
    polyline: "Polyline",
    freehandPolyline: "Freehand Polyline",
    triangle: "Triangle",
    extent: "Envelope",
    circle: "Circle",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Freehand Polygon",
    text: "Text",
	textWarningMessage:"Text must be written before placing the point on map",
    style: "Style",
    alpha: "Transparency",
    width: "Width",
    size: "Size",
    color: "Color",
    markerColor: "Marker Color",
    outlineColor: "Outline Color",
    lineColor: "Line Color",
    fillColor: "Fill Color",
    showMeasurements: "Show Measurements",
    areaUnits: "Area Units",
    distanceUnits: "Distance Units",
    kilometers: "Kilometers",
    miles: "Miles",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareKilometers: "Square kilometers",
    squareMiles: "Square miles",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Square meters",
    squareFeet: "Square feet",
    squareYards: "Square yards",
	confirmDrawDelete:"This drawing will be deleted",
	all:"All",
	draws:'drawings',
	addDrawTitle:'Add a drawing',
	editDrawTitle:'Edit a drawing',
	listDrawTitle:'Drawings list',
	importExportTitle:'Import or export drawings',
	exportTitle:"Export draws",
	importTitle:"Import draws",
	importErrorMessageNavigator:"Your navigator doesn't support this functionnality.",
	importErrorWarningSelectFile:"Please select a file.",
	importWarningNoDrawings:"No drawings to load",
	importErrorFileStructure:"The file structure doesn't match.",
	importWarningNoExport0Draw:"No export of the file (No drawing to export).",
	nameField:"Name",
	symbolField:"Symbol",
	nameFieldDefaultValue:"My drawing",
	descriptionField:"Description",
	localLoading:"Your last drawings were loaded",
	editLabel:"Update this drawing",
	deleteLabel:"Delete this drawing",
	upLabel:"Move this drawing up",
	downLabel:"Move this drawing down",
	zoomLabel:"Zoom on this drawing",
	zoomAllLabel:"Zoom on all drawings",
	saveButton:"Save",
	resetButton:"Reset",
	cancelButton:"Cancel",
	textAngle: 'Text Angle',
    fontName: 'Font Name',
    drawSampleRotatedText: 'angle',
    boldTitle: 'Bold',
    boldCharacter: 'B',
    italicTitle: 'Italic',
    italicCharacter: 'I',
    underlineTitle: 'Underline',
    underlineCharacter: 'U',
	addMessage:'You can now make your drawing on map'
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});