define(
   ({
    _widgetLabel: "Olay Analizi",
    incident: "Oluşum",
    weather: "Hava Durumu",
    locate_incident: "Olay Bul",
    clear_incidents: "Olayları Temizle",
    reverse_geocoded_address: "En yakın adres",
    reverse_geocoded_error: "Kullanılabilir değil",
    miles: "Mil",
    kilometers: "Kilometre",
    feet: "Fit",
    meters: "Metre",
    yards: "Yarda",
    nauticalMiles: "Deniz Mili",
    now: "ŞİMDİ",
    wind: "RÜZGAR",
    SUN: "PAZ",
    MON: "PTS",
    TUE: "SAL",
    WED: "ÇAR",
    THU: "PER",
    FRI: "CUM",
    SAT: "CTS",
    defaultTabMsg: "Tanımlanan olay yok.",
    actionLabel: "Olay Olarak Ayarla",
    useMapExtent: "Geçerli harita yayılımını kullan",
    noFeaturesFound: "Detay bulunamadı.",
    downloadCSV: "CSV İNDİR",
    sum: "TOP",
    min: "MIN",
    max: "MAKS",
    avg: "ORT",
    count: "SAYIM",
    area: "ALAN",
    length: "UZUNLUK"
  })
);
