define(
   ({
    _widgetLabel: "Situatiebewustzijn (Beta)",
    locate_incident: "Incident zoeken",
    clear_incidents: "Incidenten wissen",
    reverse_geocoded_address: "Dichtstbijzijnde adres",
    reverse_geocoded_error: "Not available",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    now: "NU",
    wind: "WIND",
    SUN: "ZON",
    MON: "MAA",
    TUE: "DIN",
    WED: "WOE",
    THU: "DON",
    FRI: "VRIJ",
    SAT: "ZAT",
    defaultTabMsg: "Geen incidenten bekend.",
    actionLabel: "Instellen als incident",
    drawPoint: "Punt tekenen",
    drawLine: "Lijn tekenen",
    drawPolygon: "Vlak tekenen",
    saveIncident: "Incident opslaan",
    clearIncident: "Incident wissen",
    useMapExtent: "Huidige extent van de kaart gebruiken",
    noFeaturesFound: "Geen objecten gevonden.",
    downloadCSV: "CSV DOWNLOADEN",
    editComplete: "Object succesvol opgeslagen!",
    updateComplete: "Object succesvol bijgewerkt!",
    deleteComplete: "Object succesvol verwijderd!",
    sum: "SOM",
    min: "MIN",
    max: "MAX",
    avg: "GEM",
    count: "TELLEN",
    area: "GEBIED",
    length: "LENGTE",
    notPolySave: "Geef een bufferafstand op voor opslaan.",
    update_btn: "Actualiseren",
    delete_btn: "Verwijderen"
  })
);
