define(
   ({
    taskUrl: "URL attività",
    serviceURLPlaceholder: "Immettere l\'URL dell\'attività di geoprocessing",
    ok: "OK",
    cancel: "Annulla",
    layer: "Layer",
    action: "Azione",
    input: "Input",
    output: "Output",
    name: "Nome",
    type: "Tipo",
    required: "Obbligatorio",
    layerOrder: "Ordine layer",
    options: "Opzioni",
    defaultValue: "Valore predefinito",
    inputFeatureBy: "Immetti feature mediante",
    renderer: "Renderer",
    displayType: "Tipo visualizzazione",
    label: "Etichetta",
    tooltip: "Descrizione comandi",
    visible: "Visibile",
    helpUrl: "URL Guida",
    useResultMapService: "Usa le opzioni di disegno del map service dei risultati",
    drawOnMap: "Disegno interattivo sulla mappa",
    selectLayer: "Selezione di un layer nella mappa",
    url: "URL",
    symbol: "Simbolo",
    shareResults: "Aggiungi risultato come layer operativo",
    popup: "Popup",
    setTask: "Imposta",
    setTaskTitle: "Imposta attività GP",
    enablePopup: "Abilita popup"
  })
);