define(
   ({
    _widgetLabel: "Incidentanalyse",
    incident: "Incident",
    weather: "Weer",
    locate_incident: "Incident zoeken",
    clear_incidents: "Incidenten wissen",
    reverse_geocoded_address: "Dichtstbijzijnde adres",
    reverse_geocoded_error: "Not available",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    now: "NU",
    wind: "WIND",
    SUN: "ZON",
    MON: "MAA",
    TUE: "DIN",
    WED: "WOE",
    THU: "DON",
    FRI: "VRIJ",
    SAT: "ZAT",
    defaultTabMsg: "Geen incidenten bekend.",
    actionLabel: "Instellen als incident",
    useMapExtent: "Huidige extent van de kaart gebruiken",
    noFeaturesFound: "Geen objecten gevonden.",
    downloadCSV: "CSV DOWNLOADEN",
    sum: "SOM",
    min: "MIN",
    max: "MAX",
    avg: "GEM",
    count: "TELLEN",
    area: "GEBIED",
    length: "LENGTE"
  })
);
