define(
   ({
    _widgetLabel: "列印",
    title: "地圖標題",
    format: "格式",
    layout: "排版",
    settings: "進階",
    mapScaleExtent: "地圖比例/範圍",
    preserve: "保留",
    mapScale: "地圖比例",
    mapExtent: "地圖範圍",
    forceScale: "強制比例",
    getCurrentScale: "目前",
    mapMetadata: "排版詮釋資料",
    author: "作者",
    copyright: "版權所有",
    fullLayoutOptions: "完整排版選項",
    scaleBarUnitsMetric: "比例尺單位(公制)",
    scaleBarUnitsNonMetric: "比例尺單位(非公制)",
    unitsMiles: "英里",
    unitsKilometers: "公里",
    unitsMeters: "公尺",
    unitsFeet: "英呎",
    unitsYards: "碼",
    unitsNauticalMiles: "海哩",
    lncludeLegend: "包括圖例",
    printQualityOptions: "列印品質",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY 大小",
    width: "寬度(px)",
    height: "高度(px)",
    print: "列印",
    clearList: "清除列印",
    creatingPrint: "正在建立列印",
    printError: "出現錯誤，請重試"
  })
);