define(
   ({
    _widgetLabel: "Drukuj",
    title: "Tytuł mapy",
    format: "Format",
    layout: "Układ",
    settings: "Zaawansowany",
    mapScaleExtent: "Skala/zasięg mapy",
    preserve: "Zachowaj",
    mapScale: "skala mapy",
    mapExtent: "zasięg mapy",
    forceScale: "Wymuś skalę",
    getCurrentScale: "bieżący",
    mapMetadata: "Metadane układu",
    author: "Autor",
    copyright: "Prawa autorskie",
    fullLayoutOptions: "Wszystkie opcje układu",
    scaleBarUnitsMetric: "Podziałka liniowa — jednostki metryczne",
    scaleBarUnitsNonMetric: "Podziałka liniowa — jednostki niemetryczne",
    unitsMiles: "Mile",
    unitsKilometers: "Kilometry",
    unitsMeters: "Metry",
    unitsFeet: "Stopy",
    unitsYards: "Jardy",
    unitsNauticalMiles: "Mile Morskie",
    lncludeLegend: "Uwzględnij legendę",
    printQualityOptions: "Jakość wydruku",
    dpi: "DPI",
    mapOnlyOptions: "Rozmiar TYLKO_MAPA",
    width: "Szerokość (piksele)",
    height: "Wysokość (piksele)",
    print: "Drukuj",
    clearList: "Wyczyść wydruki",
    creatingPrint: "Tworzenie wydruku",
    printError: "Błąd, spróbuj ponownie"
  })
);