define(
   ({
    selectAnalysisTools:"Wybierz narzędzie analizy, które ma być użyte w widżecie.",
    selected: "wybrane",
    name: "Nazwa",
    graphicalDisplay:"Widok graficzny",
    usage: "Wykorzystanie",
    settings: "Parametry",
    toolSetting: "Skonfiguruj szczegóły narzędzia",
    toolLabel: "Wyświetlana nazwa narzędzia",
    showHelpTip: "Wyświetl w widżecie łącza pomocy",
    showCurrentMapExtent: "Wyświetl opcję używania bieżącego zasięgu mapy",
    showCredits: "Wyświetl opcję <b>Pokaż kredyty</b>",
    saveAsFeatureService: "Zapisz wyniki na koncie użytkownika",
    showReadyToUseLayers: "Wyświetl warstwy gotowe do użycia w nieustannie rozwijającym się atlasie świata usługi ArcGIS Online",
    toolNotAvailable: "To narzędzie nie jest dostępne, ponieważ mapa nie zawiera wymaganych warstw obiektowych.",
    aggregatePoints:"Agreguj punkty",
    aggregatePointsUsage:"Agreguje punkty w poligony, w których te punkty są ulokowane.",
    calculateDensity:"Oblicz zagęszczenie",
    calculateDensityUsage:"Tworzy mapę zagęszczenia z obiektów punktowych lub liniowych poprzez odpowiednie rozmieszczenie na powierzchni mapy znanych wartości wyrażających dane zjawisko (reprezentowane przez atrybuty punktów lub linii).",
    connectOriginsToDestinations: "Połącz punkty początkowe z docelowymi",
    connectOriginsToDestinationsUsage: "Mierzy czas podróży lub odległość między parami punktów.",
    createBuffers:"Utwórz bufory",
    createBuffersUsage:"Tworzy poligony buforów z obiektów wejściowych.",
    createDriveTimeAreas:"Utwórz obszary czasu przejazdu",
    createDriveTimeAreasUsage:"Tworzy poligony czasu dojazdu (lub długości trasy) wokół punktów wejściowych dla podanych wartości czasu dojazdu.",
    createViewshed:"Utwórz widoczność",
    createViewshedUsage:"Tworzy widoczne obszary na podstawie podanych lokalizacji.",
    createWatersheds:"Utwórz zlewnie",
    createWatershedsUsage:"Tworzy obszary ciążenia na podstawie podanych lokalizacji.",
    deriveNewLocations:"Wyznacz nowe lokalizacje",
    deriveNewLocationsUsage:"Wyznacza z warstw wejściowych nowe obiekty, które spełniają warunki wprowadzonych zapytań.",
    dissolveBoundaries:"Agreguj obszary",
    dissolveBoundariesUsage:"Agreguje poligony, które się nakładają lub mają wspólną granicę.",
    enrichLayer:"Wzbogać warstwę",
    enrichLayerUsage:"Wzbogacenie obiektów danych wejściowych o osoby, miejsca i fakty biznesowe związane z pobliskimi obszarami.",
    extractData:"Wydziel dane",
    extractDataDesc:"Wydziela dane z jednej warstwy lub wielu warstw w podanym zasięgu.",
    findExistingLocations:"Znajdź istniejące lokalizacje",
    findExistingLocationsUsage:"Wybiera z warstwy wejściowej obiekty, które spełniają wprowadzone warunki zapytań o atrybuty i/lub zapytań przestrzennych.",
    findHotSpots:"Znajdź lokalizacje hot spot",
    findHotSpotsUsage:"Znajduje statystycznie istotne klastry z obiektami wejściowymi lub wysokimi/niskimi wartościami.",
    findNearest:"Narzędzie Znajdź najbliższe",
    findNearestUsage:"Dla każdego obiektu z warstwy wejściowej znajduje najbliższe obiekty na innej warstwie.",
    findSimilarLocations:"Znajdź podobne lokalizacje",
    findSimilarLocationsUsage:"Mierzy podobieństwo lokalizacji w warstwie propozycji wyszukiwania dla co najmniej jednej lokalizacji referencyjnej.",
    interpolatePoints:"Interpoluj punkty",
    interpolatePointsUsage:"Umożliwia przewidywanie wartości w nowych lokalizacjach na podstawie pomiarów wykonanych na zbiorze punktów.",
    mergeLayers:"Połącz warstwy",
    mergeLayersUsage:"Łączy obiekty z wielu warstw w nową warstwę.",
    overlayLayers:"Nałóż warstwy",
    overlayLayersUsage:"Łączy wiele warstw w jedną warstwę, która zachowuje informacje z oryginalnych warstw.",
    planRoutes:"Planuj trasy",
    planRoutesUsage:"Określa, jak efektywnie rozdzielić zadania wśród pracowników mobilnych.",
    summarizeNearby:"Sumuj w pobliżu",
    summarizeNearbyUsage:"Dla każdego obiektu z warstwy wejściowej podsumowuje dane w odległości od obiektów na innej warstwie.",
    summarizeWithin:"Sumuj w obrębie",
    summarizeWithinUsage:"Dla każdego poligonu na warstwie wejściowej poligonów podsumowuje znajdujące się w niej dane względem obiektów na innej warstwie.",
    traceDownstream:"Śledź w dół",
    traceDownstreamUsage:"Określa ścieżki przepływu w dół od podanej lokalizacji."
  })
);
