define(
   ({
    selectAnalysisTools:"Wybierz narzędzie analizy, które ma być wymienione w widżecie.",
    selected: "wybrane",
    name: "Nazwa",
    graphicalDisplay:"Widok graficzny",
    usage: "Wykorzystanie",
    toolNotAvailable: "To narzędzie nie jest dostępne, ponieważ mapa nie zawiera wymaganych warstw obiektowych.",
    aggregatePoints:"Agreguj punkty",
    aggregatePointsUsage:"Agreguje punkty w poligony, w których te punkty są ulokowane.",
    aggregatePointsInputTip: "Podaj warstwę obiektów punktowych, które będą agregowane w poligony na warstwie obiektów poligonowych.",
    calculateDensity:"Oblicz zagęszczenie",
    calculateDensityUsage:"Tworzy mapę zagęszczenia z obiektów punktowych lub liniowych poprzez odpowiednie rozmieszczenie na powierzchni mapy znanych wartości wyrażających dane zjawisko (reprezentowane przez atrybuty punktów lub linii).",
    calculateDensityInputTip:"Podaj obiekt punktowy lub liniowy, na podstawie którego ma zostać obliczone zagęszczenie.",
    connectOriginsToDestinations: "Połącz punkty początkowe z docelowymi",
    connectOriginsToDestinationsUsage: "Mierzy czas podróży lub odległość między parami punktów.",
    connectOriginsToDestinationsInputTip: "Podaj punkt początkowy lub punkty początkowe generowanych tras.",
    createBuffers:"Utwórz bufory",
    createBuffersUsage:"Tworzy poligony buforów z obiektów wejściowych.",
    createBuffersInputTip:"Podaj warstwę obiektów punktowych, liniowych lub poligonowych do buforowania.",
    createDriveTimeAreas:"Utwórz obszary czasu przejazdu",
    createDriveTimeAreasUsage:"Tworzy poligony czasu dojazdu (lub długości trasy) wokół punktów wejściowych dla podanych wartości czasu dojazdu.",
    createDriveTimeAreasInputTip:"Podaj punkty, w których mają być rysowane obszary czasu dojazdu.",
    createViewshed:"Utwórz widoczność",
    createViewshedUsage:"Tworzy widoczne obszary na podstawie podanych lokalizacji.",
    createViewshedInputTip:"Podaj lokalizacje obserwacyjne identyfikujące widoczne obszary.",
    createWatersheds:"Utwórz zlewnie",
    createWatershedsUsage:"Tworzy obszary ciążenia na podstawie podanych lokalizacji.",
    createWatershedsInputTip:"Podaj obiekty punktowe używane do wyznaczania zlewni.",
    deriveNewLocations:"Wyznacz nowe lokalizacje",
    deriveNewLocationsUsage:"Wyznacza z warstw wejściowych nowe obiekty, które spełniają warunki wprowadzonych zapytań.",
    deriveNewLocationsInputTip:"Podaj warstwę analizy, której chcesz użyć.",
    dissolveBoundaries:"Agreguj obszary",
    dissolveBoundariesUsage:"Agreguje poligony, które się nakładają lub mają wspólną granicę.",
    dissolveBoundariesInputTip:"Podaj warstwę zawierającą obiekty poligonowe przeznaczone do agregacji.",
    enrichLayer:"Wzbogać warstwę",
    enrichLayerUsage:"Wzbogacenie obiektów danych wejściowych o osoby, miejsca i fakty biznesowe związane z pobliskimi obszarami.",
    enrichLayerInputTip:"Podaj obiekty, które mają być wzbogacone nowymi danymi.",
    extractData:"Wydziel dane",
    extractDataDesc:"Wydziela dane z jednej warstwy lub wielu warstw w podanym zasięgu.",
    extractDataInputTip:"Podaj wejściową warstwę obiektów do wydzielenia.",
    findExistingLocations:"Znajdź istniejące lokalizacje",
    findExistingLocationsUsage:"Wybiera z warstwy wejściowej obiekty, które spełniają wprowadzone warunki zapytań o atrybuty i/lub zapytań przestrzennych.",
    findExistingLocationsInputTip:"Podaj warstwy analizy z danymi wejściowymi.",
    findHotSpots:"Znajdź lokalizacje hot spot",
    findHotSpotsUsage:"Znajduje statystycznie istotne klastry z obiektami wejściowymi lub wysokimi/niskimi wartościami.",
    findHotSpotsInputTip:"Podaj warstwę obiektów punktowych lub poligonowych, dla których mają być wyznaczone lokalizacje hot spot.",
    findNearest:"Narzędzie Znajdź najbliższe",
    findNearestUsage:"Dla każdego obiektu z warstwy wejściowej znajduje najbliższe obiekty na innej warstwie.",
    findNearestInputTip:"Podaj obiekty punktowe, liniowe lub poligonowe, z których mają być szukane najbliższe lokalizacje.",
    findSimilarLocations:"Znajdź podobne lokalizacje",
    findSimilarLocationsUsage:"Mierzy podobieństwo lokalizacji w warstwie propozycji wyszukiwania dla co najmniej jednej lokalizacji referencyjnej.",
    findSimilarLocationsInputTip:"Podaj warstwę obiektów, która zawiera co najmniej jedną lokalizację referencyjną, według której obiekty w warstwie wyszukiwania będą oceniane pod względem podobieństwa.",
    interpolatePoints:"Interpoluj punkty",
    interpolatePointsUsage:"Umożliwia przewidywanie wartości w nowych lokalizacjach na podstawie pomiarów wykonanych na zbiorze punktów.",
    interpolatePointsInputTip:"Podaj obiekty punktowe przeznaczone do interpolacji.",
    mergeLayers:"Połącz warstwy",
    mergeLayersUsage:"Łączy obiekty z wielu warstw w nową warstwę.",
    mergeLayersInputTip:"Podaj warstwę obiektów, która ma zostać połączona z warstwą łączenia.",
    overlayLayers:"Nałóż warstwy",
    overlayLayersUsage:"Łączy wiele warstw w jedną warstwę, która zachowuje informacje z oryginalnych warstw.",
    overlayLayersInputTip:"Podaj warstwę obiektów, która zostanie nałożona na warstwę nakładania.",
    planRoutes:"Planuj trasy",
    planRoutesUsage:"Określa, jak efektywnie rozdzielić zadania wśród pracowników mobilnych.",
    planRoutesInputTip:"Podaj punkty, które mają być odwiedzone przez pojazdy i kierowców oraz uwzględnione w trasie.",
    summarizeNearby:"Sumuj w pobliżu",
    summarizeNearbyUsage:"Dla każdego obiektu z warstwy wejściowej podsumowuje dane w odległości od obiektów na innej warstwie.",
    summarizeNearbyInputTip:"Podaj warstwę buforowanego obiektu punktowego, liniowego lub poligonowego, od której będą obliczane odległości do obiektów w warstwie sumowania.",
    summarizeWithin:"Sumuj w obrębie",
    summarizeWithinUsage:"Dla każdego poligonu na warstwie wejściowej poligonów podsumowuje znajdujące się w niej dane względem obiektów na innej warstwie.",
    summarizeWithinInputTip:"Podaj warstwę obiektu poligonowego, która ma być podsumowywana.",
    traceDownstream:"Śledź w dół",
    traceDownstreamUsage:"Określa ścieżki przepływu w dół od podanej lokalizacji.",
    traceDownstreamInputTip:"Podaj obiekty punktowe używane jako lokalizacje początkowe ścieżki przepływu w dół."
  })
);
