define(
	 ({
		chartTasks: "チャート タスク",
		addNew: "新規追加",
		addNewTip: "新規チャート タスクの追加",
		name: "名前",
		set: "設定",
		setDataSource: "データ ソースの設定",
		generalSettingsTip: "チャートのデータ ソース、タイトル、説明を設定します。",
		chartModeSettingTip: "データを分析してチャートとして表示する方法を選択します。",
		detailsSettingTip: "チャートのタイプと色を指定してチャートの外観を設定し、チャートに表示する値を設定します。",
		symbolSettingTip: "チャート化されたデータのマップ表示を設定します。",
		addFilterTip: "このデータにフィルターを追加",
		dataSource: "データ ソース",
		noResults: "フィーチャは見つかりませんでした。",
		chartTitle: "チャートのタイトル",
		description: "説明",
		chartingMode: "チャートの表示",
		featureOption: "値をフィーチャ別に表示",
		categoryOption: "値をカテゴリ別に表示",
		countOption: "フィーチャ数をカテゴリ別に表示",
		fieldOption: "属性値をチャートとして表示",
		category: "カテゴリ",
		axisLabel: "カテゴリ ラベル",
		categoryField: "カテゴリ フィールド",
		operation: "操作",
		originalOption: "元の値を使用",
		sumOption: "合計",
		averageOption: "平均",
		minOption: "最小",
		maxOption: "最大",
		valueFields: "値フィールド",
		moveUp: "上に移動",
		moveDown: "下に移動",
		sortOrder: "カテゴリ ラベルを使用してチャートの順序を並べ替え",
		ascending: "昇順",
		descending: "降順",
		chartType: "チャート タイプ",
		column: "カラム チャート",
		bar: "バー チャート",
		line: "ライン チャート",
		pie: "パイ チャート",
		chartColor: "チャートの色",
		showDataLabels: "データ ラベルの表示",
		setSymbol: "選択シンボル",
		setHighLightColor: "ハイライト色",
		settings: "設定",
		mapInterationOptions: "マップ操作オプション",
		preview: "プレビュー",
		ok: "OK",
		cancel: "キャンセル",
		close: "閉じる",
		setFilterTip: "フィルターを正しく設定してください。 ",
		setChartTitleTip: "チャートのタイトルを設定してください。",
		setChartTypeTip: "少なくとも 1 つのチャート タイプを選択してください。",
		setDataFieldTip: "少なくとも 1 つの値フィールドを選択してください。",
		setOutputFieldTip: "出力フィールドを設定してください。",
		count: "個数",
		label: "ラベル",
		horizontalAxis: "横軸",
		verticalAxis: "縦軸",
		dataLabels: "データ ラベル",
		color: "色",
		colorful: "カラー",
		monochromatic: "モノクロ",
    noTaskTip: "[新規追加] をクリックしてチャート タスクを追加します",
    info: "情報",
    charts: "チャート",
    options: "オプション",
    taskName: "タスク名",
    summary: "サマリー",
    resultDescription: "結果の説明",
    spatialFilterTip: "結果を制限するためにウィジェットで使用される空間フィルターを選択します。",
    defaultOption: "デフォルト",
    useCurrentExtentTip: "現在のマップ範囲に部分的または完全に含まれる",
    useDrawGraphicTip: "マップに描画された図形に部分的または完全に含まれる",
    useFeaturesTip: "別のレイヤー内のフィーチャを基準にした位置に基づく",
    noSpatialLimitTip: "結果を空間的に制限しない",
    drawingTools: "描画ツール",
    bufferSettings: "バッファー設定",
    defaultDistance: "デフォルトの距離",
    bufferDistance: "バッファー距離",
    defaultUnit: "デフォルトの単位",
    miles: "マイル",
    kilometers: "キロメートル",
    feet: "フィート",
    meters: "メートル",
    yards: "ヤード",
    nauticalMiles: "海里",
    availableSpatialRelationships: "使用可能な空間リレーションシップ",
    setSpatialRelationships: "空間リレーションシップの設定",
    availability: "可用性",
    relationship: "リレーションシップ",
    actions: "操作",
    intersect: "交差",
    contain: "<条件フィーチャ> を含む",
    areContainedIn: "次に含まれる",
    cross: "十字",
    envelopeIntersect: "エンベロープの交差",
    overlap: "オーバーラップ",
    areOverlapped: "オーバーラップしている",
    touche: "接する",
    within: "含まれる",
    areWithin: "「含まれる」フィーチャを検索",
    indexIntersect: "インデックスの交差"
  })
);