define(
	 ({
		charts: "チャート タスク",
		addNew: "新規追加",
		addNewTip: "新規チャート タスクの追加",
		name: "名前",
		set: "設定",
		setDataSource: "データ ソースの設定",
		generalSettingsTip: "チャートのデータ ソース、タイトル、説明を設定します。",
		chartModeSettingTip: "データを分析してチャートとして表示する方法を選択します。",
		detailsSettingTip: "チャートのタイプと色を指定してチャートの外観を設定し、チャートに表示する値を設定します。",
		symbolSettingTip: "チャート化されたデータのマップ表示を設定します。",
		addFilterTip: "このデータにフィルタを追加",
		dataSource: "データ ソース",
		noResults: "フィーチャは見つかりませんでした。",
		chartTitle: "チャートのタイトル",
		description: "説明",
		chartingMode: "チャートの表示",
		featureOption: "値をフィーチャ別に表示",
		categoryOption: "値をカテゴリ別に表示",
		countOption: "フィーチャ数をカテゴリ別に表示",
		fieldOption: "属性値をチャートとして表示",
		category: "カテゴリ",
		axisLabel: "カテゴリ ラベル",
		categoryField: "カテゴリ フィールド",
		operation: "操作",
		originalOption: "元の値を使用",
		sumOption: "合計",
		averageOption: "平均",
		minOption: "最小",
		maxOption: "最大",
		valueFields: "値フィールド",
		moveUp: "上に移動",
		moveDown: "下に移動",
		sortOrder: "カテゴリ ラベルを使用してチャートの順序を並べ替え",
		ascending: "昇順",
		descending: "降順",
		chartType: "チャート タイプ",
		column: "カラム チャート",
		bar: "バー チャート",
		line: "ライン チャート",
		pie: "パイ チャート",
		chartColor: "チャートの色",
		showDataLabels: "データ ラベルの表示",
		setSymbol: "選択シンボル",
		setHighLightColor: "ハイライト色",
		settings: "設定",
		mapInterationOptions: "マップ操作オプション",
		preview: "プレビュー",
		ok: "OK",
		cancel: "キャンセル",
		close: "閉じる",
		setFilterTip: "フィルタを正しく設定してください。 ",
		setChartTitleTip: "チャートのタイトルを設定してください。",
		setChartTypeTip: "少なくとも 1 つのチャート タイプを選択してください。",
		setDataFieldTip: "少なくとも 1 つの値フィールドを選択してください。",
		setOutputFieldTip: "出力フィールドを設定してください。",
		count: "個数",
		label: "ラベル",
		horizontalAxis: "横軸",
		verticalAxis: "縦軸",
		dataLabels: "データ ラベル",
		color: "色",
		colorful: "カラー",
		monochromatic: "モノクロ"
  })
);