define(
   ({
    layerSelect: "選擇圖像圖層",
    displayMeasureResultInPopup: "在快顯視窗中顯示測量結果",
    angularUnitSelect: "預設角度單位",
    linearUnitSelect: "預設線性單位",
    areaUnitSelect: "預設面積單位",
    displayOperationSelect: "選擇測量操作",
    errorSectionMeasage: "沒有圖層支援測量功能。",
    unitLabel: {
      esriInches: "英吋(I)",
      esriFeet: "英呎",
      esriYards: "碼",
      esriMiles: "英里",
      esriNauticalMiles: "海浬",
      esriMillimeters: "公釐(M)",
      esriCentimeters: "公分(C)",
      esriDecimeters: "公寸",
      esriMeters: "公尺",
      esriKilometers: "公里",
      esriDURadians: "弧度(A)",
      esriDUDecimalDegrees: "度(D)",
      esriSquareInches: "平方英吋",
      esriSquareFeet: "平方英呎",
      esriSquareYards: "平方碼",
      esriAcres: "英畝",
      esriSquareMiles: "平方英里",
      esriSquareMillimeters: "平方公釐",
      esriSquareCentimeters: "平方公分",
      esriSquareDecimeters: "平方公寸",
      esriSquareMeters: "平方公尺",
      esriAres: "公畝",
      esriHectares: "公頃",
      esriSquareKilometers: "平方公里"
    },
    operationLabel: {
      esriMensurationPoint: "點(P)",
      esriMensurationDistanceAndAngle: "距離和角度",
      esriMensurationAreaAndPerimeter: "面積和周長",
      esriMensurationHeightFromBaseAndTop: "底部至頂層",
      esriMensurationHeightFromBaseAndTopShadow: "底部至頂部陰影",
      esriMensurationHeightFromTopAndTopShadow: "頂部至頂部陰影",
      esriMensurationCentroid: "質心",
      esriMensurationPoint3D: "點(3D)",
      esriMensurationDistanceAndAngle3D: "距離和角度(3D)",
      esriMensurationAreaAndPerimeter3D: "面積和周長(3D)",
      esriMensurationCentroid3D: "質心(3D)"
    }
  })
);