define(
   ({
    addDistance: "Agregar unidad de longitud",
    addArea: "Agregar unidad de área",
    label: "Etiqueta",
    abbr: "Abreviatura",
    conversion: "Conversión",
    actions: "Acciones",
    areaUnits: "Unidades de área",
    distanceUnits: "Unidades de longitud",
    kilometers: "Kilómetros",
    miles: "Millas",
    meters: "Metros",
    feet: "Pies",
    yards: "Yardas",
    squareKilometers: "Kilómetros cuadrados",
    squareMiles: "Millas cuadradas",
    acres: "Acres",
    hectares: "Hectáreas",
    squareMeters: "Metros cuadrados",
    squareFeet: "Pies cuadrados",
    squareYards: "Yardas cuadradas",
    distance: "Distancias",
    area: "Áreas",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "mi²",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "ft²",
    squareYardsAbbreviation: "yd²",
    defineUnits: "Define las unidades de medida.",
    operationalLayer: "Agrega el dibujo como capa operativa del mapa."
  })
);