define(
   ({
    layerSelect: "Zaznacz warstwę obrazową",
    displayMeasureResultInPopup: "Wyświetl wyniki pomiaru w oknie podręcznym",
    angularUnitSelect: "Domyślna jednostka kątowa",
    linearUnitSelect: "Domyślna jednostka liniowa",
    areaUnitSelect: "Domyślna jednostka powierzchni",
    displayOperationSelect: "Wybierz operacje pomiaru",
    errorSectionMeasage: "Żadna z warstw nie zapewnia możliwości pomiarowych.",
    unitLabel: {
      esriInches: "Cale",
      esriFeet: "Stopy",
      esriYards: "Jardy",
      esriMiles: "Mile",
      esriNauticalMiles: "Mile morskie",
      esriMillimeters: "Milimetry",
      esriCentimeters: "Centymetry",
      esriDecimeters: "Decymetry",
      esriMeters: "Metry",
      esriKilometers: "Kilometry",
      esriDURadians: "Radiany",
      esriDUDecimalDegrees: "Stopnie",
      esriSquareInches: "Cale kw.",
      esriSquareFeet: "Stopy kw.",
      esriSquareYards: "Jardy kw.",
      esriAcres: "Akry",
      esriSquareMiles: "Mile kw.",
      esriSquareMillimeters: "Milimetry kw.",
      esriSquareCentimeters: "Centymetry kw.",
      esriSquareDecimeters: "Decymetry kw.",
      esriSquareMeters: "Metry kw.",
      esriAres: "Ary",
      esriHectares: "Hektary",
      esriSquareKilometers: "Kilometry kw."
    },
    operationLabel: {
      esriMensurationPoint: "Punkt",
      esriMensurationDistanceAndAngle: "Odległość i kąt",
      esriMensurationAreaAndPerimeter: "Pole powierzchni i obwód",
      esriMensurationHeightFromBaseAndTop: "Od podstawy do szczytu",
      esriMensurationHeightFromBaseAndTopShadow: "Od podstawy do szczytu - cień",
      esriMensurationHeightFromTopAndTopShadow: "Od szczytu do szczytu - cień",
      esriMensurationCentroid: "Centroid",
      esriMensurationPoint3D: "Punkt (3D)",
      esriMensurationDistanceAndAngle3D: "Odległość i kąt (3D)",
      esriMensurationAreaAndPerimeter3D: "Pole powierzchni i obwód (3D)",
      esriMensurationCentroid3D: "Centroid (3D)"
    }
  })
);