define(
   ({
    _widgetLabel: "Análise de Incidente",
    incident: "Incidente",
    weather: "Meteorologia",
    locate_incident: "Localizar Incidente",
    clear_incidents: "Limpar Incidentes",
    reverse_geocoded_address: "Endereço mais próximo",
    reverse_geocoded_error: "Não disponível",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    now: "AGORA",
    wind: "VENTO",
    SUN: "DOM",
    MON: "SEG",
    TUE: "TER",
    WED: "QUA",
    THU: "QUI",
    FRI: "SEX",
    SAT: "SÁB",
    defaultTabMsg: "Nenhum incidente identificado.",
    actionLabel: "Definir Como Incidente",
    useMapExtent: "Usar a extensão de mapa actual",
    noFeaturesFound: "Não foram encontrados nenhuns elementos.",
    downloadCSV: "DESCARREGAR CSV",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "CONTAGEM",
    area: "ÁREA",
    length: "LENGTH"
  })
);
