define(
   ({
    _widgetLabel: "Nahlásit prvek",
    select: "Vybrat",
    draw: "Vykreslit",
    chooseALayer: "Vybrat vrstvu",
    clickAFeature: "Kliknutím na prvek na mapě jej vyberte.",
    loadingFeatures: "Probíhá získávání podrobností vybraných prvků…",
    errorTitle: "Chyba",
    errorIdentify: "Chyba identifikace prvků. Podrobné informace naleznete v protokolu konzole.",
    infoWindowTitle: "Podrobnosti",
    layerLabel: "Jméno vrstvy",
    reviewStatusLabel: "Stav kontroly",
    selectReviewStatusAdd: "Přidat prvek",
    selectReviewStatusDelete: "Smazat prvek",
    selectReviewStatusMove: "Přesunout prvek",
    selectReviewStatusReshape: "Změnit tvar prvku",
    drawReviewStatusMissing: "Chybějící prvky",
    drawReviewStatusPosition: "Polohová chyba",
    drawReviewStatusShape: "Chyba tvaru",
    drawReviewStatusAttribute: "Chyba atributu",
    notesLabel: "Poznámky",
    severityLabel: "Závažnost",
    reportedByLabel: "Nahlásil",
    reportedByDefault: "anonymní",
    reportButton: "Zpráva",
    reportMessage: "Hlášení přijato",
    errorReportMessage: "Při nahlašování prvku došlo k chybě.",
    drawErrorInstructions: "Vyberte bod, linii nebo polygon a zakreslete chybnou geometrii do mapy:",
    errorMapService: "Při získávání informací o mapové službě došlo k chybě.",
    noFeatureSelected : "V určeném umístění nebyly nalezeny žádné prvky.",
    selectFeatureMapPoint: "Kliknutím vyberte prvek",
    drawFeatureMapPoint: "Kliknutím přidáte bod.",
    popupMessage:"Hlášení",
    popupError:"Chyba",
    manyFeaturesSelected: "Byl nalezen více než jeden prvek. Přibližte se a vyberte prvek, který chcete nahlásit."
  })
);
