define(
   ({
    _widgetLabel: "쿼리",
    executeQueryTip: "쿼리를 실행하려면 다음 작업 항목 중 하나를 클릭하세요.",
    invalidConfig: "잘못된 구성입니다. 쿼리 설정 페이지를 사용하여 올바른 구성을 가져오세요.",
    queryParams: "옵션",
    parameters: "옵션",
    queries: "쿼리",
    apply: "적용",
    queryResults: "결과",
    clear: "지우기",
    noResults: "피처를 찾을 수 없습니다.",
    queryError: "쿼리하지 못했습니다.",
    numberFound: "발견한 피처 수",
    mapExtentTip: "결과를 현재 맵 영역으로 제한합니다.",
    noValue: "값 없음",
    and: "그리고",
    stringOperatorIs: "다음과 같음", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "다음과 같지 않음",
    stringOperatorStartsWith: "다음으로 시작함",
    stringOperatorEndsWith: "다음으로 끝남",
    stringOperatorContains: "다음을 포함함",
    stringOperatorDoesNotContain: "다음을 포함하지 않음",
    stringOperatorIsBlank: "비어 있음",
    stringOperatorIsNotBlank: "비어 있지 않음",
    dateOperatorIsOn: "다음 날짜임", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "다음 날짜가 아님",
    dateOperatorIsBefore: "다음 이전 날짜임",
    dateOperatorIsAfter: "다음 이후 날짜임",
    dateOperatorDays: "일",
    dateOperatorWeeks: "주", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "개월",
    dateOperatorInTheLast: "다음 기간에 이내에 속함",
    dateOperatorNotInTheLast: "다음 기간에 이내에 속하지 않음",
    dateOperatorIsBetween: "다음 사이에 속함",
    dateOperatorIsNotBetween: "다음 사이에 속하지 않음",
    dateOperatorIsBlank: "비어 있음",
    dateOperatorIsNotBlank: "비어 있지 않음",
    numberOperatorIs: "다음과 같음", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "다음과 같지 않음",
    numberOperatorIsAtLeast: "다음 이상",
    numberOperatorIsLessThan: "다음 미만",
    numberOperatorIsAtMost: "다음 이하",
    numberOperatorIsGreaterThan: "다음 초과",
    numberOperatorIsBetween: "다음 사이에 속함",
    numberOperatorIsNotBetween: "다음 사이에 속하지 않음",
    numberOperatorIsBlank: "비어 있음",
    numberOperatorIsNotBlank: "비어 있지 않음",
    operationalLayerTip: "결과를 운영 레이어로 추가",
    queryResult: "쿼리 결과",
    specifyParamsTip: "이 작업에 대한 매개변수 지정",
    useSpatialFilter: "공간 필터를 사용하여 피처 제한",
    useCurrentMapExtent: "현재 맵 영역과 교차하는 피처만",
    drawGraphicOnMap: "사용자 정의된 영역과 교차하는 피처만",
    specifySpatialFilterMsg: "이 작업에 대한 공간 필터를 지정하세요.",
    clearResults: "결과 지우기",
    operationalTip: '이 옵션을 선택하면 \"${clearResults}\" 버튼을 클릭할 때까지 결과가 맵에서 유지됩니다.',
    noneQueryTip: "이 위젯에 구성된 쿼리 태스크가 없습니다.",
    noPermissionsMsg: "이 서비스에 접근할 권한이 없습니다.",
    attributesFromRelationship: "릴레이트된 테이블의 속성",
    tasks: "태스크",
    applySpatialFilterToLimitResults: "결과 제한에 공간 필터 적용",
    useCurrentExtentTip: "현재 맵 범위 내 일부 또는 전체",
    useDrawGraphicTip: "맵에 그려진 모양 내 일부 또는 전체",
    useFeaturesTip: "다른 레이어의 피처로부터의 상대적인 위치를 기반으로 함",
    noSpatialLimitTip: "결과를 공간적으로 제한하지 않음",
    applySearchDistance: "검색 거리 적용",
    spatialRelationship: "공간 릴레이션십",
    relatedLayer: "릴레이트된 레이어",
    bufferDistance: "버퍼 거리",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    back: "뒤로",
    execute: "실행"
  })
);