define(
   ({
    _widgetLabel: "ניתוח מקרים",
    incident: "מקרה",
    weather: "מזג אויר",
    locate_incident: "אתר מקרים",
    clear_incidents: "נקה מקרים",
    reverse_geocoded_address: "הכתובת הקרובה ביותר",
    reverse_geocoded_error: "לא זמין",
    miles: "מיילים",
    kilometers: "קילומטרים",
    feet: "רגל",
    meters: "מטרים",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    now: "עכשיו",
    wind: "רוח",
    SUN: "א\'",
    MON: "ב\'",
    TUE: "ג\'",
    WED: "ד\'",
    THU: "ה\'",
    FRI: "ו\'",
    SAT: "שבת",
    defaultTabMsg: "לא זוהו מקרים.",
    actionLabel: "הגדר כמקרה",
    useMapExtent: "השתמש בתיחום המפה הנוכחי",
    noFeaturesFound: "לא נמצאו ישויות",
    downloadCSV: "הורד CSV",
    sum: "סכום",
    min: "מינימום",
    max: "מקסימום",
    avg: "ממוצע",
    count: "ספירה",
    area: "אזור",
    length: "אורך"
  })
);
