define(
   ({
    _widgetLabel: "שאילתה",
    executeQueryTip: "לחץ על אחד מפריטי המשימה הבאים כדי לבצע את השאילתא.",
    invalidConfig: "הגדרה לא תקינה. אנא השתמש בדף הגדרת שאילתא כדי לתקן את ההגדרה.",
    queryParams: "אפשרויות",
    parameters: "אפשרויות",
    queries: "שאילתות",
    apply: "בצע",
    queryResults: "תוצאות",
    clear: "נקה",
    noResults: "לא נמצאו ישויות",
    queryError: "השאילתא נכשלה !",
    numberFound: "מספר הישויות שנמצאו",
    mapExtentTip: "הגבל את התוצאות לאזור הנוכחי במפה.",
    noValue: "אין ערך",
    and: "וגם",
    stringOperatorIs: "הוא", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "אינו",
    stringOperatorStartsWith: "מתחיל עם",
    stringOperatorEndsWith: "מסתיים ב",
    stringOperatorContains: "מכיל",
    stringOperatorDoesNotContain: "לא מכיל",
    stringOperatorIsBlank: "ריק",
    stringOperatorIsNotBlank: "אינו ריק",
    dateOperatorIsOn: "הוא ב-", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "אינו ב-",
    dateOperatorIsBefore: "הוא לפני",
    dateOperatorIsAfter: "הוא אחרי",
    dateOperatorDays: "ימים",
    dateOperatorWeeks: "שבועות", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "חודשים",
    dateOperatorInTheLast: "בסוף",
    dateOperatorNotInTheLast: "לא בסוף",
    dateOperatorIsBetween: "בין",
    dateOperatorIsNotBetween: "לא נמצא בין",
    dateOperatorIsBlank: "ריק",
    dateOperatorIsNotBlank: "אינו ריק",
    numberOperatorIs: "הוא", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "אינו",
    numberOperatorIsAtLeast: "הוא לפחות",
    numberOperatorIsLessThan: "הוא פחות מ-",
    numberOperatorIsAtMost: "הוא לכל היותר",
    numberOperatorIsGreaterThan: "הוא גדול מ-",
    numberOperatorIsBetween: "בין",
    numberOperatorIsNotBetween: "לא נמצא בין",
    numberOperatorIsBlank: "ריק",
    numberOperatorIsNotBlank: "אינו ריק",
    operationalLayerTip: "הוסף תוצאה כשכבה תפעולית",
    queryResult: "תוצאות שאילתא",
    specifyParamsTip: "הגדר פרמטרים למשימה",
    useSpatialFilter: "השתמש בסינון מרחבי להגבלת יישויות",
    useCurrentMapExtent: "רק יישויות החותכות את האזור הנוכחי במפה",
    drawGraphicOnMap: "רק יישויות החותכות אזור המוגדר על-ידי המשתמש",
    specifySpatialFilterMsg: "הגדר בבקשה סינון למשימה הזו.",
    clearResults: "נקה תוצאות",
    operationalTip: 'כאשר האפשרות מסומנת, התוצאות יוצגו במפה עד שתלחץ על הכפתור \"${clearResults}\".',
    noneQueryTip: "לא הוגדרה משימת שאילתא עבור וידג\'ט זה.",
    noPermissionsMsg: "אין לך הרשאות לגשת לשירות זה.",
    attributesFromRelationship: "מאפיינים מטבלה קשורה",
    tasks: "משימות",
    applySpatialFilterToLimitResults: "יישם פילטר מרחבי כדי להגביל את התוצאות",
    useCurrentExtentTip: "חלקית או לחלוטין בתיחום המפה הנוכחי",
    useDrawGraphicTip: "חלקית או לחלוטין בגבולות הצורה המצוירת במפה",
    useFeaturesTip: "בהתבסס על המיקום שלהם ביחס לישויות בשכבה אחרת",
    noSpatialLimitTip: "ללא הגבלה מרחבית של התוצאות",
    applySearchDistance: "החל מרחק חיפוש",
    spatialRelationship: "קישור מרחבי",
    relatedLayer: "שכבה מקושרת",
    bufferDistance: "מרחק חיץ",
    miles: "מיילים",
    kilometers: "קילומטרים",
    feet: "רגל",
    meters: "מטרים",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    back: "אחורה",
    execute: "בצע"
  })
);