define(
   ({
    _widgetLabel: "שאילתה",
    executeQueryTip: "לחץ על אחד מפריטי המשימה הבאים כדי לבצע שאילתה.",
    invalidConfig: "הגדרה לא תקינה. אנא השתמש בדף הגדרת שאילתא כדי לתקן את ההגדרה.",
    queryParams: "אפשרויות",
    parameters: "אפשרויות",
    queries: "שאילתות",
    apply: "בצע",
    queryResults: "תוצאות",
    clear: "נקה",
    noResults: "לא נמצאו ישויות",
    queryError: "השאילתא נכשלה !",
    numberFound: "מספר הישויות שנמצאו",
    mapExtentTip: "הגבל את התוצאות לתיחום נוכחי של המפה.",
    noValue: "אין ערך",
    and: "וגם",
    stringOperatorIs: "הוא", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "אינו",
    stringOperatorStartsWith: "מתחיל עם",
    stringOperatorEndsWith: "מסתיים ב",
    stringOperatorContains: "מכיל",
    stringOperatorDoesNotContain: "לא מכיל",
    stringOperatorIsBlank: "ריק",
    stringOperatorIsNotBlank: "אינו ריק",
    dateOperatorIsOn: "הוא ב-", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "אינו ב-",
    dateOperatorIsBefore: "הוא לפני",
    dateOperatorIsAfter: "הוא אחרי",
    dateOperatorDays: "ימים",
    dateOperatorWeeks: "שבועות", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "חודשים",
    dateOperatorInTheLast: "בסוף",
    dateOperatorNotInTheLast: "לא בסוף",
    dateOperatorIsBetween: "בין",
    dateOperatorIsNotBetween: "לא נמצא בין",
    dateOperatorIsBlank: "ריק",
    dateOperatorIsNotBlank: "אינו ריק",
    numberOperatorIs: "הוא", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "אינו",
    numberOperatorIsAtLeast: "הוא לפחות",
    numberOperatorIsLessThan: "הוא פחות מ-",
    numberOperatorIsAtMost: "הוא לכל היותר",
    numberOperatorIsGreaterThan: "הוא גדול מ-",
    numberOperatorIsBetween: "בין",
    numberOperatorIsNotBetween: "לא נמצא בין",
    numberOperatorIsBlank: "ריק",
    numberOperatorIsNotBlank: "אינו ריק",
    operationalLayerTip: "הוסף תוצאה כשכבה תפעולית",
    queryResult: "תוצאות שאילתא",
    specifyParamsTip: "הגדר פרמטרים למשימה",
    useSpatialFilter: "השתמש בסינון מרחבי להגבלת יישויות",
    useCurrentMapExtent: "רק יישויות שנוגעות בהיקף המפה הנוכחית",
    drawGraphicOnMap: "רק יישויות שנוגעות באזור המוגדר על-ידי המשתמש",
    specifySpatialFilterMsg: "הגדר בבקשה סינון למשימה הזו.",
    clearResults: "נקה תוצאות",
    operationalTip: 'אם אפשרות זו בחורה התוצאות ישמרו על המפה עד הקלקה על כפתור "${clearResults}".',
    noneQueryTip: "פעולות תשאול מוגדרות מראש לא זמינות.",
    noPermissionsMsg: "אין לך הרשאות לגשת לשירות זה."
  })
);