define(
	 ({
		queries: "Tác vụ truy vấn",
		addNew: "Thêm Mới",
		setSource: "Thiết lập",
		setDataSource: "Thiết lập Nguồn Dữ liệu",
		name: "Tên",
		querySource: "Nguồn dữ liệu",
		queryName: "Tên tác vụ",
		queryDefinition: "Định nghĩa Bộ lọc",
		resultsSetting: "Thiết lập Kết quả",
		symbolSetting: "Thiết lập Ký hiệu",
		resultSettingTip: "Xác định nội dung và cách thức hiển thị kết quả đầu ra.",
		resultItemTitle: "Tiêu đề Mục Kết quả",
		resultItemContent: "Nội dung Mục Kết quả",
		fieldsSetTip: "Chọn các trường mà bạn muốn hiển thị. Chọn một trường để cập nhật bí danh, thứ tự và định dạng của trường đó.",
		addField: "Thêm Trường",
		visibility: "Khả năng hiển thị",
		alias: "Bí danh",
		specialType: "Loại đặc biệt",
		actions: "Các hành động",
		none: "Không có",
		link: "Liên kết",
		image: "Hình ảnh",
		noField: "Không có trường nào",
		operationalLayerTip: "Thêm kết quả như lớp hoạt động",
		setLayerSymbolTip: "Thiết lập ký hiệu cho kết quả truy vấn: ",
		setSelectedSymbolTip: "Thiết lập ký hiệu của đối tượng được chọn.",
		notUseFilter: "Không sử dụng bộ lọc",
		setSourceTip: "Vui lòng thiết lập nguồn truy vấn.",
		setFilterTip: "Vui lòng thiết lập bộ lọc chính xác.",
		ok: "OK",
		cancel: "Hủy",
		noFilterTip: "Nếu biểu thức bộ lọc không được xác định, tác vụ truy vấn này sẽ liệt kê tất cả các đối tượng trong nguồn dữ liệu đã chỉ định."
  })
);