define(
	 ({
		queries: "Tác vụ truy vấn",
		addNew: "Thêm Mới",
    queryLayer: "Lớp Truy vấn",
		setSource: "Thiết lập",
		setDataSource: "Thiết lập Nguồn Dữ liệu",
		name: "Tên",
		querySource: "Nguồn dữ liệu",
		queryName: "Tên tác vụ",
		queryDefinition: "Định nghĩa Bộ lọc",
		resultsSetting: "Thiết lập Kết quả",
		symbolSetting: "Thiết lập Ký hiệu",
		resultSettingTip: "Xác định nội dung và cách thức hiển thị kết quả đầu ra.",
		resultItemTitle: "Tiêu đề Mục Kết quả",
		resultItemContent: "Nội dung Mục Kết quả",
		fieldsSetTip: "Chọn các trường mà bạn muốn hiển thị. Chọn một trường để cập nhật bí danh, thứ tự và định dạng của trường đó.",
		addField: "Thêm Trường",
		visibility: "Khả năng hiển thị",
		alias: "Bí danh",
		specialType: "Loại đặc biệt",
		actions: "Các hành động",
		none: "Không có",
		link: "Liên kết",
		image: "Hình ảnh",
		noField: "Không có trường nào",
		operationalLayerTip: "Thêm kết quả như lớp hoạt động",
		setLayerSymbolTip: "Thiết lập ký hiệu cho kết quả truy vấn: ",
		setSelectedSymbolTip: "Thiết lập ký hiệu của đối tượng được chọn.",
		notUseFilter: "Không sử dụng bộ lọc",
		setSourceTip: "Vui lòng thiết lập nguồn truy vấn.",
		setFilterTip: "Vui lòng thiết lập bộ lọc chính xác.",
		ok: "OK",
		cancel: "Hủy",
		noFilterTip: "Nếu biểu thức bộ lọc không được xác định, tác vụ truy vấn này sẽ liệt kê tất cả các đối tượng trong nguồn dữ liệu đã chỉ định.",
    relationships: "Mối quan hệ",
    addRelationshipLayer: "Thêm Mối Quan hệ Mới",
    relatedTo: "Liên quan đến",
    selectOption: "Vui lòng chọn..",
    resultItemSorting: "Sắp xếp Mục Kết quả",
    field: "Trường",
    sortingOrder: "Thứ tự",
    configureFieldsTip: "Vui lòng cấu hình các trường dùng để sắp xếp truy vấn.",
    setSortingFields: "Thiết lập Trường Sắp xếp",
    ascending: "Tăng dần",
    descending: "Giảm dần",
    sortBy: "Sắp xếp theo",
    thenBy: "Sau đó theo",
    addTask: "Thêm tác vụ",
    noTasksTip: 'Chưa có tác vụ, vui lòng bấm \"${addTask}\" để bắt đầu!',
    infoText: "Thông tin",
    filters: "Bộ lọc",
    results: "Kết quả",
    optionsText: "Tùy chọn",
    summaryText: "Tóm tắt",
    attributeFilter: "Bộ lọc Thuộc tính",
    attributeFilterTip: "Xác định biểu thức thuộc tính sử dụng trong tiện ích để lọc lớp truy vấn.",
    noExpressionDefinedTip: "Chưa xác định biểu thức nào.",
    needInputValuesTip: "Cần phải nhập các giá trị tại runtime",
    setExpressions: "Thiết lập Biểu thức",
    spatialFilter: "Bộ lọc Không gian",
    spatialFilterTip: "Chọn (các) bộ lọc không gian được sử dụng trong tiện ích để giới hạn kết quả.",
    defaultOption: "Mặc định",
    useCurrentExtentTip: "Từng phần hoặc toàn bộ trong kích thước bản đồ hiện tại",
    useDrawGraphicTip: "Từng phần hoặc toàn bộ trong hình dạng đã được vẽ trên bản đồ",
    useFeaturesTip: "Dựa trên vị trí của chúng liên quan đến các đối tượng trong lớp khác",
    noSpatialLimitTip: "Không giới hạn các kết quả theo không gian",
    drawingTools: "Công cụ vẽ",
    bufferSettings: "Cài đặt Vùng đệm",
    defaultDistance: "Khoảng cách Mặc định",
    bufferDistance: "Khoảng cách Đệm",
    defaultUnit: "Đơn vị Mặc định",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Feet",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    availableSpatialRelationships: "Mối quan hệ Không gian Hiện có",
    setSpatialRelationships: "Thiết lập Mối quan hệ Không gian",
    availability: "Mức độ khả dụng",
    relationship: "Mối quan hệ",
    label: "Nhãn",
    intersect: "giao cắt",
    contain: "bao gồm",
    areContainedIn: "được bao gồm trong",
    cross: "gạch ngang",
    envelopeIntersect: "đường bao giao cắt",
    overlap: "xếp chồng",
    areOverlapped: "bị xếp chồng",
    touche: "tiếp xúc",
    within: "bên trong",
    areWithin: "ở bên trong",
    indexIntersect: "chỉ số giao cắt",
    itemTitle: "Tiêu đề Mục",
    displayFields: "Trường Hiển thị",
    sortingFields: "Trường Sắp xếp",
    setDisplayFields: "Thiết lập Trường Hiển thị",
    symbol: "Ký hiệu",
    setSymbol: "Thiết lập ký hiệu",
    serviceSymbolTip: "Sử dụng các ký hiệu do lớp xác định",
    exportTip: "Hiển thị nút Xuất",
    keepResultsTip: "Lưu kết quả trên bản đồ sau khi đóng tiện ích",
    queryRelatedRecords: "Bản ghi liên quan đến truy vấn",
    createLayerForTaskTip: "Xác định cách tạo lớp của tác vụ",
    oneLayerForTaskTip: "Chỉ tạo một lớp cho tác vụ này",
    multipleLayerForTaskTip: "Tạo lớp mới mỗi khi tác vụ này thực hiện"
  })
);
