define(
   ({
    _widgetLabel: "Ανάλυση περιστατικού",
    incident: "Συμβάν",
    weather: "Καιρός",
    locate_incident: "Εντοπισμός περιστατικού",
    clear_incidents: "Απαλοιφή περιστατικών",
    reverse_geocoded_address: "Πλησιέστερη διεύθυνση",
    reverse_geocoded_error: "Μη διαθέσιμη",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    now: "ΤΩΡΑ",
    wind: "WIND",
    SUN: "ΚΥΡ",
    MON: "ΔΕΥ",
    TUE: "ΤΡΙ",
    WED: "ΤΕΤ",
    THU: "ΠΕΜ",
    FRI: "ΠΑΡ",
    SAT: "ΣΑΒ",
    defaultTabMsg: "Δεν εντοπίστηκαν περιστατικά.",
    actionLabel: "Ορίστε ως περιστατικό",
    useMapExtent: "Χρήση της τρέχουσας έκτασης χάρτη",
    noFeaturesFound: "Δεν βρέθηκαν στοιχεία.",
    downloadCSV: "ΛΗΨΗ CSV",
    sum: "ΑΘΡ",
    min: "ΕΛΑΧ",
    max: "ΜΕΓ.",
    avg: "Μ.Ο.",
    count: "ΠΛΗΘΟΣ",
    area: "ΠΕΡΙΟΧΗ",
    length: "ΜΗΚΟΣ"
  })
);
