define(
   ({
    "tabs_section_Label": "탭",
    "addTab": "탭 추가",
    "layerName": "레이어",
    "layerType": "분석 유형",
    "layerLabel": "레이블",
    "actions": "동작",
    "closest": "가장 가까운 피처",
    "proximity": "인접도",
    "summary": "요약",
    "select_lbl": "-- 선택 --",
    "general_setting_Label": "일반 설정",
    "units_text_lbl": "거리 단위",
    "miles": "마일",
    "kilometers": "킬로미터",
    "feet": "피트",
    "meters": "미터",
    "yards": "야드",
    "nauticalMiles": "해리",
    "maximum_distance_lbl": "가장 가까운 피처 최대 거리",
    "buffer_text_lbl": "버퍼 레이블",
    "buffer_lbl": "버퍼 거리",
    "buffer_max_lbl": "최대 버퍼 거리",
    "buffer_min_lbl": "최소 버퍼 거리",
    "routing_checkBox": "경로 지정 활성화",
    "weather_Label": "날씨 옵션",
    "weather_checkBox": "날씨 정보 포함",
    "selectLayers": "날씨 레이어 선택",
    "currentlySelectedLayer": "현재 선택된 날씨 레이어",
    "missingTabLabel": "하나 이상의 탭에 레이블이 누락됨",
    "cancel": "취소",
    "ok": "확인",
    "missingLayerInWebMap": "운영 레이어를 찾을 수 없습니다.",
    "selectFields": "필드 선택",
    "addField": "필드 추가",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "개수 보기",
    "area_checkBox": "면적 보기",
    "length_checkBox": "길이 보기",
    "max_records": "최대 제한 도달"
  })
);
