define({
  root: ({
    _widgetLabel: "Report Feature",
    select: "Select",
    draw: "Draw",
    chooseALayer: "Select a layer",
    clickAFeature: "Click on a feature on the map to select it.",
    loadingFeatures: "Getting selected feature details...",
    errorTitle: "Error",
    errorIdentify: "Identify features error. Please check console log for details.",
    infoWindowTitle: "Details",
    layerLabel: "Layer Name",
    reviewStatusLabel: "Review Status",
    selectReviewStatusAdd: "Add Feature",
    selectReviewStatusDelete: "Delete Feature",
    selectReviewStatusMove: "Move Feature",
    selectReviewStatusReshape: "Reshape Feature",
    drawReviewStatusMissing: "Missing Feature(s)",
    drawReviewStatusPosition: "Positional Error",
    drawReviewStatusShape: "Shape Error",
    drawReviewStatusAttribute: "Attribute Error",
    notesLabel: "Notes",
    severityLabel: "Severity",
    reportedByLabel: "Reported By",
    reportedByDefault: "anonymous",
    reportButton: "Report",
    reportMessage: "Report received",
    errorReportMessage: "There was an error reporting your feature",
    drawErrorInstructions: "Select point, line or polygon and draw the error geometry on the map:",
    errorMapService: "There was an error getting map service information",
    noFeatureSelected : "There were no features found at the clicked location",
    selectFeatureMapPoint: "Click to select a feature",
    drawFeatureMapPoint: "Click to add a point",
    popupMessage:"Message",
    popupError:"Error",
    manyFeaturesSelected: "More than one feature found. Please zoom in and select a feature to report."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
