define(
   ({
    _widgetLabel: "Abfrage",
    executeQueryTip: "Klicken Sie auf einen der folgenden Tasks, um die Abfrage auszuführen.",
    invalidConfig: "Ungültige Konfiguration. Verwenden Sie die Seite für Abfrageeinstellungen, um die richtige Konfiguration abzurufen.",
    queryParams: "Optionen",
    parameters: "OPTIONEN",
    queries: "ABFRAGEN",
    apply: "ÜBERNEHMEN",
    queryResults: "Ergebnisse",
    clear: "Löschen",
    noResults: "Kein Feature gefunden.",
    queryError: "Abfrage fehlgeschlagen!",
    numberFound: "Anzahl der gefundenen Features",
    mapExtentTip: "Beschränken Sie die Ergebnisse auf die aktuelle Kartenausdehnung.",
    noValue: "Kein Wert",
    and: "und",
    stringOperatorIs: "ist", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ist nicht",
    stringOperatorStartsWith: "beginnt mit",
    stringOperatorEndsWith: "endet mit",
    stringOperatorContains: "enthält",
    stringOperatorDoesNotContain: "enthält nicht",
    stringOperatorIsBlank: "ist leer",
    stringOperatorIsNotBlank: "ist nicht leer",
    dateOperatorIsOn: "ist am", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ist nicht am",
    dateOperatorIsBefore: "ist vor",
    dateOperatorIsAfter: "ist nach",
    dateOperatorDays: "Tagen",
    dateOperatorWeeks: "Wochen", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "Monate",
    dateOperatorInTheLast: "in den letzten",
    dateOperatorNotInTheLast: "nicht in den letzten",
    dateOperatorIsBetween: "liegt zwischen",
    dateOperatorIsNotBetween: "liegt nicht zwischen",
    dateOperatorIsBlank: "ist leer",
    dateOperatorIsNotBlank: "ist nicht leer",
    numberOperatorIs: "ist", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ist nicht",
    numberOperatorIsAtLeast: "ist mindestens",
    numberOperatorIsLessThan: "ist kleiner als",
    numberOperatorIsAtMost: "ist höchstens",
    numberOperatorIsGreaterThan: "ist größer als",
    numberOperatorIsBetween: "liegt zwischen",
    numberOperatorIsNotBetween: "liegt nicht zwischen",
    numberOperatorIsBlank: "ist leer",
    numberOperatorIsNotBlank: "ist nicht leer",
    operationalLayerTip: "Ergebnis als operationalen Layer hinzufügen",
    queryResult: "Abfrageergebnis",
    specifyParamsTip: "Parameter für diesen Task festlegen",
    useSpatialFilter: "Räumlichen Filter zum Begrenzen von Features verwenden",
    useCurrentMapExtent: "Nur Features, die in der aktuellen Kartenausdehnung liegen",
    drawGraphicOnMap: "Nur Features, die in einem benutzerdefinierten Bereich liegen",
    specifySpatialFilterMsg: "Geben Sie einen räumlichen Filter für diesen Task an.",
    clearResults: "Ergebnisse löschen",
    operationalTip: 'Wenn diese Option aktiviert ist, werden die Ergebnisse auf der Karte beibehalten, bis auf die Schaltfläche \"${clearResults}\" geklickt wird.',
    noneQueryTip: "Es sind keine vorkonfigurierten Abfrage-Tasks verfügbar.",
    noPermissionsMsg: "Sie verfügen nicht über die entsprechenden Berechtigungen für den Zugriff auf diesen Service."
  })
);