define(
   ({
    routeUrl: "Routen-URL",
    locatorUrl: "Geocoder-URL",
    geocoderOptions: "Geocoder-Optionen",
    autoComplete: "Automatisch vervollständigen",
    maxLocations: "Maximale Anzahl von Positionen",
    minCharacters: "Minimale Anzahl von Zeichen",
    searchDelay: "Suchverzögerung",
    placeholder: "Platzhalter",
    routeOptions: "Routen-Optionen",
    directionsLanguage: "Sprache für Wegbeschreibung",
    directionsLengthUnits: "Längeneinheiten für Wegbeschreibung",
    directionsOutputType: "Ausgabetyp der Wegbeschreibung",
    impedanceAttribute: "Impedanzattribut",
    kilometers: "Kilometer",
    miles: "Meilen",
    meters: "Meter",
    feet: "Fuß",
    yards: "Yards",
    nauticalMiles: "Seemeilen",
    parametersTip: "Legen Sie die Parameter ordnungsgemäß fest!",
    complete: "Abgeschlossen",
    completeNoEvents: "Ohne Ereignisse abgeschlossen",
    instructionsOnly: "Nur Anweisungen",
    standard: "Standard",
    summaryOnly: "Nur Zusammenfassung",
    travelModesUrl: "URL zu Reisemodi",
    searchPlaceholder: "Adresse oder Ort suchen",
    trafficLayerUrl: "URL des Verkehrsdaten-Layers"
  })
);