define(
   ({
    selectAnalysisTools:"Pasirinkite analizės įrankius, kurie bus nurodyti valdiklyje.",
    selected: "pasirinkta",
    name: "Pavadinimas",
    graphicalDisplay:"Grafinis vaizdas",
    usage: "Naudojimas",
    toolNotAvailable: "Šis įrankis nepasiekiamas, nes žemėlapyje nėra reikiamo elemento sluoksnio (-ių).",
    aggregatePoints:"Agreguoti taškus",
    aggregatePointsUsage:"Agreguoti taškus pagal poligonus, į kuriuos patenka šie taškai.",
    aggregatePointsInputTip: "Nurodykite taško elementų sluoksnį, kuris bus agreguotas į poligonus poligonų elementų sluoksnyje .",
    calculateDensity:"Apskaičiuoti tankį",
    calculateDensityUsage:"Sukurkite tankio žemėlapį iš taškų ir linijų  išskleidžiant žemėlapyje tam tikrų reiškinių (pateikiamų kaip taškų arba linijų atributai) žinomus kiekius.",
    calculateDensityInputTip:"Nurodykite taškus arba linijas, pagal kuriuos skaičiuoti tankį.",
    connectOriginsToDestinations: "Jungti iÅvykimo vietas su atvykimo vietomis",
    connectOriginsToDestinationsUsage: "Matuokite kelionės laiką arba atstumą tarp taškų poros.",
    connectOriginsToDestinationsInputTip: "Nurodykite maršruto, kurį norite generuoti, pradžios tašką arba taškus.",
    createBuffers:"Kurti buferius",
    createBuffersUsage:"Kurkite buferinius poligonus iš įvesties elementų.",
    createBuffersInputTip:"Nurodykite taškų, linijų arba poligonų sluoksnį, pagal kurį norite kurti buferį.",
    createDriveTimeAreas:"Sukurti važiavimo laikų plotus",
    createDriveTimeAreasUsage:"Kurkite apie įvesties taškus nurodyto važiavimo laiko verčių važiavimo laiko (arba važiavimo atstumo) poligonus.",
    createDriveTimeAreasInputTip:"Nurodykite taškus, per kuriuos bus brėžiamos važiavimo laiko sritys.",
    createViewshed:"Matymo lauko kÅ«rimas",
    createViewshedUsage:"Sukuria plotus, kurie matomi remiantis jÅ«sÅ³ nurodytomis vietomis.",
    createViewshedInputTip:"Nurodykite stebėtojo vietas, kad būtų galima identifikuoti matomus plotus.",
    createWatersheds:"Kurti upiÅ³ baseinus",
    createWatershedsUsage:"Sukuria upiÅ³ baseinÅ³ plotus remiantis jÅ«sÅ³ nurodytomis vietomis.",
    createWatershedsInputTip:"Nurodykite taškų elementus, naudojamus skaičiuojant baseinus.",
    deriveNewLocations:"Nustatyti naujas vietas",
    deriveNewLocationsUsage:"Nustatykite naujus elementus iš įvesties sluoksnių, atitinkančių jūsų apibrėžtą užklausą",
    deriveNewLocationsInputTip:"Nurodykite analizės sluoksnį, naudojamą kaip įvestį.",
    dissolveBoundaries:"Tirpdyti ribas",
    dissolveBoundariesUsage:"Tirpdykite poligonus, kurie persidengia arba dalijasi bendra riba.",
    dissolveBoundariesInputTip:"Nurodykite sluoksnį, kuriame yra tirpdytino poligono elementų.",
    enrichLayer:"Praturtinti sluoksnÄÆ",
    enrichLayerUsage:"Praturtinkite įvesties elementus sociologiniais, demografiniais ir ekonominiais faktais apie šalia esančius plotus.",
    enrichLayerInputTip:"Nurodykite elementus, kuriuose norite praturtinti naujais duomenimis.",
    extractData:"AtsisiÅ³sti duomenis",
    extractDataDesc:"Atsisiųskite nurodytos aprėpties duomenis iš vieno arba kelių sluoksnių",
    extractDataInputTip:"Nurodykite atsisiunčiamą įvesties elementų sluoksnį.",
    findExistingLocations:"Rasti esamas vietas",
    findExistingLocationsUsage:"Įvesties sluoksnyje pažymimi elementai, atitinkantys nurodytą atributų ir (arba) erdvinę užklausą",
    findExistingLocationsInputTip:"Nurodykite, kuriuos analizės sluoksnius naudoti kaip įvestį.",
    findHotSpots:"Rasti aktyvius židinius",
    findHotSpotsUsage:"Raskite statistiškai svarbias įvesties elementų arba jų atributų didžiausių / mažiausių reikšmių sankaupas.",
    findHotSpotsInputTip:"Nurodykite taško arba poligono elementų sluoksnį, kurio aktyvūs židiniai bus skaičiuojami.",
    findNearest:"Rasti artimiausiÄ…",
    findNearestUsage:"Raskite kiekvieno elemento įvesties sluoksnyje artimiausią elementą arba kitą sluoksnį",
    findNearestInputTip:"Nurodykite taškus, linijas arba poligonus, nuo kurių aptinkamos artimiausios vietos.",
    findSimilarLocations:"Rasti panašias vietas",
    findSimilarLocationsUsage:"Matuokite vietų panašumą pagal vieną ar kelias pavyzdines vietas.",
    findSimilarLocationsInputTip:"Nurodykite elementų sluoksnį, kuriame yra viena arba kelios pavyzdinės vietos, pagal kurias bus vertinamas paieškos sluoksnio elementų panašumas.",
    interpolatePoints:"Interpoliuoti taškus",
    interpolatePointsUsage:"Prognozuokite reikšmes naujose vietose pagal taškų rinkinio matavimus.",
    interpolatePointsInputTip:"Nurodykite interpoliuojamus taško elementus.",
    mergeLayers:"Sulieti sluoksnius",
    mergeLayersUsage:"Suliekite kelių sluoksnių elementus į naują sluoksnį",
    mergeLayersInputTip:"Nurodykite elementų sluoksnį, kuris bus sulietas su suliejimo sluoksniu.",
    overlayLayers:"Perdengti sluoksnius",
    overlayLayersUsage:"Derinkite kelis sluoksnius viename, išlaikydami pradinių sluoksnių informaciją.",
    overlayLayersInputTip:"Nurodykite elementų sluoksnį, kuris bus perdengtas perdengimo sluoksniu.",
    planRoutes:"Planuoti marÅrutus",
    planRoutesUsage:"Nustatykite, kaip efektyviai paskirstyti užduotis mobiliems darbuotojams.",
    planRoutesInputTip:"Nurodykite taškus, kuriuos turi pasiekti automobilis, vairuotojas arba eiti maršrutas.",
    summarizeNearby:"Sumuoti Åalia",
    summarizeNearbyUsage:"Kiekviename įvesties sluoksnio elemente sumuokite kito sluoksnio elementų, esančių tam tikru atstumu, duomenis.",
    summarizeNearbyInputTip:"Nurodykite taškų, linijų ar poligonų sluoksnį, nuo kurio elementų bus matuojamas atstumas iki suminio sluoksnio elementų.",
    summarizeWithin:"Sumuoti viduje",
    summarizeWithinUsage:"Kiekviename įvesties poligonų sluoksnio poligone sumuokite jame esančius kito sluoksnio elementų duomenis.",
    summarizeWithinInputTip:"Nurodykite poligonų elementų sluoksnį, kuris bus sumuojamas.",
    traceDownstream:"Trasuoti pasroviui",
    traceDownstreamUsage:"Nustato tėkmes, esančias pasroviui nuo jūsų nurodytų vietų.",
    traceDownstreamInputTip:"Nurodykite trasavimo pasroviui pradžios taško elementus."
  })
);
