define(
   ({
    selectAnalysisTools:"Pasirinkite analizės įrankius, kurie naudojami valdiklyje.",
    selected: "pasirinkta",
    name: "Pavadinimas",
    graphicalDisplay:"Grafinis vaizdas",
    usage: "Naudojimas",
    settings: "Nustatymai",
    toolSetting: "Įvesti įrankio informaciją",
    toolLabel: "Įrankio pavadinimas",
    showHelpTip: "Rodyti pagalbos nuorodą valdiklyje",
    showCurrentMapExtent: "Rodyti parinktį, leidžiančią naudoti esamo žemėlapio aprėptį",
    showCredits: "Rodyti parinktį <b>Rodyti kreditus</b>",
    saveAsFeatureService: "Įrašyti rezultatą vartotojo paskyroje",
    showReadyToUseLayers: "Rodyti naudotinus sluoksnius iš ArcGIS Online pasaulio atlaso",
    toolNotAvailable: "Šis įrankis nepasiekiamas, nes žemėlapyje nėra reikiamo elemento sluoksnio (-ių).",
    aggregatePoints:"Agreguoti taškus",
    aggregatePointsUsage:"Agreguoti taškus pagal poligonus, į kuriuos patenka šie taškai.",
    calculateDensity:"Apskaičiuoti tankį",
    calculateDensityUsage:"Sukurkite tankio žemėlapį iš taškų ir linijų  išskleidžiant žemėlapyje tam tikrų reiškinių (pateikiamų kaip taškų arba linijų atributai) žinomus kiekius.",
    connectOriginsToDestinations: "Jungti išvykimo vietas su atvykimo vietomis",
    connectOriginsToDestinationsUsage: "Matuokite kelionės laiką arba atstumą tarp taškų poros.",
    createBuffers:"Kurti buferius",
    createBuffersUsage:"Kurkite buferinius poligonus iš įvesties elementų.",
    createDriveTimeAreas:"Sukurti važiavimo laikų plotus",
    createDriveTimeAreasUsage:"Kurkite apie įvesties taškus nurodyto važiavimo laiko verčių važiavimo laiko (arba važiavimo atstumo) poligonus.",
    createViewshed:"Matymo lauko kūrimas",
    createViewshedUsage:"Sukuria plotus, kurie matomi remiantis jūsų nurodytomis vietomis.",
    createWatersheds:"Kurti upių baseinus",
    createWatershedsUsage:"Sukuria upių baseinų plotus remiantis jūsų nurodytomis vietomis.",
    deriveNewLocations:"Nustatyti naujas vietas",
    deriveNewLocationsUsage:"Nustatykite naujus elementus iš įvesties sluoksnių, atitinkančių jūsų apibrėžtą užklausą",
    dissolveBoundaries:"Tirpdyti ribas",
    dissolveBoundariesUsage:"Tirpdykite poligonus, kurie persidengia arba dalijasi bendra riba.",
    enrichLayer:"Praturtinti sluoksnį",
    enrichLayerUsage:"Praturtinkite įvesties elementus sociologiniais, demografiniais ir ekonominiais faktais apie šalia esančius plotus.",
    extractData:"Atsisiųsti duomenis",
    extractDataDesc:"Atsisiųskite nurodytos aprėpties duomenis iš vieno arba kelių sluoksnių",
    findExistingLocations:"Rasti esamas vietas",
    findExistingLocationsUsage:"Įvesties sluoksnyje pažymimi elementai, atitinkantys nurodytą atributų ir (arba) erdvinę užklausą",
    findHotSpots:"Rasti aktyvius židinius",
    findHotSpotsUsage:"Raskite statistiškai svarbias įvesties elementų arba jų atributų didžiausių / mažiausių reikšmių sankaupas.",
    findNearest:"Rasti artimiausią",
    findNearestUsage:"Raskite kiekvieno elemento įvesties sluoksnyje artimiausią elementą arba kitą sluoksnį",
    findSimilarLocations:"Rasti panašias vietas",
    findSimilarLocationsUsage:"Matuokite vietų panašumą pagal vieną ar kelias pavyzdines vietas.",
    interpolatePoints:"Interpoliuoti taškus",
    interpolatePointsUsage:"Prognozuokite reikšmes naujose vietose pagal taškų rinkinio matavimus.",
    mergeLayers:"Sulieti sluoksnius",
    mergeLayersUsage:"Suliekite kelių sluoksnių elementus į naują sluoksnį",
    overlayLayers:"Perdengti sluoksnius",
    overlayLayersUsage:"Derinkite kelis sluoksnius viename, išlaikydami pradinių sluoksnių informaciją.",
    planRoutes:"Planuoti maršrutus",
    planRoutesUsage:"Nustatykite, kaip efektyviai paskirstyti užduotis mobiliems darbuotojams.",
    summarizeNearby:"Sumuoti šalia",
    summarizeNearbyUsage:"Kiekviename įvesties sluoksnio elemente sumuokite kito sluoksnio elementų, esančių tam tikru atstumu, duomenis.",
    summarizeWithin:"Sumuoti viduje",
    summarizeWithinUsage:"Kiekviename įvesties poligonų sluoksnio poligone sumuokite jame esančius kito sluoksnio elementų duomenis.",
    traceDownstream:"Trasuoti pasroviui",
    traceDownstreamUsage:"Nustato tėkmes, esančias pasroviui nuo jūsų nurodytų vietų."
  })
);
