define(
   ({
    selectAnalysisTools:"選擇要在 widget 中使用的分析工具。",
    selected: "選取",
    name: "名稱",
    graphicalDisplay:"以圖形方式顯示",
    usage: "使用情況",
    settings: "設定",
    toolSetting: "設定工具詳細資訊",
    toolLabel: "工具顯示名稱",
    showHelpTip: "在 widget 中顯示説明連結",
    showCurrentMapExtent: "顯示選項來使用目前的地圖範圍",
    showCredits: "顯示<b>顯示點數</b>選項",
    saveAsFeatureService: "在使用者帳戶中儲存結果",
    showReadyToUseLayers: "顯示 ArcGIS Online 生動世界地圖集的即用型圖層",
    toolNotAvailable: "由於地圖不包含所需的圖徵圖層，因此此工具無法使用。",
    aggregatePoints:"匯聚點",
    aggregatePointsUsage:"將點匯聚到這些點所在的面中。",
    calculateDensity:"計算密度",
    calculateDensityUsage:"透過展開地圖範圍內現象(表示為點或線的屬性)的已知數量，根據點圖徵或線圖徵建立密度圖。",
    connectOriginsToDestinations: "連接起始點和目的地",
    connectOriginsToDestinationsUsage: "測量兩點之間的行駛時間或距離。",
    createBuffers:"建立環域",
    createBuffersUsage:"根據輸入圖徵建立環域面。",
    createDriveTimeAreas:"建立行駛時間區域",
    createDriveTimeAreasUsage:"根據給定的行駛時間值，圍繞輸入點建立行駛時間(或行駛距離)面。",
    createViewshed:"建立視域",
    createViewshedUsage:"根據指定位置建立可見的區域。",
    createWatersheds:"建立分水嶺",
    createWatershedsUsage:"根據指定的位置建立集水區。",
    deriveNewLocations:"衍生新位置",
    deriveNewLocationsUsage:"從符合您所指定的查詢輸入圖層衍生新圖徵",
    dissolveBoundaries:"融合邊界",
    dissolveBoundariesUsage:"融合重疊或共用公用邊界的面。",
    enrichLayer:"豐富化圖層",
    enrichLayerUsage:"透過附近區域的人員、位置和商業資訊豐富化輸入的圖徵。",
    extractData:"萃取資料",
    extractDataDesc:"從給定範圍內的一個或多個圖層萃取資料",
    findExistingLocations:"尋找現有位置",
    findExistingLocationsUsage:"選擇輸入圖層內滿足您指定的屬性和/或空間查詢的圖徵",
    findHotSpots:"尋找熱點",
    findHotSpotsUsage:"尋找具有統計顯著性的輸入圖徵聚類或高/低值。",
    findNearest:"尋找最近點",
    findNearestUsage:"針對輸入圖層上的每個圖徵尋找另一圖層上與其最近的圖徵",
    findSimilarLocations:"尋找相似位置",
    findSimilarLocationsUsage:"衡量候選位置與一個或多個參考位置的相似性。",
    interpolatePoints:"內插點",
    interpolatePointsUsage:"根據從點集合進行的測量得出新位置的預測值。",
    mergeLayers:"合併圖層",
    mergeLayersUsage:"將多個圖層中的圖徵合併到一個新圖層中",
    overlayLayers:"圖層套疊",
    overlayLayersUsage:"透過原始圖層中保留的資訊將多個圖層合併到一個圖層中。",
    planRoutes:"規劃路徑",
    planRoutesUsage:"確定在行動人力中有效劃分任務的方法。",
    summarizeNearby:"鄰近摘要",
    summarizeNearbyUsage:"針對輸入圖層上的每個圖徵，摘要在另一圖層上，距圖徵特定範圍內的資料。",
    summarizeWithin:"範圍內摘要",
    summarizeWithinUsage:"針對輸入面圖層上的每個面，摘要該範圍內來自另一圖層上的圖徵的資料。",
    traceDownstream:"網路下溯追蹤",
    traceDownstreamUsage:"確定以您指定的位置為起點的下游方向中的流動路徑。"
  })
);
