define(
   ({
    routeUrl: "URL da Rota",
    locatorUrl: "URL do Geocodificador",
    geocoderOptions: "Opções do geocodificador",
    autoComplete: "Auto Completar",
    maxLocations: "Máximo de locais",
    minCharacters: "Mínimo de caracteres",
    searchDelay: "Atraso de pesquisa",
    placeholder: "Espaço Reservado",
    routeOptions: "Opções da rota",
    directionsLanguage: "Idioma das direções",
    directionsLengthUnits: "Unidades de comprimento das direções",
    directionsOutputType: "Tipo de saída das direções",
    impedanceAttribute: "Atributo de impedância",
    kilometers: "Quilômetros",
    miles: "Milhas",
    meters: "Metros",
    feet: "Pés",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    parametersTip: "Configure parâmetros corretamente !",
    complete: "Completo",
    completeNoEvents: "Completar Sem Eventos",
    instructionsOnly: "Instruções Somente",
    standard: "Padrão",
    summaryOnly: "Resumo Somente",
    travelModesUrl: "URL de Modos de Viagem",
    searchPlaceholder: "Encontrar endereço ou lugar",
    trafficLayerUrl: "URL da Camada de Tráfego"
  })
);