define({
  root: ({
    enableUndoRedo: "Enable Undo/Redo",
    toolbarVisible: "Toolbar Visible",
    toolbarOptions: "Toolbar Options",
    mergeVisible: "Merge",
    cutVisible: "Cut",
    reshapeVisible: "Reshape",
    back: "Back",
    label: "Layer",
    edit: "Editable",
    update: "Disable Update Geometry",
    fields: "Fields",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    editpageVisible: "Visible",
    editpageEditable: "Editable",
    noLayers: "No editable feature layers are available",
    configureFields: "Configure Layer Fields"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});