define(
   ({
    selectAnalysisTools:"Selezionare gli strumenti di analisi da elencare nel widget.",
    selected: "selezionato",
    name: "Nome",
    graphicalDisplay:"Visualizzazione grafica",
    usage: "Utilizzo",
    toolNotAvailable: "Questo strumento non è disponibile perché la mappa non contiene i feature layer richiesti.",
    aggregatePoints:"Aggrega punti",
    aggregatePointsUsage:"Aggrega i punti nei poligoni in cui si trovano tali punti.",
    aggregatePointsInputTip: "Specificare il feature layer punto che verrà aggregato nei poligoni nel feature layer poligono.",
    calculateDensity:"Calcolo densità",
    calculateDensityUsage:"Creare una mappa densità dalle feature puntuali o lineari distribuendo quantità conosciute di un fenomeno (rappresentato come attributi dei punti o delle linee) sulla mappa.",
    calculateDensityInputTip:"Specificare le feature puntuali o lineari in base alle quali calcolare la densità.",
    connectOriginsToDestinations: "Connetti origini a destinazioni",
    connectOriginsToDestinationsUsage: "Consente di misurare la durata o la distanza del viaggio da coppie di punti.",
    connectOriginsToDestinationsInputTip: "Specificare il punto o i punti iniziali degli itinerari da generare.",
    createBuffers:"Crea buffer",
    createBuffersUsage:"Consente di creare poligoni buffer dalle feature di input.",
    createBuffersInputTip:"Specificare il feature layer punto, linea o poligono da definire come buffer.",
    createDriveTimeAreas:"Crea aree tempo di guida",
    createDriveTimeAreasUsage:"Consente di creare poligoni relativi al tempo di guida (o distanza di guida) attorno ai punti di input per i valori del tempo di guida specificati.",
    createDriveTimeAreasInputTip:"Specificare i punti in cui verranno tracciate le aree del tempo di guida.",
    createViewshed:"Crea campo di vista",
    createViewshedUsage:"Consente di creare aree visibili in base alle posizioni specificate.",
    createViewshedInputTip:"Specificare le posizioni dell\'osservatore per identificare le aree visibili.",
    createWatersheds:"Crea spartiacque",
    createWatershedsUsage:"Consente di creare aree di bacini fluviali in base alle posizioni specificate.",
    createWatershedsInputTip:"Specificare le feature puntuali utilizzate per calcolare gli spartiacque.",
    deriveNewLocations:"Deriva nuove località",
    deriveNewLocationsUsage:"Consente di derivare nuove feature in base ai layer di input conformi a una query specificata.",
    deriveNewLocationsInputTip:"Specificare il layer di analisi da utilizzare come input.",
    dissolveBoundaries:"Dissolvi confini",
    dissolveBoundariesUsage:"Consente di dissolvere i poligono che si sovrappongono o che condividono un confine comune.",
    dissolveBoundariesInputTip:"Specificare il layer contenente le feature poligono che verranno dissolte.",
    enrichLayer:"Aggiungi dati al layer",
    enrichLayerUsage:"Consente di aggiungere dati nelle feature di input, ovvero dati su persone, località e attività commerciali nelle aree vicine.",
    enrichLayerInputTip:"Specificare le feature in cui inserire nuovi dati.",
    extractData:"Estrai dati",
    extractDataDesc:"Consente di estrarre i dati da uno o più layer all\'interno di un\'estensione specificata.",
    extractDataInputTip:"Specificare i feature layer di input da estrarre.",
    findExistingLocations:"Trova località esistenti",
    findExistingLocationsUsage:"Consente di selezionare le feature nel layer di input che soddisfa una query attributi e/o spaziale specificata.",
    findExistingLocationsInputTip:"Specificare i layer di analisi da utilizzare come input.",
    findHotSpots:"Trova hot spot",
    findHotSpotsUsage:"Consente di cercare cluster statisticamente significativi di feature di input o valori massimi/minimi.",
    findHotSpotsInputTip:"Specificare il feature layer punto o poligono per il quale verranno calcolati gli hot spot.",
    findNearest:"Trova più vicine",
    findNearestUsage:"Per ogni feature in un layer di input, consente di trovare la relativa feature più vicina in un altro layer",
    findNearestInputTip:"Specificare i feature layer punto, linea o poligono in base ai quali cercare le località più vicine.",
    findSimilarLocations:"Trova località simili",
    findSimilarLocationsUsage:"Consente di misurare la somiglianza delle località candidate rispetto a una o più località di riferimento.",
    findSimilarLocationsInputTip:"Specificare un feature layer contenente una o più località di riferimento in base al quale le feature nel layer di ricerca verranno valutate a livello di somiglianza.",
    interpolatePoints:"Interpolazione punti",
    interpolatePointsUsage:"Consente di eseguire una previsione dei valori nelle nuove località in base alle misurazioni provenienti da una raccolta di punti.",
    interpolatePointsInputTip:"Specificare le feature puntuali che saranno oggetto dell\'interpolazione.",
    mergeLayers:"Unisci layer",
    mergeLayersUsage:"Consente di unire le feature da più layer in un nuovo layer.",
    mergeLayersInputTip:"Specificare il feature layer da unire al layer di unione.",
    overlayLayers:"Sovrapponi layer",
    overlayLayersUsage:"Consente di combinare più layer in un unico layer mantenendo inalterate le informazioni dei layer di origine.",
    overlayLayersInputTip:"Specificare il feature layer che verrà sovrapposto al layer di sovrapposizione.",
    planRoutes:"Pianifica itinerari",
    planRoutesUsage:"Consente di definire come suddividere in modo efficiente le attività tra gli addetti mobili.",
    planRoutesInputTip:"Specificare i punti che i veicoli, gli autisti o gli itinerari devono visitare.",
    summarizeNearby:"Riepiloga nelle vicinanze",
    summarizeNearbyUsage:"Per ogni feature in un layer di input, consente di riepilogare i dati all\'interno di una distanza rispetto alle feature in un altro layer.",
    summarizeNearbyInputTip:"Specificare il feature layer punto, linea o poligono a partire dal quale verranno misurate le distanze rispetto ai feature nel layer di riepilogo.",
    summarizeWithin:"Riepiloga entro",
    summarizeWithinUsage:"Per ogni poligono in un layer poligono di input, consente di riepilogare i dati che si trovano al suo interno rispetto alle feature in un altro layer.",
    summarizeWithinInputTip:"Specificare il feature layer poligono a partire del quale generare il riepilogo.",
    traceDownstream:"Traccia a valle",
    traceDownstreamUsage:"Consente di determinare i percorsi dei flussi nella direzione a valle dalle località specificate.",
    traceDownstreamInputTip:"Specificare le feature puntuali utilizzate per la località di partenza di un tracciamento a valle."
  })
);
