define(
   ({
    selectAnalysisTools:"Selezionare gli strumenti di analisi da utilizzare nel widget.",
    selected: "selezionato",
    name: "Nome",
    graphicalDisplay:"Visualizzazione grafica",
    usage: "Utilizzo",
    settings: "Impostazioni",
    toolSetting: "Imposta dettagli strumento",
    toolLabel: "Il nome visualizzato dello strumento",
    showHelpTip: "Mostra collegamenti della guida nel widget",
    showCurrentMapExtent: "Mostra opzione per utilizzare l\'estensione mappa corrente",
    showCredits: "Visualizza l\'opzione <b>Mostra crediti</b>",
    saveAsFeatureService: "Salva il risultato nell\'account dell\'utente",
    showReadyToUseLayers: "Mostra layer pronti all\'uso dall\'atlante attivo del mondo di ArcGIS Online",
    toolNotAvailable: "Questo strumento non è disponibile perché la mappa non contiene i feature layer richiesti.",
    aggregatePoints:"Aggrega punti",
    aggregatePointsUsage:"Aggrega i punti nei poligoni in cui si trovano tali punti.",
    calculateDensity:"Calcolo densità",
    calculateDensityUsage:"Creare una mappa densità dalle feature puntuali o lineari distribuendo quantità conosciute di un fenomeno (rappresentato come attributi dei punti o delle linee) sulla mappa.",
    connectOriginsToDestinations: "Connetti origini a destinazioni",
    connectOriginsToDestinationsUsage: "Consente di misurare la durata o la distanza del viaggio da coppie di punti.",
    createBuffers:"Crea buffer",
    createBuffersUsage:"Consente di creare poligoni buffer dalle feature di input.",
    createDriveTimeAreas:"Crea aree tempo di guida",
    createDriveTimeAreasUsage:"Consente di creare poligoni relativi al tempo di guida (o distanza di guida) attorno ai punti di input per i valori del tempo di guida specificati.",
    createViewshed:"Crea campo di vista",
    createViewshedUsage:"Consente di creare aree visibili in base alle posizioni specificate.",
    createWatersheds:"Crea spartiacque",
    createWatershedsUsage:"Consente di creare aree di bacini fluviali in base alle posizioni specificate.",
    deriveNewLocations:"Deriva nuove località",
    deriveNewLocationsUsage:"Consente di derivare nuove feature in base ai layer di input conformi a una query specificata.",
    dissolveBoundaries:"Dissolvi confini",
    dissolveBoundariesUsage:"Consente di dissolvere i poligono che si sovrappongono o che condividono un confine comune.",
    enrichLayer:"Aggiungi dati al layer",
    enrichLayerUsage:"Consente di aggiungere dati nelle feature di input, ovvero dati su persone, località e attività commerciali nelle aree vicine.",
    extractData:"Estrai dati",
    extractDataDesc:"Consente di estrarre i dati da uno o più layer all\'interno di un\'estensione specificata.",
    findExistingLocations:"Trova località esistenti",
    findExistingLocationsUsage:"Consente di selezionare le feature nel layer di input che soddisfa una query attributi e/o spaziale specificata.",
    findHotSpots:"Trova hot spot",
    findHotSpotsUsage:"Consente di cercare cluster statisticamente significativi di feature di input o valori massimi/minimi.",
    findNearest:"Trova più vicine",
    findNearestUsage:"Per ogni feature in un layer di input, consente di trovare la relativa feature più vicina in un altro layer",
    findSimilarLocations:"Trova località simili",
    findSimilarLocationsUsage:"Consente di misurare la somiglianza delle località candidate rispetto a una o più località di riferimento.",
    interpolatePoints:"Interpolazione punti",
    interpolatePointsUsage:"Consente di eseguire una previsione dei valori nelle nuove località in base alle misurazioni provenienti da una raccolta di punti.",
    mergeLayers:"Unisci layer",
    mergeLayersUsage:"Consente di unire le feature da più layer in un nuovo layer.",
    overlayLayers:"Sovrapponi layer",
    overlayLayersUsage:"Consente di combinare più layer in un unico layer mantenendo inalterate le informazioni dei layer di origine.",
    planRoutes:"Pianifica itinerari",
    planRoutesUsage:"Consente di definire come suddividere in modo efficiente le attività tra gli addetti mobili.",
    summarizeNearby:"Riepiloga nelle vicinanze",
    summarizeNearbyUsage:"Per ogni feature in un layer di input, consente di riepilogare i dati all\'interno di una distanza rispetto alle feature in un altro layer.",
    summarizeWithin:"Riepiloga entro",
    summarizeWithinUsage:"Per ogni poligono in un layer poligono di input, consente di riepilogare i dati che si trovano al suo interno rispetto alle feature in un altro layer.",
    traceDownstream:"Traccia a valle",
    traceDownstreamUsage:"Consente di determinare i percorsi dei flussi nella direzione a valle dalle località specificate."
  })
);
