define(
   ({
    _widgetLabel: "Stampa",
    title: "Titolo mappa",
    format: "Formato",
    layout: "Layout",
    settings: "Avanzato",
    mapScaleExtent: "Scala/estensione mappa",
    preserve: "Mantieni",
    mapScale: "scala mappa",
    mapExtent: "estensione mappa",
    forceScale: "Forza scala",
    getCurrentScale: "corrente",
    mapMetadata: "Metadati layout",
    author: "Autore",
    copyright: "Copyright",
    fullLayoutOptions: "Opzioni layout completo",
    scaleBarUnitsMetric: "Unità metriche barra scala",
    scaleBarUnitsNonMetric: "Unità non metriche barra scala",
    unitsMiles: "Miglia",
    unitsKilometers: "Chilometri",
    unitsMeters: "Metri",
    unitsFeet: "Piedi",
    unitsYards: "Iarde",
    unitsNauticalMiles: "Miglia nautiche",
    lncludeLegend: "Includi legenda",
    printQualityOptions: "Qualità di stampa",
    dpi: "DPI",
    mapOnlyOptions: "Dimensioni MAP_ONLY",
    width: "Larghezza (px)",
    height: "Altezza (px)",
    print: "Stampa",
    clearList: "Cancella stampe",
    creatingPrint: "Creazione stampa",
    printError: "Errore. Riprovare"
  })
);