define(
   ({
    _widgetLabel: "הדפס",
    title: "כותרת מפה",
    format: "פורמט",
    layout: "תצוגה",
    settings: "מתקדם",
    mapScaleExtent: "תחום/קנה מידה של המפה",
    preserve: "שמר",
    mapScale: "קנה מידה של המפה",
    mapExtent: "תיחום המפה",
    forceScale: "אלץ קנה מידה",
    getCurrentScale: "נוכחי",
    mapMetadata: "מטה-דאטה של תצוגת מפה",
    author: "מחבר",
    copyright: "זכות יוצרים",
    fullLayoutOptions: "אפשרויות תצוגת מפה מלאות",
    scaleBarUnitsMetric: "יחידות סרגל קנה מידה מטריות",
    scaleBarUnitsNonMetric: "יחידות סרגל קנה מידה לא מטריות",
    unitsMiles: "מיילים",
    unitsKilometers: "קילומטרים",
    unitsMeters: "מטרים",
    unitsFeet: "רגל",
    unitsYards: "יארד",
    unitsNauticalMiles: "מיילים ימיים",
    lncludeLegend: "כולל מקרא",
    printQualityOptions: "איכות הדפסה",
    dpi: "DPI",
    mapOnlyOptions: "גודל MAP_ONLY",
    width: "רוחב (פיקסל)",
    height: "גובה (פיקסל)",
    print: "הדפס",
    clearList: "נקה הדפסות",
    creatingPrint: "יוצר הדפסה",
    printError: "שגיאה, נסה שנית"
  })
);