define(
   ({
    _widgetLabel: "フィーチャのレポート",
    select: "選択",
    draw: "描画",
    chooseALayer: "レイヤーの選択",
    clickAFeature: "マップ上でフィーチャをクリックして選択します。",
    loadingFeatures: "選択したフィーチャの詳細を取得しています...",
    errorTitle: "エラー",
    errorIdentify: "フィーチャのエラーが識別されました。詳細については、コンソール ログを確認してください。",
    infoWindowTitle: "詳細",
    layerLabel: "レイヤー名",
    reviewStatusLabel: "レビューアー ステータス",
    selectReviewStatusAdd: "フィーチャの追加",
    selectReviewStatusDelete: "フィーチャの削除",
    selectReviewStatusMove: "フィーチャの移動",
    selectReviewStatusReshape: "フィーチャの形状変更",
    drawReviewStatusMissing: "フィーチャが見つかりません",
    drawReviewStatusPosition: "位置エラー",
    drawReviewStatusShape: "形状エラー",
    drawReviewStatusAttribute: "属性エラー",
    notesLabel: "メモ",
    severityLabel: "重要度",
    reportedByLabel: "レポート作成者",
    reportedByDefault: "匿名",
    reportButton: "レポート",
    reportMessage: "レポートが受信されました",
    errorReportMessage: "フィーチャのレポート中にエラーが発生しました",
    drawErrorInstructions: "ポイント、ライン、またはポリゴンを選択し、エラー ジオメトリをマップに描画します。",
    errorMapService: "マップ サービス情報の取得中にエラーが発生しました",
    noFeatureSelected : "クリックした位置でフィーチャが見つかりませんでした",
    selectFeatureMapPoint: "クリックしてフィーチャを選択します",
    drawFeatureMapPoint: "クリックしてポイントを追加します",
    popupMessage:"メッセージ",
    popupError:"エラー",
    manyFeaturesSelected: "複数のフィーチャが見つかりました。レポートするフィーチャを拡大して選択してください。"
  })
);
