define(
   ({
    routeUrl: "Reitin URL-osoite",
    locatorUrl: "Geokooderin URL-osoite",
    geocoderOptions: "Geokooderin vaihtoehdot",
    autoComplete: "Täydennä automaattisesti",
    maxLocations: "Sijaintien enimmäismäärä",
    minCharacters: "Merkkien vähimmäismäärä",
    searchDelay: "Haku viivästyy",
    placeholder: "Paikkamerkki",
    routeOptions: "Reittivaihtoehdot",
    directionsLanguage: "Ohjeiden kieli",
    directionsLengthUnits: "Ohjeiden pituusyksiköt",
    directionsOutputType: "Ohjeiden tulosaineiston tyyppi",
    impedanceAttribute: "Impedanssin ominaisuus",
    kilometers: "Kilometriä",
    miles: "Mailia",
    meters: "Metriä",
    feet: "Jalkaa",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    parametersTip: "Määritä parametrit oikein.",
    complete: "Valmis",
    completeNoEvents: "Älä suorita loppuun yhtään tapahtumaa",
    instructionsOnly: "Vain ohjeet",
    standard: "Vakio",
    summaryOnly: "Vain yhteenveto",
    travelModesUrl: "Matkustustapojen URL-osoitteet",
    searchPlaceholder: "Etsi osoite tai paikka",
    trafficLayerUrl: "Liikenteen karttatason URL-osoite"
  })
);