define(
   ({
    selectAnalysisTools:"Seleccionar ferramentas de análise para usar no widget.",
    selected: "selecionadas",
    name: "Nome",
    graphicalDisplay:"Exibição gráfica",
    usage: "Utilização",
    settings: "Definições",
    toolSetting: "Definir detalhes de ferramentas",
    toolLabel: "O nome de exibição da ferramenta",
    showHelpTip: "Mostar links de ajuda no widget",
    showCurrentMapExtent: "Exibir opção para utilizar a atual extensão de mapa",
    showCredits: "Exibir <b>Mostrar créditos</b>",
    saveAsFeatureService: "Guardar o resultado na conta userâ€™s",
    showReadyToUseLayers: "Mostar camadas prontas a usar a partir do living atlas ArcGIS Online do mundo",
    toolNotAvailable: "Esta ferramenta não se encontra disponível porque o mapa não contém a(s) camada(s) de elementos necessária(s).",
    aggregatePoints:"Pontos Agregados",
    aggregatePointsUsage:"Agregue pontos nos polígonos em que os pontos estão localizados.",
    calculateDensity:"Calcular Densidade",
    calculateDensityUsage:"Crie um mapa de densidade a partir de elementos de ponto ou linha distribuindo quantidades conhecidas de determinado fenómeno(representado como atributos dos pontos ou linhas) pelo mapa.",
    connectOriginsToDestinations: "Ligar Origens a Destinos",
    connectOriginsToDestinationsUsage: "Meça o tempo ou distância de viagem entre pares de pontos.",
    createBuffers:"Criar Buffers",
    createBuffersUsage:"Crie polígonos de buffer a partir de elementos de entrada.",
    createDriveTimeAreas:"Criar Áreas de Tempo de Condução",
    createDriveTimeAreasUsage:"Crie polígonos de tempo de condução (ou distância de condução) à volta de pontos de entrada para os valores de tempo de condução.",
    createViewshed:"Criar Viewshed",
    createViewshedUsage:"Cria áreas que são visíveis com base em localizações especificadas por si.",
    createWatersheds:"Criar Watersheds",
    createWatershedsUsage:"Cria áreas de captação com base em localizações especificadas por si.",
    deriveNewLocations:"Derivar Novos locais",
    deriveNewLocationsUsage:"Derive novos elementos a partir das camadas de entrada que correspondam a umaconsulta especificada por si",
    dissolveBoundaries:"Dissolver Limites",
    dissolveBoundariesUsage:"Dissolva polígonos que se sobreponham ou que partilhem um limite comum.",
    enrichLayer:"Enriquecer Camada",
    enrichLayerUsage:"Enriqueça elementos de entrada com factos sobre pessoas, locais e negócios em áreas aproximadas.",
    extractData:"Extrair Dados",
    extractDataDesc:"Extraia dados de uma ou mais camadas dentro de uma determinada extensão",
    findExistingLocations:"Encontrar Locais Existentes",
    findExistingLocationsUsage:"Selecione elementos na camada de entrada que correspondam a um atributo e/ou consulta espacial especificados por si.",
    findHotSpots:"Encontrar Hot Spots",
    findHotSpotsUsage:"Encontre clusters estatisticamente significativos de elementos de entrada ou de valores altos/baixos.",
    findNearest:"Localizar Próximo",
    findNearestUsage:"Para cada elemento numa camada de entrada, encontre o respetivo elemento mais próximo noutra camada.",
    findSimilarLocations:"Encontrar Locais Semelhantes",
    findSimilarLocationsUsage:"Meça a semelhança de locais candidados a uma ou mais localizações de referência.",
    interpolatePoints:"Interpolar Pontos",
    interpolatePointsUsage:"Preveja valores em novos locais com base em medições de uma coleção de pontos.",
    mergeLayers:"Juntar Camadas",
    mergeLayersUsage:"Junte elementos a partir de várias camadas numa nova camada.",
    overlayLayers:"Sobrepor Camadas",
    overlayLayersUsage:"Combine várias camadas numa única camada garantindo a preservação das informações das camadas originais.",
    planRoutes:"Planear Rotas",
    planRoutesUsage:"Determine como dividir as tarefas de uma força de trabalho móvel de forma eficiente.",
    summarizeNearby:"Resumir Próximo",
    summarizeNearbyUsage:"Por cada elemento numa camada de entrada, resuma dados a uma distância de elementos noutra camada.",
    summarizeWithin:"Resumir Dentro",
    summarizeWithinUsage:"Para cada polígono numa camada de saída, resuma dados localizados dentro da mesma com elementos noutra camada.",
    traceDownstream:"Trace Downstream",
    traceDownstreamUsage:"Determine os caminhos dos fluxos numa direção a jusante dos locais que especificou."
  })
);
