define(
   ({
    taskUrl: "Uzdevuma URL",
    serviceURLPlaceholder: "Lūdzu, ievadiet ģeoapstrādes uzdevuma URL",
    ok: "Labi",
    cancel: "Atcelt",
    layer: "Slānis",
    action: "Darbība",
    input: "Ievade",
    output: "Izvade",
    name: "Nosaukums",
    type: "Tips",
    required: "Nepieciešams",
    layerOrder: "Slāņu secība",
    options: "Opcijas",
    defaultValue: "Noklusējuma vērtība",
    inputFeatureBy: "Ievadīt elementu pēc",
    renderer: "Renderētājs",
    displayType: "Parādīt veidu",
    label: "Kartes teksts",
    tooltip: "Rīka padoms",
    visible: "Redzams",
    helpUrl: "Palīdzības URL",
    useResultMapService: "Izmantot rezultātu kartes pakalpojuma zīmēšanas opcijas",
    drawOnMap: "Interaktīva zīmēšana kartē",
    selectLayer: "Slāņa izvēle kartē",
    url: "URL",
    symbol: "Simbols",
    shareResults: "Pievienot rezultātu kā operacionālo slāni",
    popup: "Uznirstošais logs",
    setTask: "Iestatīt",
    setTaskTitle: "Iestatīt GP uzdevumu",
    enablePopup: "Iespējot uznirstošo logu"
  })
);