define(
   ({
    taskUrl: "Uzdevuma URL",
    serviceURLPlaceholder: "Lūdzu, ievadiet ģeoapstrādes uzdevuma URL",
    ok: "Labi",
    cancel: "Atcelt",
    layer: "Slānis",
    action: "Darbība",
    input: "Ievade",
    output: "Izvade",
    name: "Nosaukums",
    type: "Tips",
    required: "Nepieciešams",
    layerOrder: "Slāņu secība",
    options: "Opcijas",
    defaultValue: "Noklusējuma vērtība",
    inputFeatureBy: "Ievadīt elementu pēc",
    renderer: "Renderētājs",
    displayType: "Parādīt veidu",
    label: "Kartes teksts",
    tooltip: "Rīka padoms",
    visible: "Redzams",
    helpUrl: "Palīdzības URL",
    useResultMapService: "Izmantot rezultātu kartes pakalpojuma zīmēšanas opcijas",
    drawOnMap: "Interaktīva zīmēšana kartē",
    selectLayer: "Slāņa izvēle kartē",
    url: "URL",
    symbol: "Simbols",
    shareResults: "Pievienot rezultātu kā operacionālo slāni",
    popup: "Uznirstošais logs",
    setTask: "Iestatīt",
    setTaskTitle: "Iestatīt GP uzdevumu",
    enablePopup: "Iespējot uznirstošo logu",
    unSupportGeometryType: "Nevar iestatīt renderētāju nezināma ģeometrijas tipa dēļ.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Augšupielādējiet failu",
    selectFileToUpload: "Atlasiet failu...",
    upload: "Augšupielādēt",
    rasterFormat: "Rastra datu formāts",
    noFileSelected: "Nav atlasīts fails!",
    uploadSuccess:"Faila augšupielāde veiksmīga!",
    showLayerContent: "Rādīt slāņa saturu",
    Feet: "Pēdas",
    Yards: "Jardi",
    Miles: "Jūdzes",
    NauticalMiles: "Jūras jūdzes",
    Meter: "Metri",
    Kilometers: "Kilometri",
    urlPlaceholder: "elementu kopas URL",
    allowToExport: "Atļaut eksportēt rezultātus"
  })
);
