define(
   ({
    _widgetLabel: "วิเคราะห์เหตุการณ์ที่เกิดขึ้น",
    incident: "เหตุการณ์",
    weather: "สภาพอากาศ",
    locate_incident: "ค้นหาเหตุการณ์",
    clear_incidents: "เหตุการณ์ที่ชัดเจน",
    reverse_geocoded_address: "ที่อยู่ใกล้ที่สุด",
    reverse_geocoded_error: "ไม่สามารถ",
    miles: "ไมล์",
    kilometers: "กิโลเมตร",
    feet: "ฟุต",
    meters: "เมตร",
    yards: "หลา",
    nauticalMiles: "ไมล์ทะเล",
    now: "ขณะนี้",
    wind: "ลม",
    SUN: "อา.",
    MON: "จ.",
    TUE: "อ.",
    WED: "พ.",
    THU: "พฤ.",
    FRI: "ศ.",
    SAT: "ส.",
    defaultTabMsg: "เหตุการณ์ที่เกิดขึ้นไม่มีการระบุ",
    actionLabel: "ตั้งเป็นเหตุการณ์ที่เกิดขึ้น",
    useMapExtent: "ใช้ขอบเขตแผนที่ปัจจุบัน",
    noFeaturesFound: "ไม่พบฟีเจอร์",
    downloadCSV: "ดาวน์โหลด CSV",
    sum: "รวม",
    min: "น้อยที่สุด",
    max: "ข้อมูลทั้งหมด",
    avg: "เฉลี่ย",
    count: "จำนวน",
    area: "พื้นที่",
    length: "ความยาว"
  })
);
