define(
   ({
    _widgetLabel: "Γεωεπεξεργασία",
    execute: "Εκτέλεση",
    help: "Βοήθεια",
    input: "Είσοδος",
    output: "Έξοδος",
    executing: "Εκτέλεση",
    requiredInfo: "είναι προαπαιτούμενο.",
    drawnOnMap: "Το αποτέλεσμα σχεδιάζεται στον χάρτη.",
    clear: "Απαλοιφή",
    error: "Σφάλμα",
    noToolConfig: "Δεν έχει καθοριστεί εργασία γεωεπεξεργασίας.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Φόρτωση αρχείου",
    selectFileToUpload: 'Επιλογή αρχείου...',
    upload: 'Μεταφόρτωση',
    rasterFormat: 'Μορφότυπος πλεγματικών δεδομένων',
    noFileSelected: 'Δεν επιλέχθηκε αρχείο!',
    uploadSuccess:'Επιτυχής φόρτωση αρχείου!',
    url: "URL",
    showLayerContent: "Εμφάνιση περιεχομένου θεματικού επιπέδου",
    invalidUrl: "Μη έγκυρο URL Feature Service",
    Feet: "Πόδια",
    Yards: "Γιάρδες",
    Miles: "Μίλια",
    NauticalMiles: "Ναυτικά μίλια",
    Meter: "Μέτρα",
    Kilometers: "Χιλιόμετρα",
    urlPlaceholder: "URL συνόλου στοιχείων"
  })
);
