define(
	 ({
		chartTasks: "Attività grafico",
		addNew: "Aggiungi nuovo",
		addNewTip: "Aggiungi nuova attività grafico",
		name: "Nome",
		set: "Imposta",
		setDataSource: "Imposta origine dati",
		generalSettingsTip: "Imposta origine dati, titolo e descrizione per i grafici.",
		chartModeSettingTip: "Seleziona un modo per analizzare e visualizzare i dati come grafici.",
		detailsSettingTip: "Imposta l\'aspetto del grafico specificando tipo e colore e i valori da inserire:",
		symbolSettingTip: "Imposta la visualizzazione della mappa per i dati nel grafico.",
		addFilterTip: "Aggiungi filtro a questi dati+",
		dataSource: "Origine dati",
		noResults: "Nessuna feature trovata.",
		chartTitle: "Titolo grafico",
		description: "Descrizione",
		chartingMode: "Visualizzazione grafico",
		featureOption: "Visualizza valori feature per feature",
		categoryOption: "Visualizza valori per categoria",
		countOption: "Visualizza conteggi feature per categoria",
		fieldOption: "Visualizza valori attributi come grafici",
		category: "Categoria",
		axisLabel: "Etichetta categoria",
		categoryField: "Campo categoria",
		operation: "Operazione",
		originalOption: "Utilizza valori originali",
		sumOption: "Somma",
		averageOption: "Media",
		minOption: "Minimo",
		maxOption: "Massimo",
		valueFields: "Campi valore",
		moveUp: "Sposta su",
		moveDown: "Sposta giù",
		sortOrder: "Ordina ordine grafici mediante etichette categoria",
		ascending: "Ascendente",
		descending: "Discendente",
		chartType: "Tipo di grafico",
		column: "Grafico a colonne",
		bar: "Grafico a barre",
		line: "Grafico a linee",
		pie: "Grafico a torta",
		chartColor: "Colore grafico",
		showDataLabels: "Mostra etichette dati",
		setSymbol: "Simbolo di selezione",
		setHighLightColor: "Colore evidenziazione",
		settings: "Impostazioni",
		mapInterationOptions: "Opzioni interazione mappa",
		preview: "Anteprima",
		ok: "OK",
		cancel: "Annulla",
		close: "Chiudi",
		setFilterTip: "Impostare il filtro correttamente. ",
		setChartTitleTip: "Impostare il titolo del grafico.",
		setChartTypeTip: "Selezionare almeno un tipo di grafico.",
		setDataFieldTip: "Selezionare almeno un campo di valori.",
		setOutputFieldTip: "Impostare i campi di uscita.",
		count: "Conteggio",
		label: "Etichetta",
		horizontalAxis: "Asse orizzontale",
		verticalAxis: "Asse verticale",
		dataLabels: "Etichette dati",
		color: "Colore",
		colorful: "A colori",
		monochromatic: "Monocromatico",
    noTaskTip: "Fare clic su Nuovo per aggiungere un\'attività grafico.",
    info: "Informazioni",
    charts: "Grafici",
    options: "Opzioni",
    taskName: "Nome attività",
    summary: "Riepilogo",
    resultDescription: "Descrizione risultato",
    spatialFilterTip: "Scegliere il filtro o i filtri spaziali utilizzati nel widget per limitare i risultati.",
    defaultOption: "Impostazione predefinita",
    useCurrentExtentTip: "Parzialmente o completamente all\'interno dell\'estensione mappa corrente",
    useDrawGraphicTip: "Parzialmente o completamente all\'interno della forma disegnata sulla mappa",
    useFeaturesTip: "In base alle posizioni relative alle feature in un altro layer",
    noSpatialLimitTip: "Non limitare spazialmente i risultati",
    drawingTools: "Strumenti di disegno",
    bufferSettings: "Impostazioni buffer",
    defaultDistance: "Distanza predefinita",
    bufferDistance: "Distanza di buffer",
    defaultUnit: "Unità predefinita",
    miles: "Miglia",
    kilometers: "Chilometri",
    feet: "Piede",
    meters: "Metri",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    availableSpatialRelationships: "Relazioni spaziali disponibili",
    setSpatialRelationships: "Imposta relazioni spaziali",
    availability: "Disponibilità",
    relationship: "Relazione",
    actions: "Azioni",
    intersect: "intersecano",
    contain: "contengono",
    areContainedIn: "sono contenuti in",
    cross: "Incrociato",
    envelopeIntersect: "intersezione inviluppo",
    overlap: "sovrapponi",
    areOverlapped: "sono sovrapposte",
    touche: "tocca",
    within: "interno",
    areWithin: "sono interne",
    indexIntersect: "interseca indice"
  })
);