define(
   ({
    _widgetLabel: "Εκτύπωση",
    title: "Τίτλος χάρτη",
    format: "Μορφή",
    layout: "Διάταξη",
    settings: "Για προχωρημένους",
    mapScaleExtent: "Κλίμακα/έκταση χάρτη",
    preserve: "Διατήρηση",
    mapScale: "κλίμακας χάρτη",
    mapExtent: "έκτασης χάρτη",
    forceScale: "Επιλογή κλίμακας",
    getCurrentScale: "τρέχουσα",
    mapMetadata: "Μεταδεδομένα διάταξης",
    author: "Συντάκτης",
    copyright: "Πνευματικά δικαιώματα",
    fullLayoutOptions: "Επιλογές πλήρους διάταξης",
    scaleBarUnitsMetric: "Μετρικό σύστημα μονάδων γραμμής κλίμακας",
    scaleBarUnitsNonMetric: "Μη μετρικό σύστημα μονάδων γραμμής κλίμακας",
    unitsMiles: "Μίλια",
    unitsKilometers: "Χιλιόμετρα",
    unitsMeters: "Μέτρα",
    unitsFeet: "Πόδια",
    unitsYards: "Γιάρδες",
    unitsNauticalMiles: "Ναυτικά μίλια",
    lncludeLegend: "Συμπερίληψη υπομνήματος",
    printQualityOptions: "Ποιότητα εκτύπωσης",
    dpi: "DPI",
    mapOnlyOptions: "Μέγεθος MAP_ONLY",
    width: "Πλάτος (px)",
    height: "Ύψος (px)",
    print: "Εκτύπωση",
    clearList: "Απαλοιφή εκτυπώσεων",
    creatingPrint: "Δημιουργία εκτύπωσης",
    printError: "Σφάλμα, δοκιμάστε ξανά"
  })
);