define(
   ({
    _widgetLabel: "Ereignisanalyse",
    incident: "Ereignis",
    weather: "Wetter",
    locate_incident: "Ereignis verorten",
    clear_incidents: "Ereignisse löschen",
    reverse_geocoded_address: "Nächstgelegene Adresse",
    reverse_geocoded_error: "Nicht verfügbar",
    miles: "Meilen",
    kilometers: "Kilometer",
    feet: "Fuß",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Seemeilen",
    now: "JETZT",
    wind: "WIND",
    SUN: "SO",
    MON: "MO",
    TUE: "DI",
    WED: "MI",
    THU: "DO",
    FRI: "FR",
    SAT: "SA",
    defaultTabMsg: "Keine Ereignisse identifiziert.",
    actionLabel: "Als Ereignis festlegen",
    useMapExtent: "Die aktuelle Kartenausdehnung verwenden",
    noFeaturesFound: "Keine Features gefunden.",
    downloadCSV: "CSV HERUNTERLADEN",
    sum: "SUMME",
    min: "MINIMUM",
    max: "MAXIMUM",
    avg: "DURCHSCHNITT",
    count: "ANZAHL",
    area: "FLÄCHE",
    length: "LÄNGE"
  })
);
