define({
  root: ({
    settings: "Settings",
    layerTitle: "Layer Name",
    addLayer: "Add Identify Layer",
    addExcludeLayer: "Add Exclude Identify Layer",
    editLayer: "Edit Identify Layer",
    editExcludeLayer: "Edit Exclude Identify Layer",
    edit: "Edit",
    actions: "Actions",
    zoomScale: "Default Zoom Scale",
    layerZoomScale: "Zoom Scale",
    editDefaultSym: "Edit Default Identify Symbology",
    identifyoption: "Identify Layer Option",
    identTolerance: "Identify Tolerance",
    visible: "Visible",
    top: "Top",
    all: "All",
    keepActive: "Keep Identify Active",
    returnGeom: "Return Geometry for Zoom",
    enableline: "Enable Line Select",
    enablepolyline: "Enable Poly Line Select",
    enablefreehandline: "Enable Freehand Line Select",
    enableextent: "Enable Extent Select",
    enablecircle: "Enable Circle Select",
    enableellipse: "Enable Ellipse Select",
    enablepolygon: "Enable Polygon Select",
    enablefreehandpolygon: "Enable Freehand Polygon Select",
    enabletriangle: "Enable Triangle Select",
    symbologyTooltip: "Click on the symbology symbol that you want to edit.",
    pointSymbol: "Point Marker Symbol: ",
    pictureSymbol: "Picture Marker Symbol: ",
    lineSymbol: "Line Symbol: ",
    polySymbol: "Polygon Symbol: ",
    selectgeoms: "Select Geometry Types",
    mouseovergraphic: "Enable Mouse Over Graphic Info Windows",
    mouseoverresult: "Enable Mouse Over Result Info Windows",
    disablepopuplinks: "Disable PopUp Links",
    usemaptime: "Use Map Time",
    disablelayerlist: "Disable Layers Drop Down List",
    disablealllayerschoice: "Disable All Layers Choice",
    replacenullwithemptystring: "Replace Null With Empty String",
    defaultactivetool: "Default activated Select Tool",
    infowindowautoclose: "Info Window Auto Close (seconds)",
    none: "None",
    cancel: "Cancel",
    ok: "OK",
    thumbnailHint: "Click image to update",
    forceScale: "Force Scale",
    identifyUrl: "Identify URL",
    layerName: "Name",
    availableFields: "Available Fields",
    name: "Name",
    alias: "Alias",
    includedFields: "Included Fields",
    addLink: "Add Link",
    updateLink: "Update Link",
    linksTitle: "Identify Link(s)",
    popuponly: "PopUp Only",
    includeall: "Include All",
    include: "Include",
    linkAlias: "Link Alias",
    disablenulllink: "Disable Link if Null",
    disablelinkinpopup: "Disable Link in PopUp",
    popuplinktype: "PopUp Link Type",
    linktext: "Text",
    linkimage: "Image",
    linkiconcontent: "Link Icon Content",
    linkcontent: "Link Content",
    linkiconcontenthint: "The link icon content can be text, fields, or a combination of both, that make up a valid URL\\path to the links icon image. To add fields click the blue plus button to the right of the text area.",
    linkcontenthint: "The link content can be text, fields, or a combination of both, that make up a valid URL\\path to the linked item. To add fields click the blue plus button to the right of the text area.",
    browse: "Browse",
    requiredfield: "Field Required",
    isempty: "is Empty",
    dateformat: "Date format",
    dayShortMonthYear: "Day short Month Year",
    longDate: "Long Date",
    longMonthDayYear: "Long Month Day Year",
    longMonthYear: "Long Month Year",
    shortDate: "Short Date",
    shortDateLongTime: "Short Day Long Time",
    shortDateLongTime24: "Short Day Long Time 24",
    shortDateShortTime: "Short Date Short Time",
    shortDateShortTime24: "Short Day Short Time 24",
    shortMonthYear: "Short Month Year",
    year: "Year",
    custom: "Custom",
    useutc: "Use UTC",
    currencyfield: "Currency Field",
    currencySymbol: "Currency Symbol",
    examplecurrency: "$",
    precision: "Precision",
    exampleprecision: ".",
    usethousandssep: "Use thousands separator",
    examplethousands: ",",
    friendlyDatePattern: "MM/dd/yyyy",
    onlythese: "Only These",
    invalididentifylayer: "Invalid Identify Layer",
    or: "Or",
    excludeerrormsg: "You must use either the layer url or layer name, not both"
  })
});
