define(
	 ({
		queries: "クエリ タスク",
		addNew: "新規追加",
		setSource: "設定",
		setDataSource: "データ ソースの設定",
		name: "名前",
		querySource: "データ ソース",
		queryName: "タスク名",
		queryDefinition: "フィルター定義",
		resultsSetting: "結果の設定",
		symbolSetting: "シンボル設定",
		resultSettingTip: "どの出力結果をどのように表示するかを定義します。",
		resultItemTitle: "結果アイテムのタイトル",
		resultItemContent: "結果アイテムのコンテンツ",
		fieldsSetTip: "表示するフィールドのチェックボックスをオンにします。フィールドを選択して、エイリアスの更新、並べ替え、および書式設定を行います。",
		addField: "フィールドの追加",
		visibility: "表示設定",
		alias: "エイリアス",
		specialType: "特殊タイプ",
		actions: "アクション",
		none: "なし",
		link: "リンク",
		image: "画像",
		noField: "フィールドがありません",
		operationalLayerTip: "操作レイヤーとして結果を追加",
		setLayerSymbolTip: "クエリ結果のシンボルを設定: ",
		setSelectedSymbolTip: "選択したフィーチャのシンボルを設定します。",
		notUseFilter: "フィルターを使用しない",
		setSourceTip: "クエリ ソースを設定してください。",
		setFilterTip: "フィルターを正しく設定してください。",
		ok: "OK",
		cancel: "キャンセル",
		noFilterTip: "フィルターの条件式が定義されていない場合、このクエリ タスクは、指定したデータ ソース内のすべてのフィーチャをリストします。",
    relationships: "リレーションシップ テーブル",
    addRelationshipLayer: "リレーションシップを新規追加",
    relatedTo: "関連先または元",
    selectOption: "選択してください.."
  })
);
