define(
	 ({
		queries: "クエリ タスク",
		addNew: "新規追加",
    queryLayer: "クエリ レイヤー",
		setSource: "設定",
		setDataSource: "データ ソースの設定",
		name: "名前",
		querySource: "データ ソース",
		queryName: "タスク名",
		queryDefinition: "フィルター定義",
		resultsSetting: "結果の設定",
		symbolSetting: "シンボル設定",
		resultSettingTip: "どの出力結果をどのように表示するかを定義します。",
		resultItemTitle: "結果アイテムのタイトル",
		resultItemContent: "結果アイテムのコンテンツ",
		fieldsSetTip: "表示するフィールドのチェックボックスをオンにします。フィールドを選択して、エイリアスの更新、並べ替え、および書式設定を行います。",
		addField: "フィールドの追加",
		visibility: "表示設定",
		alias: "エイリアス",
		specialType: "特殊タイプ",
		actions: "アクション",
		none: "なし",
		link: "リンク",
		image: "画像",
		noField: "フィールドがありません",
		operationalLayerTip: "操作レイヤーとして結果を追加",
		setLayerSymbolTip: "クエリ結果のシンボルを設定: ",
		setSelectedSymbolTip: "選択したフィーチャのシンボルを設定します。",
		notUseFilter: "フィルターを使用しない",
		setSourceTip: "クエリ ソースを設定してください。",
		setFilterTip: "フィルターを正しく設定してください。",
		ok: "OK",
		cancel: "キャンセル",
		noFilterTip: "フィルターの条件式が定義されていない場合、このクエリ タスクは、指定したデータ ソース内のすべてのフィーチャをリストします。",
    relationships: "リレーションシップ",
    addRelationshipLayer: "リレーションシップを新規追加",
    relatedTo: "関連先または元",
    selectOption: "選択してください..",
    resultItemSorting: "結果アイテムの並べ替え",
    field: "フィールド",
    sortingOrder: "順序",
    configureFieldsTip: "クエリ結果の並べ替えに使用するフィールドを構成してください。",
    setSortingFields: "並べ替えフィールドの設定",
    ascending: "昇順",
    descending: "降順",
    sortBy: "1 番目に優先されるフィールド",
    thenBy: "2 番目に優先されるフィールド",
    addTask: "タスクの追加",
    noTasksTip: 'タスクがありません。\"${addTask}\" をクリックして開始してください。',
    infoText: "情報",
    filters: "フィルター",
    results: "結果",
    optionsText: "オプション",
    summaryText: "サマリー",
    attributeFilter: "属性フィルター",
    attributeFilterTip: "ウィジェットでクエリ レイヤーのフィルタリングに使用するための属性の条件式を定義します。",
    noExpressionDefinedTip: "条件式が定義されませんでした。",
    needInputValuesTip: "実行時に値を入力する必要があります",
    setExpressions: "条件式の設定",
    spatialFilter: "空間フィルター",
    spatialFilterTip: "結果を制限するためにウィジェットで使用される空間フィルターを選択します。",
    defaultOption: "デフォルト",
    useCurrentExtentTip: "現在のマップ範囲に部分的または完全に含まれる",
    useDrawGraphicTip: "マップに描画された図形に部分的または完全に含まれる",
    useFeaturesTip: "別のレイヤー内のフィーチャを基準にした位置に基づく",
    noSpatialLimitTip: "結果を空間的に制限しない",
    drawingTools: "描画ツール",
    bufferSettings: "バッファー設定",
    defaultDistance: "デフォルトの距離",
    bufferDistance: "バッファー距離",
    defaultUnit: "デフォルトの単位",
    miles: "マイル",
    kilometers: "キロメートル",
    feet: "フィート",
    meters: "メートル",
    yards: "ヤード",
    nauticalMiles: "海里",
    availableSpatialRelationships: "使用可能な空間リレーションシップ",
    setSpatialRelationships: "空間リレーションシップの設定",
    availability: "可用性",
    relationship: "リレーションシップ",
    label: "ラベル",
    intersect: "交差",
    contain: "<条件フィーチャ> を含む",
    areContainedIn: "次に含まれる",
    cross: "十字",
    envelopeIntersect: "エンベロープの交差",
    overlap: "オーバーラップ",
    areOverlapped: "オーバーラップしている",
    touche: "接する",
    within: "含まれる",
    areWithin: "「含まれる」フィーチャを検索",
    indexIntersect: "インデックスの交差",
    itemTitle: "アイテムのタイトル",
    displayFields: "表示フィールド",
    sortingFields: "フィールドのソート",
    setDisplayFields: "表示フィールドの設定",
    symbol: "シンボル",
    setSymbol: "シンボルの設定",
    serviceSymbolTip: "レイヤーで定義されたシンボルを使用",
    exportTip: "エクスポート ボタンを表示",
    keepResultsTip: "ウィジェットを閉じた後にマップ上の結果を維持する",
    queryRelatedRecords: "関連レコードの検索",
    createLayerForTaskTip: "タスクによるレイヤーの作成方法の指定",
    oneLayerForTaskTip: "このタスクでは 1 つのレイヤーのみを作成する",
    multipleLayerForTaskTip: "このタスクを実行するたびに、新しいレイヤーを作成する"
  })
);
