define({
  root: ({
    selectLayer: "Select Summary Layer",
    filterField: "Summary Layer Filter Field",
    count: "COUNT",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    addField: "Add Summary Field",
    label: "Label",
    type: "Type",
    field: "Field",
    actions: "Actions",
    displayCluster: "Display as Summary Clusters",
    showFeatureCount: "Show Feature Count",
    featureCountLabel: "Feature Count Label",
    missingLayerInWebMap: "Please add summary layers to webmap."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
