define(
	 ({
		chartTasks: "Diagramopgaver",
		addNew: "Tilføj ny",
		addNewTip: "Tilføj en ny diagramopgave",
		name: "Navn",
		set: "Indstil",
		setDataSource: "Angiv datakilde",
		generalSettingsTip: "Angiv datakilde, titel og beskrivelse til diagrammet.",
		chartModeSettingTip: "Vælg en måde at analysere og vise data på som diagrammer.",
		detailsSettingTip: "Indstil diagrammets udseende ved at angive dets typer og farve, samt hvilke værdier der skal afbildes:",
		symbolSettingTip: "Angiv kortvisningen for afbildede data.",
		addFilterTip: "Føj et filter til disse data",
		dataSource: "Datakilde",
		noResults: "Ingen resultater fundet.",
		chartTitle: "Diagramtitel",
		description: "Beskrivelse",
		chartingMode: "Diagramvisning",
		featureOption: "Vis værdier objekt for objekt",
		categoryOption: "Vis værdier efter kategori",
		countOption: "Vis objektantal efter kategori",
		fieldOption: "Vis attributværdier som diagrammer",
		category: "Kategori",
		axisLabel: "Kategorietiket",
		categoryField: "Kategorifelt",
		operation: "Handling",
		originalOption: "Brug originalværdier",
		sumOption: "Sum",
		averageOption: "Gennemsnitlig",
		minOption: "Minimum",
		maxOption: "Maksimum",
		valueFields: "Værdifelter",
		moveUp: "Flyt op",
		moveDown: "Flyt ned",
		sortOrder: "Sortér diagrambestilling via kategorietiketter",
		ascending: "Stigende",
		descending: "Faldende",
		chartType: "Diagramtype",
		column: "Kolonnediagram",
		bar: "Søjlediagram",
		line: "Linjediagram",
		pie: "Cirkeldiagram",
		chartColor: "Diagramfarve",
		showDataLabels: "Vis dataetiketter",
		setSymbol: "Markeringssymbol",
		setHighLightColor: "Fremhæv farve",
		settings: "Indstillinger",
		mapInterationOptions: "Indstillinger for interaktion med kortet",
		preview: "Forhåndsvisning",
		ok: "OK",
		cancel: "Annuller",
		close: "Luk",
		setFilterTip: "Angiv filteret korrekt. ",
		setChartTitleTip: "Angiv diagrammets titel.",
		setChartTypeTip: "Vælg mindst én diagramtype.",
		setDataFieldTip: "Vælg mindst ét værdifelt.",
		setOutputFieldTip: "Angiv outputfelter.",
		count: "Tælling",
		label: "Mærke",
		horizontalAxis: "Horisontal akse",
		verticalAxis: "Vertikal akse",
		dataLabels: "Dataetiketter",
		color: "Farve",
		colorful: "Farverig",
		monochromatic: "Monokrom",
    noTaskTip: "Klik på Tilføj ny for at tilføje en diagramopgave",
    info: "Info",
    charts: "Diagrammer",
    options: "Indstillinger",
    taskName: "Navn på opgave",
    summary: "Summary",
    resultDescription: "Resultatbeskrivelse",
    spatialFilterTip: "Vælg det/de spatiale filtre, der anvendes i widget\'en til at begrænse resultater.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Delvist eller helt inden for den aktuelle kortudstrækning",
    useDrawGraphicTip: "Delvist eller helt inden for den form, der et tegnet på kortet",
    useFeaturesTip: "Baseret på deres positioner i forhold til objekterne i et andet lag",
    noSpatialLimitTip: "Begræns ikke resultaterne spatialt",
    drawingTools: "Tegneværktøjer",
    bufferSettings: "Bufferindstillinger",
    defaultDistance: "Standardafstand",
    bufferDistance: "Bufferafstand",
    defaultUnit: "Standardenhed",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    availableSpatialRelationships: "Tilgængelige spatiale relationer",
    setSpatialRelationships: "Angiv spatiale relationer",
    availability: "Tilgængelighed",
    relationship: "Relation",
    actions: "Handlinger",
    intersect: "gennemskærer",
    contain: "indeholder",
    areContainedIn: "er indeholdt i",
    cross: "kors",
    envelopeIntersect: "indkredset gennemskæring",
    overlap: "overlapper",
    areOverlapped: "er overlappet",
    touche: "berører",
    within: "inden for",
    areWithin: "er inden for",
    indexIntersect: "indeksgennemskæring"
  })
);