define(
   ({
    _widgetLabel: "Hendelsesanalyse",
    incident: "Hendelse",
    weather: "Vær",
    locate_incident: "Lokaliser hendelsen",
    clear_incidents: "Fjern hendelser",
    reverse_geocoded_address: "Nærmeste adresse",
    reverse_geocoded_error: "Not available",
    miles: "Miles",
    kilometers: "kilometer",
    feet: "fot",
    meters: "meter",
    yards: "Yards",
    nauticalMiles: "Nautiske mil",
    now: "NÅ",
    wind: "VIND",
    SUN: "SØN",
    MON: "MAN",
    TUE: "TIR",
    WED: "ONS",
    THU: "TOR",
    FRI: "FRE",
    SAT: "LØR",
    defaultTabMsg: "Ingen hendelser identifisert.",
    actionLabel: "Angi som hendelse",
    useMapExtent: "Bruk gjeldende kartutstrekning",
    noFeaturesFound: "Fant ingen geoobjekter.",
    downloadCSV: "LAST NED CSV",
    sum: "SUM",
    min: "MIN.",
    max: "MAKS.",
    avg: "GJ.SN.",
    count: "ANTALL",
    area: "OMRÅDE",
    length: "LENGDE"
  })
);
