define(
   ({
    routeUrl: "경로 URL",
    locatorUrl: "지오코더 URL",
    geocoderOptions: "지오코더 옵션",
    autoComplete: "자동 완성",
    maxLocations: "최대 위치",
    minCharacters: "최소 문자",
    searchDelay: "검색 지연",
    placeholder: "플레이스홀더",
    routeOptions: "경로 옵션",
    directionsLanguage: "길찾기 언어",
    directionsLengthUnits: "길찾기 길이 단위",
    directionsOutputType: "길찾기 결과 유형",
    impedanceAttribute: "임피던스 속성",
    kilometers: "킬로미터",
    miles: "마일",
    meters: "미터",
    feet: "피트",
    yards: "야드",
    nauticalMiles: "해리",
    parametersTip: "매개변수를 올바르게 설정하세요.",
    complete: "완료",
    completeNoEvents: "완료(이벤트 없음)",
    instructionsOnly: "지침만",
    standard: "표준",
    summaryOnly: "요약만",
    travelModesUrl: "이동 모드 URL",
    searchPlaceholder: "주소 또는 위치 찾기",
    trafficLayerUrl: "교통량 레이어 URL"
  })
);