define(
   ({
    _widgetLabel: "Durum Farkındalığı (Beta)",
    locate_incident: "Olay Bul",
    clear_incidents: "Olayları Temizle",
    reverse_geocoded_address: "En yakın adres",
    reverse_geocoded_error: "Kullanılabilir değil",
    miles: "Mil",
    kilometers: "Kilometre",
    feet: "Fit",
    meters: "Metre",
    yards: "Yarda",
    nauticalMiles: "Deniz Mili",
    now: "ŞİMDİ",
    wind: "RÜZGAR",
    SUN: "PAZ",
    MON: "PTS",
    TUE: "SAL",
    WED: "ÇAR",
    THU: "PER",
    FRI: "CUM",
    SAT: "CTS",
    defaultTabMsg: "Tanımlanan olay yok.",
    actionLabel: "Olay Olarak Ayarla",
    drawPoint: "Nokta Çiz",
    drawLine: "Çizgi Çiz",
    drawPolygon: "Alan Çiz",
    saveIncident: "Olayı Kaydet",
    clearIncident: "Olayı Temizle",
    useMapExtent: "Geçerli harita yayılımını kullan",
    noFeaturesFound: "Detay bulunamadı.",
    downloadCSV: "CSV İNDİR",
    editComplete: "Detay başarıyla kaydedildi!",
    updateComplete: "Detay başarıyla güncellendi!",
    deleteComplete: "Detay başarıyla silindi!",
    sum: "TOP",
    min: "MIN",
    max: "MAKS",
    avg: "ORT",
    count: "SAYIM",
    area: "ALAN",
    length: "UZUNLUK",
    notPolySave: "Kaydetmeden önce bir tampon mesafesi belirtin.",
    update_btn: "Güncelle",
    delete_btn: "Sil"
  })
);
