define(
   ({
    "tabs_section_Label": "לשוניות",
    "addTab": "הוסף לשונית",
    "layerName": "שכבה",
    "layerType": "סוג ניתוח",
    "layerLabel": "תווית",
    "actions": "פעולות",
    "closest": "היישות הקרובה ביותר",
    "proximity": "קרבה",
    "summary": "סיכום",
    "select_lbl": "-- בחר --",
    "general_setting_Label": "הגדרות כלליות",
    "units_text_lbl": "יחידות מרחק",
    "miles": "מיילים",
    "kilometers": "קילומטרים",
    "feet": "רגל",
    "meters": "מטרים",
    "yards": "יארד",
    "nauticalMiles": "מיילים ימיים",
    "maximum_distance_lbl": "מרחק מקסימום מהיישות הקרובה ביותר",
    "buffer_text_lbl": "תווית חיץ",
    "buffer_lbl": "מרחק חיץ",
    "buffer_max_lbl": "מרחק מקסימום לחיץ",
    "buffer_min_lbl": "מרחק מינימום לחיץ",
    "routing_checkBox": "הפעל ניתוב",
    "weather_Label": "אפשרויות מזג אוויר",
    "weather_checkBox": "כלול מידע על מזג אוויר",
    "selectLayers": "בחר שכבות מזג אוויר",
    "currentlySelectedLayer": "שכבות מזג אוויר בחורות נוכחיות",
    "missingTabLabel": "לפחות לאחת מהלשוניות חסרה תווית",
    "cancel": "בטל",
    "ok": "אישור",
    "missingLayerInWebMap": "לא נמצאו שכבות אופרטיביות.",
    "selectFields": "בחר שדות",
    "addField": "הוסף שדה",
    "sum": "סכום",
    "min": "מינימום",
    "max": "מקסימום",
    "avg": "ממוצע",
    "count": "ספירה",
    "area": "אזור",
    "length": "אורך",
    "count_checkBox": "הצג ספירה",
    "area_checkBox": "הצג שטח",
    "length_checkBox": "הצג אורך",
    "max_records": "הגעת למספר המקסימלי"
  })
);
