define(
	 ({
		chartTasks: "Diagrammi toimingud",
		addNew: "Lisa uus",
		addNewTip: "Lisa uus diagrammi toiming",
		name: "Nimi",
		set: "Määra",
		setDataSource: "Määra andmeallikas",
		generalSettingsTip: "Saate määrata diagrammide andmeallikad, pealkirjad ja kirjeldused.",
		chartModeSettingTip: "Saate valida andmete analüüsimise ja diagrammina kuvamise viisi.",
		detailsSettingTip: "Saate muuta diagrammi tüüpi, värvi ja valida kuvatavad väärtused:",
		symbolSettingTip: "Saate määrata diagrammile kantud andmete kaardil esitamise viisi.",
		addFilterTip: "Saate lisada nendele andmetele filtri.",
		dataSource: "Andmeallikas",
		noResults: "Objekte ei leitud.",
		chartTitle: "Diagrammi pealkiri",
		description: "Kirjeldus",
		chartingMode: "Diagrammi kuva",
		featureOption: "Kuva väärtused objektide kaupa",
		categoryOption: "Kuva väärtused kategooriate kaupa",
		countOption: "Kuva objektide kogused kategooriate kaupa",
		fieldOption: "Kuva atribuutide väärtused diagrammidena",
		category: "Kategooria",
		axisLabel: "Kategooria märgis",
		categoryField: "Kategooria väli",
		operation: "Toiming",
		originalOption: "Kasuta algväärtusi",
		sumOption: "Summa",
		averageOption: "Keskmine",
		minOption: "Miinimum",
		maxOption: "Maksimaalne",
		valueFields: "Väärtuste väljad",
		moveUp: "Liiguta ülespoole",
		moveDown: "Liiguta allapoole",
		sortOrder: "Sordi diagrammid kategooria märgiste põhjal",
		ascending: "Kasvav",
		descending: "Kahanev",
		chartType: "Diagrammi tüüp",
		column: "Tulpdiagramm",
		bar: "Lintdiagramm",
		line: "Joondiagramm",
		pie: "Sektordiagramm",
		chartColor: "Diagrammi värv",
		showDataLabels: "Kuva andmete märgised",
		setSymbol: "Valiku sümbol",
		setHighLightColor: "Esiletõstmise värv",
		settings: "Seaded",
		mapInterationOptions: "Kaardi interaktsiooni valikud",
		preview: "Eelvaade",
		ok: "OK",
		cancel: "Tühista",
		close: "Sulge",
		setFilterTip: "Määrake filter õigesti. ",
		setChartTitleTip: "Määrake diagrammi pealkiri.",
		setChartTypeTip: "Valige vähemalt üks diagrammitüüp.",
		setDataFieldTip: "Valige vähemalt üks väärtuse väli.",
		setOutputFieldTip: "Määrake väljundi väljad.",
		count: "Kogus",
		label: "Märgis",
		horizontalAxis: "Horisontaaltelg",
		verticalAxis: "Vertikaaltelg",
		dataLabels: "Andmete märgised",
		color: "Värv",
		colorful: "Värviline",
		monochromatic: "Ühevärviline",
    noTaskTip: "Uue diagrammitoimingu lisamiseks klõpsake käsku Lisa uus",
    info: "Teave",
    charts: "Graafikud",
    options: "Seaded",
    taskName: "Ülesande nimi",
    summary: "Kokkuvõte",
    resultDescription: "Tulemuse kirjeldus",
    spatialFilterTip: "Valige vidinas tulemuste piiramiseks ruumiline filter (filtrid).",
    defaultOption: "Vaikimisi",
    useCurrentExtentTip: "Osaliselt või täielikult praeguses kaardi kuvaulatuses",
    useDrawGraphicTip: "Osaliselt või täielikult kaardile joonistatud kujundis",
    useFeaturesTip: "Vastavalt nende asukohale teise kihi objektide suhtes",
    noSpatialLimitTip: "Ära piira tulemusi ruumiliselt",
    drawingTools: "Joonistamise töövahendid",
    bufferSettings: "Puhvri seaded",
    defaultDistance: "Vaike-vahemaa",
    bufferDistance: "Puhvri ulatus",
    defaultUnit: "Vaikeühik",
    miles: "Miilid",
    kilometers: "Kilomeetrid",
    feet: "Jalad",
    meters: "Meetrid",
    yards: "Jardid",
    nauticalMiles: "Meremiilid",
    availableSpatialRelationships: "Saadaolevad ruumilised seosed",
    setSpatialRelationships: "Määra ruumilised seosed",
    availability: "Saadavus",
    relationship: "Seos",
    actions: "Toimingud",
    intersect: "lõikuvad",
    contain: "sisaldavad",
    areContainedIn: "sisalduvad",
    cross: "rist",
    envelopeIntersect: "lõikuvad ümbrisega",
    overlap: "kattuvad",
    areOverlapped: "kaetakse",
    touche: "puutuvad kokku",
    within: "vahemikus",
    areWithin: "on vahemikus",
    indexIntersect: "lõikuvad indeksiga"
  })
);