define(
	 ({
		charts: "Diagrammiülesanded",
		addNew: "Lisa uus",
		addNewTip: "Lisa uus diagrammiülesanne",
		name: "Nimi",
		set: "Määra",
		setDataSource: "Määra andmeallikas",
		generalSettingsTip: "Saate määrata diagrammide andmeallikad, pealkirjad ja kirjeldused.",
		chartModeSettingTip: "Saate valida andmete analüüsimise ja diagrammina kuvamise viisi.",
		detailsSettingTip: "Saate muuta diagrammi tüüpi, värvi ja valida kuvatavad väärtused.",
		symbolSettingTip: "Saate määrata diagrammile kantud andmete kaardil esitamise viisi.",
		addFilterTip: "Saate lisada nendele andmetele filtri.",
		dataSource: "Andmeallikas",
		noResults: "Objekte ei leitud.",
		chartTitle: "Diagrammi pealkiri",
		description: "Kirjeldus",
		chartingMode: "Diagrammi kuva",
		featureOption: "Kuva väärtused objektide kaupa",
		categoryOption: "Kuva väärtused kategooriate kaupa",
		countOption: "Kuva objektide kogused kategooriate kaupa",
		fieldOption: "Kuva atribuutide väärtused diagrammidena",
		category: "Kategooria",
		axisLabel: "Kategooria märgis",
		categoryField: "Kategooria väli",
		operation: "Toiming",
		originalOption: "Kasuta algväärtusi",
		sumOption: "Summa",
		averageOption: "Keskmine",
		minOption: "Miinimum",
		maxOption: "Maksimaalne",
		valueFields: "Väärtuste väljad",
		moveUp: "Liiguta ülespoole",
		moveDown: "Liiguta allapoole",
		sortOrder: "Sordi diagrammid kategooria märgiste põhjal",
		ascending: "Kasvav",
		descending: "Kahanev",
		chartType: "Diagrammi tüüp",
		column: "Tulpdiagramm",
		bar: "Lintdiagramm",
		line: "Joondiagramm",
		pie: "Sektordiagramm",
		chartColor: "Diagrammi värv",
		showDataLabels: "Kuva andmete märgised",
		setSymbol: "Valiku sümbol",
		setHighLightColor: "Esiletõstmise värv",
		settings: "Seaded",
		mapInterationOptions: "Kaardi interaktsiooni valikud",
		preview: "Eelvaade",
		ok: "OK",
		cancel: "Tühista",
		close: "Sulge",
		setFilterTip: "Määrake filter õigesti. ",
		setChartTitleTip: "Määrake diagrammi nimi.",
		setChartTypeTip: "Valige vähemalt üks diagrammitüüp.",
		setDataFieldTip: "Valige vähemalt üks väärtuse väli.",
		setOutputFieldTip: "Määrake väljundi väljad.",
		count: "Loend",
		label: "Märgis",
		horizontalAxis: "Horisontaaltelg",
		verticalAxis: "Vertikaaltelg",
		dataLabels: "Andmete märgised",
		color: "Värv",
		colorful: "Värviline",
		monochromatic: "Ühevärviline"
  })
);