define(
   ({
    _widgetLabel: "Situationsopmærksomhed (beta)",
    locate_incident: "Find hændelse",
    clear_incidents: "Ryd hændelser",
    reverse_geocoded_address: "Nærmeste adresse",
    reverse_geocoded_error: "Not available",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    now: "NU",
    wind: "VIND",
    SUN: "SØN",
    MON: "MAN",
    TUE: "TIR",
    WED: "ONS",
    THU: "TOR",
    FRI: "FRE",
    SAT: "LØR",
    defaultTabMsg: "Ingen hændelser identificeret.",
    actionLabel: "Indstil som hændelse",
    drawPoint: "Tegn punkt",
    drawLine: "Tegn linje",
    drawPolygon: "Tegn polygon",
    saveIncident: "Gem hændelse",
    clearIncident: "Ryd hændelse",
    useMapExtent: "Brug den aktuelle kortudstrækning",
    noFeaturesFound: "Ingen objekte fundet.",
    downloadCSV: "HENT CSV",
    editComplete: "Objekt gemt med succes!",
    updateComplete: "Objekt opdateret med succes!",
    deleteComplete: "Objekt slettet med succes!",
    sum: "SUM",
    min: "MIN",
    max: "MAKS",
    avg: "GNM.SN",
    count: "OPTÆLLING",
    area: "OMRÅDE",
    length: "LÆNGDE",
    notPolySave: "Angiv en bufferafstand, før du gemmer.",
    update_btn: "Opdatér",
    delete_btn: "Slet"
  })
);
