define(
   ({
    selectAnalysisTools:"Gereçte kullanılacak analiz aracını seçin.",
    selected: "seçili",
    name: "Adı",
    graphicalDisplay:"Grafik gösterim",
    usage: "Kullanım",
    settings: "Ayarlar",
    toolSetting: "Araç ayrıntılarını ayarla",
    toolLabel: "Araç ekran adı",
    showHelpTip: "Yardım bağlantılarını araçta göster",
    showCurrentMapExtent: "Geçerli harita yayılımını kullan seçeneğini göster",
    showCredits: "<b>Kredileri göster</b> seçeneğini görüntüle",
    saveAsFeatureService: "Sonucu kullanıcının hesabına kaydet",
    showReadyToUseLayers: "ArcGIS Online Living Atlas of the World içinde kullanıma hazır katmanları göster",
    toolNotAvailable: "Harita gerekli detay katmanlarını kapsamadığı için bu araç kullanılamıyor.",
    aggregatePoints:"Noktaları Birleştir",
    aggregatePointsUsage:"Noktaları alanlarda noktaların bulunduğu yerlerde toplayın.",
    calculateDensity:"Yoğunluğu Hesapla",
    calculateDensityUsage:"Bazı olayların (nokta veya çizgi öznitelikleriyle temsil edilen) bilinen miktarlarını haritada yayarak nokta veya çizgilerden oluşan bir yoğunluk haritası oluşturun.",
    connectOriginsToDestinations: "Başlangıç Noktalarını Hedef Noktalarına Birleştir",
    connectOriginsToDestinationsUsage: "Nokta çiftleri arasında seyahat süresini veya mesafeyi ölçün.",
    createBuffers:"Tampon Oluştur",
    createBuffersUsage:"Girdi detaylarından tampon alanlar oluşturun.",
    createDriveTimeAreas:"Sürüş Süresi Alanları Oluştur",
    createDriveTimeAreasUsage:"Verilen sürüş süresi değerleri için girdi noktaları etrafında sürüş süresi (veya sürüş mesafesi) alanları oluşturun.",
    createViewshed:"Görüş Alanı Oluştur",
    createViewshedUsage:"Belirttiğiniz konumlara bağlı olarak görünür alanlar oluşturur.",
    createWatersheds:"Havza Oluştur",
    createWatershedsUsage:"Belirttiğiniz konumlara bağlı olarak havza oluşturur.",
    deriveNewLocations:"Yeni Konumlar Türet",
    deriveNewLocationsUsage:"Belirtilen bir sorguyu karşılayan girdi katmanlarından yeni detaylar alın",
    dissolveBoundaries:"Sınırları Birleştir",
    dissolveBoundariesUsage:"Örtüşen veya ortak bir sınır paylaşan alanları birleştirin.",
    enrichLayer:"Katmanı Zenginleştir",
    enrichLayerUsage:"Çevredeki alanlar hakkında insan, yer ve işletme ayrıntılarıyla girdi detaylarını zenginleştirin.",
    extractData:"Veri Çıkart",
    extractDataDesc:"Belli bir yayılımı olan bir veya birkaç katmandan veri ayıklayın",
    findExistingLocations:"Mevcut Konumları Bul",
    findExistingLocationsUsage:"Belirtilen bir öznitelik ve/veya mekansal sorguyu karşılayan girdi katmanındaki detayları seçin",
    findHotSpots:"Duyarlı Noktaları Bul",
    findHotSpotsUsage:"İstatistiksel olarak anlamlı girdi detayı veya yüksek/düşük değer gruplarını bulun.",
    findNearest:"En Yakındakini Bul",
    findNearestUsage:"Girdi katmanındaki her detay için bir diğer katmana olan en yakın detayını bulun",
    findSimilarLocations:"Benzer Konumlar Bul",
    findSimilarLocationsUsage:"Bir veya birkaç referans konuma aday olan konumların benzerliğini ölçün.",
    interpolatePoints:"Nokta Ara Değerlerini Hesapla",
    interpolatePointsUsage:"Bir nokta koleksiyonundan alınan ölçümlere dayanan yeni konumlardaki değerleri tahmin edin.",
    mergeLayers:"Katmanları Birleştir",
    mergeLayersUsage:"Birden çok katmandan aldığınız detayları yeni bir katmanda birleştirin",
    overlayLayers:"Katmanları Çakıştır",
    overlayLayersUsage:"Korunan özgün katmanlardan alınan bilgilerle birden çok katmanı bir tek katman olarak birleştir.",
    planRoutes:"Rotaları Planla",
    planRoutesUsage:"Görevlerin bir mobil iş gücü arasında etkin biçimde nasıl dağıtılacağını belirleyin.",
    summarizeNearby:"Yakındakileri Özetle",
    summarizeNearbyUsage:"Girdi katmanındaki her detay için belirli mesafedeki başka bir katmanda bulunan detay verilerini özetleyin.",
    summarizeWithin:"İçinde Özetle",
    summarizeWithinUsage:"Bir girdi alan katmanındaki her alan için başka bir katmandaki detaylardan gelen verileri özetleyin.",
    traceDownstream:"Akış Yönünde İzle",
    traceDownstreamUsage:"Belirttiğiniz konumlardan aşağı akış yönlü akış yollarını belirler."
  })
);
