define(
   ({
    selectAnalysisTools:"Gereçte listelenecek analiz aracını seçin.",
    selected: "seçili",
    name: "Adı",
    graphicalDisplay:"Grafik gösterim",
    usage: "Kullanım",
    toolNotAvailable: "Harita gerekli detay katmanlarını kapsamadığı için bu araç kullanılamıyor.",
    aggregatePoints:"Noktaları Birleştir",
    aggregatePointsUsage:"Noktaları alanlarda noktaların bulunduğu yerlerde toplayın.",
    aggregatePointsInputTip: "Alan detayındaki alanlara eklenecek nokta detay katmanını belirtin.",
    calculateDensity:"Yoğunluğu Hesapla",
    calculateDensityUsage:"Bazı olayların (nokta veya çizgi öznitelikleriyle temsil edilen) bilinen miktarlarını haritada yayarak nokta veya çizgilerden oluşan bir yoğunluk haritası oluşturun.",
    calculateDensityInputTip:"Yoğunluğun hesaplanacağı nokta veya çizgi detaylarını belirtin.",
    connectOriginsToDestinations: "Başlangıç Noktalarını Hedef Noktalarına Birleştir",
    connectOriginsToDestinationsUsage: "Nokta çiftleri arasında seyahat süresini veya mesafeyi ölçün.",
    connectOriginsToDestinationsInputTip: "Oluşturulacak rotaların başlangıç noktasını veya noktalarını belirtin.",
    createBuffers:"Tampon Oluştur",
    createBuffersUsage:"Girdi detaylarından tampon alanlar oluşturun.",
    createBuffersInputTip:"Tampon oluşturulacak nokta, çizgi veya alan detay katmanını belirtin.",
    createDriveTimeAreas:"Sürüş Süresi Alanları Oluştur",
    createDriveTimeAreasUsage:"Verilen sürüş süresi değerleri için girdi noktaları etrafında sürüş süresi (veya sürüş mesafesi) alanları oluşturun.",
    createDriveTimeAreasInputTip:"Sürüş süresi alanlarının çizileceği noktaları belirtin.",
    createViewshed:"Görüş Alanı Oluştur",
    createViewshedUsage:"Belirttiğiniz konumlara bağlı olarak görünür alanlar oluşturur.",
    createViewshedInputTip:"Görünür alanları tanımlamak için gözlemci konumlarını belirtin.",
    createWatersheds:"Havza Oluştur",
    createWatershedsUsage:"Belirttiğiniz konumlara bağlı olarak havza oluşturur.",
    createWatershedsInputTip:"Su havzalarını hesaplamak için kullanılan nokta detaylarını belirtin.",
    deriveNewLocations:"Yeni Konumlar Türet",
    deriveNewLocationsUsage:"Belirtilen bir sorguyu karşılayan girdi katmanlarından yeni detaylar alın",
    deriveNewLocationsInputTip:"Girdi olarak kullanılacak analiz katmanını belirtin.",
    dissolveBoundaries:"Sınırları Birleştir",
    dissolveBoundariesUsage:"Örtüşen veya ortak bir sınır paylaşan alanları birleştirin.",
    dissolveBoundariesInputTip:"Birleştirilecek alan detaylarını kapsayan katmanı belirtin.",
    enrichLayer:"Katmanı Zenginleştir",
    enrichLayerUsage:"Çevredeki alanlar hakkında insan, yer ve işletme ayrıntılarıyla girdi detaylarını zenginleştirin.",
    enrichLayerInputTip:"Yeni verileri zenginleştirecek detayları belirtin.",
    extractData:"Veri Çıkart",
    extractDataDesc:"Belli bir yayılımı olan bir veya birkaç katmandan veri ayıklayın",
    extractDataInputTip:"Ayıklanacak veri detay katmanını belirtin.",
    findExistingLocations:"Mevcut Konumları Bul",
    findExistingLocationsUsage:"Belirtilen bir öznitelik ve/veya mekansal sorguyu karşılayan girdi katmanındaki detayları seçin",
    findExistingLocationsInputTip:"Girdi olarak kullanılacak analiz katmanlarını belirtin.",
    findHotSpots:"Duyarlı Noktaları Bul",
    findHotSpotsUsage:"İstatistiksel olarak anlamlı girdi detayı veya yüksek/düşük değer gruplarını bulun.",
    findHotSpotsInputTip:"Kritik noktaların hesaplanacağı nokta veya alan detay katmanını belirtin.",
    findNearest:"En Yakındakini Bul",
    findNearestUsage:"Girdi katmanındaki her detay için bir diğer katmana olan en yakın detayını bulun",
    findNearestInputTip:"En yakın konumların bulunması için kullanılan nokta, çizgi veya alan detaylarını belirtin.",
    findSimilarLocations:"Benzer Konumlar Bul",
    findSimilarLocationsUsage:"Bir veya birkaç referans konuma aday olan konumların benzerliğini ölçün.",
    findSimilarLocationsInputTip:"Benzerlik için arama katmanında detayların değerlendirileceği bir veya birkaç referans konumu bulunduran bir detay katmanı belirtin.",
    interpolatePoints:"Nokta Ara Değerlerini Hesapla",
    interpolatePointsUsage:"Bir nokta koleksiyonundan alınan ölçümlere dayanan yeni konumlardaki değerleri tahmin edin.",
    interpolatePointsInputTip:"Ara değer hesaplanacak nokta detaylarını belirtin.",
    mergeLayers:"Katmanları Birleştir",
    mergeLayersUsage:"Birden çok katmandan aldığınız detayları yeni bir katmanda birleştirin",
    mergeLayersInputTip:"Birleştirme katmanıyla birleştirilecek detay katmanını belirtin.",
    overlayLayers:"Katmanları Çakıştır",
    overlayLayersUsage:"Korunan özgün katmanlardan alınan bilgilerle birden çok katmanı bir tek katman olarak birleştir.",
    overlayLayersInputTip:"Örtüşme katmanıyla örtüştürülecek detay katmanını belirtin.",
    planRoutes:"Rotaları Planla",
    planRoutesUsage:"Görevlerin bir mobil iş gücü arasında etkin biçimde nasıl dağıtılacağını belirleyin.",
    planRoutesInputTip:"Araçların, sürücülerin veya yolların geçmesi gereken noktaları belirtin.",
    summarizeNearby:"Yakındakileri Özetle",
    summarizeNearbyUsage:"Girdi katmanındaki her detay için belirli mesafedeki başka bir katmanda bulunan detay verilerini özetleyin.",
    summarizeNearbyInputTip:"Özet katmanındaki detaylara olan mesafelerin ölçüleceği nokta, çizgi veya alan detay katmanını belirtin.",
    summarizeWithin:"İçinde Özetle",
    summarizeWithinUsage:"Bir girdi alan katmanındaki her alan için başka bir katmandaki detaylardan gelen verileri özetleyin.",
    summarizeWithinInputTip:"Özetlenecek alan hedef detay katmanını belirtin.",
    traceDownstream:"Akış Yönünde İzle",
    traceDownstreamUsage:"Belirttiğiniz konumlardan aşağı akış yönlü akış yollarını belirler.",
    traceDownstreamInputTip:"Akış izinin başlangıç konumu için kullanılan nokta detaylarını belirtin."
  })
);
