define({
  selectFeatures: "按要素",
  selectByAttribute: "按属性",
  results: "结果",
  searchLayer: "要查询的图层",
  selectFeaturesBy: "按要素查找",
  search: "查询",
  clear: "清除",
  point: "点",
  line: "线",
  polyline: "折线",
  freehandPolyline: "手画折线",
  triangle: "三角形",
  extent: "矩形",
  circle: "圆",
  ellipse: "椭圆",
  polygon: "多边形",
  freehandPolygon: "手画多边形",
  featuresSelected: "选中的要素：",
  noResults: "无结果",
  searchError:"搜索失败 !",
  searchResult:"搜索结果"
});