define(
   ({
    _widgetLabel: "情况感知 (Beta 版)",
    locate_incident: "查找事件点",
    clear_incidents: "清除事件点",
    reverse_geocoded_address: "最近的地址",
    reverse_geocoded_error: "不可用",
    miles: "英里",
    kilometers: "公里",
    feet: "英尺",
    meters: "米",
    yards: "码",
    nauticalMiles: "海里",
    now: "当前",
    wind: "风力",
    SUN: "星期日",
    MON: "星期一",
    TUE: "星期二",
    WED: "星期三",
    THU: "星期四",
    FRI: "星期五",
    SAT: "星期六",
    defaultTabMsg: "未识别任何事件点。",
    actionLabel: "设为事件点",
    drawPoint: "绘制点",
    drawLine: "绘制线",
    drawPolygon: "绘制多边形",
    saveIncident: "保存事件点",
    clearIncident: "清除事件点",
    useMapExtent: "使用当前地图范围",
    noFeaturesFound: "未找到任何要素。",
    downloadCSV: "下载 CSV",
    editComplete: "要素已成功保存！",
    updateComplete: "要素已成功更新！",
    deleteComplete: "要素已成功删除！",
    sum: "总和",
    min: "最小值",
    max: "最大值",
    avg: "平均值",
    count: "计数",
    area: "面积",
    length: "长度",
    notPolySave: "在执行保存操作前请指定缓冲距离。",
    update_btn: "更新",
    delete_btn: "删除"
  })
);
