define(
   ({
    _widgetLabel: "Situationsmedvetenhet (beta)",
    locate_incident: "Hitta incident",
    clear_incidents: "Rensa incidenter",
    reverse_geocoded_address: "Närmaste adress",
    reverse_geocoded_error: "Not available",
    miles: "Engelska mil",
    kilometers: "Kilometer",
    feet: "Fot",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Nautiska mil",
    now: "NU",
    wind: "VIND",
    SUN: "SÖN",
    MON: "MÅN",
    TUE: "TIS",
    WED: "ONS",
    THU: "TOR",
    FRI: "FRE",
    SAT: "LÖR",
    defaultTabMsg: "Inga incidenter har identifierats.",
    actionLabel: "Ange som incident",
    drawPoint: "Rita punkt",
    drawLine: "Rita linje",
    drawPolygon: "Rita polygon",
    saveIncident: "Spara incident",
    clearIncident: "Rensa incident",
    useMapExtent: "Använd aktuell kartutbredning",
    noFeaturesFound: "Hittade inga objekt.",
    downloadCSV: "HÄMTA CSV",
    editComplete: "Geoobjektet har sparats.",
    updateComplete: "Geoobjektet har uppdaterats.",
    deleteComplete: "Geoobjektet har tagits bort.",
    sum: "SUMMA",
    min: "MIN",
    max: "MAX",
    avg: "SNITT",
    count: "ANTAL",
    area: "AREA",
    length: "LÄNGD",
    notPolySave: "Ange ett buffertavstånd innan du sparar.",
    update_btn: "Uppdatera",
    delete_btn: "Ta bort"
  })
);
