define(
   ({
    "tabs_section_Label": "Flikar",
    "addTab": "Lägg till flik",
    "layerName": "Lager",
    "layerType": "Analystyp",
    "layerLabel": "Etikett",
    "actions": "Åtgärder",
    "closest": "Närmaste geoobjekt",
    "proximity": "Närhet",
    "summary": "Sammanfattning",
    "select_lbl": "-- Välj --",
    "general_setting_Label": "Allmänna inställningar",
    "units_text_lbl": "Distansenheter",
    "miles": "Engelska mil",
    "kilometers": "Kilometer",
    "feet": "Fot",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Nautiska mil",
    "maximum_distance_lbl": "Maximalt avstånd till närmaste geoobjekt",
    "buffer_text_lbl": "Buffertetikett",
    "buffer_lbl": "Buffertavstånd",
    "buffer_max_lbl": "Maximalt buffertavstånd",
    "buffer_min_lbl": "Minsta buffertavstånd",
    "routing_checkBox": "Aktivera rutter",
    "weather_Label": "Väderalternativ",
    "weather_checkBox": "Ta med väderinformation",
    "selectLayers": "Välj väderlager",
    "currentlySelectedLayer": "Valda väderlager",
    "missingTabLabel": "Minst en flik saknar sin etikett",
    "cancel": "Avbryt",
    "ok": "OK",
    "missingLayerInWebMap": "Inga funktionslager hittades.",
    "selectFields": "Välj fält",
    "addField": "Lägg till fält",
    "sum": "SUMMA",
    "min": "MIN",
    "max": "MAX",
    "avg": "SNITT",
    "count": "ANTAL",
    "area": "AREA",
    "length": "LÄNGD",
    "count_checkBox": "Visa antal",
    "area_checkBox": "Visa area",
    "length_checkBox": "Visa längd",
    "max_records": "Maximigränsen är nådd"
  })
);
