define(
   ({
    _widgetLabel: "Diagramm",
    executeChartTip: "Klicken Sie auf einen der folgenden Tasks, um das Diagramm auszuführen.",
    invalidConfig: "Ungültige Konfiguration.",
    noneChartTip: "Für dieses Widget wurde kein Diagramm-Task konfiguriert.",
    chartParams: "Optionen",
    charts: "DIAGRAMME",
    apply: "ÜBERNEHMEN",
    useSpatialFilter: "Räumlichen Filter zum Begrenzen von Features verwenden",
    useCurrentMapExtent: "Nur Features, die den aktuellen Kartenbereich schneiden",
    drawGraphicOnMap: "Nur Features, die einen benutzerdefinierten Bereich schneiden",
    chartResults: "Diagrammergebnisse",
    clearResults: "Ergebnisse löschen",
    noPermissionsMsg: "Sie verfügen nicht über die entsprechenden Berechtigungen für den Zugriff auf diesen Service.",
    specifySpatialFilterMsg: "Geben Sie einen räumlichen Filter für diesen Task an.",
    queryError: "Abfrage fehlgeschlagen.",
    noResults: "Kein Feature gefunden.",
    category: "Kategorie",
    count: "Anzahl",
    label: "Beschriftung",
    horizontalAxis: "Horizontale Achse",
    verticalAxis: "Vertikale Achse",
    dataLabels: "Datenbeschriftungen",
    color: "Farbe",
    colorful: "Farbig",
    monochromatic: "Einfarbig",
    tasks: "Tasks",
    results: "Ergebnisse",
    applySpatialFilterToLimitResults: "Zum Eingrenzen der Ergebnisse einen räumlichen Filter anwenden",
    useCurrentExtentTip: "Teilweise oder vollständig innerhalb der aktuellen Kartenausdehnung",
    useDrawGraphicTip: "Teilweise oder vollständig innerhalb des auf der Karte dargestellten Shapes",
    useFeaturesTip: "Basierend auf deren Positionen relativ zu Features in einem anderen Layer",
    noSpatialLimitTip: "Ergebnisse nicht räumlich beschränken",
    applySearchDistance: "Eine Suchentfernung anwenden",
    spatialRelationship: "Räumliche Beziehung",
    relatedLayer: "Zugehöriger Layer",
    clear: "Auswahl aufheben",
    bufferDistance: "Pufferabstand",
    miles: "Meilen",
    kilometers: "Kilometer",
    feet: "Fuß",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Seemeilen",
    back: "Zurück",
    execute: "Ausführen"
  })
);