define(
   ({
    taskUrl: "任务 URL",
    serviceURLPlaceholder: "请输入地理处理任务 URL",
    ok: "确定",
    cancel: "取消",
    layer: "图层",
    action: "操作",
    input: "输入",
    output: "输出",
    name: "名称",
    type: "类型",
    required: "必填字段",
    layerOrder: "图层顺序",
    options: "选项",
    defaultValue: "默认值",
    inputFeatureBy: "输入要素",
    renderer: "渲染器",
    displayType: "显示类型",
    label: "标注",
    tooltip: "工具提示",
    visible: "可见",
    helpUrl: "帮助 URL",
    useResultMapService: "使用结果地图服务的绘制选项",
    drawOnMap: "在地图上交互绘制",
    selectLayer: "从地图选择图层",
    url: "URL",
    symbol: "符号",
    shareResults: "将结果添加为业务图层",
    popup: "弹出窗口",
    setTask: "设置",
    setTaskTitle: "设置 GP 任务",
    enablePopup: "启用弹出窗口"
  })
);