define(
   ({
    _widgetLabel: "Geoduomenų apdorojimas",
    execute: "Vykdyti",
    help: "Pagalba",
    input: "Įvestis",
    output: "Išvestis",
    executing: "Vykdoma",
    requiredInfo: "būtina.",
    drawnOnMap: "Rezultatas nupieštas žemėlapyje.",
    clear: "Valyti",
    error: "Klaida",
    noToolConfig: "Iš anksto sukonfigūruotos geoduomenų apdorojimo užduoties nėra.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Įkelti failą",
    selectFileToUpload: 'Pasirinkite failą...',
    upload: 'Nusiųsti',
    rasterFormat: 'Rastrinių duomenų formatas',
    noFileSelected: 'Nepasirinktas joks failas!',
    uploadSuccess:'Failas įkeltas sėkmingai!',
    url: "URL",
    showLayerContent: "Rodyti sluoksnio turinį",
    invalidUrl: "Netinkamas elementų paslaugos url",
    Feet: "Pėdos",
    Yards: "Jardai",
    Miles: "Mylios",
    NauticalMiles: "Jūrmylės",
    Meter: "Metrai",
    Kilometers: "Kilometrai",
    urlPlaceholder: "elementui nustatytas URL"
  })
);
