define(
   ({
    _widgetLabel: "Análisis de incidentes",
    incident: "Incidente",
    weather: "Tiempo",
    locate_incident: "Localizar incidente",
    clear_incidents: "Borrar incidentes",
    reverse_geocoded_address: "Dirección más próxima",
    reverse_geocoded_error: "No disponible",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    now: "AHORA",
    wind: "VIENTO",
    SUN: "DOM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MIÉ",
    THU: "JUE",
    FRI: "VIE",
    SAT: "SÁB",
    defaultTabMsg: "No se han identificado incidentes.",
    actionLabel: "Establecer como incidente",
    useMapExtent: "Usar la extensión del mapa actual",
    noFeaturesFound: "No se encontraron entidades.",
    downloadCSV: "DESCARGAR CSV",
    sum: "SUM",
    min: "MIN",
    max: "MÁX",
    avg: "AVG",
    count: "TOTAL",
    area: "ÁREA",
    length: "LONGITUD"
  })
);
