define(
	 ({
		chartTasks: "Úlohy grafů",
		addNew: "Přidat nový",
		addNewTip: "Přidat novou úlohu grafu",
		name: "Název",
		set: "Nastavit",
		setDataSource: "Nastavit zdroj dat",
		generalSettingsTip: "Nastavte zdroj dat, název a popis grafu.",
		chartModeSettingTip: "Zvolte způsob, kterým chcete data analyzovat a zobrazovat v grafech.",
		detailsSettingTip: "Nastavte vzhled grafu zvolením typu grafu, barev a hodnot vykreslených v grafu:",
		symbolSettingTip: "Nastavte zobrazení mapy pro data zpracovaná v grafu.",
		addFilterTip: "Přidat filtr k těmto datům",
		dataSource: "Zdroj dat",
		noResults: "Nebyl nalezen žádný prvek",
		chartTitle: "Název grafu",
		description: "Popis",
		chartingMode: "Zobrazení grafu",
		featureOption: "Zobrazit hodnoty prvek po prvku",
		categoryOption: "Zobrazit hodnoty podle kategorie",
		countOption: "Zobrazit počty prvků podle kategorie",
		fieldOption: "Zobrazit hodnoty atributů jako grafy",
		category: "Kategorie",
		axisLabel: "Popisek kategorie",
		categoryField: "Pole kategorie",
		operation: "Operace",
		originalOption: "Použít původní hodnoty",
		sumOption: "Součet",
		averageOption: "Průměr",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Pole hodnot",
		moveUp: "Přesunout nahoru",
		moveDown: "Přesunout dolů",
		sortOrder: "Řadit grafy podle popisků kategorií",
		ascending: "Vzestupně",
		descending: "Sestupně",
		chartType: "Typ grafu",
		column: "Sloupcový graf",
		bar: "Pruhový graf",
		line: "Spojnicový graf",
		pie: "Koláčový graf",
		chartColor: "Barva grafu",
		showDataLabels: "Zobrazit popisky dat",
		setSymbol: "Symbol výběru",
		setHighLightColor: "Barva zvýraznění",
		settings: "Nastavení",
		mapInterationOptions: "Možnosti interakce s mapou",
		preview: "Náhled",
		ok: "OK",
		cancel: "Storno",
		close: "Zavřít",
		setFilterTip: "Nastavte filtr správně. ",
		setChartTitleTip: "Nastavte název grafu.",
		setChartTypeTip: "Vyberte alespoň jeden typ grafu.",
		setDataFieldTip: "Vyberte alespoň jedno pole s  hodnotami.",
		setOutputFieldTip: "Nastavte výstupní pole.",
		count: "Počet",
		label: "Štítek",
		horizontalAxis: "Vodorovná osa",
		verticalAxis: "Svislá osa",
		dataLabels: "Popisky dat",
		color: "Barva",
		colorful: "Barevné",
		monochromatic: "Monochromatické",
    noTaskTip: "Kliknutím na Přidat nový přidáte novou úlohu grafu",
    info: "Informace",
    charts: "Grafy",
    options: "Možnosti",
    taskName: "Název úlohy",
    summary: "Souhrn",
    resultDescription: "Popis výsledku",
    spatialFilterTip: "Zvolte prostorové filtry, které se ve widgetu použijí k omezení výsledků.",
    defaultOption: "Výchozí",
    useCurrentExtentTip: "Zčásti nebo zcela v aktuálním rozsahu mapy",
    useDrawGraphicTip: "Zčásti nebo zcela v obrazci nakresleném v mapě",
    useFeaturesTip: "Na základě umístění prvků v jiné vrstvě",
    noSpatialLimitTip: "Neomezovat výsledky podle polohy",
    drawingTools: "Nástroje kreslení",
    bufferSettings: "Nastavení obalové zóny",
    defaultDistance: "Výchozí vzdálenost",
    bufferDistance: "Šířka obalové zóny",
    defaultUnit: "Výchozí jednotka",
    miles: "Míle",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    availableSpatialRelationships: "Dostupné prostorové vztahy",
    setSpatialRelationships: "Nastavit prostorové vztahy",
    availability: "Dostupnost",
    relationship: "Relace",
    actions: "Akce",
    intersect: "protínají",
    contain: "obsahují",
    areContainedIn: "jsou obsaženy v",
    cross: "křížek",
    envelopeIntersect: "protínají obálku",
    overlap: "překrývají",
    areOverlapped: "jsou překryté",
    touche: "dotýkají se",
    within: "v dosahu",
    areWithin: "jsou v dosahu",
    indexIntersect: "protínají index"
  })
);