define(
   ({
    taskUrl: "URL de tarea",
    serviceURLPlaceholder: "Introduce la URL de tarea de geoprocesamiento",
    ok: "Aceptar",
    cancel: "Cancelar",
    layer: "Capa",
    action: "Acción",
    input: "Entrada",
    output: "Salida",
    name: "Nombre",
    type: "Tipo",
    required: "Obligatorio",
    layerOrder: "Orden de capa",
    options: "Opciones",
    defaultValue: "Valor predeterminado",
    inputFeatureBy: "Introducir entidad por",
    renderer: "Renderizador",
    displayType: "Mostrar tipo",
    label: "Etiqueta",
    tooltip: "Información sobre herramientas",
    visible: "Visible",
    helpUrl: "URL de ayuda",
    useResultMapService: "Utiliza las opciones de dibujo del servicio de mapa de resultado",
    drawOnMap: "Dibujo interactivo en el mapa",
    selectLayer: "Seleccionar una capa del mapa",
    url: "URL",
    symbol: "Símbolo",
    shareResults: "Agregar resultado como capa operativa",
    popup: "Elemento emergente",
    setTask: "Establecer",
    setTaskTitle: "Establecer tarea de geoprocesamiento",
    enablePopup: "Habilitar ventana emergente",
    unSupportGeometryType: "No se puede definir el renderizador porque el tipo de geometría es desconocido.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Cargar archivo",
    selectFileToUpload: "Seleccionar archivo...",
    upload: "Cargar",
    rasterFormat: "Formato de datos ráster",
    noFileSelected: "No hay ningún archivo seleccionado",
    uploadSuccess:"Archivo cargado correctamente",
    showLayerContent: "Mostrar contenido de capa",
    Feet: "Pies",
    Yards: "Yardas",
    Miles: "Millas",
    NauticalMiles: "Millas Náuticas",
    Meter: "Metros",
    Kilometers: "Kilómetros",
    urlPlaceholder: "Dirección URL del conjunto de entidades",
    allowToExport: "Permitir la exportación de resultados"
  })
);
