define(
   ({
    taskUrl: "URL de tarea",
    serviceURLPlaceholder: "Introduce la URL de tarea de geoprocesamiento",
    ok: "Aceptar",
    cancel: "Cancelar",
    layer: "Capa",
    action: "Acción",
    input: "Entrada",
    output: "Salida",
    name: "Nombre",
    type: "Tipo",
    required: "Obligatorio",
    layerOrder: "Orden de capa",
    options: "Opciones",
    defaultValue: "Valor predeterminado",
    inputFeatureBy: "Introducir entidad por",
    renderer: "Renderizador",
    displayType: "Mostrar tipo",
    label: "Etiqueta",
    tooltip: "Información sobre herramientas",
    visible: "Visible",
    helpUrl: "URL de ayuda",
    useResultMapService: "Utiliza las opciones de dibujo del servicio de mapa de resultado",
    drawOnMap: "Dibujo interactivo en el mapa",
    selectLayer: "Seleccionar una capa del mapa",
    url: "URL",
    symbol: "Símbolo",
    shareResults: "Agregar resultado como capa operativa",
    popup: "Elemento emergente",
    setTask: "Establecer",
    setTaskTitle: "Establecer tarea de geoprocesamiento",
    enablePopup: "Habilitar ventana emergente"
  })
);