define(
   ({
    _widgetLabel: "Imprimir",
    title: "Título de mapa",
    format: "Formato",
    layout: "Diseño",
    settings: "Avanzado",
    mapScaleExtent: "Escala/extensión de mapa",
    preserve: "Preservar",
    mapScale: "escala de mapa",
    mapExtent: "extensión de mapa",
    forceScale: "Forzar escala",
    getCurrentScale: "actual",
    mapMetadata: "Metadatos de diseño",
    author: "Autor",
    copyright: "Copyright",
    fullLayoutOptions: "Opciones de diseño completo",
    scaleBarUnitsMetric: "Unidades métricas de barra de escala",
    scaleBarUnitsNonMetric: "Unidades no métricas de barra de escala",
    unitsMiles: "Millas",
    unitsKilometers: "Kilómetros",
    unitsMeters: "Metros",
    unitsFeet: "Pies",
    unitsYards: "Yardas",
    unitsNauticalMiles: "Millas náuticas",
    lncludeLegend: "Incluir leyenda",
    printQualityOptions: "Calidad de impresión",
    dpi: "PPP",
    mapOnlyOptions: "Tamaño MAP_ONLY",
    width: "Ancho (px)",
    height: "Alto (px)",
    print: "Imprimir",
    clearList: "Borrar impresiones",
    creatingPrint: "Creando impresión",
    printError: "Error, vuelve a intentarlo"
  })
);