define(
   ({
    _widgetLabel: "Ataskaitos klaida",
    select: "Pasirinkite",
    draw: "Piešti",
    chooseALayer: "Pasirinkite sluoksnį",
    clickAFeature: "Spustelėkite žemėlapio elementą, kad jį pasirinktumėte.",
    loadingFeatures: "Gaunama išsami pasirinkto elemento informacija...",
    errorTitle: "Klaida",
    errorIdentify: "Įvyko klaida identifikuojant elementus. Išsamesnės informacijos rasite konsolės žurnale.",
    infoWindowTitle: "Išsamiau",
    layerLabel: "Sluoksnio pavadinimas",
    reviewStatusLabel: "Peržiūrėti būseną",
    selectReviewStatusAdd: "Įtraukti funkciją",
    selectReviewStatusDelete: "Ištrinti elementą",
    selectReviewStatusMove: "Perkelti funkciją",
    selectReviewStatusReshape: "Perbraižyti elementą",
    drawReviewStatusMissing: "Trūksta elemento (-ų)",
    drawReviewStatusPosition: "Pozicinė klaida",
    drawReviewStatusShape: "Figūros klaida",
    drawReviewStatusAttribute: "Atributo klaida",
    notesLabel: "Išnašos",
    severityLabel: "Svarba",
    reportedByLabel: "Pranešė",
    reportedByDefault: "anonimas",
    reportButton: "Ataskaita",
    reportMessage: "Ataskaita gauta",
    errorReportMessage: "Įvyko klaida naujinant jūsų elementus",
    drawErrorInstructions: "Pasirinkite tašką, liniją arba daugiakampį ir brėžkite klaidos geometriją ant žemėlapio:",
    errorMapService: "Gaunant žemėlapių paslaugos informaciją įvyko klaida",
    noFeatureSelected : "Spustelėtoje vietoje nerasta elementų",
    selectFeatureMapPoint: "Spustelėkite, kad pasirinktumėte elementą",
    drawFeatureMapPoint: "Spustelkite taškui pridėti",
    popupMessage:"Pranešimas",
    popupError:"Klaida",
    manyFeaturesSelected: "Rastas daugiau nei vienas elementas. Priartinkite ir pasirinkite elementą, apie kurį norite pranešti."
  })
);
