define(
   ({
    routeUrl: "URL de ruta",
    locatorUrl: "Dirección URL del geocodificador",
    geocoderOptions: "Opciones de geocodificador",
    autoComplete: "Autocompletar",
    maxLocations: "Ubicaciones máximas",
    minCharacters: "Caracteres mínimos",
    searchDelay: "Retardo de búsqueda",
    placeholder: "Marcador de posición",
    routeOptions: "Opciones de ruta",
    directionsLanguage: "Idioma de las indicaciones",
    directionsLengthUnits: "Unidades de longitud de las indicaciones",
    directionsOutputType: "Tipo de salida de las indicaciones",
    impedanceAttribute: "Atributo de impedancia",
    kilometers: "Kilómetros",
    miles: "Millas",
    meters: "Metros",
    feet: "Pies",
    yards: "Yardas",
    nauticalMiles: "Millas náuticas",
    parametersTip: "Establece los parámetros correctamente",
    complete: "Completar",
    completeNoEvents: "Completar sin eventos",
    instructionsOnly: "Solo instrucciones",
    standard: "Estándar",
    summaryOnly: "Solo resumen",
    travelModesUrl: "URL de modos de viaje",
    searchPlaceholder: "Buscar dirección o lugar",
    trafficLayerUrl: "Dirección URL de la capa de tráfico"
  })
);