define(
   ({
    "tabs_section_Label": "Kategorier",
    "addTab": "Legg til kategori",
    "layerName": "Lag",
    "layerType": "Analysetype",
    "layerLabel": "Etikett",
    "actions": "Handlinger",
    "closest": "Nærmeste geoobjekt",
    "proximity": "Nærhet",
    "summary": "Sammendrag",
    "select_lbl": "-- Velg --",
    "general_setting_Label": "Generelle innstillinger",
    "units_text_lbl": "Avstandsenheter",
    "miles": "Miles",
    "kilometers": "kilometer",
    "feet": "fot",
    "meters": "meter",
    "yards": "Yards",
    "nauticalMiles": "Nautiske mil",
    "maximum_distance_lbl": "Maks. avstand for nærmeste geoobjekt",
    "buffer_text_lbl": "Bufferpåskrift",
    "buffer_lbl": "Bufferavstand",
    "buffer_max_lbl": "Maks. bufferavstand",
    "buffer_min_lbl": "Minste bufferavstand",
    "routing_checkBox": "Aktiver rutetjenester",
    "weather_Label": "Væralternativer",
    "weather_checkBox": "Inkluder værinformasjon",
    "selectLayers": "Velg værlag",
    "currentlySelectedLayer": "Valgte værlag",
    "missingTabLabel": "Minst én kategori mangler påskrift",
    "cancel": "Avbryt",
    "ok": "Ok",
    "missingLayerInWebMap": "Finner ingen operative lag.",
    "selectFields": "Velg felter",
    "addField": "Legg til felt",
    "sum": "SUM",
    "min": "MIN.",
    "max": "MAKS.",
    "avg": "GJ.SN.",
    "count": "ANTALL",
    "area": "OMRÅDE",
    "length": "LENGDE",
    "count_checkBox": "Vis antall",
    "area_checkBox": "Vis område",
    "length_checkBox": "Vis lengde",
    "max_records": "Maksimumsgrensen er nådd"
  })
);
