define(
   ({
    _widgetLabel: "Interogare",
    executeQueryTip: "Faceţi clic pe unul din următoarele elemente de operaţii pentru a executa interogarea.",
    invalidConfig: "Configuraţie nevalidă. Utilizaţi pagina de setare a interogării pentru a obţine configuraţia corectă.",
    queryParams: "Opţiuni",
    parameters: "OPŢIUNI",
    queries: "INTEROGĂRI",
    apply: "APLICARE",
    queryResults: "Rezultate",
    clear: "Golire",
    noResults: "Nu a fost găsit niciun obiect spaţial.",
    queryError: "Interogare eşuată!",
    numberFound: "Număr de obiecte spaţiale găsite",
    mapExtentTip: "Limitaţi rezultatele la suprafaţa curentă a hărţii.",
    noValue: "Nicio valoare",
    and: "şi",
    stringOperatorIs: "este", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "nu este",
    stringOperatorStartsWith: "începe cu",
    stringOperatorEndsWith: "se termină cu",
    stringOperatorContains: "conţine",
    stringOperatorDoesNotContain: "nu conţine",
    stringOperatorIsBlank: "este necompletat",
    stringOperatorIsNotBlank: "nu este necompletat",
    dateOperatorIsOn: "este pe", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "nu este pe",
    dateOperatorIsBefore: "este înainte de",
    dateOperatorIsAfter: "este după",
    dateOperatorDays: "zile",
    dateOperatorWeeks: "săptămâni", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "luni",
    dateOperatorInTheLast: "în ultimele",
    dateOperatorNotInTheLast: "nu este în ultimele",
    dateOperatorIsBetween: "este între",
    dateOperatorIsNotBetween: "nu este între",
    dateOperatorIsBlank: "este necompletat",
    dateOperatorIsNotBlank: "nu este necompletat",
    numberOperatorIs: "este", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "nu este",
    numberOperatorIsAtLeast: "este cel puţin",
    numberOperatorIsLessThan: "este mai mică decât",
    numberOperatorIsAtMost: "este cel mult",
    numberOperatorIsGreaterThan: "este mai mare de",
    numberOperatorIsBetween: "este între",
    numberOperatorIsNotBetween: "nu este între",
    numberOperatorIsBlank: "este necompletat",
    numberOperatorIsNotBlank: "nu este necompletat",
    operationalLayerTip: "Adăugare rezultat drept strat tematic operaţional",
    queryResult: "Rezultat interogare",
    specifyParamsTip: "Specificaţi parametri pentru această operaţie",
    useSpatialFilter: "Utilizare filtru spaţial pentru limitarea obiectelor spaţiale",
    useCurrentMapExtent: "Numai obiectele spaţiale care se intersectează cu suprafaţa curentă a hărţii",
    drawGraphicOnMap: "Numai obiectele spaţiale care se intersectează cu suprafaţa definită de utilizator",
    specifySpatialFilterMsg: "Specificaţi filtrul spaţial pentru această operaţie.",
    clearResults: "Golire rezultate",
    operationalTip: 'Având această opţiune bifată, rezultatele vor fi păstrate pe hartă până când se face clic pe butonul „${clearResults}”.',
    noneQueryTip: "Pentru acest widget nu a fost configurată nicio activitate de interogare.",
    noPermissionsMsg: "Nu deţineţi permisiuni pentru accesarea acestui serviciu.",
    attributesFromRelationship: "Atribute din tabelul asociat",
    tasks: "Sarcini",
    applySpatialFilterToLimitResults: "Aplicaţi un filtru spaţial pentru limitarea rezultatelor",
    useCurrentExtentTip: "Parţial sau complet în cadrul extinderii curente de hartă",
    useDrawGraphicTip: "Parţial sau complet în cadrul formei trasate pe hartă",
    useFeaturesTip: "În baza locaţiilor, în raport cu obiectele spaţiale din alt strat tematic",
    noSpatialLimitTip: "Nu limitaţi spaţial rezultatele",
    applySearchDistance: "Aplicaţi o distanţă de căutare",
    spatialRelationship: "Relaţie spaţială",
    relatedLayer: "Strat tematic corelat",
    bufferDistance: "Distanţă buffer",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    back: "Înapoi",
    execute: "Executare"
  })
);