define(
   ({
    _widgetLabel: "Interogare",
    executeQueryTip: "Faceţi clic pe unul din următoarele elemente de operaţii pentru a executa interogarea.",
    invalidConfig: "Configuraţie nevalidă. Utilizaţi pagina de setare a interogării pentru a obţine configuraţia corectă.",
    queryParams: "Opţiuni",
    parameters: "OPŢIUNI",
    queries: "INTEROGĂRI",
    apply: "APLICARE",
    queryResults: "Rezultate",
    clear: "Golire",
    noResults: "Nu a fost găsit niciun obiect spaţial.",
    queryError: "Interogare eşuată!",
    numberFound: "Număr de obiecte spaţiale găsite",
    mapExtentTip: "Limitaţi rezultatele la extinderea actuală a hărţii.",
    noValue: "Nicio valoare",
    and: "şi",
    stringOperatorIs: "este", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "nu este",
    stringOperatorStartsWith: "începe cu",
    stringOperatorEndsWith: "se termină cu",
    stringOperatorContains: "conţine",
    stringOperatorDoesNotContain: "nu conţine",
    stringOperatorIsBlank: "este necompletat",
    stringOperatorIsNotBlank: "nu este necompletat",
    dateOperatorIsOn: "este pe", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "nu este pe",
    dateOperatorIsBefore: "este înainte de",
    dateOperatorIsAfter: "este după",
    dateOperatorDays: "zile",
    dateOperatorWeeks: "săptămâni", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "luni",
    dateOperatorInTheLast: "în ultimele",
    dateOperatorNotInTheLast: "nu este în ultimele",
    dateOperatorIsBetween: "este între",
    dateOperatorIsNotBetween: "nu este între",
    dateOperatorIsBlank: "este necompletat",
    dateOperatorIsNotBlank: "nu este necompletat",
    numberOperatorIs: "este", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "nu este",
    numberOperatorIsAtLeast: "este cel puţin",
    numberOperatorIsLessThan: "este mai mică decât",
    numberOperatorIsAtMost: "este cel mult",
    numberOperatorIsGreaterThan: "este mai mare de",
    numberOperatorIsBetween: "este între",
    numberOperatorIsNotBetween: "nu este între",
    numberOperatorIsBlank: "este necompletat",
    numberOperatorIsNotBlank: "nu este necompletat",
    operationalLayerTip: "Adăugare rezultat drept strat tematic operaţional",
    queryResult: "Rezultat interogare",
    specifyParamsTip: "Specificaţi parametri pentru această operaţie",
    useSpatialFilter: "Utilizare filtru spaţial pentru limitarea obiectelor spaţiale",
    useCurrentMapExtent: "Numai obiectele spaţiale care ating extinderea curentă a hărţii",
    drawGraphicOnMap: "Numai obiectele spaţiale care ating o suprafaţă definită de utilizator",
    specifySpatialFilterMsg: "Specificaţi filtrul spaţial pentru această operaţie.",
    clearResults: "Golire rezultate",
    operationalTip: 'Având această opţiune bifată, rezultatele vor fi păstrate pe hartă până când se face clic pe butonul „${clearResults}”.',
    noneQueryTip: "Nu este disponibilă nicio activitate de interogare.",
    noPermissionsMsg: "Nu deţineţi permisiuni pentru accesarea acestui serviciu."
  })
);