define(
   ({
    routeUrl: "URL של המסלול",
    locatorUrl: "URL של מעגן הכתובות",
    geocoderOptions: "אפשרויות מעגן כתובות",
    autoComplete: "השלמה אוטומטית",
    maxLocations: "מקסימום מיקומים",
    minCharacters: "מינימום תווים",
    searchDelay: "השהיית חיפוש",
    placeholder: "ממלא מקום",
    routeOptions: "אפשרויות מסלול",
    directionsLanguage: "שפת הוראות נסיעה",
    directionsLengthUnits: "יחידות אורך להוראות נסיעה",
    directionsOutputType: "סוג פלט של הוראות הנסיעה",
    impedanceAttribute: "שדה עלות",
    kilometers: "קילומטרים",
    miles: "מיילים",
    meters: "מטרים",
    feet: "רגל",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    parametersTip: "הגדר פרמטרים כהלכה!",
    complete: "שלם",
    completeNoEvents: "שלם - ללא אירועים",
    instructionsOnly: "הנחיות בלבד",
    standard: "סטנדרטי",
    summaryOnly: "סיכום בלבד",
    travelModesUrl: "כתובת URL של מצבי נסיעה",
    searchPlaceholder: "מצא כתובת או מקום",
    trafficLayerUrl: "URL של שכבת תנועה"
  })
);