define(
   ({
    _widgetLabel: "Dotaz",
    executeQueryTip: "Kliknout na jednu z následujících položek úloh pro spuštění dotazu.",
    invalidConfig: "Neplatná konfigurace. Správnou konfiguraci naleznete na stránce Nastavení dotazů.",
    queryParams: "Možnosti",
    parameters: "MOŽNOSTI",
    queries: "DOTAZY",
    apply: "POUŽÍT",
    queryResults: "Výsledky",
    clear: "Vyprázdnit",
    noResults: "Žádný prvek nebyl nalezen.",
    queryError: "Dotazování se nezdařilo!",
    numberFound: "Počet nalezených prvků",
    mapExtentTip: "Umožňuje omezit výsledky na aktuální rozsah mapy.",
    noValue: "Žádná hodnota",
    and: "a",
    stringOperatorIs: "je", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "není",
    stringOperatorStartsWith: "začíná na",
    stringOperatorEndsWith: "končí na",
    stringOperatorContains: "obsahuje",
    stringOperatorDoesNotContain: "neobsahuje",
    stringOperatorIsBlank: "je prázdný",
    stringOperatorIsNotBlank: "není prázdný",
    dateOperatorIsOn: "je na", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "není na",
    dateOperatorIsBefore: "je před",
    dateOperatorIsAfter: "je za",
    dateOperatorDays: "dní",
    dateOperatorWeeks: "týdnů", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "měsíců",
    dateOperatorInTheLast: "za posledních",
    dateOperatorNotInTheLast: "ne za posledních",
    dateOperatorIsBetween: "je mezi",
    dateOperatorIsNotBetween: "není mezi",
    dateOperatorIsBlank: "je prázdný",
    dateOperatorIsNotBlank: "není prázdný",
    numberOperatorIs: "je", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "není",
    numberOperatorIsAtLeast: "je alespoň",
    numberOperatorIsLessThan: "je menší než",
    numberOperatorIsAtMost: "je nejvýše",
    numberOperatorIsGreaterThan: "je větší než",
    numberOperatorIsBetween: "je mezi",
    numberOperatorIsNotBetween: "není mezi",
    numberOperatorIsBlank: "je prázdný",
    numberOperatorIsNotBlank: "není prázdný",
    operationalLayerTip: "Přidat výsledek jako operační vrstvu",
    queryResult: "Výsledek dotazu",
    specifyParamsTip: "Zadejte parametry pro tuto úlohu.",
    useSpatialFilter: "Použít prostorový filtr k omezení prvků",
    useCurrentMapExtent: "Pouze prvky dotýkající se aktuálního rozsahu mapy",
    drawGraphicOnMap: "Pouze prvky dotýkající se oblasti definované uživatelem",
    specifySpatialFilterMsg: "Zadejte prostorový filtr pro tuto úlohu.",
    clearResults: "Smazat výsledky",
    operationalTip: 'Zaškrtnete-li tuto možnost, budou se výsledky zobrazovat na mapě, dokud nestisknete tlačítko ${clearResults}.',
    noneQueryTip: "K dispozici není žádná předem nakonfigurovaná úloha dotazů.",
    noPermissionsMsg: "Nemáte oprávnění pro přístup k této službě."
  })
);