define(
   ({
    selectAnalysisTools:"Wählen Sie Analysewerkzeuge aus, die im Widget verwendet werden sollen.",
    selected: "ausgewählt",
    name: "Name",
    graphicalDisplay:"Grafische Anzeige",
    usage: "Nutzung",
    settings: "Einstellungen",
    toolSetting: "Werkzeugdetails festlegen",
    toolLabel: "Der Anzeigename des Werkzeugs",
    showHelpTip: "Hilfe-Links im Widget anzeigen",
    showCurrentMapExtent: "Option zum Verwenden der aktuellen Kartenausdehnung anzeigen",
    showCredits: "Die Option <b>Credits anzeigen</b>",
    saveAsFeatureService: "Die Ergebnisse im Konto des Benutzers speichern",
    showReadyToUseLayers: "Sofort einsatzfähige Layer aus dem \"Living Atlas of the World\" von ArcGIS Online anzeigen",
    toolNotAvailable: "Dieses Werkzeug ist nicht verfügbar, da die Karte keine erforderlichen Feature-Layer enthält.",
    aggregatePoints:"Punkte aggregieren",
    aggregatePointsUsage:"Punkte in Polygone aggregieren, in denen sich die Punkte befinden.",
    calculateDensity:"Dichte berechnen",
    calculateDensityUsage:"Erstellt eine Dichtekarte aus Punkt- oder Linien-Features, indem bekannte Mengen einiger Phänomene (als Attribute der Punkte oder Linien dargestellt) auf der Karte verteilt werden.",
    connectOriginsToDestinations: "Startpunkte mit Zielen verbinden",
    connectOriginsToDestinationsUsage: "Die Fahrzeit oder Entfernung zwischen Punktepaaren messen.",
    createBuffers:"Puffer erstellen",
    createBuffersUsage:"Puffer-Polygone aus Eingabe-Features erstellen.",
    createDriveTimeAreas:"Fahrzeitgebiete erstellen",
    createDriveTimeAreasUsage:"Fahrzeitpolygone (oder Fahrentfernungspolygone) um Eingabepunkte für die angegebenen Fahrzeitwerte erstellen.",
    createViewshed:"Sichtfelder erstellen",
    createViewshedUsage:"Diese Funktion erstellt Flächen, die abhängig von angegebenen Positionen zu sehen sind.",
    createWatersheds:"Wassereinzugsgebiete erstellen",
    createWatershedsUsage:"Diese Funktion erstellt Einzugsgebiete basierend auf Positionen, die Sie angeben.",
    deriveNewLocations:"Neue Positionen ableiten",
    deriveNewLocationsUsage:"Neue Features aus den Eingabe-Layern ableiten, die einer festgelegten Abfrage entsprechen",
    dissolveBoundaries:"Grenzen zusammenführen",
    dissolveBoundariesUsage:"Polygone zusammenführen, die sich überlappen oder eine gemeinsame Grenze haben.",
    enrichLayer:"Layer anreichern",
    enrichLayerUsage:"Eingabe-Features mit Fakten zu Personen, Orten und Unternehmen in nahegelegenen Gebieten anreichern.",
    extractData:"Daten extrahieren",
    extractDataDesc:"Daten aus mindestens einem Layer in einer angegebenen Ausdehnung extrahieren",
    findExistingLocations:"Vorhandene Positionen suchen",
    findExistingLocationsUsage:"Die Features im Eingabe-Layer auswählen, die einer angegebenen Attribut- und/oder räumlichen Abfrage entsprechen",
    findHotSpots:"Hot-Spots suchen",
    findHotSpotsUsage:"Statistisch signifikante Cluster von Eingabe-Features oder hohe/niedrige Werte suchen.",
    findNearest:"Nächstgelegene suchen",
    findNearestUsage:"Für jedes Feature in einem Eingabe-Layer das nächstgelegene Feature in einem anderen Layer suchen",
    findSimilarLocations:"Ähnliche Positionen suchen",
    findSimilarLocationsUsage:"Die Ähnlichkeit von Kandidatenpositionen mit mindestens einer Bezugsposition messen.",
    interpolatePoints:"Punkte interpolieren",
    interpolatePointsUsage:"Werte an neuen Positionen basierend auf Messungen aus einer Sammlung von Punkten vorhersagen.",
    mergeLayers:"Layer zusammenführen",
    mergeLayersUsage:"Features aus mehreren Layern zu einem neuen Layer zusammenführen",
    overlayLayers:"Layer überlagern",
    overlayLayersUsage:"Mehrere Layer zu einem Layer kombinieren, wobei die Informationen aus den ursprünglichen Layern beibehalten werden.",
    planRoutes:"Routen planen",
    planRoutesUsage:"Bestimmen, wie Aufgaben effizient im mobilen Außendienstteam aufgeteilt werden.",
    summarizeNearby:"Zusammenfassen (in der Nähe)",
    summarizeNearbyUsage:"Für jedes Feature in einem Eingabe-Layer Daten in einer gewissen Entfernung von Features in einem anderen Layer zusammenfassen.",
    summarizeWithin:"Zusammenfassen (innerhalb)",
    summarizeWithinUsage:"Für jedes Polygon in einem Eingabe-Polygon-Layer die enthaltenen Daten von Features eines anderen Layers zusammenfassen.",
    traceDownstream:"Verfolgung flussabwärts",
    traceDownstreamUsage:"Diese Funktion ermittelt von den angegebenen Positionen aus die Fließrichtungen flussabwärts."
  })
);
