define(
   ({
    selectAnalysisTools:"Wählen Sie Analysewerkzeuge aus, die im Widget aufgeführt werden sollen.",
    selected: "ausgewählt",
    name: "Name",
    graphicalDisplay:"Grafische Anzeige",
    usage: "Nutzung",
    toolNotAvailable: "Dieses Werkzeug ist nicht verfügbar, da die Karte keine erforderlichen Feature-Layer enthält.",
    aggregatePoints:"Punkte aggregieren",
    aggregatePointsUsage:"Punkte in Polygone aggregieren, in denen sich die Punkte befinden.",
    aggregatePointsInputTip: "Geben Sie den Punkt-Feature-Layer an, der in den Polygonen im Polygon-Feature-Layer aggregiert wird.",
    calculateDensity:"Dichte berechnen",
    calculateDensityUsage:"Erstellt eine Dichtekarte aus Punkt- oder Linien-Features, indem bekannte Mengen einiger Phänomene (als Attribute der Punkte oder Linien dargestellt) auf der Karte verteilt werden.",
    calculateDensityInputTip:"Die Punkt- oder Linien-Features angeben, mit denen die Dichte berechnet werden soll.",
    connectOriginsToDestinations: "Startpunkte mit Zielen verbinden",
    connectOriginsToDestinationsUsage: "Die Fahrzeit oder Entfernung zwischen Punktepaaren messen.",
    connectOriginsToDestinationsInputTip: "Die Startpunkte der zu erstellenden Routen festlegen.",
    createBuffers:"Puffer erstellen",
    createBuffersUsage:"Puffer-Polygone aus Eingabe-Features erstellen.",
    createBuffersInputTip:"Die zu puffernden Punkt-, Linien- oder Polygon-Feature-Layer festlegen.",
    createDriveTimeAreas:"Fahrzeitgebiete erstellen",
    createDriveTimeAreasUsage:"Fahrzeitpolygone (oder Fahrentfernungspolygone) um Eingabepunkte für die angegebenen Fahrzeitwerte erstellen.",
    createDriveTimeAreasInputTip:"Die Punkte festlegen, an denen Fahrzeitgebiete dargestellt werden.",
    createViewshed:"Sichtfelder erstellen",
    createViewshedUsage:"Diese Funktion erstellt Flächen, die abhängig von angegebenen Positionen zu sehen sind.",
    createViewshedInputTip:"Die Beobachterpositionen festlegen, um sichtbare Bereiche zu identifizieren.",
    createWatersheds:"Wassereinzugsgebiete erstellen",
    createWatershedsUsage:"Diese Funktion erstellt Einzugsgebiete basierend auf Positionen, die Sie angeben.",
    createWatershedsInputTip:"Die zum Berechnen von Wassereinzugsgebieten verwendeten Punkt-Features festlegen.",
    deriveNewLocations:"Neue Positionen ableiten",
    deriveNewLocationsUsage:"Neue Features aus den Eingabe-Layern ableiten, die einer festgelegten Abfrage entsprechen",
    deriveNewLocationsInputTip:"Die als Eingabe zu verwendenden Analyse-Layer festlegen.",
    dissolveBoundaries:"Grenzen zusammenführen",
    dissolveBoundariesUsage:"Polygone zusammenführen, die sich überlappen oder eine gemeinsame Grenze haben.",
    dissolveBoundariesInputTip:"Den Layer festlegen, der Polygon-Features enthält, die zusammengeführt werden.",
    enrichLayer:"Layer anreichern",
    enrichLayerUsage:"Eingabe-Features mit Fakten zu Personen, Orten und Unternehmen in nahegelegenen Gebieten anreichern.",
    enrichLayerInputTip:"Die Features festlegen, die mit neuen Daten angereichert werden sollen.",
    extractData:"Daten extrahieren",
    extractDataDesc:"Daten aus mindestens einem Layer in einer angegebenen Ausdehnung extrahieren",
    extractDataInputTip:"Den zu extrahierenden Eingabe-Feature-Layer festlegen.",
    findExistingLocations:"Vorhandene Positionen suchen",
    findExistingLocationsUsage:"Die Features im Eingabe-Layer auswählen, die einer angegebenen Attribut- und/oder räumlichen Abfrage entsprechen",
    findExistingLocationsInputTip:"Den als Eingabe zu verwendenden Analyse-Layer festlegen.",
    findHotSpots:"Hot Spots suchen",
    findHotSpotsUsage:"Statistisch signifikante Cluster von Eingabe-Features oder hohe/niedrige Werte suchen.",
    findHotSpotsInputTip:"Den Punkt- oder Polygon-Feature-Layer festlegen, für den Hot Spots berechnet werden.",
    findNearest:"Nächstgelegene suchen",
    findNearestUsage:"Für jedes Feature in einem Eingabe-Layer das nächstgelegene Feature in einem anderen Layer suchen",
    findNearestInputTip:"Die Punkt-, Linien- oder Polygon-Features angeben, über die die nächstgelegenen Positionen gesucht werden.",
    findSimilarLocations:"Ähnliche Positionen suchen",
    findSimilarLocationsUsage:"Die Ähnlichkeit von Kandidatenpositionen mit mindestens einer Bezugsposition messen.",
    findSimilarLocationsInputTip:"Einen Feature-Layer angeben, der mindestens eine Bezugsposition enthält, anhand derer Features im Such-Layer nach Ähnlichkeit ausgewertet werden.",
    interpolatePoints:"Punkte interpolieren",
    interpolatePointsUsage:"Werte an neuen Positionen basierend auf Messungen aus einer Sammlung von Punkten vorhersagen.",
    interpolatePointsInputTip:"Die Punkt-Features festlegen, die interpoliert werden.",
    mergeLayers:"Layer zusammenführen",
    mergeLayersUsage:"Features aus mehreren Layern zu einem neuen Layer zusammenführen",
    mergeLayersInputTip:"Den Feature-Layer festlegen, der mit dem Merge-Layer (Layer zum Zusammenführen) zusammengeführt werden soll.",
    overlayLayers:"Layer überlagern",
    overlayLayersUsage:"Mehrere Layer zu einem Layer kombinieren, wobei die Informationen aus den ursprünglichen Layern beibehalten werden.",
    overlayLayersInputTip:"Den Feature-Layer festlegen, der durch den Overlay-Layer (Layer zum Überlagern) überlagert wird.",
    planRoutes:"Routen planen",
    planRoutesUsage:"Bestimmen, wie Aufgaben effizient im mobilen Außendienstteam aufgeteilt werden.",
    planRoutesInputTip:"Die Punkte festlegen, die von Fahrzeugen, Fahrern oder Routen aufgesucht werden sollen.",
    summarizeNearby:"Zusammenfassen (in der Nähe)",
    summarizeNearbyUsage:"Für jedes Feature in einem Eingabe-Layer Daten in einer gewissen Entfernung von Features in einem anderen Layer zusammenfassen.",
    summarizeNearbyInputTip:"Den Punkt-, Linien- oder Polygon-Feature-Layer auswählen, von dem aus Entfernungen zu Features in zusammengefassten Layern gemessen werden.",
    summarizeWithin:"Zusammenfassen (innerhalb)",
    summarizeWithinUsage:"Für jedes Polygon in einem Eingabe-Polygon-Layer die enthaltenen Daten von Features eines anderen Layers zusammenfassen.",
    summarizeWithinInputTip:"Den Polygon-Feature-Layer festlegen, für den Daten zusammengefasst werden sollen.",
    traceDownstream:"Verfolgung flussabwärts",
    traceDownstreamUsage:"Diese Funktion ermittelt von den angegebenen Positionen aus die Fließrichtungen flussabwärts.",
    traceDownstreamInputTip:"Die Punkt-Features festlegen, die für die Startposition einer Verfolgung flussabwärts verwendet werden sollen."
  })
);
