define(
   ({
    "tabs_section_Label": "タブ",
    "addTab": "タブの追加",
    "layerName": "レイヤー",
    "layerType": "分析タイプ",
    "layerLabel": "ラベル",
    "actions": "アクション",
    "closest": "最近隣フィーチャ",
    "proximity": "近接",
    "summary": "サマリー",
    "select_lbl": "-- 選択 --",
    "general_setting_Label": "一般設定",
    "units_text_lbl": "距離単位",
    "miles": "マイル",
    "kilometers": "キロメートル",
    "feet": "フィート",
    "meters": "メートル",
    "yards": "ヤード",
    "nauticalMiles": "海里",
    "maximum_distance_lbl": "最近隣フィーチャの最大距離",
    "buffer_text_lbl": "バッファー ラベル",
    "buffer_lbl": "バッファー距離",
    "buffer_max_lbl": "最大バッファー距離",
    "buffer_min_lbl": "最小バッファー距離",
    "routing_checkBox": "ルート検索の有効化",
    "weather_Label": "天気オプション",
    "weather_checkBox": "天気情報を含める",
    "selectLayers": "天気レイヤーの選択",
    "currentlySelectedLayer": "現在選択されている天気レイヤー",
    "missingTabLabel": "少なくとも 1 つのタブにラベルがありません",
    "cancel": "キャンセル",
    "ok": "OK",
    "missingLayerInWebMap": "操作レイヤーが見つかりません",
    "selectFields": "フィールド選択",
    "addField": "フィールドの追加",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "数の表示",
    "area_checkBox": "面積の表示",
    "length_checkBox": "長さの表示",
    "max_records": "最大制限に達しました"
  })
);
