define(
   ({
    taskUrl: "Opgave-URL",
    serviceURLPlaceholder: "Angiv geoprocesseringsopgavens URL",
    ok: "OK",
    cancel: "Annuller",
    layer: "Lag",
    action: "Handling",
    input: "Input",
    output: "Output",
    name: "Navn",
    type: "Type",
    required: "Krævet",
    layerOrder: "Lagrækkefølge",
    options: "Indstillinger",
    defaultValue: "Standardværdi",
    inputFeatureBy: "Angiv objekt efter",
    renderer: "Gengivelsesværktøj",
    displayType: "Vis type",
    label: "Mærke",
    tooltip: "Værktøjstip",
    visible: "Synlig",
    helpUrl: "Hjælp-URL",
    useResultMapService: "Brug resultatkorttjenestens tegnemuligheder",
    drawOnMap: "Interaktiv tegning på kortet",
    selectLayer: "Valg af lag fra kortet",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Tilføj resultat som operationelt lag",
    popup: "Pop-up",
    setTask: "Indstil",
    setTaskTitle: "Indstil GP-opgave",
    enablePopup: "Aktivér pop-up-vindue"
  })
);