define(
	 ({
		chartTasks: "Tarefas de Gráficos",
		addNew: "Adicionar Nova",
		addNewTip: "Adicionar uma Nova Tarefa de Gráfico",
		name: "Nome",
		set: "Definir",
		setDataSource: "Definir Fonte dos Dados",
		generalSettingsTip: "Definir a fonte dos dados, título e descrição para os gráficos.",
		chartModeSettingTip: "Selecione uma forma de analisar e exibir dados como gráficos.",
		detailsSettingTip: "Definir a aparência do gráfico especificando tipo e cor, e os valores a incluir no gráfico.",
		symbolSettingTip: "Definir a exibição do mapa para dados em gráfico.",
		addFilterTip: "Adicionar Filtro a estes dados",
		dataSource: "Fonte da Dados",
		noResults: "Nenhum resultado",
		chartTitle: "Título do Gráfico",
		description: "Descrição",
		chartingMode: "Exibição do Gráfico",
		featureOption: "Exibir elemento a elemento",
		categoryOption: "Exibir valores por categoria",
		countOption: "Exibir contagens de elementos por categoria",
		fieldOption: "Exibir valores de atributos como gráficos",
		category: "Categoria",
		axisLabel: "Rótulo de Categoria",
		categoryField: "Campo de Categoria",
		operation: "Operação",
		originalOption: "Utilizar valores originais",
		sumOption: "Soma",
		averageOption: "Média",
		minOption: "Mínimo",
		maxOption: "Máximo",
		valueFields: "Campos de Valores",
		moveUp: "Mover para cima",
		moveDown: "Mover para baixo",
		sortOrder: "Ordenar Gráficos através de Rótulos de Categorias",
		ascending: "Ascendente",
		descending: "Descendente",
		chartType: "Tipo de Gráfico",
		column: "Gráfico de Colunas",
		bar: "Gráfico de Barras",
		line: "Gráfico de Linhas",
		pie: "Gráfico Circular",
		chartColor: "Cor do Gráfico",
		showDataLabels: "Exibir Rótulos de Dados",
		setSymbol: "Símbolo de Seleção",
		setHighLightColor: "Realçar Cor",
		settings: "Definições",
		mapInterationOptions: "Opções de Interação do Mapa",
		preview: "Pré-Visualizar",
		ok: "OK",
		cancel: "Cancelar",
		close: "Fechar",
		setFilterTip: "Por favor, defina o filtro corretamente. ",
		setChartTitleTip: "Por favor, defina o título do gráfico.",
		setChartTypeTip: "Por favor, selecione pelo menos um tipo de gráfico.",
		setDataFieldTip: "por favor, selecione pelo menos um campo de valor.",
		setOutputFieldTip: "por favor, defina campos de saída.",
		count: "Contagem",
		label: "Rótulo",
		horizontalAxis: "Eixo Horizontal",
		verticalAxis: "Eixo Vertical",
		dataLabels: "Rótulos de Dados",
		color: "Cor",
		colorful: "Colorido",
		monochromatic: "Monocromático",
    noTaskTip: "Clique em Adicionar Novo para adicionar uma tarefa de gráfico",
    info: "Informação",
    charts: "Gráficos",
    options: "Opções",
    taskName: "Nome da Tarefa",
    summary: "Resumo",
    resultDescription: "Descrição de Resultado",
    spatialFilterTip: "Escolha o(s) filtro(s) espacial(ais) utilizados no widget para limitar os resultados.",
    defaultOption: "Padrão",
    useCurrentExtentTip: "Parcialmente ou totalmente no contido na atual extensão de mapa",
    useDrawGraphicTip: "Parcialmente ou totalmente no contido na forma desenhada no mapa",
    useFeaturesTip: "Baseado nas respetivas localizações em relação a elementos noutra camada",
    noSpatialLimitTip: "Não limita resultados espacialmente",
    drawingTools: "Ferramentas de desenho",
    bufferSettings: "Definições de Buffer",
    defaultDistance: "Distância Padrão",
    bufferDistance: "Distância do Buffer",
    defaultUnit: "Unidade Padrão",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    availableSpatialRelationships: "Relações Espaciais Disponíveis",
    setSpatialRelationships: "Definir Relações Espaciais",
    availability: "Disponibilidade",
    relationship: "Relacionamento",
    actions: "Acções",
    intersect: "intersetar",
    contain: "conter",
    areContainedIn: "estão contidos em",
    cross: "cruz",
    envelopeIntersect: "interseção envelope",
    overlap: "sobrepor",
    areOverlapped: "estão sobrepostos",
    touche: "touche",
    within: "contidos",
    areWithin: "estão contidos",
    indexIntersect: "interseção índice"
  })
);