define(
	 ({
		charts: "Tarefas de Gráficos",
		addNew: "Adicionar Nova",
		addNewTip: "Adicionar uma Nova Tarefa de Gráfico",
		name: "Nome",
		set: "Definir",
		setDataSource: "Definir Fonte dos Dados",
		generalSettingsTip: "Definir a fonte dos dados, título e descrição para os gráficos.",
		chartModeSettingTip: "Selecione uma forma de analisar e exibir dados como gráficos.",
		detailsSettingTip: "Definir a aparência do gráfico especificando os seus tipos e cor e os valores que devem ser inseridos no gráfico.",
		symbolSettingTip: "Definir a exibição do mapa para dados em gráfico.",
		addFilterTip: "Adicionar Filtro a estes dados",
		dataSource: "Fonte da Dados",
		noResults: "Nenhum resultado",
		chartTitle: "Título do Gráfico",
		description: "Descrição",
		chartingMode: "Exibição do Gráfico",
		featureOption: "Exibir elemento a elemento",
		categoryOption: "Exibir valores por categoria",
		countOption: "Exibir contagens de elementos por categoria",
		fieldOption: "Exibir valores de atributos como gráficos",
		category: "Categoria",
		axisLabel: "Rótulo de Categoria",
		categoryField: "Campo de Categoria",
		operation: "Operação",
		originalOption: "Utilizar valores originais",
		sumOption: "Soma",
		averageOption: "Média",
		minOption: "Mínimo",
		maxOption: "Máximo",
		valueFields: "Campos de Valores",
		moveUp: "Mover para cima",
		moveDown: "Mover para baixo",
		sortOrder: "Ordenar Gráficos através de Rótulos de Categorias",
		ascending: "Ascendente",
		descending: "Descendente",
		chartType: "Tipo de Gráfico",
		column: "Gráfico de Colunas",
		bar: "Gráfico de Barras",
		line: "Gráfico de Linhas",
		pie: "Gráfico Circular",
		chartColor: "Cor do Gráfico",
		showDataLabels: "Exibir Rótulos de Dados",
		setSymbol: "Símbolo de Seleção",
		setHighLightColor: "Realçar Cor",
		settings: "Definições",
		mapInterationOptions: "Opções de Interação do Mapa",
		preview: "Pré-Visualizar",
		ok: "OK",
		cancel: "Cancelar",
		close: "Fechar",
		setFilterTip: "Por favor, defina o filtro corretamente. ",
		setChartTitleTip: "Por favor, defina o título do gráfico.",
		setChartTypeTip: "Por favor, selecione pelo menos um tipo de gráfico.",
		setDataFieldTip: "por favor, selecione pelo menos um campo de valor.",
		setOutputFieldTip: "por favor, defina campos de saída.",
		count: "Contagem",
		label: "Rótulo",
		horizontalAxis: "Eixo Horizontal",
		verticalAxis: "Eixo Vertical",
		dataLabels: "Rótulos de Dados",
		color: "Cor",
		colorful: "Colorido",
		monochromatic: "Monocromático"
  })
);