define(
   ({
    selectAnalysisTools:"Selecteer analysetools om te vermelden in de widget.",
    selected: "geselecteerd",
    name: "Naam",
    graphicalDisplay:"Grafische weergave",
    usage: "Gebruik",
    toolNotAvailable: "Deze tool is niet beschikbaar omdat de kaart geen vereiste objectla(a)g(en) bevat.",
    aggregatePoints:"Punten aggregeren",
    aggregatePointsUsage:"Punten aggregeren in polygonen waar de punten zich bevinden.",
    aggregatePointsInputTip: "Geef de puntobjectlaag op die worden geaggregeerd in de polygonen in de polygoonobjectlaag.",
    calculateDensity:"Dichtheid berekenen",
    calculateDensityUsage:"Maakt een dichtheidskaart vanaf punt- of lijnobjecten door bekende hoeveelheden van een bepaald fenomeen (voorgesteld als attributen van de punten of lijnen) over de kaart te verspreiden.",
    calculateDensityInputTip:"Geef de punt- of lijnobjecten op waarmee de dichtheid moet worden berekend.",
    connectOriginsToDestinations: "Vertrekpunten en bestemmingen met elkaar verbinden",
    connectOriginsToDestinationsUsage: "Meet de reistijd of afstand tussen paren van beginpunten.",
    connectOriginsToDestinationsInputTip: "Geef het startpunten of -punten op van de routes die moeten worden gegenereerd.",
    createBuffers:"Buffers maken",
    createBuffersUsage:"Bufferpolygonen maken van invoerobjecten.",
    createBuffersInputTip:"Geef het punt, de lijn of polygoonobjectlaag op die moet worden gebufferd.",
    createDriveTimeAreas:"Gebieden op basis van reisduur maken",
    createDriveTimeAreasUsage:"Maak polygonen voor reistijd (of rij-afstand) rond invoerpunten voor de gegeven reistijdwaarden.",
    createDriveTimeAreasInputTip:"Geef de punten op waar reistijdgebieden worden getekend.",
    createViewshed:"Viewshed maken",
    createViewshedUsage:"Maakt gebieden die zichtbaar zijn op basis van locaties die u opgeeft.",
    createViewshedInputTip:"Geef de waarnemerlocaties op om zichtbare gebieden te identificeren.",
    createWatersheds:"Stroomgebied maken",
    createWatershedsUsage:"Maakt stroomgebieden op basis van locaties die u opgeeft.",
    createWatershedsInputTip:"Geef de puntobjecten op gebruikt voor de berekening van stroomgebieden.",
    deriveNewLocations:"Nieuwe locaties afleiden",
    deriveNewLocationsUsage:"Leid nieuwe objecten af van de invoerlagen die voldoen aan een query die u opgeeft",
    deriveNewLocationsInputTip:"Geef de analyselaag op die moet worden gebruikt als input.",
    dissolveBoundaries:"Grenzen oplossen",
    dissolveBoundariesUsage:"Los polygonen op die een gemeenschappelijke grens overlappen of delen.",
    dissolveBoundariesInputTip:"Geef de laag op met polygoonobjecten die worden opgelost.",
    enrichLayer:"Laag verrijken",
    enrichLayerUsage:"Verrijk invoerobjecten met informatie over mensen, plaatsen en bedrijven in nabijgelegen gebieden.",
    enrichLayerInputTip:"Geef de objecten op om met nieuwe data te verrijken.",
    extractData:"Gegevens exporteren",
    extractDataDesc:"Exporteer gegevens van een of meerdere lagen binnen een bepaalde extent",
    extractDataInputTip:"Geef de invoerobjectlaag op om te exporteren.",
    findExistingLocations:"Bestaande locaties zoeken",
    findExistingLocationsUsage:"Selecteer objecten in de invoerlaag die voldoen aan een attribuut en/of ruimtelijke query u opgeeft",
    findExistingLocationsInputTip:"Geef de analyselaag op die moet worden gebruikt als input.",
    findHotSpots:"Hotspots zoeken",
    findHotSpotsUsage:"Zoek statistisch signficante clusters van invoerobjecten of hoge/lage waarden.",
    findHotSpotsInputTip:"Geef de punt- of polygoonobjectlaag op waarvoor de hotspots worden berekend.",
    findNearest:"Dichtstbijzijnde zoeken",
    findNearestUsage:"Zoek voor elk object op een invoerlaag het dichtstbijzijnde object op een andere laag",
    findNearestInputTip:"Geef de punt-, lijn- of polygoonobjecten op van waaruit de dichtstbijzijnde locaties zijn gevonden.",
    findSimilarLocations:"Gelijksoortige locaties zoeken",
    findSimilarLocationsUsage:"Meet de gelijkenis van kandidaat-locaties aan de hand van één of meerdere referentiepunten.",
    findSimilarLocationsInputTip:"Geef een objectlaag op die één of meerdere referentiepunten bevat waarmee de objecten in de zoeklaag worden geëvalueerd met het oog op vergelijkbaarheid.",
    interpolatePoints:"Punten interpoleren",
    interpolatePointsUsage:"Voorspel waarden op nieuwe locaties op basis van metingen die worden gevonden in een verzameling van punten.",
    interpolatePointsInputTip:"Geef de puntobjecten op die worden geïnterpoleerd.",
    mergeLayers:"Lagen samenvoegen",
    mergeLayersUsage:"Voeg objecten toe van meerdere lagen aan een nieuwe laag",
    mergeLayersInputTip:"Geef de objectlaag op die u wilt samenvoegen met de laag.",
    overlayLayers:"Lagen bovenop plaatsen",
    overlayLayersUsage:"Combineer meerdere lagen in één enkele laag met informatie uit de originele bewaarde kaartlagen.",
    overlayLayersInputTip:"Geef de objectlaag op die u op de laag wilt plaatsen.",
    planRoutes:"Routes plannen",
    planRoutesUsage:"Bepaal hoe taken efficiënt kunnen worden verdeeld over mobiel personeel.",
    planRoutesInputTip:"Geef de punten op die de voertuigen, chauffeurs of routes moeten bezoeken.",
    summarizeNearby:"Samenvatten in de buurt van",
    summarizeNearbyUsage:"Zoek voor elk object een invoerlaag op het dichtstbijzijnde object op een andere laag.",
    summarizeNearbyInputTip:"Geef de punt-, lijn- of polygoonobjectlaag op van waaruit de afstanden worden gemeten tot objecten in laag samenvatten.",
    summarizeWithin:"Samenvatten in",
    summarizeWithinUsage:"Vat voor elke polygoon op een invoerpolygoonlaag data samen met objecten uit een andere laag.",
    summarizeWithinInputTip:"Geef de polygoonobjectlaag op om samen te vatten.",
    traceDownstream:"Stroomafwaarts traceren",
    traceDownstreamUsage:"Bepaal de stromingstrajecten stroomafwaarts van de locaties die u opgeeft.",
    traceDownstreamInputTip:"Geef de puntobjecten op gebruikt voor de startlocatie van stroomafwaarts traceren."
  })
);
