define(
   ({
    selectAnalysisTools:"Selecteer analysetools om te gebruiken in de widget.",
    selected: "geselecteerd",
    name: "Naam",
    graphicalDisplay:"Grafische weergave",
    usage: "Gebruik",
    settings: "Instellingen",
    toolSetting: "Tooldetails instellen",
    toolLabel: "De weergegeven naam van de tool",
    showHelpTip: "Helplinks weergeven in de widget",
    showCurrentMapExtent: "Optie weergeven om de huidige kaart te gebruiken",
    showCredits: "Optie <b>Credits weergeven</b> tonen",
    saveAsFeatureService: "Sla het resultaat op in de account van de gebruiker",
    showReadyToUseLayers: "Gereed weergeven om lagen te gebruiken van ArcGIS Online levende atlas van de wereld",
    toolNotAvailable: "Deze tool is niet beschikbaar omdat de kaart geen vereiste objectla(a)g(en) bevat.",
    aggregatePoints:"Punten aggregeren",
    aggregatePointsUsage:"Punten aggregeren in polygonen waar de punten zich bevinden.",
    calculateDensity:"Dichtheid berekenen",
    calculateDensityUsage:"Maakt een dichtheidskaart vanaf punt- of lijnobjecten door bekende hoeveelheden van een bepaald fenomeen (voorgesteld als attributen van de punten of lijnen) over de kaart te verspreiden.",
    connectOriginsToDestinations: "Vertrekpunten en bestemmingen met elkaar verbinden",
    connectOriginsToDestinationsUsage: "Meet de reistijd of afstand tussen paren van beginpunten.",
    createBuffers:"Buffers maken",
    createBuffersUsage:"Bufferpolygonen maken van invoerobjecten.",
    createDriveTimeAreas:"Gebieden op basis van reisduur maken",
    createDriveTimeAreasUsage:"Maak polygonen voor reistijd (of rij-afstand) rond invoerpunten voor de gegeven reistijdwaarden.",
    createViewshed:"Viewshed maken",
    createViewshedUsage:"Maakt gebieden die zichtbaar zijn op basis van locaties die u opgeeft.",
    createWatersheds:"Stroomgebied maken",
    createWatershedsUsage:"Maakt stroomgebieden op basis van locaties die u opgeeft.",
    deriveNewLocations:"Nieuwe locaties afleiden",
    deriveNewLocationsUsage:"Leid nieuwe objecten af van de invoerlagen die voldoen aan een query die u opgeeft",
    dissolveBoundaries:"Grenzen oplossen",
    dissolveBoundariesUsage:"Los polygonen op die een gemeenschappelijke grens overlappen of delen.",
    enrichLayer:"Laag verrijken",
    enrichLayerUsage:"Verrijk invoerobjecten met informatie over mensen, plaatsen en bedrijven in nabijgelegen gebieden.",
    extractData:"Gegevens exporteren",
    extractDataDesc:"Exporteer gegevens van een of meerdere lagen binnen een bepaalde extent",
    findExistingLocations:"Bestaande locaties zoeken",
    findExistingLocationsUsage:"Selecteer objecten in de invoerlaag die voldoen aan een attribuut en/of ruimtelijke query u opgeeft",
    findHotSpots:"Hotspots zoeken",
    findHotSpotsUsage:"Zoek statistisch signficante clusters van invoerobjecten of hoge/lage waarden.",
    findNearest:"Dichtstbijzijnde zoeken",
    findNearestUsage:"Zoek voor elk object op een invoerlaag het dichtstbijzijnde object op een andere laag",
    findSimilarLocations:"Gelijksoortige locaties zoeken",
    findSimilarLocationsUsage:"Meet de gelijkenis van kandidaat-locaties aan de hand van één of meerdere referentiepunten.",
    interpolatePoints:"Punten interpoleren",
    interpolatePointsUsage:"Voorspel waarden op nieuwe locaties op basis van metingen die worden gevonden in een verzameling van punten.",
    mergeLayers:"Lagen samenvoegen",
    mergeLayersUsage:"Voeg objecten toe van meerdere lagen aan een nieuwe laag",
    overlayLayers:"Lagen bovenop plaatsen",
    overlayLayersUsage:"Combineer meerdere lagen in één enkele laag met informatie uit de originele bewaarde kaartlagen.",
    planRoutes:"Routes plannen",
    planRoutesUsage:"Bepaal hoe taken efficiënt kunnen worden verdeeld over mobiel personeel.",
    summarizeNearby:"Samenvatten in de buurt van",
    summarizeNearbyUsage:"Zoek voor elk object een invoerlaag op het dichtstbijzijnde object op een andere laag.",
    summarizeWithin:"Samenvatten in",
    summarizeWithinUsage:"Vat voor elke polygoon op een invoerpolygoonlaag data samen met objecten uit een andere laag.",
    traceDownstream:"Stroomafwaarts traceren",
    traceDownstreamUsage:"Bepaal de stromingstrajecten stroomafwaarts van de locaties die u opgeeft."
  })
);
