define(
   ({
    _widgetLabel: "In",
    title: "Tên Bản đồ",
    format: "Định dạng",
    layout: "Bố cục",
    settings: "Nâng cao",
    mapScaleExtent: "Phạm vi/tỷ lệ bản đồ",
    preserve: "Bảo tồn",
    mapScale: "tỷ lệ bản đồ",
    mapExtent: "phạm vi bản đồ",
    forceScale: "Tỷ lệ bắt buộc",
    getCurrentScale: "hiện tại",
    mapMetadata: "Siêu dữ liệu bố cục",
    author: "Tác giả",
    copyright: "Bản quyền",
    fullLayoutOptions: "Tùy chọn bố cục đầy đủ",
    scaleBarUnitsMetric: "Đơn vị của thanh tỷ lệ theo hệ mét",
    scaleBarUnitsNonMetric: "Đơn vị của thanh tỷ lệ không theo hệ mét",
    unitsMiles: "Dặm",
    unitsKilometers: "Kilômét",
    unitsMeters: "Mét",
    unitsFeet: "Feet",
    unitsYards: "Thước",
    unitsNauticalMiles: "Hải lý",
    lncludeLegend: "Bao gồm chú giải",
    printQualityOptions: "Chất lượng in",
    dpi: "DPI",
    mapOnlyOptions: "Kích thước MAP_ONLY",
    width: "Chiều rộng (px)",
    height: "Chiều cao (px)",
    print: "In",
    clearList: "Xóa Bản in",
    creatingPrint: "Tạo Bản in",
    printError: "Lỗi, thử lại"
  })
);