define(
   ({
    selectAnalysisTools:"위젯에 나열할 분석 도구를 선택합니다.",
    selected: "선택함",
    name: "이름",
    graphicalDisplay:"그래픽 표시",
    usage: "사용량",
    toolNotAvailable: "맵에 필요한 피처 레이어가 포함되어 있지 않으므로 이 도구를 사용할 수 없습니다.",
    aggregatePoints:"포인트 집약",
    aggregatePointsUsage:"포인트들이 있는 위치에서 포인트들을 폴리곤으로 집약합니다.",
    aggregatePointsInputTip: "폴리곤 피처 레이어에서 폴리곤으로 집약될 포인트 피처 레이어를 지정합니다.",
    calculateDensity:"밀도 계산",
    calculateDensityUsage:"포인트 또는 라인 피처를 가지고 맵 전반에 알려져 있는 일부 현상(포인트 또는 라인 속성으로 표시됨)을 분산하여 밀도 맵을 생성합니다.",
    calculateDensityInputTip:"밀도를 계산할 포인트 또는 라인 피처를 지정합니다.",
    connectOriginsToDestinations: "출발지를 목적지에 연결",
    connectOriginsToDestinationsUsage: "포인트 쌍 간의 이동 시간 또는 거리를 측정합니다.",
    connectOriginsToDestinationsInputTip: "생성할 경로의 시작점을 지정합니다.",
    createBuffers:"버퍼 생성",
    createBuffersUsage:"입력 피처에서 버퍼 폴리곤을 생성합니다.",
    createBuffersInputTip:"버퍼링할 포인트, 라인 또는 폴리곤 피처를 지정합니다.",
    createDriveTimeAreas:"운전 시간 영역 생성",
    createDriveTimeAreasUsage:"제공된 운전-시간 값에 대해 입력 포인트 주위에 운전-시간(또는 운전-거리)을 생성합니다.",
    createDriveTimeAreasInputTip:"운전-시간 영역을 그릴 포인트를 지정합니다.",
    createViewshed:"가시권역 생성",
    createViewshedUsage:"지정한 위치를 기반으로 가시 영역을 생성합니다.",
    createViewshedInputTip:"가시 영역을 식별하기 위한 관찰자 위치를 지정합니다.",
    createWatersheds:"유역 생성",
    createWatershedsUsage:"지정한 위치를 기반으로 집수 영역을 생성합니다.",
    createWatershedsInputTip:"유역 계산에 사용될 포인트 피처를 지정합니다.",
    deriveNewLocations:"새 위치 파생",
    deriveNewLocationsUsage:"지정한 쿼리를 충족하는 입력 레이어에서 새 피처 파생",
    deriveNewLocationsInputTip:"입력으로 사용할 분석 레이어를 지정합니다.",
    dissolveBoundaries:"경계 디졸브",
    dissolveBoundariesUsage:"공통 경계가 겹치거나 공통 경계를 공유하는 폴리곤을 디졸브합니다.",
    dissolveBoundariesInputTip:"디졸브할 폴리곤 피처를 포함하는 레이어를 지정합니다.",
    enrichLayer:"레이어 보강",
    enrichLayerUsage:"주변 영역의 사람, 장소 및 회사에 대한 사실로 입력 피처를 보강합니다.",
    enrichLayerInputTip:"새 데이터로 보강하기 위한 피처를 지정합니다.",
    extractData:"데이터 추출",
    extractDataDesc:"주어진 범위 내에서 하나 이상의 레이어로부터 데이터 추출",
    extractDataInputTip:"추출할 입력 피처 레이어를 지정합니다.",
    findExistingLocations:"기존 위치 찾기",
    findExistingLocationsUsage:"입력 레이어에서 지정한 속성 및/또는 공간 쿼리를 충족하는 피처를 선택합니다.",
    findExistingLocationsInputTip:"입력으로 사용할 분석 레이어를 지정합니다.",
    findHotSpots:"핫스팟 찾기",
    findHotSpotsUsage:"입력 피처 또는 높은/낮은 값의 통계적으로 유의미한 군집점을 찾습니다.",
    findHotSpotsInputTip:"핫스팟을 계산할 포인트 또는 폴리곤 피처 레이어를 지정합니다.",
    findNearest:"가장 가까운 위치 찾기",
    findNearestUsage:"입력 레이어에서 각 피처의 경우 다른 레이어에서 가장 가까운 피처를 찾습니다.",
    findNearestInputTip:"가장 가까운 위치에서 포인트, 라인 또는 폴리곤 피처를 지정합니다.",
    findSimilarLocations:"유사한 위치 찾기",
    findSimilarLocationsUsage:"하나 이상의 참조 위치에 대한 후보 위치의 근사(Similarity)를 측정합니다.",
    findSimilarLocationsInputTip:"검색 레이어의 피처가 근사(Similarity)에 대해 평가되는 것과 달리 하나 이상의 참조 위치를 포함하는 피처 레이어를 지정합니다.",
    interpolatePoints:"포인트 내삽",
    interpolatePointsUsage:"포인트 컬렉션에서 측정을 기반으로 새 위치에서 값을 예측합니다.",
    interpolatePointsInputTip:"내삽할 포인트 피처를 지정합니다.",
    mergeLayers:"레이어 병합",
    mergeLayersUsage:"여러 레이어에서 새 레이어로 피처 병합",
    mergeLayersInputTip:"레이어 병합으로 병합할 피처 레이어를 지정합니다.",
    overlayLayers:"레이어 중첩",
    overlayLayersUsage:"유지된 원래 레이어의 정보가 있는 하나의 단일 레이어로 여러 레이어를 결합합니다.",
    overlayLayersInputTip:"레이어 중첩으로 중첩될 피처 레이어를 지정합니다.",
    planRoutes:"경로 계획",
    planRoutesUsage:"이동 인력 간에 효율적으로 작업을 나누는 방법을 결정합니다.",
    planRoutesInputTip:"차량, 운전자 또는 경로가 방문해야 하는 포인트를 지정합니다.",
    summarizeNearby:"다음 주변 요약",
    summarizeNearbyUsage:"입력 레이어에서 각 피처의 경우 다른 레이어의 피처에서 거리 내 데이터를 요약합니다.",
    summarizeNearbyInputTip:"레이어 요약에서 거리가 피처로 측정될 포인트, 라인 또는 폴리곤 피처를 지정합니다.",
    summarizeWithin:"다음 범위 내 요약",
    summarizeWithinUsage:"입력 폴리곤 레이어에서 각 폴리곤의 경우 다른 레이어의 피처에서 위치한 데이터를 요약합니다.",
    summarizeWithinInputTip:"요약될 폴리곤 피처 레이어를 지정합니다.",
    traceDownstream:"하류 추적",
    traceDownstreamUsage:"지정한 위치에서 하류 방향으로 흐름 경로를 결정합니다.",
    traceDownstreamInputTip:"하류 추적의 시작 위치에 사용될 포인트 피처를 지정합니다."
  })
);
