define(
   ({
    selectAnalysisTools:"위젯에서 사용할 분석 도구를 선택합니다.",
    selected: "선택함",
    name: "이름",
    graphicalDisplay:"그래픽 표시",
    usage: "사용량",
    settings: "설정",
    toolSetting: "도구 세부정보 설정",
    toolLabel: "도구 디스플레이 이름",
    showHelpTip: "위젯에서 도움말 링크 보기",
    showCurrentMapExtent: "현재 맵 범위 사용 옵션 나타내기",
    showCredits: "<b>크레딧 보기</b> 옵션 디스플레이",
    saveAsFeatureService: "사용자 계정에 결과 저장",
    showReadyToUseLayers: "ArcGIS Online의 생동감 있는 세계 지도에서 즉시 사용 가능한 레이어 보기",
    toolNotAvailable: "맵에 필요한 피처 레이어가 포함되어 있지 않으므로 이 도구를 사용할 수 없습니다.",
    aggregatePoints:"포인트 집약",
    aggregatePointsUsage:"포인트들이 있는 위치에서 포인트들을 폴리곤으로 집약합니다.",
    calculateDensity:"밀도 계산",
    calculateDensityUsage:"포인트 또는 라인 피처를 가지고 맵 전반에 알려져 있는 일부 현상(포인트 또는 라인 속성으로 표시됨)을 분산하여 밀도 맵을 생성합니다.",
    connectOriginsToDestinations: "출발지를 목적지에 연결",
    connectOriginsToDestinationsUsage: "포인트 쌍 간의 이동 시간 또는 거리를 측정합니다.",
    createBuffers:"버퍼 생성",
    createBuffersUsage:"입력 피처에서 버퍼 폴리곤을 생성합니다.",
    createDriveTimeAreas:"운전 시간 영역 생성",
    createDriveTimeAreasUsage:"제공된 운전-시간 값에 대해 입력 포인트 주위에 운전-시간(또는 운전-거리)을 생성합니다.",
    createViewshed:"가시권역 생성",
    createViewshedUsage:"지정한 위치를 기반으로 가시 영역을 생성합니다.",
    createWatersheds:"유역 생성",
    createWatershedsUsage:"지정한 위치를 기반으로 집수 영역을 생성합니다.",
    deriveNewLocations:"새 위치 파생",
    deriveNewLocationsUsage:"지정한 쿼리를 충족하는 입력 레이어에서 새 피처 파생",
    dissolveBoundaries:"경계 디졸브",
    dissolveBoundariesUsage:"공통 경계가 겹치거나 공통 경계를 공유하는 폴리곤을 디졸브합니다.",
    enrichLayer:"레이어 보강",
    enrichLayerUsage:"주변 영역의 사람, 장소 및 회사에 대한 사실로 입력 피처를 보강합니다.",
    extractData:"데이터 추출",
    extractDataDesc:"주어진 범위 내에서 하나 이상의 레이어로부터 데이터 추출",
    findExistingLocations:"기존 위치 찾기",
    findExistingLocationsUsage:"입력 레이어에서 지정한 속성 및/또는 공간 쿼리를 충족하는 피처를 선택합니다.",
    findHotSpots:"핫스팟 찾기",
    findHotSpotsUsage:"입력 피처 또는 높은/낮은 값의 통계적으로 유의미한 군집점을 찾습니다.",
    findNearest:"가장 가까운 위치 찾기",
    findNearestUsage:"입력 레이어에서 각 피처의 경우 다른 레이어에서 가장 가까운 피처를 찾습니다.",
    findSimilarLocations:"유사한 위치 찾기",
    findSimilarLocationsUsage:"하나 이상의 참조 위치에 대한 후보 위치의 근사(Similarity)를 측정합니다.",
    interpolatePoints:"포인트 내삽",
    interpolatePointsUsage:"포인트 컬렉션에서 측정을 기반으로 새 위치에서 값을 예측합니다.",
    mergeLayers:"레이어 병합",
    mergeLayersUsage:"여러 레이어에서 새 레이어로 피처 병합",
    overlayLayers:"레이어 중첩",
    overlayLayersUsage:"유지된 원래 레이어의 정보가 있는 하나의 단일 레이어로 여러 레이어를 결합합니다.",
    planRoutes:"경로 계획",
    planRoutesUsage:"이동 인력 간에 효율적으로 작업을 나누는 방법을 결정합니다.",
    summarizeNearby:"다음 주변 요약",
    summarizeNearbyUsage:"입력 레이어에서 각 피처의 경우 다른 레이어의 피처에서 거리 내 데이터를 요약합니다.",
    summarizeWithin:"다음 범위 내 요약",
    summarizeWithinUsage:"입력 폴리곤 레이어에서 각 폴리곤의 경우 다른 레이어의 피처에서 위치한 데이터를 요약합니다.",
    traceDownstream:"하류 추적",
    traceDownstreamUsage:"지정한 위치에서 하류 방향으로 흐름 경로를 결정합니다."
  })
);
