define(
   ({
    taskUrl: "URL úlohy",
    serviceURLPlaceholder: "Zadejte URL úlohy geoprocessingu.",
    ok: "OK",
    cancel: "Storno",
    layer: "Vrstva",
    action: "Akce",
    input: "Vstup",
    output: "Výstup",
    name: "Název",
    type: "Typ",
    required: "Požadováno",
    layerOrder: "Pořadí vrstev",
    options: "Možnosti",
    defaultValue: "Výchozí hodnota",
    inputFeatureBy: "Vstupní prvek od",
    renderer: "Vykreslovač",
    displayType: "Typ zobrazení",
    label: "Štítek",
    tooltip: "Plovoucí popisek",
    visible: "Viditelná",
    helpUrl: "URL nápovědy",
    useResultMapService: "Použít možnosti kreslení výsledné mapové služby",
    drawOnMap: "Interaktivní kreslení na mapu",
    selectLayer: "Výběr vrstvy z mapy",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Přidat výsledek jako operační vrstvu",
    popup: "Vyskakovací okno",
    setTask: "Nastavit",
    setTaskTitle: "Nastavit GP úlohu",
    enablePopup: "Povolit vyskakovací okna",
    unSupportGeometryType: "Vykreslovač nelze nastavit, protože je typ geometrie neznámý.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Nahrát soubor",
    selectFileToUpload: "Vybrat soubor…",
    upload: "Nahrát",
    rasterFormat: "Formát rastrových dat",
    noFileSelected: "Nebyl vybrán žádný soubor.",
    uploadSuccess:"Soubor byl úspěšně nahrán.",
    showLayerContent: "Zobrazit obsah vrstvy",
    Feet: "Stopy",
    Yards: "Yardy",
    Miles: "Míle",
    NauticalMiles: "Námořní míle",
    Meter: "Metry",
    Kilometers: "Kilometry",
    urlPlaceholder: "adresa URL sady prvků",
    allowToExport: "Povolit export výsledků"
  })
);
