define(
   ({
    _widgetLabel: "Rapportera geoobjekt",
    select: "Välj",
    draw: "Rita",
    chooseALayer: "Välj ett lager",
    clickAFeature: "Klicka på ett geoobjekt på kartan för att markera det.",
    loadingFeatures: "Hämtar markerade geoobjektsdetaljer...",
    errorTitle: "Fel",
    errorIdentify: "Identifiera geoobjektsfel. Kontrollera konsolloggen för närmare information.",
    infoWindowTitle: "Detaljer",
    layerLabel: "Lagernamn",
    reviewStatusLabel: "Granskningsstatus",
    selectReviewStatusAdd: "Lägg till geoobjekt",
    selectReviewStatusDelete: "Ta bort geoobjekt",
    selectReviewStatusMove: "Flytta geoobjekt",
    selectReviewStatusReshape: "Omforma geoobjekt",
    drawReviewStatusMissing: "Saknade geoobjekt",
    drawReviewStatusPosition: "Positionsfel",
    drawReviewStatusShape: "Omformningsfel",
    drawReviewStatusAttribute: "Attributfel",
    notesLabel: "Anmärkningar",
    severityLabel: "Allvarlighetsgrad",
    reportedByLabel: "Rapporterad av",
    reportedByDefault: "anonymt",
    reportButton: "Rapport",
    reportMessage: "Rapporten mottagen",
    errorReportMessage: "Ett fel uppstod när geoobjektet rapporterades",
    drawErrorInstructions: "Markera en punkt, linje eller polygon och rita felgeometrin på kartan:",
    errorMapService: "Ett fel uppstod när informationen hämtades från karttjänsten",
    noFeatureSelected : "Inga geoobjekt hittades där du klickade",
    selectFeatureMapPoint: "Markera ett geoobjekt genom att klicka på det",
    drawFeatureMapPoint: "Klicka om du vill lägga till en punkt",
    popupMessage:"Meddelande",
    popupError:"Fel",
    manyFeaturesSelected: "Fler än ett geoobjekt hittades. Zooma in och markera ett geoobjekt som ska rapporteras."
  })
);
