define(
	 ({
		charts: "Tarefas do Gráfico",
		addNew: "Adicionar Novo",
		addNewTip: "Adicionar uma Nova Tarefa do Gráfico",
		name: "Nome",
		set: "Configurar",
		setDataSource: "Configurar Fonte de Dados",
		generalSettingsTip: "Configura a fonte de dados, título e descrição para gráficos.",
		chartModeSettingTip: "Seleciona uma maneira para analisar e exibir dados como gráficos.",
		detailsSettingTip: "Configura a aparência do gráfico especificando seus tipos e cores, e quais valores a serem mapeados.",
		symbolSettingTip: "Configura a exibição do mapa para dados do gráfico.",
		addFilterTip: "Adicionar Fintro Nestes Dados",
		dataSource: "Fonte de Dados",
		noResults: "Nenhuma feição encontrada.",
		chartTitle: "Títilo do Gráfico",
		description: "Descrição",
		chartingMode: "Exibição do Gráfico",
		featureOption: "Exibir valores feição por feição",
		categoryOption: "Exibir valores por categoria",
		countOption: "Exibir contagem de feição por categoria",
		fieldOption: "Exibir valores de atributo como gráficos",
		category: "Categoria",
		axisLabel: "Rótulo de Categoria",
		categoryField: "Campo de Categoria",
		operation: "Operação",
		originalOption: "Utilizar valores originais",
		sumOption: "Soma",
		averageOption: "Média",
		minOption: "Mínimo",
		maxOption: "Máximo",
		valueFields: "Campos de Valor",
		moveUp: "Mover para cima",
		moveDown: "Mover para baixo",
		sortOrder: "Classificar Ordem dos Gráficos via Rótulos de Categoria",
		ascending: "Crescente",
		descending: "Descendente",
		chartType: "Tipo de Gráfico",
		column: "Gráfico de Coluna",
		bar: "Gráfico de Barra",
		line: "Gráfico de Linha",
		pie: "Gráfico de Pizza",
		chartColor: "Cor do Gráfico",
		showDataLabels: "Mostrar Rótulos dos Dados",
		setSymbol: "Seleção de Símbolo",
		setHighLightColor: "Cor de Destaque",
		settings: "Configurações",
		mapInterationOptions: "Opções de Interação do Mapa",
		preview: "Visualizar",
		ok: "OK",
		cancel: "Cancelar",
		close: "Fechar",
		setFilterTip: "Configure o filtro corretamente. ",
		setChartTitleTip: "Configure o título do gráfico.",
		setChartTypeTip: "Selecione um tipo de gráfico pelo menos.",
		setDataFieldTip: "Selecione um campo de valor pelo menos.",
		setOutputFieldTip: "Configure os campos de saída.",
		count: "Contagem",
		label: "Rótulo",
		horizontalAxis: "Eixo Horizontal",
		verticalAxis: "Eixo Vertical",
		dataLabels: "Rótulos de Data",
		color: "Cor",
		colorful: "Colorido",
		monochromatic: "Monocromático"
  })
);