define(
	 ({
		queries: "查询任务",
		addNew: "新增",
		setSource: "集合",
		setDataSource: "设置数据源",
		name: "名称",
		querySource: "数据源",
		queryName: "任务名称",
		queryDefinition: "过滤器定义",
		resultsSetting: "结果设置",
		symbolSetting: "符号设置",
		resultSettingTip: "定义输出结果的显示内容和显示方式。",
		resultItemTitle: "结果项目标题",
		resultItemContent: "结果项目内容",
		fieldsSetTip: "检查您希望显示的字段。选择要更新别名、进行排序和格式化的字段。",
		addField: "添加字段",
		visibility: "可见性",
		alias: "别名",
		specialType: "特殊类型",
		actions: "操作",
		none: "无",
		link: "链接",
		image: "图像",
		noField: "无字段",
		operationalLayerTip: "将结果添加为业务图层",
		setLayerSymbolTip: "设置查询结果的符号: ",
		setSelectedSymbolTip: "设置所选要素的符号。",
		notUseFilter: "不使用过滤器",
		setSourceTip: "请设置查询源。",
		setFilterTip: "请正确设置过滤器。",
		ok: "确定",
		cancel: "取消",
		noFilterTip: "在未定义过滤表达式的情况下，此查询任务会列出指定数据源中的所有要素。"
  })
);