define(
   ({
    routeUrl: "ルート URL",
    locatorUrl: "ジオコーダーの URL",
    geocoderOptions: "ジオコーダ オプション",
    autoComplete: "自動入力",
    maxLocations: "最大位置数",
    minCharacters: "最小文字数",
    searchDelay: "検索の遅延",
    placeholder: "プレースホルダー",
    routeOptions: "ルート オプション",
    directionsLanguage: "ルート案内の言語",
    directionsLengthUnits: "ルート案内の長さの単位",
    directionsOutputType: "ルート案内の出力タイプ",
    impedanceAttribute: "インピーダンス属性",
    kilometers: "キロメートル",
    miles: "マイル",
    meters: "メートル",
    feet: "フィート",
    yards: "ヤード",
    nauticalMiles: "海里",
    parametersTip: "パラメーターを正しく設定してください",
    complete: "完了",
    completeNoEvents: "完了したイベントはありません",
    instructionsOnly: "手順のみ",
    standard: "標準",
    summaryOnly: "サマリーのみ",
    travelModesUrl: "移動モードの URL",
    searchPlaceholder: "住所または場所の検索",
    trafficLayerUrl: "交通量レイヤーの URL"
  })
);