define(
	 ({
		charts: "Diagramuppgifter",
		addNew: "Lägg till ny",
		addNewTip: "Lägg till en ny diagramuppgift",
		name: "Namn",
		set: "Ange",
		setDataSource: "Ange datakälla",
		generalSettingsTip: "Ange datakälla, titel och beskrivning för diagram.",
		chartModeSettingTip: "Välj ett sätt att analysera och visa data som diagram.",
		detailsSettingTip: "Ange diagrammets utseende genom att ställa in typ och färg samt vilka värden som ska ingå.",
		symbolSettingTip: "Ange kartvisning för data i diagrammet.",
		addFilterTip: "Lägg till filter till dessa data",
		dataSource: "Datakälla",
		noResults: "Inget geoobjekt hittades.",
		chartTitle: "Diagramtitel",
		description: "Beskrivning",
		chartingMode: "Diagramvisning",
		featureOption: "Visa värden geoobjekt för geoobjekt",
		categoryOption: "Visa värden efter kategori",
		countOption: "Visa geoobjektantal efter kategori",
		fieldOption: "Visa attributvärden som diagram",
		category: "Kategori",
		axisLabel: "Kategorietikett",
		categoryField: "Kategorifält",
		operation: "Åtgärd",
		originalOption: "Använd originalvärden",
		sumOption: "Summa",
		averageOption: "Medel",
		minOption: "Minimum",
		maxOption: "Högsta värde",
		valueFields: "Värdefält",
		moveUp: "Flytta uppåt",
		moveDown: "Flytta nedåt",
		sortOrder: "Sortera diagramordningen via kategorietiketter",
		ascending: "Stigande",
		descending: "Fallande",
		chartType: "Diagramtyp",
		column: "Kolumndiagram",
		bar: "Stapeldiagram",
		line: "Linjediagram",
		pie: "Cirkeldiagram",
		chartColor: "Diagramfärg",
		showDataLabels: "Visa dataetiketter",
		setSymbol: "Markeringssymbol",
		setHighLightColor: "Markeringsfärg",
		settings: "Inställningar",
		mapInterationOptions: "Alternativ för interaktion med kartan",
		preview: "Förhandsgranska",
		ok: "OK",
		cancel: "Avbryt",
		close: "Stäng",
		setFilterTip: "Ställ in filtret korrekt. ",
		setChartTitleTip: "Ange en diagramtitel.",
		setChartTypeTip: "Välj minst en diagramtyp.",
		setDataFieldTip: "Välj minst ett värdefält.",
		setOutputFieldTip: "Välj utdatafält.",
		count: "Antal",
		label: "Etikett",
		horizontalAxis: "Horisontell axel",
		verticalAxis: "Vertikal axel",
		dataLabels: "Dataetiketter",
		color: "Färg",
		colorful: "Färgrika",
		monochromatic: "Monokroma"
  })
);