define(
   ({
    _widgetLabel: "Diagram",
    executeChartTip: "Klicka på någon av följande uppgiftsobjekt för att köra diagrammet.",
    invalidConfig: "Ogiltig konfiguration.",
    noneChartTip: "Ingen diagramuppgift har konfigurerats för denna widget.",
    chartParams: "Alternativ",
    charts: "DIAGRAM",
    apply: "TILLÄMPA",
    useSpatialFilter: "Använd geografiskt filter för att begränsa geoobjekt",
    useCurrentMapExtent: "Endast geoobjekt som korsar det aktuella kartområdet",
    drawGraphicOnMap: "Endast geoobjekt som korsar ett användardefinierat område",
    chartResults: "Diagramresultat",
    clearResults: "Rensa resultat",
    noPermissionsMsg: "Du saknar behörighet för att få åtkomst till denna tjänst.",
    specifySpatialFilterMsg: "Ange ett geografiskt filter för den här uppgiften.",
    queryError: "Frågan misslyckades.",
    noResults: "Inget geoobjekt hittades.",
    category: "Kategori",
    count: "Antal",
    label: "Etikett",
    horizontalAxis: "Horisontell axel",
    verticalAxis: "Vertikal axel",
    dataLabels: "Dataetiketter",
    color: "Färg",
    colorful: "Färgrika",
    monochromatic: "Monokroma",
    tasks: "Uppgifter",
    results: "Resultat",
    applySpatialFilterToLimitResults: "Lägg på ett geografiskt filter så att resultaten begränsas",
    useCurrentExtentTip: "Helt eller delvis inom den aktuella kartutbredningen",
    useDrawGraphicTip: "Helt eller delvis inom den form som ritats på kartan",
    useFeaturesTip: "Baserat på deras platser relativt geoobjekt i ett annat lager",
    noSpatialLimitTip: "Begränsa inte resultaten geografiskt",
    applySearchDistance: "Använd en sökdistans",
    spatialRelationship: "Geografisk relation",
    relatedLayer: "Relaterat lager",
    clear: "Rensa",
    bufferDistance: "Buffertavstånd",
    miles: "Engelska mil",
    kilometers: "Kilometer",
    feet: "Fot",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Nautiska mil",
    back: "Bakom",
    execute: "Utför"
  })
);