define(
   ({
    _widgetLabel: "Kaavio",
    executeChartTip: "Luo kaavio napsauttamalla jotakin seuraavista tehtäväkohteista.",
    invalidConfig: "Virheellinen kokoonpano",
    noneChartTip: "Tälle pienoisohjelmalle ei ole määritetty kaaviotehtävää.",
    chartParams: "Valinnat",
    charts: "KAAVIOT",
    apply: "KÄYTÄ",
    useSpatialFilter: "Rajoita kohteita käyttämällä sijaintisuodatinta",
    useCurrentMapExtent: "Vain nykyisen kartta-alueen kanssa leikkaavat kohteet",
    drawGraphicOnMap: "Vain käyttäjän määrittämän alueeseen kanssa leikkaavat kohteet",
    chartResults: "Kaaviotulokset",
    clearResults: "Tyhjennä tulokset",
    noPermissionsMsg: "Sinulla ei ole palvelun käyttöoikeutta.",
    specifySpatialFilterMsg: "Määritä tehtävän sijaintisuodatin.",
    queryError: "Kysely epäonnistui.",
    noResults: "Kohdetta ei löytynyt.",
    category: "Luokka",
    count: "Lukumäärä",
    label: "Tunnusteksti",
    horizontalAxis: "Vaaka-akseli",
    verticalAxis: "Pystyakseli",
    dataLabels: "Tietojen tunnustekstit",
    color: "Väri",
    colorful: "Värikäs",
    monochromatic: "Yksivärinen",
    tasks: "Tehtävät",
    results: "Tulokset",
    applySpatialFilterToLimitResults: "Rajoita tuloksia käyttämällä sijaintisuodatinta",
    useCurrentExtentTip: "Osittain tai kokonaan nykyisessä karttalaajuudessa",
    useDrawGraphicTip: "Osittain tai kokonaan karttaan piirretyn muodon sisällä",
    useFeaturesTip: "Niiden sijaintien perusteella suhteessa toisen karttatason kohteisiin",
    noSpatialLimitTip: "Älä rajoita tuloksia sijaintitietojen mukaan",
    applySearchDistance: "Käytä hakuetäisyyttä",
    spatialRelationship: "Sijaintisuhde",
    relatedLayer: "Liittyvä karttataso",
    clear: "Tyhjennä",
    bufferDistance: "Puskurin etäisyys",
    miles: "Mailia",
    kilometers: "Kilometriä",
    feet: "Jalka",
    meters: "Metriä",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    back: "Takaisin",
    execute: "Suorita"
  })
);