define(
   ({
    routeUrl: "URL de rota",
    locatorUrl: "URL de Localizador",
    geocoderOptions: "Opções do Geocodificador",
    autoComplete: "Auto Completar",
    maxLocations: "Locais máximos",
    minCharacters: "Caracteres mínimos",
    searchDelay: "Demora na pesquisa",
    placeholder: "Placeholder",
    routeOptions: "Opções de rota",
    directionsLanguage: "Idioma das direções",
    directionsLengthUnits: "Unidades de comprimento das direções",
    directionsOutputType: "Tipo de saída das direções",
    impedanceAttribute: "Atributo de impedância",
    kilometers: "Quilômetros",
    miles: "Milhas",
    meters: "Metros",
    feet: "Pés",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    parametersTip: "Por favor, defina os parâmetros corretamente!",
    complete: "Completo",
    completeNoEvents: "Completo Sem Eventos",
    instructionsOnly: "Apenas Instruções",
    standard: "Padrão",
    summaryOnly: "Resumo Apenas",
    travelModesUrl: "URL de Modos de Viagem",
    searchPlaceholder: "Encontrar um endereço ou local",
    trafficLayerUrl: "URL de Camada de Tráfego"
  })
);