define(
   ({
    selectAnalysisTools:"تحديد أدوات التحليل المُدرجة في عنصر واجهة المستخدم.",
    selected: "المحدد",
    name: "الاسم",
    graphicalDisplay:"عرض بياني",
    usage: "استخدام",
    toolNotAvailable: "هذه الأداة غير متوفرة لأن الخريطة لا تحتوي على طبقات المعلم المطلوبة.",
    aggregatePoints:"تجميع النقاط",
    aggregatePointsUsage:"تجميع النقاط في مضلعات حيث تقع النقاط.",
    aggregatePointsInputTip: "تحديد طبقة معالم النقطة التي سيتم تجميعها في المضلعات في طبقة معالم المضلع.",
    calculateDensity:"حساب الكثافة",
    calculateDensityUsage:"إنشاء خريطة كثافة من معالم نقطية أو معالم خطية عبر نشر كميات مُحددة من بعض الظواهر (المُمثلة كبيانات جدولية من الخطوط أو النقاط) عبر الخريطة.",
    calculateDensityInputTip:"تحديد معالم النقطة أو الخط الذي يتم حساب الكثافة منه.",
    connectOriginsToDestinations: "ربط الأصول بالوجهات",
    connectOriginsToDestinationsUsage: "قياس وقت السفر أو مسافة السفر بين نقطتين.",
    connectOriginsToDestinationsInputTip: "تحديد نقطة أو نقاط البدء في الطرق لإنشائها.",
    createBuffers:"إنشاء مخازن مؤقتة",
    createBuffersUsage:"إنشاء مضلع احتياطي من المعالم المُدخلة.",
    createBuffersInputTip:"تحديد طبقة معلم النقطة أو الخط أو المضلع لتخزينها مؤقتًا.",
    createDriveTimeAreas:"إنشاء مناطق زمن القيادة",
    createDriveTimeAreasUsage:"إنشاء مضلعات وقت القيادة (أو مسافة القيادة) حول النقاط المدخلة لقيم وقت القيادة المحددة.",
    createDriveTimeAreasInputTip:"تحديد نقاط رسم مناطق زمن القيادة.",
    createViewshed:"إنشاء مُسطح بزاوية مُحددة",
    createViewshedUsage:"إنشاء مناطق مرئية بحسب المواقع التي تحددها.",
    createViewshedInputTip:"تحديد مواقع المُراقب لتحديد المناطق المرئية.",
    createWatersheds:"إنشاء أحواض مائية",
    createWatershedsUsage:"إنشاء مناطق تخزين مؤقت وفقًا للمواقع التي تُحددها.",
    createWatershedsInputTip:"تحديد معالم النقطة المستخدم في حساب الأحواض المائية.",
    deriveNewLocations:"اشتقاق مواقع جديدة",
    deriveNewLocationsUsage:"اشتقاق معالم جديدة من الطبقات المُدخلة التي تُلبي الاستعلام الذي تحدده",
    deriveNewLocationsInputTip:"تحديد طبقة التحليل لاستخدامها كمُدخلات.",
    dissolveBoundaries:"إذابة الحدود",
    dissolveBoundariesUsage:"إذابة المضلعات التي تتراكب أو تشترك مع حدود مشترك.",
    dissolveBoundariesInputTip:"تحديد الطبقة التي تضم معالم المضلع التي سيتم إذابتها.",
    enrichLayer:"تحسين الطبقة",
    enrichLayerUsage:"تحسين المعالم المدخلة التي تتضمن أشخاصًا وأماكنًا وحقائق عن الأعمال عن المناطق القريبة.",
    enrichLayerInputTip:"تحديد المعالم لتحسينها في بيانات جديدة.",
    extractData:"استخراج البيانات",
    extractDataDesc:"استخراج البيانات من طبقة أو أكثر ضمن مدى محدد",
    extractDataInputTip:"تحديد طبقة المعالم المدخلة لاستخراجها.",
    findExistingLocations:"العثور على المواقع الحالية",
    findExistingLocationsUsage:"تحديد المعالم في الطبقة المدخلة التي تُلبي جدول البيانات و/أو استعلام المكان الذي حددته",
    findExistingLocationsInputTip:"تحديد طبقات التحليل لاستخدامها كمُدخلات.",
    findHotSpots:"العثور على المناطق الفعالة",
    findHotSpotsUsage:"العثور على تجمّعات هامة إحصائيًا من المعالم المدخلة أو القيم العليا/الدنيا.",
    findHotSpotsInputTip:"تحديد طبقة معلم النقطة أو المضلع الذي يتم حساب المناطق الفعالة منه.",
    findNearest:"العثور على الأقرب",
    findNearestUsage:"لكل معلم من المعالم في طبقة مدخلة، اعثر على المعلم الأقرب في طبقة أخرى",
    findNearestInputTip:"تحديد معالم النقطة أو الخط أو المضلع حيث يتم العثور على أقرب مواقع.",
    findSimilarLocations:"العثور على مواقع مشابهة.",
    findSimilarLocationsUsage:"قياس تشابه المواقع المرشحة لموقع أو أكثر مواقع الإسناد.",
    findSimilarLocationsInputTip:"حدد طبقة معالم تحتوي على موقع إسناد أو أكثر مُقابل المعالم في طبقة البحث التي سيتم تقييمها للتشابه.",
    interpolatePoints:"استيفاء النقاط",
    interpolatePointsUsage:"التنبؤ بالقيم في مواقع جديدة بناءً على المقاييس من مجموعة من النقاط.",
    interpolatePointsInputTip:"تحديد معالم النقطة التي سيتم استيفائها.",
    mergeLayers:"دمج الطبقات",
    mergeLayersUsage:"دمج المعالم من عدة طبقات في طبقة جديدة",
    mergeLayersInputTip:"تحديد طبقة المعالم المُراد دمجها في طبقة الدمج.",
    overlayLayers:"تراكب الطبقات",
    overlayLayersUsage:"الدمج بين عدة طبقات لتكون طبقة مفردة واحدة مصحوبة بمعلومات من الطبقات الأصلية المحفوظة.",
    overlayLayersInputTip:"تحديد طبقة المعالم التي ستتراكب مع طبقة التراكب.",
    planRoutes:"تخطيط الاتجاهات",
    planRoutesUsage:"تحديد كيفية تقسيم المهام بفاعلية ضمن القوة العاملة المتنقلة.",
    planRoutesInputTip:"تحديد النقاط التي يجب على المركبات أو السائقين أو الطرق زيارتها",
    summarizeNearby:"تلخيص القريب",
    summarizeNearbyUsage:"لكل معلم من المعالم في طبقة مدخلة، لخّص البيانات ضمن مسافة من المعالم في طبقة أخرى.",
    summarizeNearbyInputTip:"حدد طبقة معلم النقطة أو الخط أو المضلع من المسافات التي سيتم قياسها للمعالم في تلخيص الطبقة.",
    summarizeWithin:"تلخيص ضمن",
    summarizeWithinUsage:"في كل مضلع في طبقة المضلع المدخلة، لخّص البيانات الواقعة ضمنها من المعالم في طبقة أخرى.",
    summarizeWithinInputTip:"تحديد طبقة معلم المضلع المراد تلخيصها.",
    traceDownstream:"تتبّع انتقال البيانات من الخادم",
    traceDownstreamUsage:"تحديد مسارات التدفق في اتجاه انتقال البيانات من الخادم من المواقع التي تحددها.",
    traceDownstreamInputTip:"تحديد معالم النقاط المستخدمة في موقع البدء لتتبع انتقال البيانات من الخادم."
  })
);
