define(
   ({
    selectAnalysisTools:"تحديد أدوات التحليل لاستخدامها في عناصر واجهة الاستخدام.",
    selected: "المحدد",
    name: "الاسم",
    graphicalDisplay:"عرض بياني",
    usage: "استخدام",
    settings: "الإعدادات",
    toolSetting: "تحديد تفاصيل الأداة",
    toolLabel: "اسم عرض الأداة",
    showHelpTip: "عرض روابط المساعدة في عناصر واجهة الاستخدام",
    showCurrentMapExtent: "عرض خيار لاستخدام مدى الخريطة الحالي",
    showCredits: "عرض خيار <b>عرض المشرفون</b>",
    saveAsFeatureService: "حفظ النتيجة في حساب userâ€™s",
    showReadyToUseLayers: "عرض الطبقات جاهزة الاستخدام من أطلس العالم الحقيقي في ArcGIS Online",
    toolNotAvailable: "هذه الأداة غير متوفرة لأن الخريطة لا تحتوي على طبقات المعلم المطلوبة.",
    aggregatePoints:"تجميع النقاط",
    aggregatePointsUsage:"تجميع النقاط في مضلعات حيث تقع النقاط.",
    calculateDensity:"حساب الكثافة",
    calculateDensityUsage:"إنشاء خريطة كثافة من معالم نقطية أو معالم خطية عبر نشر كميات مُحددة من بعض الظواهر (المُمثلة كبيانات جدولية من الخطوط أو النقاط) عبر الخريطة.",
    connectOriginsToDestinations: "ربط الأصول بالوجهات",
    connectOriginsToDestinationsUsage: "قياس وقت السفر أو مسافة السفر بين نقطتين.",
    createBuffers:"إنشاء مخازن مؤقتة",
    createBuffersUsage:"إنشاء مضلع احتياطي من المعالم المُدخلة.",
    createDriveTimeAreas:"إنشاء مناطق زمن القيادة",
    createDriveTimeAreasUsage:"إنشاء مضلعات وقت القيادة (أو مسافة القيادة) حول النقاط المدخلة لقيم وقت القيادة المحددة.",
    createViewshed:"إنشاء مُسطح بزاوية مُحددة",
    createViewshedUsage:"إنشاء مناطق مرئية بحسب المواقع التي تحددها.",
    createWatersheds:"إنشاء أحواض مائية",
    createWatershedsUsage:"إنشاء مناطق تخزين مؤقت وفقًا للمواقع التي تُحددها.",
    deriveNewLocations:"اشتقاق مواقع جديدة",
    deriveNewLocationsUsage:"اشتقاق معالم جديدة من الطبقات المُدخلة التي تُلبي الاستعلام الذي تحدده",
    dissolveBoundaries:"إذابة الحدود",
    dissolveBoundariesUsage:"إذابة المضلعات التي تتراكب أو تشترك مع حدود مشترك.",
    enrichLayer:"تحسين الطبقة",
    enrichLayerUsage:"تحسين المعالم المدخلة التي تتضمن أشخاصًا وأماكنًا وحقائق عن الأعمال عن المناطق القريبة.",
    extractData:"استخراج البيانات",
    extractDataDesc:"استخراج البيانات من طبقة أو أكثر ضمن مدى محدد",
    findExistingLocations:"العثور على المواقع الحالية",
    findExistingLocationsUsage:"تحديد المعالم في الطبقة المدخلة التي تُلبي جدول البيانات و/أو استعلام المكان الذي حددته",
    findHotSpots:"العثور على المناطق الفعالة",
    findHotSpotsUsage:"العثور على تجمّعات هامة إحصائيًا من المعالم المدخلة أو القيم العليا/الدنيا.",
    findNearest:"العثور على الأقرب",
    findNearestUsage:"لكل معلم من المعالم في طبقة مدخلة، اعثر على المعلم الأقرب في طبقة أخرى",
    findSimilarLocations:"العثور على مواقع مشابهة.",
    findSimilarLocationsUsage:"قياس تشابه المواقع المرشحة لموقع أو أكثر مواقع الإسناد.",
    interpolatePoints:"استيفاء النقاط",
    interpolatePointsUsage:"التنبؤ بالقيم في مواقع جديدة بناءً على المقاييس من مجموعة من النقاط.",
    mergeLayers:"دمج الطبقات",
    mergeLayersUsage:"دمج المعالم من عدة طبقات في طبقة جديدة",
    overlayLayers:"تراكب الطبقات",
    overlayLayersUsage:"الدمج بين عدة طبقات لتكون طبقة مفردة واحدة مصحوبة بمعلومات من الطبقات الأصلية المحفوظة.",
    planRoutes:"تخطيط الاتجاهات",
    planRoutesUsage:"تحديد كيفية تقسيم المهام بفاعلية ضمن القوة العاملة المتنقلة.",
    summarizeNearby:"تلخيص القريب",
    summarizeNearbyUsage:"لكل معلم من المعالم في طبقة مدخلة، لخّص البيانات ضمن مسافة من المعالم في طبقة أخرى.",
    summarizeWithin:"تلخيص ضمن",
    summarizeWithinUsage:"في كل مضلع في طبقة المضلع المدخلة، لخّص البيانات الواقعة ضمنها من المعالم في طبقة أخرى.",
    traceDownstream:"تتبّع انتقال البيانات من الخادم",
    traceDownstreamUsage:"تحديد مسارات التدفق في اتجاه انتقال البيانات من الخادم من المواقع التي تحددها."
  })
);
