define(
   ({
    routeUrl: "عنوان URL للمسار",
    locatorUrl: "عنوان URL للمُكود الجغرافي",
    geocoderOptions: "خيارات المكود الجغرافي",
    autoComplete: "اكتمال تلقائي",
    maxLocations: "المواقع القصوى",
    minCharacters: "الأحرف الدُنيا",
    searchDelay: "تأخير البحث",
    placeholder: "عنصر نائب",
    routeOptions: "خيارات التوجيه",
    directionsLanguage: "لغة الاتجاهات",
    directionsLengthUnits: "وحدات طول الاتجاهات",
    directionsOutputType: "نوع الاتجاهات الناتج",
    impedanceAttribute: "معاوقة البيانات الجدولية",
    kilometers: "كيلومترات",
    miles: "أميال",
    meters: "مترات",
    feet: "قدم",
    yards: "ياردات",
    nauticalMiles: "ميل بحري",
    parametersTip: "الرجاء تعيين المعلمات بشكل صحيح!",
    complete: "إكمال",
    completeNoEvents: "إكمال لا توجد أحداث",
    instructionsOnly: "التعليمات فقط",
    standard: "قياسي",
    summaryOnly: "التلخيص فقط",
    travelModesUrl: "عنوان URL لأوضاع السفر",
    searchPlaceholder: "العثور على عنوان أو مكان ما",
    trafficLayerUrl: "عنوان URL لطبقة حركة المرور"
  })
);