define(
   ({
    _widgetLabel: "Padėties suvokimas (beta)",
    locate_incident: "Rasti įvykį",
    clear_incidents: "Valyti įvykius",
    reverse_geocoded_address: "Artimiausias adresas",
    reverse_geocoded_error: "Negalimas",
    miles: "Mylios",
    kilometers: "Kilometrai",
    feet: "Pėdos",
    meters: "Metrai",
    yards: "Jardai",
    nauticalMiles: "Jūrmylės",
    now: "DABAR",
    wind: "VĖJAS",
    SUN: "SEK",
    MON: "PIR",
    TUE: "ANT",
    WED: "TRE",
    THU: "KET",
    FRI: "PEN",
    SAT: "ŠEŠ",
    defaultTabMsg: "Nurodytų įvykių nėra.",
    actionLabel: "Nustatyti kaip įvykį",
    drawPoint: "Brėžti tašką",
    drawLine: "Brėžti liniją",
    drawPolygon: "Brėžti plotą",
    saveIncident: "Įrašyti įvykį",
    clearIncident: "Valyti įvykį",
    useMapExtent: "Naudoti esamą žemėlapio plotą",
    noFeaturesFound: "Elementų nerasta.",
    downloadCSV: "ATSISIŲSTI CSV",
    editComplete: "Elementas įrašytas sėkmingai!",
    updateComplete: "Elementas atnaujintas sėkmingai!",
    deleteComplete: "Elementas panaikintas sėkmingai!",
    sum: "SUMA",
    min: "MIN.",
    max: "MAKS.",
    avg: "VID.",
    count: "KIEKIS",
    area: "PLOTAS",
    length: "ILGIS",
    notPolySave: "Prieš įrašydami nurodykite buferio nuotolį.",
    update_btn: "Naujinti",
    delete_btn: "Pašalinti"
  })
);
