define({
    selectFeatures: "Par Forme",
    selectByAttribute: "Par Attribut",
    results: "Résultats",
    searchLayer: "Couche de recherche",
    searchType: "Alias de la recherche",
    selectFeaturesBy: "Sélection d'entités par",
    selectSpatial: "Sélection Spatiale",
    search: "Rechercher",
    clear: "Vider",
    clearBuffer: "Supprimer la zone tampon",
    zoomall: "Zoom tous",
    point: "Point",
    line: "Ligne",
    polyline: "Polyligne",
    freehandPolyline: "Polyligne libre",
    triangle: "Triangle",
    extent: "Etendue",
    circle: "Cercle",
    ellipse: "Ellipse",
    polygon: "Polygone",
    freehandPolygon: "Polygone libre",
    featuresSelected: "Entités sélectionnées: ",
    noResults: "Pas de résultats",
    searchError: "La recherche a échouée !",
    searchResult: "Résultat de la recherche",
    useMultiGraphics: "Autoriser les graphiques multi-parties",
    addTolerance: "Ajouter un tolrérance à la recherche autour du point sélectionné",
    specifyParamsTip: "Spécifier les paramètres pour cette recherche",
    and: "et",
    friendlyDatePattern: "MM/dd/aaaa",
    stringOperatorIs: 'stringOperatorIs',
    stringOperatorIsNot: 'stringOperatorIsNot',
    stringOperatorStartsWith: 'stringOperatorStartsWith',
    stringOperatorEndsWith: 'stringOperatorEndsWith',
    stringOperatorContains: 'stringOperatorContains',
    stringOperatorDoesNotContain: 'stringOperatorDoesNotContain',
    stringOperatorIsBlank: 'stringOperatorIsBlank',
    stringOperatorIsNotBlank: 'stringOperatorIsNotBlank',
    dateOperatorIsOn: 'dateOperatorIsOn',
    dateOperatorIsNotOn: 'dateOperatorIsNotOn',
    dateOperatorIsBefore: 'dateOperatorIsBefore',
    dateOperatorIsAfter: 'dateOperatorIsAfter',
    dateOperatorDays: 'dateOperatorDays',
    dateOperatorWeeks: 'dateOperatorWeeks',
    dateOperatorMonths: 'dateOperatorMonths',
    dateOperatorInTheLast: 'dateOperatorInTheLast',
    dateOperatorNotInTheLast: 'dateOperatorNotInTheLast',
    dateOperatorIsBetween: 'dateOperatorIsBetween',
    dateOperatorIsNotBetween: 'dateOperatorIsNotBetween',
    dateOperatorIsBlank: 'dateOperatorIsBlank',
    dateOperatorIsNotBlank: 'dateOperatorIsNotBlank',
    numberOperatorIs: 'numberOperatorIs',
    numberOperatorIsNot: 'numberOperatorIsNot',
    numberOperatorIsAtLeast: 'numberOperatorIsAtLeast',
    numberOperatorIsLessThan: 'numberOperatorIsLessThan',
    numberOperatorIsAtMost: 'numberOperatorIsAtMost',
    numberOperatorIsGreaterThan: 'numberOperatorIsGreaterThan',
    numberOperatorIsBetween: 'numberOperatorIsBetween',
    numberOperatorIsNotBetween: 'numberOperatorIsNotBetween',
    numberOperatorIsBlank: 'numberOperatorIsBlank',
    numberOperatorIsNotBlank: 'numberOperatorIsNotBlank',
    bufferGraphic: 'Zone tampon - graphique',
    searchDistance: 'Appliquer une distance de recherche:',
    applyBuffer: 'Ajouter la zone tampon',
    searchEntities: 'Rechercher les entités dans :',
    intersectMessage: 'Il n\'y a pas de résultats pour l\'intersection, veuillez réaliser une recherche graphique ou sémenatique en premier.',
    spatialSearchErrorTitle: 'Erreur dans la recherche spatiale',
    bufferMessage: 'Il n\'a pas de résultat dans la zone tampon, merci de faire une recherche par attributs ou graphiques.',
    bufferSearchErrorTitle: 'Erreur pour la zone tampon',
    spatialchoicemsg: 'Souhaitez vous utiliser la zone tampon -graphique ou les Graphiques de sélection ?',
    spatialchoicetitle: 'Sélectionner',
    buffergraphics: 'Zone tampon',
    selectiongraphics: 'Sélection',
    widgetversion: 'Info. sur la version du Widget eSearch',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Ce Widget a été créé pour fonctionner avec la version du Web AppBuilder',
    exporturl: 'URL de la Recherche Export',
    copyurlprompt: 'Copier dans le presse-papiers: Ctrl+C, Entrer',
    limit2mapextent: 'Limiter les résultats aux cartes mesure',
    graphicgeomtypemsg1: 'Mélanger les types de géométrie majeurs comme des points, des lignes et des polygones est pas pris en charge.',
    graphicgeomtypemsg2: 'Voulez-vous continuer ce qui se traduira en effaçant tous les graphiques dessinés précédentes?',
    cancel: 'annuler',
    continue: 'continuer',
    warning: 'Attention!',
    zoomErrorMessage: 'Les tentatives de zoom automatique aux résultats de la recherche ont échoué.',
    addTextQuery: 'Inclure le texte requête dans les critères de sélection',
    uniqueValues: 'Récupération des valeurs uniques',
    processingUnique: 'Traitement des valeurs uniques: ',
    of: ' de ',
    requiredTip: "Valeur nécessaire pour exécuter la recherche",
    required: "Nécessaire",
    requiredWarning: "Valeur Obligatoire manquant",
    requiredErrorMessage: "Vous avez échoué à entrer un ou plusieurs valeurs requises",
    selectFeaturesFrom: "Utilisez des graphiques à partir de",
    eLocateTip: "L'utilisation actuelle Enhanced Localiser Graphics Widget",
    createnewselection: "Créer de nouveaux résultats",
    addtoselection: "Ajouter aux résultats actuels",
    removefromselection: "Retirer de résultats actuels",
    mapServiceFailureTitle: "Recherche d'erreurs couche Map Service",
    mapServicefailureMsg: "La couche de recherche suivant (s) service de carte (s) n'a pas répondu: ",
    mapServicefailureMsg2: ". En raison de cet échec la couche (s) de recherche sera supprimé de le widget."
});
