define({
    selectFeatures: "Par Forme",
    selectByAttribute: "Par Attribut",
    results: "Résultats",
    searchLayer: "Couche de recherche",
    searchType: "Alias de la recherche",
    selectFeaturesBy: "Sélection d'entités par",
    selectSpatial: "Sélection Spatiale",
    search: "Rechercher",
    clear: "Vider",
    clearBuffer: "Supprimer la zone tampon",
    zoomall: "Zoom tous",
    point: "Point",
    line: "Ligne",
    polyline: "Polyligne",
    freehandPolyline: "Polyligne libre",
    triangle: "Triangle",
    extent: "Etendue",
    circle: "Cercle",
    ellipse: "Ellipse",
    polygon: "Polygone",
    freehandPolygon: "Polygone libre",
    featuresSelected: "Entités sélectionnées: ",
    noResults: "Pas de résultats",
    searchError: "La recherche a échouée !",
    searchResult: "Résultat de la recherche",
    useMultiGraphics: "Autoriser les graphiques multi-parties",
    addTolerance: "Ajouter un tolrérance à la recherche autour du point sélectionné",
    specifyParamsTip: "Spécifier les paramètres pour cette recherche",
    and: "et",
    friendlyDatePattern: "MM/dd/aaaa",
    stringOperatorIs: 'stringOperatorIs',
    stringOperatorIsNot: 'stringOperatorIsNot',
    stringOperatorStartsWith: 'stringOperatorStartsWith',
    stringOperatorEndsWith: 'stringOperatorEndsWith',
    stringOperatorContains: 'stringOperatorContains',
    stringOperatorDoesNotContain: 'stringOperatorDoesNotContain',
    stringOperatorIsBlank: 'stringOperatorIsBlank',
    stringOperatorIsNotBlank: 'stringOperatorIsNotBlank',
    dateOperatorIsOn: 'dateOperatorIsOn',
    dateOperatorIsNotOn: 'dateOperatorIsNotOn',
    dateOperatorIsBefore: 'dateOperatorIsBefore',
    dateOperatorIsAfter: 'dateOperatorIsAfter',
    dateOperatorDays: 'dateOperatorDays',
    dateOperatorWeeks: 'dateOperatorWeeks',
    dateOperatorMonths: 'dateOperatorMonths',
    dateOperatorInTheLast: 'dateOperatorInTheLast',
    dateOperatorNotInTheLast: 'dateOperatorNotInTheLast',
    dateOperatorIsBetween: 'dateOperatorIsBetween',
    dateOperatorIsNotBetween: 'dateOperatorIsNotBetween',
    dateOperatorIsBlank: 'dateOperatorIsBlank',
    dateOperatorIsNotBlank: 'dateOperatorIsNotBlank',
    numberOperatorIs: 'numberOperatorIs',
    numberOperatorIsNot: 'numberOperatorIsNot',
    numberOperatorIsAtLeast: 'numberOperatorIsAtLeast',
    numberOperatorIsLessThan: 'numberOperatorIsLessThan',
    numberOperatorIsAtMost: 'numberOperatorIsAtMost',
    numberOperatorIsGreaterThan: 'numberOperatorIsGreaterThan',
    numberOperatorIsBetween: 'numberOperatorIsBetween',
    numberOperatorIsNotBetween: 'numberOperatorIsNotBetween',
    numberOperatorIsBlank: 'numberOperatorIsBlank',
    numberOperatorIsNotBlank: 'numberOperatorIsNotBlank',
    bufferGraphic: 'Zone tampon - graphique',
    searchDistance: 'Appliquer une distance de recherche:',
    applyBuffer: 'Ajouter la zone tampon',
    searchEntities: 'Rechercher les entités dans :',
    intersectMessage: 'Il n\'y a pas de résultats pour l\'intersection, veuillez réaliser une recherche graphique ou sémenatique en premier.',
    spatialSearchErrorTitle: 'Erreur dans la recherche spatiale',
    bufferMessage: 'Il n\'a pas de résultat dans la zone tampon, merci de faire une recherche par attributs ou graphiques.',
    bufferSearchErrorTitle: 'Erreur pour la zone tampon',
    spatialchoicemsg: 'Souhaitez vous utiliser la zone tampon -graphique ou les Graphiques de sélection ?',
    spatialchoicetitle: 'Sélectionner',
    buffergraphics: 'Zone tampon',
    selectiongraphics: 'Sélection',
    widgetversion: 'Info. sur la version du Widget eSearch',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Ce Widget a été créé pour fonctionner avec la version du Web AppBuilder',
    exporturl: 'URL de la Recherche Export',
    copyurlprompt: 'Copier dans le presse-papiers: Ctrl+C, Entrer'
});
