define(
	 ({
		queries: "Задачи запросов",
		addNew: "Добавить новый",
    queryLayer: "Запрос слоя",
		setSource: "Задать",
		setDataSource: "Задать источник данных",
		name: "Имя",
		querySource: "Источник данных",
		queryName: "Имя задачи",
		queryDefinition: "Определение фильтра",
		resultsSetting: "Настройка результатов",
		symbolSetting: "Настройка символов",
		resultSettingTip: "Задайте способ отображения выходных результатов.",
		resultItemTitle: "Название полученного элемента",
		resultItemContent: "Содержание элемента результата",
		fieldsSetTip: "Отметьте поля, которые требуется отобразить. Выберите поле, чтобы изменить его псевдоним, порядок сортировки и формат.",
		addField: "Добавить поле",
		visibility: "Видимость",
		alias: "Псевдоним",
		specialType: "Особый тип",
		actions: "Действия",
		none: "Нет",
		link: "Ссылка",
		image: "Изображение",
		noField: "Нет поля",
		operationalLayerTip: "Добавить результат как операционный слой",
		setLayerSymbolTip: "Задать символ для результатов запроса: ",
		setSelectedSymbolTip: "Задать символ для выбранных объектов.",
		notUseFilter: "Не используйте фильтр",
		setSourceTip: "Задайте источник запроса.",
		setFilterTip: "Задайте корректный фильтр.",
		ok: "OK",
		cancel: "Отмена",
		noFilterTip: "Если не задано выражение для фильтра, этот запрос перечислит все объекты указанного источника данных.",
    relationships: "Отношения",
    addRelationshipLayer: "Добавить новое отношение",
    relatedTo: "Связано с",
    selectOption: "Выберите..",
    resultItemSorting: "Сортировка элементов результатов",
    field: "Поле",
    sortingOrder: "Порядок",
    configureFieldsTip: "Настройте поля, в которых будут сортироваться результаты запроса.",
    setSortingFields: "Задать поля сортировки",
    ascending: "По возрастанию",
    descending: "По убыванию",
    sortBy: "Сортировать по",
    thenBy: "Далее по",
    addTask: "Добавить задачу",
    noTasksTip: 'Нет задач, щелкните \"${addTask}\", чтобы начать!',
    infoText: "Информация",
    filters: "Фильтры",
    results: "Результаты",
    optionsText: "Опции",
    summaryText: "Краткая информация",
    attributeFilter: "Атрибутивный фильтр",
    attributeFilterTip: "Задать атрибутивные выражения в виджете для фильтрации слоя запроса.",
    noExpressionDefinedTip: "Выражение не задано.",
    needInputValuesTip: "Необходимо вводить значения во время выполнения",
    setExpressions: "Задать Выражения",
    spatialFilter: "Пространственный фильтр",
    spatialFilterTip: "Выберите пространственные фильтры виджета для ограничения результатов.",
    defaultOption: "По умолчанию",
    useCurrentExtentTip: "Частично или полностью в пределах текущего экстента карты",
    useDrawGraphicTip: "Частично или полностью в пределах фигуры на карте",
    useFeaturesTip: "На основе местоположения относительно объектов другого слоя",
    noSpatialLimitTip: "Не ограничивать результаты пространственным фильтром",
    drawingTools: "Инструменты рисования",
    bufferSettings: "Параметры буфера",
    defaultDistance: "Расстояние по умолчанию",
    bufferDistance: "Буферное расстояние",
    defaultUnit: "Единицы по умолчанию",
    miles: "Мили",
    kilometers: "Километры",
    feet: "Футы",
    meters: "Метры",
    yards: "Ярды",
    nauticalMiles: "Морские мили",
    availableSpatialRelationships: "Доступные пространственные отношения",
    setSpatialRelationships: "Задать пространственные отношения",
    availability: "Доступность",
    relationship: "Отношение",
    label: "Подпись",
    intersect: "пересекают",
    contain: "содержат",
    areContainedIn: "содержатся в",
    cross: "крест",
    envelopeIntersect: "пересекает внешнюю границу",
    overlap: "наложение",
    areOverlapped: "перекрывается",
    touche: "касается",
    within: "внутри",
    areWithin: "находится в пределах",
    indexIntersect: "пересекает индекс",
    itemTitle: "Название элемента",
    displayFields: "Поля отображения",
    sortingFields: "Поля сортировки",
    setDisplayFields: "Задать отображаемые поля",
    symbol: "Символ",
    setSymbol: "Задать символ",
    serviceSymbolTip: "Использовать символы, заданные слоем",
    exportTip: "Показать кнопку Экспорт",
    keepResultsTip: "Сохранить результаты на карте после закрытия виджета",
    queryRelatedRecords: "Запрос к связанным записям",
    createLayerForTaskTip: "Укажите, как задача должна создавать слои",
    oneLayerForTaskTip: "Создавать только один слой для этой задачи",
    multipleLayerForTaskTip: "Создавать новый слой при каждом выполнении этой задачи"
  })
);
