define({
  root: ({
    styleText: "1. Choose a default style for the swipe tool.",
    vertical: "Vertical bar",
    horizontal: "Horizontal bar",
    scope: "Spyglass",
    spyglassSizeText: "2. Choose the default size for the spyglass:",
    small: 'Small (120 px)',
    medium: 'Medium (260 px)',
    large: 'Large (400 px)',
    layerSelectionHeight: "3. Set the height of the swipe layer selection list (in pixels):",
    layerText: "4. Choose one or more layers you want to swipe by default:",
    spyglassText: "4. Choose one or more layers to appear within the spyglass by default:",
    layerHint: "Note: If the layer(s) is hidden by upper layers, swipe won't have any effect."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});