define(
	 ({
		queries: "Zadania zapytań",
		addNew: "Dodaj nowe",
    queryLayer: "Warstwa zapytania",
		setSource: "Ustaw",
		setDataSource: "Skonfiguruj źródło danych",
		name: "Nazwa",
		querySource: "Źródło danych",
		queryName: "Nazwa zadania",
		queryDefinition: "Definicja filtru",
		resultsSetting: "Ustawienie wyników",
		symbolSetting: "Ustawienia symboli",
		resultSettingTip: "Zdefiniuj, które wyniki mają być wyświetlane, oraz sposób ich wyświetlania.",
		resultItemTitle: "Nazwa elementu wynikowego",
		resultItemContent: "Zawartość elementu wynikowego",
		fieldsSetTip: "Zaznacz pola, które mają być wyświetlane. Wybierz pole, aby zaktualizować jego alias, kolejność i formatowanie.",
		addField: "Dodaj pole",
		visibility: "Widoczność",
		alias: "Alias",
		specialType: "Typ specjalny",
		actions: "Operacje",
		none: "Brak",
		link: "Łącze",
		image: "Obraz",
		noField: "Brak pola",
		operationalLayerTip: "Dodaj wynik jako warstwę operacyjną",
		setLayerSymbolTip: "Skonfiguruj symbol wyników zapytania: ",
		setSelectedSymbolTip: "Skonfiguruj symbol wybranego obiektu.",
		notUseFilter: "Nie stosuj filtrów",
		setSourceTip: "Skonfiguruj źródło zapytania.",
		setFilterTip: "Skonfiguruj poprawnie filtr.",
		ok: "OK",
		cancel: "Anuluj",
		noFilterTip: "Jeżeli wyrażenie filtru nie zostanie zdefiniowane, zadanie zapytania zwróci wszystkie obiekty w podanym źródle danych.",
    relationships: "Zależności",
    addRelationshipLayer: "Dodaj nowe powiązanie",
    relatedTo: "Powiązane z",
    selectOption: "Wybierz...",
    resultItemSorting: "Sortowanie elementów wynikowych",
    field: "Pole",
    sortingOrder: "Kolejność",
    configureFieldsTip: "Proszę skonfigurować pola, według których sortowane będą wyniki wyszukiwania.",
    setSortingFields: "Skonfiguruj pola sortowania",
    ascending: "Rosnąco",
    descending: "Malejąco",
    sortBy: "Sortuj według",
    thenBy: "Następnie według",
    addTask: "Dodaj zadanie",
    noTasksTip: 'Brak zadania; aby rozpocząć, kliknij \"${addTask}\"!',
    infoText: "Informacje",
    filters: "Filtry",
    results: "Wyniki",
    optionsText: "Opcje",
    summaryText: "Podsumowanie",
    attributeFilter: "Filtr atrybutów",
    attributeFilterTip: "Zdefiniuj wyrażenia atrybutów do użytku w widżecie, aby dokonać filtrowania warstwy zapytań.",
    noExpressionDefinedTip: "Nie zdefiniowano żadnych wyrażeń.",
    needInputValuesTip: "Należy wprowadzić wartości w czasie pracy",
    setExpressions: "Skonfiguruj wyrażenia",
    spatialFilter: "Filtr przestrzenny",
    spatialFilterTip: "Wybierz filtry przestrzenne używane w widżecie, aby ograniczyć liczbę wyników.",
    defaultOption: "Domyślne",
    useCurrentExtentTip: "Częściowo lub całkowicie w bieżącym zasięgu mapy",
    useDrawGraphicTip: "Częściowo lub całkowicie w zasięgu narysowanego na mapie obszaru",
    useFeaturesTip: "Na podstawie ich lokalizacji względem obiektów na innej warstwie",
    noSpatialLimitTip: "Nie ograniczaj przestrzennie wyników wyszukiwania",
    drawingTools: "Narzędzia rysowania",
    bufferSettings: "Ustawienia bufora",
    defaultDistance: "Domyślna odległość",
    bufferDistance: "Odległość buforowania",
    defaultUnit: "Jednostka domyślna",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    availableSpatialRelationships: "Dostępne zależności przestrzenne",
    setSpatialRelationships: "Skonfiguruj zależności przestrzenne",
    availability: "Dostępność",
    relationship: "Zależność",
    label: "Etykieta",
    intersect: "przecinają",
    contain: "zawierają",
    areContainedIn: "są zawarte w",
    cross: "krzyżują się",
    envelopeIntersect: "przecinają obwiednię",
    overlap: "nachodzą",
    areOverlapped: "są zakryte",
    touche: "dotykają",
    within: "w zasięgu",
    areWithin: "są w zasięgu",
    indexIntersect: "przecinają indeks",
    itemTitle: "Tytuł elementu",
    displayFields: "Wyświetl pola",
    sortingFields: "Pola sortowania",
    setDisplayFields: "Skonfiguruj pola wyświetlania",
    symbol: "Symbol",
    setSymbol: "Skonfiguruj symbol",
    serviceSymbolTip: "Użyj symboli zdefiniowanych przez warstwę",
    exportTip: "Pokaż przycisk Eksportuj",
    keepResultsTip: "Utrzymuj wyniki na mapie po zamknięciu widżetu",
    queryRelatedRecords: "Rekordy powiązane z zapytaniem",
    createLayerForTaskTip: "Podaj, jak zadanie tworzy warstwy",
    oneLayerForTaskTip: "Utwórz tylko jedną warstwę dla tego zadania",
    multipleLayerForTaskTip: "Utwórz nową warstwę przy każdorazowym uruchomieniu tego zadania"
  })
);
