define(
	 ({
		queries: "Zadania zapytań",
		addNew: "Dodaj nowe",
		setSource: "Ustaw",
		setDataSource: "Skonfiguruj źródło danych",
		name: "Nazwa",
		querySource: "Źródło danych",
		queryName: "Nazwa zadania",
		queryDefinition: "Definicja filtru",
		resultsSetting: "Ustawienie wyników",
		symbolSetting: "Ustawienia symboli",
		resultSettingTip: "Zdefiniuj, które wyniki mają być wyświetlane, oraz sposób ich wyświetlania.",
		resultItemTitle: "Nazwa elementu wynikowego",
		resultItemContent: "Zawartość elementu wynikowego",
		fieldsSetTip: "Zaznacz pola, które mają być wyświetlane. Wybierz pole, aby zaktualizować jego alias, kolejność i formatowanie.",
		addField: "Dodaj pole",
		visibility: "Widoczność",
		alias: "Alias",
		specialType: "Typ specjalny",
		actions: "Operacje",
		none: "Brak",
		link: "Łącze",
		image: "Obraz",
		noField: "Brak pola",
		operationalLayerTip: "Dodaj wynik jako warstwę operacyjną",
		setLayerSymbolTip: "Skonfiguruj symbol wyników zapytania: ",
		setSelectedSymbolTip: "Skonfiguruj symbol wybranego obiektu.",
		notUseFilter: "Nie stosuj filtrów",
		setSourceTip: "Skonfiguruj źródło zapytania.",
		setFilterTip: "Skonfiguruj poprawnie filtr.",
		ok: "OK",
		cancel: "Anuluj",
		noFilterTip: "Jeżeli wyrażenie filtru nie zostanie zdefiniowane, zadanie zapytania zwróci wszystkie obiekty w podanym źródle danych."
  })
);