define(
	 ({
		queries: "Tareas de consulta",
		addNew: "Agregar nueva",
    queryLayer: "Capa de consulta",
		setSource: "Establecer",
		setDataSource: "Definir fuente de datos",
		name: "Nombre",
		querySource: "Fuente de datos",
		queryName: "Nombre de tarea",
		queryDefinition: "Definición de filtro",
		resultsSetting: "Configuración de resultados",
		symbolSetting: "Configuración de símbolo",
		resultSettingTip: "Define qué se debe mostrar en los resultados de salida y cómo mostrarlo.",
		resultItemTitle: "Título del elemento de resultado",
		resultItemContent: "Contenido del elemento de resultado",
		fieldsSetTip: "Marca los campos que deseas mostrar. Selecciona un campo para actualizar su alias, su orden y su formato.",
		addField: "Agregar campo",
		visibility: "Visibilidad",
		alias: "Alias",
		specialType: "Tipo especial",
		actions: "Acciones",
		none: "Ninguno",
		link: "Vínculo",
		image: "Imagen",
		noField: "Sin campo",
		operationalLayerTip: "Agregar resultado como capa operativa",
		setLayerSymbolTip: "Establecer el símbolo para los resultados de consulta: ",
		setSelectedSymbolTip: "Establece el símbolo de la entidad seleccionada.",
		notUseFilter: "No utilizar filtro",
		setSourceTip: "Define la fuente de consulta.",
		setFilterTip: "Define el filtro correctamente.",
		ok: "Aceptar",
		cancel: "Cancelar",
		noFilterTip: "Sin expresión de filtro definida, esta tarea de consulta enumerará todas las entidades de la fuente de datos especificada.",
    relationships: "Relaciones",
    addRelationshipLayer: "Agregar nueva relación",
    relatedTo: "Relacionado con",
    selectOption: "Selecciona...",
    resultItemSorting: "Ordenación de los resultados",
    field: "Campo",
    sortingOrder: "Orden",
    configureFieldsTip: "Configura los campos según los cuales se debe ordenar el resultado de la consulta.",
    setSortingFields: "Configurar campos de ordenación",
    ascending: "Ascendente",
    descending: "Descendente",
    sortBy: "Ordenar por",
    thenBy: "A continuación por",
    addTask: "Agregar tarea",
    noTasksTip: 'No hay ninguna tarea. Haz clic en \"${addTask}\" para comenzar.',
    infoText: "Información",
    filters: "Filtros",
    results: "Resultados",
    optionsText: "Opciones",
    summaryText: "Resumen",
    attributeFilter: "Filtro de atributo",
    attributeFilterTip: "Define las expresiones de atributos que se deben usar en el widget para filtrar la capa de consulta.",
    noExpressionDefinedTip: "No se ha definido ninguna expresión.",
    needInputValuesTip: "Se deben introducir valores en tiempo de ejecución",
    setExpressions: "Definir expresiones",
    spatialFilter: "Filtro espacial",
    spatialFilterTip: "Elige los filtros espaciales utilizados en el widget para limitar los resultados.",
    defaultOption: "Predeterminado",
    useCurrentExtentTip: "Parcial o totalmente dentro de la extensión de mapa actual",
    useDrawGraphicTip: "Parcial o totalmente dentro de la forma dibujada en el mapa",
    useFeaturesTip: "En función de sus ubicaciones con respecto a las entidades de otra capa",
    noSpatialLimitTip: "No limitar espacialmente los resultados",
    drawingTools: "Herramientas de dibujo",
    bufferSettings: "Configuración de la zona de influencia",
    defaultDistance: "Distancia predeterminada",
    bufferDistance: "Distancia de zona de influencia",
    defaultUnit: "Unidad predeterminada",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    availableSpatialRelationships: "Relaciones espaciales disponibles",
    setSpatialRelationships: "Definir relaciones espaciales",
    availability: "Disponibilidad",
    relationship: "Relación",
    label: "Etiqueta",
    intersect: "intersecar",
    contain: "contienen",
    areContainedIn: "están contenidas en",
    cross: "cruz",
    envelopeIntersect: "intersección con el contorno",
    overlap: "superponer",
    areOverlapped: "se superponen",
    touche: "se tocan",
    within: "dentro de",
    areWithin: "están dentro de",
    indexIntersect: "con intersección de índice",
    itemTitle: "Título del elemento",
    displayFields: "Campos de visualización",
    sortingFields: "Campos de ordenación",
    setDisplayFields: "Definir campos de visualización",
    symbol: "Símbolo",
    setSymbol: "Definir símbolo",
    serviceSymbolTip: "Usar símbolos definidos por la capa",
    exportTip: "Mostrar botón de exportación",
    keepResultsTip: "Conservar resultados en el mapa después de cerrar el widget",
    queryRelatedRecords: "Consultar registros relacionados",
    createLayerForTaskTip: "Especifica cómo crea las capas la tarea",
    oneLayerForTaskTip: "Crear solo una capa para esta tarea",
    multipleLayerForTaskTip: "Crear una nueva capa cada vez que se ejecute esta tarea"
  })
);
