define(
	 ({
		queries: "Tareas de consulta",
		addNew: "Agregar nueva",
		setSource: "Establecer",
		setDataSource: "Definir fuente de datos",
		name: "Nombre",
		querySource: "Fuente de datos",
		queryName: "Nombre de tarea",
		queryDefinition: "Definición de filtro",
		resultsSetting: "Configuración de resultados",
		symbolSetting: "Configuración de símbolo",
		resultSettingTip: "Define qué se debe mostrar en los resultados de salida y cómo mostrarlo.",
		resultItemTitle: "Título del elemento de resultado",
		resultItemContent: "Contenido del elemento de resultado",
		fieldsSetTip: "Marca los campos que deseas mostrar. Selecciona un campo para actualizar su alias, su orden y su formato.",
		addField: "Agregar campo",
		visibility: "Visibilidad",
		alias: "Alias",
		specialType: "Tipo especial",
		actions: "Acciones",
		none: "Ninguno",
		link: "Vínculo",
		image: "Imagen",
		noField: "Sin campo",
		operationalLayerTip: "Agregar resultado como capa operativa",
		setLayerSymbolTip: "Establecer el símbolo para los resultados de consulta: ",
		setSelectedSymbolTip: "Establece el símbolo de la entidad seleccionada.",
		notUseFilter: "No utilizar filtro",
		setSourceTip: "Define la fuente de consulta.",
		setFilterTip: "Define el filtro correctamente.",
		ok: "Aceptar",
		cancel: "Cancelar",
		noFilterTip: "Sin expresión de filtro definida, esta tarea de consulta enumerará todas las entidades de la fuente de datos especificada."
  })
);