define(
	 ({
		charts: "Задания диаграммы",
		addNew: "Добавить новый",
		addNewTip: "Добавить новое задание диаграммы",
		name: "Имя",
		set: "Задать",
		setDataSource: "Задать источник данных",
		generalSettingsTip: "Задать источник данных, заголовок и описание диаграмм.",
		chartModeSettingTip: "Выберите способ анализа и отображения данных на диаграммах.",
		detailsSettingTip: "Задайте внешний вид диаграммы, выбрав ее тип, цвет и отображаемые значения.",
		symbolSettingTip: "Задайте отображение данных диаграммы на карте.",
		addFilterTip: "Добавить фильтр к этим данным",
		dataSource: "Источник данных",
		noResults: "Объекты не найдены.",
		chartTitle: "Заголовок диаграммы",
		description: "Описание",
		chartingMode: "Отображение диаграммы",
		featureOption: "Отображать значения по объектам",
		categoryOption: "Отображать значения по категории",
		countOption: "Отображать число объектов по категориям",
		fieldOption: "Отображать атрибутивные значения в виде диаграмм",
		category: "Категория",
		axisLabel: "Подпись категории",
		categoryField: "Поле категории",
		operation: "Операция",
		originalOption: "Использовать исходные значения",
		sumOption: "Сумма",
		averageOption: "Среднее",
		minOption: "Минимум",
		maxOption: "Максимум",
		valueFields: "Поля значений",
		moveUp: "Выше",
		moveDown: "Ниже",
		sortOrder: "Сортировка порядка диаграмм по подписям категорий",
		ascending: "По возрастанию",
		descending: "По убыванию",
		chartType: "Тип диаграммы",
		column: "Гистограмма",
		bar: "Столбчатая диаграмма",
		line: "Линейная диаграмма",
		pie: "Круговая диаграмма",
		chartColor: "Цвет диаграммы",
		showDataLabels: "Показать подписи к данным",
		setSymbol: "Символ выборки",
		setHighLightColor: "Цвет подсветки",
		settings: "Настройки",
		mapInterationOptions: "Опции взаимодействия с картой",
		preview: "Просмотр",
		ok: "OK",
		cancel: "Отмена",
		close: "Закрыть",
		setFilterTip: "Задайте корректный фильтр. ",
		setChartTitleTip: "Введите заголовок диаграммы.",
		setChartTypeTip: "Выберите хотя бы один тип диаграммы.",
		setDataFieldTip: "Выберите хотя бы одно поле значений.",
		setOutputFieldTip: "Задайте выходные поля.",
		count: "Число",
		label: "Надпись",
		horizontalAxis: "Горизонтальная ось",
		verticalAxis: "Вертикальная ось",
		dataLabels: "Надписи данных",
		color: "Цвет",
		colorful: "Цветная",
		monochromatic: "Монохромная"
  })
);