define(
   ({
    _widgetLabel: "Truy vấn",
    executeQueryTip: "Bấm vào một trong các mục tác vụ sau để thực hiện truy vấn.",
    invalidConfig: "Cấu hình không hợp lệ. Vui lòng sử dụng trang thiết lập Truy vấn để tải đúng cấu hình.",
    queryParams: "Tùy chọn",
    parameters: "TÙY CHỌN",
    queries: "TRUY VẤN",
    apply: "ÁP DỤNG",
    queryResults: "Kết quả",
    clear: "Xóa",
    noResults: "Không tìm thấy đối tượng nào.",
    queryError: "Truy vấn thất bại!",
    numberFound: "Số lượng đối tượng được tìm thấy",
    mapExtentTip: "Giới hạn kết quả theo khu vực bản đồ hiện tại.",
    noValue: "Không có giá trị nào",
    and: "và",
    stringOperatorIs: "là", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "không phải là",
    stringOperatorStartsWith: "bắt đầu với",
    stringOperatorEndsWith: "kết thúc với",
    stringOperatorContains: "chứa",
    stringOperatorDoesNotContain: "không chứa",
    stringOperatorIsBlank: "trống",
    stringOperatorIsNotBlank: "không trống",
    dateOperatorIsOn: "vào ngày", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "không vào ngày",
    dateOperatorIsBefore: "trước",
    dateOperatorIsAfter: "sau",
    dateOperatorDays: "ngày",
    dateOperatorWeeks: "tuần", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "tháng",
    dateOperatorInTheLast: "trong ngày cuối",
    dateOperatorNotInTheLast: "không phải cuối cùng",
    dateOperatorIsBetween: "ở giữa",
    dateOperatorIsNotBetween: "không ở giữa",
    dateOperatorIsBlank: "trống",
    dateOperatorIsNotBlank: "không trống",
    numberOperatorIs: "là", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "không phải là",
    numberOperatorIsAtLeast: "tối thiểu",
    numberOperatorIsLessThan: "ít hơn",
    numberOperatorIsAtMost: "tối đa",
    numberOperatorIsGreaterThan: "nhiều hơn",
    numberOperatorIsBetween: "ở giữa",
    numberOperatorIsNotBetween: "không ở giữa",
    numberOperatorIsBlank: "trống",
    numberOperatorIsNotBlank: "không trống",
    operationalLayerTip: "Thêm kết quả như lớp hoạt động",
    queryResult: "Kết quả truy vấn",
    specifyParamsTip: "Chỉ định tham số cho tác vụ này",
    useSpatialFilter: "Sử dụng bộ lọc không gian để giới hạn các đối tượng",
    useCurrentMapExtent: "Chỉ các đối tượng giao cắt với khu vực bản đồ hiện tại",
    drawGraphicOnMap: "Chỉ các đối tượng liên quan đến khu vực do người dùng xác định",
    specifySpatialFilterMsg: "Vui lòng chỉ định bộ lọc không gian cho tác vụ này.",
    clearResults: "Xóa Kết quả",
    operationalTip: 'Nếu chọn tùy chọn này, kết quả sẽ được giữ trên bản đồ cho đến khi nút \"${clearResults}\" được bấm.',
    noneQueryTip: "Không có tác vụ truy vấn nào được cấu hình cho tiện ích này.",
    noPermissionsMsg: "Bạn không có quyền truy cập vào dịch vụ này.",
    attributesFromRelationship: "Thuộc tính từ bảng liên quan",
    tasks: "Tác vụ",
    applySpatialFilterToLimitResults: "Áp dụng bộ lọc không gian để giới hạn kết quả",
    useCurrentExtentTip: "Từng phần hoặc toàn bộ trong kích thước bản đồ hiện tại",
    useDrawGraphicTip: "Từng phần hoặc toàn bộ trong hình dạng đã được vẽ trên bản đồ",
    useFeaturesTip: "Dựa trên vị trí của chúng liên quan đến các đối tượng trong lớp khác",
    noSpatialLimitTip: "Không giới hạn các kết quả theo không gian",
    applySearchDistance: "Áp dụng khoảng cách tìm kiếm",
    spatialRelationship: "Mối quan hệ về Không gian",
    relatedLayer: "Lớp có Liên quan",
    bufferDistance: "Khoảng cách Đệm",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Feet",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    back: "Quay lại",
    execute: "Thực hiện"
  })
);