define(
   ({
    _widgetLabel: "Analiza zdarzenia",
    incident: "Zdarzenie",
    weather: "Pogoda",
    locate_incident: "Zlokalizuj zdarzenie",
    clear_incidents: "Wyczyść zdarzenia",
    reverse_geocoded_address: "Najbliższy adres",
    reverse_geocoded_error: "Not available",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    now: "TERAZ",
    wind: "WIATR",
    SUN: "NIEDZ",
    MON: "PON",
    TUE: "WT",
    WED: "ŚR",
    THU: "CZW",
    FRI: "PT",
    SAT: "SOB",
    defaultTabMsg: "Nie znaleziono żadnych zdarzeń.",
    actionLabel: "Skonfiguruj jako zdarzenie",
    useMapExtent: "Użyj zasięgu bieżącej mapy",
    noFeaturesFound: "Nie odnaleziono obiektów.",
    downloadCSV: "POBIERZ PLIK CSV",
    sum: "SUMA",
    min: "MIN.",
    max: "MAKS.",
    avg: "ŚRED.",
    count: "LICZBA",
    area: "POWIERZCHNIA",
    length: "DŁUGOŚĆ"
  })
);
