define(
	 ({
		queries: "Vaicājuma uzdevumi",
		addNew: "Pievienot jaunu",
    queryLayer: "Vaicājuma slānis",
		setSource: "Kopa",
		setDataSource: "Iestatīt datu avotu",
		name: "Nosaukums",
		querySource: "Datu avots",
		queryName: "Uzdevuma nosaukums",
		queryDefinition: "Filtra definīcija",
		resultsSetting: "Rezultātu iestatījums",
		symbolSetting: "Simbola iestatījums",
		resultSettingTip: "Definējiet parādāmos izvades rezultātus un parādīšanas veidu.",
		resultItemTitle: "Rezultātu vienības virsraksts",
		resultItemContent: "Rezultātu vienību saturs",
		fieldsSetTip: "Atzīmējiet laukus, kuri jārāda. Izvēlieties lauku, lai atjauninātu tā aizstājvārdu, kārtotu vai formatētu to.",
		addField: "Pievienot lauku",
		visibility: "Redzamība",
		alias: "Aizstājvārds",
		specialType: "Īpašais veids",
		actions: "Darbības",
		none: "Nav",
		link: "Saite",
		image: "Attēls",
		noField: "Nav lauka",
		operationalLayerTip: "Pievienot rezultātu kā operacionālo slāni",
		setLayerSymbolTip: "Iestatiet vaicājuma rezultātu simbolu: ",
		setSelectedSymbolTip: "Iestatiet izraudzītā elementa simbolu.",
		notUseFilter: "Neizmantot filtru",
		setSourceTip: "Iestatiet vaicājuma avotu.",
		setFilterTip: "Iestatiet filtru pareizi.",
		ok: "Labi",
		cancel: "Atcelt",
		noFilterTip: "Bez definētas filtra izteiksmes šajā vaicājuma uzdevumā būs norādīti visi elementi norādītajā datu avotā.",
    relationships: "Attiecības",
    addRelationshipLayer: "Pievienot jaunu saistību",
    relatedTo: "Saistīts ar",
    selectOption: "Lūdzu, izvēlieties..",
    resultItemSorting: "Rezultātu vienumu kārtošana",
    field: "Lauks",
    sortingOrder: "Secība",
    configureFieldsTip: "Lūdzu, konfigurējiet laukus, pēc kuriem tiks veikta vaicājuma rezultātu kārtošana.",
    setSortingFields: "Iestatiet kārtošanas laukus",
    ascending: "Pieaugoši",
    descending: "Dilstošā secībā",
    sortBy: "Kārtot pēc",
    thenBy: "Pēc tam pēc",
    addTask: "Pievienot uzdevumu",
    noTasksTip: 'Uzdevumu nav, noklikšķiniet uz \"${addTask}\", lai sāktu darbu.',
    infoText: "Informācija",
    filters: "Filtri",
    results: "Rezultāti",
    optionsText: "Opcijas",
    summaryText: "Kopsavilkums",
    attributeFilter: "Atribūtu filtrs",
    attributeFilterTip: "Definējiet atribūtu izteiksmes izmantošanai logrīkā, lai filtrētu vaicājumu slāni.",
    noExpressionDefinedTip: "Izteiksme netika definēta.",
    needInputValuesTip: "Vērtības jāievada izpildlaikā",
    setExpressions: "Iestatīt izteiksmes",
    spatialFilter: "Telpiskais filtrs",
    spatialFilterTip: "Izvēlieties logrīkā izmantoto(-s) telpisko(-s) filtru(-s), lai ierobežotu rezultātus.",
    defaultOption: "Noklusējums",
    useCurrentExtentTip: "Daļēji vai pilnībā pašreizējā kartes pārklājumā",
    useDrawGraphicTip: "Daļēji vai pilnībā uz kartes uzzīmētajā formā",
    useFeaturesTip: "Pēc to atrašanās vietās attiecībā pret elementiem citā slānī",
    noSpatialLimitTip: "Neierobežot rezultātus telpiski",
    drawingTools: "Zīmēšanas rīki",
    bufferSettings: "Bufera iestatījumi",
    defaultDistance: "Noklusējuma attālums",
    bufferDistance: "Bufera distance",
    defaultUnit: "Noklusējuma vienība",
    miles: "Jūdzes",
    kilometers: "Kilometri",
    feet: "Pēdas",
    meters: "Metri",
    yards: "Jardi",
    nauticalMiles: "Jūras jūdzes",
    availableSpatialRelationships: "Pieejamās telpiskās attiecības",
    setSpatialRelationships: "Iestatīt telpiskās attiecības",
    availability: "Pieejamība",
    relationship: "Attiecības",
    label: "Etiķete",
    intersect: "šķērso",
    contain: "satur",
    areContainedIn: "ietilpst",
    cross: "krustojums",
    envelopeIntersect: "aploksne šķērso",
    overlap: "pārklāj",
    areOverlapped: "ir pārklāts",
    touche: "skar",
    within: "ietver",
    areWithin: "ietverts",
    indexIntersect: "indekss šķērso",
    itemTitle: "Vienuma virsraksts",
    displayFields: "Lauku rādīšana",
    sortingFields: "Lauku kārtošana",
    setDisplayFields: "Iestatīt rādāmos laukus",
    symbol: "Simbols",
    setSymbol: "Iestatīt simbolu",
    serviceSymbolTip: "Izmantot slāņa definētos simbolus",
    exportTip: "Rādīt pogu Eksportēt",
    keepResultsTip: "Pēc logrīka aizvēršanas paturēt rezultātus kartē",
    queryRelatedRecords: "Izpildīt vaicājumu saistītajos ierakstos",
    createLayerForTaskTip: "Norādīt, kā uzdevums izveido slāņus",
    oneLayerForTaskTip: "Šim uzdevumam izveidot tikai vienu slāni",
    multipleLayerForTaskTip: "Izveidot jaunu slāni katru reizi, kad tiek izpildīts šis uzdevums"
  })
);
