define(
	 ({
		queries: "Vaicājumu uzdevumi",
		addNew: "Pievienot jaunu",
		setSource: "Kopa",
		setDataSource: "Iestatīt datu avotu",
		name: "Nosaukums",
		querySource: "Datu avots",
		queryName: "Uzdevuma nosaukums",
		queryDefinition: "Filtra definīcija",
		resultsSetting: "Rezultātu iestatījums",
		symbolSetting: "Simbola iestatījums",
		resultSettingTip: "Definējiet parādāmos izvades rezultātus un parādīšanas veidu.",
		resultItemTitle: "Rezultātu vienības virsraksts",
		resultItemContent: "Rezultātu vienību saturs",
		fieldsSetTip: "Atzīmējiet laukus, kuri jārāda. Izvēlieties lauku, lai atjauninātu tā aizstājvārdu, kārtotu vai formatētu to.",
		addField: "Pievienot lauku",
		visibility: "Redzamība",
		alias: "Aizstājvārds",
		specialType: "Īpašais veids",
		actions: "Darbības",
		none: "Nav",
		link: "Saite",
		image: "Attēls",
		noField: "Nav lauka",
		operationalLayerTip: "Pievienot rezultātu kā operacionālo slāni",
		setLayerSymbolTip: "Iestatiet vaicājuma rezultātu simbolu: ",
		setSelectedSymbolTip: "Iestatiet izraudzītā elementa simbolu.",
		notUseFilter: "Neizmantot filtru",
		setSourceTip: "Iestatiet vaicājuma avotu.",
		setFilterTip: "Iestatiet filtru pareizi.",
		ok: "Labi",
		cancel: "Atcelt",
		noFilterTip: "Bez definētas filtra izteiksmes šajā vaicājuma uzdevumā būs norādīti visi elementi norādītajā datu avotā."
  })
);