define(
   ({
    _widgetLabel: "Geoprocessing",
    execute: "Esegui",
    help: "Guida",
    input: "Input",
    output: "Output",
    executing: "In esecuzione",
    requiredInfo: "obbligatorio.",
    drawnOnMap: "Il risultato viene disegnato nella mappa.",
    clear: "Cancella",
    error: "Errore",
    noToolConfig: "Nessuna attività di geoprocessing preconfigurata disponibile.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Carica file",
    selectFileToUpload: 'Seleziona file...',
    upload: 'Caricamento',
    rasterFormat: 'Formato dati raster',
    noFileSelected: 'Nessun file selezionato.',
    uploadSuccess:'Caricamento file riuscito.',
    url: "URL",
    showLayerContent: "Mostra contenuto layer",
    invalidUrl: "URL feature service non valido",
    Feet: "Piede",
    Yards: "Iarde",
    Miles: "Miglia",
    NauticalMiles: "Miglia nautiche",
    Meter: "Metri",
    Kilometers: "Chilometri",
    urlPlaceholder: "URL insieme di feature"
  })
);
