define(
	 ({
		chartTasks: "Sarcini pentru diagrame",
		addNew: "Adăugare nou",
		addNewTip: "Adăugare sarcină nouă pentru diagrame",
		name: "Nume",
		set: "Setare",
		setDataSource: "Setare sursă de date",
		generalSettingsTip: "Setaţi sursa de date, titlul şi descrierea pentru diagrame.",
		chartModeSettingTip: "Selectaţi un mod de analiza şi afişa date drept diagrame.",
		detailsSettingTip: "Setaţi aspectul diagramelor specificând tipurile şi culorile şi ce valori să fie incluse în ele:",
		symbolSettingTip: "Setaţi afişarea pe hartă a datelor din diagramă.",
		addFilterTip: "Adăugare filtru la aceste date",
		dataSource: "Sursă date",
		noResults: "Nu a fost găsit niciun obiect spaţial.",
		chartTitle: "Titlu diagramă",
		description: "Descriere",
		chartingMode: "Afişare diagramă",
		featureOption: "Afişare valori pentru fiecare obiecte spaţial",
		categoryOption: "Afişare valori pe categorii",
		countOption: "Afişare număr de obiecte spaţiale pe categorii",
		fieldOption: "Afişare valori de atribute sub formă de diagramă",
		category: "Categorie",
		axisLabel: "Etichetă categorie",
		categoryField: "Câmp categorie",
		operation: "Operaţie",
		originalOption: "Utilizare valori originale",
		sumOption: "Sumă",
		averageOption: "Medie",
		minOption: "Minim",
		maxOption: "Maxim",
		valueFields: "Câmpuri pentru valori",
		moveUp: "Deplasare în sus",
		moveDown: "Deplasare în jos",
		sortOrder: "Sortare ordine diagrame pe baza etichetelor de categorii",
		ascending: "Ascendent",
		descending: "Descendent",
		chartType: "Tip diagramă",
		column: "Diagramă cu coloane",
		bar: "Diagramă cu bare",
		line: "Diagramă liniară",
		pie: "Diagramă circulară",
		chartColor: "Culoare diagramă",
		showDataLabels: "Afişare etichete pentru date",
		setSymbol: "Simbol pentru selectare",
		setHighLightColor: "Culoare de evidenţiere",
		settings: "Setări",
		mapInterationOptions: "Opţiuni pentru interacţiunea cu harta",
		preview: "Previzualizare",
		ok: "OK",
		cancel: "Anulare",
		close: "Închidere",
		setFilterTip: "Setaţi filtrul corect. ",
		setChartTitleTip: "Setaţi titlul diagramei.",
		setChartTypeTip: "Selectaţi cel puţin un tip de diagramă.",
		setDataFieldTip: "Selectaţi cel puţin un câmp de valori.",
		setOutputFieldTip: "Setaţi câmpuri de ieşire.",
		count: "Număr",
		label: "Etichetă",
		horizontalAxis: "Axă orizontală",
		verticalAxis: "Axă verticală",
		dataLabels: "Etichete date",
		color: "Culoare",
		colorful: "Color",
		monochromatic: "Monocrom",
    noTaskTip: "Faceţi clic pe Adăugare nou pentru a adăuga o activitate pentru diagrame",
    info: "Informaţii",
    charts: "Diagrame",
    options: "Opţiuni",
    taskName: "Nume operaţie",
    summary: "Rezumat",
    resultDescription: "Descriere rezultat",
    spatialFilterTip: "Alegeţi filtrele spaţiale utilizate în widget pentru limitarea rezultatelor.",
    defaultOption: "Implicit",
    useCurrentExtentTip: "Parţial sau complet în cadrul extinderii curente de hartă",
    useDrawGraphicTip: "Parţial sau complet în cadrul formei trasate pe hartă",
    useFeaturesTip: "În baza locaţiilor, în raport cu obiectele spaţiale din alt strat tematic",
    noSpatialLimitTip: "Nu limitaţi spaţial rezultatele",
    drawingTools: "Instrumente de trasare",
    bufferSettings: "Setări buffer",
    defaultDistance: "Distanţă implicită",
    bufferDistance: "Distanţă buffer",
    defaultUnit: "Unitate implicită",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    availableSpatialRelationships: "Relaţie spaţială disponibilă",
    setSpatialRelationships: "Setare relaţie spaţială",
    availability: "Disponibilitate",
    relationship: "Relaţie",
    actions: "Acţiuni",
    intersect: "intersectare",
    contain: "conţine",
    areContainedIn: "sunt conţinute de",
    cross: "cruce",
    envelopeIntersect: "intersectare plic",
    overlap: "suprapunere",
    areOverlapped: "sunt suprapuse",
    touche: "atins",
    within: "în",
    areWithin: "sunt la",
    indexIntersect: "intersectare index"
  })
);