define(
	 ({
		charts: "Sarcini pentru diagrame",
		addNew: "Adăugare nou",
		addNewTip: "Adăugare sarcină nouă pentru diagrame",
		name: "Nume",
		set: "Setare",
		setDataSource: "Setare sursă de date",
		generalSettingsTip: "Setaţi sursa de date, titlul şi descrierea pentru diagrame.",
		chartModeSettingTip: "Selectaţi un mod de analiza şi afişa date drept diagrame.",
		detailsSettingTip: "Setaţi aspectul diagramelor specificând tipurile şi culorile şi ce valori să fie incluse în ele.",
		symbolSettingTip: "Setaţi afişarea pe hartă a datelor din diagramă.",
		addFilterTip: "Adăugare filtru la aceste date",
		dataSource: "Sursă date",
		noResults: "Nu a fost găsit niciun obiect spaţial.",
		chartTitle: "Titlu diagramă",
		description: "Descriere",
		chartingMode: "Afişare diagramă",
		featureOption: "Afişare valori pentru fiecare obiecte spaţial",
		categoryOption: "Afişare valori pe categorii",
		countOption: "Afişare număr de obiecte spaţiale pe categorii",
		fieldOption: "Afişare valori de atribute sub formă de diagramă",
		category: "Categorie",
		axisLabel: "Etichetă categorie",
		categoryField: "Câmp categorie",
		operation: "Operaţie",
		originalOption: "Utilizare valori originale",
		sumOption: "Sumă",
		averageOption: "Medie",
		minOption: "Minim",
		maxOption: "Maxim",
		valueFields: "Câmpuri pentru valori",
		moveUp: "Deplasare în sus",
		moveDown: "Deplasare în jos",
		sortOrder: "Sortare ordine diagrame pe baza etichetelor de categorii",
		ascending: "Ascendent",
		descending: "Descendent",
		chartType: "Tip diagramă",
		column: "Diagramă cu coloane",
		bar: "Diagramă cu bare",
		line: "Diagramă liniară",
		pie: "Diagramă circulară",
		chartColor: "Culoare diagramă",
		showDataLabels: "Afişare etichete pentru date",
		setSymbol: "Simbol pentru selectare",
		setHighLightColor: "Culoare de evidenţiere",
		settings: "Setări",
		mapInterationOptions: "Opţiuni pentru interacţiunea cu harta",
		preview: "Previzualizare",
		ok: "OK",
		cancel: "Anulare",
		close: "Închidere",
		setFilterTip: "Setaţi filtrul corect. ",
		setChartTitleTip: "Setaţi titlul diagramei.",
		setChartTypeTip: "Selectaţi cel puţin un tip de diagramă.",
		setDataFieldTip: "Selectaţi cel puţin un câmp de valori.",
		setOutputFieldTip: "Setaţi câmpuri de ieşire.",
		count: "Număr",
		label: "Etichetă",
		horizontalAxis: "Axă orizontală",
		verticalAxis: "Axă verticală",
		dataLabels: "Etichete date",
		color: "Culoare",
		colorful: "Color",
		monochromatic: "Monocrom"
  })
);