define(
   ({
    _widgetLabel: "Diagramm",
    executeChartTip: "Diagrammi loomiseks kasutage mõnda järgmist toimingut.",
    invalidConfig: "Sobimatu konfiguratsioon",
    noneChartTip: "Selle vidina jaoks pole konfigureeritud diagrammi toimingut.",
    chartParams: "Valikud",
    charts: "DIAGRAMMID",
    apply: "RAKENDA",
    useSpatialFilter: "Kasuta objektide piiramiseks ruumifiltrit",
    useCurrentMapExtent: "Vaid praeguses kaardiulatuses lõikuvad objektid",
    drawGraphicOnMap: "Vaid kasutaja poolt määratletud alas lõikuvad objektid.",
    chartResults: "Diagrammi tulemused",
    clearResults: "Puhasta tulemused",
    noPermissionsMsg: "Teil puudub juurdepääs sellele teenusele.",
    specifySpatialFilterMsg: "Määrake selle ülesande jaoks ruumifilter.",
    queryError: "Päring nurjus.",
    noResults: "Objekte ei leitud.",
    category: "Kategooria",
    count: "Loend",
    label: "Märgis",
    horizontalAxis: "Horisontaaltelg",
    verticalAxis: "Vertikaaltelg",
    dataLabels: "Andmete märgised",
    color: "Värv",
    colorful: "Värviline",
    monochromatic: "Ühevärviline",
    tasks: "Toimingud",
    results: "Tulemused",
    applySpatialFilterToLimitResults: "Rakenda tulemuste piiramiseks ruumifilter",
    useCurrentExtentTip: "Osaliselt või täielikult praeguses kaardi kuvaulatuses",
    useDrawGraphicTip: "Osaliselt või täielikult kaardile joonistatud kujundis",
    useFeaturesTip: "Vastavalt nende asukohale teise kihi objektide suhtes",
    noSpatialLimitTip: "Ära piira tulemusi ruumiliselt",
    applySearchDistance: "Rakenda otsingu vahemaa",
    spatialRelationship: "Ruumiline seos",
    relatedLayer: "Seotud kiht",
    clear: "Eemalda",
    bufferDistance: "Puhvri ulatus",
    miles: "Miilid",
    kilometers: "Kilomeetrid",
    feet: "Jalad",
    meters: "Meetrid",
    yards: "Jardid",
    nauticalMiles: "Meremiilid",
    back: "Tagasi",
    execute: "Käivita"
  })
);