define(
	 ({
		chartTasks: "Diagramm-Tasks",
		addNew: "Neu hinzufügen",
		addNewTip: "Neuen Diagramm-Task hinzufügen",
		name: "Name",
		set: "Festlegen",
		setDataSource: "Datenquelle festlegen",
		generalSettingsTip: "Legen Sie die Datenquelle, den Titel und die Beschreibung für Diagramme fest.",
		chartModeSettingTip: "Legen Sie fest, wie Daten als Diagramme analysiert und angezeigt werden sollen.",
		detailsSettingTip: "Legen Sie das Aussehen des Diagramms durch Angabe des Typs, der Farbe und der als Diagramm darzustellenden Werte fest:",
		symbolSettingTip: "Legen Sie die Kartenanzeige für Daten fest, die als Diagramm dargestellt werden.",
		addFilterTip: "Filter zu diesen Daten hinzufügen",
		dataSource: "Datenquelle",
		noResults: "Kein Feature gefunden.",
		chartTitle: "Diagrammtitel",
		description: "Beschreibung",
		chartingMode: "Diagrammanzeige",
		featureOption: "Werte auf Feature-Ebene anzeigen",
		categoryOption: "Werte nach Kategorie anzeigen",
		countOption: "Feature-Anzahl nach Kategorie anzeigen",
		fieldOption: "Attributwerte als Diagramme anzeigen",
		category: "Kategorie",
		axisLabel: "Kategoriebeschriftung",
		categoryField: "Kategoriefeld",
		operation: "Operation",
		originalOption: "Ursprüngliche Werte verwenden",
		sumOption: "Summe",
		averageOption: "Durchschnitt",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Wertefelder",
		moveUp: "Nach oben verschieben",
		moveDown: "Nach unten verschieben",
		sortOrder: "Diagrammreihenfolge über Kategoriebeschriftungen sortieren",
		ascending: "Aufsteigend",
		descending: "Absteigend",
		chartType: "Diagrammtyp",
		column: "Spaltendiagramm",
		bar: "Balkendiagramm",
		line: "Liniendiagramm",
		pie: "Kreisdiagramm",
		chartColor: "Diagrammfarbe",
		showDataLabels: "Datenbeschriftungen anzeigen",
		setSymbol: "Auswahlsymbol",
		setHighLightColor: "Hervorhebungsfarbe",
		settings: "Einstellungen",
		mapInterationOptions: "Optionen für die Karteninteraktion",
		preview: "Vorschau",
		ok: "OK",
		cancel: "Abbrechen",
		close: "Schließen",
		setFilterTip: "Legen Sie den Filter ordnungsgemäß fest. ",
		setChartTitleTip: "Legen Sie den Diagrammtitel fest.",
		setChartTypeTip: "Wählen Sie mindestens einen Diagrammtyp aus.",
		setDataFieldTip: "Wählen Sie mindestens ein Wertefeld aus.",
		setOutputFieldTip: "Legen Sie Ausgabefelder fest.",
		count: "Anzahl",
		label: "Beschriftung",
		horizontalAxis: "Horizontale Achse",
		verticalAxis: "Vertikale Achse",
		dataLabels: "Datenbeschriftungen",
		color: "Farbe",
		colorful: "Farbig",
		monochromatic: "Einfarbig",
    noTaskTip: "Klicken Sie auf \"Neue hinzufügen\", um einen Diagramm-Task hinzuzufügen",
    info: "Info",
    charts: "Diagramme",
    options: "Optionen",
    taskName: "Task-Name",
    summary: "Zusammenfassung",
    resultDescription: "Beschreibung des Ergebnisses",
    spatialFilterTip: "Wählen Sie den/die räumlichen Filter zum Begrenzen der Ergebnisse in Widgets aus.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Teilweise oder vollständig innerhalb der aktuellen Kartenausdehnung",
    useDrawGraphicTip: "Teilweise oder vollständig innerhalb des auf der Karte dargestellten Shapes",
    useFeaturesTip: "Basierend auf deren Positionen relativ zu Features in einem anderen Layer",
    noSpatialLimitTip: "Ergebnisse nicht räumlich beschränken",
    drawingTools: "Zeichenwerkzeuge",
    bufferSettings: "Puffer-Einstellungen",
    defaultDistance: "Standardentfernung",
    bufferDistance: "Pufferabstand",
    defaultUnit: "Standardeinheit",
    miles: "Meilen",
    kilometers: "Kilometer",
    feet: "Fuß",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Seemeilen",
    availableSpatialRelationships: "Verfügbare räumliche Beziehungen",
    setSpatialRelationships: "Räumliche Beziehungen festlegen",
    availability: "Verfügbarkeit",
    relationship: "Beziehung",
    actions: "Aktionen",
    intersect: "überschneiden",
    contain: "enthalten",
    areContainedIn: "sind enthalten in",
    cross: "Kreuz",
    envelopeIntersect: "Envelope-Überschneidung",
    overlap: "Überlappung",
    areOverlapped: "werden überlappt",
    touche: "berühren",
    within: "innerhalb",
    areWithin: "enthalten sind in",
    indexIntersect: "Index-Überschneidung"
  })
);