define(
   ({
    _widgetLabel: "Consulta",
    executeQueryTip: "Clique em um dos seguintes itens da tarefa para executar a consulta.",
    invalidConfig: "Configuração inválida. Utilize a página de configuração da Consulta para obter a configuração correta.",
    queryParams: "Opções",
    parameters: "OPÇÕES",
    queries: "CONSULTAS",
    apply: "APLICAR",
    queryResults: "Resultados",
    clear: "Limpar",
    noResults: "Nenhuma feição encontrada.",
    queryError: "Falha ao consultar !",
    numberFound: "Número de feições encontradas",
    mapExtentTip: "Limite os resultados à extensão de mapa atual.",
    noValue: "Nenhum valor",
    and: "e",
    stringOperatorIs: "é", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "não é",
    stringOperatorStartsWith: "inicia com",
    stringOperatorEndsWith: "finaliza com",
    stringOperatorContains: "contém",
    stringOperatorDoesNotContain: "não contém",
    stringOperatorIsBlank: "está em branco",
    stringOperatorIsNotBlank: "não está em branco",
    dateOperatorIsOn: "está em", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "não está em",
    dateOperatorIsBefore: "está antes",
    dateOperatorIsAfter: "está após",
    dateOperatorDays: "dias",
    dateOperatorWeeks: "semanas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "meses",
    dateOperatorInTheLast: "no último",
    dateOperatorNotInTheLast: "não no último",
    dateOperatorIsBetween: "está entre",
    dateOperatorIsNotBetween: "não está entre",
    dateOperatorIsBlank: "está em branco",
    dateOperatorIsNotBlank: "não está em branco",
    numberOperatorIs: "é", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "não é",
    numberOperatorIsAtLeast: "é pelo menos",
    numberOperatorIsLessThan: "é menor que",
    numberOperatorIsAtMost: "é na maioria",
    numberOperatorIsGreaterThan: "é maior que",
    numberOperatorIsBetween: "está entre",
    numberOperatorIsNotBetween: "não está entre",
    numberOperatorIsBlank: "está em branco",
    numberOperatorIsNotBlank: "não está em branco",
    operationalLayerTip: "Adicionar resultado como camada operacional",
    queryResult: "Resultado da Consulta",
    specifyParamsTip: "Especificar parâmetros para esta tarefa",
    useSpatialFilter: "Utilizar filtro espacial para limitar feições",
    useCurrentMapExtent: "Somente feições tocando a extensão de mapa atual",
    drawGraphicOnMap: "Somente feições tocando a área definida do usuário",
    specifySpatialFilterMsg: "Especifique o filtro espacial para esta tarefa.",
    clearResults: "Limpar Resultados",
    operationalTip: 'Com esta opção marcada, os resultados serão mantidos no mapa até que o botão \"${clearResults}\" seja clicado.',
    noneQueryTip: "Nenhuma tarefa de consulta pré-configurada disponível.",
    noPermissionsMsg: "Você não tem permissões para acessar este serviço."
  })
);