define(
   ({
    _widgetLabel: "Analiză incident",
    incident: "Incident",
    weather: "Vreme",
    locate_incident: "Localizare incident",
    clear_incidents: "Golire incidente",
    reverse_geocoded_address: "Cea mai apropiată adresă",
    reverse_geocoded_error: "Indisponibil",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    now: "ACUM",
    wind: "VÂNT",
    SUN: "DUM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MIE",
    THU: "JOI",
    FRI: "VIN",
    SAT: "SÂM",
    defaultTabMsg: "Niciun incident identificat.",
    actionLabel: "Setare ca incident",
    useMapExtent: "Utilizare extindere curentă a hărţii",
    noFeaturesFound: "Nu a fost găsit niciun obiect spaţial.",
    downloadCSV: "DESCĂRCARE CSV",
    sum: "SUMĂ",
    min: "MIN.",
    max: "MAX",
    avg: "MED.",
    count: "NUMĂR",
    area: "SUPRAFAŢĂ",
    length: "LUNGIME"
  })
);
