define(
   ({
    layerSelect: "Selecionar a Camada de Imagem",
    displayMeasureResultInPopup: "Exibir resultados da medida em um pop-up",
    angularUnitSelect: "Unidade Angular Padrão",
    linearUnitSelect: "Unidade Linear Padrão",
    areaUnitSelect: "Unidade de Área Padrão",
    displayOperationSelect: "Selecionar operações de medida",
    errorSectionMeasage: "Nenhuma das camadas suporta recursos de medição.",
    unitLabel: {
      esriInches: "Polegadas",
      esriFeet: "Pés",
      esriYards: "Jardas",
      esriMiles: "Milhas",
      esriNauticalMiles: "Milhas Náuticas",
      esriMillimeters: "Milímetros",
      esriCentimeters: "Centímetros",
      esriDecimeters: "Decímetros",
      esriMeters: "Metros",
      esriKilometers: "Quilômetros",
      esriDURadians: "Radianos",
      esriDUDecimalDegrees: "Graus",
      esriSquareInches: "Polegadas Quadradas",
      esriSquareFeet: "Pés Quadrados",
      esriSquareYards: "Jardas Quadradas",
      esriAcres: "Acres",
      esriSquareMiles: "Milhas Quadradas",
      esriSquareMillimeters: "Milímetros Quadrados",
      esriSquareCentimeters: "Centímetros Quadrados",
      esriSquareDecimeters: "Decímetros Quadrados",
      esriSquareMeters: "Metros Quadrados",
      esriAres: "Ares",
      esriHectares: "Hectares",
      esriSquareKilometers: "Quilômetros Quadrados"
    },
    operationLabel: {
      esriMensurationPoint: "Ponto",
      esriMensurationDistanceAndAngle: "Distância e Ângulo",
      esriMensurationAreaAndPerimeter: "Área e Perímetro",
      esriMensurationHeightFromBaseAndTop: "Base para Topo",
      esriMensurationHeightFromBaseAndTopShadow: "Base para Sombra Topo",
      esriMensurationHeightFromTopAndTopShadow: "Topo para Sombra Topo",
      esriMensurationCentroid: "Centróide",
      esriMensurationPoint3D: "Ponto (3D)",
      esriMensurationDistanceAndAngle3D: "Distância e Ângulo (3D)",
      esriMensurationAreaAndPerimeter3D: "Área e Perímetro (3D)",
      esriMensurationCentroid3D: "Centróide (3D)"
    }
  })
);