define(
	 ({
		queries: "Sorgu Görevleri",
		addNew: "Yeni Ekle",
    queryLayer: "Sorgu Katmanı",
		setSource: "Ayarla",
		setDataSource: "Veri Kaynağını Belirt",
		name: "Ad",
		querySource: "Veri Kaynağı",
		queryName: "Görev Adı",
		queryDefinition: "Filtre Tanımı",
		resultsSetting: "Sonuçlar Ayarı",
		symbolSetting: "Sembol Ayarı",
		resultSettingTip: "Hangi çıktı sonuçlarının nasıl görüntüleneceğini tanımlayın.",
		resultItemTitle: "Sonuç Öğesi Başlığı",
		resultItemContent: "Sonuç Öğesi İçerikleri",
		fieldsSetTip: "Görüntülemek istediğiniz alanları denetleyin. Takma adı güncellemek, sıralamak ve biçimlendirmek için bir alan seçin.",
		addField: "Alan Ekle",
		visibility: "Görünürlük",
		alias: "Takma Ad",
		specialType: "Özel Tür",
		actions: "İşlemler",
		none: "Hiçbiri",
		link: "Bağlantı",
		image: "Görüntü",
		noField: "Alan yok",
		operationalLayerTip: "Sonucu işlem katmanı olarak ekle",
		setLayerSymbolTip: "Sorgu sonuçları için simgeyi ayarla: ",
		setSelectedSymbolTip: "Seçilen detayın simgesini ayarlayın.",
		notUseFilter: "Filtre kullanma",
		setSourceTip: "Sorgu kaynağını belirtin.",
		setFilterTip: "Filtreyi düzgün şekilde ayarlayın.",
		ok: "Tamam",
		cancel: "İptal",
		noFilterTip: "Tanımlı filtre ifadesi olmadan, bu sorgu görevi belirtilen veri kaynağındaki tüm detayları listeleyecektir.",
    relationships: "İlişkiler",
    addRelationshipLayer: "Yeni İlişki Ekle",
    relatedTo: "İlgili",
    selectOption: "Seçim yapın..",
    resultItemSorting: "Sonuç Öğesi Sıralama",
    field: "Alan",
    sortingOrder: "Sırala",
    configureFieldsTip: "Sorgu sonucu için sıralama ölçütü olarak kullanılacak alanları yapılandırın.",
    setSortingFields: "Sıralama Alanlarını Ayarla",
    ascending: "Artan",
    descending: "Azalan",
    sortBy: "Şuna göre sırala:",
    thenBy: "Ardından şuna göre",
    addTask: "Görev ekle",
    noTasksTip: 'Görev yok, başlamak için \"${addTask}\" öğesine tıklayın!',
    infoText: "Bilgi",
    filters: "Filtreler",
    results: "Sonuçlar",
    optionsText: "Seçenekler",
    summaryText: "Özet",
    attributeFilter: "Öznitelik Filtresi",
    attributeFilterTip: "Sorgu katmanını filtrelemek için araç içinde kullanılacak öznitelik ifadelerini tanımlayın.",
    noExpressionDefinedTip: "Tanımlı ifade yok.",
    needInputValuesTip: "Çalışma zamanında değer girilmesi gerekli",
    setExpressions: "İfade Ayarla",
    spatialFilter: "Mekansal Süzgeç",
    spatialFilterTip: "Sonuçları daraltmak için araçta kullanılacak mekansal filtreleri seçin.",
    defaultOption: "Varsayılan",
    useCurrentExtentTip: "Kısmen veya tamamen geçerli harita yayılımında",
    useDrawGraphicTip: "Kısmen veya tamamen haritada çizilen şekil içinde",
    useFeaturesTip: "Başka bir katmandaki detaylara göre konumlarına dayanarak",
    noSpatialLimitTip: "Sonuçları mekansal olarak sınırlama",
    drawingTools: "Çizim araçları",
    bufferSettings: "Tampon Ayarları",
    defaultDistance: "Varsayılan Mesafe",
    bufferDistance: "Tampon Mesafesi",
    defaultUnit: "Varsayılan Birim",
    miles: "Mil",
    kilometers: "Kilometre",
    feet: "Fit",
    meters: "Metre",
    yards: "Yarda",
    nauticalMiles: "Deniz Mili",
    availableSpatialRelationships: "Kullanılabilir Mekansal İlişkiler",
    setSpatialRelationships: "Mekansal İlişki Ayarla",
    availability: "Yararlanırlık",
    relationship: "İlişki",
    label: "Etiket",
    intersect: "kesişen",
    contain: "içeren",
    areContainedIn: "içinde bulunuyor",
    cross: "çapraz",
    envelopeIntersect: "zarf kesişmesi",
    overlap: "örtüşme",
    areOverlapped: "örtüşüyor",
    touche: "dokunma",
    within: "birliktelik",
    areWithin: "birlikte",
    indexIntersect: "dizin kesişmesi",
    itemTitle: "Öğe Başlığı",
    displayFields: "Görüntüleme Alanları",
    sortingFields: "Sıralama Alanları",
    setDisplayFields: "Görüntüleme Alanlarını Ayarla",
    symbol: "Sembol",
    setSymbol: "Simgeyi ayarla",
    serviceSymbolTip: "Katman tarafından tanımlanan simgeleri kullan",
    exportTip: "Dışa Aktar düğmesini göster",
    keepResultsTip: "Araç kapatıldıktan sonra sonuçları haritada sakla",
    queryRelatedRecords: "Sorgu ile ilgili kayıtlar",
    createLayerForTaskTip: "Görevin nasıl katman oluşturduğunu belirt",
    oneLayerForTaskTip: "Bu görev için yalnızca bir katman oluştur",
    multipleLayerForTaskTip: "Bu görev her gerçekleştirildiğinde yeni bir katman oluştur"
  })
);
