define(
	 ({
		queries: "Sorgu Görevleri",
		addNew: "Yeni Ekle",
		setSource: "Ayarla",
		setDataSource: "Veri Kaynağını Belirt",
		name: "Ad",
		querySource: "Veri Kaynağı",
		queryName: "Görev Adı",
		queryDefinition: "Filtre Tanımı",
		resultsSetting: "Sonuçlar Ayarı",
		symbolSetting: "Sembol Ayarı",
		resultSettingTip: "Hangi çıktı sonuçlarının nasıl görüntüleneceğini tanımlayın.",
		resultItemTitle: "Sonuç Öğesi Başlığı",
		resultItemContent: "Sonuç Öğesi İçerikleri",
		fieldsSetTip: "Görüntülemek istediğiniz alanları denetleyin. Takma adı güncellemek, sıralamak ve biçimlendirmek için bir alan seçin.",
		addField: "Alan Ekle",
		visibility: "Görünürlük",
		alias: "Takma Ad",
		specialType: "Özel Tür",
		actions: "İşlemler",
		none: "Hiçbiri",
		link: "Bağlantı",
		image: "Görüntü",
		noField: "Alan yok",
		operationalLayerTip: "Sonucu işlem katmanı olarak ekle",
		setLayerSymbolTip: "Sorgu sonuçları için simgeyi ayarla: ",
		setSelectedSymbolTip: "Seçilen detayın simgesini ayarlayın.",
		notUseFilter: "Filtre kullanma",
		setSourceTip: "Sorgu kaynağını belirtin.",
		setFilterTip: "Filtreyi düzgün şekilde ayarlayın.",
		ok: "Tamam",
		cancel: "İptal",
		noFilterTip: "Tanımlı filtre ifadesi olmadan, bu sorgu görevi belirtilen veri kaynağındaki tüm detayları listeleyecektir."
  })
);