define(
   ({
    _widgetLabel: "Geoprocessing",
    execute: "בצע",
    help: "עזרה",
    input: "קלט",
    output: "פלט",
    executing: "מבצע",
    requiredInfo: "נדרש.",
    drawnOnMap: "התוצאה מוצגת במפה.",
    clear: "נקה",
    error: "שגיאה",
    noToolConfig: "אין משימת עיבוד נתונים זמינה שהוגדרה מראש.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "טעינת קובץ",
    selectFileToUpload: 'בחר קובץ...',
    upload: 'העלאה',
    rasterFormat: 'פורמט נתוני רסטר',
    noFileSelected: 'לא נבחר קובץ!',
    uploadSuccess:'הקובץ נטען בהצלחה!',
    url: "URL",
    showLayerContent: "הצג תוכן שכבה",
    invalidUrl: "כתובת ה-URL של שירות הישויות לא חוקית",
    Feet: "רגל",
    Yards: "יארד",
    Miles: "מיילים",
    NauticalMiles: "מיילים ימיים",
    Meter: "מטרים",
    Kilometers: "קילומטרים",
    urlPlaceholder: "URL של סט ישויות"
  })
);
