define(
   ({
    _widgetLabel: "Ερώτημα",
    executeQueryTip: "Κάντε κλικ σε ένα από τα παρακάτω αντικείμενα για να εκτελέσετε το αντίστοιχο ερώτημα.",
    invalidConfig: "Μη έγκυρη διαμόρφωση. Χρησιμοποιήστε τη σελίδα ρυθμίσεων των ερωτημάτων για να δείτε τη σωστή διαμόρφωση.",
    queryParams: "Επιλογές",
    parameters: "ΕΠΙΛΟΓΕΣ",
    queries: "ΕΡΩΤΗΜΑΤΑ",
    apply: "ΕΦΑΡΜΟΓΗ",
    queryResults: "Αποτελέσματα",
    clear: "Απαλοιφή",
    noResults: "Δεν εντοπίστηκε κανένα στοιχείο.",
    queryError: "Το ερώτημα απέτυχε!",
    numberFound: "Αριθμός στοιχείων που εντοπίστηκαν",
    mapExtentTip: "Περιορισμός των αποτελεσμάτων στην τρέχουσα περιοχή χάρτη.",
    noValue: "Χωρίς τιμή",
    and: "και",
    stringOperatorIs: "είναι", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "δεν είναι",
    stringOperatorStartsWith: "ξεκινάει με",
    stringOperatorEndsWith: "τελειώνει με",
    stringOperatorContains: "περιέχει",
    stringOperatorDoesNotContain: "δεν περιέχει",
    stringOperatorIsBlank: "είναι κενό",
    stringOperatorIsNotBlank: "δεν είναι κενό",
    dateOperatorIsOn: "είναι στις", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "δεν είναι στις",
    dateOperatorIsBefore: "είναι πριν από",
    dateOperatorIsAfter: "είναι μετά από",
    dateOperatorDays: "ημέρες",
    dateOperatorWeeks: "εβδομάδες", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "μήνες",
    dateOperatorInTheLast: "τους τελευταίους/τις τελευταίες",
    dateOperatorNotInTheLast: "όχι τους τελευταίους/τις τελευταίες",
    dateOperatorIsBetween: "είναι μεταξύ",
    dateOperatorIsNotBetween: "δεν είναι μεταξύ",
    dateOperatorIsBlank: "είναι κενό",
    dateOperatorIsNotBlank: "δεν είναι κενό",
    numberOperatorIs: "είναι", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "δεν είναι",
    numberOperatorIsAtLeast: "είναι τουλάχιστον",
    numberOperatorIsLessThan: "είναι λιγότερο από",
    numberOperatorIsAtMost: "είναι το πολύ",
    numberOperatorIsGreaterThan: "είναι μεγαλύτερο από",
    numberOperatorIsBetween: "είναι μεταξύ",
    numberOperatorIsNotBetween: "δεν είναι μεταξύ",
    numberOperatorIsBlank: "είναι κενό",
    numberOperatorIsNotBlank: "δεν είναι κενό",
    operationalLayerTip: "Προσθήκη αποτελέσματος ως επιχειρησιακό επίπεδο",
    queryResult: "Αποτέλεσμα ερωτήματος",
    specifyParamsTip: "Ορισμός παραμέτρων για αυτήν την εργασία",
    useSpatialFilter: "Χρήση χωρικού φίλτρου για τον περιορισμό των στοιχείων",
    useCurrentMapExtent: "Μόνο στοιχεία που τέμνουν την τρέχουσα περιοχή χάρτη",
    drawGraphicOnMap: "Μόνο στοιχεία που τέμνουν την περιοχή η οποία έχει οριστεί από το χρήστη",
    specifySpatialFilterMsg: "Ορίστε χωρικό φίλτρο.",
    clearResults: "Απαλοιφή αποτελεσμάτων",
    operationalTip: 'Με αυτή την επιλογή, τα αποτελέσματα θα διατηρηθούν στο χάρτη μέχρι να γίνει κλικ στο κουμπί \"${clearResults}\".',
    noneQueryTip: "Δεν έχουν καθοριστεί ερωτήματα για αυτό το widget.",
    noPermissionsMsg: "Δεν έχετε άδεια πρόσβασης σε αυτή την υπηρεσία.",
    attributesFromRelationship: "Γνωρίσματα από συσχετισμένο πίνακα",
    tasks: "Εργασίες",
    applySpatialFilterToLimitResults: "Εφαρμόστε ένα χωρικό φίλτρο για να περιορίσετε τα αποτελέσματα",
    useCurrentExtentTip: "Μερικώς ή πλήρως εντός της τρέχουσας έκτασης χάρτη",
    useDrawGraphicTip: "Μερικώς ή πλήρως εντός του σχήματος που έχει σχεδιαστεί στο χάρτη",
    useFeaturesTip: "Βάσει των τοποθεσιών που είναι σχετικές με στοιχεία άλλου θεματικού επιπέδου",
    noSpatialLimitTip: "Χωρίς χωρικό περιορισμό αποτελεσμάτων",
    applySearchDistance: "Εφαρμογή απόστασης αναζήτησης",
    spatialRelationship: "Χωρική συσχέτιση",
    relatedLayer: "Συσχετιζόμενο θεματικό επίπεδο",
    bufferDistance: "Απόσταση ζώνης",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    back: "Πίσω",
    execute: "Εκτέλεση"
  })
);