define(
   ({
    _widgetLabel: "Raportoi kohde",
    select: "Valitse",
    draw: "Piirrä",
    chooseALayer: "Valitse karttataso",
    clickAFeature: "Valitse kohde napsauttamalla sitä kartassa.",
    loadingFeatures: "Noudetaan valitun kohteen tietoja...",
    errorTitle: "Virhe",
    errorIdentify: "Kohteiden tunnistusvirhe. Lisätietoja on konsolin lokissa.",
    infoWindowTitle: "Yksityiskohdat",
    layerLabel: "Karttatason nimi",
    reviewStatusLabel: "Tarkista tila",
    selectReviewStatusAdd: "Lisää kohde",
    selectReviewStatusDelete: "Poista kohde",
    selectReviewStatusMove: "Siirrä kohdetta",
    selectReviewStatusReshape: "Muotoile kohde uudelleen",
    drawReviewStatusMissing: "Kohteita puuttuu",
    drawReviewStatusPosition: "Sijaintivirhe",
    drawReviewStatusShape: "Muotovirhe",
    drawReviewStatusAttribute: "Määritevirhe",
    notesLabel: "Huomautukset",
    severityLabel: "Vakavuus",
    reportedByLabel: "Raportoija",
    reportedByDefault: "anonyymi",
    reportButton: "Raportti",
    reportMessage: "Raportti vastaanotettu",
    errorReportMessage: "Kohteen raportoinnissa tapahtui virhe",
    drawErrorInstructions: "Valitse piste, viiva tai polygoni ja vedä virhegeometria karttaan:",
    errorMapService: "Karttapalvelujen tietojen noudossa tapahtui virhe",
    noFeatureSelected : "Valitusta sijainnista ei löytynyt kohteita",
    selectFeatureMapPoint: "Valitse kohde napsauttamalla",
    drawFeatureMapPoint: "Lisää piste napsauttamalla",
    popupMessage:"Viesti",
    popupError:"Virhe",
    manyFeaturesSelected: "Löytyi useita kohteita. Lähennä ja valitse raportoitava kohde."
  })
);
