define(
   ({
    _widgetLabel: "Query",
    executeQueryTip: "Klik op een van de volgende taakitems om de query uit te voeren.",
    invalidConfig: "Ongeldige configuratie. Gebruik de pagina van de query-instellingen om de juiste configuratie te krijgen.",
    queryParams: "Opties",
    parameters: "OPTIES",
    queries: "QUERY\'S",
    apply: "TOEPASSEN",
    queryResults: "Resultaten",
    clear: "Wissen",
    noResults: "Geen object gevonden",
    queryError: "Query is mislukt.",
    numberFound: "Aantal gevonden objecten",
    mapExtentTip: "Beperk de resultaten tot het huidige kaartextent.",
    noValue: "Geen waarde",
    and: "en",
    stringOperatorIs: "is", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "is niet",
    stringOperatorStartsWith: "begint met",
    stringOperatorEndsWith: "eindigt met",
    stringOperatorContains: "bevat",
    stringOperatorDoesNotContain: "bevat niet",
    stringOperatorIsBlank: "is leeg",
    stringOperatorIsNotBlank: "is niet leeg",
    dateOperatorIsOn: "is op", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "is niet op",
    dateOperatorIsBefore: "is voor",
    dateOperatorIsAfter: "is na",
    dateOperatorDays: "dagen",
    dateOperatorWeeks: "weken", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "maanden",
    dateOperatorInTheLast: "in de afgelopen",
    dateOperatorNotInTheLast: "niet in de afgelopen",
    dateOperatorIsBetween: "is tussen",
    dateOperatorIsNotBetween: "is niet tussen",
    dateOperatorIsBlank: "is leeg",
    dateOperatorIsNotBlank: "is niet leeg",
    numberOperatorIs: "is", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "is niet",
    numberOperatorIsAtLeast: "is minimaal",
    numberOperatorIsLessThan: "is kleiner dan",
    numberOperatorIsAtMost: "is maximaal",
    numberOperatorIsGreaterThan: "is groter dan",
    numberOperatorIsBetween: "is tussen",
    numberOperatorIsNotBetween: "is niet tussen",
    numberOperatorIsBlank: "is leeg",
    numberOperatorIsNotBlank: "is niet leeg",
    operationalLayerTip: "Resultaat als operationele laag toevoegen",
    queryResult: "Query-resultaat",
    specifyParamsTip: "Parameters voor deze taak specificeren",
    useSpatialFilter: "Ruimtelijke filter gebruiken om objecten te beperken",
    useCurrentMapExtent: "Alleen objecten die het huidige kaartextent aanraken",
    drawGraphicOnMap: "Alleen objecten die een door de gebruiker gedefinieerd gebied aanraken",
    specifySpatialFilterMsg: "Specificeer een ruimtelijke filter voor deze taak.",
    clearResults: "Resultaten wissen",
    operationalTip: 'Als deze optie aangevinkt is, worden de resultaten op de kaart gehandhaafd totdat op de knop \"${clearResults}\" wordt geklikt.',
    noneQueryTip: "Er zijn geen vooraf gedefinieerde query-taken beschikbaar.",
    noPermissionsMsg: "U hebt geen toestemming voor toegang tot deze service."
  })
);