define(
   ({
    _widgetLabel: "Query",
    executeQueryTip: "Klik op een van de volgende taakitems om de query uit te voeren.",
    invalidConfig: "Ongeldige configuratie. Gebruik de pagina van de query-instellingen om de juiste configuratie te krijgen.",
    queryParams: "Opties",
    parameters: "OPTIES",
    queries: "QUERY\'S",
    apply: "TOEPASSEN",
    queryResults: "Resultaten",
    clear: "Wissen",
    noResults: "Geen object gevonden",
    queryError: "Query is mislukt.",
    numberFound: "Aantal gevonden objecten",
    mapExtentTip: "Beperk de resultaten tot het huidige kaartgebied.",
    noValue: "Geen waarde",
    and: "en",
    stringOperatorIs: "is", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "is niet",
    stringOperatorStartsWith: "begint met",
    stringOperatorEndsWith: "eindigt met",
    stringOperatorContains: "bevat",
    stringOperatorDoesNotContain: "bevat niet",
    stringOperatorIsBlank: "is leeg",
    stringOperatorIsNotBlank: "is niet leeg",
    dateOperatorIsOn: "is op", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "is niet op",
    dateOperatorIsBefore: "is voor",
    dateOperatorIsAfter: "is na",
    dateOperatorDays: "dagen",
    dateOperatorWeeks: "weken", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "maanden",
    dateOperatorInTheLast: "in de afgelopen",
    dateOperatorNotInTheLast: "niet in de afgelopen",
    dateOperatorIsBetween: "is tussen",
    dateOperatorIsNotBetween: "is niet tussen",
    dateOperatorIsBlank: "is leeg",
    dateOperatorIsNotBlank: "is niet leeg",
    numberOperatorIs: "is", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "is niet",
    numberOperatorIsAtLeast: "is minimaal",
    numberOperatorIsLessThan: "is kleiner dan",
    numberOperatorIsAtMost: "is maximaal",
    numberOperatorIsGreaterThan: "is groter dan",
    numberOperatorIsBetween: "is tussen",
    numberOperatorIsNotBetween: "is niet tussen",
    numberOperatorIsBlank: "is leeg",
    numberOperatorIsNotBlank: "is niet leeg",
    operationalLayerTip: "Resultaat als operationele laag toevoegen",
    queryResult: "Query-resultaat",
    specifyParamsTip: "Parameters voor deze taak specificeren",
    useSpatialFilter: "Ruimtelijke filter gebruiken om objecten te beperken",
    useCurrentMapExtent: "Alleen objecten die het huidige kaartgebieden kruisen",
    drawGraphicOnMap: "Alleen objecten die het door de gebruiker gedefinieerd gebied kruisen",
    specifySpatialFilterMsg: "Specificeer een ruimtelijke filter voor deze taak.",
    clearResults: "Resultaten wissen",
    operationalTip: 'Als deze optie aangevinkt is, worden de resultaten op de kaart gehandhaafd totdat op de knop \"${clearResults}\" wordt geklikt.',
    noneQueryTip: "Er is geen zoektaak geconfigureerd voor deze widget.",
    noPermissionsMsg: "U hebt geen toestemming voor toegang tot deze service.",
    attributesFromRelationship: "Attributen van gerelateerde tabel",
    tasks: "Taken",
    applySpatialFilterToLimitResults: "Een ruimtelijk filter toepassen om resultaten te beperken",
    useCurrentExtentTip: "Gedeeltelijk of volledig in de actuele kaart",
    useDrawGraphicTip: "Gedeeltelijk of volledig in de vorm die op de kaart getekend is",
    useFeaturesTip: "Op basis van de locaties t.o.v. de objecten in een andere laag",
    noSpatialLimitTip: "Resultaten niet ruimtelijk beperken",
    applySearchDistance: "Een zoekafstand toepassen",
    spatialRelationship: "Ruimtelijke verhouding",
    relatedLayer: "Gerelateerde laag",
    bufferDistance: "Bufferafstand",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    back: "Vorige",
    execute: "Uitvoeren"
  })
);