define(
   ({
    routeUrl: "URL itinerario",
    locatorUrl: "URL geocodificatore",
    geocoderOptions: "Opzioni geocodificatore",
    autoComplete: "Completamento automatico",
    maxLocations: "Numero max posizioni",
    minCharacters: "Numero min caratteri",
    searchDelay: "Ritardo ricerca",
    placeholder: "Segnaposto",
    routeOptions: "Opzioni itinerari",
    directionsLanguage: "Lingua indicazioni",
    directionsLengthUnits: "Unità di lunghezza indicazioni",
    directionsOutputType: "Tipo di output indicazioni",
    impedanceAttribute: "Attributo impedenza",
    kilometers: "Chilometri",
    miles: "Miglia",
    meters: "Metri",
    feet: "Piedi",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    parametersTip: "Impostare correttamente i parametri.",
    complete: "Complete",
    completeNoEvents: "Complete senza eventi",
    instructionsOnly: "Solo istruzioni",
    standard: "Standard",
    summaryOnly: "Solo riepilogo",
    travelModesUrl: "URL delle modalità di viaggio",
    searchPlaceholder: "Trova indirizzo o luogo",
    trafficLayerUrl: "URL layer per il traffico"
  })
);