define(
   ({
    _widgetLabel: "チャート",
    executeChartTip: "次のタスク アイテムの 1 つをクリックして、チャートを実行します。",
    invalidConfig: "無効な構成です。",
    noneChartTip: "このウィジェット用のチャート タスクが構成されていません。",
    chartParams: "オプション",
    charts: "チャート",
    apply: "適用",
    useSpatialFilter: "空間フィルターを使用してフィーチャを制限",
    useCurrentMapExtent: "現在のマップ エリアと交差するフィーチャのみ",
    drawGraphicOnMap: "ユーザー指定エリアと交差するフィーチャのみ",
    chartResults: "結果のチャート化",
    clearResults: "結果の消去",
    noPermissionsMsg: "このサービスにアクセスできる権限がありません。",
    specifySpatialFilterMsg: "このタスクの空間フィルターを指定してください。",
    queryError: "クエリに失敗しました。",
    noResults: "フィーチャは見つかりませんでした。",
    category: "カテゴリ",
    count: "個数",
    label: "ラベル",
    horizontalAxis: "横軸",
    verticalAxis: "縦軸",
    dataLabels: "データ ラベル",
    color: "色",
    colorful: "カラー",
    monochromatic: "モノクロ",
    tasks: "タスク",
    results: "結果",
    applySpatialFilterToLimitResults: "空間フィルターを適用して結果を制限する",
    useCurrentExtentTip: "現在のマップ範囲に部分的または完全に含まれる",
    useDrawGraphicTip: "マップに描画された図形に部分的または完全に含まれる",
    useFeaturesTip: "別のレイヤー内のフィーチャを基準にした位置に基づく",
    noSpatialLimitTip: "結果を空間的に制限しない",
    applySearchDistance: "検索距離の適用",
    spatialRelationship: "空間リレーションシップ",
    relatedLayer: "関連レイヤー",
    clear: "消去",
    bufferDistance: "バッファー距離",
    miles: "マイル",
    kilometers: "キロメートル",
    feet: "フィート",
    meters: "メートル",
    yards: "ヤード",
    nauticalMiles: "海里",
    back: "戻る",
    execute: "実行"
  })
);