define({
  root: ({
    selectFeatures: "By Shape",
    selectByAttribute: "By Value",
    results: "Results",
    searchLayer: "Search layer",
    searchType: "Search alias",
    selectFeaturesBy: "Select features by",
    selectSpatial: "By Spatial",
    search: "Search",
    clear: "Clear",
    clearBuffer: "Clear Buffer",
    zoomall: "Zoom All",
    point: "Point",
    line: "Line",
    polyline: "Polyline",
    freehandPolyline: "Freehand Polyline",
    triangle: "Triangle",
    extent: "Extent",
    circle: "Circle",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Freehand Polygon",
    featuresSelected: "Features selected: ",
    noResults: "No results",
    searchError: "Search failed !",
    searchResult: "Search result",
    useMultiGraphics: "Enable multi-part graphics",
    addTolerance: "Add search tolerance to point selection",
    specifyParamsTip: "Specify parameters for this search",
    and: "and",
    friendlyDatePattern: "MM/dd/yyyy",
    stringOperatorIs: 'stringOperatorIs',
    stringOperatorIsNot: 'stringOperatorIsNot',
    stringOperatorStartsWith: 'stringOperatorStartsWith',
    stringOperatorEndsWith: 'stringOperatorEndsWith',
    stringOperatorContains: 'stringOperatorContains',
    stringOperatorDoesNotContain: 'stringOperatorDoesNotContain',
    stringOperatorIsBlank: 'stringOperatorIsBlank',
    stringOperatorIsNotBlank: 'stringOperatorIsNotBlank',
    dateOperatorIsOn: 'dateOperatorIsOn',
    dateOperatorIsNotOn: 'dateOperatorIsNotOn',
    dateOperatorIsBefore: 'dateOperatorIsBefore',
    dateOperatorIsAfter: 'dateOperatorIsAfter',
    dateOperatorDays: 'dateOperatorDays',
    dateOperatorWeeks: 'dateOperatorWeeks',
    dateOperatorMonths: 'dateOperatorMonths',
    dateOperatorInTheLast: 'dateOperatorInTheLast',
    dateOperatorNotInTheLast: 'dateOperatorNotInTheLast',
    dateOperatorIsBetween: 'dateOperatorIsBetween',
    dateOperatorIsNotBetween: 'dateOperatorIsNotBetween',
    dateOperatorIsBlank: 'dateOperatorIsBlank',
    dateOperatorIsNotBlank: 'dateOperatorIsNotBlank',
    numberOperatorIs: 'numberOperatorIs',
    numberOperatorIsNot: 'numberOperatorIsNot',
    numberOperatorIsAtLeast: 'numberOperatorIsAtLeast',
    numberOperatorIsLessThan: 'numberOperatorIsLessThan',
    numberOperatorIsAtMost: 'numberOperatorIsAtMost',
    numberOperatorIsGreaterThan: 'numberOperatorIsGreaterThan',
    numberOperatorIsBetween: 'numberOperatorIsBetween',
    numberOperatorIsNotBetween: 'numberOperatorIsNotBetween',
    numberOperatorIsBlank: 'numberOperatorIsBlank',
    numberOperatorIsNotBlank: 'numberOperatorIsNotBlank',
    bufferGraphic: 'Buffer Graphic',
    searchDistance: 'Apply a search distance:',
    applyBuffer: 'Apply Buffer',
    searchEntities: 'Search entities of:',
    intersectMessage: 'There is no result to intersect, please complete a graphical or text search first.',
    spatialSearchErrorTitle: 'Spatial Search error',
    bufferMessage: 'There is no result to buffer, please complete a graphical or text search first.',
    bufferSearchErrorTitle: 'Buffer error',
    spatialchoicemsg: 'Do you want to use the Buffer Graphics or the Selection Graphics?',
    spatialchoicetitle: 'Choose',
    buffergraphics: 'Buffer',
    selectiongraphics: 'Selection',
    widgetversion: 'eSearch Widget Version Info',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Widget is designed to run in Web AppBuilder version',
    exporturl: 'Export Search URL',
    copyurlprompt: 'Copy to clipboard: Ctrl+C, Enter',
    limit2mapextent: 'Limit search to map extent',
    graphicgeomtypemsg1: 'Mixing major geometry types like points, lines and polygons is not supported.',
    graphicgeomtypemsg2: 'Do you want to continue which will result in clearing all previous drawn graphics?',
    cancel: 'cancel',
    _continue: 'continue',
    warning: 'Warning!',
    zoomErrorMessage: 'Attempts to auto zoom to the search results have failed.',
    addTextQuery: 'Include text query in selection criteria',
    uniqueValues: 'Retrieving unique values',
    processingUnique: 'Processing unique values: ',
    of: ' of ',
    requiredTip: "Value required to execute search",
    required: "Required",
    requiredWarning: "Required Value Missing",
    requiredErrorMessage: "You have failed to enter one or more required values",
    selectFeaturesFrom: "Use graphics from",
    eLocateTip: "Use Existing Enhanced Locate Widget Graphics",
    createnewselection: "Create new results",
    addtoselection: "Add to current results",
    removefromselection: "Remove from current results",
    mapServiceFailureTitle: "Search Layer Map Service Failure",
    mapServicefailureMsg: "The following search layer(s) map service(s) failed to respond: ",
    mapServicefailureMsg2: ". Due to this failure the search layer(s) will be removed from the widget."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 1,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  'zh-cn': 0
});
