define({
  root: ({
    "tabs_section_Label": "Tabs",
    "addTab": "Add Tab",
    "layerName": "Layer",
    "layerType": "Analysis Type",
    "layerLabel": "Label",
    "actions": "Actions",
    "closest": "Closest Feature",
    "proximity": "Proximity",
    "summary": "Summary",
    "select_lbl": "-- Select --",
    "general_setting_Label": "General Settings",
    "units_text_lbl": "Distance Units",
    "miles": "Miles",
    "kilometers": "Kilometers",
    "feet": "Feet",
    "meters": "Meters",
    "yards": "Yards",
    "nauticalMiles": "Nautical Miles",
    "maximum_distance_lbl": "Closest Feature Maximum Distance",
    "buffer_text_lbl": "Buffer Label",
    "buffer_lbl": "Buffer Distance",
    "buffer_max_lbl": "Maximum Buffer Distance",
    "buffer_min_lbl": "Minimum Buffer Distance",
    "routing_checkBox": "Enable Routing",
    "weather_Label": "Weather Options",
    "weather_checkBox": "Include Weather Information",
    "selectLayers": "Select Weather Layers",
    "currentlySelectedLayer": "Currently selected weather layers",
    "missingTabLabel": "At least one tab is missing its label",
    "cancel": "Cancel",
    "ok": "Ok",
    "missingLayerInWebMap": "No operational layers found.",
    "selectFields": "Select Fields",
    "addField": "Add Field",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Show Count",
    "area_checkBox": "Show Area",
    "length_checkBox": "Show Length",
    "max_records": "Maximum limit reached"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
