define({
    showArcgisBasemaps: "Kaasa portaali aluskaardid",
    settings: "Seaded",
    add: "Klikkige uue aluskaardi lisamiseks",
    edit: "Omadused",
    title: "Pealkiri",
    titlePH: "Aluskaardi pealkiri",
    thumbnail: "Pisipilt",
    thumbnailHint: "Kliki uuendamiseks pilti",
    url: "URL",
    urlPH: "Kihi URL",
    addlayer: "Lisa aluskaart",
    actions: "Tegevused",
    warning: "Vale sisend",
    save: "Tagasi ja salvesta",
    back: "Tagasi ja tühista",
    addUrl: "Lisa URL",
    autoCheck: "Automaatne kontroll",
    checking: "Kontrollimine...",
    ok: "OK",
    cancel: "Tühista",
    result: "Salvestamine õnnestus",
    spError: "Kõik galeriisse lisatud aluskaardid peavad kasutama samasugust koordinaatsüsteemi.",
    invalidTitle1:"Aluskaart nimega",
    invalidTitle2:"on juba olemas. Valige uus pealkiri.",
    invalidBasemapUrl1: "Seda tüüpi kihti ei saa kasutada aluskaardina.",
    invalidBasemapUrl2: "Praegune kaart kasutab erinevat koordinaatsüsteemi.",
    addBaselayer: "Š_Add Basemap Layer_ä"

});