define(
   ({
    _widgetLabel: "مخطط",
    executeChartTip: "انقر على أحد عناصر المهمة التالية لتنفيذ المخطط.",
    invalidConfig: "تكوين غير صحيح.",
    noneChartTip: "لم يتم تكوين مهمة المخطط لعنصر واجهة الاستخدام الحالي.",
    chartParams: "خيارات",
    charts: "مخططات",
    apply: "تطبيق",
    useSpatialFilter: "استخدام عوامل التصفية المكانية لتقييد المعالم",
    useCurrentMapExtent: "فقط المعالم التي تتقاطع في منطقة الخريطة الحالية",
    drawGraphicOnMap: "فقط المعالم التي تتقاطع في المنطقة التي يُعرفها المستخدم",
    chartResults: "نتائج المخطط",
    clearResults: "مسح النتائج",
    noPermissionsMsg: "ليس لديك أي اذونات للوصول إلى هذه الخدمة.",
    specifySpatialFilterMsg: "يرجى تحديد عامل التصفية المكاني للمهمة الحالية.",
    queryError: "فشل الاستعلام.",
    noResults: "لم يتم العثور على أية معالم",
    category: "الفئة",
    count: "عدد",
    label: "لافتة التسمية",
    horizontalAxis: "محور أفقي",
    verticalAxis: "محور رأسي",
    dataLabels: "تسميات البيانات",
    color: "لون",
    colorful: "مُلوّن",
    monochromatic: "أحادي اللون",
    tasks: "المهام",
    results: "النتائج",
    applySpatialFilterToLimitResults: "تطبيق التصفية المكانية لتحديد النتائج",
    useCurrentExtentTip: "جزئيًا أو بالكامل ضمن مدى الخريطة الحالي",
    useDrawGraphicTip: "جزئيًا أو بالكامل ضمن الشكل المرسوم في الخريطة",
    useFeaturesTip: "يستند إلى المواقع المرتبطة بالمعالم في طبقة أخرى",
    noSpatialLimitTip: "ليست نتائج حدود مكانية",
    applySearchDistance: "تطبيق مسافة البحث",
    spatialRelationship: "العلاقة المكانية",
    relatedLayer: "الطبقة المرتبطة",
    clear: "مسح",
    bufferDistance: "مسافة النطاق",
    miles: "ميل",
    kilometers: "كيلومترات",
    feet: "قدم",
    meters: "متر",
    yards: "ياردة",
    nauticalMiles: "الأميال البحرية",
    back: "الخلف",
    execute: "تنفيذ"
  })
);