define(
	 ({
		queries: "Ερωτήματα",
		addNew: "Προσθήκη νέου",
    queryLayer: "Θεματικό επίπεδο ερωτήματος",
		setSource: "Ορισμός",
		setDataSource: "Ορισμός προέλευσης δεδομένων",
		name: "Όνομα",
		querySource: "Προέλευση δεδομένων",
		queryName: "Όνομα ερωτήματος",
		queryDefinition: "Ορισμός φίλτρου",
		resultsSetting: "Ρύθμιση αποτελεσμάτων",
		symbolSetting: "Ρύθμιση συμβόλου",
		resultSettingTip: "Προσδιορίστε ποια αποτελέσματα θα εμφανίζονται και με ποιον τρόπο.",
		resultItemTitle: "Τίτλος αντικειμένου αποτελέσματος",
		resultItemContent: "Περιεχόμενα αντικειμένου αποτελέσματος",
		fieldsSetTip: "Ελέγξτε τα πεδία που θέλετε να εμφανίσετε. Επιλέξτε ένα πεδίο για να ενημερώσετε το ψευδώνυμο, τη σειρά και τη μορφή του.",
		addField: "Προσθήκη πεδίου",
		visibility: "Ορατότητα",
		alias: "Ψευδώνυμο",
		specialType: "Ειδικός τύπος",
		actions: "Ενέργειες",
		none: "Κανένα",
		link: "Σύνδεσμος",
		image: "Εικόνα",
		noField: "Χωρίς πεδίο",
		operationalLayerTip: "Προσθήκη αποτελέσματος ως επιχειρησιακό επίπεδο",
		setLayerSymbolTip: "Καθορισμός συμβόλου για τα αποτελέσματα: ",
		setSelectedSymbolTip: "Ορίστε το σύμβολο του επιλεγμένου στοιχείου.",
		notUseFilter: "Να μη χρησιμοποιηθεί φίλτρο",
		setSourceTip: "Ορίστε δεδομένα προέλευσης για το ερώτημα.",
		setFilterTip: "Ορίστε σωστά το φίλτρο.",
		ok: "ΟΚ",
		cancel: "Ακύρωση",
		noFilterTip: "Αν δεν καθοριστεί έκφραση για το φίλτρο, αυτό το ερώτημα θα συμπεριλάβει σε λίστα όλα τα στοιχεία από την καθορισμένη προέλευση δεδομένων.",
    relationships: "Συσχετίσεις",
    addRelationshipLayer: "Προσθήκη νέας συσχέτισης",
    relatedTo: "Συσχετίζεται με",
    selectOption: "Παρακαλώ επιλέξτε..",
    resultItemSorting: "Ταξινόμηση των αντικοιμένων των αποτελεσμάτων",
    field: "Πεδίο",
    sortingOrder: "Σειρά",
    configureFieldsTip: "Διαμορφώστε τα πεδία με βάση τα οποία θα ταξινομηθούν τα αποτελέσματα του ερωτήματος.",
    setSortingFields: "Ορισμός πεδίων ταξινόμησης",
    ascending: "Αύξουσα",
    descending: "Φθίνουσα",
    sortBy: "Ταξινόμηση κατά",
    thenBy: "Έπειτα κατά",
    addTask: "Προσθήκη εργασίας",
    noTasksTip: 'Δεν υπάρχουν εργασίες, κάντε κλικ στο στοιχείο \"${addTask}\" για να ξεκινήσετε!',
    infoText: "Πληροφορίες",
    filters: "Φίλτρα",
    results: "Αποτελέσματα",
    optionsText: "Επιλογές",
    summaryText: "Σύνοψη",
    attributeFilter: "Φίλτρο χαρακτηριστικού",
    attributeFilterTip: "Καθορίστε εκφράσεις περιγραφικών γνωρισμάτων για χρήση στο widget, για φιλτράρισμα θεματικού επιπέδου ερωτήματος.",
    noExpressionDefinedTip: "Δεν καθορίστηκε έκφραση.",
    needInputValuesTip: "Χρειάζεται εισαγωγή τιμών κατά τον χρόνο εκτέλεσης",
    setExpressions: "Ορισμός εκφράσεων",
    spatialFilter: "Χωρικό φίλτρο",
    spatialFilterTip: "Επιλέξτε τα χωρικά φίλτρα που χρησιμοποιούνται στο widget για να περιορίσετε τα αποτελέσματα.",
    defaultOption: "Προεπιλογή",
    useCurrentExtentTip: "Μερικώς ή πλήρως εντός της τρέχουσας έκτασης χάρτη",
    useDrawGraphicTip: "Μερικώς ή πλήρως εντός του σχήματος που έχει σχεδιαστεί στο χάρτη",
    useFeaturesTip: "Βάσει των τοποθεσιών που είναι σχετικές με στοιχεία άλλου θεματικού επιπέδου",
    noSpatialLimitTip: "Χωρίς χωρικό περιορισμό αποτελεσμάτων",
    drawingTools: "Εργαλεία σχεδίασης",
    bufferSettings: "Ρυθμίσεις ζώνης",
    defaultDistance: "Προκαθορισμένη απόσταση",
    bufferDistance: "Απόσταση ζώνης",
    defaultUnit: "Προκαθορισμένη μονάδα",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    availableSpatialRelationships: "Διαθέσιμη χωρική συσχέτιση",
    setSpatialRelationships: "Ορισμός χωρικής συσχέτισης",
    availability: "Διαθεσιμότητα",
    relationship: "Συσχέτιση",
    label: "Ετικέτα",
    intersect: "τέμνει",
    contain: "περιέχει",
    areContainedIn: "περιέχονται σε",
    cross: "σταυρός",
    envelopeIntersect: "τομή περιγεγραμμένου πλαισίου",
    overlap: "επικαλύπτει",
    areOverlapped: "επικαλύπτονται",
    touche: "αγγίζει",
    within: "εντός",
    areWithin: "είναι εντός",
    indexIntersect: "τομή ευρετηρίου",
    itemTitle: "Τίτλος αντικειμένου",
    displayFields: "Πεδία εμφάνισης",
    sortingFields: "Ταξινόμηση πεδίων",
    setDisplayFields: "Ορισμός πεδίων εμφάνισης",
    symbol: "Σύμβολο",
    setSymbol: "Ορισμός συμβόλου",
    serviceSymbolTip: "Χρησιμοποιήστε σύμβολα που ορίζονται από το θεματικό επίπεδο",
    exportTip: "Εμφάνιση κουμπιού εξαγωγής",
    keepResultsTip: "Διατήρηση των αποτελεσμάτων στη σελίδα μετά το κλείσιμο του widget",
    queryRelatedRecords: "Εγγραφές συναφείς με το ερώτημα",
    createLayerForTaskTip: "Καθορίστε τον τρόπο δημιουργίας θεματικών επιπέδων από την εργασία",
    oneLayerForTaskTip: "Δημιουργία μόνο ενός θεματικού επιπέδου για αυτή την εργασία",
    multipleLayerForTaskTip: "Δημιουργία νέου θεματικού επιπέδου κάθε φορά που εκτελείται αυτή η εργασία"
  })
);
