define({
  root: ({
    _widgetLabel: "Stream",
    noStreamLayer: "No preconfigured stream layer options available.",
    streamControls: "Streaming Controls",
    startStreaming: "Start Streaming",
    stopStreaming: "Stop Streaming",
    clearObservation: "Clear previous observations",
    streamFilter: "Filter",
    showAllObservations: "Show all observations",
    showMapAreaObservations: "Limit observations to current map area",
    showObservationsByDrawing: "Limit observations by drawing on the map",
    useSpatialFilter: "Use spatial filter to limit observations",
    useAttributeFilter: "Use attribute filter to limit observations",
    selectStreamLayer: "Select a Stream Layer",
    previousObservations: "Draw previous observations",
    applyAttrFilter: "Apply"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
