define(
   ({
    routeUrl: "URL tuyến đường",
    locatorUrl: "URL Trình mã hóa địa lý",
    geocoderOptions: "Tùy chọn của trình mã hóa địa lý",
    autoComplete: "Tự động hoàn tất",
    maxLocations: "Vị trí tối đa",
    minCharacters: "Ký tự tối đa",
    searchDelay: "Trì hoãn tìm kiếm",
    placeholder: "Trình giữ chỗ",
    routeOptions: "Tùy chọn định tuyến",
    directionsLanguage: "Ngôn ngữ thông tin định hướng",
    directionsLengthUnits: "Đơn vị độ dài thông tin định hướng",
    directionsOutputType: "Loại đầu ra của thông tin định hướng",
    impedanceAttribute: "Thuộc tính trở kháng",
    kilometers: "Kilômét",
    miles: "Dặm",
    meters: "Mét",
    feet: "Feet",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    parametersTip: "Vui lòng đặt tham số chính xác !",
    complete: "Hoàn tất",
    completeNoEvents: "Hoàn tất không có sự kiện nào",
    instructionsOnly: "Chỉ hướng dẫn",
    standard: "Tiêu chuẩn",
    summaryOnly: "Chỉ tóm tắt",
    travelModesUrl: "URL Hình thức Di chuyển",
    searchPlaceholder: "Tìm địa chỉ hoặc địa điểm",
    trafficLayerUrl: "URL Lớp Lưu lượng giao thông"
  })
);