define(
   ({
    _widgetLabel: "Diagram",
    executeChartTip: "Klikk på ett av følgende oppgaveelementer for å lage diagrammet.",
    invalidConfig: "Ugyldig konfigurasjon.",
    noneChartTip: "Ingen diagramoppgave er konfigurert for denne widgeten.",
    chartParams: "Alternativer",
    charts: "DIAGRAMMER",
    apply: "BRUK",
    useSpatialFilter: "Bruk geografisk filter til å begrense antall geoobjekter",
    useCurrentMapExtent: "Bare geoobjekter som krysser det gjeldende kartområdet",
    drawGraphicOnMap: "Bare geoobjekter som krysser et brukerdefinert område",
    chartResults: "Diagramresultater",
    clearResults: "Fjern resultater",
    noPermissionsMsg: "Du har ikke tillatelse til å bruke denne tjenesten.",
    specifySpatialFilterMsg: "Angi et romlig filter for denne oppgaven.",
    queryError: "Spørringen mislyktes.",
    noResults: "Fant ingen geoobjekter.",
    category: "Kategori",
    count: "Antall",
    label: "Etikett",
    horizontalAxis: "Horisontal akse",
    verticalAxis: "Vertikal akse",
    dataLabels: "Datapåskrifter",
    color: "Farge",
    colorful: "Med flere farger",
    monochromatic: "Med bare én farge",
    tasks: "Oppgaver",
    results: "Resultater",
    applySpatialFilterToLimitResults: "Bruk et romlig filter til å begrense resultatene",
    useCurrentExtentTip: "Delvis eller helt innenfor gjeldende kartutstrekning",
    useDrawGraphicTip: "Delvis eller helt innenfor formen tegnet på kartet",
    useFeaturesTip: "Basert på deres lokasjoner i forhold til geoobjekter i andre lag",
    noSpatialLimitTip: "Ikke bruk romlig begrensing på resultater",
    applySearchDistance: "Bruk en søkeavstand",
    spatialRelationship: "Romlig relasjon",
    relatedLayer: "Relatert lag",
    clear: "Tøm",
    bufferDistance: "Bufferavstand",
    miles: "Miles",
    kilometers: "kilometer",
    feet: "fot",
    meters: "meter",
    yards: "Yards",
    nauticalMiles: "Nautiske mil",
    back: "Tilbake",
    execute: "Utfør"
  })
);