define(
   ({
    _widgetLabel: "ジオプロセシング",
    execute: "実行",
    help: "ヘルプ",
    input: "入力",
    output: "出力",
    executing: "実行中",
    requiredInfo: "は必須です。",
    drawnOnMap: "結果はマップ上に描画されます。",
    clear: "消去",
    error: "エラー",
    noToolConfig: "構成済みの使用可能なジオプロセシング タスクがありません。",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "ファイルのアップロード",
    selectFileToUpload: 'ファイルの選択...',
    upload: 'アップロード',
    rasterFormat: 'ラスター データ形式',
    noFileSelected: 'ファイルが選択されませんでした。',
    uploadSuccess:'ファイルのアップロードに成功しました。',
    url: "URL",
    showLayerContent: "レイヤー コンテンツの表示",
    invalidUrl: "無効なフィーチャ サービス URL",
    Feet: "フィート",
    Yards: "ヤード",
    Miles: "マイル",
    NauticalMiles: "海里",
    Meter: "メートル",
    Kilometers: "キロメートル",
    urlPlaceholder: "フィーチャ セット URL"
  })
);
