define(
   ({
    _widgetLabel: "Drukāt",
    title: "Kartes virsraksts",
    format: "Formāts",
    layout: "Izkārtojums",
    settings: "Augsts",
    mapScaleExtent: "Kartes mērogs/pārklājums",
    preserve: "Saglabāt",
    mapScale: "kartes mērogs",
    mapExtent: "kartes pārklājums",
    forceScale: "Uzspiest mērogu",
    getCurrentScale: "pašreizējais",
    mapMetadata: "Izkārtojuma metadati",
    author: "Autors",
    copyright: "Autortiesības",
    fullLayoutOptions: "Pilna izkārtojuma opcijas",
    scaleBarUnitsMetric: "Metriskas mēroga joslas vienības",
    scaleBarUnitsNonMetric: "Ne metriskas mēroga joslas vienības",
    unitsMiles: "Jūdzes",
    unitsKilometers: "Kilometri",
    unitsMeters: "Metri",
    unitsFeet: "Pēdas",
    unitsYards: "Jardi",
    unitsNauticalMiles: "Jūras jūdzes",
    lncludeLegend: "Iekļaut apzīmējumus",
    printQualityOptions: "Drukas kvalitāte",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY lielums",
    width: "Platums (px)",
    height: "Augstums (px)",
    print: "Drukāt",
    clearList: "Notīrīt izdrukas",
    creatingPrint: "Drukas izveide",
    printError: "Kļūda, mēģiniet vēlreiz"
  })
);