define(
   ({
    _widgetLabel: "ישות דו\"ח",
    select: "בחר",
    draw: "שרטוט",
    chooseALayer: "בחר שכבה",
    clickAFeature: "לחץ על ישות במפה כדי לבחור בה.",
    loadingFeatures: "מקבל פרטי יישויות נבחרות...",
    errorTitle: "שגיאה",
    errorIdentify: "שגיאה בזיהוי ישויות. עיין ביומן של לוח הבקרה לקבלת פרטים.",
    infoWindowTitle: "פרטים",
    layerLabel: "שם שכבה",
    reviewStatusLabel: "בחן את הסטטוס",
    selectReviewStatusAdd: "הוסף ישות",
    selectReviewStatusDelete: "מחק ישות",
    selectReviewStatusMove: "העבר ישות",
    selectReviewStatusReshape: "עצב ישות מחדש",
    drawReviewStatusMissing: "ישויות חסרות",
    drawReviewStatusPosition: "שגיאה במיקום",
    drawReviewStatusShape: "שגיאה בצורה",
    drawReviewStatusAttribute: "שגיאה במאפיין",
    notesLabel: "הערות",
    severityLabel: "רמת חומרה",
    reportedByLabel: "דווח על-ידי",
    reportedByDefault: "אנונימי",
    reportButton: "דוח",
    reportMessage: "דו\"ח התקבל",
    errorReportMessage: "אירעה שגיאה בעת דיווח על הישות שלך",
    drawErrorInstructions: "בחר נקודה, קו או פוליגון וצייר את הגיאומטריה של השגיאה על המפה:",
    errorMapService: "אירעה שגיאה בעת קבלת הפרטים משירות המפה",
    noFeatureSelected : "לא נמצאו ישויות במיקום שלחצת עליו",
    selectFeatureMapPoint: "לחץ כדי לבחור ישות",
    drawFeatureMapPoint: "הקש להוספת נקודה",
    popupMessage:"הודעה",
    popupError:"שגיאה",
    manyFeaturesSelected: "נמצאה יותר מישות אחת. בצע מיקוד ובחר ישות שעליה יש לדווח."
  })
);
