define(
	 ({
		chartTasks: "Γραφήματα",
		addNew: "Προσθήκη νέου",
		addNewTip: "Προσθήκη νέου γραφήματος",
		name: "Όνομα",
		set: "Ορισμός",
		setDataSource: "Ορισμός προέλευσης δεδομένων",
		generalSettingsTip: "Ορίστε την προέλευση δεδομένων, τον τίτλο και την περιγραφή για τα γραφήματα.",
		chartModeSettingTip: "Επιλέξτε έναν τρόπο ανάλυσης και προβολής των δεδομένων ως γραφήματα.",
		detailsSettingTip: "Διαμορφώστε την εμφάνιση του γραφήματος καθορίζοντας τους τύπους, το χρώμα, καθώς και τις τιμές που θα περιέχει:",
		symbolSettingTip: "Καθορίστε την εμφάνιση του χάρτη για τα δεδομένα που βρίσκονται στο γράφημα.",
		addFilterTip: "Προσθήκη φίλτρου σε αυτά τα δεδομένα",
		dataSource: "Προέλευση δεδομένων",
		noResults: "Δεν εντοπίστηκε στοιχείο.",
		chartTitle: "Τίτλος γραφήματος",
		description: "Περιγραφή",
		chartingMode: "Εμφάνιση γραφήματος",
		featureOption: "Εμφάνιση τιμών ανά στοιχείο",
		categoryOption: "Εμφάνιση τιμών ανά κατηγορία",
		countOption: "Εμφάνιση πλήθους στοιχείων ανά κατηγορία",
		fieldOption: "Εμφάνιση τιμών στοιχείων ως γραφήματα",
		category: "Κατηγορία",
		axisLabel: "Ετικέτα κατηγορίας",
		categoryField: "Πεδίο κατηγορίας",
		operation: "Λειτουργία",
		originalOption: "Χρήση αρχικών τιμών",
		sumOption: "Άθροισμα",
		averageOption: "Μέσος όρος",
		minOption: "Ελάχιστο",
		maxOption: "Μέγιστο",
		valueFields: "Πεδία τιμών",
		moveUp: "Μετακίνηση προς τα επάνω",
		moveDown: "Μετακίνηση προς τα κάτω",
		sortOrder: "Ταξινόμηση της σειράς των γραφημάτων μέσω των ετικετών της κατηγορίας",
		ascending: "Αύξουσα",
		descending: "Φθίνουσα",
		chartType: "Τύπος γραφήματος",
		column: "Γράφημα στηλών",
		bar: "Γράφημα ράβδων",
		line: "Γράφημα γραμμών",
		pie: "Γράφημα πίτας",
		chartColor: "Γράφημα χρώματος",
		showDataLabels: "Εμφάνιση ετικετών δεδομένων",
		setSymbol: "Σύμβολο επιλογής",
		setHighLightColor: "Χρώμα επισήμανσης",
		settings: "Ρυθμίσεις",
		mapInterationOptions: "Επιλογές αλληλεπίδρασης με το χάρτη",
		preview: "Προεπισκόπηση",
		ok: "ΟΚ",
		cancel: "Ακύρωση",
		close: "Κλείσιμο",
		setFilterTip: "Ορίστε σωστά το φίλτρο. ",
		setChartTitleTip: "Ορίστε τον τίτλο του γραφήματος.",
		setChartTypeTip: "Επιλέξτε τουλάχιστον έναν τύπο γραφήματος.",
		setDataFieldTip: "Επιλέξτε τουλάχιστον ένα πεδίο τιμών.",
		setOutputFieldTip: "Ορίστε πεδία εξόδου.",
		count: "Πλήθος",
		label: "Ετικέτα",
		horizontalAxis: "Οριζόντιος άξονας",
		verticalAxis: "Κατακόρυφος άξονας",
		dataLabels: "Ετικέτες δεδομένων",
		color: "Χρώμα",
		colorful: "Πολύχρωμο",
		monochromatic: "Μονόχρωμο",
    noTaskTip: "Κάντε κλικ στην επιλογή \"Προσθήκη νέου\" για να προσθέσετε ένα γράφημα",
    info: "Πληροφορίες",
    charts: "Γραφήματα",
    options: "Επιλογές",
    taskName: "Όνομα ερωτήματος",
    summary: "Σύνοψη",
    resultDescription: "Περιγραφή αποτελέσματος",
    spatialFilterTip: "Επιλέξτε τα χωρικά φίλτρα που χρησιμοποιούνται στο widget για να περιορίσετε τα αποτελέσματα.",
    defaultOption: "Προεπιλογή",
    useCurrentExtentTip: "Μερικώς ή πλήρως εντός της τρέχουσας έκτασης χάρτη",
    useDrawGraphicTip: "Μερικώς ή πλήρως εντός του σχήματος που έχει σχεδιαστεί στο χάρτη",
    useFeaturesTip: "Βάσει των τοποθεσιών που είναι σχετικές με στοιχεία άλλου θεματικού επιπέδου",
    noSpatialLimitTip: "Χωρίς χωρικό περιορισμό αποτελεσμάτων",
    drawingTools: "Εργαλεία σχεδίασης",
    bufferSettings: "Ρυθμίσεις ζώνης",
    defaultDistance: "Προκαθορισμένη απόσταση",
    bufferDistance: "Απόσταση ζώνης",
    defaultUnit: "Προκαθορισμένη μονάδα",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    availableSpatialRelationships: "Διαθέσιμη χωρική συσχέτιση",
    setSpatialRelationships: "Ορισμός χωρικής συσχέτισης",
    availability: "Διαθεσιμότητα",
    relationship: "Συσχέτιση",
    actions: "Ενέργειες",
    intersect: "τομή",
    contain: "περιέχει",
    areContainedIn: "περιέχονται σε",
    cross: "σταυρός",
    envelopeIntersect: "η έκταση τέμνεται",
    overlap: "επικάλυψη",
    areOverlapped: "επικαλύπτονται",
    touche: "αγγίζει",
    within: "εντός",
    areWithin: "είναι εντός",
    indexIntersect: "τομή δείκτη"
  })
);