define(
   ({
    "tabs_section_Label": "Onglets",
    "addTab": "Ajouter un onglet",
    "layerName": "Couche",
    "layerType": "Type d\'analyse",
    "layerLabel": "Etiqueter",
    "actions": "Opérations",
    "closest": "Entité la plus proche",
    "proximity": "Proximité",
    "summary": "Résumé",
    "select_lbl": "-- Sélectionner --",
    "general_setting_Label": "Paramètres généraux",
    "units_text_lbl": "Unités de distance",
    "miles": "Miles",
    "kilometers": "Kilomètres",
    "feet": "Pieds",
    "meters": "Mètres",
    "yards": "Yards",
    "nauticalMiles": "Milles nautiques",
    "maximum_distance_lbl": "Distance maximum de l\'entité la plus proche",
    "buffer_text_lbl": "Etiquette de zone tampon",
    "buffer_lbl": "Distance de la zone tampon",
    "buffer_max_lbl": "Distance maximum de la zone tampon",
    "buffer_min_lbl": "Distance minimum de la zone tampon",
    "routing_checkBox": "Activer le calcul d\'itinéraire",
    "weather_Label": "Options météorologiques",
    "weather_checkBox": "Inclure des informations météorologiques",
    "selectLayers": "Sélectionner les couches météorologiques",
    "currentlySelectedLayer": "Couches météorologiques actuellement sélectionnées",
    "missingTabLabel": "L\'étiquette d\'un onglet au moins est manquante",
    "cancel": "Annuler",
    "ok": "OK",
    "missingLayerInWebMap": "Aucune couche opérationnelle n\'a été trouvée.",
    "selectFields": "Sélectionner des champs",
    "addField": "Ajouter un champ",
    "sum": "SOMME",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "TOTAL",
    "area": "SURFACE",
    "length": "LENGTH",
    "count_checkBox": "Afficher le total",
    "area_checkBox": "Afficher la zone",
    "length_checkBox": "Afficher la longueur",
    "max_records": "Limite maximale atteinte"
  })
);
