define(
   ({
    taskUrl: "URL da Tarefa",
    serviceURLPlaceholder: "Insira a URL da tarefa de geoprocessamento",
    ok: "OK",
    cancel: "Cancelar",
    layer: "Camada",
    action: "Ação",
    input: "Entrada",
    output: "Saída",
    name: "Nome",
    type: "Tipo",
    required: "Exigido",
    layerOrder: "Ordem da Camada",
    options: "Opções",
    defaultValue: "Valor Padrão",
    inputFeatureBy: "Inserir Feição por",
    renderer: "Renderizador",
    displayType: "Tipo de Exibição",
    label: "Rótulo",
    tooltip: "Dica da Ferramenta",
    visible: "Visível",
    helpUrl: "URL de Ajuda",
    useResultMapService: "Utilizar as opções de desenho do serviço de mapa resultante",
    drawOnMap: "Desenhar interativamente no mapa",
    selectLayer: "Selecionando uma camada do mapa",
    url: "URL",
    symbol: "Símbolo",
    shareResults: "Adicionar resultado como camada operacional",
    popup: "Popup",
    setTask: "Configurar",
    setTaskTitle: "Definir Tarefa de GP",
    enablePopup: "Habilitar pop-up"
  })
);