define(
   ({
    taskUrl: "URL da Tarefa",
    serviceURLPlaceholder: "Insira a URL da tarefa de geoprocessamento",
    ok: "OK",
    cancel: "Cancelar",
    layer: "Camada",
    action: "Ação",
    input: "Entrada",
    output: "Saída",
    name: "Nome",
    type: "Tipo",
    required: "Exigido",
    layerOrder: "Ordem da Camada",
    options: "Opções",
    defaultValue: "Valor Padrão",
    inputFeatureBy: "Inserir Feição por",
    renderer: "Renderizador",
    displayType: "Tipo de Exibição",
    label: "Rótulo",
    tooltip: "Dica da Ferramenta",
    visible: "Visível",
    helpUrl: "URL de Ajuda",
    useResultMapService: "Utilizar as opções de desenho do serviço de mapa resultante",
    drawOnMap: "Desenhar interativamente no mapa",
    selectLayer: "Selecionando uma camada do mapa",
    url: "URL",
    symbol: "Símbolo",
    shareResults: "Adicionar resultado como camada operacional",
    popup: "Popup",
    setTask: "Configurar",
    setTaskTitle: "Definir Tarefa de GP",
    enablePopup: "Habilitar pop-up",
    unSupportGeometryType: "Não é possível configurar o renderizador devido ao tipo de geometria desconhecido.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Carregar arquivo",
    selectFileToUpload: "Selecionar arquivo...",
    upload: "Fazer Upload",
    rasterFormat: "Formato de dados raster",
    noFileSelected: "Nenhum arquivo selecionado!",
    uploadSuccess:"Arquivo carregado com sucesso!",
    showLayerContent: "Mostrar conteúdo da camada",
    Feet: "Pés",
    Yards: "Jardas",
    Miles: "Milhas",
    NauticalMiles: "Milhas Náuticas",
    Meter: "Metros",
    Kilometers: "Quilômetros",
    urlPlaceholder: "URL de conjunto da feição",
    allowToExport: "Permitir exportar os resultados"
  })
);
