define(
	 ({
		queries: "Tâches de requête",
		addNew: "Ajouter une requête",
		setSource: "Définir",
		setDataSource: "Définir la source de données",
		name: "Nom",
		querySource: "Source de données",
		queryName: "Nom de la tâche",
		queryDefinition: "Définition de filtre",
		resultsSetting: "Paramétrage des résultats",
		symbolSetting: "Paramètre de symbole",
		resultSettingTip: "Définissez les informations et le mode d’affichage des résultats en sortie.",
		resultItemTitle: "Titre de l’élément de résultat",
		resultItemContent: "Contenu de l’élément de résultat",
		fieldsSetTip: "Cochez les champs que vous souhaitez afficher. Sélectionnez un champ pour mettre à jour son alias, le classer et le mettre en forme.",
		addField: "Ajouter un champ",
		visibility: "Visibilité",
		alias: "Alias",
		specialType: "Type spécial",
		actions: "Actions",
		none: "Aucun",
		link: "Lien",
		image: "Image",
		noField: "Aucun champ",
		operationalLayerTip: "Ajouter le résultat en tant que couche opérationnelle",
		setLayerSymbolTip: "Définissez le symbole des résultats de requête : ",
		setSelectedSymbolTip: "Définissez le symbole de l’entité sélectionnée.",
		notUseFilter: "Ne pas utiliser de filtre",
		setSourceTip: "Définissez la source de la requête.",
		setFilterTip: "Définissez le filtre correctement.",
		ok: "OK",
		cancel: "Annuler",
		noFilterTip: "Sans expression de filtre définie, cette tâche de requête répertorie toutes les entités dans la source de données spécifiée."
  })
);