define(
	 ({
		queries: "Tâches de requête",
		addNew: "Ajouter une requête",
    queryLayer: "Couche de la requête",
		setSource: "Définir",
		setDataSource: "Définir la source de données",
		name: "Nom",
		querySource: "Source de données",
		queryName: "Nom de la tâche",
		queryDefinition: "Définition de filtre",
		resultsSetting: "Paramétrage des résultats",
		symbolSetting: "Paramètre de symbole",
		resultSettingTip: "Définissez les informations et le mode d’affichage des résultats en sortie.",
		resultItemTitle: "Titre de l’élément de résultat",
		resultItemContent: "Contenu de l’élément de résultat",
		fieldsSetTip: "Cochez les champs que vous souhaitez afficher. Sélectionnez un champ pour mettre à jour son alias, le classer et le mettre en forme.",
		addField: "Ajouter un champ",
		visibility: "Visibilité",
		alias: "Alias",
		specialType: "Type spécial",
		actions: "Actions",
		none: "Aucun",
		link: "Lien",
		image: "Image",
		noField: "Aucun champ",
		operationalLayerTip: "Ajouter le résultat en tant que couche opérationnelle",
		setLayerSymbolTip: "Définissez le symbole des résultats de requête : ",
		setSelectedSymbolTip: "Définissez le symbole de l’entité sélectionnée.",
		notUseFilter: "Ne pas utiliser de filtre",
		setSourceTip: "Définissez la source de la requête.",
		setFilterTip: "Définissez le filtre correctement.",
		ok: "OK",
		cancel: "Annuler",
		noFilterTip: "Sans expression de filtre définie, cette tâche de requête répertorie toutes les entités dans la source de données spécifiée.",
    relationships: "Relations",
    addRelationshipLayer: "Ajouter une nouvelle relation",
    relatedTo: "Associé à",
    selectOption: "Sélectionnez..",
    resultItemSorting: "Tri de l\'élément de résultat",
    field: "Champ",
    sortingOrder: "",
    configureFieldsTip: "Configurez les champs en fonction desquels le résultat de la requête sera trié.",
    setSortingFields: "Définir les champs de tri",
    ascending: "Croissant",
    descending: "Décroissant",
    sortBy: "Trier par",
    thenBy: "Puis par",
    addTask: "Ajouter une tâche",
    noTasksTip: 'Aucune tâche. Cliquez sur \"${addTask}\" pour commencer.',
    infoText: "Infos",
    filters: "Filtres",
    results: "Résultats",
    optionsText: "Options",
    summaryText: "Résumé",
    attributeFilter: "Filtre attributaire",
    attributeFilterTip: "Définissez les expressions attributaires à utiliser dans le widget pour filtrer la couche de requête.",
    noExpressionDefinedTip: "Aucune expression n\'a été définie.",
    needInputValuesTip: "Vous devez saisir des valeurs au moment de l\'exécution",
    setExpressions: "Définir des expressions",
    spatialFilter: "Filtre spatial",
    spatialFilterTip: "Choisissez le ou les filtres spatiaux utilisés dans le widget pour limiter les résultats.",
    defaultOption: "Paramètre par défaut",
    useCurrentExtentTip: "Partiellement ou entièrement dans l\'étendue de la carte actuelle",
    useDrawGraphicTip: "Partiellement ou entièrement dans la forme dessinée sur la carte",
    useFeaturesTip: "En fonction de leurs emplacements par rapport aux entités d\'une autre couche",
    noSpatialLimitTip: "Ne pas limiter spatialement les résultats",
    drawingTools: "Outils de dessin",
    bufferSettings: "Paramètres de la zone tampon",
    defaultDistance: "Distance par défaut",
    bufferDistance: "Distance de la zone tampon",
    defaultUnit: "Unité par défaut",
    miles: "Miles",
    kilometers: "Kilomètres",
    feet: "Pieds",
    meters: "Mètres",
    yards: "Yards",
    nauticalMiles: "Milles nautiques",
    availableSpatialRelationships: "Relations spatiales disponibles",
    setSpatialRelationships: "Définir les relations spatiales",
    availability: "Disponibilité",
    relationship: "Relation",
    label: "Etiqueter",
    intersect: "intersectent",
    contain: "contiennent",
    areContainedIn: "sont contenus dans",
    cross: "croiser",
    envelopeIntersect: "intersection de l\'enveloppe",
    overlap: "superposition",
    areOverlapped: "sont superposés",
    touche: "touchent",
    within: "dans",
    areWithin: "sont dans",
    indexIntersect: "intersection de l\'index",
    itemTitle: "Titre de l\'élément",
    displayFields: "Afficher les champs",
    sortingFields: "Tri de champs",
    setDisplayFields: "Définir les champs d\'affichage",
    symbol: "Symbole",
    setSymbol: "Définir le symbole",
    serviceSymbolTip: "Utiliser les symboles définis par la couche",
    exportTip: "Afficher le bouton Exporter",
    keepResultsTip: "Conserver les résultats sur la carte après la fermeture du widget",
    queryRelatedRecords: "Enregistrements relatifs à la requête",
    createLayerForTaskTip: "Spécifiez les modalités de création des couches par la tâche",
    oneLayerForTaskTip: "Créer une seule couche pour cette tâche",
    multipleLayerForTaskTip: "Créer une couche à chaque exécution de cette tâche"
  })
);
