define(
	 ({
		queries: "פעולות תשאול",
		addNew: "הוסף חדש",
    queryLayer: "שכבת שאילתא",
		setSource: "הגדר",
		setDataSource: "הגדר מקור נתונים",
		name: "שם",
		querySource: "מקור נתונים",
		queryName: "שם משימה",
		queryDefinition: "הגדרת סינון",
		resultsSetting: "הגדרת תוצאות",
		symbolSetting: "הגדרות סימבול",
		resultSettingTip: "הגדר אילו תוצאות פלט להציג ואיך להציג אותן.",
		resultItemTitle: "כותרת פריט תוצאה",
		resultItemContent: "תוכן פריט תוצאה",
		fieldsSetTip: "סמן את השדות שאתה רוצה להציג. בחר שדה כדי לעדכן את הכינוי, הסדר והתבנית שלו.",
		addField: "הוסף שדה",
		visibility: "ניראות",
		alias: "שם נוסף",
		specialType: "סוג מיוחד",
		actions: "פעולות",
		none: "ללא",
		link: "קישור",
		image: "תמונה",
		noField: "אין שדה",
		operationalLayerTip: "הוסף תוצאה כשכבה תפעולית",
		setLayerSymbolTip: "הגדר את הסמל לתוצאת השאילתה: ",
		setSelectedSymbolTip: "הגדר סמל לישות הנבחרת.",
		notUseFilter: "אל תשתמש בסינון.",
		setSourceTip: "הגדר בבקשה מקור שאילתה.",
		setFilterTip: "הגדר בבקשה סינון תקין.",
		ok: "אישור",
		cancel: "ביטול",
		noFilterTip: "מבלי להגדיר ביטוי לסינון, שאילתה זו תציג את כל הישויות במקור הנתונים שצוין.",
    relationships: "קישורים",
    addRelationshipLayer: "הוסף קישור חדש",
    relatedTo: "קשור אל",
    selectOption: "בחר אפשרות...",
    resultItemSorting: "מיון פריטי תוצאה",
    field: "שדה",
    sortingOrder: "סדר",
    configureFieldsTip: "הגדר את השדות שישמשו למיון תוצאות השאילתא.",
    setSortingFields: "הגדר שדות מיון",
    ascending: "עולה",
    descending: "יורד",
    sortBy: "מיון על ידי",
    thenBy: "ולאחר מכן לפי",
    addTask: "הוסף משימה",
    noTasksTip: 'אין משימות, לחץ על \"${addTask}\" כדי להתחיל!',
    infoText: "מידע",
    filters: "סינונים",
    results: "תוצאות",
    optionsText: "אפשרויות",
    summaryText: "תקציר",
    attributeFilter: "פילטר מאפיינים",
    attributeFilterTip: "הגדר ביטויי מאפיינים לשימוש בווידג\'ט כדי לסנן את שכבת השאילתא.",
    noExpressionDefinedTip: "לא הוגדר ביטוי.",
    needInputValuesTip: "יש להזין ערכים ב-Runtime‬",
    setExpressions: "הגדר ביטויים",
    spatialFilter: "הפילטר מרחבי",
    spatialFilterTip: "בחר את הפילטרים המרחביים שיעשה בהם שימוש בווידג\'ט כדי להגביל את התוצאות.",
    defaultOption: "ברירת מחדל",
    useCurrentExtentTip: "חלקית או לחלוטין בתיחום המפה הנוכחי",
    useDrawGraphicTip: "חלקית או לחלוטין בגבולות הצורה המצוירת במפה",
    useFeaturesTip: "בהתבסס על המיקום שלהם ביחס לישויות בשכבה אחרת",
    noSpatialLimitTip: "ללא הגבלה מרחבית של התוצאות",
    drawingTools: "כלי שרטוט",
    bufferSettings: "הגדרות חיץ",
    defaultDistance: "מרחק המוגדר כברירת מחדל",
    bufferDistance: "מרחק חיץ",
    defaultUnit: "יחידה המוגדרת כברירת מחדל",
    miles: "מיילים",
    kilometers: "קילומטרים",
    feet: "רגל",
    meters: "מטרים",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    availableSpatialRelationships: "קישורים מרחביים זמינים",
    setSpatialRelationships: "הגדר קישורים מרחביים",
    availability: "זמינות",
    relationship: "קישור",
    label: "תווית",
    intersect: "חיתוך",
    contain: "הכלה",
    areContainedIn: "כלולים בתוך",
    cross: "צלב",
    envelopeIntersect: "אזור תיחום לחיתוך",
    overlap: "חפיפה",
    areOverlapped: "חופפים",
    touche: "נוגע",
    within: "בתוך",
    areWithin: "כלולים",
    indexIntersect: "חיתוך אינדקס",
    itemTitle: "כותרת פריט",
    displayFields: "הצג שדות",
    sortingFields: "שדות מיון",
    setDisplayFields: "הגדר שדות תצוגה",
    symbol: "סמל",
    setSymbol: "הגדר סמל",
    serviceSymbolTip: "השתמש בסמלים המוגדרים על-ידי השכבה",
    exportTip: "הצג את הלחצן \'יצוא\'",
    keepResultsTip: "שמור תוצאות על המפה לאחר סגירת הווידג\'ט",
    queryRelatedRecords: "רשומות המקושרות לשאילתא",
    createLayerForTaskTip: "ציין באיזה אופן יווצרו שכבות במשימה",
    oneLayerForTaskTip: "צור שכבה אחת בלבד במשימה זו",
    multipleLayerForTaskTip: "צור שכבה חדשה בכל הפעלה של משימה זו"
  })
);
