define(
   ({
    _widgetLabel: "Teata objektist",
    select: "Vali",
    draw: "Joonistamine",
    chooseALayer: "Vali kiht",
    clickAFeature: "Objekti valimiseks klõpsake seda kaardil.",
    loadingFeatures: "Valitud objekti andmete toomine ...",
    errorTitle: "Viga",
    errorIdentify: "Objektide tuvastamise tõrge. Vaadake lisateavet konsooli logist.",
    infoWindowTitle: "Detailid",
    layerLabel: "Kihi nimi",
    reviewStatusLabel: "Läbivaatamise olek",
    selectReviewStatusAdd: "Lisa objekt",
    selectReviewStatusDelete: "Kustuta objekt",
    selectReviewStatusMove: "Teisalda objekt",
    selectReviewStatusReshape: "Muuda objekti kuju",
    drawReviewStatusMissing: "Puuduv(ad) objekt(id)",
    drawReviewStatusPosition: "Positsiooniline viga",
    drawReviewStatusShape: "Kujundi viga",
    drawReviewStatusAttribute: "Atribuudi viga",
    notesLabel: "Märkmed",
    severityLabel: "Raskusaste",
    reportedByLabel: "Raporteerija:",
    reportedByDefault: "anonüümne",
    reportButton: "Aruanne",
    reportMessage: "Teade kätte saadud",
    errorReportMessage: "Teie objektist teatamisel ilmnes tõrge",
    drawErrorInstructions: "Valige punkt, joon või polügoon ja joonistage veaga seotud geomeetria kaardile:",
    errorMapService: "Kaarditeenuse teabe hankimisel ilmnes tõrge",
    noFeatureSelected : "Klõpsu asukohast ei leitud objekte",
    selectFeatureMapPoint: "Klõpsake objekti valimiseks",
    drawFeatureMapPoint: "Kliki punkti lisamiseks",
    popupMessage:"Sõnum",
    popupError:"Viga",
    manyFeaturesSelected: "Leiti mitu objekti. Suumige sisse ja valige teatamiseks objekt."
  })
);
