define(
   ({
    _widgetLabel: "Rapportobject",
    select: "Selecteren",
    draw: "Tekenen",
    chooseALayer: "Een kaartlaag selecteren",
    clickAFeature: "Klik op een object op de kaart om het te selecteren.",
    loadingFeatures: "Gegevens geselecteerde object ophalen...",
    errorTitle: "Fout",
    errorIdentify: "Fout bij identificatie object. Controle het consolelogboek voor meer details.",
    infoWindowTitle: "Details",
    layerLabel: "Laagnaam",
    reviewStatusLabel: "Status controleren",
    selectReviewStatusAdd: "Object toevoegen",
    selectReviewStatusDelete: "Verwijder object",
    selectReviewStatusMove: "Object verplaatsen",
    selectReviewStatusReshape: "Objectvorm wijzigen",
    drawReviewStatusMissing: "Ontbrekend(e) object(en)",
    drawReviewStatusPosition: "Positionele fout",
    drawReviewStatusShape: "Vormfout",
    drawReviewStatusAttribute: "Attribuutfout",
    notesLabel: "Opmerkingen",
    severityLabel: "Ernst",
    reportedByLabel: "Gerapporteerd door",
    reportedByDefault: "anoniem",
    reportButton: "Rapport",
    reportMessage: "Rapport ontvangen",
    errorReportMessage: "Er is een fout opgetreden bij het rapporteren van uw object",
    drawErrorInstructions: "Selecteer punt, lijn of polygoon en teken de foutgeometrie op de kaart:",
    errorMapService: "Er is een fout opgetreden bij het ophalen van kaartservice-informatie",
    noFeatureSelected : "Er werden geen objecten gevonden op de aangeklikte locatie",
    selectFeatureMapPoint: "Klik om een object te selecteren",
    drawFeatureMapPoint: "Klik om een punt toe te voegen",
    popupMessage:"Bericht",
    popupError:"Fout",
    manyFeaturesSelected: "Meer dan één object gevonden. Zoom in en selecteer een te rapporteren object."
  })
);
