define({
  root: ({
    popupwidth: "Popup Window Width",
    popupheight: "Popup Window Height",
    panooptions: "Google Street View Panorama Options",
    hidestreetviewvwidowwhenminimized: "Hide window when minimized",
    googleapikey: "Google Maps API Key",
    googlemapsclientid: "Google Maps API Client Id",
    showaddresscontrol: "Show Address Control",
    topleft: "Top Left",
    topcenter: "Top Center",
    topright: "Top Right",
    lefttop: "Left Top",
    righttop: "Right Top",
    leftcenter: "Left Center",
    rightcenter: "Right Center",
    leftbottom: "Left Bottom",
    rightbottom: "Right Bottom",
    bottomleft: "Bottom Left",
    bottomcenter: "Bottom Center",
    bottomright: "Bottom Right",
    showpancontrol: "Show Pan Control",
    position: "Control Position",
    showzoomcontrol: "Show Zoom Control",
    small: "Small",
    default: "Default",
    large: "Large",
    zoomcontrolstyle: "Control Style",
    enableclicktogo: "Enable Click To Go",
    disabledoubleclickzoom: "Disable Double Click Zoom",
    enableimagedatecontrol: "Enable Image Date Control",
    enablelinkscontrol: "Enable Links Control",
    or: "Or"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});