define({
  root: ({
    drsUrl: "Data Revierwer Server URL",
    includeReportedBy: "Reviewer Technician",
    label: "Layer",
    show: "Include",
    alias: "Alias",
    warning: "Incorrect input",
    defaultSessionId:"Default Session",
    setSource: "Set",
    getCurrentUser: "Logged in Username",
    getDefaultUser: "Enter a default value",
    getUser: "Allow user input",
    userName:"Enter Username",
    noUserName: "Please enter default username.",
    noLayers: "No operational layers in the web map.",
    noSessionName:"Please select a Session"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});