define(
	 ({
		charts: "Tâches du diagramme",
		addNew: "Ajouter une tâche",
		addNewTip: "Ajouter une tâche au diagramme",
		name: "Nom",
		set: "Définir",
		setDataSource: "Définir la source de données",
		generalSettingsTip: "Définissez la source de données, le titre et la description des diagrammes.",
		chartModeSettingTip: "Sélectionnez un mode d’analyse et d’affichage des données sous forme de diagrammes.",
		detailsSettingTip: "Définissez l’apparence du diagramme en spécifiant son type et sa couleur, ainsi que les valeurs à représenter.",
		symbolSettingTip: "Définissez l’affichage cartographique des données représentées.",
		addFilterTip: "Appliquer un filtre à ces données",
		dataSource: "Source de données",
		noResults: "Aucune entité trouvée.",
		chartTitle: "Titre du diagramme",
		description: "Description",
		chartingMode: "Affichage du diagramme",
		featureOption: "Afficher les valeurs entité par entité",
		categoryOption: "Afficher les valeurs par catégorie",
		countOption: "Afficher le nombre d’entités par catégorie",
		fieldOption: "Afficher les valeurs attributaires sous forme de diagrammes",
		category: "Catégorie",
		axisLabel: "Etiquette de catégorie",
		categoryField: "Champ de catégorie",
		operation: "Opération",
		originalOption: "Utiliser les valeurs d’origine",
		sumOption: "Somme",
		averageOption: "Moyenne",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Champs de valeur",
		moveUp: "Monter",
		moveDown: "Descendre",
		sortOrder: "Trier les diagrammes via les étiquettes de catégorie",
		ascending: "Croissant",
		descending: "Décroissant",
		chartType: "Type de diagramme",
		column: "Histogramme",
		bar: "Barres",
		line: "Courbes",
		pie: "Secteurs",
		chartColor: "Couleur du diagramme",
		showDataLabels: "Afficher les étiquettes de données",
		setSymbol: "Symbole de la sélection",
		setHighLightColor: "Couleur de mise en surbrillance",
		settings: "Paramètres",
		mapInterationOptions: "Options d’interaction cartographique",
		preview: "Aperçu",
		ok: "OK",
		cancel: "Annuler",
		close: "Fermer",
		setFilterTip: "Définissez le filtre correctement ",
		setChartTitleTip: "Définissez le titre du diagramme.",
		setChartTypeTip: "Sélectionnez au moins un type de diagramme.",
		setDataFieldTip: "Sélectionnez au moins un champ de valeur.",
		setOutputFieldTip: "Définissez les champs en sortie.",
		count: "Total",
		label: "Etiquette",
		horizontalAxis: "Axe horizontal",
		verticalAxis: "Axe vertical",
		dataLabels: "Etiquettes de données",
		color: "Couleur",
		colorful: "Coloré",
		monochromatic: "Monochromatique"
  })
);