define(
   ({
    _widgetLabel: "Graf",
    executeChartTip: "Kliknutím na jednu z následujících položek úloh vytvoříte graf.",
    invalidConfig: "Neplatná konfigurace.",
    noneChartTip: "Pro tento widget nebyla nakonfigurována žádná úloha grafů.",
    chartParams: "Možnosti",
    charts: "GRAFY",
    apply: "POUŽÍT",
    useSpatialFilter: "Použít prostorový filtr k omezení prvků",
    useCurrentMapExtent: "Pouze prvky protínající současnou oblast mapy",
    drawGraphicOnMap: "Pouze prvky protínající oblast definovanou uživatelem",
    chartResults: "Výsledky grafů",
    clearResults: "Smazat výsledky",
    noPermissionsMsg: "Nemáte oprávnění pro přístup k této službě.",
    specifySpatialFilterMsg: "Zadejte prostorový filtr pro tuto úlohu.",
    queryError: "Dotazování se nezdařilo.",
    noResults: "Žádný prvek nebyl nalezen.",
    category: "Kategorie",
    count: "Počet",
    label: "Štítek",
    horizontalAxis: "Vodorovná osa",
    verticalAxis: "Svislá osa",
    dataLabels: "Popisky dat",
    color: "Barva",
    colorful: "Barevné",
    monochromatic: "Monochromatické",
    tasks: "Úlohy",
    results: "Výsledky",
    applySpatialFilterToLimitResults: "Použít prostorový filtr k omezení výsledků",
    useCurrentExtentTip: "Zčásti nebo zcela v aktuálním rozsahu mapy",
    useDrawGraphicTip: "Zčásti nebo zcela v obrazci nakresleném v mapě",
    useFeaturesTip: "Na základě umístění prvků v jiné vrstvě",
    noSpatialLimitTip: "Neomezovat výsledky podle polohy",
    applySearchDistance: "Použít vyhledávací vzdálenost",
    spatialRelationship: "Prostorový vztah",
    relatedLayer: "Související vrstva",
    clear: "Vyprázdnit",
    bufferDistance: "Šířka obalové zóny",
    miles: "Míle",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    back: "Zpět",
    execute: "Spustit"
  })
);