define(
   ({
    _widgetLabel: "Αναγνώριση κατάστασης (Beta)",
    locate_incident: "Εντοπισμός περιστατικού",
    clear_incidents: "Απαλοιφή περιστατικών",
    reverse_geocoded_address: "Πλησιέστερη διεύθυνση",
    reverse_geocoded_error: "Μη διαθέσιμο",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    now: "ΤΩΡΑ",
    wind: "ΑΝΕΜΟΣ",
    SUN: "ΚΥΡ",
    MON: "ΔΕΥ",
    TUE: "ΤΡΙ",
    WED: "ΤΕΤ",
    THU: "ΠΕΜ",
    FRI: "ΠΑΡ",
    SAT: "ΣΑΒ",
    defaultTabMsg: "Δεν εντοπίστηκαν περιστατικά.",
    actionLabel: "Ορίστε ως περιστατικό",
    drawPoint: "Σχεδίαση σημείου",
    drawLine: "Σχεδίαση γραμμής",
    drawPolygon: "Σχεδίαση πολυγώνου",
    saveIncident: "Αποθήκευση περιστατικού",
    clearIncident: "Απαλοιφή περιστατικών",
    useMapExtent: "Χρήση της τρέχουσας έκτασης χάρτη",
    noFeaturesFound: "Δεν βρέθηκαν στοιχεία.",
    downloadCSV: "ΛΗΨΗ CSV",
    editComplete: "Το στοιχείο αποθηκεύτηκε με επιτυχία!",
    updateComplete: "Το στοιχείο ενημερώθηκε με επιτυχία!",
    deleteComplete: "Το στοιχείο διαγράφηκε με επιτυχία!",
    sum: "ΑΘΡ",
    min: "ΕΛΑΧ",
    max: "ΜΕΓ.",
    avg: "Μ.Ο.",
    count: "ΠΛΗΘΟΣ",
    area: "ΠΕΡΙΟΧΗ",
    length: "ΜΗΚΟΣ",
    notPolySave: "Να ορίσετε ακτίνα ζώνης επιρροής πριν αποθηκεύσετε.",
    update_btn: "Ενημέρωση",
    delete_btn: "Διαγραφή"
  })
);
