define(
   ({
    _widgetLabel: "Diagram",
    executeChartTip: "Kliknij jedno z podanych poniżej zadań, aby wykonać diagram.",
    invalidConfig: "Nieprawidłowa konfiguracja",
    noneChartTip: "Nie skonfigurowano żadnego zadania diagramu dla tego widżetu.",
    chartParams: "Opcje",
    charts: "DIAGRAMY",
    apply: "ZASTOSUJ",
    useSpatialFilter: "Użyj filtru przestrzennego, aby ograniczyć liczbę obiektów",
    useCurrentMapExtent: "Tylko obiekty, które przecinają obszar bieżącej mapy",
    drawGraphicOnMap: "Tylko obiekty, które przecinają zdefiniowany przez użytkownika obszar",
    chartResults: "Wyniki diagramu",
    clearResults: "Wyczyść wyniki",
    noPermissionsMsg: "Nie masz uprawnień dostępu do tej usługi.",
    specifySpatialFilterMsg: "Należy określić filtr przestrzenny dla tego zadania",
    queryError: "Wykonywanie zapytania nie powiodło się.",
    noResults: "Nie odnaleziono żadnego obiektu.",
    category: "Kategoria",
    count: "Liczba",
    label: "Etykieta",
    horizontalAxis: "Oś pozioma",
    verticalAxis: "Oś pionowa",
    dataLabels: "Etykiety danych",
    color: "Kolor",
    colorful: "Kolorowe",
    monochromatic: "Monochromatyczne",
    tasks: "Zadania",
    results: "Wyniki",
    applySpatialFilterToLimitResults: "Aby ograniczyć wyniki, zastosuj filtr przestrzenny",
    useCurrentExtentTip: "Częściowo lub całkowicie w bieżącym zasięgu mapy",
    useDrawGraphicTip: "Częściowo lub całkowicie w zasięgu narysowanego na mapie obszaru",
    useFeaturesTip: "Na podstawie ich lokalizacji względem obiektów na innej warstwie",
    noSpatialLimitTip: "Nie ograniczaj przestrzennie wyników wyszukiwania",
    applySearchDistance: "Zastosuj odległość wyszukiwania",
    spatialRelationship: "Zależność przestrzenna",
    relatedLayer: "Powiązana warstwa",
    clear: "Wyczyść",
    bufferDistance: "Odległość buforowania",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    back: "Powrót",
    execute: "Wykonaj"
  })
);