define(
   ({
    _widgetLabel: "Grafico",
    executeChartTip: "Fare clic su uno degli elementi attività seguenti per eseguire il grafico.",
    invalidConfig: "Configurazione non valida.",
    noneChartTip: "Nessuna attività grafico è stata configurata per questo widget.",
    chartParams: "Opzioni",
    charts: "GRAFICI",
    apply: "APPLICA",
    useSpatialFilter: "Usa filtro spaziale per limitare le feature",
    useCurrentMapExtent: "Solo le feature che intersecano l\'area della mappa corrente",
    drawGraphicOnMap: "Solo le feature che intersecano un\'area definita dall\'utente",
    chartResults: "Risultati grafico",
    clearResults: "Elimina risultati",
    noPermissionsMsg: "Non si dispone delle autorizzazioni per accedere al servizio.",
    specifySpatialFilterMsg: "Specificare il filtro spaziale per questa attività.",
    queryError: "Interrogazione non riuscita.",
    noResults: "Nessuna feature trovata.",
    category: "Categoria",
    count: "Conteggio",
    label: "Etichetta",
    horizontalAxis: "Asse orizzontale",
    verticalAxis: "Asse verticale",
    dataLabels: "Etichette dati",
    color: "Colore",
    colorful: "A colori",
    monochromatic: "Monocromatico",
    tasks: "Attività",
    results: "Risultati",
    applySpatialFilterToLimitResults: "Applica un filtro spaziale per limitare i risultati",
    useCurrentExtentTip: "Parzialmente o completamente all\'interno dell\'estensione mappa corrente",
    useDrawGraphicTip: "Parzialmente o completamente all\'interno della forma disegnata sulla mappa",
    useFeaturesTip: "In base alle posizioni relative alle feature in un altro layer",
    noSpatialLimitTip: "Non limitare spazialmente i risultati",
    applySearchDistance: "Applica a distanza di ricerca",
    spatialRelationship: "Relazione spaziale",
    relatedLayer: "Layer correlato",
    clear: "Azzera",
    bufferDistance: "Distanza di buffer",
    miles: "Miglia",
    kilometers: "Chilometri",
    feet: "Piede",
    meters: "Metri",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    back: "Indietro",
    execute: "Esegui"
  })
);