define(
   ({
    _widgetLabel: "Nhận biết Tình huống (Beta)",
    locate_incident: "Định vị Sự cố",
    clear_incidents: "Xóa Sự cố",
    reverse_geocoded_address: "Địa chỉ gần nhất",
    reverse_geocoded_error: "Không khả dụng",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Feet",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    now: "BÂY GIỜ",
    wind: "GIÓ",
    SUN: "CN",
    MON: "T2",
    TUE: "T3",
    WED: "T4",
    THU: "T5",
    FRI: "T6",
    SAT: "T7",
    defaultTabMsg: "Không có sự cố được xác định.",
    actionLabel: "Thiết lập Là Sự cố",
    drawPoint: "Vẽ Điểm",
    drawLine: "Vẽ Đường",
    drawPolygon: "Vẽ Đa giác",
    saveIncident: "Lưu Sự cố",
    clearIncident: "Xóa Sự cố",
    useMapExtent: "Sử dụng phạm vi bản đồ hiện tại",
    noFeaturesFound: "Không tìm thấy đối tượng.",
    downloadCSV: "TẢI XUỐNG CSV",
    editComplete: "Đã lưu thành công đối tượng!",
    updateComplete: "Đã cập nhật thành công đối tượng!",
    deleteComplete: "Đã xóa thành công đối tượng!",
    sum: "TỔNG",
    min: "TỐI THIỂU",
    max: "Tối đa",
    avg: "TRUNG BÌNH",
    count: "SỐ LƯỢNG",
    area: "DIỆN TÍCH",
    length: "ĐỘ DÀI",
    notPolySave: "Vui lòng xác định khoảng cách vùng đệm trước khi lưu.",
    update_btn: "Cập nhật",
    delete_btn: "Xóa"
  })
);
