define(
   ({
    selectAnalysisTools:"Sélectionnez les outils d\'analyse à utiliser dans le widget.",
    selected: "sélectionné",
    name: "Nom",
    graphicalDisplay:"Affichage graphique",
    usage: "Utilisation",
    settings: "Paramètres",
    toolSetting: "Définir les détails de l\'outil",
    toolLabel: "Nom d\'affichage de l\'outil",
    showHelpTip: "Affichez les liens d\'aide dans le widget",
    showCurrentMapExtent: "Afficher l\'option permettant d\'utiliser l\'étendue de la carte actuelle",
    showCredits: "Afficher l\'option <b>Afficher les crédits</b>",
    saveAsFeatureService: "Enregistrer le résultat dans le compte de l\'utilisateur",
    showReadyToUseLayers: "Afficher les couches prêtes à l\'emploi de l\'atlas mondial dynamique ArcGIS Online",
    toolNotAvailable: "Cet outil n\'est pas disponible, car la carte ne contient pas les couches d\'entités requises.",
    aggregatePoints:"Agréger les points",
    aggregatePointsUsage:"Agrège les points en polygones à l\'endroit où se situent les points.",
    calculateDensity:"Calculer la densité",
    calculateDensityUsage:"Crée une carte de densité à partir d\'entités ponctuelles ou linéaires en répartissant des quantités connues de certains phénomènes (représentés sous forme d\'attributs des points ou lignes) sur la carte.",
    connectOriginsToDestinations: "Relier les origines aux destinations",
    connectOriginsToDestinationsUsage: "Mesure le temps de trajet ou la distance à parcourir entre des paires de points.",
    createBuffers:"Créer des zones tampon",
    createBuffersUsage:"Crée des polygones de zone tampon à partir d\'entités en entrée.",
    createDriveTimeAreas:"Créer des zones isochrones",
    createDriveTimeAreasUsage:"Crée des polygones isochrones (ou des distances à parcourir) autour de points en entrée pour les valeurs isochrones données.",
    createViewshed:"Créer un champ de vision",
    createViewshedUsage:"Crée des zones visibles d\'après les emplacements que vous spécifiez.",
    createWatersheds:"Créer des bassins versants",
    createWatershedsUsage:"Crée des zones de captation d\'après les emplacements que vous spécifiez.",
    deriveNewLocations:"Dériver de nouveaux emplacements",
    deriveNewLocationsUsage:"Dérive de nouvelles entités à partir des couches en entrée qui correspondent à une requête que vous spécifiez.",
    dissolveBoundaries:"Fusionner les limites",
    dissolveBoundariesUsage:"Fusionne les polygones qui sont superposés ou qui partagent une limite commune.",
    enrichLayer:"Enrichir la couche",
    enrichLayerUsage:"Enrichit les entités en entrée de faits sur les personnes, lieux et commerces dans les environs.",
    extractData:"Extraire des données",
    extractDataDesc:"Extrait des données d\'une ou de plusieurs couches au sein d\'une étendue donnée.",
    findExistingLocations:"Identifier des emplacements existants",
    findExistingLocationsUsage:"Sélectionne des entités dans la couche en entrée qui correspondent à une requête attributaire et/ou spatiale que vous spécifiez.",
    findHotSpots:"Rechercher les points chauds",
    findHotSpotsUsage:"Recherche les grappes statistiquement significatives d\'entités en entrée ou de valeurs élevées/faibles.",
    findNearest:"Trouver le plus proche",
    findNearestUsage:"Pour chaque entité d\'une couche en entrée, recherche son entité la plus proche sur une autre couche.",
    findSimilarLocations:"Rechercher des emplacements similaires",
    findSimilarLocationsUsage:"Mesure la similarité des emplacements candidats par rapport à un ou plusieurs emplacements de référence.",
    interpolatePoints:"Interpoler les points",
    interpolatePointsUsage:"Prévoit les valeurs de nouveaux emplacements selon des mesures provenant d\'un ensemble de points.",
    mergeLayers:"Combiner les couches",
    mergeLayersUsage:"Combine les entités de plusieurs couches en une nouvelle couche.",
    overlayLayers:"Superposer les couches",
    overlayLayersUsage:"Fusionne plusieurs couches en une seule couche dont les informations issues des couches d\'origine sont préservées.",
    planRoutes:"Planifier des itinéraires",
    planRoutesUsage:"Détermine comment diviser efficacement des tâches parmi le personnel mobile.",
    summarizeNearby:"Synthétiser - A proximité",
    summarizeNearbyUsage:"Pour chaque entité d\'une couche en entrée, synthétise les données situées à une certaine distance des entités d\'une autre couche.",
    summarizeWithin:"Synthétiser - A l\'intérieur",
    summarizeWithinUsage:"Pour chaque polygone d\'une couche surfacique en entrée, synthétise les données situées à l\'intérieur par rapport aux entités d\'une autre couche.",
    traceDownstream:"Parcours aval",
    traceDownstreamUsage:"Détermine les chemins des flux vers l\'aval à partir des emplacements que vous spécifiez."
  })
);
