define(
   ({
    selectAnalysisTools:"Sélectionnez les outils d\'analyse à répertorier dans le widget.",
    selected: "sélectionné",
    name: "Nom",
    graphicalDisplay:"Affichage graphique",
    usage: "Utilisation",
    toolNotAvailable: "Cet outil n\'est pas disponible, car la carte ne contient pas les couches d\'entités requises.",
    aggregatePoints:"Agréger les points",
    aggregatePointsUsage:"Agrège les points en polygones à l\'endroit où se situent les points.",
    aggregatePointsInputTip: "Spécifiez la couche d\'entités ponctuelles qui sera agrégée en polygones dans la couche d\'entités surfaciques.",
    calculateDensity:"Calculer la densité",
    calculateDensityUsage:"Crée une carte de densité à partir d\'entités ponctuelles ou linéaires en répartissant des quantités connues de certains phénomènes (représentés sous forme d\'attributs des points ou lignes) sur la carte.",
    calculateDensityInputTip:"Spécifiez les entités ponctuelles ou linéaires à partir desquelles calculer la densité.",
    connectOriginsToDestinations: "Relier les origines aux destinations",
    connectOriginsToDestinationsUsage: "Mesure le temps de trajet ou la distance à parcourir entre des paires de points.",
    connectOriginsToDestinationsInputTip: "Spécifiez le ou les points de départ des itinéraires à générer.",
    createBuffers:"Créer des zones tampon",
    createBuffersUsage:"Crée des polygones de zone tampon à partir d\'entités en entrée.",
    createBuffersInputTip:"Spécifiez la couche d\'entités ponctuelles, linéaires ou surfaciques à buffériser.",
    createDriveTimeAreas:"Créer des zones isochrones",
    createDriveTimeAreasUsage:"Crée des polygones isochrones (ou des distances à parcourir) autour de points en entrée pour les valeurs isochrones données.",
    createDriveTimeAreasInputTip:"Spécifiez les points où les zones isochrones seront tracés.",
    createViewshed:"Créer un champ de vision",
    createViewshedUsage:"Crée des zones visibles d\'après les emplacements que vous spécifiez.",
    createViewshedInputTip:"Spécifiez les emplacements des points d\'observation afin d\'identifier les zones visibles.",
    createWatersheds:"Créer des bassins versants",
    createWatershedsUsage:"Crée des zones de captation d\'après les emplacements que vous spécifiez.",
    createWatershedsInputTip:"Spécifiez les entités ponctuelles utilisées pour calculer les bassins versants.",
    deriveNewLocations:"Dériver de nouveaux emplacements",
    deriveNewLocationsUsage:"Dérive de nouvelles entités à partir des couches en entrée qui correspondent à une requête que vous spécifiez.",
    deriveNewLocationsInputTip:"Spécifiez la couche d\'analyse à utiliser en entrée.",
    dissolveBoundaries:"Fusionner les limites",
    dissolveBoundariesUsage:"Fusionne les polygones qui sont superposés ou qui partagent une limite commune.",
    dissolveBoundariesInputTip:"Spécifiez la couche contenant les entités surfaciques qui seront fusionnées.",
    enrichLayer:"Enrichir la couche",
    enrichLayerUsage:"Enrichit les entités en entrée de faits sur les personnes, lieux et commerces dans les environs.",
    enrichLayerInputTip:"Spécifiez les entités à enrichir de nouvelles données.",
    extractData:"Extraire des données",
    extractDataDesc:"Extrait des données d\'une ou de plusieurs couches au sein d\'une étendue donnée.",
    extractDataInputTip:"Spécifiez la couche d\'entités en entrée à extraire.",
    findExistingLocations:"Identifier des emplacements existants",
    findExistingLocationsUsage:"Sélectionne des entités dans la couche en entrée qui correspondent à une requête attributaire et/ou spatiale que vous spécifiez.",
    findExistingLocationsInputTip:"Spécifiez les couches d\'analyse à utiliser en entrée.",
    findHotSpots:"Rechercher les points chauds",
    findHotSpotsUsage:"Recherche les grappes statistiquement significatives d\'entités en entrée ou de valeurs élevées/faibles.",
    findHotSpotsInputTip:"Spécifiez la couche d\'entités ponctuelles ou surfaciques pour laquelle les points chauds seront calculés.",
    findNearest:"Trouver le plus proche",
    findNearestUsage:"Pour chaque entité d\'une couche en entrée, recherche son entité la plus proche sur une autre couche.",
    findNearestInputTip:"Spécifiez les entités ponctuelles, linéaires ou surfaciques à partir desquelles rechercher les emplacements les plus proches.",
    findSimilarLocations:"Rechercher des emplacements similaires",
    findSimilarLocationsUsage:"Mesure la similarité des emplacements candidats par rapport à un ou plusieurs emplacements de référence.",
    findSimilarLocationsInputTip:"Spécifiez une couche d\'entités qui contient un ou plusieurs emplacements de référence par rapport auxquels la similarité des entités dans la couche de recherche sera évaluée.",
    interpolatePoints:"Interpoler les points",
    interpolatePointsUsage:"Prévoit les valeurs de nouveaux emplacements selon des mesures provenant d\'un ensemble de points.",
    interpolatePointsInputTip:"Spécifiez les entités ponctuelles qui seront interpolées.",
    mergeLayers:"Combiner les couches",
    mergeLayersUsage:"Combine les entités de plusieurs couches en une nouvelle couche.",
    mergeLayersInputTip:"Spécifiez la couche d\'entités à combiner avec la couche de combinaison.",
    overlayLayers:"Superposer les couches",
    overlayLayersUsage:"Fusionne plusieurs couches en une seule couche dont les informations issues des couches d\'origine sont préservées.",
    overlayLayersInputTip:"Spécifiez la couche d\'entités qui sera superposée à la couche de superposition.",
    planRoutes:"Planifier des itinéraires",
    planRoutesUsage:"Détermine comment diviser efficacement des tâches parmi le personnel mobile.",
    planRoutesInputTip:"Spécifiez les points par lesquels les véhicules, chauffeurs ou itinéraires doivent passer.",
    summarizeNearby:"Synthétiser - A proximité",
    summarizeNearbyUsage:"Pour chaque entité d\'une couche en entrée, synthétise les données situées à une certaine distance des entités d\'une autre couche.",
    summarizeNearbyInputTip:"Spécifiez la couche d\'entités ponctuelles, linéaires ou surfaciques à partir de laquelle les distances seront mesurées jusqu\'aux entités de la couche de synthétisation.",
    summarizeWithin:"Synthétiser - A l\'intérieur",
    summarizeWithinUsage:"Pour chaque polygone d\'une couche surfacique en entrée, synthétise les données situées à l\'intérieur par rapport aux entités d\'une autre couche.",
    summarizeWithinInputTip:"Spécifiez la couche d\'entités surfaciques vers laquelle effectuer la synthétisation.",
    traceDownstream:"Parcours aval",
    traceDownstreamUsage:"Détermine les chemins des flux vers l\'aval à partir des emplacements que vous spécifiez.",
    traceDownstreamInputTip:"Spécifiez les entités ponctuelles utilisées pour l\'emplacement de départ d\'un parcours aval."
  })
);
