define(
   ({
    layerSelect: "Sélectionner la couche d\'image",
    displayMeasureResultInPopup: "Afficher les résultats de mesure dans une fenêtre contextuelle",
    angularUnitSelect: "Unité angulaire par défaut",
    linearUnitSelect: "Unité linéaire par défaut",
    areaUnitSelect: "Unité de surface par défaut",
    displayOperationSelect: "Sélectionner les opérations de mesure",
    errorSectionMeasage: "Aucune des couches ne prend en charge les fonctionnalités de mesure.",
    unitLabel: {
      esriInches: "Pouces",
      esriFeet: "Pieds",
      esriYards: "Yards",
      esriMiles: "Miles",
      esriNauticalMiles: "Milles nautiques",
      esriMillimeters: "Millimètres",
      esriCentimeters: "Centimètres",
      esriDecimeters: "Décimètres",
      esriMeters: "Mètres",
      esriKilometers: "Kilomètres",
      esriDURadians: "Radians",
      esriDUDecimalDegrees: "Degrés",
      esriSquareInches: "Pouces carrés",
      esriSquareFeet: "Pieds carrés",
      esriSquareYards: "Yards carrés",
      esriAcres: "Acres",
      esriSquareMiles: "Miles carrés",
      esriSquareMillimeters: "Millimètres carrés",
      esriSquareCentimeters: "Centimètres carrés",
      esriSquareDecimeters: "Décimètres carrés",
      esriSquareMeters: "Mètres carrés",
      esriAres: "Ares",
      esriHectares: "Hectares",
      esriSquareKilometers: "Kilomètres carrés"
    },
    operationLabel: {
      esriMensurationPoint: "point",
      esriMensurationDistanceAndAngle: "Distance et angle",
      esriMensurationAreaAndPerimeter: "Superficie et périmètre",
      esriMensurationHeightFromBaseAndTop: "De la base au sommet",
      esriMensurationHeightFromBaseAndTopShadow: "Ombre de la base au sommet",
      esriMensurationHeightFromTopAndTopShadow: "Ombre du sommet au sommet",
      esriMensurationCentroid: "Centroïde",
      esriMensurationPoint3D: "Point (3D)",
      esriMensurationDistanceAndAngle3D: "Distance et angle (3D)",
      esriMensurationAreaAndPerimeter3D: "Superficie et périmètre (3D)",
      esriMensurationCentroid3D: "Centroïde (3D)"
    }
  })
);