define(
	 ({
		queries: "Päringuülesanded",
		addNew: "Lisa uus",
		setSource: "Määra",
		setDataSource: "Määra andmeallikas",
		name: "Nimi",
		querySource: "Andmeallikas",
		queryName: "Ülesande nimi",
		queryDefinition: "Filtri määratlus",
		resultsSetting: "Tulemuste seade",
		symbolSetting: "Sümboli seade",
		resultSettingTip: "Saate määrata, kuidas tulemused kuvatakse ja mida need hõlmavad.",
		resultItemTitle: "Tulemuse pealkiri",
		resultItemContent: "Tulemuse sisu",
		fieldsSetTip: "Kontrollige kuvatavaid välju. Väljade järjestuse muutmiseks, välja vormindamiseks või aliase värskendamiseks valige väli.",
		addField: "Lisa väli",
		visibility: "Nähtavus",
		alias: "Alias",
		specialType: "Eritüüp",
		actions: "Tegevused",
		none: "Pole",
		link: "Link",
		image: "Pilt",
		noField: "Väli puudub",
		operationalLayerTip: "Lisa tulemus töökihina",
		setLayerSymbolTip: "Määrake päringu tulemuste sümbol: ",
		setSelectedSymbolTip: "Määrake valitud objekti sümbol.",
		notUseFilter: "Ära kasuta filtrit",
		setSourceTip: "Määrake päringu allikas.",
		setFilterTip: "Määrake filter õigesti.",
		ok: "OK",
		cancel: "Tühista",
		noFilterTip: "Määratlemata filtriavaldiseta loendab see päringuülesanne kõik määratud andmeallika funktsioonid."
  })
);