define(
	 ({
		queries: "Päringuülesanded",
		addNew: "Lisa uus",
    queryLayer: "Päringukiht",
		setSource: "Määra",
		setDataSource: "Määra andmeallikas",
		name: "Nimi",
		querySource: "Andmeallikas",
		queryName: "Ülesande nimi",
		queryDefinition: "Filtri määratlus",
		resultsSetting: "Tulemuste seade",
		symbolSetting: "Sümboli seade",
		resultSettingTip: "Saate määrata, kuidas tulemused kuvatakse ja mida need hõlmavad.",
		resultItemTitle: "Tulemuse pealkiri",
		resultItemContent: "Tulemuse sisu",
		fieldsSetTip: "Kontrollige kuvatavaid välju. Väljade järjestuse muutmiseks, välja vormindamiseks või aliase värskendamiseks valige väli.",
		addField: "Lisa väli",
		visibility: "Nähtavus",
		alias: "Alias",
		specialType: "Eritüüp",
		actions: "Tegevused",
		none: "Pole",
		link: "Link",
		image: "Pilt",
		noField: "Väli puudub",
		operationalLayerTip: "Lisa tulemus töökihina",
		setLayerSymbolTip: "Määrake päringu tulemuste sümbol: ",
		setSelectedSymbolTip: "Määrake valitud objekti sümbol.",
		notUseFilter: "Ära kasuta filtrit",
		setSourceTip: "Määrake päringu allikas.",
		setFilterTip: "Määrake filter õigesti.",
		ok: "OK",
		cancel: "Tühista",
		noFilterTip: "Määratlemata filtriavaldiseta loendab see päringuülesanne kõik määratud andmeallika funktsioonid.",
    relationships: "Seosed",
    addRelationshipLayer: "Lisa uus seos",
    relatedTo: "Seotud",
    selectOption: "Valige...",
    resultItemSorting: "Tulemuse üksuste sortimine",
    field: "Väli",
    sortingOrder: "Järjekord",
    configureFieldsTip: "Palun konfigureerige väljad, mille järgi päringutulemusi sorditakse.",
    setSortingFields: "Määra sortimisväljad",
    ascending: "Kahanev",
    descending: "Kahanev",
    sortBy: "Sorteeri:",
    thenBy: "Seejärel",
    addTask: "Lisa toiming",
    noTasksTip: 'Toiminguid pole, alustamiseks klõpsake käsku ${addTask}!',
    infoText: "Teave",
    filters: "Filtrid",
    results: "Tulemused",
    optionsText: "Seaded",
    summaryText: "Kokkuvõte",
    attributeFilter: "Atribuudifilter",
    attributeFilterTip: "Määratlege atribuudiavaldised, mida kasutatakse vidinas päringukihi filtreerimiseks.",
    noExpressionDefinedTip: "Ühtki avaldist pole määratletud.",
    needInputValuesTip: "Käitusaja käigus tuleb sisestada väärtused",
    setExpressions: "Määra avaldised",
    spatialFilter: "Ruumifilter",
    spatialFilterTip: "Valige vidinas tulemuste piiramiseks ruumiline filter (filtrid).",
    defaultOption: "Vaikimisi",
    useCurrentExtentTip: "Osaliselt või täielikult praeguses kaardi kuvaulatuses",
    useDrawGraphicTip: "Osaliselt või täielikult kaardile joonistatud kujundis",
    useFeaturesTip: "Vastavalt nende asukohale teise kihi objektide suhtes",
    noSpatialLimitTip: "Ära piira tulemusi ruumiliselt",
    drawingTools: "Joonistamise töövahendid",
    bufferSettings: "Puhvri seaded",
    defaultDistance: "Vaike-vahemaa",
    bufferDistance: "Puhvri ulatus",
    defaultUnit: "Vaikeühik",
    miles: "Miilid",
    kilometers: "Kilomeetrid",
    feet: "Jalad",
    meters: "Meetrid",
    yards: "Jardid",
    nauticalMiles: "Meremiilid",
    availableSpatialRelationships: "Saadaolevad ruumilised seosed",
    setSpatialRelationships: "Määra ruumilised seosed",
    availability: "Saadavus",
    relationship: "Seos",
    label: "Märgis",
    intersect: "lõikuvad",
    contain: "sisaldavad",
    areContainedIn: "sisalduvad",
    cross: "rist",
    envelopeIntersect: "lõikuvad ümbrisega",
    overlap: "ülekattes",
    areOverlapped: "kaetakse",
    touche: "puutuvad kokku",
    within: "vahemikus",
    areWithin: "on vahemikus",
    indexIntersect: "lõikuvad indeksiga",
    itemTitle: "Üksuse pealkiri",
    displayFields: "Kuvamise väljad",
    sortingFields: "Sortimise väljad",
    setDisplayFields: "Määra kuvamise väljad",
    symbol: "Sümbol",
    setSymbol: "Määra sümbol",
    serviceSymbolTip: "Kasuta kihi kaudu määratud sümboleid",
    exportTip: "Kuva eksportimise nuppu",
    keepResultsTip: "Säilita tulemused kaardil pärast vidina sulgemist",
    queryRelatedRecords: "Seotud kirjete päring",
    createLayerForTaskTip: "Määrake, kuidas toiming loob kihte",
    oneLayerForTaskTip: "Loo selle toimingu jaoks ainult üks kiht",
    multipleLayerForTaskTip: "Loo uus kiht iga kord, kui see toiming käivitub"
  })
);
