define(
   ({
    _widgetLabel: "Interrogazione",
    executeQueryTip: "Fare clic su uno degli elementi attività seguenti per eseguire la query.",
    invalidConfig: "Configurazione non valida. Utilizzare la pagina delle impostazioni interrogazione per ottenere la configurazione corretta.",
    queryParams: "Opzioni",
    parameters: "OPZIONI",
    queries: "INTERROGAZIONI",
    apply: "APPLICA",
    queryResults: "Risultati",
    clear: "Cancella",
    noResults: "Nessuna feature trovata.",
    queryError: "Interrogazione non riuscita.",
    numberFound: "Numero di feature trovate",
    mapExtentTip: "Limita i risultati all\'area della mappa corrente.",
    noValue: "Valore non disponibile",
    and: "e",
    stringOperatorIs: "è", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "non è",
    stringOperatorStartsWith: "inizia con",
    stringOperatorEndsWith: "termina con",
    stringOperatorContains: "contiene",
    stringOperatorDoesNotContain: "non contiene",
    stringOperatorIsBlank: "è vuoto",
    stringOperatorIsNotBlank: "non è vuoto",
    dateOperatorIsOn: "ricorre il giorno", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "non ricorre il giorno",
    dateOperatorIsBefore: "ricorre prima del giorno",
    dateOperatorIsAfter: "ricorre dopo il giorno",
    dateOperatorDays: "giorni",
    dateOperatorWeeks: "settimane", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "mesi",
    dateOperatorInTheLast: "negli ultimi/nelle ultime",
    dateOperatorNotInTheLast: "non negli ultimi/nelle ultime",
    dateOperatorIsBetween: "è compreso tra",
    dateOperatorIsNotBetween: "non è compreso tra",
    dateOperatorIsBlank: "è vuoto",
    dateOperatorIsNotBlank: "non è vuoto",
    numberOperatorIs: "è", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "non è",
    numberOperatorIsAtLeast: "è almeno",
    numberOperatorIsLessThan: "è minore di",
    numberOperatorIsAtMost: "è al massimo",
    numberOperatorIsGreaterThan: "è maggiore di",
    numberOperatorIsBetween: "è compreso tra",
    numberOperatorIsNotBetween: "non è compreso tra",
    numberOperatorIsBlank: "è vuoto",
    numberOperatorIsNotBlank: "non è vuoto",
    operationalLayerTip: "Aggiungi risultato come layer operativo",
    queryResult: "Risultato interrogazione",
    specifyParamsTip: "Specificare i parametri per l'attività",
    useSpatialFilter: "Usa filtro spaziale per limitare le feature",
    useCurrentMapExtent: "Solo le feature che intersecano l\'area della mappa corrente",
    drawGraphicOnMap: "Solo le feature che intersecano l\'area definita dall\'utente",
    specifySpatialFilterMsg: "Specificare il filtro spaziale per questa attività.",
    clearResults: "Elimina risultati",
    operationalTip: 'Se questa opzione è selezionata, i risultati verranno mantenuti sulla mappa finché non si fa clic sul pulsante \"${clearResults}\".',
    noneQueryTip: "Nessuna attività di interrogazione è stata configurata per questo widget.",
    noPermissionsMsg: "Non si dispone delle autorizzazioni per accedere al servizio.",
    attributesFromRelationship: "Attributi da tabella correlata",
    tasks: "Attività",
    applySpatialFilterToLimitResults: "Applica un filtro spaziale per limitare i risultati",
    useCurrentExtentTip: "Parzialmente o completamente all\'interno dell\'estensione mappa corrente",
    useDrawGraphicTip: "Parzialmente o completamente all\'interno della forma disegnata sulla mappa",
    useFeaturesTip: "In base alle posizioni relative alle feature in un altro layer",
    noSpatialLimitTip: "Non limitare spazialmente i risultati",
    applySearchDistance: "Applica a distanza di ricerca",
    spatialRelationship: "Relazione spaziale",
    relatedLayer: "Layer correlato",
    bufferDistance: "Distanza di buffer",
    miles: "Miglia",
    kilometers: "Chilometri",
    feet: "Piede",
    meters: "Metri",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    back: "Indietro",
    execute: "Esegui"
  })
);