define(
   ({
    "tabs_section_Label": "Закладки",
    "addTab": "Добавить вкладку",
    "layerName": "Слой",
    "layerType": "Тип анализа",
    "layerLabel": "Подпись",
    "actions": "Действия",
    "closest": "Ближайший объект",
    "proximity": "Близость",
    "summary": "Краткая информация",
    "select_lbl": "-- Выбрать --",
    "general_setting_Label": "Общие параметры",
    "units_text_lbl": "Единицы расстояния",
    "miles": "Мили",
    "kilometers": "Километры",
    "feet": "Футы",
    "meters": "Метры",
    "yards": "Ярды",
    "nauticalMiles": "Морские мили",
    "maximum_distance_lbl": "Максимальное расстояние до ближайшего объекта",
    "buffer_text_lbl": "Буфер надписей",
    "buffer_lbl": "Буферное расстояние",
    "buffer_max_lbl": "Максимальное буферное расстояние",
    "buffer_min_lbl": "Минимальное буферное расстояние",
    "routing_checkBox": "Включить маршрутизацию",
    "weather_Label": "Опции погоды",
    "weather_checkBox": "Включить информацию о погоде",
    "selectLayers": "Выбрать слои погоды",
    "currentlySelectedLayer": "Выбранные слои погоды",
    "missingTabLabel": "В надписи не хватает одной вкладки",
    "cancel": "Отмена",
    "ok": "OK",
    "missingLayerInWebMap": "Не найдено рабочих слоев.",
    "selectFields": "Выбрать поля",
    "addField": "Добавить поле",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Показать количество",
    "area_checkBox": "Показать площадь",
    "length_checkBox": "Показать длину",
    "max_records": "Достигнуто максимальное ограничение",
    "save_label": "Опции сохранения",
    "save_checkbox": "Включить сохранение",
    "csv_label": "Опции CSV",
    "csv_checkbox": "Экспортировать все поля в слое.",
    "display_label": "Опции отображения",
    "display_checkbox": "Отобразить суммарные объекты",
    "must_select_template": "Выберите один из шаблонов редактирования в Опциях сохранения."
  })
);
