define(
   ({
    _widgetLabel: "状況認識 (ベータ版)",
    locate_incident: "インシデントの特定",
    clear_incidents: "インシデントの消去",
    reverse_geocoded_address: "最も近い住所",
    reverse_geocoded_error: "利用不可",
    miles: "マイル",
    kilometers: "キロメートル",
    feet: "フィート",
    meters: "メートル",
    yards: "ヤード",
    nauticalMiles: "海里",
    now: "現在",
    wind: "風",
    SUN: "日",
    MON: "月",
    TUE: "火",
    WED: "水",
    THU: "木",
    FRI: "金",
    SAT: "土",
    defaultTabMsg: "インシデントが見つかりません。",
    actionLabel: "インシデントとして設定",
    drawPoint: "ポイントの描画",
    drawLine: "ラインの描画",
    drawPolygon: "ポリゴンの描画",
    saveIncident: "インシデントの保存",
    clearIncident: "インシデントの消去",
    useMapExtent: "現在のマップ範囲を使用",
    noFeaturesFound: "フィーチャは見つかりませんでした。",
    downloadCSV: "CSV のダウンロード",
    editComplete: "フィーチャが正常に保存されました",
    updateComplete: "フィーチャが正常に更新されました",
    deleteComplete: "フィーチャが正常に削除されました",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH",
    notPolySave: "バッファー距離を指定してから保存してください。",
    update_btn: "更新",
    delete_btn: "削除"
  })
);
