define(
   ({
    selectAnalysisTools:"Atlasiet logrīkā izmantojamos analīzes logrīkus.",
    selected: "izraudzīts",
    name: "Nosaukums",
    graphicalDisplay:"Grafiskais attēlojums",
    usage: "Lietojums",
    settings: "Iestatījumi",
    toolSetting: "Iestatiet detalizētu rīka informāciju",
    toolLabel: "Rīka nosaukums displejā",
    showHelpTip: "Parādīt logrīkā palīdzības saites",
    showCurrentMapExtent: "Rādīt pašreizējā kartes pārklājuma lietošanas opciju",
    showCredits: "Parādīt opciju <b>Rādīt kredītus</b>",
    saveAsFeatureService: "Saglabāt rezultātus lietotāja kontā",
    showReadyToUseLayers: "Rādīt ArcGIS tiešsaistes Living Atlas gatavos slāņus",
    toolNotAvailable: "Šis rīks nav pieejams, jo kartē neietilpst nepieciešamais(ie) elementu slānis(ņi).",
    aggregatePoints:"Apkopot punktus",
    aggregatePointsUsage:"Apkopojiet punktus laukumos, kuros šie punkti ir izvietoti.",
    calculateDensity:"Aprēķināt blīvumu",
    calculateDensityUsage:"Izveidojiet blīvuma karti no punktu vai līniju elementiem, izklājot kartē kādas parādības zināmo daudzumu (attēlots kā punktu vai līniju atribūti).",
    connectOriginsToDestinations: "Savienot sākumpunktus ar galamērķi.",
    connectOriginsToDestinationsUsage: "Izmēriet ceļojuma laiku vai attālumu starp punktu pāriem.",
    createBuffers:"Izveidot buferzonas",
    createBuffersUsage:"Izveidojiet buferzonu laukumus no ievades elementiem.",
    createDriveTimeAreas:"Izveidot braukšanas laika laukumus",
    createDriveTimeAreasUsage:"Izveidojiet braukšanas laika (vai braukšanas attāluma) laukums ap ievades punktiem attiecībā uz norādītajām braukšanas laika vērtībām.",
    createViewshed:"Izveidot skata aizsegumu",
    createViewshedUsage:"Izveido redzamos apgabalus, pamatojoties uz norādītajām atrašanās vietām.",
    createWatersheds:"Izveidot ūdensšķirtnes",
    createWatershedsUsage:"Izveido sateces apgabalus, pamatojoties uz norādītajām atrašanās vietām.",
    deriveNewLocations:"Atvasināt jaunus izvietojumus",
    deriveNewLocationsUsage:"Atvasiniet jaunus elementus no ievades slāņiem, kas atbilst jūsu norādītajam vaicājumam",
    dissolveBoundaries:"Noņemt robežas",
    dissolveBoundariesUsage:"Noņemiet to laukumu robežas, kas pārklājas vai koplieto kādu kopīgu robežu.",
    enrichLayer:"Bagātināt slāni.",
    enrichLayerUsage:"Papildiniet ievades elementus ar personām, vietām un biznesa faktiem par tuvumā esošajām teritorijām.",
    extractData:"Izvilkt datus",
    extractDataDesc:"Izvelciet datus no viena vai vairākiem slāņiem norādītā pārklājuma robežās",
    findExistingLocations:"Atrast esošos izvietojumus",
    findExistingLocationsUsage:"Atlasiet elementus ievades slānī, kas atbilst jūsu norādītajam atribūta un/vai telpiskajam vaicājumam",
    findHotSpots:"Atrast karstos punktus",
    findHotSpotsUsage:"Atrodiet statistisko būtiskos ievades elementu vai augstu/zemu vērtību klasterus.",
    findNearest:"Atrast tuvāko",
    findNearestUsage:"Katram ievades slānī esošam elementam atrodiet tā tuvāko elementu citā slānī",
    findSimilarLocations:"Atrast līdzīgus izvietojumus",
    findSimilarLocationsUsage:"Izmēriet kandidātu izvietojumu līdzību ar vienu vai vairākiem atsauces izvietojumiem.",
    interpolatePoints:"Interpolēt punktus",
    interpolatePointsUsage:"Nosakiet vērtības jaunos izvietojumos, ņemot vērā mērījumus no punktu kolekcijām.",
    mergeLayers:"Apvienot slāņus",
    mergeLayersUsage:"Apvienojiet elementus no vairākiem slāņiem jaunā slānī",
    overlayLayers:"Pārklājuma slāņi",
    overlayLayersUsage:"Apvienojiet vairākus slāņus vienā slāni, saglabājot oriģinālo slāņu informāciju.",
    planRoutes:"Plānot maršrutus.",
    planRoutesUsage:"Nosakiet, kā efektīvi sadalīt uzdevumus starp mobilo darbaspēku.",
    summarizeNearby:"Apkopot blakus",
    summarizeNearbyUsage:"Katram ievades slānī esošajam elementam apkopojiet datus, ņemot vērā attālumu no elementiem citā slānī.",
    summarizeWithin:"Apkopot ietvaros",
    summarizeWithinUsage:"Katram laukumam, kas atrodas ievades laukumu slānī, apkopojiet tajā esošos datus no elementiem citā slānī.",
    traceDownstream:"Izsekot straumes lejteci",
    traceDownstreamUsage:"Nosaka plūsmas ceļu lejteces virzienā no jūsu norādītās vietas."
  })
);
