define(
   ({
    selectAnalysisTools:"Izvēlieties logrīkā uzskaitāmos analīzes rīkus.",
    selected: "izraudzīts",
    name: "Nosaukums",
    graphicalDisplay:"Grafiskais attēlojums",
    usage: "Lietojums",
    toolNotAvailable: "Šis rīks nav pieejams, jo kartē neietilpst nepieciešamais(ie) elementu slānis(ņi).",
    aggregatePoints:"Apkopot punktus",
    aggregatePointsUsage:"Apkopojiet punktus laukumos, kuros šie punkti ir izvietoti.",
    aggregatePointsInputTip: "Norādiet punktu elementu slāni, kas tiks apkopoti laukumos laukumu elementu slānī.",
    calculateDensity:"Aprēķināt blīvumu",
    calculateDensityUsage:"Izveidojiet blīvuma karti no punktu vai līniju elementiem, izklājot kartē kādas parādības zināmo daudzumu (attēlots kā punktu vai līniju atribūti).",
    calculateDensityInputTip:"Norādiet to punktu vai līniju elementus, no kuriem jāaprēķina blīvums.",
    connectOriginsToDestinations: "Savienot sÄkumpunktus ar galamÄ“rÄ·iem",
    connectOriginsToDestinationsUsage: "Izmēriet ceļojuma laiku vai attālumu starp punktu pāriem.",
    connectOriginsToDestinationsInputTip: "Norādiet ģenerējamo maršrutu punktus vai sākuma punktus.",
    createBuffers:"Izveidot buferzonas",
    createBuffersUsage:"Izveidojiet buferzonu laukumus no ievades elementiem.",
    createBuffersInputTip:"Norādiet punktu, līniju vai laukumu elementu slāni, kam izveidot buferzonu.",
    createDriveTimeAreas:"Izveidot braukšanas laika laukumus",
    createDriveTimeAreasUsage:"Izveidojiet braukšanas laika (vai braukšanas attāluma) laukums ap ievades punktiem attiecībā uz norādītajām braukšanas laika vērtībām.",
    createDriveTimeAreasInputTip:"Norādiet punktus, kur tiks zīmēti braukšanas laika laukumi.",
    createViewshed:"Izveidot skata aizsegumu",
    createViewshedUsage:"Izveido redzamos apgabalus, pamatojoties uz norÄdÄ«tajÄm atraÅanÄs vietÄm.",
    createViewshedInputTip:"Norādiet vērotāja izvietojumus, lai noteiktu redzamās teritorijas.",
    createWatersheds:"Izveidot Å«densgÅ«tves baseinus",
    createWatershedsUsage:"Izveido sateces apgabalus, pamatojoties uz norÄdÄ«tajÄm atraÅanÄs vietÄm.",
    createWatershedsInputTip:"Norādiet punktu elementus, kas tiek izmantoti ūdenskrātuvju aprēķināšanai.",
    deriveNewLocations:"Atvasināt jaunus izvietojumus",
    deriveNewLocationsUsage:"Atvasiniet jaunus elementus no ievades slāņiem, kas atbilst jūsu norādītajam vaicājumam",
    deriveNewLocationsInputTip:"Norādiet analīzes slāni, kas tiks izmantots kā ievade.",
    dissolveBoundaries:"Noņemt robežas",
    dissolveBoundariesUsage:"Noņemiet to laukumu robežas, kas pārklājas vai koplieto kādu kopīgu robežu.",
    dissolveBoundariesInputTip:"Norādiet slāni, kurā ietilpst laukumu elementi, kuriem tiks noņemtas robežas.",
    enrichLayer:"BagÄtinÄt slÄni",
    enrichLayerUsage:"Papildiniet ievades elementus ar personām, vietām un biznesa faktiem par tuvumā esošajām teritorijām.",
    enrichLayerInputTip:"Norādiet elementus, ko bagātināt ar jaunajiem datiem.",
    extractData:"Izvilkt datus",
    extractDataDesc:"Izvelciet datus no viena vai vairākiem slāņiem norādītā pārklājuma robežās",
    extractDataInputTip:"Norādiet izvelkamo ievades elementu slāni.",
    findExistingLocations:"Atrast esošos izvietojumus",
    findExistingLocationsUsage:"Atlasiet elementus ievades slānī, kas atbilst jūsu norādītajam atribūta un/vai telpiskajam vaicājumam",
    findExistingLocationsInputTip:"Norādiet analīzes slāņus, kas tiks izmantoti kā ievade.",
    findHotSpots:"Atrast karstos punktus",
    findHotSpotsUsage:"Atrodiet statistisko būtiskos ievades elementu vai augstu/zemu vērtību klasterus.",
    findHotSpotsInputTip:"Norādiet punktu vai laukumu elementu slāni, kuram tiks aprēķināti karstie punkti.",
    findNearest:"Atrast tuvÄko",
    findNearestUsage:"Katram ievades slānī esošam elementam atrodiet tā tuvāko elementu citā slānī",
    findNearestInputTip:"Norādiet punktu, līniju vai laukumu elementus, no kuriem tiks atrasti tuvākie izvietojumi.",
    findSimilarLocations:"Atrast līdzīgus izvietojumus",
    findSimilarLocationsUsage:"Izmēriet kandidātu izvietojumu līdzību ar vienu vai vairākiem atsauces izvietojumiem.",
    findSimilarLocationsInputTip:"Norādiet elementu slāni, kurā ietilpst viens vai vairāki atsauces izvietojumi, saskaņā ar kuriem tiks novērtēta meklēšanas slānī esošo elementu līdzība.",
    interpolatePoints:"Interpolēt punktus",
    interpolatePointsUsage:"Nosakiet vērtības jaunos izvietojumos, ņemot vērā mērījumus no punktu kolekcijām.",
    interpolatePointsInputTip:"Norādiet punktu elementus, kas tiks interpolēti.",
    mergeLayers:"Apvienot slāņus",
    mergeLayersUsage:"Apvienojiet elementus no vairākiem slāņiem jaunā slānī",
    mergeLayersInputTip:"Norādiet elementu slāni, kas jāapvieno ar apvienojamo slāni.",
    overlayLayers:"Pārklājuma slāņi",
    overlayLayersUsage:"Apvienojiet vairākus slāņus vienā slāni, saglabājot oriģinālo slāņu informāciju.",
    overlayLayersInputTip:"Norādiet to elementu slāni, kas tiks pārklāts ar pārklājuma slāni.",
    planRoutes:"PlÄnot marÅrutus",
    planRoutesUsage:"Nosakiet, kā efektīvi sadalīt uzdevumus starp mobilo darbaspēku.",
    planRoutesInputTip:"Norādiet punktus, kas jāapmeklē transportlīdzekļiem, vadītājiem vai pa kuriem jāvirzās maršrutiem.",
    summarizeNearby:"Apkopot blakus",
    summarizeNearbyUsage:"Katram ievades slānī esošajam elementam apkopojiet datus, ņemot vērā attālumu no elementiem citā slānī.",
    summarizeNearbyInputTip:"Norādiet punktu, līniju vai laukumu elementu slāni, no kura tiks mērīti attālumi līdz elementiem apkopotajā slānī.",
    summarizeWithin:"Apkopot ietvaros",
    summarizeWithinUsage:"Katram laukumam, kas atrodas ievades laukumu slānī, apkopojiet tajā esošos datus no elementiem citā slānī.",
    summarizeWithinInputTip:"Norādiet laukumu elementu slāni, uz kuru tiks veikta apkopošana.",
    traceDownstream:"Izsekot straumes lejteci",
    traceDownstreamUsage:"Nosaka plÅ«smas ceÄ¼us virzienÄ uz lejteci no norÄdÄ«tajÄm vietÄm.",
    traceDownstreamInputTip:"Norādiet punktu elementus, kas tiek izmantoti lejteces ceļa sākuma izvietojumam."
  })
);
