define(
   ({
    taskUrl: "URL υπηρεσίας",
    serviceURLPlaceholder: "Εισαγάγετε το URL της υπηρεσίας γεωεπεξεργασίας",
    ok: "ΟΚ",
    cancel: "Ακύρωση",
    layer: "Θεματικό Επίπεδο",
    action: "Ενέργεια",
    input: "Είσοδος",
    output: "Έξοδος",
    name: "Όνομα",
    type: "Τύπος",
    required: "Απαιτείται",
    layerOrder: "Διάταξη θεματικών επιπέδων",
    options: "Επιλογές",
    defaultValue: "Προκαθορισμένη τιμή",
    inputFeatureBy: "Καθορισμός στοιχείου εισόδου με",
    renderer: "Απεικόνιση",
    displayType: "Τύπος εμφάνισης",
    label: "Ετικέτα",
    tooltip: "Tooltip",
    visible: "Ορατό",
    helpUrl: "URL βοήθειας",
    useResultMapService: "Χρησιμοποιήστε τις επιλογές σχεδιασμού της εξαγόμενης χαρτογραφικής υπηρεσίας",
    drawOnMap: "Διαδραστική σχεδίαση στο χάρτη",
    selectLayer: "Επιλογή θεματικού επιπέδου από τον χάρτη",
    url: "URL",
    symbol: "Σύμβολο",
    shareResults: "Προσθήκη αποτελέσματος ως επιχειρησιακό επίπεδο",
    popup: "Αναδυόμενο παράθυρο",
    setTask: "Ορισμός",
    setTaskTitle: "Ορισμός εργασίας GP",
    enablePopup: "Ενεργοποίηση αναδυόμενου παραθύρου",
    unSupportGeometryType: "Δεν είναι δυνατός ο καθορισμός της απεικόνισης λόγω άγνωστου τύπου γεωμετρίας.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Φόρτωση αρχείου",
    selectFileToUpload: "Επιλογή αρχείου...",
    upload: "Μεταφόρτωση",
    rasterFormat: "Μορφότυπος πλεγματικών δεδομένων",
    noFileSelected: "Δεν επιλέχθηκε αρχείο!",
    uploadSuccess:"Το αρχείο φορτώθηκε με επιτυχία!",
    showLayerContent: "Εμφάνιση περιεχομένου θεματικού επιπέδου",
    Feet: "Πόδια",
    Yards: "Γιάρδες",
    Miles: "Μίλια",
    NauticalMiles: "Ναυτικά μίλια",
    Meter: "Μέτρα",
    Kilometers: "Χιλιόμετρα",
    urlPlaceholder: "URL συνόλου στοιχείων",
    allowToExport: "Να επιτραπεί η εξαγωγή αποτελεσμάτων"
  })
);
