define(
	 ({
		queries: "Consultas",
		addNew: "Adicionar Nova",
		setSource: "Definir",
		setDataSource: "Definir Fonte dos Dados",
		name: "Nome",
		querySource: "Fonte da Dados",
		queryName: "Nome da Tarefa",
		queryDefinition: "Definição do Filtro",
		resultsSetting: "Definição de Resultados",
		symbolSetting: "Definições de símbolos",
		resultSettingTip: "Defina o quê e como exibir os resultados de saída.",
		resultItemTitle: "Título do Item Resultante",
		resultItemContent: "Conteúdo do Item Resultante",
		fieldsSetTip: "Marque os campos que pretende exibir. Selecione um campo para atualizar o seu nome alternativo, ordená-lo e formatá-lo.",
		addField: "Adicionar Campo",
		visibility: "Visibilidade",
		alias: "Nome Alternativo",
		specialType: "Tipo Especial",
		actions: "Ações",
		none: "Nenhum",
		link: "Ligação",
		image: "Imagem",
		noField: "Sem Campo",
		operationalLayerTip: "Adicionar resultado como camada operacional",
		setLayerSymbolTip: "Definir o símbolo para os resultados da consulta. ",
		setSelectedSymbolTip: "Definir o símbolo do elemento selecionado.",
		notUseFilter: "Não utilizar filtro",
		setSourceTip: "Por favor, defina a fonte da consulta.",
		setFilterTip: "Por favor, defina o filtro corretamente.",
		ok: "Ok",
		cancel: "Cancelar",
		noFilterTip: "Sem uma expressão de filtro definida, esta tarefa de consulta irá listar todos os elementos na fonte de dados especificada."
  })
);