define(
	 ({
		queries: "Consultas",
		addNew: "Adicionar Nova",
    queryLayer: "Camada de Consulta",
		setSource: "Definir",
		setDataSource: "Definir Fonte dos Dados",
		name: "Nome",
		querySource: "Fonte da Dados",
		queryName: "Nome da Tarefa",
		queryDefinition: "Definição do Filtro",
		resultsSetting: "Definição de Resultados",
		symbolSetting: "Definições de símbolos",
		resultSettingTip: "Defina o quê e como exibir os resultados de saída.",
		resultItemTitle: "Título do Item Resultante",
		resultItemContent: "Conteúdo do Item Resultante",
		fieldsSetTip: "Marque os campos que pretende exibir. Selecione um campo para atualizar o seu nome alternativo, ordená-lo e formatá-lo.",
		addField: "Adicionar Campo",
		visibility: "Visibilidade",
		alias: "Nome Alternativo",
		specialType: "Tipo Especial",
		actions: "Ações",
		none: "Nenhum",
		link: "Ligação",
		image: "Imagem",
		noField: "Sem Campo",
		operationalLayerTip: "Adicionar resultado como camada operacional",
		setLayerSymbolTip: "Definir o símbolo para os resultados da consulta. ",
		setSelectedSymbolTip: "Definir o símbolo do elemento selecionado.",
		notUseFilter: "Não utilizar filtro",
		setSourceTip: "Por favor, defina a fonte da consulta.",
		setFilterTip: "Por favor, defina o filtro corretamente.",
		ok: "Ok",
		cancel: "Cancelar",
		noFilterTip: "Sem uma expressão de filtro definida, esta tarefa de consulta irá listar todos os elementos na fonte de dados especificada.",
    relationships: "Relações",
    addRelationshipLayer: "Adicionar Nova Relação",
    relatedTo: "Relacionado com",
    selectOption: "Por favor, selecione..",
    resultItemSorting: "Classificando Resultado de Item",
    field: "Campo",
    sortingOrder: "Ordem",
    configureFieldsTip: "Por favor configure os campos nos quais o resultado da consulta será ordenada por.",
    setSortingFields: "Definir Seleção Campos",
    ascending: "Ascendente",
    descending: "Decrescente",
    sortBy: "Ordenar por",
    thenBy: "De seguida por",
    addTask: "Adicionar Tarefa",
    noTasksTip: 'Sem tarefas, por favor clique em \"${addTask}\" para começar!',
    infoText: "Informação",
    filters: "Filtros",
    results: "Resultados",
    optionsText: "Opções",
    summaryText: "Resumo",
    attributeFilter: "Filtro de Atributos",
    attributeFilterTip: "Defina expressões de atributos para utilizar no widget para filtrar a camada da consulta.",
    noExpressionDefinedTip: "Não foi definida qualquer expressão.",
    needInputValuesTip: "É necessário introduzir valores no runtime",
    setExpressions: "Definir Expressões",
    spatialFilter: "Filtro Espacial",
    spatialFilterTip: "Escolha o(s) filtro(s) espacial(ais) utilizados no widget para limitar os resultados.",
    defaultOption: "Padrão",
    useCurrentExtentTip: "Parcialmente ou totalmente no contido na atual extensão de mapa",
    useDrawGraphicTip: "Parcialmente ou totalmente no contido na forma desenhada no mapa",
    useFeaturesTip: "Baseado nas respetivas localizações em relação a elementos noutra camada",
    noSpatialLimitTip: "Não limita resultados espacialmente",
    drawingTools: "Ferramentas de desenho",
    bufferSettings: "Definições de Buffer",
    defaultDistance: "Distância Padrão",
    bufferDistance: "Distância do Buffer",
    defaultUnit: "Unidade Padrão",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    availableSpatialRelationships: "Relações Espaciais Disponíveis",
    setSpatialRelationships: "Definir Relações Espaciais",
    availability: "Disponibilidade",
    relationship: "Relacionamento",
    label: "Rótulo",
    intersect: "intersetar",
    contain: "conter",
    areContainedIn: "estão contidos em",
    cross: "cruz",
    envelopeIntersect: "interseção envelope",
    overlap: "sobrepor",
    areOverlapped: "estão sobrepostos",
    touche: "touche",
    within: "contidos",
    areWithin: "estão contidos",
    indexIntersect: "interseção índice",
    itemTitle: "Título do Item",
    displayFields: "Campos de Visualização",
    sortingFields: "A Ordenar Campos",
    setDisplayFields: "Definir Exibir Campos",
    symbol: "Símbolo",
    setSymbol: "Definir símbolo",
    serviceSymbolTip: "Utilizar símbolos definidos pela camada",
    exportTip: "Exibir botão Exportar",
    keepResultsTip: "Manter resultados no mapa após fechar o widget",
    queryRelatedRecords: "Registos relacionados com a consulta",
    createLayerForTaskTip: "Especificar como a tarefa cria as camadas",
    oneLayerForTaskTip: "Apenas criar uma camada para esta tarefa",
    multipleLayerForTaskTip: "Criar uma nova camada de cada vez que esta tarefa for executada"
  })
);
