define(
   ({
    _widgetLabel: "地理處理",
    execute: "執行",
    help: "說明",
    input: "輸入",
    output: "輸出",
    executing: "執行",
    requiredInfo: "是必要的。",
    drawnOnMap: "結果繪製在地圖上。",
    clear: "清除",
    error: "錯誤",
    noToolConfig: "無可用的預配置地理處理任務。",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "上傳檔案",
    selectFileToUpload: '選擇檔案...',
    upload: '上傳',
    rasterFormat: '光柵資料格式',
    noFileSelected: '未選擇任何檔案!',
    uploadSuccess:'檔案上傳成功!',
    url: "URL",
    showLayerContent: "顯示圖層內容",
    invalidUrl: "圖徵服務 url 無效",
    Feet: "英呎",
    Yards: "碼",
    Miles: "英里",
    NauticalMiles: "海浬",
    Meter: "公尺",
    Kilometers: "公里",
    urlPlaceholder: "圖徵設定 URL"
  })
);
