define(
   ({
    _widgetLabel: "Geoprocessing",
    execute: "Uitvoeren",
    help: "Help",
    input: "Invoer",
    output: "Uitvoer",
    executing: "Uitvoeren",
    requiredInfo: "is vereist.",
    drawnOnMap: "Het resultaat wordt getekend op de kaart.",
    clear: "Wissen",
    error: "Fout",
    noToolConfig: "Geen vooraf geconfigureerde geoprocessing-taak beschikbaar.",
    useUrlForGPInput: ".URL",
    useUploadForGPInput: "Bestand uploaden",
    selectFileToUpload: 'Bestand selecteren...',
    upload: 'Uploaden',
    rasterFormat: 'Bestandsformaat rooster',
    noFileSelected: 'Geen bestand geselecteerd!',
    uploadSuccess:'Bestand met succes geüpload!',
    url: ".URL",
    showLayerContent: "Content van de laag weergeven",
    invalidUrl: "Ongeldige feature service-URL",
    Feet: "Voet",
    Yards: "Yard",
    Miles: "Mijl",
    NauticalMiles: "Zeemijl",
    Meter: "Meter",
    Kilometers: "Kilometer",
    urlPlaceholder: "Feature set URL"
  })
);
