define(
   ({
    "tabs_section_Label": "แท็ป",
    "addTab": "เพิ่มแท็ป",
    "layerName": "ชั้นข้อมูล",
    "layerType": "ประเภทการวิเคราะห์",
    "layerLabel": "ป้ายชื่อ",
    "actions": "กระทำ",
    "closest": "ฟีเจอร์ที่ใกล้ที่สุด",
    "proximity": "ความใกล้ชิด",
    "summary": "สรุป",
    "select_lbl": "-- เลือก --",
    "general_setting_Label": "ตั้งค่าทั่วไป",
    "units_text_lbl": "หน่วยระยะทาง",
    "miles": "ไมล์",
    "kilometers": "กิโลเมตร",
    "feet": "ฟุต",
    "meters": "เมตร",
    "yards": "หลา",
    "nauticalMiles": "ไมล์ทะเล",
    "maximum_distance_lbl": "ฟีเจอร์ที่ใกล้ที่สุดระยะทางสูงสุด",
    "buffer_text_lbl": "ตัวอักษร",
    "buffer_lbl": "ระยะทางขยายออกไป",
    "buffer_max_lbl": "ระยะทางบัฟเฟอร์สูงสุด",
    "buffer_min_lbl": "ระยะทางบัฟเฟอร์สูงสุด",
    "routing_checkBox": "เปิดใช้งานการกำหนดเส้นทาง",
    "weather_Label": "ตัวเลือกอากาศ",
    "weather_checkBox": "รวมข้อมูลสภาพอากาศ",
    "selectLayers": "เลือกชั้นข้อมูลอากาศ",
    "currentlySelectedLayer": "เลือกชั้นข้อมูลอากาศ",
    "missingTabLabel": "ตัวอักษาหายไปอย่างน้อยหนึ่งในแท็บ",
    "cancel": "ยกเลิก",
    "ok": "ตกลง",
    "missingLayerInWebMap": "ไม่พบชั้นข้อมูลการดำเนินงาน",
    "selectFields": "เลือกฟิลด์",
    "addField": "เพิ่มฟิลด์",
    "sum": "รวม",
    "min": "น้อยที่สุด",
    "max": "ข้อมูลทั้งหมด",
    "avg": "เฉลี่ย",
    "count": "จำนวน",
    "area": "พื้นที่",
    "length": "ความยาว",
    "count_checkBox": "แสดงจำนวน",
    "area_checkBox": "แสดงพื้นที่",
    "length_checkBox": "แสดงความยาว",
    "max_records": "ถึงขีดจำกัดสูงสุด"
  })
);
