define(
   ({
    _widgetLabel: "Анализ инцидентов",
    incident: "Инцидент",
    weather: "Погода",
    locate_incident: "Найти инцидент",
    clear_incidents: "Очистить инциденты",
    reverse_geocoded_address: "Ближайший адрес",
    reverse_geocoded_error: "Не доступно",
    miles: "Миль",
    kilometers: "километры",
    feet: "Футы (Feet)",
    meters: "Метры (Meters)",
    yards: "Ярды (Yards)",
    nauticalMiles: "Морские мили (Nautical Miles)",
    now: "Сейчас",
    wind: "ВЕТЕР",
    SUN: "ВС",
    MON: "ПН",
    TUE: "ВТ",
    WED: "СР",
    THU: "ЧТ",
    FRI: "ПТ",
    SAT: "СБ",
    defaultTabMsg: "Нет идентифицированных инцидентов.",
    actionLabel: "Установить как инцидент",
    useMapExtent: "Использовать текущий экстент карты",
    noFeaturesFound: "Объекты не найдены.",
    downloadCSV: "ЗАГРУЗИТЬ CSV",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH"
  })
);
