define({
  root: ({
    _widgetLabel: "Query",
    executeQueryTip: "Click one of the following task items to execute the query.",
    invalidConfig: "Invalid configuration. Please use Query setting page to get correct configuration.",
    queryParams: "Options",
    parameters: "OPTIONS",
    queries: "QUERIES",
    apply: "APPLY",
    queryResults: "Results",
    clear: "Clear",
    noResults: "No feature found.",
    queryError: "Query failed !",
    numberFound: "Number of features found",
    mapExtentTip: "Limit the results to the current map area.",
    noValue: "No value",
    and: "and",
    stringOperatorIs: "is", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "is not",
    stringOperatorStartsWith: "starts with",
    stringOperatorEndsWith: "ends with",
    stringOperatorContains: "contains",
    stringOperatorDoesNotContain: "does not contain",
    stringOperatorIsBlank: "is blank",
    stringOperatorIsNotBlank: "is not blank",
    dateOperatorIsOn: "is on", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "is not on",
    dateOperatorIsBefore: "is before",
    dateOperatorIsAfter: "is after",
    dateOperatorDays: "days",
    dateOperatorWeeks: "weeks", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "months",
    dateOperatorInTheLast: "in the last",
    dateOperatorNotInTheLast: "not in the last",
    dateOperatorIsBetween: "is between",
    dateOperatorIsNotBetween: "is not between",
    dateOperatorIsBlank: "is blank",
    dateOperatorIsNotBlank: "is not blank",
    numberOperatorIs: "is", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "is not",
    numberOperatorIsAtLeast: "is at least",
    numberOperatorIsLessThan: "is less than",
    numberOperatorIsAtMost: "is at most",
    numberOperatorIsGreaterThan: "is greater than",
    numberOperatorIsBetween: "is between",
    numberOperatorIsNotBetween: "is not between",
    numberOperatorIsBlank: "is blank",
    numberOperatorIsNotBlank: "is not blank",
    operationalLayerTip: "Add result as operational layer",
    queryResult: "Query Result",
    specifyParamsTip: "Specify parameters for this task",
    useSpatialFilter: "Use spatial filter to limit features",
    useCurrentMapExtent: "Only features intersecting the current map area",
    drawGraphicOnMap: "Only features intersecting the user-defined area",
    specifySpatialFilterMsg: "Please specify spatial filter for this task.",
    clearResults: "Clear Results",
    operationalTip: 'With this option checked, results will be kept on the map until the "${clearResults}" button is clicked.',
    noneQueryTip: "No query task was configured for this widget.",
    noPermissionsMsg: "You do not have permissions to access this service.",
    attributesFromRelationship: "Attributes from related table",
    tasks: "Tasks",
    applySpatialFilterToLimitResults: "Apply a spatial filter to limit results",
    useCurrentExtentTip: "Partially or completely within current map extent",
    useDrawGraphicTip: "Partially or completely within the shape drawn on the map",
    useFeaturesTip: "Based on their locations relative to features in another layer",
    noSpatialLimitTip: "Do not spatially limit results",
    applySearchDistance: "Apply a search distance",
    spatialRelationship: "Spatial Relationship",
    relatedLayer: "Related Layer",
    bufferDistance: "Buffer Distance",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    back: "Back",
    execute: "Execute"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});