define(
   ({
    _widgetLabel: "事件點分析",
    incident: "事件",
    weather: "天氣",
    locate_incident: "尋找事件點",
    clear_incidents: "清除事件點",
    reverse_geocoded_address: "最近的地址",
    reverse_geocoded_error: "無法使用",
    miles: "英里",
    kilometers: "公里",
    feet: "英呎",
    meters: "公尺",
    yards: "碼",
    nauticalMiles: "海浬",
    now: "目前",
    wind: "風力",
    SUN: "星期日",
    MON: "星期一",
    TUE: "星期二",
    WED: "星期三",
    THU: "星期四",
    FRI: "星期五",
    SAT: "星期六",
    defaultTabMsg: "未識別任何事件點。",
    actionLabel: "設為事件點",
    useMapExtent: "使用目前地圖範圍",
    noFeaturesFound: "未找到任何圖徵。",
    downloadCSV: "下載 CSV",
    sum: "總和",
    min: "最小值",
    max: "最大值",
    avg: "平均值",
    count: "計數",
    area: "區域",
    length: "長度"
  })
);
