define(
   ({
    _widgetLabel: "Afdrukken",
    title: "Kaarttitel",
    format: "Opmaak",
    layout: "Lay-out",
    settings: "Geavanceerd",
    mapScaleExtent: "Kaartschaal/-extent",
    preserve: "Behouden",
    mapScale: "kaartschaal",
    mapExtent: "kaartextent",
    forceScale: "Schaal afdwingen",
    getCurrentScale: "huidig",
    mapMetadata: "Lay-out metadata",
    author: "Auteur",
    copyright: "Copyright",
    fullLayoutOptions: "Volledige lay-outopties",
    scaleBarUnitsMetric: "Eenheden voor schaalbalk metrisch",
    scaleBarUnitsNonMetric: "Eenheden voor schaalbalk niet-metrisch",
    unitsMiles: "Mijl",
    unitsKilometers: "Kilometer",
    unitsMeters: "Meter",
    unitsFeet: "Voet",
    unitsYards: "Yard",
    unitsNauticalMiles: "Zeemijl",
    lncludeLegend: "Legenda opnemen",
    printQualityOptions: "Afdrukkwaliteit",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY grootte",
    width: "Breedte (px)",
    height: "Hoogte (px)",
    print: "Afdrukken",
    clearList: "Afdrukken wissen",
    creatingPrint: "Afdruk maken",
    printError: "Fout, probeer het opnieuw"
  })
);