define(
	 ({
		queries: "Abfrage-Tasks",
		addNew: "Neu hinzufügen",
		setSource: "Festlegen",
		setDataSource: "Datenquelle festlegen",
		name: "Name",
		querySource: "Datenquelle",
		queryName: "Task-Name",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Ergebniseinstellung",
		symbolSetting: "Symboleinstellung",
		resultSettingTip: "Definieren Sie, welche Ausgabeergebnisse und wie sie angezeigt werden sollen.",
		resultItemTitle: "Titel des Ergebniselements",
		resultItemContent: "Inhalt des Ergebniselements",
		fieldsSetTip: "Aktivieren Sie die Felder, die angezeigt werden sollen. Wählen Sie ein Feld aus, um dessen Alias zu aktualisieren, es zu sortieren und zu formatieren.",
		addField: "Feld hinzufügen",
		visibility: "Sichtbarkeit",
		alias: "Alias",
		specialType: "Besonderer Typ",
		actions: "Aktionen",
		none: "Keine",
		link: "Link",
		image: "Bild",
		noField: "Kein Feld",
		operationalLayerTip: "Ergebnis als operationalen Layer hinzufügen",
		setLayerSymbolTip: "Legen Sie das Symbol für die Abfrageergebnisse fest: ",
		setSelectedSymbolTip: "Legen Sie das Symbol des ausgewählten Features fest.",
		notUseFilter: "Keinen Filter verwenden",
		setSourceTip: "Legen Sie die Abfragequelle fest.",
		setFilterTip: "Legen Sie den Filter ordnungsgemäß fest.",
		ok: "OK",
		cancel: "Abbrechen",
		noFilterTip: "Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf."
  })
);