define(
	 ({
		queries: "Abfrage-Tasks",
		addNew: "Neu hinzufügen",
    queryLayer: "Abfrage-Layer",
		setSource: "Festlegen",
		setDataSource: "Datenquelle festlegen",
		name: "Name",
		querySource: "Datenquelle",
		queryName: "Task-Name",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Ergebniseinstellung",
		symbolSetting: "Symboleinstellung",
		resultSettingTip: "Definieren Sie, welche Ausgabeergebnisse und wie sie angezeigt werden sollen.",
		resultItemTitle: "Titel des Ergebniselements",
		resultItemContent: "Inhalt des Ergebniselements",
		fieldsSetTip: "Aktivieren Sie die Felder, die angezeigt werden sollen. Wählen Sie ein Feld aus, um dessen Alias zu aktualisieren, es zu sortieren und zu formatieren.",
		addField: "Feld hinzufügen",
		visibility: "Sichtbarkeit",
		alias: "Alias",
		specialType: "Besonderer Typ",
		actions: "Aktionen",
		none: "Keine",
		link: "Link",
		image: "Bild",
		noField: "Kein Feld",
		operationalLayerTip: "Ergebnis als operationalen Layer hinzufügen",
		setLayerSymbolTip: "Legen Sie das Symbol für die Abfrageergebnisse fest: ",
		setSelectedSymbolTip: "Legen Sie das Symbol des ausgewählten Features fest.",
		notUseFilter: "Keinen Filter verwenden",
		setSourceTip: "Legen Sie die Abfragequelle fest.",
		setFilterTip: "Legen Sie den Filter ordnungsgemäß fest.",
		ok: "OK",
		cancel: "Abbrechen",
		noFilterTip: "Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf.",
    relationships: "Beziehungen",
    addRelationshipLayer: "Neue Beziehung hinzufügen",
    relatedTo: "In Beziehung mit",
    selectOption: "Wählen Sie..",
    resultItemSorting: "Sortierung von Ergebniselementen",
    field: "Feld",
    sortingOrder: "Reihenfolge",
    configureFieldsTip: "Konfigurieren Sie die Felder, nach denen das Abfrageergebnis sortiert wird.",
    setSortingFields: "Sortierfelder festlegen",
    ascending: "Aufsteigend",
    descending: "Absteigend",
    sortBy: "Sortieren nach",
    thenBy: "Dann nach",
    addTask: "Task hinzufügen",
    noTasksTip: 'Keine Tasks; klicken Sie auf \"${addTask}\", um zu starten!',
    infoText: "Info",
    filters: "Filter",
    results: "Ergebnisse",
    optionsText: "Optionen",
    summaryText: "Zusammenfassung",
    attributeFilter: "Attributfilter",
    attributeFilterTip: "Definieren Sie Attributausdrücke für die Verwendung in Widgets, um den Abfrage-Layer zu filtern.",
    noExpressionDefinedTip: "Es wurde kein Ausdruck definiert.",
    needInputValuesTip: "Während der Laufzeit müssen Werte eingegeben werden",
    setExpressions: "Ausdrücke festlegen",
    spatialFilter: "Räumlicher Filter",
    spatialFilterTip: "Wählen Sie den/die räumlichen Filter zum Begrenzen der Ergebnisse in Widgets aus.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Teilweise oder vollständig innerhalb der aktuellen Kartenausdehnung",
    useDrawGraphicTip: "Teilweise oder vollständig innerhalb des auf der Karte dargestellten Shapes",
    useFeaturesTip: "Basierend auf deren Positionen relativ zu Features in einem anderen Layer",
    noSpatialLimitTip: "Ergebnisse nicht räumlich beschränken",
    drawingTools: "Zeichenwerkzeuge",
    bufferSettings: "Puffer-Einstellungen",
    defaultDistance: "Standardentfernung",
    bufferDistance: "Pufferabstand",
    defaultUnit: "Standardeinheit",
    miles: "Meilen",
    kilometers: "Kilometer",
    feet: "Fuß",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Seemeilen",
    availableSpatialRelationships: "Verfügbare räumliche Beziehungen",
    setSpatialRelationships: "Räumliche Beziehungen festlegen",
    availability: "Verfügbarkeit",
    relationship: "Beziehung",
    label: "Beschriftung",
    intersect: "überschneiden",
    contain: "contain",
    areContainedIn: "sind enthalten in",
    cross: "Kreuz",
    envelopeIntersect: "Envelope-Überschneidung",
    overlap: "Überlappung",
    areOverlapped: "werden überlappt",
    touche: "berühren",
    within: "Innerhalb",
    areWithin: "enthalten sind in",
    indexIntersect: "Index-Überschneidung",
    itemTitle: "Elementtitel",
    displayFields: "Anzeigefelder",
    sortingFields: "Sortierfelder",
    setDisplayFields: "Anzeigefelder festlegen",
    symbol: "Symbol",
    setSymbol: "Symbol festlegen",
    serviceSymbolTip: "Vom Layer definierte Symbole verwenden",
    exportTip: "Die Schaltfläche \"Exportieren\" anzeigen",
    keepResultsTip: "Ergebnisse auf der Karte beibehalten, nachdem das Widget geschlossen wurde",
    queryRelatedRecords: "Zugehörige Datensätze abfragen",
    createLayerForTaskTip: "Festlegen, wie der Task Layer erstellt",
    oneLayerForTaskTip: "Nur einen Layer für diesen Task erstellen",
    multipleLayerForTaskTip: "Bei jeder Ausführung dieses Tasks einen neuen Layer erstellen"
  })
);
