define(
   ({
    routeUrl: "路径 URL",
    locatorUrl: "地理编码器 URL",
    geocoderOptions: "地理编码器选项",
    autoComplete: "自动完成",
    maxLocations: "最大位置数",
    minCharacters: "最小字符数",
    searchDelay: "搜索延迟",
    placeholder: "占位符",
    routeOptions: "路线选项",
    directionsLanguage: "方向语言",
    directionsLengthUnits: "方向长度单位",
    directionsOutputType: "方向输出类型",
    impedanceAttribute: "阻抗属性",
    kilometers: "千米",
    miles: "英里",
    meters: "米",
    feet: "英尺",
    yards: "码",
    nauticalMiles: "海里",
    parametersTip: "请正确设置参数!",
    complete: "完成",
    completeNoEvents: "未完成任何事件",
    instructionsOnly: "仅说明",
    standard: "标准",
    summaryOnly: "仅摘要",
    travelModesUrl: "出行模式 URL",
    searchPlaceholder: "查找地址或地点",
    trafficLayerUrl: "交通图层 URL"
  })
);