define(
   ({
    _widgetLabel: "תרשים",
    executeChartTip: "לחץ על אחד מפריטי המשימה הבאים כדי לבצע תרשים.",
    invalidConfig: "תצורה לא חוקית.",
    noneChartTip: "לא הוגדרה משימת תרשים עבור וידג\'ט זה.",
    chartParams: "אפשרויות",
    charts: "תרשימים",
    apply: "בצע",
    useSpatialFilter: "השתמש בסינון מרחבי להגבלת יישויות",
    useCurrentMapExtent: "רק יישויות החותכות את האזור הנוכחי במפה",
    drawGraphicOnMap: "רק יישויות החותכות אזור המוגדר על-ידי המשתמש",
    chartResults: "הצג תוצאות בתרשים",
    clearResults: "נקה תוצאות",
    noPermissionsMsg: "אין לך הרשאות לגשת לשירות זה.",
    specifySpatialFilterMsg: "הגדר בבקשה סינון מרחבי למשימה הזו.",
    queryError: "השאילתה נכשלה.",
    noResults: "לא נמצאה ישות.",
    category: "קטגוריה",
    count: "ספירה",
    label: "תווית",
    horizontalAxis: "ציר אופקי",
    verticalAxis: "ציר אנכי",
    dataLabels: "תוויות נתונים",
    color: "צבע",
    colorful: "צבעוני",
    monochromatic: "צבע אחד",
    tasks: "משימות",
    results: "תוצאות",
    applySpatialFilterToLimitResults: "יישם פילטר מרחבי כדי להגביל את התוצאות",
    useCurrentExtentTip: "חלקית או לחלוטין בתיחום המפה הנוכחי",
    useDrawGraphicTip: "חלקית או לחלוטין בגבולות הצורה המצוירת במפה",
    useFeaturesTip: "בהתבסס על המיקום שלהם ביחס לישויות בשכבה אחרת",
    noSpatialLimitTip: "ללא הגבלה מרחבית של התוצאות",
    applySearchDistance: "החל מרחק חיפוש",
    spatialRelationship: "קישור מרחבי",
    relatedLayer: "שכבה מקושרת",
    clear: "נקה",
    bufferDistance: "מרחק חיץ",
    miles: "מיילים",
    kilometers: "קילומטרים",
    feet: "רגל",
    meters: "מטרים",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    back: "אחורה",
    execute: "בצע"
  })
);