define(
   ({
    taskUrl: "Ülesande URL",
    serviceURLPlaceholder: "Sisestage geotöötluse toimingu URL",
    ok: "OK",
    cancel: "Tühista",
    layer: "Kiht",
    action: "Tegevus",
    input: "Sisend",
    output: "Väljund",
    name: "Nimi",
    type: "Tüüp",
    required: "Nõutav",
    layerOrder: "Kihi järjestus",
    options: "Valikud",
    defaultValue: "Vaikeväärtus",
    inputFeatureBy: "Sisendobjektid vastavalt",
    renderer: "Renderdaja",
    displayType: "Kuva tüüp",
    label: "Märgis",
    tooltip: "Kohtspikker",
    visible: "Nähtav",
    helpUrl: "Abi URL",
    useResultMapService: "Kasutage kaarditeenuse tulemuse kuvamise valikuid",
    drawOnMap: "Interaktiivselt kaardile joonistamine",
    selectLayer: "Kihi valimine kaardilt",
    url: "URL",
    symbol: "Sümbol",
    shareResults: "Lisa tulemus töökihina",
    popup: "Hüpikaken",
    setTask: "Määra",
    setTaskTitle: "Määra GT toiming",
    enablePopup: "Luba hüpikaken",
    unSupportGeometryType: "Renderdajat ei saa määrata, kuna geomeetria tüüp on tundmatu.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Faili üleslaadimine",
    selectFileToUpload: "Vali fail...",
    upload: "Lae üles",
    rasterFormat: "Rasterandmete formaat",
    noFileSelected: "Ühtegi faili pole valitud!",
    uploadSuccess:"Faili üleslaadimine oli edukas!",
    showLayerContent: "Kuva kihi sisu",
    Feet: "Jalad",
    Yards: "Jardid",
    Miles: "Miilid",
    NauticalMiles: "Meremiilid",
    Meter: "Meetrid",
    Kilometers: "Kilomeetrid",
    urlPlaceholder: "objektikomplekti URL",
    allowToExport: "Luba tulemused eksportida"
  })
);
