define({
  root: ({
    "tabs_section_Label": "Tabs",
    "addTab": "Add Tab",
    "layerName": "Layer",
    "layerType": "Analysis Type",
    "layerLabel": "Label",
    "actions": "Actions",
    "closest": "Closest Feature",
    "proximity": "Proximity",
    "summary": "Summary",
    "select_lbl": "-- Select --",
    "general_setting_Label": "General Settings",
    "units_text_lbl": "Distance Units",
    "miles": "Miles",
    "kilometers": "Kilometers",
    "feet": "Feet",
    "meters": "Meters",
    "yards": "Yards",
    "nauticalMiles": "Nautical Miles",
    "maximum_distance_lbl": "Closest Feature Maximum Distance",
    "buffer_text_lbl": "Buffer Label",
    "buffer_lbl": "Buffer Distance",
    "buffer_max_lbl": "Maximum Buffer Distance",
    "buffer_min_lbl": "Minimum Buffer Distance",
    "routing_checkBox": "Enable Routing",
    "weather_Label": "Weather Options",
    "weather_checkBox": "Include Weather Information",
    "selectLayers": "Select Weather Layers",
    "currentlySelectedLayer": "Currently selected weather layers",
    "missingTabLabel": "At least one tab is missing its label",
    "cancel": "Cancel",
    "ok": "Ok",
    "missingLayerInWebMap": "No operational layers found.",
    "selectFields": "Select Fields",
    "addField": "Add Field",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Show Count",
    "area_checkBox": "Show Area",
    "length_checkBox": "Show Length",
    "max_records": "Maximum limit reached",
    "save_label": "Save Options",
    "save_checkbox": "Enable Save",
    "csv_label": "CSV Options",
    "csv_checkbox": "Export all fields in the layer.",
    "display_label": "Display Options",
    "display_checkbox": "Display Summary Features",
    "must_select_template": "Please select one of the edit templates in Save Options."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
