define(
   ({
    _widgetLabel: "Analyse des incidents",
    incident: "Incident",
    weather: "Temps",
    locate_incident: "Localiser l\'incident",
    clear_incidents: "Effacer les incidents",
    reverse_geocoded_address: "Adresse la plus proche",
    reverse_geocoded_error: "Indisponible",
    miles: "Miles",
    kilometers: "Kilomètres",
    feet: "Pieds",
    meters: "Mètres",
    yards: "Yards",
    nauticalMiles: "Milles nautiques",
    now: "MAINTENANT",
    wind: "VENT",
    SUN: "DIM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MER",
    THU: "JEU",
    FRI: "VEN",
    SAT: "SAM",
    defaultTabMsg: "Aucun incident identifié.",
    actionLabel: "Définir comme incident",
    useMapExtent: "Utiliser l\'étendue de la carte actuelle",
    noFeaturesFound: "Aucune entité n’a été trouvée.",
    downloadCSV: "TELECHARGER CSV",
    sum: "SOMME",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "TOTAL",
    area: "SURFACE",
    length: "LENGTH"
  })
);
