define(
   ({
    selectAnalysisTools:"选择要在微件中列出的分析工具。",
    selected: "已选择",
    name: "名称",
    graphicalDisplay:"以图形方式显示",
    usage: "使用情况",
    toolNotAvailable: "由于地图不包含所需的要素图层，因此此工具不可用。",
    aggregatePoints:"聚合点",
    aggregatePointsUsage:"将点聚合到这些点所在的面中。",
    aggregatePointsInputTip: "在面要素图层中指定将聚合到面的点要素图层。",
    calculateDensity:"计算密度",
    calculateDensityUsage:"通过展开地图范围内某一现象(表示为点或线的属性)的已知量，根据点要素或线要素创建密度图。",
    calculateDensityInputTip:"指定计算密度所使用的点要素或线要素。",
    connectOriginsToDestinations: "连接起始点和目的地",
    connectOriginsToDestinationsUsage: "测量点对之间的行驶时间或距离。",
    connectOriginsToDestinationsInputTip: "指定起始点或要生成的路径点。",
    createBuffers:"创建缓冲区",
    createBuffersUsage:"根据输入要素创建缓冲区面。",
    createBuffersInputTip:"指定要进行缓冲的点、线或面要素图层。",
    createDriveTimeAreas:"创建行驶时间区域",
    createDriveTimeAreasUsage:"根据给定的行驶时间值围绕输入点创建行驶时间(或行驶距离)面。",
    createDriveTimeAreasInputTip:"指定要绘制行驶时间区域的点。",
    createViewshed:"创建视域",
    createViewshedUsage:"根据指定位置创建可见的区域。",
    createViewshedInputTip:"指定观察者位置以确定可见区域。",
    createWatersheds:"创建流域",
    createWatershedsUsage:"根据指定的位置创建集水区。",
    createWatershedsInputTip:"指定用于计算流域的点要素。",
    deriveNewLocations:"派生新位置",
    deriveNewLocationsUsage:"根据满足您指定的查询的输入图层派生新要素",
    deriveNewLocationsInputTip:"指定要用作输入的分析图层。",
    dissolveBoundaries:"融合边界",
    dissolveBoundariesUsage:"融合叠置或共享公共边界的面。",
    dissolveBoundariesInputTip:"指定包含要融合的面要素的图层。",
    enrichLayer:"丰富图层",
    enrichLayerUsage:"通过附近区域的人员、位置和商业信息丰富输入要素。",
    enrichLayerInputTip:"指定要使用新数据进行丰富的要素。",
    extractData:"提取数据",
    extractDataDesc:"从给定范围内的一个或多个图层提取数据",
    extractDataInputTip:"指定要提取的输入要素图层。",
    findExistingLocations:"查找现有位置",
    findExistingLocationsUsage:"选择输入图层内满足您指定的属性和/或空间查询的要素",
    findExistingLocationsInputTip:"指定要用作输入的空间图层。",
    findHotSpots:"查找热点",
    findHotSpotsUsage:"查找具有统计显著性的输入要素聚类或高/低值。",
    findHotSpotsInputTip:"指定要为其计算热点的点或面要素图层。",
    findNearest:"查找最近点",
    findNearestUsage:"针对输入图层上的每个要素查找另一图层上与其最近的要素",
    findNearestInputTip:"指定要在其中找到最近位置的点、线或面要素。",
    findSimilarLocations:"查找相似位置",
    findSimilarLocationsUsage:"衡量候选位置与一个或多个参考位置的相似性。",
    findSimilarLocationsInputTip:"指定包含一个或多个参考位置的要素图层，将针对其评估搜索图层中要素的相似性。",
    interpolatePoints:"插值点",
    interpolatePointsUsage:"根据通过点集合进行的测量得出的新位置的预测值。",
    interpolatePointsInputTip:"指定将要插入的点要素。",
    mergeLayers:"合并图层",
    mergeLayersUsage:"将多个图层中的要素合并到一个新图层中",
    mergeLayersInputTip:"指定要与合并图层进行合并的要素图层。",
    overlayLayers:"图层叠加",
    overlayLayersUsage:"通过原始图层中保留的信息将多个图层合并到一个图层中。",
    overlayLayersInputTip:"指定将与叠加图层进行叠加的要素图层。",
    planRoutes:"计划路径",
    planRoutesUsage:"确定在流动劳动力中有效划分任务的方法。",
    planRoutesInputTip:"指定车辆、驾驶员和路径应该访问的点。",
    summarizeNearby:"邻近汇总",
    summarizeNearbyUsage:"针对输入图层上的每个要素，汇总距离另一图层上的要素一段距离范围内的数据。",
    summarizeNearbyInputTip:"指定汇总图层中用作到要素的距离的测量起点的点、线或面要素图层。",
    summarizeWithin:"范围内汇总",
    summarizeWithinUsage:"针对输入面图层上的每个面，汇总该范围内来自另一图层上的要素的数据。",
    summarizeWithinInputTip:"指定要汇总到的面要素图层。",
    traceDownstream:"网络下溯追踪",
    traceDownstreamUsage:"确定以您指定的位置为起点的下游方向中的流路径。",
    traceDownstreamInputTip:"指定用于网络下溯追踪起始位置的点要素。"
  })
);
