define(
   ({
    selectAnalysisTools:"选择要在微件中使用的分析工具。",
    selected: "已选择",
    name: "名称",
    graphicalDisplay:"以图形方式显示",
    usage: "使用情况",
    settings: "设置",
    toolSetting: "设置工具详细信息",
    toolLabel: "工具显示名称",
    showHelpTip: "在微件中显示帮助链接",
    showCurrentMapExtent: "显示使用当前地图范围的选项",
    showCredits: "显示<b>显示配额</b>选项",
    saveAsFeatureService: "在用户帐户中保存结果",
    showReadyToUseLayers: "显示 ArcGIS Online 生动世界地图集的即用型图层",
    toolNotAvailable: "由于地图不包含所需的要素图层，因此此工具不可用。",
    aggregatePoints:"聚合点",
    aggregatePointsUsage:"将点聚合到这些点所在的面中。",
    calculateDensity:"计算密度",
    calculateDensityUsage:"通过展开地图范围内某一现象(表示为点或线的属性)的已知量，根据点要素或线要素创建密度图。",
    connectOriginsToDestinations: "连接起始点和目的地",
    connectOriginsToDestinationsUsage: "测量点对之间的行驶时间或距离。",
    createBuffers:"创建缓冲区",
    createBuffersUsage:"根据输入要素创建缓冲区面。",
    createDriveTimeAreas:"创建行驶时间区域",
    createDriveTimeAreasUsage:"根据给定的行驶时间值围绕输入点创建行驶时间(或行驶距离)面。",
    createViewshed:"创建视域",
    createViewshedUsage:"根据指定位置创建可见的区域。",
    createWatersheds:"创建流域",
    createWatershedsUsage:"根据指定的位置创建集水区。",
    deriveNewLocations:"派生新位置",
    deriveNewLocationsUsage:"根据满足您指定的查询的输入图层派生新要素",
    dissolveBoundaries:"融合边界",
    dissolveBoundariesUsage:"融合叠置或共享公共边界的面。",
    enrichLayer:"丰富图层",
    enrichLayerUsage:"通过附近区域的人员、位置和商业信息丰富输入要素。",
    extractData:"提取数据",
    extractDataDesc:"从给定范围内的一个或多个图层提取数据",
    findExistingLocations:"查找现有位置",
    findExistingLocationsUsage:"选择输入图层内满足您指定的属性和/或空间查询的要素",
    findHotSpots:"查找热点",
    findHotSpotsUsage:"查找具有统计显著性的输入要素聚类或高/低值。",
    findNearest:"查找最近点",
    findNearestUsage:"针对输入图层上的每个要素查找另一图层上与其最近的要素",
    findSimilarLocations:"查找相似位置",
    findSimilarLocationsUsage:"衡量候选位置与一个或多个参考位置的相似性。",
    interpolatePoints:"插值点",
    interpolatePointsUsage:"根据通过点集合进行的测量得出的新位置的预测值。",
    mergeLayers:"合并图层",
    mergeLayersUsage:"将多个图层中的要素合并到一个新图层中",
    overlayLayers:"图层叠加",
    overlayLayersUsage:"通过原始图层中保留的信息将多个图层合并到一个图层中。",
    planRoutes:"计划路径",
    planRoutesUsage:"确定在流动劳动力中有效划分任务的方法。",
    summarizeNearby:"邻近汇总",
    summarizeNearbyUsage:"针对输入图层上的每个要素，汇总距离另一图层上的要素一段距离范围内的数据。",
    summarizeWithin:"范围内汇总",
    summarizeWithinUsage:"针对输入面图层上的每个面，汇总该范围内来自另一图层上的要素的数据。",
    traceDownstream:"网络下溯追踪",
    traceDownstreamUsage:"确定以您指定的位置为起点的下游方向中的流路径。"
  })
);
