define(
   ({
    _widgetLabel: "Gráfico",
    executeChartTip: "Clique em um dos seguintes itens da tarefa para executar o gráfico.",
    invalidConfig: "Configuração inválida.",
    noneChartTip: "Nenhuma tarefa de gráfico foi configurada para este widget.",
    chartParams: "Opções",
    charts: "GRÁFICOS",
    apply: "APLICAR",
    useSpatialFilter: "Utilizar filtro espacial para limitar feições",
    useCurrentMapExtent: "Somente as feições que interseccionam a área de mapa atual",
    drawGraphicOnMap: "Somente as feições que interseccionam uma área definida pelo usuário",
    chartResults: "Resultados do Gráfico",
    clearResults: "Limpar Resultados",
    noPermissionsMsg: "Você não tem permissões para acessar este serviço.",
    specifySpatialFilterMsg: "Especifique o filtro espacial para esta tarefa.",
    queryError: "Falha na consulta.",
    noResults: "Nenhuma feição encontrada.",
    category: "Categoria",
    count: "Contagem",
    label: "Rótulo",
    horizontalAxis: "Eixo Horizontal",
    verticalAxis: "Eixo Vertical",
    dataLabels: "Rótulos de Data",
    color: "Cor",
    colorful: "Colorido",
    monochromatic: "Monocromático",
    tasks: "Tarefas",
    results: "Resultados",
    applySpatialFilterToLimitResults: "Aplicar um filtro espacial para limitar resultados",
    useCurrentExtentTip: "Parcialmente ou completamente dentro da extensão de mapa atual",
    useDrawGraphicTip: "Parcialmente ou completamente dentro da forma desenhada no mapa",
    useFeaturesTip: "Baseado em suas localizações em relação às feições em outra camada",
    noSpatialLimitTip: "Não limitar espacialmente os resultados",
    applySearchDistance: "Aplicar uma distância de pesquisa",
    spatialRelationship: "Relacionamento Espacial",
    relatedLayer: "Camada Relacionada",
    clear: "Apagar",
    bufferDistance: "Distância do Buffer",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    back: "Voltar",
    execute: "Executar"
  })
);