define(
   ({
    _widgetLabel: "Fråga",
    executeQueryTip: "Klicka på något av följande uppgiftsobjekt för att köra frågan.",
    invalidConfig: "Ogiltig konfiguration. Ställ in korrekt konfiguration på frågeinställningssidan.",
    queryParams: "Alternativ",
    parameters: "ALTERNATIV",
    queries: "FRÅGOR",
    apply: "TILLÄMPA",
    queryResults: "Resultat",
    clear: "Rensa",
    noResults: "Inget geoobjekt hittades.",
    queryError: "Frågan misslyckades!",
    numberFound: "Antal geoobjekt som hittades",
    mapExtentTip: "Begränsa resultatet till den aktuella kartutbredningen.",
    noValue: "Inget värde",
    and: "och",
    stringOperatorIs: "är", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "är inte",
    stringOperatorStartsWith: "börjar med",
    stringOperatorEndsWith: "slutar med",
    stringOperatorContains: "innehåller",
    stringOperatorDoesNotContain: "innehåller inte",
    stringOperatorIsBlank: "är tomt",
    stringOperatorIsNotBlank: "är inte tomt",
    dateOperatorIsOn: "är", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "är inte",
    dateOperatorIsBefore: "är före",
    dateOperatorIsAfter: "är efter",
    dateOperatorDays: "dagar",
    dateOperatorWeeks: "veckor", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "månader",
    dateOperatorInTheLast: "i den sista",
    dateOperatorNotInTheLast: "inte i den sista",
    dateOperatorIsBetween: "är mellan",
    dateOperatorIsNotBetween: "är inte mellan",
    dateOperatorIsBlank: "är tomt",
    dateOperatorIsNotBlank: "är inte tomt",
    numberOperatorIs: "är", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "är inte",
    numberOperatorIsAtLeast: "är minst",
    numberOperatorIsLessThan: "är mindre än",
    numberOperatorIsAtMost: "är som mest",
    numberOperatorIsGreaterThan: "är större än",
    numberOperatorIsBetween: "är mellan",
    numberOperatorIsNotBetween: "är inte mellan",
    numberOperatorIsBlank: "är tomt",
    numberOperatorIsNotBlank: "är inte tomt",
    operationalLayerTip: "Lägg till resultat som funktionslager",
    queryResult: "Frågeresultat",
    specifyParamsTip: "Ange parametrar för den här uppgiften",
    useSpatialFilter: "Använd geografiskt filter för att begränsa geoobjekt",
    useCurrentMapExtent: "Endast geoobjekt som rör den aktuella kartutbredningen",
    drawGraphicOnMap: "Endast geoobjekt som rör ett användardefinierat område",
    specifySpatialFilterMsg: "Ange ett geografiskt filter för den här uppgiften.",
    clearResults: "Rensa resultat",
    operationalTip: 'När det här alternativet har markerats behålls resultaten på kartan tills du klickar på knappen "${clearResults}".',
    noneQueryTip: "Det finns inga tillgängliga förinställda frågeuppgifter.",
    noPermissionsMsg: "Du saknar behörighet för att få åtkomst till denna tjänst."
  })
);