define({
  root: ({
    addDistance: "Add Length Unit",
    addArea: "Add Area Unit",
    label: "Label",
    abbr: "Abbreviation",
    conversion: "Conversion",
    actions: "Actions",
    areaUnits: "Area Units",
    distanceUnits: "Length Units",
    miles: "Miles",
    kilometers: "Kilometers",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareMiles: "Square miles",
    acres: "Acres",
    squareKilometers: "Square kilometers",
    hectares: "Hectares",
    squareMeters: "Square meters",
    squareFeet: "Square feet",
    squareYards: "Square yards",
    distance: "Distances",
    area: "Areas"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});