define(
   ({
    _widgetLabel: "Forespørgsel",
    executeQueryTip: "Klik på et af følgende opgaveelementer for at udføre forespørgslen.",
    invalidConfig: "Ugyldig konfiguration. Brug siden med indstillinger for forespørgsler til at rette konfigurationen.",
    queryParams: "Indstillinger",
    parameters: "INDSTILLINGER",
    queries: "FORESPØRGSLER",
    apply: "ANVEND",
    queryResults: "Resultater",
    clear: "Ryd",
    noResults: "Ingen resultater fundet.",
    queryError: "Forespørgslen mislykkedes!",
    numberFound: "Antal objekter fundet",
    mapExtentTip: "Begræns resultaterne til det aktuelle kortområde.",
    noValue: "Ingen værdi",
    and: "og",
    stringOperatorIs: "er", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "er ikke",
    stringOperatorStartsWith: "starter med",
    stringOperatorEndsWith: "slutter med",
    stringOperatorContains: "indeholder",
    stringOperatorDoesNotContain: "indeholder ikke",
    stringOperatorIsBlank: "er tomt",
    stringOperatorIsNotBlank: "er ikke tomt",
    dateOperatorIsOn: "er d.", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "er ikke d.",
    dateOperatorIsBefore: "er før",
    dateOperatorIsAfter: "er efter",
    dateOperatorDays: "dage",
    dateOperatorWeeks: "uger", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "måneder",
    dateOperatorInTheLast: "i de seneste",
    dateOperatorNotInTheLast: "ikke i de seneste",
    dateOperatorIsBetween: "er mellem",
    dateOperatorIsNotBetween: "er ikke mellem",
    dateOperatorIsBlank: "er tomt",
    dateOperatorIsNotBlank: "er ikke tomt",
    numberOperatorIs: "er", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "er ikke",
    numberOperatorIsAtLeast: "er mindst",
    numberOperatorIsLessThan: "er mindre end",
    numberOperatorIsAtMost: "er højest",
    numberOperatorIsGreaterThan: "er større end",
    numberOperatorIsBetween: "er mellem",
    numberOperatorIsNotBetween: "er ikke mellem",
    numberOperatorIsBlank: "er tomt",
    numberOperatorIsNotBlank: "er ikke tomt",
    operationalLayerTip: "Tilføj resultat som operationelt lag",
    queryResult: "Forespørgselsresultat",
    specifyParamsTip: "Angiv parametrene for denne opgave",
    useSpatialFilter: "Brug spatialt filter til at begrænse objekter",
    useCurrentMapExtent: "Kun objekter, der gennemskærer det aktuelle kortområde",
    drawGraphicOnMap: "Kun objekter, der gennemskærer det brugerdefinerede område",
    specifySpatialFilterMsg: "Angiv et spatialt filter til denne opgave.",
    clearResults: "Ryd resultater",
    operationalTip: 'Med denne indstilling markeret bevares resultaterne på kortet, indtil der klikkes på knappen \"${clearResults}\".',
    noneQueryTip: "Der er ikke blevet konfigureret nogen forespørgselsopgave for denne widget.",
    noPermissionsMsg: "Du har ikke adgang til denne tjeneste.",
    attributesFromRelationship: "Attributter fra relateret tabel",
    tasks: "Opgaver",
    applySpatialFilterToLimitResults: "Anvend et spatialt filter til at begrænse resultaterne",
    useCurrentExtentTip: "Delvist eller helt inden for den aktuelle kortudstrækning",
    useDrawGraphicTip: "Delvist eller helt inden for den form, der et tegnet på kortet",
    useFeaturesTip: "Baseret på deres positioner i forhold til objekterne i et andet lag",
    noSpatialLimitTip: "Begræns ikke resultaterne spatialt",
    applySearchDistance: "Anvend en søgeafstand",
    spatialRelationship: "Spatial relation",
    relatedLayer: "Relateret lag",
    bufferDistance: "Bufferafstand",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    back: "Tilbage",
    execute: "Udfør"
  })
);