define(
   ({
    _widgetLabel: "Forespørgsel",
    executeQueryTip: "Klik på en af følgende opgaveelementer for at udføre en forespørgsel.",
    invalidConfig: "Ugyldig konfiguration. Brug siden med indstillinger for forespørgsler til at rette konfigurationen.",
    queryParams: "Indstillinger",
    parameters: "INDSTILLINGER",
    queries: "FORESPØRGSLER",
    apply: "ANVEND",
    queryResults: "Resultater",
    clear: "Ryd",
    noResults: "Ingen resultater fundet.",
    queryError: "Forespørgslen mislykkedes!",
    numberFound: "Antal objekter fundet",
    mapExtentTip: "Begræns resultaterne til det aktuelle korts udstrækning.",
    noValue: "Ingen værdi",
    and: "og",
    stringOperatorIs: "er", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "er ikke",
    stringOperatorStartsWith: "starter med",
    stringOperatorEndsWith: "slutter med",
    stringOperatorContains: "indeholder",
    stringOperatorDoesNotContain: "indeholder ikke",
    stringOperatorIsBlank: "er tomt",
    stringOperatorIsNotBlank: "er ikke tomt",
    dateOperatorIsOn: "er d.", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "er ikke d.",
    dateOperatorIsBefore: "er før",
    dateOperatorIsAfter: "er efter",
    dateOperatorDays: "dage",
    dateOperatorWeeks: "uger", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "måneder",
    dateOperatorInTheLast: "i de seneste",
    dateOperatorNotInTheLast: "ikke i de seneste",
    dateOperatorIsBetween: "er mellem",
    dateOperatorIsNotBetween: "er ikke mellem",
    dateOperatorIsBlank: "er tomt",
    dateOperatorIsNotBlank: "er ikke tomt",
    numberOperatorIs: "er", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "er ikke",
    numberOperatorIsAtLeast: "er mindst",
    numberOperatorIsLessThan: "er mindre end",
    numberOperatorIsAtMost: "er højest",
    numberOperatorIsGreaterThan: "er større end",
    numberOperatorIsBetween: "er mellem",
    numberOperatorIsNotBetween: "er ikke mellem",
    numberOperatorIsBlank: "er tomt",
    numberOperatorIsNotBlank: "er ikke tomt",
    operationalLayerTip: "Tilføj resultat som operationelt lag",
    queryResult: "Forespørgselsresultat",
    specifyParamsTip: "Angiv parametrene for denne opgave",
    useSpatialFilter: "Brug spatialt filter til at begrænse objekter",
    useCurrentMapExtent: "Kun objekter, der berører den aktuelle kortudstrækning",
    drawGraphicOnMap: "Kun objekter, der berører et brugerdefineret område",
    specifySpatialFilterMsg: "Angiv et spatialt filter til denne opgave.",
    clearResults: "Ryd resultater",
    operationalTip: 'Er denne indstilling markeret, bevares resultaterne på kortet, indtil der klikkes på knappen "${clearResults}".',
    noneQueryTip: "Der er ingen tilgængelige forespørgselsopgaver, der er konfigureret på forhånd.",
    noPermissionsMsg: "Du har ikke adgang til denne tjeneste."
  })
);