define(
	 ({
		queries: "Attività interrogazioni",
		addNew: "Aggiungi nuovo",
		setSource: "Imposta",
		setDataSource: "Imposta origine dati",
		name: "Nome",
		querySource: "Origine dati",
		queryName: "Nome attività",
		queryDefinition: "Definizione filtro",
		resultsSetting: "Impostazione risultati",
		symbolSetting: "Impostazione simbolo",
		resultSettingTip: "Definire le informazioni di visualizzazione sui risultanti di output.",
		resultItemTitle: "Titolo elemento risultati",
		resultItemContent: "Contenuto elemento risultati",
		fieldsSetTip: "Verificare i campi da visualizzare. Selezionare un campo per aggiornarne alias, ordine e formato.",
		addField: "Aggiungi campo",
		visibility: "Visibilità",
		alias: "Alias",
		specialType: "Tipo speciale",
		actions: "Azioni",
		none: "Nessuno",
		link: "Collegamento",
		image: "Immagine",
		noField: "Campi non disponibili",
		operationalLayerTip: "Aggiungi risultato come layer operativo",
		setLayerSymbolTip: "Impostare il simbolo per i risultati dell\'interrogazione: ",
		setSelectedSymbolTip: "Impostare il simbolo della feature selezionata.",
		notUseFilter: "Non utilizzare filtri",
		setSourceTip: "Impostare l\'origine dell\'interrogazione.",
		setFilterTip: "Impostare il filtro correttamente.",
		ok: "OK",
		cancel: "Annulla",
		noFilterTip: "Se non si definisce l\'espressione di filtro, questa attività di interrogazione restituirà tutte le feature presenti nell\'origine dati specificata."
  })
);