define(
	 ({
		queries: "Attività interrogazioni",
		addNew: "Aggiungi nuovo",
    queryLayer: "Layer interrogazione",
		setSource: "Imposta",
		setDataSource: "Imposta origine dati",
		name: "Nome",
		querySource: "Origine dati",
		queryName: "Nome attività",
		queryDefinition: "Definizione filtro",
		resultsSetting: "Impostazione risultati",
		symbolSetting: "Impostazione simbolo",
		resultSettingTip: "Definire le informazioni di visualizzazione sui risultanti di output.",
		resultItemTitle: "Titolo elemento risultati",
		resultItemContent: "Contenuto elemento risultati",
		fieldsSetTip: "Verificare i campi da visualizzare. Selezionare un campo per aggiornarne alias, ordine e formato.",
		addField: "Aggiungi campo",
		visibility: "Visibilità",
		alias: "Alias",
		specialType: "Tipo speciale",
		actions: "Azioni",
		none: "Nessuno",
		link: "Collegamento",
		image: "Immagine",
		noField: "Campi non disponibili",
		operationalLayerTip: "Aggiungi risultato come layer operativo",
		setLayerSymbolTip: "Impostare il simbolo per i risultati dell\'interrogazione: ",
		setSelectedSymbolTip: "Impostare il simbolo della feature selezionata.",
		notUseFilter: "Non utilizzare filtri",
		setSourceTip: "Impostare l\'origine dell\'interrogazione.",
		setFilterTip: "Impostare il filtro correttamente.",
		ok: "OK",
		cancel: "Annulla",
		noFilterTip: "Se non si definisce l\'espressione di filtro, questa attività di interrogazione restituirà tutte le feature presenti nell\'origine dati specificata.",
    relationships: "Relazioni",
    addRelationshipLayer: "Aggiungi nuova relazione",
    relatedTo: "Correlata a",
    selectOption: "Selezionare...",
    resultItemSorting: "Ordinamento elemento risultati",
    field: "Campo",
    sortingOrder: "Ordina",
    configureFieldsTip: "Configurare i campi per cui verrà ordinato il risultato della query.",
    setSortingFields: "Imposta ordinamento campi",
    ascending: "Ascendente",
    descending: "Decrescente",
    sortBy: "Ordina secondo",
    thenBy: "Quindi per",
    addTask: "Aggiungi attività",
    noTasksTip: 'Nessuna attività. Fare clic su \"${addTask}\" per iniziare.',
    infoText: "Informazioni",
    filters: "Filtri",
    results: "Risultati",
    optionsText: "Opzioni",
    summaryText: "Riepilogo",
    attributeFilter: "Filtra attributo",
    attributeFilterTip: "Definire le espressioni di attributi da utilizzare nel widget per filtrare il layer interrogazione.",
    noExpressionDefinedTip: "Nessuna espressione definita.",
    needInputValuesTip: "È necessario immettere valori in fase di runtime",
    setExpressions: "Imposta espressioni",
    spatialFilter: "Filtro spaziale",
    spatialFilterTip: "Scegliere il filtro o i filtri spaziali utilizzati nel widget per limitare i risultati.",
    defaultOption: "Impostazione predefinita",
    useCurrentExtentTip: "Parzialmente o completamente all\'interno dell\'estensione mappa corrente",
    useDrawGraphicTip: "Parzialmente o completamente all\'interno della forma disegnata sulla mappa",
    useFeaturesTip: "In base alle posizioni relative alle feature in un altro layer",
    noSpatialLimitTip: "Non limitare spazialmente i risultati",
    drawingTools: "Strumenti di disegno",
    bufferSettings: "Impostazioni buffer",
    defaultDistance: "Distanza predefinita",
    bufferDistance: "Distanza di buffer",
    defaultUnit: "Unità predefinita",
    miles: "Miglia",
    kilometers: "Chilometri",
    feet: "Piede",
    meters: "Metri",
    yards: "Iarde",
    nauticalMiles: "Miglia nautiche",
    availableSpatialRelationships: "Relazioni spaziali disponibili",
    setSpatialRelationships: "Imposta relazioni spaziali",
    availability: "Disponibilità",
    relationship: "Relazione",
    label: "Etichetta",
    intersect: "intersecano",
    contain: "contengono",
    areContainedIn: "sono contenuti in",
    cross: "Incrociato",
    envelopeIntersect: "intersezione inviluppo",
    overlap: "sovrapponi",
    areOverlapped: "sono sovrapposte",
    touche: "tocca",
    within: "interno",
    areWithin: "sono interne",
    indexIntersect: "interseca indice",
    itemTitle: "Titolo elemento",
    displayFields: "Visualizza campi",
    sortingFields: "Ordinamento campi",
    setDisplayFields: "Imposta campi in visualizzazione",
    symbol: "Simbolo",
    setSymbol: "Imposta simbolo",
    serviceSymbolTip: "Utilizza i simboli definiti dal layer",
    exportTip: "Mostra pulsante Esporta",
    keepResultsTip: "Mantieni risultati nella mappa dopo la chiusura del widget",
    queryRelatedRecords: "Interroga record correlati",
    createLayerForTaskTip: "Specificare in che modo l\'attività crea i layer",
    oneLayerForTaskTip: "Crea un solo layer per questa attività",
    multipleLayerForTaskTip: "Crea un nuovo layer ogni volta che l\'attività viene eseguita"
  })
);
