define(
	 ({
		charts: "Diagramos užduotys",
		addNew: "Pridėti naują",
		addNewTip: "Pridėti naują diagramos užduotį",
		name: "Pavadinimas",
		set: "Grupė",
		setDataSource: "Nustatykite duomenų šaltinį",
		generalSettingsTip: "Nustatykite diagramų duomenų šaltinį, pavadinimą ir aprašymą.",
		chartModeSettingTip: "Pasirinkite, kaip analizuoti ir rodyti duomenis diagramomis.",
		detailsSettingTip: "Nustatykite diagramos išvaizdą nurodydami jos tipą, spalvą ir kokias reikšmes rodyti diagramoje.",
		symbolSettingTip: "Nustatykite, kaip žemėlapyje būtų rodomi diagramų duomenys.",
		addFilterTip: "Pridėti filtrą prie šių duomenų",
		dataSource: "Duomenų šaltinis",
		noResults: "Elementų nerasta.",
		chartTitle: "Diagramos pavadinimas",
		description: "Aprašas",
		chartingMode: "Diagramos rodymas",
		featureOption: "Rodyti reikšmes po vieną elementą",
		categoryOption: "Rodyti reikšmes pagal kategoriją",
		countOption: "Rodyti elementų skaičių kiekvienoje kategorijoje",
		fieldOption: "Rodyti atributo reikšmes kaip diagramas",
		category: "Kategorija",
		axisLabel: "Kategorijos žymė",
		categoryField: "Kategorijos laukas",
		operation: "Veiksmas",
		originalOption: "Naudoti pradines reikšmes",
		sumOption: "Suma",
		averageOption: "Vidutinis",
		minOption: "Minimumas",
		maxOption: "Maksimumas",
		valueFields: "Reikšmių laukai",
		moveUp: "Pakelti aukštyn",
		moveDown: "Nuleisti žemyn",
		sortOrder: "Rūšiuoti diagramų tvarką naudojant kategorijų žymes",
		ascending: "Didėjimo tvarka",
		descending: "Mažėjimo tvarka",
		chartType: "Diagramos tipas",
		column: "Stulpelinė diagrama",
		bar: "Juostinė diagrama",
		line: "Linijinė diagrama",
		pie: "Skritulinė diagrama",
		chartColor: "Diagramos spalva",
		showDataLabels: "Rodyti duomenų žymes",
		setSymbol: "Išrankos simbolis",
		setHighLightColor: "Išryškinimo spalva",
		settings: "Nustatymai",
		mapInterationOptions: "Sąveikos su žemėlapiu parinktys",
		preview: "Peržiūra",
		ok: "Gerai",
		cancel: "Atšaukti",
		close: "Užverti",
		setFilterTip: "Tinkamai nustatykite filtrą. ",
		setChartTitleTip: "Nustatykite diagramos pavadinimą.",
		setChartTypeTip: "Pasirinkite bent vieną diagramos tipą.",
		setDataFieldTip: "Pasirinkite bent vieną reikšmės lauką.",
		setOutputFieldTip: "Nustatykite išvesties laukus.",
		count: "Kiekis",
		label: "Žymė",
		horizontalAxis: "Horizontali ašis",
		verticalAxis: "Vertikali ašis",
		dataLabels: "Duomenų žymės",
		color: "Spalva",
		colorful: "Spalvingas",
		monochromatic: "Vienspalvis"
  })
);