define(
   ({
    _widgetLabel: "Geobearbetning",
    execute: "Utför",
    help: "Hjälp",
    input: "Indata",
    output: "Utdata",
    executing: "Kör",
    requiredInfo: "är obligatoriskt.",
    drawnOnMap: "Resultatet ritas på kartan.",
    clear: "Rensa",
    error: "Fel",
    noToolConfig: "Ingen förkonfigurerad geobearbetningsåtgärd är tillgänglig.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Överför fil",
    selectFileToUpload: 'Välj fil ...',
    upload: 'Överför',
    rasterFormat: 'Rasterdataformat',
    noFileSelected: 'Ingen fil har valts!',
    uploadSuccess:'Filen har överförts!',
    url: "URL",
    showLayerContent: "Visa lagrets innehåll",
    invalidUrl: "Ogiltig URL för geoobjektstjänsten.",
    Feet: "Fot",
    Yards: "Yard",
    Miles: "Engelska mil",
    NauticalMiles: "Nautiska mil",
    Meter: "Meter",
    Kilometers: "Kilometer",
    urlPlaceholder: "URL till geoobjektsuppsättning"
  })
);
