define(
   ({
    _widgetLabel: "Hændelsesanalyse",
    incident: "Hændelse",
    weather: "Vejr",
    locate_incident: "Find hændelse",
    clear_incidents: "Ryd hændelser",
    reverse_geocoded_address: "Nærmeste adresse",
    reverse_geocoded_error: "Not available",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    now: "NU",
    wind: "VIND",
    SUN: "SØN",
    MON: "MAN",
    TUE: "TIR",
    WED: "ONS",
    THU: "TOR",
    FRI: "FRE",
    SAT: "LØR",
    defaultTabMsg: "Ingen hændelser identificeret.",
    actionLabel: "Indstil som hændelse",
    useMapExtent: "Brug den aktuelle kortudstrækning",
    noFeaturesFound: "Ingen objekte fundet.",
    downloadCSV: "HENT CSV",
    sum: "SUM",
    min: "MIN",
    max: "MAKS",
    avg: "GNM.SN",
    count: "OPTÆLLING",
    area: "AREA",
    length: "LÆNGDE"
  })
);
