define(
	 ({
		queries: "Užklausų užduotys",
		addNew: "Pridėti naują",
    queryLayer: "Užklausos sluoksnis",
		setSource: "Grupė",
		setDataSource: "Nustatykite duomenų šaltinį",
		name: "Pavadinimas",
		querySource: "Duomenų šaltinis",
		queryName: "Užduoties pavadinimas",
		queryDefinition: "Filtro apibrėžimas",
		resultsSetting: "Rezultatų nustatymai",
		symbolSetting: "Simbolio nustatymas",
		resultSettingTip: "Nustatykite, ką ir kaip rodyti išvesties rezultatuose.",
		resultItemTitle: "Gauto elemento pavadinimas",
		resultItemContent: "Gauto elemento turinys",
		fieldsSetTip: "Pažymėkite, kurie laukai turi būti rodomi. Pasirinkite laukus ir galėsite atnaujinti jų pseudonimus, išdėstymo tvarką ir formatavimą.",
		addField: "Pridėti lauką",
		visibility: "Matomumas",
		alias: "Pseudonimas",
		specialType: "Specialus tipas",
		actions: "Veiksmai",
		none: "Nėra",
		link: "Nuoroda",
		image: "Paveikslėlis",
		noField: "Lauko nėra",
		operationalLayerTip: "Pridėti rezultatus kaip darbinį sluoksnį",
		setLayerSymbolTip: "Nustatykite užklausos rezultatų simbolį: ",
		setSelectedSymbolTip: "Nustatykite pasirinkto elemento simbolį.",
		notUseFilter: "Nenaudoti filtro",
		setSourceTip: "Nustatykite užklausos šaltinį.",
		setFilterTip: "Nustatykite filtrą tinkamai.",
		ok: "Gerai",
		cancel: "Atšaukti",
		noFilterTip: "Nenustačius filtro sąlygos, ši užklausos užduotis nurodys visus nurodyto duomenų šaltinio elementus.",
    relationships: "Ryšys",
    addRelationshipLayer: "Pridėti naują ryšį",
    relatedTo: "Susiję su",
    selectOption: "Pasirinkite..",
    resultItemSorting: "Gautų elementų rūšiavimas",
    field: "Laukas",
    sortingOrder: "Tvarka",
    configureFieldsTip: "Sukonfigūruokite laukus, pagal kuriuos bus rūšiuojami užklausos rezultatai.",
    setSortingFields: "Nustatyti rūšiavimo laukus",
    ascending: "didėjančia tvarka",
    descending: "Mažėjimo tvarka",
    sortBy: "Rūšiuoti pagal",
    thenBy: "Tada pagal",
    addTask: "Įtraukti užduotį",
    noTasksTip: 'Užduočių nėra, norėdami pradėti, spustelėkite \"${addTask}\"!',
    infoText: "Informacija",
    filters: "Filtrai",
    results: "Rezultatai",
    optionsText: "Parinktys",
    summaryText: "Santrauka",
    attributeFilter: "Atributų filtras",
    attributeFilterTip: "Apibrėžkite atributų išraišką, skirtą užklausos sluoksniams filtruoti valdiklyje.",
    noExpressionDefinedTip: "Neapibrėžta nė viena išraiška.",
    needInputValuesTip: "Reikia įvesti reikšmes vykdymo aplinkoje",
    setExpressions: "Nustatyti išraiškas",
    spatialFilter: "Erdvinis filtras",
    spatialFilterTip: "Pasirinkite erdvinį filtrą (-us), naudojamą valdiklyje rezultatams apriboti.",
    defaultOption: "Numatytasis",
    useCurrentExtentTip: "Iš dalies ar visiškai esamo žemėlapio aprėptyje",
    useDrawGraphicTip: "Iš dalies arba visiškai žemėlapyje nubrėžtoje figūroje",
    useFeaturesTip: "Remiantis jų vietomis kito sluoksnio elementų atžvilgiu",
    noSpatialLimitTip: "Erdviškai neapriboti rezultatų",
    drawingTools: "Braižymo įrankiai",
    bufferSettings: "Buferio parametrai",
    defaultDistance: "Numatytasis nuotolis",
    bufferDistance: "Buferio atstumas",
    defaultUnit: "Numatytasis vienetas",
    miles: "Mylios",
    kilometers: "Kilometrai",
    feet: "Pėdos",
    meters: "Metrai",
    yards: "Jardai",
    nauticalMiles: "Jūrmylės",
    availableSpatialRelationships: "Galimi erdviniai ryšiai",
    setSpatialRelationships: "Nustatyti erdvinius ryšius",
    availability: "Prieinamumas",
    relationship: "Ryšys",
    label: "Žymė",
    intersect: "sukirsti",
    contain: "aprėpti",
    areContainedIn: "yra aprėpti",
    cross: "kryžius",
    envelopeIntersect: "apgaubų susikirtimas",
    overlap: "persikloti",
    areOverlapped: "yra užkloti",
    touche: "glaustis",
    within: "viduje",
    areWithin: "yra viduje",
    indexIntersect: "indeksų susikirtimas",
    itemTitle: "Elemento antraštė",
    displayFields: "Rodyti laukus",
    sortingFields: "Rūšiuoti laukus",
    setDisplayFields: "Nustatyti rodomus laukus",
    symbol: "Simbolis",
    setSymbol: "Nustatyti simbolį",
    serviceSymbolTip: "Naudoti simbolius, apibrėžtus pagal sluoksnį",
    exportTip: "Rodyti eksportavimo mygtuką",
    keepResultsTip: "Uždarius valdiklį palikti rezultatus ant žemėlapio",
    queryRelatedRecords: "Ieškoti susijusiuose įrašuose",
    createLayerForTaskTip: "Nurodyti, kaip užduotis kuria sluoksnius",
    oneLayerForTaskTip: "Šiai užduočiai kurti tik vieną sluoksnį",
    multipleLayerForTaskTip: "Kurti naują sluoksnį kiekvieną kartą, kai vykdoma ši užduotis"
  })
);
