define(
	 ({
		queries: "Užklausų užduotys",
		addNew: "Pridėti naują",
		setSource: "Grupė",
		setDataSource: "Nustatykite duomenų šaltinį",
		name: "Pavadinimas",
		querySource: "Duomenų šaltinis",
		queryName: "Užduoties pavadinimas",
		queryDefinition: "Filtro apibrėžimas",
		resultsSetting: "Rezultatų nustatymai",
		symbolSetting: "Simbolio nustatymas",
		resultSettingTip: "Nustatykite, ką ir kaip rodyti išvesties rezultatuose.",
		resultItemTitle: "Gauto elemento pavadinimas",
		resultItemContent: "Gauto elemento turinys",
		fieldsSetTip: "Pažymėkite, kurie laukai turi būti rodomi. Pasirinkite laukus ir galėsite atnaujinti jų pseudonimus, išdėstymo tvarką ir formatavimą.",
		addField: "Pridėti lauką",
		visibility: "Matomumas",
		alias: "Pseudonimas",
		specialType: "Specialus tipas",
		actions: "Veiksmai",
		none: "Nėra",
		link: "Nuoroda",
		image: "Paveikslėlis",
		noField: "Lauko nėra",
		operationalLayerTip: "Pridėti rezultatus kaip darbinį sluoksnį",
		setLayerSymbolTip: "Nustatykite užklausos rezultatų simbolį: ",
		setSelectedSymbolTip: "Nustatykite pasirinkto elemento simbolį.",
		notUseFilter: "Nenaudoti filtro",
		setSourceTip: "Nustatykite užklausos šaltinį.",
		setFilterTip: "Nustatykite filtrą tinkamai.",
		ok: "Gerai",
		cancel: "Atšaukti",
		noFilterTip: "Nenustačius filtro sąlygos, ši užklausos užduotis nurodys visus nurodyto duomenų šaltinio elementus."
  })
);