define(
   ({
    _widgetLabel: "인쇄",
    title: "맵 제목",
    format: "형식",
    layout: "레이아웃",
    settings: "고급",
    mapScaleExtent: "맵 축척/범위",
    preserve: "유지",
    mapScale: "맵 축척",
    mapExtent: "맵 범위",
    forceScale: "강제 축척",
    getCurrentScale: "현재",
    mapMetadata: "레이아웃 메타데이터",
    author: "작성자",
    copyright: "저작권",
    fullLayoutOptions: "전체 레이아웃 옵션",
    scaleBarUnitsMetric: "축척 막대 단위(미터법)",
    scaleBarUnitsNonMetric: "축척 막대 단위(비미터법)",
    unitsMiles: "마일",
    unitsKilometers: "킬로미터",
    unitsMeters: "미터",
    unitsFeet: "피트",
    unitsYards: "야드",
    unitsNauticalMiles: "해리",
    lncludeLegend: "범례 포함",
    printQualityOptions: "인쇄 품질",
    dpi: "DPI",
    mapOnlyOptions: "맵 전용 크기",
    width: "너비(px)",
    height: "높이(px)",
    print: "인쇄",
    clearList: "인쇄 지우기",
    creatingPrint: "인쇄를 생성 중",
    printError: "오류가 있습니다. 다시 시도하세요."
  })
);