define(
   ({
    "tabs_section_Label": "Sekmeler",
    "addTab": "Sekme Ekle",
    "layerName": "Katman",
    "layerType": "Analiz Türü",
    "layerLabel": "Etiket",
    "actions": "İşlemler",
    "closest": "En Yakın Detay",
    "proximity": "Yakınlık",
    "summary": "Özet",
    "select_lbl": "-- Seç --",
    "general_setting_Label": "Genel Ayarlar",
    "units_text_lbl": "Mesafe Birimleri",
    "miles": "Mil",
    "kilometers": "Kilometre",
    "feet": "Fit",
    "meters": "Metre",
    "yards": "Yarda",
    "nauticalMiles": "Deniz Mili",
    "maximum_distance_lbl": "En Yakın Detayın Maksimum Mesafesi",
    "buffer_text_lbl": "Tampon Etiketi",
    "buffer_lbl": "Tampon Mesafesi",
    "buffer_max_lbl": "Maksimum Tampon Mesafesi",
    "buffer_min_lbl": "Minimum Tampon Mesafesi",
    "routing_checkBox": "Rotalamayı Etkinleştir",
    "weather_Label": "Hava Durumu Seçenekleri",
    "weather_checkBox": "Hava Durumu Bilgilerini Ekle",
    "selectLayers": "Hava Durumu Katmanı Seç",
    "currentlySelectedLayer": "Şu anda seçili hava durumu katmanları",
    "missingTabLabel": "En az bir sekmenin etiketi yok",
    "cancel": "İptal",
    "ok": "Tamam",
    "missingLayerInWebMap": "Hiçbir işlem katmanı bulunamadı.",
    "selectFields": "Alanları Seç",
    "addField": "Alan Ekle",
    "sum": "TOP",
    "min": "MIN",
    "max": "MAKS",
    "avg": "ORT",
    "count": "SAYIM",
    "area": "ALAN",
    "length": "UZUNLUK",
    "count_checkBox": "Sayımı Göster",
    "area_checkBox": "Alanı Göster",
    "length_checkBox": "Uzunluğu Göster",
    "max_records": "Maksimum sınıra ulaşıldı"
  })
);
