define({
  root: {
    enableUndoRedo: "Enable Undo/Redo",
    toolbarVisible: "Toolbar Visible",
    toolbarOptions: "Toolbar Options",
    mergeVisible: "Merge",
    cutVisible: "Cut",
    reshapeVisible: "Reshape",
    back: "Back",
    label: "Layer",
    edit: "Editable",
    update: "Disable Update Geometry",
    fields: "Fields",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    editpageVisible: "Visible",
    editpageEditable: "Editable",
    geometryServiceURL: "Geometry Service URL:",
    lengthUnit: "Length Unit:",
    feet: "Feet (ft)",
    kilometers: "Kilometers (km)",
    meters: "Meters (m)",
    nauticalMiles: "Nautical Miles (nm)",
    statuteMiles: "Statute Miles (mi)",
    usStatuteMiles: "US Nautical Miles (nm)",
    areaUnit: "Area Unit:",
    acres: "Acres",
    ares: "Ares (a)",
    hectares: "Hectares (ha)",
    squareCentimeters: "Square Centimeters (cm^2)",
    squareDecimeters: "Square Decimeters (dm^2)",
    squareFeet: "Square Feet (ft^2)",
    squareInches: "Square Inches (in^2)",
    squareKilometers: "Square Kilometers (km^2)",
    squareMeters: "Square Meters (m^2)",
    squareMiles: "Square Miles (mi^2)",
    squareMillimeters: "Square Millimeters (mm^2)",
    squareYards: "Square Yards (yd^2)",
    currency: "Currency:",
    dollar: "Dollar ($)",
    euro: "Euro (€)",
    pound: "Pound (£)",
    yen: "Yen (¥)",
    projectLayer: "Project Layer",
    costEquation: "Cost Equation",
    convexHullBufferDistance: "Convex Hull Buffer Distance:",
    noLayers: "No editable feature layers available"
  }
});
