define(
   ({
    "tabs_section_Label": "Vahekaardid",
    "addTab": "Lisa vahekaart",
    "layerName": "Kiht",
    "layerType": "Analüüsi tüüp",
    "layerLabel": "Silt",
    "actions": "Tegevused",
    "closest": "Lähim objekt",
    "proximity": "Lähedus",
    "summary": "Kokkuvõte",
    "select_lbl": "-- Vali --",
    "general_setting_Label": "Üldseaded",
    "units_text_lbl": "Vahemaa ühikud",
    "miles": "Miilid",
    "kilometers": "Kilomeetrid",
    "feet": "Jalad",
    "meters": "Meetrid",
    "yards": "Jardid",
    "nauticalMiles": "Meremiilid",
    "maximum_distance_lbl": "Funktsiooni Lähim maksimaalne ulatus",
    "buffer_text_lbl": "Puhvri märgis",
    "buffer_lbl": "Puhvri ulatus",
    "buffer_max_lbl": "Maksimaalne puhvri ulatus",
    "buffer_min_lbl": "Minimaalne puhvri ulatus",
    "routing_checkBox": "Luba marsruutimine",
    "weather_Label": "Ilma suvandid",
    "weather_checkBox": "Kaasa ilmainfo",
    "selectLayers": "Vali ilmakihid",
    "currentlySelectedLayer": "Hetkel valitud ilmakihid",
    "missingTabLabel": "Vähemalt ühel vahekaardil puudub märgis.",
    "cancel": "Tühista",
    "ok": "Ok",
    "missingLayerInWebMap": "Töökihte ei leitud.",
    "selectFields": "Vali välja",
    "addField": "Lisa väli",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "KOGUARV",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Kuva arv",
    "area_checkBox": "Kuva ala",
    "length_checkBox": "Kuva pikkus",
    "max_records": "Limiit on täis"
  })
);
