define(
   ({
    taskUrl: "Tehtävän URL-osoite",
    serviceURLPlaceholder: "Syötä geoprosessointitehtävän URL-osoite",
    ok: "OK",
    cancel: "Peruuta",
    layer: "Karttataso",
    action: "Toimi",
    input: "Lähtöaineisto",
    output: "Tulosaineisto",
    name: "Nimi",
    type: "Tyyppi",
    required: "Pakollinen",
    layerOrder: "Karttatasojen järjestys",
    options: "Valinnat",
    defaultValue: "Oletusarvo",
    inputFeatureBy: "Lähtöaineiston kohde",
    renderer: "Renderöinti",
    displayType: "Näyttötyyppi",
    label: "Tunnusteksti",
    tooltip: "Työkalun ohje",
    visible: "Näkyvä",
    helpUrl: "Ohjeen URL-osoite",
    useResultMapService: "Käytä tuloskarttapalvelun piirustusoptioita",
    drawOnMap: "Interaktiivinen piirtäminen kartalla",
    selectLayer: "Karttatason valitseminen kartasta",
    url: "URL",
    symbol: "Symboli",
    shareResults: "Lisää tulos toiminnalliseksi karttatasoksi",
    popup: "Ponnahdusikkuna",
    setTask: "Aseta",
    setTaskTitle: "Määritä geoprosessointitehtävä",
    enablePopup: "Ota ponnahdusikkunat käyttöön",
    unSupportGeometryType: "Renderöintiä ei voi määrittää tuntemattoman geometriatyypin vuoksi.",
    useUrlForGPInput: "URL-osoite",
    useUploadForGPInput: "Lähetä tiedosto",
    selectFileToUpload: "Valitse tiedosto...",
    upload: "Lähetä",
    rasterFormat: "Rasteriaineiston muoto",
    noFileSelected: "Yhtään tiedostoa ei ole valittu.",
    uploadSuccess:"Tiedoston lataus onnistui.",
    showLayerContent: "Näytä karttatason sisältö",
    Feet: "Jalkaa",
    Yards: "Jaardia",
    Miles: "Mailia",
    NauticalMiles: "Meripeninkulmaa",
    Meter: "Metriä",
    Kilometers: "Kilometriä",
    urlPlaceholder: "kohderyhmän URL-osoite",
    allowToExport: "Salli tulosten vienti"
  })
);
