define(
   ({
    taskUrl: "Tehtävän URL-osoite",
    serviceURLPlaceholder: "Syötä geoprosessointitehtävän URL-osoite",
    ok: "OK",
    cancel: "Peruuta",
    layer: "Karttataso",
    action: "Toimi",
    input: "Lähtöaineisto",
    output: "Tulosaineisto",
    name: "Nimi",
    type: "Tyyppi",
    required: "Pakollinen",
    layerOrder: "Karttatasojen järjestys",
    options: "Valinnat",
    defaultValue: "Oletusarvo",
    inputFeatureBy: "Lähtöaineiston kohde",
    renderer: "Renderöinti",
    displayType: "Näyttötyyppi",
    label: "Tunnusteksti",
    tooltip: "Työkalun ohje",
    visible: "Näkyvä",
    helpUrl: "Ohjeen URL-osoite",
    useResultMapService: "Käytä tuloskarttapalvelun piirustusoptioita",
    drawOnMap: "Interaktiivinen piirtäminen kartalla",
    selectLayer: "Karttatason valitseminen kartasta",
    url: "URL",
    symbol: "Symboli",
    shareResults: "Lisää tulos toiminnalliseksi karttatasoksi",
    popup: "Ponnahdusikkuna",
    setTask: "Aseta",
    setTaskTitle: "Määritä geoprosessointitehtävä",
    enablePopup: "Ota ponnahdusikkunat käyttöön"
  })
);