define({
  root: ({
    taskUrl: "Profile Task URL",
    serviceURLPlaceholder: "Please input Profile task URL",
    ok: "OK",
    cancel: "Cancel",
    setTask: "Set",
    setTaskTitle: "Set Profile Task",
    invalidURL: "Invalid Profile Task URL",
    urlContainsProfile: "Task URL should not contain /Profile",
    feet: "Feet",
    metric: "Metric",
    measureunits: "Measure Units",
    chart: {
      title: "Elevation Profile",
      elevationTitleTemplate: "Elevation in {0}",
      distanceTitleTemplate: "Distance in {0}",
      chartTitleFontSize: "Chart Title Font Size",
      axisTitleFontSize: "Axis Title Font Size",
      axisLabelFontSize: "Axis Label Font Size",
      indicatorFontColor: "Indicator Font Color",
      indicatorFillColor: "Indicator Fill Color",
      titleFontColor: "Chart Title Font Color",
      axisFontColor: "Axis Font Color",
      axisMajorTickColor: "Axis Major Tick Color",
      skyTopColor: "Sky Top Color",
      skyBottomColor: "Sky Bottom Color",
      waterLineColor: "Water Line Color",
      waterTopColor: "Water Top Color",
      waterBottomColor: "Water Bottom Color",
      elevationLineColor: "Elevation Line Color",
      elevationTopColor: "Elevation Top Color",
      elevationBottomColor: "Elevation Bottom Color",
      constrain: "Constrain profile height to 320px",
      constraintooltip: "Use this option when placing this widget in a panel and not in a onscreen widget."
    },
    editDefaultSym: "Edit Default Line Symbol",
    editChartProperties: "Edit Chart Display Properties",
    lineSymbol: "Line Symbol: ",
    symbologyTooltip: "Click on the symbology symbol that you want to edit."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
