define(
	 ({
		queries: "Querytaken",
		addNew: "Nieuwe toevoegen",
    queryLayer: "Querylaag",
		setSource: "Instellen",
		setDataSource: "Gegevensbron instellen",
		name: "Naam",
		querySource: "Bron gegevens",
		queryName: "Naam taak",
		queryDefinition: "Definitie filter",
		resultsSetting: "Resultaten instelling",
		symbolSetting: "Symboolinstelling",
		resultSettingTip: "Definieer welke uitvoerresultaten u wilt weergeven en hoe.",
		resultItemTitle: "Titel van resultaatitem",
		resultItemContent: "Inhoud van resultaatitem",
		fieldsSetTip: "Selecteer de velden die u wilt weergeven. Selecteer een veld om de alias, de volgorde en opmaak ervan bij te werken.",
		addField: "Veld toevoegen",
		visibility: "Zichtbaarheid",
		alias: "Alias",
		specialType: "Speciaal type",
		actions: "Acties",
		none: "Geen",
		link: "Koppeling",
		image: "Afbeelding",
		noField: "Geen veld",
		operationalLayerTip: "Resultaat toevoegen als operationele laag",
		setLayerSymbolTip: "Stel het symbool voor queryresultaten in: ",
		setSelectedSymbolTip: "Stel het symbool van geselecteerde objecten in.",
		notUseFilter: "Geen filter gebruiken",
		setSourceTip: "Stel de querybron in.",
		setFilterTip: "Stel het filter correct in.",
		ok: "OK",
		cancel: "Annuleren",
		noFilterTip: "Zonder filterexpressie zal deze querytaak alle functies in de opgegeven gegevensbron weergeven.",
    relationships: "Relaties",
    addRelationshipLayer: "Nieuwe relatie toevoegen",
    relatedTo: "Met betrekking tot",
    selectOption: "Selecteren.",
    resultItemSorting: "Sorteren resultaatitem",
    field: "Veld",
    sortingOrder: "Volgorde",
    configureFieldsTip: "Configureer de velden waarop het queryresultaat wordt gesorteerd.",
    setSortingFields: "Sorteervelden instellen",
    ascending: "Oplopend",
    descending: "Aflopend",
    sortBy: "Sorteren op",
    thenBy: "Vervolgens op",
    addTask: "Taak toevoegen",
    noTasksTip: 'Geen taken, klik op \"${addTask}\" om te starten!',
    infoText: "Info",
    filters: "Filters",
    results: "Resultaten",
    optionsText: "Opties",
    summaryText: "Samenvatting",
    attributeFilter: "Attribuutfilter",
    attributeFilterTip: "Bepaal attrivuutexpressies voor gebruik in de widget om de querylaag te filteren.",
    noExpressionDefinedTip: "Er is geen expressie bepaald.",
    needInputValuesTip: "Invoer vereist bij runtime",
    setExpressions: "Expressies instellen",
    spatialFilter: "Ruimtelijk filter",
    spatialFilterTip: "Kies de ruimtelijke filter(s) die in de widget gebruikt worden om de resultaten te beperken.",
    defaultOption: "Standaard",
    useCurrentExtentTip: "Gedeeltelijk of volledig in de actuele kaart",
    useDrawGraphicTip: "Gedeeltelijk of volledig in de vorm die op de kaart getekend is",
    useFeaturesTip: "Op basis van de locaties t.o.v. de objecten in een andere laag",
    noSpatialLimitTip: "Resultaten niet ruimtelijk beperken",
    drawingTools: "Tekentools",
    bufferSettings: "Bufferinstellingen",
    defaultDistance: "Standaardafstand",
    bufferDistance: "Bufferafstand",
    defaultUnit: "Standaardeenheid",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    availableSpatialRelationships: "Beschikbare ruimtelijke relaties",
    setSpatialRelationships: "Ruimtelijke relaties instellen",
    availability: "Beschikbaarheid",
    relationship: "Verhouding",
    label: "Label",
    intersect: "kruisen",
    contain: "bevatten",
    areContainedIn: "zijn omvat in",
    cross: "kruis",
    envelopeIntersect: "kruisingenvelop",
    overlap: "overlappen",
    areOverlapped: "zijn overlapt",
    touche: "aanraking",
    within: "in",
    areWithin: "bevinden zich in",
    indexIntersect: "index kruising",
    itemTitle: "Itemtitel",
    displayFields: "Weergavevelden",
    sortingFields: "Sorteervelden",
    setDisplayFields: "Weergavevelden instellen",
    symbol: "Symbool",
    setSymbol: "Symbool instellen",
    serviceSymbolTip: "Gebruik de symbolen die door de laag zijn gedefinieerd",
    exportTip: "Export-knop weergeven",
    keepResultsTip: "Houd resultaten op de kaart nadat de widget gesloten is",
    queryRelatedRecords: "Gerelateerde records zoeken",
    createLayerForTaskTip: "Specificeren hoe de taak lagen creëert",
    oneLayerForTaskTip: "Slechts één laag creëren voor deze taak",
    multipleLayerForTaskTip: "Een nieuwe laag creëren telkens deze taak uitgevoerd wordt"
  })
);
