define(
	 ({
		queries: "Querytaken",
		addNew: "Nieuwe toevoegen",
		setSource: "Instellen",
		setDataSource: "Gegevensbron instellen",
		name: "Naam",
		querySource: "Bron gegevens",
		queryName: "Naam taak",
		queryDefinition: "Definitie filter",
		resultsSetting: "Resultaten instelling",
		symbolSetting: "Symboolinstelling",
		resultSettingTip: "Definieer welke uitvoerresultaten u wilt weergeven en hoe.",
		resultItemTitle: "Titel van resultaatitem",
		resultItemContent: "Inhoud van resultaatitem",
		fieldsSetTip: "Selecteer de velden die u wilt weergeven. Selecteer een veld om de alias, de volgorde en opmaak ervan bij te werken.",
		addField: "Veld toevoegen",
		visibility: "Zichtbaarheid",
		alias: "Alias",
		specialType: "Speciaal type",
		actions: "Acties",
		none: "Geen",
		link: "Koppeling",
		image: "Afbeelding",
		noField: "Geen veld",
		operationalLayerTip: "Resultaat toevoegen als operationele laag",
		setLayerSymbolTip: "Stel het symbool voor queryresultaten in: ",
		setSelectedSymbolTip: "Stel het symbool van geselecteerde objecten in.",
		notUseFilter: "Geen filter gebruiken",
		setSourceTip: "Stel de querybron in.",
		setFilterTip: "Stel het filter correct in.",
		ok: "OK",
		cancel: "Annuleren",
		noFilterTip: "Zonder filterexpressie zal deze querytaak alle functies in de opgegeven gegevensbron weergeven."
  })
);