define(
   ({
    _widgetLabel: "Rapportgeoobjekt",
    select: "Velg",
    draw: "Tegn",
    chooseALayer: "Velg et lag",
    clickAFeature: "Klikk på et geoobjekt på kartet for å velge det.",
    loadingFeatures: "Henter detaljer for valgt geoobjekt...",
    errorTitle: "Feil",
    errorIdentify: "Identifiser geoobjektsfeil. Se konsolloggen for flere detaljer.",
    infoWindowTitle: "Detaljer",
    layerLabel: "Lagnavn",
    reviewStatusLabel: "Kontrollstatus",
    selectReviewStatusAdd: "Legg til geoobjekt",
    selectReviewStatusDelete: "Slett geoobjekt",
    selectReviewStatusMove: "Flytt geoobjekt",
    selectReviewStatusReshape: "Endre formen på geoobjekt",
    drawReviewStatusMissing: "Geoobjekt(er) mangler",
    drawReviewStatusPosition: "Mulig feil",
    drawReviewStatusShape: "Formfeil",
    drawReviewStatusAttribute: "Attributtfeil",
    notesLabel: "Merknader",
    severityLabel: "Alvorlighetsgrad",
    reportedByLabel: "Rapportert av",
    reportedByDefault: "anonym",
    reportButton: "Rapport",
    reportMessage: "Rapport mottatt",
    errorReportMessage: "Det oppstod en feil ved rapportering av geoobjektet",
    drawErrorInstructions: "Velg punkt, linje eller polygon, og tegn feilgeometrien på kartet:",
    errorMapService: "Kan ikke hente karttjenesteinformasjon",
    noFeatureSelected : "Finner ingen geoobjekter på lokasjonen det ble klikket på",
    selectFeatureMapPoint: "Klikk for å velge et geoobjekt",
    drawFeatureMapPoint: "Klikk for å legge til et punkt",
    popupMessage:"Melding",
    popupError:"Feil",
    manyFeaturesSelected: "Flere geoobjekter ble funnet. Zoom inn, og velg et geoobjekt som skal rapporteres."
  })
);
