define(
   ({
    routeUrl: "Adres URL trasy",
    locatorUrl: "Adres URL geokodera",
    geocoderOptions: "Opcje geokodera",
    autoComplete: "Autouzupełnianie",
    maxLocations: "Maksymalna liczba lokalizacji",
    minCharacters: "Minimalna liczba znaków",
    searchDelay: "Opóźnienie wyszukiwania",
    placeholder: "Symbol zastępczy",
    routeOptions: "Opcje trasy",
    directionsLanguage: "Język wskazówek",
    directionsLengthUnits: "Jednostki długości używane we wskazówkach",
    directionsOutputType: "Typ wynikowych wskazówek",
    impedanceAttribute: "Atrybut impedancji",
    kilometers: "Kilometry",
    miles: "Mile",
    meters: "Metry",
    feet: "Stopy",
    yards: "Jardy",
    nauticalMiles: "Mile Morskie",
    parametersTip: "Skonfiguruj poprawnie atrybuty!",
    complete: "Zakończone",
    completeNoEvents: "Zakończone brakiem zdarzeń",
    instructionsOnly: "Tylko instrukcje",
    standard: "Standard",
    summaryOnly: "Tylko podsumowanie",
    travelModesUrl: "URL trybów podróżowania",
    searchPlaceholder: "Znajdź adres lub miejsce",
    trafficLayerUrl: "Adres URL warstwy ruchu drogowego"
  })
);