define(
   ({
    _widgetLabel: "Spørring",
    executeQueryTip: "Klikk på ett av disse oppgaveelementene for å utføre spørringen.",
    invalidConfig: "Ugyldig konfigurasjon. Bruk innstillingssiden for spørringer til å hente riktig konfigurasjon.",
    queryParams: "Alternativer",
    parameters: "ALTERNATIVER",
    queries: "SPØRRINGER",
    apply: "BRUK",
    queryResults: "Resultater",
    clear: "Fjern",
    noResults: "Fant ingen geoobjekter.",
    queryError: "Spørringen mislyktes.",
    numberFound: "Antall geoobjekter som ble funnet:",
    mapExtentTip: "Begrens resultatene til den gjeldende kartutstrekningen.",
    noValue: "Ingen verdi",
    and: "og",
    stringOperatorIs: "er", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "er ikke",
    stringOperatorStartsWith: "begynner på",
    stringOperatorEndsWith: "slutter på",
    stringOperatorContains: "inneholder",
    stringOperatorDoesNotContain: "inneholder ikke",
    stringOperatorIsBlank: "er tomt",
    stringOperatorIsNotBlank: "er ikke tomt",
    dateOperatorIsOn: "er den", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "er ikke den",
    dateOperatorIsBefore: "er før",
    dateOperatorIsAfter: "er etter",
    dateOperatorDays: "dagene",
    dateOperatorWeeks: "ukene", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "månedene",
    dateOperatorInTheLast: "i de/den siste",
    dateOperatorNotInTheLast: "ikke i de/den siste",
    dateOperatorIsBetween: "er mellom",
    dateOperatorIsNotBetween: "er ikke mellom",
    dateOperatorIsBlank: "er tomt",
    dateOperatorIsNotBlank: "er ikke tomt",
    numberOperatorIs: "er", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "er ikke",
    numberOperatorIsAtLeast: "er minst",
    numberOperatorIsLessThan: "er mindre enn",
    numberOperatorIsAtMost: "er maksimalt",
    numberOperatorIsGreaterThan: "er større enn",
    numberOperatorIsBetween: "er mellom",
    numberOperatorIsNotBetween: "er ikke mellom",
    numberOperatorIsBlank: "er tomt",
    numberOperatorIsNotBlank: "er ikke tomt",
    operationalLayerTip: "Legg til resultat som operativt kartlag",
    queryResult: "Spørringsresultat",
    specifyParamsTip: "Angi parametere for denne oppgaven",
    useSpatialFilter: "Bruk geografisk filter til å begrense geoobjekter",
    useCurrentMapExtent: "Bare geoobjekter som berører gjeldende kartutstrekning",
    drawGraphicOnMap: "Bare geoobjekter som berører et brukerdefinert område",
    specifySpatialFilterMsg: "Angi et romlig filter for denne oppgaven.",
    clearResults: "Fjern resultater",
    operationalTip: 'Når dette alternativet er merket av, beholdes resultatene på kartet frem til det klikkes på knappen ${clearResults}.',
    noneQueryTip: "Ingen forhåndskonfigurerte spørringsoppgaver er tilgjengelige.",
    noPermissionsMsg: "Du har ikke tillatelse til å bruke denne tjenesten."
  })
);