define(
   ({
    _widgetLabel: "印刷",
    title: "タイトル",
    format: "書式設定",
    layout: "レイアウト",
    settings: "高度",
    mapScaleExtent: "マップ縮尺/範囲",
    preserve: "マップの状態を維持",
    mapScale: "縮尺",
    mapExtent: "範囲",
    forceScale: "縮尺の適用",
    getCurrentScale: "現在値",
    mapMetadata: "レイアウト",
    author: "作成者",
    copyright: "著作権",
    fullLayoutOptions: "全レイアウト オプション",
    scaleBarUnitsMetric: "メートル法の単位の縮尺記号",
    scaleBarUnitsNonMetric: "メートル法以外の単位の縮尺記号",
    unitsMiles: "マイル",
    unitsKilometers: "キロメートル",
    unitsMeters: "メートル",
    unitsFeet: "フィート",
    unitsYards: "ヤード",
    unitsNauticalMiles: "海里",
    lncludeLegend: "凡例",
    printQualityOptions: "印刷品質",
    dpi: "DPI",
    mapOnlyOptions: "サイズ (MAP_ONLY)",
    width: "幅 (px)",
    height: "高さ (px)",
    print: "印刷",
    clearList: "印刷結果の消去",
    creatingPrint: "印刷中",
    printError: "エラーが発生しました。もう一度試してください。"
  })
);