define(
   ({
    routeUrl: "URL δρομολόγησης",
    locatorUrl: "URL εργαλείου γεωκωδικοποίησης",
    geocoderOptions: "Επιλογές εργαλείου γεωκωδικοποίησης",
    autoComplete: "Αυτόματη συμπλήρωση",
    maxLocations: "Μέγιστος αριθμός τοποθεσιών",
    minCharacters: "Ελάχιστος αριθμός χαρακτήρων",
    searchDelay: "Καθυστέρηση αναζήτησης",
    placeholder: "Κείμενο υπόδειξης",
    routeOptions: "Επιλογές δρομολόγησης",
    directionsLanguage: "Γλώσσα οδηγιών",
    directionsLengthUnits: "Μονάδες μήκους οδηγιών",
    directionsOutputType: "Τύπος εμφάνισης οδηγιών",
    impedanceAttribute: "Κύριο γνώρισμα δρομολόγησης",
    kilometers: "Χιλιόμετρα",
    miles: "Μίλια",
    meters: "Μέτρα",
    feet: "Πόδια",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    parametersTip: "Ορίστε σωστά τις παραμέτρους !",
    complete: "Ολοκληρωμένος",
    completeNoEvents: "Ολοκληρωμένος - χωρίς συμβάντα",
    instructionsOnly: "Μόνο οδηγίες",
    standard: "Βασικός",
    summaryOnly: "Μόνο σύνοψη",
    travelModesUrl: "URL τρόπων μετάβασης",
    searchPlaceholder: "Αναζήτηση διεύθυνσης ή μέρους",
    trafficLayerUrl: "URL θεματικού επιπέδου κίνησης"
  })
);