define({
	root: ({
		chartTasks: "Chart Tasks",
		addNew: "Add New",
		addNewTip: "Add a New Chart Task",
		name: "Name",
		set: "Set",
		setDataSource: "Set Data Source",
		generalSettingsTip: "Set data source, title and description for charts.",
		chartModeSettingTip: "Select a way to analyze and display data as charts.",
		detailsSettingTip: "Set chart appearance by specifying its types and color, and what values to be charted:",
		symbolSettingTip: "Set the map display for charted data.",
		addFilterTip: "Add Filter to this Data",
		dataSource: "Data Source",
		noResults: "No feature found.",
		chartTitle: "Chart Title",
		description: "Description",
		chartingMode: "Chart Display",
		featureOption: "Display values feature by feature",
		categoryOption: "Display values by category",
		countOption: "Display feature counts by category",
		fieldOption: "Display attribute values as charts",
		category: "Category",
		axisLabel: "Category Label",
		categoryField: "Category Field",
		operation: "Operation",
		originalOption: "Use original values",
		sumOption: "Sum",
		averageOption: "Average",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Value Fields",
		moveUp: "Move up",
		moveDown: "Move down",
		sortOrder: "Sort Charts Order via Category Labels",
		ascending: "Ascending",
		descending: "Descending",
		chartType: "Chart Type",
		column: "Column Chart",
		bar: "Bar Chart",
		line: "Line Chart",
		pie: "Pie Chart",
		chartColor: "Chart Color",
		showDataLabels: "Show Data Labels",
		setSymbol: "Selection Symbol",
		setHighLightColor: "Highlight Color",
		settings: "Settings",
		mapInterationOptions: "Map Interaction Options",
		preview: "Preview",
		ok: "OK",
		cancel: "Cancel",
		close: "Close",
		setFilterTip: "Please set filter correctly. ",
		setChartTitleTip: "Please set chart title.",
		setChartTypeTip: "Please select one chart type at least.",
		setDataFieldTip: "Please select one value field at least.",
		setOutputFieldTip: "Please set output fields.",
		count: "Count",
		label: "Label",
		horizontalAxis: "Horizontal Axis",
		verticalAxis: "Vertical Axis",
		dataLabels: "Data Labels",
		color: "Color",
		colorful: "Colorful",
		monochromatic: "Monochromatic",
    noTaskTip: "Click Add New to add a chart task",
    info: "Info",
    charts: "Charts",
    options: "Options",
    taskName: "Task Name",
    summary: "Summary",
    resultDescription: "Result Description",
    spatialFilterTip: "Choose the spatial filter(s) used in the widget to limit results.",
    defaultOption: "Default",
    useCurrentExtentTip: "Partially or completely within current map extent",
    useDrawGraphicTip: "Partially or completely within the shape drawn on the map",
    useFeaturesTip: "Based on their locations relative to features in another layer",
    noSpatialLimitTip: "Do not spatially limit results",
    drawingTools: "Drawing tools",
    bufferSettings: "Buffer Settings",
    defaultDistance: "Default Distance",
    bufferDistance: "Buffer Distance",
    defaultUnit: "Default Unit",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    availableSpatialRelationships: "Available Spatial Relationships",
    setSpatialRelationships: "Set Spatial Relationships",
    availability: "Availability",
    relationship: "Relationship",
    actions: "Actions",
    intersect: "intersect",
    contain: "contain",
    areContainedIn: "are contained in",
    cross: "cross",
    envelopeIntersect: "envelope intersect",
    overlap: "overlap",
    areOverlapped: "are overlapped",
    touche: "touche",
    within: "within",
    areWithin: "are within",
    indexIntersect: "index intersect"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});