define({
	root: ({
		queries: "Query Tasks",
		addNew: "Add New",
		setSource: "Set",
		setDataSource: "Set Data Source",
		name: "Name",
		querySource: "Data Source",
		queryName: "Task Name",
		queryDefinition: "Filter Definition",
		resultsSetting: "Results Setting",
		symbolSetting: "Symbol Setting",
		resultSettingTip: "Define what and how to display the output results.",
		resultItemTitle: "Result Item Title",
		resultItemContent: "Result Item Contents",
		fieldsSetTip: "Check the fields you want to display. Select a field to update its alias, order, and format.",
		addField: "Add Field",
		visibility: "Visibility",
		alias: "Alias",
		specialType: "Special Type",
		actions: "Actions",
		none: "None",
		link: "Link",
		image: "Image",
		noField: "No field",
		operationalLayerTip: "Add result as operational layer",
		setLayerSymbolTip: "Set symbol for query results: ",
		setSelectedSymbolTip: "Set symbol of selected feature.",
		notUseFilter: "Don't use filter",
		setSourceTip: "Please set query source.",
		setFilterTip: "Please set filter correctly.",
		ok: "OK",
		cancel: "Cancel",
		noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});