define({
	root: ({
		queries: "Query Tasks",
		addNew: "Add New",
    queryLayer: "Query Layer",
		setSource: "Set",
		setDataSource: "Set Data Source",
		name: "Name",
		querySource: "Data Source",
		queryName: "Task Name",
		queryDefinition: "Filter Definition",
		resultsSetting: "Results Setting",
		symbolSetting: "Symbol Setting",
		resultSettingTip: "Define what and how to display the output results.",
		resultItemTitle: "Result Item Title",
		resultItemContent: "Result Item Contents",
		fieldsSetTip: "Check the fields you want to display. Select a field to update its alias, order, and format.",
		addField: "Add Field",
		visibility: "Visibility",
		alias: "Alias",
		specialType: "Special Type",
		actions: "Actions",
		none: "None",
		link: "Link",
		image: "Image",
		noField: "No field",
		operationalLayerTip: "Add result as operational layer",
		setLayerSymbolTip: "Set symbol for query results: ",
		setSelectedSymbolTip: "Set symbol of selected feature.",
		notUseFilter: "Don't use filter",
		setSourceTip: "Please set query source.",
		setFilterTip: "Please set filter correctly.",
		ok: "OK",
		cancel: "Cancel",
		noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source.",
    relationships: "Relationships",
    addRelationshipLayer: "Add New Relationship",
    relatedTo: "Related To",
    selectOption: "Please select..",
    resultItemSorting: "Result Item Sorting",
    field: "Field",
    sortingOrder: "Order",
    configureFieldsTip: "Please configure the fields which the query result will be sorted by.",
    setSortingFields: "Set Sorting Fields",
    ascending: "Ascending",
    descending: "Descending",
    sortBy: "Sort by",
    thenBy: "Then by",
    addTask: "Add task",
    noTasksTip: 'No tasks, please click "${addTask}" to start!',
    infoText: "Info",
    filters: "Filters",
    results: "Results",
    optionsText: "Options",
    summaryText: "Summary",
    attributeFilter: "Attribute Filter",
    attributeFilterTip: "Define attribute expressions for use in the widget to filter the query layer .",
    noExpressionDefinedTip: "No expression was defined.",
    needInputValuesTip: "Need to input values at runtime",
    setExpressions: "Set Expressions",
    spatialFilter: "Spatial Filter",
    spatialFilterTip: "Choose the spatial filter(s) used in the widget to limit results.",
    defaultOption: "Default",
    useCurrentExtentTip: "Partially or completely within current map extent",
    useDrawGraphicTip: "Partially or completely within the shape drawn on the map",
    useFeaturesTip: "Based on their locations relative to features in another layer",
    noSpatialLimitTip: "Do not spatially limit results",
    drawingTools: "Drawing tools",
    bufferSettings: "Buffer Settings",
    defaultDistance: "Default Distance",
    bufferDistance: "Buffer Distance",
    defaultUnit: "Default Unit",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    availableSpatialRelationships: "Available Spatial Relationships",
    setSpatialRelationships: "Set Spatial Relationships",
    availability: "Availability",
    relationship: "Relationship",
    label: "Label",
    intersect: "intersect",
    contain: "contain",
    areContainedIn: "are contained in",
    cross: "cross",
    envelopeIntersect: "envelope intersect",
    overlap: "overlap",
    areOverlapped: "are overlapped",
    touche: "touche",
    within: "within",
    areWithin: "are within",
    indexIntersect: "index intersect",
    itemTitle: "Item Title",
    displayFields: "Display Fields",
    sortingFields: "Sorting Fields",
    setDisplayFields: "Set Display Fields",
    symbol: "Symbol",
    setSymbol: "Set symbol",
    serviceSymbolTip: "Use symbols defined by the layer",
    exportTip: "Show Export button",
    keepResultsTip: "Keep results on the map after widget is closed",
    queryRelatedRecords: "Query related records",
    createLayerForTaskTip: "Specify how the task creates layers",
    oneLayerForTaskTip: "Only create one layer for this task",
    multipleLayerForTaskTip: "Create a new layer every time this task executes"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
