define({
  root: ({
    _widgetLabel: "Analysis",
    executeAnalysisTip: "Click an analysis tool to execute",
    noToolTip: "No analysis tool is selected!",
    back: "Back",
    next: "Next",
    home: "Home",
    jobSubmitted: "submitted.",
    jobCancelled: "Canceled.",
    jobFailed: "Failed",
    jobSuccess: "Succeeded.",
    executing: "Executing",
    cancelJob: "Cancel the analysis task",
    paramName: "Parameter Name",
    link: "Link",
    learnMore: "Learn More",
    messages: "Messages",
    outputs: "Outputs",
    outputtip: "Note: Feature and table outputs are added in the map as operational layers.",
    outputSaveInPortal: "The data has been saved in your portal.",
    privilegeError: "Your user role cannot perform analysis. In order to perform analysis, the administrator of your organization needs to grant you certain <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a>."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
