define(
   ({
    "tabs_section_Label": "选项卡",
    "addTab": "添加选项卡",
    "layerName": "图层",
    "layerType": "分析类型",
    "layerLabel": "标注",
    "actions": "操作",
    "closest": "最近的要素",
    "proximity": "邻域分析",
    "summary": "摘要",
    "select_lbl": "-- 选择 --",
    "general_setting_Label": "常规设置",
    "units_text_lbl": "距离单位",
    "miles": "英里",
    "kilometers": "千米",
    "feet": "英尺",
    "meters": "米",
    "yards": "码",
    "nauticalMiles": "海里",
    "maximum_distance_lbl": "最近的要素最大距离",
    "buffer_text_lbl": "缓冲区标注",
    "buffer_lbl": "缓冲距离",
    "buffer_max_lbl": "最大缓冲距离",
    "buffer_min_lbl": "最小缓冲距离",
    "routing_checkBox": "启用路径查找",
    "weather_Label": "天气选项",
    "weather_checkBox": "包括天气信息",
    "selectLayers": "选择天气图层",
    "currentlySelectedLayer": "当前选择的天气图层",
    "missingTabLabel": "至少一个选项卡缺失标注",
    "cancel": "取消",
    "ok": "确定",
    "missingLayerInWebMap": "未找到业务图层。",
    "selectFields": "选择字段",
    "addField": "添加字段",
    "sum": "总和",
    "min": "最小值",
    "max": "最大值",
    "avg": "平均值",
    "count": "计数",
    "area": "面积",
    "length": "长度",
    "count_checkBox": "显示计数",
    "area_checkBox": "显示面积",
    "length_checkBox": "显示长度",
    "max_records": "已达到最大限制"
  })
);
