define(
   ({
    _widgetLabel: "Raportare obiect spaţial",
    select: "Selectare",
    draw: "Trasare",
    chooseALayer: "Selectaţi un strat tematic",
    clickAFeature: "Faceţi clic pe un obiect spaţial de pe hartă pentru a-l selecta.",
    loadingFeatures: "Se obţin detaliile obiectului spaţial selectat...",
    errorTitle: "Eroare",
    errorIdentify: "Identificaţi erorile obiectelor spaţiale. Verificaţi jurnalul consolei pentru detalii.",
    infoWindowTitle: "Detalii",
    layerLabel: "Nume strat tematic",
    reviewStatusLabel: "Revizuire stare",
    selectReviewStatusAdd: "Adăugare obiect spaţial",
    selectReviewStatusDelete: "Ştergere obiect spaţial",
    selectReviewStatusMove: "Mutare obiect spaţial",
    selectReviewStatusReshape: "Remodelare obiect spaţial",
    drawReviewStatusMissing: "Obiecte spaţiale lipsă",
    drawReviewStatusPosition: "Eroare poziţională",
    drawReviewStatusShape: "Eroare formă",
    drawReviewStatusAttribute: "Eroare atribute",
    notesLabel: "Note",
    severityLabel: "Gravitate",
    reportedByLabel: "Raportat de",
    reportedByDefault: "anonim",
    reportButton: "Raport",
    reportMessage: "Raport primit",
    errorReportMessage: "A existat o eroare la raportarea obiectului dvs. spaţial",
    drawErrorInstructions: "Selectaţi punctul, linia sau poligonul şi trasaţi geometria erorii pe hartă:",
    errorMapService: "A existat o eroare la obţinerea informaţiilor serviciului hărţii",
    noFeatureSelected : "În locaţia pe care s-a făcut clic nu s-a găsit niciun obiect spaţial",
    selectFeatureMapPoint: "Faceţi clic pentru a selecta un obiect spaţial",
    drawFeatureMapPoint: "Faceţi clic pentru a adăuga un punct",
    popupMessage:"Mesaj",
    popupError:"Eroare",
    manyFeaturesSelected: "S-au găsit mai multe obiecte spaţiale. Măriţi şi selectaţi un obiect spaţial care va fi raportat."
  })
);
