define(
   ({
    "tabs_section_Label": "Καρτέλες",
    "addTab": "Προσθήκη καρτέλας",
    "layerName": "Θεματικό επίπεδο",
    "layerType": "Τύπος ανάλυσης",
    "layerLabel": "Ετικέτα",
    "actions": "Ενέργειες",
    "closest": "Πλησιέστερο στοιχείο",
    "proximity": "Εγγύτητα",
    "summary": "Σύνοψη",
    "select_lbl": "-- Επιλογή --",
    "general_setting_Label": "Γενικές ρυθμίσεις",
    "units_text_lbl": "Μονάδες απόστασης",
    "miles": "Μίλια",
    "kilometers": "Χιλιόμετρα",
    "feet": "Πόδια",
    "meters": "Μέτρα",
    "yards": "Γιάρδες",
    "nauticalMiles": "Ναυτικά μίλια",
    "maximum_distance_lbl": "Μέγιστη απόσταση πλησιέστερου στοιχείου",
    "buffer_text_lbl": "Ετικέτα ζώνης",
    "buffer_lbl": "Απόσταση ζώνης",
    "buffer_max_lbl": "Μέγιστη απόσταση ζώνης",
    "buffer_min_lbl": "Ελάχιστη απόσταση ζώνης",
    "routing_checkBox": "Ενεργοποίηση δρομολόγησης",
    "weather_Label": "Επιλογές καιρού",
    "weather_checkBox": "Συμπερίληψη πληροφοριών καιρού",
    "selectLayers": "Επιλογή θεματικών επιπέδων καιρού",
    "currentlySelectedLayer": "Επιλεγμένα θεματικά επίπεδα καιρού",
    "missingTabLabel": "Λείπει η ετικέτα από τουλάχιστον μία καρτέλα",
    "cancel": "Ακύρωση",
    "ok": "ΟΚ",
    "missingLayerInWebMap": "Δεν βρέθηκαν επιχειρησιακά επίπεδα.",
    "selectFields": "Επιλογή πεδίων",
    "addField": "Προσθήκη πεδίου",
    "sum": "ΑΘΡ",
    "min": "ΕΛΑΧ",
    "max": "ΜΕΓ.",
    "avg": "Μ.Ο.",
    "count": "ΠΛΗΘΟΣ",
    "area": "ΠΕΡΙΟΧΗ",
    "length": "ΜΗΚΟΣ",
    "count_checkBox": "Εμφάνιση πλήθους",
    "area_checkBox": "Εμφάνιση περιοχής",
    "length_checkBox": "Εμφάνιση μήκους",
    "max_records": "Το μέγιστο όριο εξαντλήθηκε"
  })
);
