define(
	 ({
		charts: "Tác vụ Biểu đồ",
		addNew: "Thêm Mới",
		addNewTip: "Thêm Tác vụ Biểu đồ mới",
		name: "Tên",
		set: "Thiết lập",
		setDataSource: "Thiết lập Nguồn Dữ liệu",
		generalSettingsTip: "Thiết lập nguồn dữ liệu, tiêu đề và mô tả cho biểu đồ.",
		chartModeSettingTip: "Chọn phương pháp để phân tích và hiển thị dữ liệu dưới dạng biểu đồ.",
		detailsSettingTip: "Thiết lập giao diện biểu đồ bằng cách chỉ định loại biểu đồ, màu sắc và giá trị sẽ được lập biểu đồ.",
		symbolSettingTip: "Thiết lập hiển thị bản đồ cho dữ liệu đã được lập biểu đồ.",
		addFilterTip: "Thêm Bộ lọc vào Dữ liệu này",
		dataSource: "Nguồn dữ liệu",
		noResults: "Không tìm thấy đối tượng nào.",
		chartTitle: "Tiêu đề Biểu đồ",
		description: "Mô tả",
		chartingMode: "Hiển thị Biểu đồ",
		featureOption: "Hiển thị giá trị đối tượng theo đối tượng",
		categoryOption: "Hiển thị các giá trị theo thể loại",
		countOption: "Hiển thị số lượng đối tượng theo thể loại",
		fieldOption: "Hiển thị giá trị thuộc tính dưới dạng biểu đồ",
		category: "Thể loại",
		axisLabel: "Nhãn Thể loại",
		categoryField: "Trường Thể loại",
		operation: "Hoạt động",
		originalOption: "Sử dụng các giá trị gốc",
		sumOption: "Tổng",
		averageOption: "Trung bình",
		minOption: "Tối thiểu",
		maxOption: "Tối đa",
		valueFields: "Trường Giá trị",
		moveUp: "Di chuyển lên trên",
		moveDown: "Di chuyển xuống dưới",
		sortOrder: "Sắp xếp Thứ tự Biểu đồ thông qua Nhãn Thể loại",
		ascending: "Tăng dần",
		descending: "Giảm dần",
		chartType: "Loại Biểu đồ",
		column: "Biểu đồ cột dọc",
		bar: "Biểu đồ thanh ngang",
		line: "Biểu đồ dạng đường",
		pie: "Biểu đồ hình tròn",
		chartColor: "Màu sắc Biểu đồ",
		showDataLabels: "Hiển thị Nhãn Dữ liệu",
		setSymbol: "Ký hiệu Lựa chọn",
		setHighLightColor: "Màu sắc Nổi Bật",
		settings: "Thiết lập",
		mapInterationOptions: "Tùy chọn tương tác bản đồ",
		preview: "Xem trước",
		ok: "OK",
		cancel: "Hủy",
		close: "Đóng",
		setFilterTip: "Vui lòng thiết lập bộ lọc chính xác. ",
		setChartTitleTip: "Vui lòng thiết lập tiêu đề biểu đồ.",
		setChartTypeTip: "Vui lòng chọn ít nhất một loại biểu đồ.",
		setDataFieldTip: "Vui lòng chọn ít nhất một trường giá trị.",
		setOutputFieldTip: "Vui lòng thiết lập các trường đầu ra.",
		count: "Số lượng",
		label: "Nhãn",
		horizontalAxis: "Trục ngang",
		verticalAxis: "Trục dọc",
		dataLabels: "Nhãn Dữ liệu",
		color: "Màu sắc",
		colorful: "Nhiều màu sắc",
		monochromatic: "Đơn sắc"
  })
);