define(
	 ({
		chartTasks: "Tác vụ Biểu đồ",
		addNew: "Thêm Mới",
		addNewTip: "Thêm Tác vụ Biểu đồ mới",
		name: "Tên",
		set: "Thiết lập",
		setDataSource: "Thiết lập Nguồn Dữ liệu",
		generalSettingsTip: "Thiết lập nguồn dữ liệu, tiêu đề và mô tả cho biểu đồ.",
		chartModeSettingTip: "Chọn phương pháp để phân tích và hiển thị dữ liệu dưới dạng biểu đồ.",
		detailsSettingTip: "Thiết lập giao diện biểu đồ bằng cách chỉ định loại biểu đồ, màu sắc và giá trị sẽ được lập biểu đồ:",
		symbolSettingTip: "Thiết lập hiển thị bản đồ cho dữ liệu đã được lập biểu đồ.",
		addFilterTip: "Thêm Bộ lọc vào Dữ liệu này",
		dataSource: "Nguồn dữ liệu",
		noResults: "Không tìm thấy đối tượng nào.",
		chartTitle: "Tiêu đề Biểu đồ",
		description: "Mô tả",
		chartingMode: "Hiển thị Biểu đồ",
		featureOption: "Hiển thị giá trị đối tượng theo đối tượng",
		categoryOption: "Hiển thị các giá trị theo thể loại",
		countOption: "Hiển thị số lượng đối tượng theo thể loại",
		fieldOption: "Hiển thị giá trị thuộc tính dưới dạng biểu đồ",
		category: "Thể loại",
		axisLabel: "Nhãn Thể loại",
		categoryField: "Trường Thể loại",
		operation: "Hoạt động",
		originalOption: "Sử dụng các giá trị gốc",
		sumOption: "Tổng",
		averageOption: "Trung bình",
		minOption: "Tối thiểu",
		maxOption: "Tối đa",
		valueFields: "Trường Giá trị",
		moveUp: "Di chuyển lên trên",
		moveDown: "Di chuyển xuống dưới",
		sortOrder: "Sắp xếp Thứ tự Biểu đồ thông qua Nhãn Thể loại",
		ascending: "Tăng dần",
		descending: "Giảm dần",
		chartType: "Loại Biểu đồ",
		column: "Biểu đồ Cột",
		bar: "Biểu đồ Thanh",
		line: "Biểu đồ dạng Đường",
		pie: "Biểu đồ Hình tròn",
		chartColor: "Màu sắc Biểu đồ",
		showDataLabels: "Hiển thị Nhãn Dữ liệu",
		setSymbol: "Ký hiệu Lựa chọn",
		setHighLightColor: "Màu sắc Nổi Bật",
		settings: "Thiết lập",
		mapInterationOptions: "Tùy chọn Tương tác Bản đồ",
		preview: "Xem trước",
		ok: "OK",
		cancel: "Hủy",
		close: "Đóng",
		setFilterTip: "Vui lòng thiết lập bộ lọc chính xác. ",
		setChartTitleTip: "Vui lòng thiết lập tiêu đề biểu đồ.",
		setChartTypeTip: "Vui lòng chọn ít nhất một loại biểu đồ.",
		setDataFieldTip: "Vui lòng chọn ít nhất một trường giá trị.",
		setOutputFieldTip: "Vui lòng thiết lập các trường đầu ra.",
		count: "Số lượng",
		label: "Nhãn",
		horizontalAxis: "Trục ngang",
		verticalAxis: "Trục dọc",
		dataLabels: "Nhãn Dữ liệu",
		color: "Màu sắc",
		colorful: "Nhiều màu sắc",
		monochromatic: "Đơn sắc",
    noTaskTip: "Bấm vào Thêm Mới để thêm tác vụ biểu đồ",
    info: "Thông tin",
    charts: "Biểu đồ",
    options: "Tùy chọn",
    taskName: "Tên tác vụ",
    summary: "Tóm tắt",
    resultDescription: "Mô tả Kết quả",
    spatialFilterTip: "Chọn (các) bộ lọc không gian được sử dụng trong tiện ích để giới hạn kết quả.",
    defaultOption: "Mặc định",
    useCurrentExtentTip: "Từng phần hoặc toàn bộ trong kích thước bản đồ hiện tại",
    useDrawGraphicTip: "Từng phần hoặc toàn bộ trong hình dạng đã được vẽ trên bản đồ",
    useFeaturesTip: "Dựa trên vị trí của chúng liên quan đến các đối tượng trong lớp khác",
    noSpatialLimitTip: "Không giới hạn các kết quả theo không gian",
    drawingTools: "Công cụ vẽ",
    bufferSettings: "Cài đặt Vùng đệm",
    defaultDistance: "Khoảng cách Mặc định",
    bufferDistance: "Khoảng cách Đệm",
    defaultUnit: "Đơn vị Mặc định",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Feet",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    availableSpatialRelationships: "Mối quan hệ Không gian Hiện có",
    setSpatialRelationships: "Thiết lập Mối quan hệ Không gian",
    availability: "Mức độ khả dụng",
    relationship: "Mối quan hệ",
    actions: "Các hành động",
    intersect: "giao cắt",
    contain: "bao gồm",
    areContainedIn: "được bao gồm trong",
    cross: "gạch ngang",
    envelopeIntersect: "đường bao giao cắt",
    overlap: "xếp chồng",
    areOverlapped: "bị xếp chồng",
    touche: "tiếp xúc",
    within: "bên trong",
    areWithin: "ở bên trong",
    indexIntersect: "chỉ số giao cắt"
  })
);