define(
   ({
    _widgetLabel: "Diagramma",
    executeChartTip: "Noklikšķiniet uz vienas no šīm uzdevumu vienībām, lai izpildītu diagrammu.",
    invalidConfig: "Nederīga konfigurācija.",
    noneChartTip: "Šim logrīkam nav konfigurēts neviens diagrammas uzdevums.",
    chartParams: "Opcijas",
    charts: "DIAGRAMMAS",
    apply: "LIETOT",
    useSpatialFilter: "Izmantot telpisko filtru, lai ierobežotu elementus",
    useCurrentMapExtent: "Tikai elementi, kas krustojas ar pašreizējās kartes pārklājumu",
    drawGraphicOnMap: "Tikai elementi, kas krustojas ar lietotāja definētu teritoriju",
    chartResults: "Diagrammas rezultāti",
    clearResults: "Notīrīt rezultātus",
    noPermissionsMsg: "Jums nav atļauju piekļūt šim pakalpojumam.",
    specifySpatialFilterMsg: "Norādiet šī uzdevuma telpisko filtru.",
    queryError: "Vaicājums neizdevās.",
    noResults: "Nav atrasts neviens elements.",
    category: "Kategorija",
    count: "Skaitīt",
    label: "Kartes teksts",
    horizontalAxis: "Horizontālā ass",
    verticalAxis: "Vertikālā ass",
    dataLabels: "Datu teksti",
    color: "Krāsa",
    colorful: "Krāsains",
    monochromatic: "Melnbalts",
    tasks: "Uzdevumi",
    results: "Rezultāti",
    applySpatialFilterToLimitResults: "Lietot telpisko filtru, lai ierobežotu rezultātus",
    useCurrentExtentTip: "Daļēji vai pilnībā pašreizējā kartes pārklājumā",
    useDrawGraphicTip: "Daļēji vai pilnībā uz kartes uzzīmētajā formā",
    useFeaturesTip: "Pēc to atrašanās vietās attiecībā pret elementiem citā slānī",
    noSpatialLimitTip: "Neierobežot rezultātus telpiski",
    applySearchDistance: "Lietot meklēšanas attālumu",
    spatialRelationship: "Telpiskās attiecības",
    relatedLayer: "Saistītais slānis",
    clear: "Notīrīt",
    bufferDistance: "Bufera distance",
    miles: "Jūdzes",
    kilometers: "Kilometri",
    feet: "Pēdas",
    meters: "Metri",
    yards: "Jardi",
    nauticalMiles: "Jūras jūdzes",
    back: "Atpakaļ",
    execute: "Izpildīt"
  })
);