define(
   ({
    selectAnalysisTools:"Valitse pienoisohjelmassa lueteltava analyysityökalu.",
    selected: "valittu",
    name: "Nimi",
    graphicalDisplay:"Graafinen näyttö",
    usage: "Käyttö",
    toolNotAvailable: "Tämä työkalu ei ole käytettävissä, koska kartta ei sisällä tarvittavia kohdekarttatasoja.",
    aggregatePoints:"Kokoa pisteet",
    aggregatePointsUsage:"Kokoa pisteet alueiksi, joissa pisteet sijaitsevat.",
    aggregatePointsInputTip: "Määritä pistekohdekarttataso, joka koostetaan alueiksi aluekohdekarttatasossa.",
    calculateDensity:"Laske tiheys",
    calculateDensityUsage:"Luo tiheyskartta piste- tai viivakohteista jakamalla tietyn ilmiön tunnetut määrät (esitetään pisteiden ja viivojen ominaisuustietoina) kartan alueelle.",
    calculateDensityInputTip:"Määritä piste- tai viivakohteet, joista tiheys lasketaan.",
    connectOriginsToDestinations: "Yhdistä lähtöpisteet määränpäihin",
    connectOriginsToDestinationsUsage: "Mittaa matkustusajan tai kahden pisteen välinen etäisyys.",
    connectOriginsToDestinationsInputTip: "Määritä luotavien reittien lähtöpiste tai -pisteet.",
    createBuffers:"Luo puskurit",
    createBuffersUsage:"Luo puskurialueet lähtöaineiston kohteista.",
    createBuffersInputTip:"Määritä puskuroitava piste-, viiva- tai aluekohdekarttataso.",
    createDriveTimeAreas:"Luo ajoaika-alueita",
    createDriveTimeAreasUsage:"Luo ajoaika-alueet (tai ajoetäisyysalueet) lähtöpisteiden ympärille annettujen ajoaika-arvojen perusteella.",
    createDriveTimeAreasInputTip:"Määritä pisteet, joihin ajoaika-alueet piirretään.",
    createViewshed:"Luo näkymäalue",
    createViewshedUsage:"Luo alueita, jotka näkyvät määrittämiesi sijaintien perusteella.",
    createViewshedInputTip:"Tunnista näkyvä alueet määrittämällä tarkkailusijainteja.",
    createWatersheds:"Luo valuma-alueet",
    createWatershedsUsage:"Luo valuma-alueet määrittämiesi sijaintien perusteella.",
    createWatershedsInputTip:"Määritä valuma-alueiden laskennassa käytettävät pistekohteet.",
    deriveNewLocations:"Laske uudet sijainnit",
    deriveNewLocationsUsage:"Johda uusia kohteita lähtöaineiston karttatasoista, jotka täyttävät määrittämäsi kyselyn",
    deriveNewLocationsInputTip:"Määritä lähtöaineistona käytettävä analyysitaso.",
    dissolveBoundaries:"Sulauta rajaukset",
    dissolveBoundariesUsage:"Sulauta alueet, jotka ovat päällekkäisiä tai joilla on yhteinen raja.",
    dissolveBoundariesInputTip:"Määritä karttataso, joka sisältää sulautettavat aluekohteet.",
    enrichLayer:"Rikasta karttataso",
    enrichLayerUsage:"Rikasta lähtöaineiston kohteita lähialueen ihmisten, paikkojen ja yritysten tiedoilla.",
    enrichLayerInputTip:"Määritä kohteet, joita rikastetaan uudella aineistolla.",
    extractData:"Pura aineisto",
    extractDataDesc:"Pura aineisto yhdestä tai useammasta karttatasosta annetun laajuuden rajoissa",
    extractDataInputTip:"Määritä purettava lähtöaineiston kohdekarttataso.",
    findExistingLocations:"Hae nykyiset sijainnit",
    findExistingLocationsUsage:"Valitse lähtöaineiston karttatason kohteet, jotka täyttävät määrittämäsi ominaisuustiedon ja/tai sijaintikyselyn.",
    findExistingLocationsInputTip:"Määritä lähtöaineistona käytettävät analyysitasot.",
    findHotSpots:"Hae kuumat pisteet",
    findHotSpotsUsage:"Etsi tilastollisesti merkitsevät lähtöaineiston kohteiden tai pienten ja suurten arvojen keskittymät.",
    findHotSpotsInputTip:"Määritä piste- tai aluekohdekarttataso, jonka HotSpot-pisteet lasketaan.",
    findNearest:"Hae lähin",
    findNearestUsage:"Etsi kullekin lähtöaineiston karttatason kohteelle sen lähdin kohde toisessa karttatasossa",
    findNearestInputTip:"Määritä piste-, viiva- tai aluekohteet, joista lähimmät sijainnit löytyvät.",
    findSimilarLocations:"Etsi samankaltaisia sijainteja",
    findSimilarLocationsUsage:"Vertaa ehdokassijaintien samankaltaisuutta vähintään yhteen viitesijaintiin.",
    findSimilarLocationsInputTip:"Määritä kohdekarttataso, joka sisältää vähintään yhden viitesijainnin, johon hakukarttatason kohteiden samankaltaisuutta verrataan.",
    interpolatePoints:"Interpoloi pisteet",
    interpolatePointsUsage:"Ennusta uusien sijaintien arvot kerätyistä pisteistä löytyvien mittausten perusteella.",
    interpolatePointsInputTip:"Määritä interpoloitavat pistekohteet.",
    mergeLayers:"Yhdistä karttatasot",
    mergeLayersUsage:"Yhdistä usean karttatason kohteet uuteen karttatasoon",
    mergeLayersInputTip:"Määritä yhdistettävään karttatasoon yhdistettävä kohdekarttataso.",
    overlayLayers:"Kerrostasot",
    overlayLayersUsage:"Yhdistä useita karttatasoja yhdeksi karttatasoksi, jossa alkuperäisten karttatasojen tiedot on säilytetty.",
    overlayLayersInputTip:"Määritä päällekkäisen karttatason päälle liitettävä kohdekarttataso.",
    planRoutes:"Suunnittele reitit",
    planRoutesUsage:"Määritä, miten voit jakaa tehtäviä tehokkaasti liikkuvalle työvoimalle.",
    planRoutesInputTip:"Määritä pisteet, joiden kautta kulkuneuvojen, kuljettajien tai reittien on kuljettava.",
    summarizeNearby:"Yhteenveto, lähistö",
    summarizeNearbyUsage:"Laadi aineiston yhteenveto kustakin lähtöaineiston karttatason kohteesta, joka on tietyllä etäisyydellä toisen karttatason kohteista",
    summarizeNearbyInputTip:"Määritä piste-, viiva- tai aluekohdekarttataso, josta etäisyydet mitataan yhteenvetokarttatason kohteisiin.",
    summarizeWithin:"Yhteenveto alueella",
    summarizeWithinUsage:"Laadi aineiston yhteenveto kustakin lähtöaineiston aluekarttatason alueesta, joka sijaitsee alueen rajoissa toisen karttatason kohteista.",
    summarizeWithinInputTip:"Määritä aluekohdekarttataso. josta yhteenveto luodaan.",
    traceDownstream:"Jäljitä alavirtaan",
    traceDownstreamUsage:"Määrittää virtojen polut alavirran suunnassa määrittämistäsi sijainneista.",
    traceDownstreamInputTip:"Määritä pistekohteet, joita käytetään alavirran jäljityksen aloitussijaintina."
  })
);
