define(
   ({
    selectAnalysisTools:"Valitse pienoisohjelmassa käytettävät analyysityökalut.",
    selected: "valittu",
    name: "Nimi",
    graphicalDisplay:"Graafinen näyttö",
    usage: "Käyttö",
    settings: "Settings",
    toolSetting: "Määritä työkalun tiedot",
    toolLabel: "Työkalun näyttönimi",
    showHelpTip: "Näytä ohjelinkit pienoisohjelmassa",
    showCurrentMapExtent: "Näytä vaihtoehto nykyisen karttalaajuuden käyttöä varten",
    showCredits: "Näytä <b>Näytä krediitit</b> -vaihtoehto",
    saveAsFeatureService: "Tallenna tulos käyttäjän tiliin",
    showReadyToUseLayers: "Näytä ArcGIS Onlinen maailmankartaston käyttövalmiit karttatasot",
    toolNotAvailable: "Tämä työkalu ei ole käytettävissä, koska kartta ei sisällä tarvittavia kohdekarttatasoja.",
    aggregatePoints:"Kokoa pisteet",
    aggregatePointsUsage:"Kokoa pisteet alueiksi, joissa pisteet sijaitsevat.",
    calculateDensity:"Laske tiheys",
    calculateDensityUsage:"Luo tiheyskartta piste- tai viivakohteista jakamalla tietyn ilmiön tunnetut määrät (esitetään pisteiden ja viivojen ominaisuustietoina) kartan alueelle.",
    connectOriginsToDestinations: "Yhdistä lähtöpisteet määränpäihin",
    connectOriginsToDestinationsUsage: "Mittaa matkustusajan tai kahden pisteen välinen etäisyys.",
    createBuffers:"Luo puskurit",
    createBuffersUsage:"Luo puskurialueet lähtöaineiston kohteista.",
    createDriveTimeAreas:"Luo ajoaika-alueita",
    createDriveTimeAreasUsage:"Luo ajoaika-alueet (tai ajoetäisyysalueet) lähtöpisteiden ympärille annettujen ajoaika-arvojen perusteella.",
    createViewshed:"Luo näkymäalue",
    createViewshedUsage:"Luo alueita, jotka näkyvät määrittämiesi sijaintien perusteella.",
    createWatersheds:"Luo valuma-alueet",
    createWatershedsUsage:"Luo valuma-alueet määrittämiesi sijaintien perusteella.",
    deriveNewLocations:"Laske uudet sijainnit",
    deriveNewLocationsUsage:"Johda uusia kohteita lähtöaineiston karttatasoista, jotka täyttävät määrittämäsi kyselyn",
    dissolveBoundaries:"Sulauta rajaukset",
    dissolveBoundariesUsage:"Sulauta alueet, jotka ovat päällekkäisiä tai joilla on yhteinen raja.",
    enrichLayer:"Rikasta karttataso",
    enrichLayerUsage:"Rikasta lähtöaineiston kohteita lähialueen ihmisten, paikkojen ja yritysten tiedoilla.",
    extractData:"Pura aineisto",
    extractDataDesc:"Pura aineisto yhdestä tai useammasta karttatasosta annetun laajuuden rajoissa",
    findExistingLocations:"Hae nykyiset sijainnit",
    findExistingLocationsUsage:"Valitse lähtöaineiston karttatason kohteet, jotka täyttävät määrittämäsi ominaisuustiedon ja/tai sijaintikyselyn.",
    findHotSpots:"Hae kuumat pisteet",
    findHotSpotsUsage:"Etsi tilastollisesti merkitsevät lähtöaineiston kohteiden tai pienten ja suurten arvojen keskittymät.",
    findNearest:"Hae lähin",
    findNearestUsage:"Etsi kullekin lähtöaineiston karttatason kohteelle sen lähdin kohde toisessa karttatasossa",
    findSimilarLocations:"Etsi samankaltaisia sijainteja",
    findSimilarLocationsUsage:"Vertaa ehdokassijaintien samankaltaisuutta vähintään yhteen viitesijaintiin.",
    interpolatePoints:"Interpoloi pisteet",
    interpolatePointsUsage:"Ennusta uusien sijaintien arvot kerätyistä pisteistä löytyvien mittausten perusteella.",
    mergeLayers:"Yhdistä karttatasot",
    mergeLayersUsage:"Yhdistä usean karttatason kohteet uuteen karttatasoon",
    overlayLayers:"Kerrostasot",
    overlayLayersUsage:"Yhdistä useita karttatasoja yhdeksi karttatasoksi, jossa alkuperäisten karttatasojen tiedot on säilytetty.",
    planRoutes:"Suunnittele reitit",
    planRoutesUsage:"Määritä, miten voit jakaa tehtäviä tehokkaasti liikkuvalle työvoimalle.",
    summarizeNearby:"Yhteenveto, lähistö",
    summarizeNearbyUsage:"Laadi aineiston yhteenveto kustakin lähtöaineiston karttatason kohteesta, joka on tietyllä etäisyydellä toisen karttatason kohteista",
    summarizeWithin:"Yhteenveto alueella",
    summarizeWithinUsage:"Laadi aineiston yhteenveto kustakin lähtöaineiston aluekarttatason alueesta, joka sijaitsee alueen rajoissa toisen karttatason kohteista.",
    traceDownstream:"Jäljitä alavirtaan",
    traceDownstreamUsage:"Määrittää virtojen polut alavirran suunnassa määrittämistäsi sijainneista."
  })
);
