define(
   ({
    "tabs_section_Label": "Faner",
    "addTab": "Tilføj fane",
    "layerName": "Lag",
    "layerType": "Analysetype",
    "layerLabel": "Label",
    "actions": "Handlinger",
    "closest": "Nærmeste objekt",
    "proximity": "Nærhed",
    "summary": "Summary",
    "select_lbl": "-- Vælg --",
    "general_setting_Label": "Generelle indstillinger",
    "units_text_lbl": "Afstandsenheder",
    "miles": "Miles",
    "kilometers": "Kilometer",
    "feet": "Fod",
    "meters": "Meter",
    "yards": "Yards",
    "nauticalMiles": "Sømil",
    "maximum_distance_lbl": "Maksimal afstand til nærmeste objekt",
    "buffer_text_lbl": "Buffermærkat",
    "buffer_lbl": "Bufferafstand",
    "buffer_max_lbl": "Maksimal bufferafstand",
    "buffer_min_lbl": "Minimal bufferafstand",
    "routing_checkBox": "Aktivér ruteangivelser",
    "weather_Label": "Vejrindstillinger",
    "weather_checkBox": "Inkludér vejroplysninger",
    "selectLayers": "Vælg vejrlag",
    "currentlySelectedLayer": "Aktuelt valgte vejrlag",
    "missingTabLabel": "Mindst én fane mangler sin mærkat",
    "cancel": "Annuller",
    "ok": "Ok",
    "missingLayerInWebMap": "Ingen operationelle lag fundet.",
    "selectFields": "Vælg felter",
    "addField": "Tilføj felt",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAKS",
    "avg": "GNM.SN",
    "count": "OPTÆLLING",
    "area": "AREA",
    "length": "LÆNGDE",
    "count_checkBox": "Vis antal",
    "area_checkBox": "Vis område",
    "length_checkBox": "Vis længde",
    "max_records": "Maksimumgrænse nået"
  })
);
