define(
   ({
    _widgetLabel: "Situation Awareness(베타)",
    locate_incident: "사건 찾기",
    clear_incidents: "사건 지우기",
    reverse_geocoded_address: "가장 가까운 주소",
    reverse_geocoded_error: "사용할 수 없음",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    now: "지금",
    wind: "풍력",
    SUN: "일",
    MON: "월",
    TUE: "화",
    WED: "수",
    THU: "목",
    FRI: "금",
    SAT: "토",
    defaultTabMsg: "식별된 사건이 없습니다.",
    actionLabel: "사건으로 설정",
    drawPoint: "포인트 그리기",
    drawLine: "라인 그리기",
    drawPolygon: "폴리곤 그리기",
    saveIncident: "Incident 저장",
    clearIncident: "Incident 지우기",
    useMapExtent: "현재 맵 범위 사용",
    noFeaturesFound: "피처를 찾을 수 없습니다.",
    downloadCSV: "CSV 다운로드",
    editComplete: "피처를 저장했습니다.",
    updateComplete: "피처를 업데이트했습니다.",
    deleteComplete: "피처를 삭제했습니다.",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH",
    notPolySave: "저장하려면 먼저 버퍼 거리를 지정하세요.",
    update_btn: "업데이트",
    delete_btn: "삭제"
  })
);
