define(
   ({
    _widgetLabel: "Geoprocesare",
    execute: "Executare",
    help: "Ajutor",
    input: "Introducere",
    output: "Ieşire",
    executing: "În curs de execuţie",
    requiredInfo: "este obligatoriu.",
    drawnOnMap: "Rezultatul este figurat pe hartă.",
    clear: "Golire",
    error: "Eroare",
    noToolConfig: "Nu este disponibilă nicio operaţie de geoprocesare preconfigurată.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Încărcare fişier",
    selectFileToUpload: 'Selectare fişier...',
    upload: 'Încărcare',
    rasterFormat: 'Format date raster',
    noFileSelected: 'Niciun fişier selectat!',
    uploadSuccess:'Încărcare fişier reuşită!',
    url: "URL",
    showLayerContent: "Afişare conţinut strat tematic",
    invalidUrl: "URL serviciu de obiecte spaţiale nevalid",
    Feet: "Ft",
    Yards: "Iarzi",
    Miles: "Mile",
    NauticalMiles: "Mile marine",
    Meter: "Metri",
    Kilometers: "Kilometri",
    urlPlaceholder: "URL set de obiecte spaţiale"
  })
);
