define(
   ({
    "tabs_section_Label": "Закладки",
    "addTab": "Добавить вкладку",
    "layerName": "Слой (Layer)",
    "layerType": "Тип анализа",
    "layerLabel": "Подпись",
    "actions": "Действия",
    "closest": "Ближайший объект",
    "proximity": "Близость",
    "summary": "Итоговая информация",
    "select_lbl": "-- Выбрать --",
    "general_setting_Label": "Общие параметры",
    "units_text_lbl": "Единицы расстояния",
    "miles": "Миль",
    "kilometers": "километры",
    "feet": "Футы (Feet)",
    "meters": "Метры (Meters)",
    "yards": "Ярды (Yards)",
    "nauticalMiles": "Морские мили (Nautical Miles)",
    "maximum_distance_lbl": "Максимальное расстояние до ближайшего объекта",
    "buffer_text_lbl": "Буфер надписей",
    "buffer_lbl": "Буферное расстояние",
    "buffer_max_lbl": "Максимальное буферное расстояние",
    "buffer_min_lbl": "Минимальное буферное расстояние",
    "routing_checkBox": "Включить маршрутизацию",
    "weather_Label": "Опции погоды",
    "weather_checkBox": "Включить информацию о погоде",
    "selectLayers": "Выбрать слои погоды",
    "currentlySelectedLayer": "Выбранные слои погоды",
    "missingTabLabel": "В надписи не хватает одной вкладки",
    "cancel": "Отменить",
    "ok": "Ok",
    "missingLayerInWebMap": "Не найдено рабочих слоев.",
    "selectFields": "Выбрать поля",
    "addField": "Добавить поле",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Показать количество",
    "area_checkBox": "Показать площадь",
    "length_checkBox": "Показать длину",
    "max_records": "Достигнуто максимальное ограничение"
  })
);
