define({
  root: ({
    usemapextent: "Share current map extent by default",
    bitylogin: "Bitly user name",
    bitlyapikey: "Bitly API Key",
    linktitle: "Link Title",
    linkimage: "Link Image",
    linksummary: "Link Summary",
    hashtags: "Link Hashtags",
    usedforfasebook: "Used for facebook share",
    usedfortwitter: "Used for twitter share",
    titletip: "If not specified then the webpage title will be used"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
