define(
   ({
    _widgetLabel: "Pārskata elements",
    select: "Izvēlēties",
    draw: "Zīmēt",
    chooseALayer: "Atlasiet slāni",
    clickAFeature: "Kartē noklikšķiniet uz elementa, lai to atlasītu.",
    loadingFeatures: "Iegūst atlasītā elementa datus...",
    errorTitle: "Kļūda",
    errorIdentify: "Elementu identificēšanas kļūda. Lūdzu, skatiet detalizētu informāciju konsoles žurnālā.",
    infoWindowTitle: "Detaļas",
    layerLabel: "Slāņa nosaukums",
    reviewStatusLabel: "Pārskata statuss",
    selectReviewStatusAdd: "Pievienot elementu",
    selectReviewStatusDelete: "Izdzēst elementu",
    selectReviewStatusMove: "Pārvietot elementu",
    selectReviewStatusReshape: "Pārveidot elementa formu",
    drawReviewStatusMissing: "Trūkst elementa(-u)",
    drawReviewStatusPosition: "Pozīciju kļūda",
    drawReviewStatusShape: "Formas kļūda",
    drawReviewStatusAttribute: "Atribūta kļūda",
    notesLabel: "Piezīmes",
    severityLabel: "Svarīgums",
    reportedByLabel: "Ziņoja",
    reportedByDefault: "anonīms lietotājs",
    reportButton: "Pārskats",
    reportMessage: "Saņemts pārskats",
    errorReportMessage: "Ziņojot par elementu, radās kļūda.",
    drawErrorInstructions: "Atlasiet punktu, līniju vai daudzstūri un uzzīmējiet kļūdas ģeometriju kartē:",
    errorMapService: "Iegūstot kartes pakalpojuma informāciju, radās kļūda",
    noFeatureSelected : "Atrašanās vietā, uz kuras noklikšķinājāt, nav atrasts neviens elements",
    selectFeatureMapPoint: "Noklikšķiniet, lai atlasītu elementu",
    drawFeatureMapPoint: "Noklikšķiniet, lai pievienotu punktu",
    popupMessage:"Ziņojums",
    popupError:"Kļūda",
    manyFeaturesSelected: "Atrasts vairāk nekā viens elements. Lūdzu, tuviniet un atlasiet elementu, par ko ziņot."
  })
);
