define(
   ({
    _widgetLabel: "Tisk",
    title: "Název mapy",
    format: "Formát",
    layout: "Rozvržení",
    settings: "Pokročilé",
    mapScaleExtent: "Měřítko/rozsah mapy",
    preserve: "Zachovat",
    mapScale: "měřítko mapy",
    mapExtent: "rozsah mapy",
    forceScale: "Vynutit měřítko",
    getCurrentScale: "aktuální",
    mapMetadata: "Metadata rozvržení",
    author: "Autor",
    copyright: "Autorská práva",
    fullLayoutOptions: "Všechny možnosti rozvržení",
    scaleBarUnitsMetric: "Grafické měřítko v metrických jednotkách",
    scaleBarUnitsNonMetric: "Grafické měřítko v nemetrických jednotkách",
    unitsMiles: "Míle",
    unitsKilometers: "Kilometry",
    unitsMeters: "Metry",
    unitsFeet: "Stopy",
    unitsYards: "Yardy",
    unitsNauticalMiles: "Námořní míle",
    lncludeLegend: "Přidat legendu",
    printQualityOptions: "Kvalita tisku",
    dpi: "DPI",
    mapOnlyOptions: "velikost MAP_ONLY",
    width: "Šířka (px)",
    height: "Výška (px)",
    print: "Tisk",
    clearList: "Vymazat výtisky",
    creatingPrint: "Vytváření výtisku",
    printError: "Chyba, zkuste to znovu."
  })
);