define(
   ({
    _widgetLabel: "Phân tích Sự cố",
    incident: "Sự cố",
    weather: "Thời tiết",
    locate_incident: "Định vị Sự cố",
    clear_incidents: "Xóa Sự cố",
    reverse_geocoded_address: "Địa chỉ gần nhất",
    reverse_geocoded_error: "Không khả dụng",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Bộ",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    now: "BÂY GIỜ",
    wind: "GIÓ",
    SUN: "CN",
    MON: "T2",
    TUE: "T3",
    WED: "T4",
    THU: "T5",
    FRI: "T6",
    SAT: "T7",
    defaultTabMsg: "Không có sự cố được xác định.",
    actionLabel: "Thiết lập Là Sự cố",
    useMapExtent: "Sử dụng phạm vi bản đồ hiện tại",
    noFeaturesFound: "Không tìm thấy đối tượng.",
    downloadCSV: "TẢI XUỐNG CSV",
    sum: "TỔNG",
    min: "TỐI THIỂU",
    max: "Tối đa",
    avg: "TRUNG BÌNH",
    count: "SỐ LƯỢNG",
    area: "DIỆN TÍCH",
    length: "ĐỘ DÀI"
  })
);
