define({
  root: ({
    _widgetLabel: "Geoprocessing",
    execute: "Execute",
    help: "Help",
    input: "Input",
    output: "Output",
    executing: "Executing",
    requiredInfo: "is required.",
    drawnOnMap: "The result is drawn on the map.",
    clear: "Clear",
    error: "Error",
    noToolConfig: "No preconfigured geoprocessing task available.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Upload file",
    selectFileToUpload: 'Select file...',
    upload: 'Upload',
    rasterFormat: 'Raster data format',
    noFileSelected: 'No file selected!',
    uploadSuccess:'File upload success!',
    url: "URL",
    showLayerContent: "Show layer content",
    invalidUrl: "Invalid feature service url",
    Feet: "Feet",
    Yards: "Yards",
    Miles: "Miles",
    NauticalMiles: "Nautical Miles",
    Meter: "Meters",
    Kilometers: "Kilometers",
    urlPlaceholder: "feature set URL"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
