define(
   ({
    _widgetLabel: "Контроль за ситуацией (бета)",
    locate_incident: "Найти инцидент",
    clear_incidents: "Очистить инциденты",
    reverse_geocoded_address: "Ближайший адрес",
    reverse_geocoded_error: "Не доступно",
    miles: "Мили",
    kilometers: "Километры",
    feet: "Футы",
    meters: "Метры",
    yards: "Ярды",
    nauticalMiles: "Морские мили",
    now: "Сейчас",
    wind: "WIND",
    SUN: "ВС",
    MON: "ПН",
    TUE: "ВТ",
    WED: "СР",
    THU: "ЧТ",
    FRI: "ПТ",
    SAT: "СБ",
    defaultTabMsg: "Нет идентифицированных инцидентов.",
    actionLabel: "Установить как инцидент",
    drawPoint: "Нарисовать точку",
    drawLine: "Нарисовать линию",
    drawPolygon: "Нарисовать полигон",
    saveIncident: "Сохранить инцидент",
    clearIncident: "Очистить инцидент",
    useMapExtent: "Использовать текущий экстент карты",
    noFeaturesFound: "Объекты не найдены.",
    downloadCSV: "ЗАГРУЗИТЬ CSV",
    editComplete: "Объект сохранен успешно!",
    updateComplete: "Объект обновлен успешно!",
    deleteComplete: "Объекты успешно удален!",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH",
    notPolySave: "Перед сохранением необходимо указать буферное расстояние.",
    update_btn: "Обновить",
    delete_btn: "Удалить"
  })
);
