define(
   ({
    _widgetLabel: "Užklausos",
    executeQueryTip: "Norėdami vykdyti užklausą, paspauskite vieną iš šių užduoties elementų.",
    invalidConfig: "Neleistina konfigūracija. Užklausos nustatymo puslapyje nustatykite tinkamą konfigūraciją.",
    queryParams: "Parinktys",
    parameters: "PARINKTYS",
    queries: "UŽKLAUSOS",
    apply: "TAIKYTI",
    queryResults: "Rezultatai",
    clear: "Valyti",
    noResults: "Elementų nerasta.",
    queryError: "Užklausos įvykdyti nepavyko!",
    numberFound: "Rastų elementų skaičius",
    mapExtentTip: "Apribokite rezultatus iki esamo žemėlapio ploto.",
    noValue: "Reikšmių nėra",
    and: "ir",
    stringOperatorIs: "yra", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "nėra",
    stringOperatorStartsWith: "prasideda su",
    stringOperatorEndsWith: "baigiasi su",
    stringOperatorContains: "įraše yra",
    stringOperatorDoesNotContain: "įraše nėra",
    stringOperatorIsBlank: "yra tuščias",
    stringOperatorIsNotBlank: "nėra tuščias",
    dateOperatorIsOn: "yra ant", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "yra ne ant",
    dateOperatorIsBefore: "yra prieš",
    dateOperatorIsAfter: "yra po",
    dateOperatorDays: "dienos",
    dateOperatorWeeks: "savaitės", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "mėnesiai",
    dateOperatorInTheLast: "yra paskutinis",
    dateOperatorNotInTheLast: "nėra paskutinis",
    dateOperatorIsBetween: "yra tarp",
    dateOperatorIsNotBetween: "nėra tarp",
    dateOperatorIsBlank: "yra tuščias",
    dateOperatorIsNotBlank: "nėra tuščias",
    numberOperatorIs: "yra", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "nėra",
    numberOperatorIsAtLeast: "yra mažiausia (bent)",
    numberOperatorIsLessThan: "yra mažiau nei",
    numberOperatorIsAtMost: "yra daugiausia",
    numberOperatorIsGreaterThan: "yra daugiau nei",
    numberOperatorIsBetween: "yra tarp",
    numberOperatorIsNotBetween: "nėra tarp",
    numberOperatorIsBlank: "yra tuščias",
    numberOperatorIsNotBlank: "nėra tuščias",
    operationalLayerTip: "Pridėti rezultatus kaip darbinį sluoksnį",
    queryResult: "Užklausos rezultatas",
    specifyParamsTip: "Nurodyti užduoties parametrus",
    useSpatialFilter: "Naudoti erdvinį filtrą elementų apribojimui",
    useCurrentMapExtent: "Tik elementai, besikertantys su esamu žemėlapio plotu",
    drawGraphicOnMap: "Tik elementai, besikertantys su vartotojo apibrėžtu plotu",
    specifySpatialFilterMsg: "Nurodykite šios užduoties erdvinį filtrą.",
    clearResults: "Išvalyti rezultatus",
    operationalTip: 'Pažymėjus šią parinktį, rezultatai bus saugomi žemėlapyje, kol paspausite mygtuką „${clearResults}“.',
    noneQueryTip: "Šiam valdikliui nesukonfigūruota nė viena užklausos užduotis.",
    noPermissionsMsg: "Neturite teisės pasiekti šią paslaugą.",
    attributesFromRelationship: "Atributai iš susijusios lentelės",
    tasks: "Užduotys",
    applySpatialFilterToLimitResults: "Taikyti erdvinį filtrą, kad būtų apriboti rezultatai",
    useCurrentExtentTip: "Iš dalies ar visiškai esamo žemėlapio aprėptyje",
    useDrawGraphicTip: "Iš dalies arba visiškai žemėlapyje nubrėžtoje figūroje",
    useFeaturesTip: "Remiantis jų vietomis kito sluoksnio elementų atžvilgiu",
    noSpatialLimitTip: "Erdviškai neapriboti rezultatų",
    applySearchDistance: "Taikyti paieškos nuotolį",
    spatialRelationship: "Erdviniai ryšiai",
    relatedLayer: "Susijęs sluoksnis",
    bufferDistance: "Buferio atstumas",
    miles: "Mylios",
    kilometers: "Kilometrai",
    feet: "Pėdos",
    meters: "Metrai",
    yards: "Jardai",
    nauticalMiles: "Jūrmylės",
    back: "Atgal",
    execute: "Vykdyti"
  })
);