define(
   ({
    taskUrl: "Užduoties URL",
    serviceURLPlaceholder: "Įveskite geoduomenų apdorojimo užduoties URL",
    ok: "Gerai",
    cancel: "Atšaukti",
    layer: "Sluoksnis",
    action: "Veiksmas",
    input: "Įvestis",
    output: "Išvestis",
    name: "Pavadinimas",
    type: "Tipas",
    required: "Privalomas",
    layerOrder: "Sluoksnių tvarka",
    options: "Parinktys",
    defaultValue: "Numatytoji reikšmė",
    inputFeatureBy: "Įvesti elementą pagal",
    renderer: "Vaizdavimas",
    displayType: "Rodymo būdas",
    label: "Žymė",
    tooltip: "Įrankio užuomina",
    visible: "Matoma",
    helpUrl: "Pagalbos URL",
    useResultMapService: "Naudoti gautos žemėlapių paslaugos piešimo parinktis",
    drawOnMap: "Interaktyvus piešimas žemėlapyje",
    selectLayer: "Sluoksnio iš žemėlapio pasirinkimas",
    url: "URL",
    symbol: "Simbolis",
    shareResults: "Pridėti rezultatus kaip darbinį sluoksnį",
    popup: "Iškylantis langas",
    setTask: "Nustatyti",
    setTaskTitle: "Nustatyti GP užduotį",
    enablePopup: "Įgalinti informacinį langą",
    unSupportGeometryType: "Negalima nustatyti vaizdavimo dėl nežinomo geometrijos tipo.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Įkelti failą",
    selectFileToUpload: "Pasirinkite failą...",
    upload: "Nusiųsti",
    rasterFormat: "Rastrinių duomenų formatas",
    noFileSelected: "Nepasirinktas joks failas!",
    uploadSuccess:"Failas įkeltas sėkmingai!",
    showLayerContent: "Rodyti sluoksnio turinį",
    Feet: "Pėdos",
    Yards: "Jardai",
    Miles: "Mylios",
    NauticalMiles: "Jūrmylės",
    Meter: "Metrai",
    Kilometers: "Kilometrai",
    urlPlaceholder: "elementui nustatytas URL",
    allowToExport: "Leisti eksportuoti rezultatus"
  })
);
