define(
   ({
    routeUrl: "เส้นทาง URL",
    locatorUrl: "Geocoder URL",
    geocoderOptions: "ตัวเลือก Geocoder",
    autoComplete: "Autocomplete",
    maxLocations: "สถานที่สูงสุด",
    minCharacters: "ตัวอักษรขั้นต่ำ",
    searchDelay: "ค้นหาล่าช้า",
    placeholder: "ตัวยึด",
    routeOptions: "ตัวเลือกเส้นทาง",
    directionsLanguage: "ทิศทางภาษา",
    directionsLengthUnits: "ทิศทางหน่วยความยาว",
    directionsOutputType: "ทิศทางประเภทผลลัพธ์",
    impedanceAttribute: "การต้านทานข้อมูล",
    kilometers: "กิโลเมตร",
    miles: "ไมล์",
    meters: "เมตร",
    feet: "ฟุต",
    yards: "หลา",
    nauticalMiles: "ไมล์ทะเล",
    parametersTip: "กรุณากำหนดพารามิเตอร์ให้ถูกต้อง",
    complete: "สมบูรณ์",
    completeNoEvents: "สมบูรณ์โดยไม่มีเหตุการณ์ใดใด",
    instructionsOnly: "คำแนะนำเท่านั้น",
    standard: "มาตรฐาน",
    summaryOnly: "สรุปเท่านั้น",
    travelModesUrl: "URL ของรูปแบบการเดินทาง",
    searchPlaceholder: "ค้นหาที่อยู่หรือสถานที่",
    trafficLayerUrl: "การรับ-ส่งข้อมูลในชั้น URL"
  })
);