define(
   ({
    _widgetLabel: "繪圖",
    selectDrawMode: "選擇繪製模式",
    clear: "清除",
    point: "點",
    line: "線",
    polyline: "線",
    freehandPolyline: "手繪線",
    triangle: "三角形",
    extent: "方框",
    circle: "圓形",
    ellipse: "橢圓",
    polygon: "面",
    freehandPolygon: "手繪面",
    text: "文字",
    style: "樣式",
    alpha: "透明度",
    width: "寬度",
    size: "大小",
    color: "顏色",
    markerColor: "標記顏色",
    outlineColor: "輪廓顏色",
    lineColor: "線顏色",
    fillColor: "填滿顏色",
    showMeasurements: "顯示量測",
    areaUnits: "面積單位",
    distanceUnits: "距離單位",
    kilometers: "公里",
    miles: "英里",
    meters: "公尺",
    feet: "英呎",
    yards: "碼",
    squareKilometers: "平方公里",
    squareMiles: "平方英里",
    acres: "英畝",
    hectares: "公頃",
    squareMeters: "平方公尺",
    squareFeet: "平方英呎",
    squareYards: "平方碼",
    undo: "復原",
    redo: "重做",
    results: "結果",
    points: "點",
    lines: "線",
    areas: "面"
  })
);