define(
   ({
    taskUrl: "งาน URL",
    serviceURLPlaceholder: "โปรดนำเข้างานด้านกระบวนการภูมิศาสตร์ URL",
    ok: "ตกลง",
    cancel: "ยกเลิก",
    layer: "ชั้นข้อมูล",
    action: "กระทำ",
    input: "ข้อมูลนำเข้า",
    output: "ผลลัพธ์",
    name: "ชื่อ",
    type: "ประเภท",
    required: "ต้องการ",
    layerOrder: "เรียงลำดับชั้นข้อมูล",
    options: "ตัวเลือก",
    defaultValue: "ค่าตั้งต้น",
    inputFeatureBy: "นำเข้าฟีเจอร์โดย",
    renderer: "แสดง",
    displayType: "ประเภทการแสดง",
    label: "ตัวอักษร",
    tooltip: "คำแนะนำเครื่องมือ",
    visible: "มองเห็น",
    helpUrl: "ตัวช่วย URL",
    useResultMapService: "ใช้ตัวเลือกการวาดสำหรับผลลัพธ์เซอร์วิสแผนที่",
    drawOnMap: "การวาดแบบแผนที่แบบโต้ตอบอัตโนมัติ",
    selectLayer: "การเลือกชั้นข้อมูลจากแผนที่",
    url: "URL",
    symbol: "สัญลักษณ์",
    shareResults: "เพิ่มผลลัพธ์เป็นชั้นข้อมูลเกี่ยวกับการดำเนินงาน",
    popup: "ป๊อปอัพ",
    setTask: "ตั้ง",
    setTaskTitle: "ตั้งค่าการทำงานของ GP",
    enablePopup: "เปิดแสดงป็อปอัพ"
  })
);