define(
   ({
    taskUrl: "งาน URL",
    serviceURLPlaceholder: "โปรดนำเข้างานด้านกระบวนการภูมิศาสตร์ URL",
    ok: "ตกลง",
    cancel: "ยกเลิก",
    layer: "ชั้นข้อมูล",
    action: "กระทำ",
    input: "ข้อมูลนำเข้า",
    output: "ผลลัพธ์",
    name: "ชื่อ",
    type: "ประเภท",
    required: "ต้องการ",
    layerOrder: "เรียงลำดับชั้นข้อมูล",
    options: "ตัวเลือก",
    defaultValue: "ค่าตั้งต้น",
    inputFeatureBy: "นำเข้าฟีเจอร์โดย",
    renderer: "แสดง",
    displayType: "ประเภทการแสดง",
    label: "ตัวอักษร",
    tooltip: "คำแนะนำเครื่องมือ",
    visible: "มองเห็น",
    helpUrl: "ตัวช่วย URL",
    useResultMapService: "ใช้ตัวเลือกการวาดสำหรับผลลัพธ์เซอร์วิสแผนที่",
    drawOnMap: "การวาดแบบแผนที่แบบโต้ตอบอัตโนมัติ",
    selectLayer: "การเลือกชั้นข้อมูลจากแผนที่",
    url: "URL",
    symbol: "สัญลักษณ์",
    shareResults: "เพิ่มผลลัพธ์เป็นชั้นข้อมูลเกี่ยวกับการดำเนินงาน",
    popup: "ป๊อปอัพ",
    setTask: "ตั้ง",
    setTaskTitle: "ตั้งค่าการทำงานของ GP",
    enablePopup: "เปิดแสดงป็อปอัพ",
    unSupportGeometryType: "ไม่สามารถกำหนดการเรนเดอร์ เนื่องจากไม่ทราบประเภทเรขาคณิต",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "อัพโหลดไฟล์",
    selectFileToUpload: "เลือกไฟล์...",
    upload: "อัพโหลด",
    rasterFormat: "รูปแบบข้อมูลราสเตอร์",
    noFileSelected: "ไม่มีไฟล์ที่ถูกเลือก",
    uploadSuccess:"อัพโหลดไฟล์สำเร็จ",
    showLayerContent: "แสดงรายละเอียดชั้นข้อมูล",
    Feet: "ฟุต",
    Yards: "หลา",
    Miles: "ไมล์",
    NauticalMiles: "ไมล์ทะเล",
    Meter: "เมตร",
    Kilometers: "กิโลเมตร",
    urlPlaceholder: "การตั้งค่าคุณลักษณะ URL",
    allowToExport: "ยอมให้ส่งผลลัพธ์ออกไปได้"
  })
);
