define(
   ({
    addDistance: "新增長度單位",
    addArea: "新增面積單位",
    label: "標籤",
    abbr: "縮寫",
    conversion: "換算",
    actions: "操作",
    areaUnits: "面積單位",
    distanceUnits: "長度單位",
    kilometers: "公里",
    miles: "英里",
    meters: "公尺",
    feet: "英呎",
    yards: "碼",
    squareKilometers: "平方公里",
    squareMiles: "平方英里",
    acres: "英畝",
    hectares: "公頃",
    squareMeters: "平方公尺",
    squareFeet: "平方英呎",
    squareYards: "平方碼",
    distance: "距離",
    area: "面積",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "sq yd",
    defineUnits: "定義測量單位。",
    operationalLayer: "將繪製新增為地圖的業務圖層。"
  })
);