define(
   ({
    _widgetLabel: "Grafik",
    executeChartTip: "Grafiği işlemek için aşağıdaki öğelerden birine tıklayın.",
    invalidConfig: "Geçersiz yapılandırma.",
    noneChartTip: "Bu araç için yapılandırılan grafik görevi yok.",
    chartParams: "Seçenekler",
    charts: "GRAFİKLER",
    apply: "UYGULA",
    useSpatialFilter: "Özellikleri sınırlandırmak için mekansal filtre kullan",
    useCurrentMapExtent: "Yalnızca geçerli harita alanıyla kesişen detaylar",
    drawGraphicOnMap: "Yalnızca kullanıcı tanımlı bir alanla kesişen detaylar",
    chartResults: "Grafik Sonuçları",
    clearResults: "Sonuçları Temizle",
    noPermissionsMsg: "Bu servise erişmek için izniniz yok.",
    specifySpatialFilterMsg: "Bu görev için mekansal filtreyi belirtin.",
    queryError: "Sorgu başarısız.",
    noResults: "Detay bulunamadı.",
    category: "Kategori",
    count: "Sayım",
    label: "Etiket",
    horizontalAxis: "Yatay Eksen",
    verticalAxis: "Dikey Eksen",
    dataLabels: "Veri Etiketleri",
    color: "Renk",
    colorful: "Renkli",
    monochromatic: "Monokromatik",
    tasks: "Görevler",
    results: "Sonuçlar",
    applySpatialFilterToLimitResults: "Sonuçları sınırlamak için mekansal filtre uygula",
    useCurrentExtentTip: "Kısmen veya tamamen geçerli harita yayılımında",
    useDrawGraphicTip: "Kısmen veya tamamen haritada çizilen şekil içinde",
    useFeaturesTip: "Başka bir katmandaki detaylara göre konumlarına dayanarak",
    noSpatialLimitTip: "Sonuçları mekansal olarak sınırlama",
    applySearchDistance: "Arama mesafesi uygula",
    spatialRelationship: "Mekansal İlişki",
    relatedLayer: "İlgili Katman",
    clear: "Temizle",
    bufferDistance: "Tampon Mesafesi",
    miles: "Mil",
    kilometers: "Kilometre",
    feet: "Fit",
    meters: "Metre",
    yards: "Yarda",
    nauticalMiles: "Deniz Mili",
    back: "Geri",
    execute: "Çalıştır"
  })
);