define({
  root: ({
    _widgetLabel: "Reviewer Dashboard",
    spatialFilterSelection: "Filter results by geography",
    drawSelectionArea: "Draw a result selection area on the map",
    currentSelection:"Show results only in current map extent",
    censusBlockGroup:"Show results by geography",
    noSpatialFilter:" Use no spatial filter",
    reviewerSessionFilter:"Filter results by Reviewer Session",
    selectAttributeFilters:"Select information to display",
    phaseFieldName:"lifecyclephase",
    statusFieldName:"lifecyclestatus",
    allSessions:"All Sessions",
    dashboardTab:"Dashboard",
    filtersTab:"Settings",
    noResults:"No Results Found",
    resultsBy:"Results by: ",
    reviewed: "Review",
    corrected : "Correction",
    verified: "Verification",
    OtherCategory:"Other"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
