define(
   ({
    routeUrl: "Rutt-URL",
    locatorUrl: "Geokodarens URL",
    geocoderOptions: "Alternativ för geokodare",
    autoComplete: "Komplettera automatiskt",
    maxLocations: "Maximalt antal platser",
    minCharacters: "Minsta antal tecken",
    searchDelay: "Sökfördröjning",
    placeholder: "Platshållare",
    routeOptions: "Ruttalternativ",
    directionsLanguage: "Språk för beskrivningar",
    directionsLengthUnits: "Längdenheter för beskrivningar",
    directionsOutputType: "Utdatatyp för beskrivningar",
    impedanceAttribute: "Impedansattribut",
    kilometers: "Kilometer",
    miles: "Engelska mil",
    meters: "Meter",
    feet: "Fot",
    yards: "Yard",
    nauticalMiles: "Nautiska mil",
    parametersTip: "Ange parametrarna korrekt!",
    complete: "Fullständig",
    completeNoEvents: "Fullständig inga händelser",
    instructionsOnly: "Endast anvisningar",
    standard: "Standard",
    summaryOnly: "Endast sammanfattning",
    travelModesUrl: "URL för färdlägen",
    searchPlaceholder: "Sök efter adress eller plats",
    trafficLayerUrl: "URL för trafiklager"
  })
);