define(
   ({
    _widgetLabel: "Skriv ut",
    title: "Karttitel",
    format: "Format",
    layout: "Layout",
    settings: "Avancerad",
    mapScaleExtent: "Kartskala/utbredning",
    preserve: "Bevara",
    mapScale: "kartskala",
    mapExtent: "kartutbredning",
    forceScale: "Tvinga skala",
    getCurrentScale: "aktuell",
    mapMetadata: "Layout för metadata",
    author: "Författare",
    copyright: "Copyright",
    fullLayoutOptions: "Fullständiga layoutalternativ",
    scaleBarUnitsMetric: "Metriska enheter för skalfältet",
    scaleBarUnitsNonMetric: "Icke-metriska enheter för skalfältet",
    unitsMiles: "Engelska mil",
    unitsKilometers: "Kilometer",
    unitsMeters: "Meter",
    unitsFeet: "Fot",
    unitsYards: "Yard",
    unitsNauticalMiles: "Nautiska mil",
    lncludeLegend: "Inkludera teckenförklaring",
    printQualityOptions: "Utskriftskvalitet",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY-storlek",
    width: "Bredd (px)",
    height: "Höjd (px)",
    print: "Skriv ut",
    clearList: "Rensa utskrifter",
    creatingPrint: "Skapar utskrift",
    printError: "Fel, försök igen"
  })
);