define(
   ({
    _widgetLabel: "Diagrama",
    executeChartTip: "Norėdami vykdyti diagramą, paspauskite vieną iš šių užduoties elementų.",
    invalidConfig: "Neleidžiama konfigūracija.",
    noneChartTip: "Šiam valdikliui nesukonfigūruota nė viena diagramos užduotis.",
    chartParams: "Parinktys",
    charts: "DIAGRAMOS",
    apply: "TAIKYTI",
    useSpatialFilter: "Naudoti erdvinį filtrą elementų apribojimui",
    useCurrentMapExtent: "Tik elementai, besikertantys su esamu žemėlapio plotu",
    drawGraphicOnMap: "Tik elementai, besikertantys su vartotojo apibrėžtu plotu",
    chartResults: "Diagramos rezultatai",
    clearResults: "Išvalyti rezultatus",
    noPermissionsMsg: "Neturite teisės pasiekti šią paslaugą.",
    specifySpatialFilterMsg: "Nurodykite šios užduoties erdvinį filtrą.",
    queryError: "Užklausa nepavyko.",
    noResults: "Elementų nerasta.",
    category: "Kategorija",
    count: "Kiekis",
    label: "Žymė",
    horizontalAxis: "Horizontali ašis",
    verticalAxis: "Vertikali ašis",
    dataLabels: "Duomenų žymės",
    color: "Spalva",
    colorful: "Spalvingas",
    monochromatic: "Vienspalvis",
    tasks: "Užduotys",
    results: "Rezultatai",
    applySpatialFilterToLimitResults: "Taikyti erdvinį filtrą, kad būtų apriboti rezultatai",
    useCurrentExtentTip: "Iš dalies ar visiškai esamo žemėlapio aprėptyje",
    useDrawGraphicTip: "Iš dalies arba visiškai žemėlapyje nubrėžtoje figūroje",
    useFeaturesTip: "Remiantis jų vietomis kito sluoksnio elementų atžvilgiu",
    noSpatialLimitTip: "Erdviškai neapriboti rezultatų",
    applySearchDistance: "Taikyti paieškos nuotolį",
    spatialRelationship: "Erdviniai ryšiai",
    relatedLayer: "Susijęs sluoksnis",
    clear: "Valyti",
    bufferDistance: "Buferio atstumas",
    miles: "Mylios",
    kilometers: "Kilometrai",
    feet: "Pėdos",
    meters: "Metrai",
    yards: "Jardai",
    nauticalMiles: "Jūrmylės",
    back: "Atgal",
    execute: "Vykdyti"
  })
);