define(
   ({
    _widgetLabel: "عملية تحليل الحادث",
    incident: "طارئ",
    weather: "الطقس",
    locate_incident: "تحديد موقع الحادث",
    clear_incidents: "مسح الحوادث",
    reverse_geocoded_address: "أقرب عنوان",
    reverse_geocoded_error: "غير متاح",
    miles: "ميل",
    kilometers: "كيلومترات",
    feet: "قدم",
    meters: "متر",
    yards: "ياردة",
    nauticalMiles: "ميل بحري",
    now: "الآن",
    wind: "رياح",
    SUN: "الأحد",
    MON: "الأثنين",
    TUE: "الثلاثاء",
    WED: "الأربعاء",
    THU: "الخميس",
    FRI: "الجمعة",
    SAT: "السبت",
    defaultTabMsg: "لم يتم تعريف أية حوادث",
    actionLabel: "تحديد باعتبارها حادثة",
    useMapExtent: "استخدم نطاق الخريطة الحالي",
    noFeaturesFound: "لم يتم العثور على معالم.",
    downloadCSV: "تنزيل CSV",
    sum: "مجموع",
    min: "الحد الأدنى",
    max: "الحد الأقصى",
    avg: "المعدل",
    count: "عدد",
    area: "AREA",
    length: "LENGTH"
  })
);
