define(
   ({
    layerSelect: "Selecione a Camada de Imagens",
    displayMeasureResultInPopup: "Exiba resultados de medição numa janela pop-up",
    angularUnitSelect: "Unidade Angular Padrão",
    linearUnitSelect: "Unidade Linear Padrão",
    areaUnitSelect: "Unidade de Área padrão",
    displayOperationSelect: "Selecione operações de medida",
    errorSectionMeasage: "Nenhuma das camadas suporta capacidades de medição.",
    unitLabel: {
      esriInches: "Polegadas",
      esriFeet: "Pés",
      esriYards: "Jardas",
      esriMiles: "Milhas",
      esriNauticalMiles: "Milhas Náuticas",
      esriMillimeters: "Milímetros",
      esriCentimeters: "Centímetros",
      esriDecimeters: "Decímetros",
      esriMeters: "Metros",
      esriKilometers: "Quilômetros",
      esriDURadians: "Radians",
      esriDUDecimalDegrees: "Graus",
      esriSquareInches: "Sq Polegadas",
      esriSquareFeet: "Pés Quadrados",
      esriSquareYards: "Jardas Quadradas",
      esriAcres: "Acres",
      esriSquareMiles: "Milhas Quadradas",
      esriSquareMillimeters: "Sq Milímetros",
      esriSquareCentimeters: "Sq Centímetros",
      esriSquareDecimeters: "Sq Decímetros",
      esriSquareMeters: "Metros Quadrados",
      esriAres: "Ares",
      esriHectares: "Hectares",
      esriSquareKilometers: "Quilómetros Quadrados"
    },
    operationLabel: {
      esriMensurationPoint: "Ponto",
      esriMensurationDistanceAndAngle: "Distância e Ângulo",
      esriMensurationAreaAndPerimeter: "Área e Perimetro",
      esriMensurationHeightFromBaseAndTop: "Base para o Topo",
      esriMensurationHeightFromBaseAndTopShadow: "Base para o Topo-Sombra",
      esriMensurationHeightFromTopAndTopShadow: "Topo para Topo.Sombra",
      esriMensurationCentroid: "Centroid",
      esriMensurationPoint3D: "Ponto (3D)",
      esriMensurationDistanceAndAngle3D: "Distância e Ângulo (3D)",
      esriMensurationAreaAndPerimeter3D: "Área e Perimetro (3D)",
      esriMensurationCentroid3D: "Centroid (3D)"
    }
  })
);