define(
	 ({
		charts: "Diagramtaken",
		addNew: "Nieuwe toevoegen",
		addNewTip: "Een nieuwe diagramtaak toevoegen",
		name: "Naam",
		set: "Instellen",
		setDataSource: "Gegevensbron instellen",
		generalSettingsTip: "Stel de gegevensbron, titel en beschrijving voor diagrammen in.",
		chartModeSettingTip: "Selecteer een manier om gegevens als diagrammen te analyseren en weer te geven.",
		detailsSettingTip: "Stel het uiterlijk van het diagram in door de typen en kleur op te geven en de waarden die in het diagram zullen worden geplaatst.",
		symbolSettingTip: "Stel de kaartweergave in voor gegevens die in een diagram zijn geplaatst.",
		addFilterTip: "Filter toevoegen aan deze gegevens",
		dataSource: "Bron gegevens",
		noResults: "Geen object gevonden",
		chartTitle: "Diagramtitel",
		description: "Beschrijving",
		chartingMode: "Diagramweergave",
		featureOption: "Waarden object per object weergeven",
		categoryOption: "Waarden op categorie weergeven",
		countOption: "Objectaantallen op categorie weergeven",
		fieldOption: "Attribuutwaarden weergeven als diagrammen",
		category: "Categorie",
		axisLabel: "Categorielabel",
		categoryField: "Categorieveld",
		operation: "Bewerking",
		originalOption: "Oorspronkelijke waarden gebruiken",
		sumOption: "Som",
		averageOption: "Gemiddelde",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Waardevelden",
		moveUp: "Naar boven verplaatsen",
		moveDown: "Naar beneden verplaatsen",
		sortOrder: "Volgorde van diagrammen sorteren via categorielabels",
		ascending: "Oplopend",
		descending: "Aflopend",
		chartType: "Diagramtype",
		column: "Kolomdiagram",
		bar: "Staafdiagram",
		line: "Lijndiagram",
		pie: "Taartdiagram",
		chartColor: "Diagramkleur",
		showDataLabels: "Gegevenslabels weergeven",
		setSymbol: "Selectiesymbool",
		setHighLightColor: "Markeringskleur",
		settings: "Instellingen",
		mapInterationOptions: "Opties voor kaartinteractie",
		preview: "Voorbeeld",
		ok: "OK",
		cancel: "Annuleren",
		close: "Sluiten",
		setFilterTip: "Stel het filter correct in. ",
		setChartTitleTip: "Stel de diagramtitel in.",
		setChartTypeTip: "Selecteer ten minste één diagramtype.",
		setDataFieldTip: "Selecteer ten minste één waardeveld.",
		setOutputFieldTip: "Stel uitvoervelden in.",
		count: "Telling",
		label: "Label",
		horizontalAxis: "Horizontale as",
		verticalAxis: "Verticale as",
		dataLabels: "Datalabels",
		color: "Kleur",
		colorful: "Kleur",
		monochromatic: "Zwart-wit"
  })
);