define(
	 ({
		chartTasks: "Diagramtaken",
		addNew: "Nieuwe toevoegen",
		addNewTip: "Een nieuwe diagramtaak toevoegen",
		name: "Naam",
		set: "Instellen",
		setDataSource: "Gegevensbron instellen",
		generalSettingsTip: "Stel de gegevensbron, titel en beschrijving voor diagrammen in.",
		chartModeSettingTip: "Selecteer een manier om gegevens als diagrammen te analyseren en weer te geven.",
		detailsSettingTip: "Stel het uiterlijk van het diagram in door de typen en kleur op te geven en de waarden die in het diagram zullen worden geplaatst:",
		symbolSettingTip: "Stel de kaartweergave in voor gegevens die in een diagram zijn geplaatst.",
		addFilterTip: "Filter toevoegen aan deze gegevens",
		dataSource: "Bron gegevens",
		noResults: "Geen object gevonden",
		chartTitle: "Diagramtitel",
		description: "Beschrijving",
		chartingMode: "Diagramweergave",
		featureOption: "Waarden object per object weergeven",
		categoryOption: "Waarden op categorie weergeven",
		countOption: "Objectaantallen op categorie weergeven",
		fieldOption: "Attribuutwaarden weergeven als diagrammen",
		category: "Categorie",
		axisLabel: "Categorielabel",
		categoryField: "Categorieveld",
		operation: "Bewerking",
		originalOption: "Oorspronkelijke waarden gebruiken",
		sumOption: "Som",
		averageOption: "Gemiddelde",
		minOption: "Minimum",
		maxOption: "Maximum",
		valueFields: "Waardevelden",
		moveUp: "Naar boven verplaatsen",
		moveDown: "Naar beneden verplaatsen",
		sortOrder: "Volgorde van diagrammen sorteren via categorielabels",
		ascending: "Oplopend",
		descending: "Aflopend",
		chartType: "Diagramtype",
		column: "Kolomdiagram",
		bar: "Staafdiagram",
		line: "Lijndiagram",
		pie: "Taartdiagram",
		chartColor: "Diagramkleur",
		showDataLabels: "Gegevenslabels weergeven",
		setSymbol: "Selectiesymbool",
		setHighLightColor: "Markeringskleur",
		settings: "Instellingen",
		mapInterationOptions: "Opties voor kaartinteractie",
		preview: "Voorbeeld",
		ok: "OK",
		cancel: "Annuleren",
		close: "Sluiten",
		setFilterTip: "Stel het filter correct in. ",
		setChartTitleTip: "Stel de diagramtitel in.",
		setChartTypeTip: "Selecteer ten minste één diagramtype.",
		setDataFieldTip: "Selecteer ten minste één waardeveld.",
		setOutputFieldTip: "Stel uitvoervelden in.",
		count: "Telling",
		label: "Label",
		horizontalAxis: "Horizontale as",
		verticalAxis: "Verticale as",
		dataLabels: "Datalabels",
		color: "Kleur",
		colorful: "Kleur",
		monochromatic: "Zwart-wit",
    noTaskTip: "Klik op Nieuwe toevoegen om een nieuwe diagramtaak toe te voegen",
    info: "Info",
    charts: "Diagrammen",
    options: "Opties",
    taskName: "Naam taak",
    summary: "Samenvatting",
    resultDescription: "Resultaatomschrijving",
    spatialFilterTip: "Kies de ruimtelijke filter(s) die in de widget gebruikt worden om de resultaten te beperken.",
    defaultOption: "Standaard",
    useCurrentExtentTip: "Gedeeltelijk of volledig in de actuele kaart",
    useDrawGraphicTip: "Gedeeltelijk of volledig in de vorm die op de kaart getekend is",
    useFeaturesTip: "Op basis van de locaties t.o.v. de objecten in een andere laag",
    noSpatialLimitTip: "Resultaten niet ruimtelijk beperken",
    drawingTools: "Tekentools",
    bufferSettings: "Bufferinstellingen",
    defaultDistance: "Standaardafstand",
    bufferDistance: "Bufferafstand",
    defaultUnit: "Standaardeenheid",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    availableSpatialRelationships: "Beschikbare ruimtelijke relaties",
    setSpatialRelationships: "Ruimtelijke relaties instellen",
    availability: "Beschikbaarheid",
    relationship: "Verhouding",
    actions: "Acties",
    intersect: "kruisen",
    contain: "bevatten",
    areContainedIn: "zijn omvat in",
    cross: "kruis",
    envelopeIntersect: "kruisingenvelop",
    overlap: "overlappen",
    areOverlapped: "zijn overlapt",
    touche: "aanraking",
    within: "in",
    areWithin: "bevinden zich in",
    indexIntersect: "index kruising"
  })
);