define(
   ({
    _widgetLabel: "Feature report",
    select: "Seleziona",
    draw: "Disegna",
    chooseALayer: "Seleziona un layer",
    clickAFeature: "Fare clic su una feature nella mappa per selezionarla.",
    loadingFeatures: "Recupero dettagli feature selezionate in corso...",
    errorTitle: "Errore",
    errorIdentify: "Identifica errore feature. Per i dettagli, consultare il log della console.",
    infoWindowTitle: "Dettagli",
    layerLabel: "Nome layer",
    reviewStatusLabel: "Stato revisione",
    selectReviewStatusAdd: "Aggiungi feature",
    selectReviewStatusDelete: "Elimina feature",
    selectReviewStatusMove: "Sposta feature",
    selectReviewStatusReshape: "Rimodella la feature",
    drawReviewStatusMissing: "Feature mancanti",
    drawReviewStatusPosition: "Errore di posizionamento",
    drawReviewStatusShape: "Errore shape",
    drawReviewStatusAttribute: "Errore attributo",
    notesLabel: "Note",
    severityLabel: "Severità",
    reportedByLabel: "Segnalato da",
    reportedByDefault: "anonimo",
    reportButton: "Report",
    reportMessage: "Report ricevuto",
    errorReportMessage: "Errore durante la segnalazione della feature",
    drawErrorInstructions: "Selezionare punto, linea o poligono e disegnare la geometria errori sulla mappa:",
    errorMapService: "Si è verificato un errore durante il recupero delle informazioni su map service.",
    noFeatureSelected : "Nessuna feature trovata nella posizione selezionata",
    selectFeatureMapPoint: "Fare clic per selezionare una feature",
    drawFeatureMapPoint: "Fare clic per aggiungere un punto",
    popupMessage:"Messaggio",
    popupError:"Errore",
    manyFeaturesSelected: "Trovate più feature. Eseguire lo zoom avanti e selezionare una feature da segnalare."
  })
);
