define(
	 ({
		queries: "Spørringsoppgaver",
		addNew: "Legg til ny",
    queryLayer: "Kjør spørring for lag",
		setSource: "Angi",
		setDataSource: "Angi datakilde",
		name: "Navn",
		querySource: "Datakilde",
		queryName: "Navn på oppgave",
		queryDefinition: "Filterdefinisjon",
		resultsSetting: "Resultatinnstilling",
		symbolSetting: "Symbolinnstilling",
		resultSettingTip: "Definer hva som skal vises i resultatene og hvordan de skal vises.",
		resultItemTitle: "Tittelelement for resultat",
		resultItemContent: "Innhold i resultatelement",
		fieldsSetTip: "Merk av for feltene du vil vise. Velg et felt for å oppdatere aliaset, rekkefølgen eller formatet.",
		addField: "Legg til felt",
		visibility: "Synlighet",
		alias: "Alias",
		specialType: "Spesiell type",
		actions: "Handlinger",
		none: "Ingen",
		link: "Kobling",
		image: "Bilde",
		noField: "Ingen felt",
		operationalLayerTip: "Legg til resultat som operativt kartlag",
		setLayerSymbolTip: "Angi symbol for spørringsresultater: ",
		setSelectedSymbolTip: "Angi symbolet for det valgte geoobjektet.",
		notUseFilter: "Ikke bruk filter",
		setSourceTip: "Angi kilde for spørring.",
		setFilterTip: "Angi filteret på riktig måte.",
		ok: "OK",
		cancel: "Avbryt",
		noFilterTip: "Uten definert filteruttrykk viser denne spørringoppgaven alle geoobjekter i den angitte datakilden.",
    relationships: "Relasjoner",
    addRelationshipLayer: "Legg til ny relasjon",
    relatedTo: "Gjelder",
    selectOption: "Du må velge...",
    resultItemSorting: "Sortering av resultatelementer",
    field: "Felt",
    sortingOrder: "Rekkefølge",
    configureFieldsTip: "Konfigurer feltene som spørringsresultatene skal sorteres etter.",
    setSortingFields: "Angi sorteringsfelter",
    ascending: "Stigende",
    descending: "Synkende",
    sortBy: "Sorter etter",
    thenBy: "Deretter etter",
    addTask: "Legg til oppgave",
    noTasksTip: 'Ingen oppgaver. Klikk på \"${addTask}\" for å begynne.',
    infoText: "Info",
    filters: "Filtre",
    results: "Resultater",
    optionsText: "Alternativer",
    summaryText: "Sammendrag",
    attributeFilter: "Attributtfilter",
    attributeFilterTip: "Definer attributtuttrykk som skal brukes i widgeten til å filtrere spørringslaget.",
    noExpressionDefinedTip: "Det er ingen definerte uttrykk.",
    needInputValuesTip: "Verdier må angis ved kjøretid",
    setExpressions: "Angi uttrykk",
    spatialFilter: "Geografisk filter",
    spatialFilterTip: "Velg et eller flere romlige filtre som er brukt til å begrense resultatene i widgeten.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Delvis eller helt innenfor gjeldende kartutstrekning",
    useDrawGraphicTip: "Delvis eller helt innenfor formen som er tegnet på kartet",
    useFeaturesTip: "Basert på deres lokasjoner i forhold til geoobjekter i andre lag",
    noSpatialLimitTip: "Ikke bruk romlig begrensing på resultater",
    drawingTools: "Tegneverktøy",
    bufferSettings: "Bufferinnstillinger",
    defaultDistance: "Standardavstand",
    bufferDistance: "Bufferavstand",
    defaultUnit: "Standardenhet",
    miles: "Miles",
    kilometers: "kilometer",
    feet: "fot",
    meters: "meter",
    yards: "Yards",
    nauticalMiles: "Nautiske mil",
    availableSpatialRelationships: "Tilgjengelige romlige relasjoner",
    setSpatialRelationships: "Angi romlige relasjoner",
    availability: "Tilgjengelighet",
    relationship: "Relasjon",
    label: "Etikett",
    intersect: "skjæringspunkt",
    contain: "inneholder",
    areContainedIn: "forekommer i",
    cross: "krysse",
    envelopeIntersect: "skjæringspunkt for innhyllingskurve",
    overlap: "overlapping",
    areOverlapped: "er overlappet",
    touche: "tanger",
    within: "innenfor",
    areWithin: "er innenfor",
    indexIntersect: "skjæringspunkt for indeks",
    itemTitle: "Elementtittel",
    displayFields: "Vis felter",
    sortingFields: "Sorteringsfelter",
    setDisplayFields: "Angi vsiningsfelter",
    symbol: "Symbol",
    setSymbol: "Angi symbol",
    serviceSymbolTip: "Bruk symboler definert av laget",
    exportTip: "Vis Eksporter-knappen",
    keepResultsTip: "Behold resultatene på kartet etter at widgeten er lukket",
    queryRelatedRecords: "Foreta spørring i relaterte poster",
    createLayerForTaskTip: "Angi hvordan oppgaven oppretter lag",
    oneLayerForTaskTip: "Opprett bare ett lag for denne oppgaven",
    multipleLayerForTaskTip: "Opprett et nytt lag hver gang oppgaven utføres"
  })
);
