define(
	 ({
		queries: "Spørringsoppgaver",
		addNew: "Legg til ny",
		setSource: "Angi",
		setDataSource: "Angi datakilde",
		name: "Navn",
		querySource: "Datakilde",
		queryName: "Navn på oppgave",
		queryDefinition: "Filterdefinisjon",
		resultsSetting: "Resultatinnstilling",
		symbolSetting: "Symbolinnstilling",
		resultSettingTip: "Definer hva som skal vises i resultatene og hvordan de skal vises.",
		resultItemTitle: "Tittelelement for resultat",
		resultItemContent: "Innhold i resultatelement",
		fieldsSetTip: "Merk av for feltene du vil vise. Velg et felt for å oppdatere aliaset, endre rekkefølgen på det eller formatere det.",
		addField: "Legg til felt",
		visibility: "Synlighet",
		alias: "Alias",
		specialType: "Spesiell type",
		actions: "Handlinger",
		none: "Ingen",
		link: "Kobling",
		image: "Bilde",
		noField: "Ingen felt",
		operationalLayerTip: "Legg til resultat som operativt kartlag",
		setLayerSymbolTip: "Angi symbol for spørringsresultater: ",
		setSelectedSymbolTip: "Angi symbolet for det valgte geoobjektet.",
		notUseFilter: "Ikke bruk filter'",
		setSourceTip: "Angi kilde for spørring.",
		setFilterTip: "Angi filteret på riktig måte.",
		ok: "OK",
		cancel: "Avbryt",
		noFilterTip: "Uten noe definert filteruttrykk viser denne spørringoppgaven alle geoobjekter i den angitte datakilden."
  })
);