define(
   ({
    "tabs_section_Label": "Pestañas",
    "addTab": "Agregar pestaña",
    "layerName": "Capa",
    "layerType": "Tipo de análisis",
    "layerLabel": "Etiqueta",
    "actions": "Acciones",
    "closest": "Entidad más próxima",
    "proximity": "Proximidad",
    "summary": "Resumen",
    "select_lbl": "-- Seleccionar --",
    "general_setting_Label": "Configuración general",
    "units_text_lbl": "Unidades de distancia",
    "miles": "Millas",
    "kilometers": "Kilómetros",
    "feet": "Pies",
    "meters": "Metros",
    "yards": "Yardas",
    "nauticalMiles": "Millas Náuticas",
    "maximum_distance_lbl": "Distancia máxima a la entidad más próxima",
    "buffer_text_lbl": "Etiqueta de zona de influencia",
    "buffer_lbl": "Distancia de zona de influencia",
    "buffer_max_lbl": "Distancia de zona de influencia máxima",
    "buffer_min_lbl": "Distancia de zona de influencia mínima",
    "routing_checkBox": "Habilitar enrutamiento",
    "weather_Label": "Opciones del tiempo",
    "weather_checkBox": "Incluir información del tiempo",
    "selectLayers": "Seleccionar capas del tiempo",
    "currentlySelectedLayer": "Capas del tiempo seleccionadas actualmente",
    "missingTabLabel": "Falta la etiqueta en una pestaña al menos",
    "cancel": "Cancelar",
    "ok": "Aceptar",
    "missingLayerInWebMap": "No se ha encontrado ninguna capa operativa.",
    "selectFields": "Selecciona campos",
    "addField": "Agregar campo",
    "sum": "SUM",
    "min": "MIN",
    "max": "MÁX",
    "avg": "AVG",
    "count": "TOTAL",
    "area": "ÁREA",
    "length": "LONGITUD",
    "count_checkBox": "Mostrar recuento",
    "area_checkBox": "Mostrar área",
    "length_checkBox": "Mostrar longitud",
    "max_records": "Se ha alcanzado el límite máximo"
  })
);
