define(
   ({
    "tabs_section_Label": "File",
    "addTab": "Adăugare filă",
    "layerName": "Strat tematic",
    "layerType": "Tip analiză",
    "layerLabel": "Etichetă",
    "actions": "Acţiuni",
    "closest": "Cel mai apropiat obiect spaţial",
    "proximity": "Proximitate",
    "summary": "Rezumat",
    "select_lbl": "-- Selectare --",
    "general_setting_Label": "Setări generale",
    "units_text_lbl": "Unităţi distanţă",
    "miles": "Mile",
    "kilometers": "Kilometri",
    "feet": "Ft",
    "meters": "Metri",
    "yards": "Iarzi",
    "nauticalMiles": "Mile marine",
    "maximum_distance_lbl": "Distanţă maximă cel mai apropiat obiect spaţial",
    "buffer_text_lbl": "Etichetă buffer",
    "buffer_lbl": "Distanţă buffer",
    "buffer_max_lbl": "Distanţă maximă buffer",
    "buffer_min_lbl": "Distanţă minimă buffer",
    "routing_checkBox": "Activare rutare",
    "weather_Label": "Opţiuni condiţii meteo",
    "weather_checkBox": "Includere informaţii condiţii meteo",
    "selectLayers": "Selectare straturi tematice condiţii meteo",
    "currentlySelectedLayer": "Straturile tematice cu condiţii meteo selectate în mod curent",
    "missingTabLabel": "Cel puţin o filă nu are etichetă",
    "cancel": "Anulare",
    "ok": "OK",
    "missingLayerInWebMap": "Nu s-a găsit niciun strat tematic operaţional.",
    "selectFields": "Selectare câmpuri",
    "addField": "Adăugare câmp",
    "sum": "SUMĂ",
    "min": "MIN.",
    "max": "MAX",
    "avg": "MED.",
    "count": "NUMĂR",
    "area": "SUPRAFAŢĂ",
    "length": "LUNGIME",
    "count_checkBox": "Afişare număr",
    "area_checkBox": "Afişare zonă",
    "length_checkBox": "Afişare lungime",
    "max_records": "Limită maximă atinsă"
  })
);
