define({
  root: ({
    _widgetLabel: "Incident Analysis",
    incident: "Incident",
    weather: "Weather",
    locate_incident: "Locate Incident",
    clear_incidents: "Clear Incidents",
    reverse_geocoded_address: "Closest address",
    reverse_geocoded_error: "Not available",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    now: "NOW",
    wind: "WIND",
    SUN: "SUN",
    MON: "MON",
    TUE: "TUE",
    WED: "WED",
    THU: "THU",
    FRI: "FRI",
    SAT: "SAT",
    defaultTabMsg: "No incidents identified.",
    actionLabel: "Set As Incident",
    useMapExtent: "Use the current map extent",
    noFeaturesFound: "No features found.",
    downloadCSV: "DOWNLOAD CSV",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
