define(
   ({
    routeUrl: "Marsruudi URL",
    locatorUrl: "Geokodeerija URL",
    geocoderOptions: "Geokodeerija valikud",
    autoComplete: "Autom. koostamine",
    maxLocations: "Maksimaalselt asukohti",
    minCharacters: "Minimaalselt tähemärke",
    searchDelay: "Otsingu viivitus",
    placeholder: "Kohatäide",
    routeOptions: "Marsruudi valikud",
    directionsLanguage: "Teejuhiste keel",
    directionsLengthUnits: "Teejuhiste pikkusühikud",
    directionsOutputType: "Teejuhiste väljundi tüüp",
    impedanceAttribute: "Takistuse atribuut",
    kilometers: "Kilomeetrit",
    miles: "Miili",
    meters: "Meetrit",
    feet: "Jalga",
    yards: "Jardi",
    nauticalMiles: "Meremiili",
    parametersTip: "Määrake parameetrid õigesti!",
    complete: "Valmis",
    completeNoEvents: "Valmis, sündmusi pole",
    instructionsOnly: "Ainult juhised",
    standard: "Standardne",
    summaryOnly: "Ainult kokkuvõte",
    travelModesUrl: "Liikumisviiside URL",
    searchPlaceholder: "Otsi aadressi või kohta",
    trafficLayerUrl: "Liikluskihi URL"
  })
);