define(
   ({
    _widgetLabel: "Запрос",
    executeQueryTip: "Выберите одну из следующих задач для выполнения запроса.",
    invalidConfig: "Недопустимая конфигурация. Используйте страницу настройки запроса для получения правильной конфигурации.",
    queryParams: "Опции",
    parameters: "ОПЦИИ",
    queries: "ЗАПРОСЫ",
    apply: "ПРИМЕНИТЬ",
    queryResults: "Результаты",
    clear: "Очистить",
    noResults: "Объекты не найдены.",
    queryError: "Сбой запроса!",
    numberFound: "Число найденных объектов",
    mapExtentTip: "Ограничить результаты на текущим экстентом карты.",
    noValue: "Нет значения",
    and: "и",
    stringOperatorIs: "соответствует", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "не соответствует",
    stringOperatorStartsWith: "начинается с",
    stringOperatorEndsWith: "заканчивается",
    stringOperatorContains: "содержит",
    stringOperatorDoesNotContain: "не содержит",
    stringOperatorIsBlank: "является пустым",
    stringOperatorIsNotBlank: "не является пустым",
    dateOperatorIsOn: "соответствует", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "не соответствует",
    dateOperatorIsBefore: "перед",
    dateOperatorIsAfter: "после",
    dateOperatorDays: "дней",
    dateOperatorWeeks: "недель", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "месяцев",
    dateOperatorInTheLast: "в последние",
    dateOperatorNotInTheLast: "не в последние",
    dateOperatorIsBetween: "между",
    dateOperatorIsNotBetween: "не между",
    dateOperatorIsBlank: "является пустым",
    dateOperatorIsNotBlank: "не является пустым",
    numberOperatorIs: "соответствует", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "не соответствует",
    numberOperatorIsAtLeast: "больше или равно",
    numberOperatorIsLessThan: "меньше чем",
    numberOperatorIsAtMost: "меньше или равно",
    numberOperatorIsGreaterThan: "больше чем",
    numberOperatorIsBetween: "между",
    numberOperatorIsNotBetween: "не между",
    numberOperatorIsBlank: "является пустым",
    numberOperatorIsNotBlank: "не является пустым",
    operationalLayerTip: "Добавить результат как операционный слой",
    queryResult: "Результат запроса",
    specifyParamsTip: "Укажите параметры для этой задачи",
    useSpatialFilter: "Использовать пространственный фильтр для ограничения объектов",
    useCurrentMapExtent: "Только объекты, касающиеся текущего экстента карты",
    drawGraphicOnMap: "Только объекты, касающиеся заданной пользователем области",
    specifySpatialFilterMsg: "Укажите пространственный фильтр для этой задачи.",
    clearResults: "Очистить результаты",
    operationalTip: 'При выборе этой опции результаты будут на карте, пока не нажата кнопка "${clearResults}".',
    noneQueryTip: "Нет доступных настроенных заданий диаграммы.",
    noPermissionsMsg: "У вас нет разрешения на доступ к этому сервису."
  })
);