define(
   ({
    _widgetLabel: "Berichts-Feature",
    select: "Auswählen",
    draw: "Darstellen",
    chooseALayer: "Layer auswählen",
    clickAFeature: "Klicken Sie auf ein Feature auf der Karte, um es auszuwählen.",
    loadingFeatures: "Details zu den ausgewählten Features werden abgerufen...",
    errorTitle: "Fehler",
    errorIdentify: "Fehler beim Identifizieren der Features. Details finden Sie im Konsolenprotokoll.",
    infoWindowTitle: "Details",
    layerLabel: "Layer-Name",
    reviewStatusLabel: "Überprüfungsstatus",
    selectReviewStatusAdd: "Feature hinzufügen",
    selectReviewStatusDelete: "Feature löschen",
    selectReviewStatusMove: "Feature verschieben",
    selectReviewStatusReshape: "Feature umformen",
    drawReviewStatusMissing: "Fehlende(s) Feature(s)",
    drawReviewStatusPosition: "Positionsfehler",
    drawReviewStatusShape: "Shape-Fehler",
    drawReviewStatusAttribute: "Attributfehler",
    notesLabel: "Hinweise",
    severityLabel: "Gewichtung",
    reportedByLabel: "Erfasst von",
    reportedByDefault: "anonym",
    reportButton: "Bericht",
    reportMessage: "Bericht empfangen",
    errorReportMessage: "Beim Melden des Features ist ein Fehler aufgetreten",
    drawErrorInstructions: "Wählen Sie einen Punkt, eine Linie oder ein Polygon aus, und stellen Sie die Fehlergeometrie auf der Karte dar:",
    errorMapService: "Beim Abrufen der Kartenservice-Informationen ist ein Fehler aufgetreten",
    noFeatureSelected : "An der Position, auf die geklickt wurde, wurden keine Features gefunden",
    selectFeatureMapPoint: "Klicken Sie hier, um ein Feature auszuwählen",
    drawFeatureMapPoint: "Klicken, um einen Punkt hinzuzufügen",
    popupMessage:"Meldung",
    popupError:"Fehler",
    manyFeaturesSelected: "Es wurden mehrere Features gefunden. Vergrößern Sie die Ansicht, und wählen Sie ein zu meldendes Feature aus."
  })
);
