define(
   ({
    _widgetLabel: "Consulta",
    executeQueryTip: "Haz clic en uno de los siguientes elementos de tarea para ejecutar la consulta.",
    invalidConfig: "Configuración no válida. Utiliza la página de configuración de consulta para obtener la configuración correcta.",
    queryParams: "Opciones",
    parameters: "OPCIONES",
    queries: "CONSULTAS",
    apply: "APLICAR",
    queryResults: "Resultados",
    clear: "Borrar",
    noResults: "Ninguna entidad encontrada.",
    queryError: "Error en la consulta",
    numberFound: "Número de entidades encontradas",
    mapExtentTip: "Limita los resultados a la extensión de mapa actual.",
    noValue: "Sin valor",
    and: "y",
    stringOperatorIs: "es", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "no es",
    stringOperatorStartsWith: "comienza por",
    stringOperatorEndsWith: "termina en",
    stringOperatorContains: "contiene",
    stringOperatorDoesNotContain: "no contiene",
    stringOperatorIsBlank: "está vacío",
    stringOperatorIsNotBlank: "no está vacío",
    dateOperatorIsOn: "es el", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "no es el",
    dateOperatorIsBefore: "es anterior a",
    dateOperatorIsAfter: "es posterior a",
    dateOperatorDays: "días",
    dateOperatorWeeks: "semanas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "meses",
    dateOperatorInTheLast: "es el último",
    dateOperatorNotInTheLast: "no es el último",
    dateOperatorIsBetween: "está entre",
    dateOperatorIsNotBetween: "no está entre",
    dateOperatorIsBlank: "está vacío",
    dateOperatorIsNotBlank: "no está vacío",
    numberOperatorIs: "es", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "no es",
    numberOperatorIsAtLeast: "es como mínimo",
    numberOperatorIsLessThan: "es menos que",
    numberOperatorIsAtMost: "es como máximo",
    numberOperatorIsGreaterThan: "es mayor que",
    numberOperatorIsBetween: "está entre",
    numberOperatorIsNotBetween: "no está entre",
    numberOperatorIsBlank: "está vacío",
    numberOperatorIsNotBlank: "no está vacío",
    operationalLayerTip: "Agregar resultado como capa operativa",
    queryResult: "Resultado de consulta",
    specifyParamsTip: "Especificar parámetros para esta tarea",
    useSpatialFilter: "Usar filtro espacial para limitar las entidades",
    useCurrentMapExtent: "Solo entidades que toquen la extensión de mapa actual",
    drawGraphicOnMap: "Solo entidades que toquen un área definida por el usuario",
    specifySpatialFilterMsg: "Especifica un filtro espacial para esta tarea.",
    clearResults: "Borrar resultados",
    operationalTip: 'Con esta opción seleccionada, los resultados se conservarán en el mapa hasta que se haga clic en el botón "${clearResults}".',
    noneQueryTip: "No hay ninguna tarea de consulta preconfigurada disponible.",
    noPermissionsMsg: "No tienes permisos para acceder a este servicio."
  })
);