define(
   ({
    _widgetLabel: "Consulta",
    executeQueryTip: "Haz clic en uno de los siguientes elementos de tarea para ejecutar la consulta.",
    invalidConfig: "Configuración no válida. Utiliza la página de configuración de consulta para obtener la configuración correcta.",
    queryParams: "Opciones",
    parameters: "OPCIONES",
    queries: "CONSULTAS",
    apply: "APLICAR",
    queryResults: "Resultados",
    clear: "Borrar",
    noResults: "Ninguna entidad encontrada.",
    queryError: "Error en la consulta",
    numberFound: "Número de entidades encontradas",
    mapExtentTip: "Limita los resultados al área de mapa actual.",
    noValue: "Sin valor",
    and: "y",
    stringOperatorIs: "es", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "no es",
    stringOperatorStartsWith: "comienza por",
    stringOperatorEndsWith: "termina en",
    stringOperatorContains: "contiene",
    stringOperatorDoesNotContain: "no contiene",
    stringOperatorIsBlank: "está vacío",
    stringOperatorIsNotBlank: "no está vacío",
    dateOperatorIsOn: "es el", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "no es el",
    dateOperatorIsBefore: "es anterior a",
    dateOperatorIsAfter: "es posterior a",
    dateOperatorDays: "días",
    dateOperatorWeeks: "semanas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "meses",
    dateOperatorInTheLast: "es el último",
    dateOperatorNotInTheLast: "no es el último",
    dateOperatorIsBetween: "está entre",
    dateOperatorIsNotBetween: "no está entre",
    dateOperatorIsBlank: "está vacío",
    dateOperatorIsNotBlank: "no está vacío",
    numberOperatorIs: "es", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "no es",
    numberOperatorIsAtLeast: "es como mínimo",
    numberOperatorIsLessThan: "es menos que",
    numberOperatorIsAtMost: "es como máximo",
    numberOperatorIsGreaterThan: "es mayor que",
    numberOperatorIsBetween: "está entre",
    numberOperatorIsNotBetween: "no está entre",
    numberOperatorIsBlank: "está vacío",
    numberOperatorIsNotBlank: "no está vacío",
    operationalLayerTip: "Agregar resultado como capa operativa",
    queryResult: "Resultado de consulta",
    specifyParamsTip: "Especificar parámetros para esta tarea",
    useSpatialFilter: "Usar filtro espacial para limitar las entidades",
    useCurrentMapExtent: "Solo entidades que intersequen el área de mapa actual",
    drawGraphicOnMap: "Solo entidades que intersequen el área definida por el usuario",
    specifySpatialFilterMsg: "Especifica un filtro espacial para esta tarea.",
    clearResults: "Borrar resultados",
    operationalTip: 'Con esta opción seleccionada, los resultados se conservarán en el mapa hasta que se haga clic en el botón \"${clearResults}\".',
    noneQueryTip: "No se ha configurado ninguna tarea de consulta para este widget.",
    noPermissionsMsg: "No tienes permisos para acceder a este servicio.",
    attributesFromRelationship: "Atributos de la tabla asociada",
    tasks: "Tareas",
    applySpatialFilterToLimitResults: "Aplicar un filtro espacial para limitar los resultados",
    useCurrentExtentTip: "Parcial o totalmente dentro de la extensión de mapa actual",
    useDrawGraphicTip: "Parcial o totalmente dentro de la forma dibujada en el mapa",
    useFeaturesTip: "En función de sus ubicaciones con respecto a las entidades de otra capa",
    noSpatialLimitTip: "No limitar espacialmente los resultados",
    applySearchDistance: "Aplicar una distancia de búsqueda",
    spatialRelationship: "Relación espacial",
    relatedLayer: "Capa relacionada",
    bufferDistance: "Distancia de zona de influencia",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    back: "Atrás",
    execute: "Ejecutar"
  })
);