define(
   ({
    taskUrl: "Oppgave-URL",
    serviceURLPlaceholder: "Angi oppgave-URLen for geoprosessering",
    ok: "OK",
    cancel: "Avbryt",
    layer: "Lag",
    action: "Handling",
    input: "Inndata",
    output: "Resultat",
    name: "Navn",
    type: "Type",
    required: "Obligatorisk",
    layerOrder: "Lagrekkefølge",
    options: "Alternativer",
    defaultValue: "Standardverdi",
    inputFeatureBy: "Inndata-geoobjekter etter",
    renderer: "Opptegning",
    displayType: "Vis type",
    label: "Etikett",
    tooltip: "Verktøytips",
    visible: "Synlig",
    helpUrl: "Hjelp-URL",
    useResultMapService: "Bruk tegnealternativene fra resultatkarttjenesten",
    drawOnMap: "Interaktiv tegning på kartet",
    selectLayer: "Velge et kartlag fra kartet",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Legg til resultat som operativt kartlag",
    popup: "Sprettoppvindu",
    setTask: "Angi",
    setTaskTitle: "Angi GP-oppgave:",
    enablePopup: "Aktiver sprettoppvindu"
  })
);