define(
   ({
    taskUrl: "Oppgave-URL",
    serviceURLPlaceholder: "Angi oppgave-URLen for geoprosessering",
    ok: "OK",
    cancel: "Avbryt",
    layer: "Lag",
    action: "Handling",
    input: "Inndata",
    output: "Resultat",
    name: "Navn",
    type: "Type",
    required: "Obligatorisk",
    layerOrder: "Lagrekkefølge",
    options: "Alternativer",
    defaultValue: "Standardverdi",
    inputFeatureBy: "Inndata-geoobjekter etter",
    renderer: "Opptegning",
    displayType: "Vis type",
    label: "Etikett",
    tooltip: "Verktøytips",
    visible: "Synlig",
    helpUrl: "Hjelp-URL",
    useResultMapService: "Bruk tegnealternativene fra resultatkarttjenesten",
    drawOnMap: "Interaktiv tegning på kartet",
    selectLayer: "Velge et kartlag fra kartet",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Legg til resultat som operativt kartlag",
    popup: "Sprettoppvindu",
    setTask: "Angi",
    setTaskTitle: "Angi GP-oppgave:",
    enablePopup: "Aktiver sprettoppvindu",
    unSupportGeometryType: "Kan ikke angi opptegning på grunn av ukjent geometritype.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Last opp fil",
    selectFileToUpload: "Velg fil...",
    upload: "Last opp",
    rasterFormat: "Rasterdataformat",
    noFileSelected: "Ingen fil er valgt!",
    uploadSuccess:"Filen er lastet opp.",
    showLayerContent: "Vis laginnhold",
    Feet: "fot",
    Yards: "Yards",
    Miles: "Miles",
    NauticalMiles: "Nautiske mil",
    Meter: "meter",
    Kilometers: "kilometer",
    urlPlaceholder: "geoobjektsett-URL",
    allowToExport: "Tillat eksport av resultater"
  })
);
