define(
   ({
    selectAnalysisTools:"בחר כלי ניתוח שיפורטו בוידג'ט.",
    selected: "נבחר",
    name: "שם",
    graphicalDisplay:"תצוגה גרפית",
    usage: "שימוש",
    toolNotAvailable: "כלי זה אינו זמין כיוון שהמפה אינה כוללת את שכבות הישויות הנדרשות.",
    aggregatePoints:"קבץ נקודות",
    aggregatePointsUsage:"קבץ נקודות בפוליגונים שבהם הן נמצאות.",
    aggregatePointsInputTip: "ציין את שכבת הישויות נקודתית שתקובץ בפוליגונים בשכבת ישויות הפוליגון.",
    calculateDensity:"חשב צפיפות",
    calculateDensityUsage:"צור מפת צפיפות מישויות נקודתיות או קוויות באמצעות פיזור כמותי של תופעה מסוימת (המיוצגת במאפיינים של הנקודות או הקווים) על המפה.",
    calculateDensityInputTip:"ציין את הישויות הנקודתיות או הקוויות שמהן יש לחשב את הצפיפות.",
    connectOriginsToDestinations: "חבר מקורות ליעד",
    connectOriginsToDestinationsUsage: "מדוד את זמן הנסיעה או את המרחק בין צמדי נקודות.",
    connectOriginsToDestinationsInputTip: "ציין את נקודת(ות) ההתחלה של הנתיבים שיש ליצור.",
    createBuffers:"צור חייצים",
    createBuffersUsage:"צור פוליגונים שישמשו כחיץ מישויות קלט.",
    createBuffersInputTip:"ציין את שכבת ישות הנקודה, הקו או הפוליגון שיש ליצור בה חייצים.",
    createDriveTimeAreas:"צור אזורי זמן נסיעה",
    createDriveTimeAreasUsage:"צור פוליגונים של זמן נסיעה (או מרחק נסיעה) סביב נקודות הקלט של ערכי זמן הנסיעה הנתונים.",
    createDriveTimeAreasInputTip:"ציין את הנקודות שבהן יצויירו אזורי זמן נסיעה.",
    createViewshed:"צור שטחים נצפים",
    createViewshedUsage:"יוצר אזורים נצפים בהתבסס על מיקומים שתציין.",
    createViewshedInputTip:"ציין את המיקומים שבהם נמצא הצופה כדי לזהות אזורים נצפים.",
    createWatersheds:"צור אגני ניקוז",
    createWatershedsUsage:"יוצר אזורי אגני היקוות בהתבסס על מיקומים שתגדיר.",
    createWatershedsInputTip:"הגדר את הישויות הנקודתיות המשמשות לחישוב אגני ניקוז.",
    deriveNewLocations:"גזור מיקומים חדשים",
    deriveNewLocationsUsage:"גוזר ישויות חדשות מתוך שכבות הקלט העומדות בתנאי שאילתא שהגדרת",
    deriveNewLocationsInputTip:"הגדר את שכבת הניתוח לשימוש כקלט.",
    dissolveBoundaries:"מזג גבולות",
    dissolveBoundariesUsage:"מזג פוליגונים חופפים או בעלי גבול משותף.",
    dissolveBoundariesInputTip:"ציין את השכבה הכוללת ישויות פוליגונאליות שישתתפו במיזוג.",
    enrichLayer:"העשר שכבה",
    enrichLayerUsage:"העשר ישויות קלט בנתוני אנשים ומקומות ובעובדות עסקיות על אזורים סמוכים.",
    enrichLayerInputTip:"ציין אילו ישויות יש להעשיר בנתונים החדשים.",
    extractData:"חלץ נתונים",
    extractDataDesc:"חלץ נתונים משכבה אחת או יותר בתיחום נתון",
    extractDataInputTip:"ציין איזו שכבת ישות קלט יש לחלץ.",
    findExistingLocations:"מצא מיקומים קיימים",
    findExistingLocationsUsage:"בחר ישויות בשכבת הקלט שיעמדו בתנאי שאילתת מאפיינים ו/או שאילתא מרחבית שתגדיר",
    findExistingLocationsInputTip:"ציין את שכבות הניתוח שבהן יש להשתמש כקלט.",
    findHotSpots:"מצא נקודות חמות",
    findHotSpotsUsage:"מצא אשכולות של ישויות קלט בעלי חשיבות סטטיסטית או ערכים גבוהים/נמוכים.",
    findHotSpotsInputTip:"ציין את השכבה הפוליגונאלית או הנקודתית שעבורה יחושבו נקודות חמות.",
    findNearest:"מציאת המיקום הקרוב ביותר",
    findNearestUsage:"עבור כל ישות בשכבת הקלט, מצא את הישות הקרובה אליה ביותר בשכבה אחרת",
    findNearestInputTip:"ציין את הישויות הנקודתיות, הקוויות או הפוליגונאליות שמהן יתבצא חיפוש של המיקומים הקרובים ביותר.",
    findSimilarLocations:"מצא מיקומים דומים",
    findSimilarLocationsUsage:"מדוד הדמיון של מיקומי המועמדים עבור מיקומי יחוס אחד או יותר.",
    findSimilarLocationsInputTip:"ציין שכבת ישויות הכוללת מיקום ייחוס אחד או יותר שאליו יושוו ישויות בשכבת החיפוש על מנת לזהות דמיון.",
    interpolatePoints:"‏‫בצע אינטרפולציה לנקודות",
    interpolatePointsUsage:"תוכל לחזות ערכים במיקומים חדשים בהתבסס על מדידות שיאספו מאוסף של נקודות.",
    interpolatePointsInputTip:"ציין את הישויות הנקודתיות שלהן יש לבצע אינטרפולציה.",
    mergeLayers:"מזג שכבות",
    mergeLayersUsage:"מזג ישויות משכבות רבות לשכבה חדשה",
    mergeLayersInputTip:"ציין את שכבת הישויות שאותה יש למזג בעזרת שכבת המיזוג.",
    overlayLayers:"כסה שכבות",
    overlayLayersUsage:"שלב שכבות רבות וצור מהן שכבה יחידה תוך שמירה על מידע הקיים בשכבות המקוריות.",
    overlayLayersInputTip:"ציין איזו שכבת ישויות תכוסה בשכבת הכיסוי.",
    planRoutes:"תכנן מסלולים",
    planRoutesUsage:"קבע כיצד לחלק משימות לכוח עבודה נייד ביעילות.",
    planRoutesInputTip:"ציין את הנקודות שבהן על הרכבים, הנהגים או המסלולים לעבור.",
    summarizeNearby:"סכם סמיכויות",
    summarizeNearbyUsage:"עבור כל ישות בשכבת קלט, סכם נתונים הנמצאים במרחק מסוים מישויות בשכבה אחרת.",
    summarizeNearbyInputTip:"ציין את הישות הנקודתית,הקווית או הפוליגונאלית שממנה ימדדו מרחקים לישויות בשכבת סיכום.",
    summarizeWithin:"סיכום פנימי",
    summarizeWithinUsage:"עבור כל פוליגון בשכבת הקלט הפוליגונאלית, סכם את הנתונים שהתקבלו מישויות הנמצאות בתוכה בשכבה אחרת.",
    summarizeWithinInputTip:"ציין את השכבה הפוליגונאלית שאליה יש לסכם.",
    traceDownstream:"עקוב במורד הזרם",
    traceDownstreamUsage:"קבע את נתיבי הזרימה ממיקומים שתציין במורד הזרם.",
    traceDownstreamInputTip:"ציין את הישויות הנקודתיות שישמשו כמיקום התחלתי למעקב במורד הזרם."
  })
);
