define(
   ({
    selectAnalysisTools:"בחר כלי ניתוח לשימוש בווידג\'ט.",
    selected: "נבחר",
    name: "שם",
    graphicalDisplay:"תצוגה גרפית",
    usage: "שימוש",
    settings: "הגדרות",
    toolSetting: "הגדרת פרטי כלי",
    toolLabel: "השם לתצוגה של הכלי",
    showHelpTip: "הצג קישורים לעזרה בווידג\'ט",
    showCurrentMapExtent: "הצג אפשרות להשתמש בתיחום המפה הנוכחי",
    showCredits: "הצג את האפשרות <b>הצג קרדיט</b>",
    saveAsFeatureService: "שמור את התוצאה בחשבון של המשתמש",
    showReadyToUseLayers: "הצג שכבות מוכנות לשימוש מתוך האטלס החי של העולם ב-ArcGIS Online",
    toolNotAvailable: "כלי זה אינו זמין כיוון שהמפה אינה כוללת את שכבות הישויות הנדרשות.",
    aggregatePoints:"קבץ נקודות",
    aggregatePointsUsage:"קבץ נקודות בפוליגונים שבהם הן נמצאות.",
    calculateDensity:"חשב צפיפות",
    calculateDensityUsage:"צור מפת צפיפות מישויות נקודתיות או קוויות באמצעות פיזור כמותי של תופעה מסוימת (המיוצגת במאפיינים של הנקודות או הקווים) על המפה.",
    connectOriginsToDestinations: "חבר מקורות ליעד",
    connectOriginsToDestinationsUsage: "מדוד את זמן הנסיעה או את המרחק בין צמדי נקודות.",
    createBuffers:"צור חייצים",
    createBuffersUsage:"צור פוליגונים שישמשו כחיץ מישויות קלט.",
    createDriveTimeAreas:"צור אזורי זמן נסיעה",
    createDriveTimeAreasUsage:"צור פוליגונים של זמן נסיעה (או מרחק נסיעה) סביב נקודות הקלט של ערכי זמן הנסיעה הנתונים.",
    createViewshed:"צור שטחים נצפים",
    createViewshedUsage:"יוצר אזורים נצפים בהתבסס על מיקומים שתציין.",
    createWatersheds:"צור אגני ניקוז",
    createWatershedsUsage:"יוצר אזורי אגני היקוות בהתבסס על מיקומים שתגדיר.",
    deriveNewLocations:"גזור מיקומים חדשים",
    deriveNewLocationsUsage:"גוזר ישויות חדשות מתוך שכבות הקלט העומדות בתנאי שאילתא שהגדרת",
    dissolveBoundaries:"מזג גבולות",
    dissolveBoundariesUsage:"מזג פוליגונים חופפים או בעלי גבול משותף.",
    enrichLayer:"העשר שכבה",
    enrichLayerUsage:"העשר ישויות קלט בנתוני אנשים ומקומות ובעובדות עסקיות על אזורים סמוכים.",
    extractData:"חלץ נתונים",
    extractDataDesc:"חלץ נתונים משכבה אחת או יותר בתיחום נתון",
    findExistingLocations:"מצא מיקומים קיימים",
    findExistingLocationsUsage:"בחר ישויות בשכבת הקלט שיעמדו בתנאי שאילתת מאפיינים ו/או שאילתא מרחבית שתגדיר",
    findHotSpots:"מצא נקודות חמות",
    findHotSpotsUsage:"מצא אשכולות של ישויות קלט בעלי חשיבות סטטיסטית או ערכים גבוהים/נמוכים.",
    findNearest:"מציאת המיקום הקרוב ביותר",
    findNearestUsage:"עבור כל ישות בשכבת הקלט, מצא את הישות הקרובה אליה ביותר בשכבה אחרת",
    findSimilarLocations:"מצא מיקומים דומים",
    findSimilarLocationsUsage:"מדוד הדמיון של מיקומי המועמדים עבור מיקומי יחוס אחד או יותר.",
    interpolatePoints:"‏‫בצע אינטרפולציה לנקודות",
    interpolatePointsUsage:"תוכל לחזות ערכים במיקומים חדשים בהתבסס על מדידות שיאספו מאוסף של נקודות.",
    mergeLayers:"מזג שכבות",
    mergeLayersUsage:"מזג ישויות משכבות רבות לשכבה חדשה",
    overlayLayers:"כסה שכבות",
    overlayLayersUsage:"שלב שכבות רבות וצור מהן שכבה יחידה תוך שמירה על מידע הקיים בשכבות המקוריות.",
    planRoutes:"תכנן מסלולים",
    planRoutesUsage:"קבע כיצד לחלק משימות לכוח עבודה נייד ביעילות.",
    summarizeNearby:"סכם סמיכויות",
    summarizeNearbyUsage:"עבור כל ישות בשכבת קלט, סכם נתונים הנמצאים במרחק מסוים מישויות בשכבה אחרת.",
    summarizeWithin:"סיכום פנימי",
    summarizeWithinUsage:"עבור כל פוליגון בשכבת הקלט הפוליגונאלית, סכם את הנתונים שהתקבלו מישויות הנמצאות בתוכה בשכבה אחרת.",
    traceDownstream:"עקוב במורד הזרם",
    traceDownstreamUsage:"קבע את נתיבי הזרימה ממיקומים שתציין במורד הזרם."
  })
);
