define(
   ({
    _widgetLabel: "Prindi",
    title: "Kaardi pealkiri",
    format: "Vorming",
    layout: "Paigutus",
    settings: "Täiustunud",
    mapScaleExtent: "Kaardi mõõtkava/ulatus",
    preserve: "Säilita",
    mapScale: "kaardi mõõtkava",
    mapExtent: "kaardi ulatus",
    forceScale: "Kehtesta mõõtkava",
    getCurrentScale: "praegune",
    mapMetadata: "Paigutuse metaandmed",
    author: "Autor",
    copyright: "Autoriõigus",
    fullLayoutOptions: "Kõik paigutuse valikud",
    scaleBarUnitsMetric: "Mõõtkavariba meetermõõdustiku ühikud",
    scaleBarUnitsNonMetric: "Mõõtkavariba muud kui meetermõõdustiku ühikud",
    unitsMiles: "Miili",
    unitsKilometers: "Kilomeetrit",
    unitsMeters: "Meetrit",
    unitsFeet: "Jalga",
    unitsYards: "Jardi",
    unitsNauticalMiles: "Meremiili",
    lncludeLegend: "Kaasa legend",
    printQualityOptions: "Printimise kvaliteet",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY suurus",
    width: "Laius (px)",
    height: "Kõrgus (px)",
    print: "Prindi",
    clearList: "Tühista printimine",
    creatingPrint: "Printimine",
    printError: "Viga, proovige uuesti"
  })
);