define(
   ({
    _widgetLabel: "Zapytanie",
    executeQueryTip: "Kliknij jedno z poniższych zadań, aby wykonać zapytanie.",
    invalidConfig: "Nieprawidłowa konfiguracja. Przejdź do strony Ustawienia zapytania, aby uzyskać prawidłowe wartości konfiguracji.",
    queryParams: "Opcje",
    parameters: "OPCJE",
    queries: "ZAPYTANIA",
    apply: "ZASTOSUJ",
    queryResults: "Wyniki",
    clear: "Wyczyść",
    noResults: "Nie odnaleziono żadnego obiektu.",
    queryError: "Wykonanie zapytania nie powiodło się!",
    numberFound: "Liczba znalezionych obiektów",
    mapExtentTip: "Ogranicz wyniki do obszaru bieżącej mapy.",
    noValue: "Brak wartości",
    and: "i",
    stringOperatorIs: "wynosi", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "nie równa się",
    stringOperatorStartsWith: "zaczyna się od",
    stringOperatorEndsWith: "kończy się na",
    stringOperatorContains: "zawiera",
    stringOperatorDoesNotContain: "nie zawiera",
    stringOperatorIsBlank: "jest puste",
    stringOperatorIsNotBlank: "nie jest puste",
    dateOperatorIsOn: "jest w dniu", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "nie jest w dniu",
    dateOperatorIsBefore: "jest przed",
    dateOperatorIsAfter: "jest po",
    dateOperatorDays: "dni",
    dateOperatorWeeks: "tygodni", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "miesięcy",
    dateOperatorInTheLast: "w ciągu ostatnich",
    dateOperatorNotInTheLast: "nie w ciągu ostatnich",
    dateOperatorIsBetween: "jest pomiędzy",
    dateOperatorIsNotBetween: "nie jest pomiędzy",
    dateOperatorIsBlank: "jest puste",
    dateOperatorIsNotBlank: "nie jest puste",
    numberOperatorIs: "wynosi", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "nie równa się",
    numberOperatorIsAtLeast: "równa się co najmniej",
    numberOperatorIsLessThan: "jest mniejsze niż",
    numberOperatorIsAtMost: "równa się maksymalnie",
    numberOperatorIsGreaterThan: "jest większe niż",
    numberOperatorIsBetween: "jest pomiędzy",
    numberOperatorIsNotBetween: "nie jest pomiędzy",
    numberOperatorIsBlank: "jest puste",
    numberOperatorIsNotBlank: "nie jest puste",
    operationalLayerTip: "Dodaj wynik jako warstwę operacyjną",
    queryResult: "Wynik zapytania",
    specifyParamsTip: "Określ parametry tego zadania",
    useSpatialFilter: "Użyj filtru przestrzennego, aby ograniczyć liczbę obiektów",
    useCurrentMapExtent: "Tylko obiekty, które przecinają obszar bieżącej mapy",
    drawGraphicOnMap: "Tylko obiekty, które przecinają zdefiniowany przez użytkownika obszar bieżącej mapy",
    specifySpatialFilterMsg: "Należy określić filtr przestrzenny dla tego zadania",
    clearResults: "Wyczyść wyniki",
    operationalTip: 'Jeżeli opcja ta jest zaznaczona, wyniki są wyświetlane na mapie do momentu kliknięcia przycisku \"${clearResults}\".',
    noneQueryTip: "Nie skonfigurowano żadnego zadania zapytania dla tego widżetu.",
    noPermissionsMsg: "Nie masz uprawnień dostępu do tej usługi.",
    attributesFromRelationship: "Atrybuty z powiązanej tabeli",
    tasks: "Zadania",
    applySpatialFilterToLimitResults: "Aby ograniczyć wyniki, zastosuj filtr przestrzenny",
    useCurrentExtentTip: "Częściowo lub całkowicie w bieżącym zasięgu mapy",
    useDrawGraphicTip: "Częściowo lub całkowicie w zasięgu narysowanego na mapie obszaru",
    useFeaturesTip: "Na podstawie ich lokalizacji względem obiektów na innej warstwie",
    noSpatialLimitTip: "Nie ograniczaj przestrzennie wyników wyszukiwania",
    applySearchDistance: "Zastosuj odległość wyszukiwania",
    spatialRelationship: "Zależność przestrzenna",
    relatedLayer: "Powiązana warstwa",
    bufferDistance: "Odległość buforowania",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    back: "Powrót",
    execute: "Wykonaj"
  })
);