define(
	 ({
		queries: "Frågeuppgifter",
		addNew: "Lägg till ny",
		setSource: "Ange",
		setDataSource: "Ange datakälla",
		name: "Namn",
		querySource: "Datakälla",
		queryName: "Uppgiftsnamn",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Resultatinställning",
		symbolSetting: "Symbolinställning",
		resultSettingTip: "Definiera vad som ska visas i resultaten och hur det ska visas.",
		resultItemTitle: "Resultatobjektets titel",
		resultItemContent: "Resultatobjektets innehåll",
		fieldsSetTip: "Markera de fält du vill visa. Välj ett fält om du vill uppdatera dess alias, ändra ordning och formatera det.",
		addField: "Lägg till fält",
		visibility: "Synlighet",
		alias: "Alias",
		specialType: "Särskild typ",
		actions: "Åtgärder",
		none: "Ingen",
		link: "Länk",
		image: "Bild",
		noField: "Inget fält",
		operationalLayerTip: "Lägg till resultat som funktionslager",
		setLayerSymbolTip: "Ange en symbol för frågeresultat: ",
		setSelectedSymbolTip: "Ange en symbol för det valda geoobjektet.",
		notUseFilter: "Använd inte filter",
		setSourceTip: "Ange en frågekälla.",
		setFilterTip: "Ange filtret korrekt.",
		ok: "OK",
		cancel: "Avbryt",
		noFilterTip: "Om inget filteruttryck definierats visar denna frågeuppgift en lista med alla geoobjekt i den angivna datakällan."
  })
);