define(
	 ({
		queries: "Frågeuppgifter",
		addNew: "Lägg till ny",
    queryLayer: "Frågelager",
		setSource: "Ange",
		setDataSource: "Ange datakälla",
		name: "Namn",
		querySource: "Datakälla",
		queryName: "Uppgiftsnamn",
		queryDefinition: "Filterdefinition",
		resultsSetting: "Resultatinställning",
		symbolSetting: "Symbolinställning",
		resultSettingTip: "Definiera vad som ska visas i resultaten och hur det ska visas.",
		resultItemTitle: "Resultatobjektets titel",
		resultItemContent: "Resultatobjektets innehåll",
		fieldsSetTip: "Markera de fält du vill visa. Välj ett fält om du vill uppdatera dess alias, ändra ordning och formatera det.",
		addField: "Lägg till fält",
		visibility: "Synlighet",
		alias: "Alias",
		specialType: "Särskild typ",
		actions: "Åtgärder",
		none: "Ingen",
		link: "Länk",
		image: "Bild",
		noField: "Inget fält",
		operationalLayerTip: "Lägg till resultat som funktionslager",
		setLayerSymbolTip: "Ange en symbol för frågeresultat: ",
		setSelectedSymbolTip: "Ange en symbol för det valda geoobjektet.",
		notUseFilter: "Använd inte filter",
		setSourceTip: "Ange en frågekälla.",
		setFilterTip: "Ange filtret korrekt.",
		ok: "OK",
		cancel: "Avbryt",
		noFilterTip: "Om inget filteruttryck definierats visar denna frågeuppgift en lista med alla geoobjekt i den angivna datakällan.",
    relationships: "Relationer",
    addRelationshipLayer: "Lägg till ny relation",
    relatedTo: "Relaterat till",
    selectOption: "Välj...",
    resultItemSorting: "Sortering av resultatobjekt",
    field: "Fält",
    sortingOrder: "Ordning",
    configureFieldsTip: "Konfigurera de fält som frågeresultatet ska sorteras efter.",
    setSortingFields: "Ange sorteringsfält",
    ascending: "Stigande",
    descending: "Fallande",
    sortBy: "Sortera efter",
    thenBy: "Sedan efter",
    addTask: "Lägg till uppgift",
    noTasksTip: 'Inga uppgifter, klicka på \"${addTask}\" för att sätta i gång!',
    infoText: "Info",
    filters: "Filter",
    results: "Resultat",
    optionsText: "Alternativ",
    summaryText: "Sammanfattning",
    attributeFilter: "Attributfilter",
    attributeFilterTip: "Definiera attribututtryck som kan användas i widgeten för att filtrera frågelagret.",
    noExpressionDefinedTip: "Inga uttryck har definierats.",
    needInputValuesTip: "Behöver ange värden vid körtid",
    setExpressions: "Ange uttryck",
    spatialFilter: "Geografiskt filter",
    spatialFilterTip: "Begränsa resultaten med de geografiska filter som används i widgeten.",
    defaultOption: "Standard",
    useCurrentExtentTip: "Helt eller delvis inom den aktuella kartutbredningen",
    useDrawGraphicTip: "Helt eller delvis inom den form som ritats på kartan",
    useFeaturesTip: "Baserat på deras platser relativt geoobjekt i ett annat lager",
    noSpatialLimitTip: "Begränsa inte resultaten geografiskt",
    drawingTools: "Ritverktyg",
    bufferSettings: "Buffertinställningar",
    defaultDistance: "Standarddistans",
    bufferDistance: "Buffertavstånd",
    defaultUnit: "Standardenhet",
    miles: "Engelska mil",
    kilometers: "Kilometer",
    feet: "Fot",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Nautiska mil",
    availableSpatialRelationships: "Tillgängliga geografiska relationer",
    setSpatialRelationships: "Ange geografiska relationer",
    availability: "Tillgänglighet",
    relationship: "Relation",
    label: "Etikett",
    intersect: "korsa",
    contain: "innehålla",
    areContainedIn: "ingår i",
    cross: "kors",
    envelopeIntersect: "områdesskärning",
    overlap: "överlappning",
    areOverlapped: "överlappar varandra",
    touche: "vidröra",
    within: "inom",
    areWithin: "är inom",
    indexIntersect: "indexskärning",
    itemTitle: "Titel på objektet",
    displayFields: "Visningsfält",
    sortingFields: "Sortera fält",
    setDisplayFields: "Ange visningsfält",
    symbol: "Symbol",
    setSymbol: "Ange symbol",
    serviceSymbolTip: "Använd symbolerna som definieras av lagret",
    exportTip: "Visa knappen Exportera",
    keepResultsTip: "Behåll resultaten på kartan när widgeten stängs",
    queryRelatedRecords: "Frågerelaterade poster",
    createLayerForTaskTip: "Ange hur uppgiften ska skapa lager",
    oneLayerForTaskTip: "Skapa bar ett lager för denna uppgift",
    multipleLayerForTaskTip: "Skapa ett nytt lager varje gång som uppgiften körs"
  })
);
