define(
   ({
    taskUrl: "URL de Tarefa",
    serviceURLPlaceholder: "Por favor introduza o URL de tarefa de Geoprocessamento",
    ok: "OK",
    cancel: "Cancelar",
    layer: "Camada",
    action: "Ação",
    input: "Introdução",
    output: "Saída",
    name: "Nome",
    type: "Tipo",
    required: "Exigido",
    layerOrder: "Ordem de camadas",
    options: "Opções",
    defaultValue: "Valor Padrão",
    inputFeatureBy: "Input Elemento por",
    renderer: "Renderizador",
    displayType: "Exibir tipo",
    label: "Rótulo",
    tooltip: "Dica de Ferramenta",
    visible: "Visível",
    helpUrl: "URL de Ajuda",
    useResultMapService: "Utilize as opções de desenho do serviço de mapa resultante",
    drawOnMap: "Desenhando no mapa de forma interativa",
    selectLayer: "Selecionando uma camada no mapa",
    url: "URL",
    symbol: "Símbolo",
    shareResults: "Adicionar resultado como camada operacional",
    popup: "Janela popup",
    setTask: "Definir",
    setTaskTitle: "Definir Tarefa GP",
    enablePopup: "Ativar janelas popup"
  })
);