define(
   ({
    _widgetLabel: "报表要素",
    select: "选择",
    draw: "绘制",
    chooseALayer: "选择图层",
    clickAFeature: "单击地图上的要素以将其选中。",
    loadingFeatures: "获取所选要素的详细信息...",
    errorTitle: "错误",
    errorIdentify: "识别要素错误。请检查控制台日志以获取详细信息。",
    infoWindowTitle: "详细信息",
    layerLabel: "图层名称",
    reviewStatusLabel: "检查状态",
    selectReviewStatusAdd: "添加要素",
    selectReviewStatusDelete: "删除要素",
    selectReviewStatusMove: "移动要素",
    selectReviewStatusReshape: "整形要素",
    drawReviewStatusMissing: "缺少要素",
    drawReviewStatusPosition: "定位错误",
    drawReviewStatusShape: "形状错误",
    drawReviewStatusAttribute: "属性错误",
    notesLabel: "注意事项",
    severityLabel: "严重性",
    reportedByLabel: "报告者",
    reportedByDefault: "匿名",
    reportButton: "报告",
    reportMessage: "接收到的报告",
    errorReportMessage: "报告要素时出错",
    drawErrorInstructions: "选择点、线或面并在地图上绘制错误几何:",
    errorMapService: "获取地图服务信息时出错",
    noFeatureSelected : "未在单击的位置发现要素",
    selectFeatureMapPoint: "单击以选择要素",
    drawFeatureMapPoint: "单击以添加点",
    popupMessage:"消息",
    popupError:"错误",
    manyFeaturesSelected: "发现了多个要素。请放大并选择要报告的要素。"
  })
);
