define(
   ({
    _widgetLabel: "Consulta",
    executeQueryTip: "Clique num dos seguintes itens de tarefas para executar a consulta.",
    invalidConfig: "Configuração inválida. Por favor utilize a página de definições de Consulta para obter a configuração correta.",
    queryParams: "Parâmetros de Consulta",
    parameters: "Parâmetros",
    queries: "Consultas",
    apply: "Aplicar",
    queryResults: "Resultados de Consulta",
    clear: "Limpar",
    noResults: "Nenhum resultado",
    queryError: "Consulta falhou !",
    numberFound: "Número de elementos encontrados",
    mapExtentTip: "Limitar os resultados à atual extensão de mapa",
    noValue: "Sem valores",
    and: "e",
    stringOperatorIs: "é", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "não é",
    stringOperatorStartsWith: "começa por",
    stringOperatorEndsWith: "acaba em",
    stringOperatorContains: "contém",
    stringOperatorDoesNotContain: "não contém",
    stringOperatorIsBlank: "está vazio",
    stringOperatorIsNotBlank: "não está vazio",
    dateOperatorIsOn: "é em", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "não é em",
    dateOperatorIsBefore: "é anterior a",
    dateOperatorIsAfter: "é posterior a",
    dateOperatorDays: "dias",
    dateOperatorWeeks: "semanas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "meses",
    dateOperatorInTheLast: "nos(as) últimos(as)",
    dateOperatorNotInTheLast: "não nos(as) últimos(as)",
    dateOperatorIsBetween: "é entre",
    dateOperatorIsNotBetween: "não é entre",
    dateOperatorIsBlank: "está vazio",
    dateOperatorIsNotBlank: "não está vazio",
    numberOperatorIs: "é", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "não é",
    numberOperatorIsAtLeast: "é no mínimo",
    numberOperatorIsLessThan: "é inferior a",
    numberOperatorIsAtMost: "é no máximo",
    numberOperatorIsGreaterThan: "é superior a",
    numberOperatorIsBetween: "é entre",
    numberOperatorIsNotBetween: "não é entre",
    numberOperatorIsBlank: "está vazio",
    numberOperatorIsNotBlank: "não está vazio",
    operationalLayerTip: "Adicionar resultado como camada operacional",
    queryResult: "Resultado da Consulta",
    specifyParamsTip: "Especificar parâmetros para esta tarefa",
    useSpatialFilter: "Utilizar filtro espacial para limitar elementos",
    useCurrentMapExtent: "Apenas elementos que tocam a atual extensão to mapa",
    drawGraphicOnMap: "Apenas elementos que tocam uma área definida pelo utilizador",
    specifySpatialFilterMsg: "Por favor especifique um filtro espacial para esta tarefa.",
    clearResults: "Limpar Resultados",
    operationalTip: 'Com esta opção ativa, os resultados serão guardados no mapa até que o botão \"${clearResults}\" seja clicado.',
    noneQueryTip: "Não se encontram disponíveis quaisquer tarefas de consulta pré-configuradas.",
    noPermissionsMsg: "Não possui permissões para aceder a este serviço."
  })
);