define(
   ({
    _widgetLabel: "Consulta",
    executeQueryTip: "Clique num dos seguintes itens de tarefas para executar a consulta.",
    invalidConfig: "Configuração inválida. Por favor utilize a página de definições de Consulta para obter a configuração correta.",
    queryParams: "Parâmetros de Consulta",
    parameters: "Parâmetros",
    queries: "Consultas",
    apply: "Aplicar",
    queryResults: "Resultados de Consulta",
    clear: "Limpar",
    noResults: "Nenhum resultado",
    queryError: "Consulta falhou !",
    numberFound: "Número de elementos encontrados",
    mapExtentTip: "Limitar os resultados da área de mapa actual.",
    noValue: "Sem valores",
    and: "e",
    stringOperatorIs: "é", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "não é",
    stringOperatorStartsWith: "começa por",
    stringOperatorEndsWith: "acaba em",
    stringOperatorContains: "contém",
    stringOperatorDoesNotContain: "não contém",
    stringOperatorIsBlank: "está vazio",
    stringOperatorIsNotBlank: "não está vazio",
    dateOperatorIsOn: "é em", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "não é em",
    dateOperatorIsBefore: "é anterior a",
    dateOperatorIsAfter: "é posterior a",
    dateOperatorDays: "dias",
    dateOperatorWeeks: "semanas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "meses",
    dateOperatorInTheLast: "nos(as) últimos(as)",
    dateOperatorNotInTheLast: "não nos(as) últimos(as)",
    dateOperatorIsBetween: "é entre",
    dateOperatorIsNotBetween: "não é entre",
    dateOperatorIsBlank: "está vazio",
    dateOperatorIsNotBlank: "não está vazio",
    numberOperatorIs: "é", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "não é",
    numberOperatorIsAtLeast: "é no mínimo",
    numberOperatorIsLessThan: "é inferior a",
    numberOperatorIsAtMost: "é no máximo",
    numberOperatorIsGreaterThan: "é superior a",
    numberOperatorIsBetween: "é entre",
    numberOperatorIsNotBetween: "não é entre",
    numberOperatorIsBlank: "está vazio",
    numberOperatorIsNotBlank: "não está vazio",
    operationalLayerTip: "Adicionar resultado como camada operacional",
    queryResult: "Resultado da Consulta",
    specifyParamsTip: "Especificar parâmetros para esta tarefa",
    useSpatialFilter: "Utilizar filtro espacial para limitar elementos",
    useCurrentMapExtent: "Apenas elementos intersectam área de mapa actual",
    drawGraphicOnMap: "Apenas elementos intersectam a área definida por utilizador",
    specifySpatialFilterMsg: "Por favor especifique um filtro espacial para esta tarefa.",
    clearResults: "Limpar Resultados",
    operationalTip: 'Com esta opcção validada, os resultados serão mantidos no mapa até o botão \"${clearResults}\" ser clicado.',
    noneQueryTip: "Não foi configurada qualquer tarefa de consulta para este widget.",
    noPermissionsMsg: "Não possui permissões para aceder a este serviço.",
    attributesFromRelationship: "Atributos de tabela relacionada",
    tasks: "Tarefas",
    applySpatialFilterToLimitResults: "Aplique um filtro espacial para limitar os resultados",
    useCurrentExtentTip: "Parcialmente ou totalmente no contido na atual extensão de mapa",
    useDrawGraphicTip: "Parcialmente ou totalmente no contido na forma desenhada no mapa",
    useFeaturesTip: "Baseado nas respetivas localizações em relação a elementos noutra camada",
    noSpatialLimitTip: "Não limita resultados espacialmente",
    applySearchDistance: "Aplique uma distância de pesquisa",
    spatialRelationship: "Relação Espacial",
    relatedLayer: "Camada Relacionada",
    bufferDistance: "Distância do Buffer",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    back: "Retroceder",
    execute: "Executar"
  })
);