define(
   ({
    _widgetLabel: "Incidentanalys",
    incident: "Händelse",
    weather: "Väder",
    locate_incident: "Hitta incident",
    clear_incidents: "Rensa incidenter",
    reverse_geocoded_address: "Närmaste adress",
    reverse_geocoded_error: "Inte tillgänglig",
    miles: "Engelska mil",
    kilometers: "Kilometer",
    feet: "Fot",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Nautiska mil",
    now: "NU",
    wind: "VIND",
    SUN: "SÖN",
    MON: "MÅN",
    TUE: "TIS",
    WED: "ONS",
    THU: "TOR",
    FRI: "FRE",
    SAT: "LÖR",
    defaultTabMsg: "Inga incidenter har identifierats.",
    actionLabel: "Ange som incident",
    useMapExtent: "Använd aktuell kartutbredning",
    noFeaturesFound: "Hittade inga objekt.",
    downloadCSV: "HÄMTA CSV",
    sum: "SUMMA",
    min: "MIN",
    max: "MAX",
    avg: "SNITT",
    count: "ANTAL",
    area: "AREA",
    length: "LÄNGD"
  })
);
