define(
   ({
    "tabs_section_Label": "Tab",
    "addTab": "Thêm Tab",
    "layerName": "Lớp",
    "layerType": "Loại Phân tích",
    "layerLabel": "Nhãn",
    "actions": "Các hành động",
    "closest": "Đối tượng Gần nhất",
    "proximity": "Vùng lân cận",
    "summary": "Tóm tắt",
    "select_lbl": "-- Chọn --",
    "general_setting_Label": "Thiết lập Tổng quan",
    "units_text_lbl": "Đơn vị Khoảng cách",
    "miles": "Dặm",
    "kilometers": "Kilômét",
    "feet": "Bộ",
    "meters": "Mét",
    "yards": "Thước",
    "nauticalMiles": "Hải lý",
    "maximum_distance_lbl": "Khoảng cách Tối đa Đối tượng Gần nhất",
    "buffer_text_lbl": "Nhãn Vùng đệm",
    "buffer_lbl": "Khoảng cách Vùng đệm",
    "buffer_max_lbl": "Khoảng cách Vùng đệm Tối đa",
    "buffer_min_lbl": "Khoảng cách Vùng đệm Tối thiểu",
    "routing_checkBox": "Bật Định tuyến",
    "weather_Label": "Tùy chọn Thời tiết",
    "weather_checkBox": "Bao gồm Thông tin Thời tiết",
    "selectLayers": "Chọn Lớp Thời tiết",
    "currentlySelectedLayer": "Các lớp thời tiết đang được chọn",
    "missingTabLabel": "Ít nhất một lớp đang bị thiếu nhãn",
    "cancel": "Hủy",
    "ok": "Ok",
    "missingLayerInWebMap": "Không tìm thấy lớp hoạt động nào.",
    "selectFields": "Chọn Trường",
    "addField": "Thêm Trường",
    "sum": "TỔNG",
    "min": "TỐI THIỂU",
    "max": "Tối đa",
    "avg": "TRUNG BÌNH",
    "count": "SỐ LƯỢNG",
    "area": "DIỆN TÍCH",
    "length": "ĐỘ DÀI",
    "count_checkBox": "Hiển thị Số lượng",
    "area_checkBox": "Hiển thị Diện tích",
    "length_checkBox": "Hiển thị Độ dài",
    "max_records": "Giới hạn tối đa đã đạt đến"
  })
);
