define(
	 ({
		charts: "รายการแผนภูมิ",
		addNew: "เพิ่มใหม่",
		addNewTip: "เพิ่มรายการแผนภูมิใหม่",
		name: "ชื่อ",
		set: "ตั้งค่า",
		setDataSource: "ตั้งค่าแหล่งข้อมูล",
		generalSettingsTip: "ตั้งค่าแหล่งข้อมูล ชื่อเรื่องและคำอธิบายของแผนภูมิ",
		chartModeSettingTip: "เลือกวิธีในการวิเคราะห์และแสดงข้อมูลเป็นแผนภูมิ",
		detailsSettingTip: "ตั้งค่าการแสดงแผนภูมิโดยการระบุประเภทและสี และข้อมูลที่จะนำไปสร้างแผนภูมิ",
		symbolSettingTip: "ตั้งค่าการแสดงแผนที่สำหรับข้อมูลที่จะสร้างแผนภูมิ",
		addFilterTip: "เพิ่มตัวกรองให้กับข้อมูลนี้",
		dataSource: "แหล่งข้อมูล",
		noResults: "ไม่มีผลลัพธ์",
		chartTitle: "ชื่อแผนภูมิ",
		description: "คำอธิบาย",
		chartingMode: "ผลการแสดงแผนภูมิ",
		featureOption: "แสดงค่าฟีเจอร์ต่อฟีเจอร์",
		categoryOption: "แสดงค่าโดยหมวดหมู่",
		countOption: "แสดงจำนวนฟีเจอร์โดยหมวดหมู่",
		fieldOption: "แสดงค่าเชิงประกอบด้วยแผนภูมิ",
		category: "หมวดหมู่",
		axisLabel: "ข้อความของหมวดหมู่",
		categoryField: "ฟิลด์หมวดหมู่",
		operation: "ดำเนินการ",
		originalOption: "ใช้ค่าเริ่มต้น",
		sumOption: "ผลรวม",
		averageOption: "ค่าเฉลี่ย",
		minOption: "ค่าน้อยที่สุด",
		maxOption: "ค่ามากที่สุด",
		valueFields: "ตั้งค่าฟิลด์",
		moveUp: "เลื่อนขึ้น",
		moveDown: "เลื่อนลง",
		sortOrder: "เรียงลำดับแผนภูมิตามชื่อหมวดหมู่",
		ascending: "เรียงจากน้อยไปมาก",
		descending: "เรียงจากมากไปน้อย",
		chartType: "ประเภทแผนภูมิ",
		column: "ตอลัมน์ของแผนภูมิ",
		bar: "แผนภูมิแท่ง",
		line: "แผนภูมิเส้น",
		pie: "แผนภูมิวงกลม",
		chartColor: "สีแผนภูมิ",
		showDataLabels: "แสดงชื่อของข้อมูล",
		setSymbol: "การเลือกสัญลักษณ์",
		setHighLightColor: "สีเน้น",
		settings: "การตั้งค่า",
		mapInterationOptions: "ตัวเลือกการตอบสนองแผนที่",
		preview: "ตัวอย่าง",
		ok: "ตกลง",
		cancel: "ยกเลิก",
		close: "ปิด",
		setFilterTip: "โปรดตั้งค่าตัวกรองให้ถูกต้อง ",
		setChartTitleTip: "โปรดตั้งค่าชื่อแผนภูมิ",
		setChartTypeTip: "โปรดเลือกแผนภูมิอย่างน้อย 1 แผนภูมิ",
		setDataFieldTip: "โปรดเลือกฟิลด์อย่างน้อย 1 ฟิลด์",
		setOutputFieldTip: "โปรดตั้งค่าฟิลด์ผลลัพธ์",
		count: "นับ",
		label: "ตัวอักษร",
		horizontalAxis: "แกนระนาบ",
		verticalAxis: "แกนดิ่ง",
		dataLabels: "ชื่อข้อมูล",
		color: "สี",
		colorful: "สีสัน",
		monochromatic: "โมโนโครมาติก"
  })
);