define(
	 ({
		chartTasks: "รายการแผนภูมิ",
		addNew: "เพิ่มใหม่",
		addNewTip: "เพิ่มรายการแผนภูมิใหม่",
		name: "ชื่อ",
		set: "ตั้งค่า",
		setDataSource: "ตั้งค่าแหล่งข้อมูล",
		generalSettingsTip: "ตั้งค่าแหล่งข้อมูล ชื่อเรื่องและคำอธิบายของแผนภูมิ",
		chartModeSettingTip: "เลือกวิธีในการวิเคราะห์และแสดงข้อมูลเป็นแผนภูมิ",
		detailsSettingTip: "ระบุลักษณะของแผนภูมิ  โดยการระบุประเภท สี และค่าตัวแปรที่ต้องการให้แสดงแผนภูมิ",
		symbolSettingTip: "ตั้งค่าการแสดงแผนที่สำหรับข้อมูลที่จะสร้างแผนภูมิ",
		addFilterTip: "เพิ่มตัวกรองให้กับข้อมูลนี้",
		dataSource: "แหล่งข้อมูล",
		noResults: "ไม่มีผลลัพธ์",
		chartTitle: "ชื่อแผนภูมิ",
		description: "คำอธิบาย",
		chartingMode: "ผลการแสดงแผนภูมิ",
		featureOption: "แสดงค่าฟีเจอร์ต่อฟีเจอร์",
		categoryOption: "แสดงค่าโดยหมวดหมู่",
		countOption: "แสดงจำนวนฟีเจอร์โดยหมวดหมู่",
		fieldOption: "แสดงค่าเชิงประกอบด้วยแผนภูมิ",
		category: "หมวดหมู่",
		axisLabel: "ข้อความของหมวดหมู่",
		categoryField: "ฟิลด์หมวดหมู่",
		operation: "ดำเนินการ",
		originalOption: "ใช้ค่าเริ่มต้น",
		sumOption: "ผลรวม",
		averageOption: "ค่าเฉลี่ย",
		minOption: "ค่าน้อยที่สุด",
		maxOption: "ค่ามากที่สุด",
		valueFields: "ตั้งค่าฟิลด์",
		moveUp: "เลื่อนขึ้น",
		moveDown: "เลื่อนลง",
		sortOrder: "เรียงลำดับแผนภูมิตามชื่อหมวดหมู่",
		ascending: "เรียงจากน้อยไปมาก",
		descending: "เรียงจากมากไปน้อย",
		chartType: "ประเภทแผนภูมิ",
		column: "ตอลัมน์ของแผนภูมิ",
		bar: "แผนภูมิแท่ง",
		line: "แผนภูมิเส้น",
		pie: "แผนภูมิวงกลม",
		chartColor: "สีแผนภูมิ",
		showDataLabels: "แสดงชื่อของข้อมูล",
		setSymbol: "การเลือกสัญลักษณ์",
		setHighLightColor: "สีเน้น",
		settings: "การตั้งค่า",
		mapInterationOptions: "ตัวเลือกการตอบสนองแผนที่",
		preview: "ตัวอย่าง",
		ok: "ตกลง",
		cancel: "ยกเลิก",
		close: "ปิด",
		setFilterTip: "โปรดตั้งค่าตัวกรองให้ถูกต้อง ",
		setChartTitleTip: "โปรดตั้งค่าชื่อแผนภูมิ",
		setChartTypeTip: "โปรดเลือกแผนภูมิอย่างน้อย 1 แผนภูมิ",
		setDataFieldTip: "โปรดเลือกฟิลด์อย่างน้อย 1 ฟิลด์",
		setOutputFieldTip: "โปรดตั้งค่าฟิลด์ผลลัพธ์",
		count: "นับ",
		label: "ตัวอักษร",
		horizontalAxis: "แกนระนาบ",
		verticalAxis: "แกนดิ่ง",
		dataLabels: "ชื่อข้อมูล",
		color: "สี",
		colorful: "สีสัน",
		monochromatic: "โมโนโครมาติก",
    noTaskTip: "คลิกเพื่อเพิ่มแผนภูมิใหม่",
    info: "ข้อมูล",
    charts: "แผนภูมิ",
    options: "ตัวเลือก",
    taskName: "ชื่อคำถาม",
    summary: "สรุป",
    resultDescription: "คำอธิบายผล",
    spatialFilterTip: "เลือกตัวกรองเชิงพื้นที่ (s) ที่ใช้ในเครื่องมือเพื่อจำกัดผลการค้นหา",
    defaultOption: "ค่าตั้งต้น",
    useCurrentExtentTip: "บางส่วนหรือทั้งหมดที่อยู่ภายในขอบเขตแผนที่ปัจจุบัน",
    useDrawGraphicTip: "บางส่วนหรือทั้งหมดที่อยู่ภายในภาพบนแผนที่",
    useFeaturesTip: "ขึ้นอยู่กับตำแหน่งที่ตั้งที่สัมพันธ์กับลักษณะการทำงานในเลเยอร์อื่น",
    noSpatialLimitTip: "ไม่จำกัดผลการค้นหาตำแหน่ง",
    drawingTools: "เครื่องมือสำหรับวาด",
    bufferSettings: "การตั้งค่าบัฟเฟอร์",
    defaultDistance: "ระยะเริ่มต้น",
    bufferDistance: "ระยะทางขยายออกไป",
    defaultUnit: "หน่วยเริ่มต้น",
    miles: "ไมล์",
    kilometers: "กิโลเมตร",
    feet: "ฟุต",
    meters: "เมตร",
    yards: "หลา",
    nauticalMiles: "ไมล์ทะเล",
    availableSpatialRelationships: "ความสัมพันธ์เชิงพื้นที่ที่เหมาะสม",
    setSpatialRelationships: "ตั้งค่าความสัมพันธ์เชิงพื้นที่",
    availability: "สภาพพร้อมใช้งาน",
    relationship: "ความสัมพันธ์",
    actions: "การดำเนินการ",
    intersect: "ทับกัน",
    contain: "ประกอบด้วย",
    areContainedIn: "ที่มีอยู่ใน",
    cross: "กากบาท",
    envelopeIntersect: "ขอบเขตของกรอบทับกัน",
    overlap: "ทับซ้อนกัน",
    areOverlapped: "มีการซ้อนทับกัน",
    touche: "สัมผัส",
    within: "ภายใน",
    areWithin: "ที่อยู่ภายใน",
    indexIntersect: "อินเดกซ์ทับกัน"
  })
);