define(
	 ({
		chartTasks: "Kaaviotehtävät",
		addNew: "Lisää uusi",
		addNewTip: "Lisää uusi kaaviotehtävä",
		name: "Nimi",
		set: "Aseta",
		setDataSource: "Määritä aineistolähde",
		generalSettingsTip: "Määritä kaavioiden aineistolähde, otsikko ja kuvaus.",
		chartModeSettingTip: "Valitse tapa, jolla tiedot analysoidaan ja näytetään kaavioina.",
		detailsSettingTip: "Määritä kaavion ulkoasu määrittämällä kaavion tyyppi ja väri sekä kaavioon sisällytettävät arvot:",
		symbolSettingTip: "Määritä kartta kaaviotietojen näyttämistä varten.",
		addFilterTip: "Lisää tietoihin suodatin",
		dataSource: "Tietolähde",
		noResults: "Kohdetta ei löytynyt.",
		chartTitle: "Kaavion otsikko",
		description: "Kuvaus",
		chartingMode: "Kaavion näyttö",
		featureOption: "Näytä arvot kohteittain",
		categoryOption: "Näytä arvot luokittain",
		countOption: "Näytä kohdemäärät luokittain",
		fieldOption: "Näytä ominaisuustietoarvot kaavioina",
		category: "Luokka",
		axisLabel: "Luokan tunnusteksti",
		categoryField: "Luokkakenttä",
		operation: "Toiminto",
		originalOption: "Käytä alkuperäisiä arvoja",
		sumOption: "Summa",
		averageOption: "Keskiarvo",
		minOption: "Minimi",
		maxOption: "Enimmäisarvo",
		valueFields: "Luokituskenttät",
		moveUp: "Siirrä ylös",
		moveDown: "Siirrä alas",
		sortOrder: "Järjestä kaaviot luokan tunnustekstin mukaan",
		ascending: "Nouseva",
		descending: "Laskeva",
		chartType: "Kaavion tyyppi",
		column: "Sarakekaavio",
		bar: "Palkkikaavio",
		line: "Viivakaavio",
		pie: "Ympyräkaavio",
		chartColor: "Kaavion väri",
		showDataLabels: "Näytä tietojen tunnustekstit",
		setSymbol: "Valintasymboli",
		setHighLightColor: "Korostusväri",
		settings: "Asetukset",
		mapInterationOptions: "Kartan vuorovaikutteisuusasetukset",
		preview: "Esikatselu",
		ok: "OK",
		cancel: "Peruuta",
		close: "Sulje",
		setFilterTip: "Määritä suodatin oikein. ",
		setChartTitleTip: "Määritä kaavion otsikko.",
		setChartTypeTip: "Valitse vähintään yksi kaaviotyyppi.",
		setDataFieldTip: "Valitse vähintään yksi arvokenttä.",
		setOutputFieldTip: "Määritä tuloskentät",
		count: "Lukumäärä",
		label: "Tunnusteksti",
		horizontalAxis: "Vaaka-akseli",
		verticalAxis: "Pystyakseli",
		dataLabels: "Tietojen tunnustekstit",
		color: "Väri",
		colorful: "Värikäs",
		monochromatic: "Yksivärinen",
    noTaskTip: "Lisää kaaviotehtävä napsauttamalla Lisää uusi -vaihtoehtoa",
    info: "Tiedot",
    charts: "Kaaviot",
    options: "Valinnat",
    taskName: "Tehtävän nimi",
    summary: "Yhteenveto",
    resultDescription: "Tuloksen kuvaus",
    spatialFilterTip: "Valitse sijaintisuodattimet, joita käytetään pienoisohjelmassa tulosten rajoittamiseen.",
    defaultOption: "Oletus",
    useCurrentExtentTip: "Osittain tai kokonaan nykyisessä karttalaajuudessa",
    useDrawGraphicTip: "Osittain tai kokonaan karttaan piirretyn muodon sisällä",
    useFeaturesTip: "Niiden sijaintien perusteella suhteessa toisen karttatason kohteisiin",
    noSpatialLimitTip: "Älä rajoita tuloksia sijaintitietojen mukaan",
    drawingTools: "Piirtotyökalut",
    bufferSettings: "Puskurin asetukset",
    defaultDistance: "Oletusetäisyys",
    bufferDistance: "Puskurin etäisyys",
    defaultUnit: "Oletusyksikkö",
    miles: "Mailia",
    kilometers: "Kilometriä",
    feet: "Jalka",
    meters: "Metriä",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    availableSpatialRelationships: "Käytettävissä olevat sijaintisuhteet",
    setSpatialRelationships: "Määritä sijaintisuhteet",
    availability: "Saatavuus",
    relationship: "Suhde",
    actions: "Toimet",
    intersect: "leikkaa",
    contain: "sisältää",
    areContainedIn: "sisältyvät",
    cross: "risti",
    envelopeIntersect: "rajojen leikkaus",
    overlap: "limittyy",
    areOverlapped: "on päällekkäin",
    touche: "koskettaa",
    within: "sisässä",
    areWithin: "on sisässä",
    indexIntersect: "indeksin leikkaus"
  })
);