define(
	 ({
		charts: "Kaaviotehtävät",
		addNew: "Lisää uusi",
		addNewTip: "Lisää uusi kaaviotehtävä",
		name: "Nimi",
		set: "Aseta",
		setDataSource: "Määritä aineistolähde",
		generalSettingsTip: "Määritä kaavioiden aineistolähde, otsikko ja kuvaus.",
		chartModeSettingTip: "Valitse tapa, jolla tiedot analysoidaan ja näytetään kaavioina.",
		detailsSettingTip: "Määritä kaavion ulkoasu määrittämällä kaavion tyyppi ja väri sekä kaavioon sisällytettävät arvot.",
		symbolSettingTip: "Määritä kartta kaaviotietojen näyttämistä varten.",
		addFilterTip: "Lisää tietoihin suodatin",
		dataSource: "Tietolähde",
		noResults: "Kohdetta ei löytynyt.",
		chartTitle: "Kaavion otsikko",
		description: "Kuvaus",
		chartingMode: "Kaavion näyttö",
		featureOption: "Näytä arvot kohteittain",
		categoryOption: "Näytä arvot luokittain",
		countOption: "Näytä kohdemäärät luokittain",
		fieldOption: "Näytä ominaisuustietoarvot kaavioina",
		category: "Luokka",
		axisLabel: "Luokan tunnusteksti",
		categoryField: "Luokkakenttä",
		operation: "Toiminto",
		originalOption: "Käytä alkuperäisiä arvoja",
		sumOption: "Summa",
		averageOption: "Keskiarvo",
		minOption: "Minimi",
		maxOption: "Enimmäisarvo",
		valueFields: "Luokituskenttät",
		moveUp: "Siirrä ylös",
		moveDown: "Siirrä alas",
		sortOrder: "Järjestä kaaviot luokan tunnustekstin mukaan",
		ascending: "Nouseva",
		descending: "Laskeva",
		chartType: "Kaavion tyyppi",
		column: "Sarakekaavio",
		bar: "Palkkikaavio",
		line: "Viivakaavio",
		pie: "Ympyräkaavio",
		chartColor: "Kaavion väri",
		showDataLabels: "Näytä tietojen tunnustekstit",
		setSymbol: "Valintasymboli",
		setHighLightColor: "Korostusväri",
		settings: "Asetukset",
		mapInterationOptions: "Kartan vuorovaikutteisuusasetukset",
		preview: "Esikatselu",
		ok: "OK",
		cancel: "Peruuta",
		close: "Sulje",
		setFilterTip: "Määritä suodatin oikein. ",
		setChartTitleTip: "Määritä kaavion otsikko.",
		setChartTypeTip: "Valitse vähintään yksi kaaviotyyppi.",
		setDataFieldTip: "Valitse vähintään yksi arvokenttä.",
		setOutputFieldTip: "Määritä tuloskentät",
		count: "Lukumäärä",
		label: "Tunnusteksti",
		horizontalAxis: "Vaaka-akseli",
		verticalAxis: "Pystyakseli",
		dataLabels: "Tietojen tunnustekstit",
		color: "Väri",
		colorful: "Värikäs",
		monochromatic: "Yksivärinen"
  })
);