define(
   ({
    _widgetLabel: "Kysely",
    executeQueryTip: "Suorita kysely napsauttamalla jotakin seuraavista tehtäväkohteista.",
    invalidConfig: "Virheellinen konfigurointi. Korjaa konfigurointi kyselyn asetussivulla.",
    queryParams: "Valinnat",
    parameters: "VALINNAT",
    queries: "KYSELYT",
    apply: "KÄYTÄ",
    queryResults: "Tulokset",
    clear: "Tyhjennä",
    noResults: "Kohdetta ei löytynyt.",
    queryError: "Kysely epäonnistui !",
    numberFound: "Löydettyjen kohteiden lukumäärä",
    mapExtentTip: "Rajoita tulokset nykyiselle kartan laajuudelle.",
    noValue: "Ei arvoa",
    and: "ja",
    stringOperatorIs: "on", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ei ole",
    stringOperatorStartsWith: "alkaa merkillä",
    stringOperatorEndsWith: "päättyy merkkiin",
    stringOperatorContains: "sisältää",
    stringOperatorDoesNotContain: "ei sisällä",
    stringOperatorIsBlank: "on tyhjä",
    stringOperatorIsNotBlank: "ei ole tyhjä",
    dateOperatorIsOn: "on päällä", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ei ole päällä",
    dateOperatorIsBefore: "on ennen",
    dateOperatorIsAfter: "on jälkeen",
    dateOperatorDays: "päivää",
    dateOperatorWeeks: "viikkoa", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "kuukautta",
    dateOperatorInTheLast: "viimeisessä",
    dateOperatorNotInTheLast: "ei viimeisessä",
    dateOperatorIsBetween: "on välillä",
    dateOperatorIsNotBetween: "ei ole välillä",
    dateOperatorIsBlank: "on tyhjä",
    dateOperatorIsNotBlank: "ei ole tyhjä",
    numberOperatorIs: "on", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ei ole",
    numberOperatorIsAtLeast: "on vähintään",
    numberOperatorIsLessThan: "on vähemmän kuin",
    numberOperatorIsAtMost: "on enintään",
    numberOperatorIsGreaterThan: "on suurempi kuin",
    numberOperatorIsBetween: "on välillä",
    numberOperatorIsNotBetween: "ei ole välillä",
    numberOperatorIsBlank: "on tyhjä",
    numberOperatorIsNotBlank: "ei ole tyhjä",
    operationalLayerTip: "Lisää tulos toiminnalliseksi karttatasoksi",
    queryResult: "Kyselytulos",
    specifyParamsTip: "Määritä tehtävän parametrit",
    useSpatialFilter: "Rajoita kohteita käyttämällä sijaintisuodatinta",
    useCurrentMapExtent: "Vain nykyisen kartan laajuuteen ulottuvat kohteet.",
    drawGraphicOnMap: "Vain käyttäjän määrittämään alueeseen ulottuvat kohteet",
    specifySpatialFilterMsg: "Määritä tehtävän sijaintisuodatin.",
    clearResults: "Tyhjennä tulokset",
    operationalTip: 'Kun tämä vaihtoehto on valittuna, tulokset näkyvät kartassa, kunnes painiketta ${clearResults} napsautetaan.',
    noneQueryTip: "Käytettävissä ei ole ennalta määritettyjä kyselytehtäviä.",
    noPermissionsMsg: "Sinulla ei ole palvelun käyttöoikeutta."
  })
);