define(
   ({
    "tabs_section_Label": "Guias",
    "addTab": "Adicionar Guia",
    "layerName": "Camada",
    "layerType": "Tipo de Análise",
    "layerLabel": "Rótulo",
    "actions": "Ações",
    "closest": "Feição Mais Próxima",
    "proximity": "Proximidade",
    "summary": "Resumo",
    "select_lbl": "-- Selecionar --",
    "general_setting_Label": "Configurações Gerais",
    "units_text_lbl": "Unidades de Distância",
    "miles": "Milhas",
    "kilometers": "Quilômetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas Náuticas",
    "maximum_distance_lbl": "Distância Máxima da Feição Mais Próxima",
    "buffer_text_lbl": "Rótulo do Buffer",
    "buffer_lbl": "Distância do Buffer",
    "buffer_max_lbl": "Distância Máxima do Buffer",
    "buffer_min_lbl": "Distância Mínima do Buffer",
    "routing_checkBox": "Habilitar Rota",
    "weather_Label": "Opções de Tempo",
    "weather_checkBox": "Incluir Informações de Tempo",
    "selectLayers": "Selecionar Camadas de Tempo",
    "currentlySelectedLayer": "Camadas de tempo atualmente selecionadas",
    "missingTabLabel": "Pelo menos uma guia está sem rótulo",
    "cancel": "Cancelar",
    "ok": "OK",
    "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
    "selectFields": "Selecionar Campos",
    "addField": "Adicionar Campo",
    "sum": "SOMA",
    "min": "MÍN",
    "max": "MÁX",
    "avg": "MÉDIA",
    "count": "CONTAGEM",
    "area": "ÁREA",
    "length": "COMPRIMENTO",
    "count_checkBox": "Mostrar Contagem",
    "area_checkBox": "Mostrar Área",
    "length_checkBox": "Mostrar Comprimento",
    "max_records": "Limite máximo alcançado",
    "save_label": "Opções de Salvar",
    "save_checkbox": "Habilitar Salvar",
    "csv_label": "Opções do CSV",
    "csv_checkbox": "Exportar todos os campos na camada.",
    "display_label": "Opções de Visualização",
    "display_checkbox": "Exibir Feições de Resumo",
    "must_select_template": "Selecione um dos modelos de edição em Opções de Salvar."
  })
);
