define(
   ({
    _widgetLabel: "Imprimer",
    title: "Titre de la carte",
    format: "Format",
    layout: "Mise en page",
    settings: "Avancé",
    mapScaleExtent: "Echelle/étendue de la carte",
    preserve: "Conserver",
    mapScale: "échelle de la carte",
    mapExtent: "étendue de la carte",
    forceScale: "Forcer l’échelle",
    getCurrentScale: "actuelle",
    mapMetadata: "Métadonnées de mise en page",
    author: "Auteur",
    copyright: "Copyright",
    fullLayoutOptions: "Options de mise en page complètes",
    scaleBarUnitsMetric: "Unités métriques de la barre d’échelle",
    scaleBarUnitsNonMetric: "Unités non métriques de la barre d’échelle",
    unitsMiles: "Miles",
    unitsKilometers: "Kilomètres",
    unitsMeters: "Mètres",
    unitsFeet: "Pieds",
    unitsYards: "Yards",
    unitsNauticalMiles: "Milles nautiques",
    lncludeLegend: "Inclure la légende",
    printQualityOptions: "Qualité d’impression",
    dpi: "PPP",
    mapOnlyOptions: "Format MAP_ONLY",
    width: "Largeur (px)",
    height: "Hauteur (px)",
    print: "Imprimer",
    clearList: "Supprimer les impressions",
    creatingPrint: "Création d’une impression",
    printError: "Erreur, réessayez"
  })
);