define(
   ({
    _widgetLabel: "打印",
    title: "地图标题",
    format: "格式",
    layout: "布局",
    settings: "高级",
    mapScaleExtent: "地图比例/范围",
    preserve: "保留",
    mapScale: "地图比例",
    mapExtent: "地图范围",
    forceScale: "强制比例",
    getCurrentScale: "当前",
    mapMetadata: "布局元数据",
    author: "作者",
    copyright: "版权所有",
    fullLayoutOptions: "完整布局选项",
    scaleBarUnitsMetric: "比例尺单位(公制)",
    scaleBarUnitsNonMetric: "比例尺单位(非公制)",
    unitsMiles: "英里",
    unitsKilometers: "千米",
    unitsMeters: "米",
    unitsFeet: "英尺",
    unitsYards: "码",
    unitsNauticalMiles: "海里",
    lncludeLegend: "包括图例",
    printQualityOptions: "打印质量",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY 大小",
    width: "宽度(px)",
    height: "高度(px)",
    print: "打印",
    clearList: "清除打印",
    creatingPrint: "正在创建打印",
    printError: "出现错误，请重试"
  })
);