define({
  root: ({
    clear: "Clear",
    status: "Show Google Street View",
    nostreetviewimageavailablemsg: "No Street View Image Available<br>or you have not yet dragged the Google® Street View man<br>onto the map to set your location.",
    instructions: "Drag the Google® Street View man onto the street you want to see a panorama for. You can also drag the street view man around on the map once he has been placed.",
    operamsg: "Because you are using Opera as your web browser you may need to perform the following steps",
    operamsgtitle: "Opera Browser Detected",
    popupblockermsg: "This widget uses a popup window to show Google Street View panoramas. You need to enable popups in your browser.",
    popupblockererrortitle: "Popup Blocker Detected",
    ok: "OK"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
