define({
  root: ({
    "name": "Name",
    "example": "Example",
    "xlabel": "X Label",
    "ylabel": "Y Label",
    "wkid": "WKID",
    "countryCode": "Country Code(s)",
    "countryCodeEg": "e.g. ",
    "countryCodeHint": "Leaving this value blank will search all countries",
    "locatorUrl": "Geocoder URL",
    "locatorName": "Geocoder Name",
    "locatorExample": "Example",
    "locatorWarning": "This version of geocoding service is not supported. The widget supports geocoding service 00.0 and above.",
    "locatorTips": "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    "set": "Set",
    "ok": "OK",
    "cancel": "Cancel",
    "invalidUrlTip": "The URL you have entered is invalid or inaccessible.",
    "addUnit": "Add map coordinate unit",
    "editUnit": "Edit map coordinate unit",
    "initialView": "Initial View",
    "disableTabs": "Edit Disabled Tab(s)",
    "zoomScale": "Default Zoom Scale",
    "addresslabel": "Address",
    "coordslabel": "Coordinates",
    "addressinsplabel": "Address Inspector",
    "resultslabel": "Results",
    "editDefaultSym": "Edit default symbols",
    "forcescale": "Force scale",
    "infowindowautoclose": "Info Window Auto Close (seconds)",
    "mouseovergraphic": "Enable Mouse Over Graphic Info Windows",
    "mouseoverresult": "Enable Mouse Over Result Info Windows",
    "keepactive": "Keep address inspector tool active after each address inspection",
    "symbologyTooltip": "Click on the symbology symbol that you want to edit",
    "addressSymbol": "Address Search Marker Symbol",
    "coordSymbol": "Coordinate Search Marker Symbol",
    "reverseSymbol": "Address Inspector Marker Symbol",
    "editdisabledtaboptions": "Choose Search Tab(s) to Disable",
    "availabletabs": "Disabled Tab(s)",
    "addRemove": "Add\\Remove",
    "autoclosetip": "If you do not specify a number of seconds here then the popup will not auto close",
    "nameExample": "NAD 1983 UTM 16N",
    "unitExample": "608140.63, 3724298.41",
    "cName": "Coordinate System ID",
    "dd": "Decimal Degrees (DD)",
    "dms": "Degrees Minutes Seconds (DMS)",
    "dm": "Degrees Minutes (DM)",
    "ddm": "Degrees Decimal Minutes (DDM)",
    "inputunits": "Input Units",
    "limittomapextent": "Enable geocoder limit to map extent by default (if supported)",
    "geox": "Longitude:",
    "geoy": "Latitude:",
    "projx": "Easting (X):",
    "projy": "Northing (Y):"
  })
});
