define(
   ({
    _widgetLabel: "報告圖徵",
    select: "選擇",
    draw: "繪製(D)",
    chooseALayer: "選擇圖層",
    clickAFeature: "在地圖上按一下圖徵以選擇它。",
    loadingFeatures: "正在取得所選的圖徵詳細資訊...",
    errorTitle: "錯誤",
    errorIdentify: "識別圖徵錯誤。請檢查主控台記錄的詳細資訊。",
    infoWindowTitle: "詳細資訊",
    layerLabel: "圖層名稱",
    reviewStatusLabel: "檢閱狀態",
    selectReviewStatusAdd: "新增圖徵",
    selectReviewStatusDelete: "刪除圖徵",
    selectReviewStatusMove: "移動圖徵",
    selectReviewStatusReshape: "重塑圖徵形狀",
    drawReviewStatusMissing: "缺少圖徵",
    drawReviewStatusPosition: "位置錯誤",
    drawReviewStatusShape: "形狀錯誤",
    drawReviewStatusAttribute: "屬性錯誤",
    notesLabel: "注意事項",
    severityLabel: "嚴重性",
    reportedByLabel: "報告者",
    reportedByDefault: "匿名",
    reportButton: "報告",
    reportMessage: "已接收報告",
    errorReportMessage: "報告圖徵時出錯",
    drawErrorInstructions: "選擇點、線或多邊形，並在地圖上繪製錯誤幾何:",
    errorMapService: "取得地圖服務資訊時出錯",
    noFeatureSelected : "在按一下的位置處找不到圖徵",
    selectFeatureMapPoint: "按一下以選擇圖徵",
    drawFeatureMapPoint: "按一下以增加點",
    popupMessage:"訊息",
    popupError:"錯誤",
    manyFeaturesSelected: "發現多個圖徵。請放大並選擇要報告的圖徵。"
  })
);
