define(
	 ({
		charts: "مهام المخطط",
		addNew: "إضافة أخرى جديدة",
		addNewTip: "إضافة مهمة مخطط جديد",
		name: "الاسم",
		set: "تعيين",
		setDataSource: "تعيين مصدر البيانات",
		generalSettingsTip: "تعيين مصدر بيانات وعنوان ووصف المخططات.",
		chartModeSettingTip: "حدد طريقة لتحليل وعرض البيانات كمخططات.",
		detailsSettingTip: "تعيين مظهر المخطط بتحديد أنواعه ولونه، فضلاً عن القيم المُراد وضعها في مخطط.",
		symbolSettingTip: "تعيين عرض الخريطة للبيانات المُخططة.",
		addFilterTip: "إضافة عامل تصفية إلى هذه البيانات",
		dataSource: "مصدر البيانات",
		noResults: "لم يتم العثور على أية معالم",
		chartTitle: "عنوان المخطط",
		description: "الوصف",
		chartingMode: "عرض المخطط",
		featureOption: "عرض القيم معلمًا بمعلم",
		categoryOption: "عرض القيم بواسطة الفئة",
		countOption: "عرض أعداد المعالم بواسطة الفئة",
		fieldOption: "عرض قيم البيانات الجدولية كمخططات",
		category: "الفئة",
		axisLabel: "وسيلة إيضاح الفئة",
		categoryField: "حقل الفئة",
		operation: "العملية",
		originalOption: "استخدام القيم الأصلية",
		sumOption: "مجموع",
		averageOption: "متوسط",
		minOption: "الحد الأدنى",
		maxOption: "الحد الأقصى",
		valueFields: "حقول القيم",
		moveUp: "نقل لأعلى",
		moveDown: "نقل لأسفل",
		sortOrder: "فرز ترتيب المخططات عبر وسائل إيضاح الفئة",
		ascending: "تصاعدي",
		descending: "تنازلي",
		chartType: "نوع المخطط",
		column: "مخطط العمود",
		bar: "مخطط الشريط",
		line: "مخطط الخط",
		pie: "مخطط دائري",
		chartColor: "لون المخطط",
		showDataLabels: "عرض وسائل إيضاح البيانات",
		setSymbol: "رمز التحديد",
		setHighLightColor: "لون التمييز",
		settings: "إعدادات",
		mapInterationOptions: "خيارات تفاعل الخريطة",
		preview: "معاينة",
		ok: "موافق",
		cancel: "إلغاء الأمر",
		close: "إغلاق",
		setFilterTip: "يرجى تعيين عامل التصفية بشكل صحيح. ",
		setChartTitleTip: "يرجى تعيين عنوان المخطط.",
		setChartTypeTip: "يرجى تعيين نوع مخطط واحد على الأقل.",
		setDataFieldTip: "يرجى تعيين حقل واحد على الأقل.",
		setOutputFieldTip: "يرجى تعيين الحقول الناتجة.",
		count: "عدد",
		label: "لافتة التسمية",
		horizontalAxis: "محور أفقي",
		verticalAxis: "محور رأسي",
		dataLabels: "تسميات البيانات",
		color: "لون",
		colorful: "مُلوّن",
		monochromatic: "أحادي اللون"
  })
);