define(
   ({
    selectAnalysisTools:"Velg analyseverktøy som skal være oppført i miniprogrammet.",
    selected: "valgte",
    name: "Navn",
    graphicalDisplay:"Grafisk visning",
    usage: "Bruk",
    toolNotAvailable: "Dette verktøyet er ikke tilgjengelig fordi kartet ikke inneholder et eller flere nødvendige geoobjektslag.",
    aggregatePoints:"Samle punkter",
    aggregatePointsUsage:"Samle punkter i polygoner der punktene befinner seg.",
    aggregatePointsInputTip: "Angi laget med punktgeoobjekter som skal samles i polygoner i laget med polygongeoobjekter.",
    calculateDensity:"Beregn tetthet",
    calculateDensityUsage:"Lag et tetthetskart fra punkt- eller linjegeoobjekter ved å spre kjente mengder av et fenomen (vises som attributter for punktene eller linjene) over kartet.",
    calculateDensityInputTip:"Angi punkt- eller linjegeoobjekter som beregningen av tetthet skal baseres på.",
    connectOriginsToDestinations: "Koble startpunkter til destinasjoner",
    connectOriginsToDestinationsUsage: "Beregn reisetiden eller avstanden mellom to punkter.",
    connectOriginsToDestinationsInputTip: "Angi startpunktet eller startpunktene for rutene som skal genereres.",
    createBuffers:"Opprett buffere",
    createBuffersUsage:"Opprett bufferpolygoner fra inndatageoobjektene.",
    createBuffersInputTip:"Angi laget med punkt-, linje- eller polygongeoobjekter som skal bufres.",
    createDriveTimeAreas:"Opprett kjøretidsområder",
    createDriveTimeAreasUsage:"Opprett kjøretidspolygoner (eller kjøreavstand) rundt inndatapunktene for angitte kjøretidsverdier.",
    createDriveTimeAreasInputTip:"Angi punktene der kjøretidsområdene skal tegnes.",
    createViewshed:"Create Viewshed",
    createViewshedUsage:"Oppretter områder som er synlige basert på lokasjonene du angir.",
    createViewshedInputTip:"Angi observasjonslokasjoner for å identifisere synlige områder.",
    createWatersheds:"Create Watersheds",
    createWatershedsUsage:"Oppretter nedbørsfeltområder basert på lokasjonene du oppgir.",
    createWatershedsInputTip:"Angi punktgeoobjektene som brukes til å beregne nedbørsfelt.",
    deriveNewLocations:"Utled nye plasseringer",
    deriveNewLocationsUsage:"Utled nye geoobjekter fra inndatalagene som oppfyller en spørring du angir",
    deriveNewLocationsInputTip:"Angi analyselaget som skal brukes som inndata.",
    dissolveBoundaries:"Visk ut grenser",
    dissolveBoundariesUsage:"Løs opp polygoner som overlapper eller deler en felles grense.",
    dissolveBoundariesInputTip:"Angi laget som inneholder polygongeoobjektene som skal løses opp.",
    enrichLayer:"Suppleringsdata",
    enrichLayerUsage:"Berik inndatageoobjekter med fakta om mennesker, steder og bedrifter i nærliggende områder.",
    enrichLayerInputTip:"Angi geoobjektene som skal berikes med nye data.",
    extractData:"Ekstraher data",
    extractDataDesc:"Trekk ut data fra ett eller flere lag med en gitt utstrekning",
    extractDataInputTip:"Angi laget med inndatageoobjekter det skal trekkes ut data fra.",
    findExistingLocations:"Finn eksisterende plasseringer",
    findExistingLocationsUsage:"Velg geoobjekter i inndatalaget som oppfyller et attributt og/eller geografisk spørring du angir",
    findExistingLocationsInputTip:"Angi analyselagene som skal brukes som inndata.",
    findHotSpots:"Finn hotspots",
    findHotSpotsUsage:"Finn statistisk signifikante klynger med inndatageoobjekter eller høye/lave verdier.",
    findHotSpotsInputTip:"Angi laget med punkt- eller polygongeoobjekter som det skal beregnes hotpots for.",
    findNearest:"Finn nærmeste",
    findNearestUsage:"For hvert geoobjekt i et inndatalag finner du dets nærmeste geoobjekt i et annet lag",
    findNearestInputTip:"Angi punkt-, linje- eller polygongeoobjekter som de nærmeste lokasjonene skal finnes fra.",
    findSimilarLocations:"Finn lignende lokasjoner",
    findSimilarLocationsUsage:"Mål likheten mellom kandidatlokasjoner og to eller flere referanselokasjoner.",
    findSimilarLocationsInputTip:"Angi et geoobjektslag som inneholder en eller flere referanselokasjoner som geoobjektene i søkelaget vurderes mot med hensyn til likheter.",
    interpolatePoints:"Interpoler punkter",
    interpolatePointsUsage:"Forutsi verdier på nye lokasjoner basert på målinger fra en samling punkter.",
    interpolatePointsInputTip:"Angi punktgeoobjektene som skal interpoleres.",
    mergeLayers:"Slå sammen lag",
    mergeLayersUsage:"Slå sammen geoobjekter fra flere lag til et nytt lag.",
    mergeLayersInputTip:"Angi geoobjektslaget som skal slås sammen med sammenslåingslaget.",
    overlayLayers:"Legg lag oppå",
    overlayLayersUsage:"Kombiner flere lag til ett enkelt lag der informasjonen fra de opprinnelige lagene beholdes.",
    overlayLayersInputTip:"Angi geoobjektslaget som overleggslaget skal legges over.",
    planRoutes:"Planlegg ruter",
    planRoutesUsage:"Finn ut hvordan du effektivt fordeler oppgaver i en mobil arbeidsstyrke.",
    planRoutesInputTip:"Angi punktene som kjøretøyene, sjåførene eller rutene skal besøke.",
    summarizeNearby:"Summer nærliggende",
    summarizeNearbyUsage:"For hvert geoobjekt i et inndatalaget summerer du data innenfor en avstand fra geoobjekter på et annet lag.",
    summarizeNearbyInputTip:"Angi laget med punkt-, linje- eller polygongeoobjekter som avstandene til geoobjekter i oppsummeringslaget skal måles fra.",
    summarizeWithin:"Summer innenfor",
    summarizeWithinUsage:"For hvert polygon i et lagt med inndatapolygoner summerer du data som befinner seg i det fra geoobjekter i et annet lag.",
    summarizeWithinInputTip:"Angi laget med polygongeoobjekter det skal oppsummeres mot.",
    traceDownstream:"Spor medstrøm",
    traceDownstreamUsage:"Finner strømningslinjene i nedstrøms retning fra lokasjonene du oppgir.",
    traceDownstreamInputTip:"Angi punktgeoobjektene som brukes til startlokasjonen for en nedstrømssporing."
  })
);
