define(
   ({
    selectAnalysisTools:"Velg analyseverktøy som skal brukes i widgeten.",
    selected: "valgte",
    name: "Navn",
    graphicalDisplay:"Grafisk visning",
    usage: "Bruk",
    settings: "Innstillinger",
    toolSetting: "Angi verktøydetaljer",
    toolLabel: "Visningsnavnet for verktøyet",
    showHelpTip: "Vis hjelpekoblinger i widgeten",
    showCurrentMapExtent: "Vis alternativ for å bruke gjeldende kartutstrekning",
    showCredits: "Vis alternativet <b>Vis credits</b>",
    saveAsFeatureService: "Lagre resultatet i brukerens konto",
    showReadyToUseLayers: "Vis lag som er klare til bruk fra ArcGIS Online living atlas of the world",
    toolNotAvailable: "Dette verktøyet er ikke tilgjengelig fordi kartet ikke inneholder påkrevde geoobjektslag.",
    aggregatePoints:"Aggreger punkter",
    aggregatePointsUsage:"Aggreger punkter til flater der punktene befinner seg.",
    calculateDensity:"Beregn tetthet",
    calculateDensityUsage:"Lag et tetthetskart fra punkter eller linjer ved å spre kjente mengder av et fenomen (representert som attributter for punktene eller linjene) i kartet.",
    connectOriginsToDestinations: "Koble startpunkter til destinasjoner",
    connectOriginsToDestinationsUsage: "Beregn reisetiden eller avstanden mellom to punkter.",
    createBuffers:"Opprett buffere",
    createBuffersUsage:"Opprett bufferflater fra inndata.",
    createDriveTimeAreas:"Opprett kjøretidsområder",
    createDriveTimeAreasUsage:"Opprett kjøretidsflater (eller kjøreavstand) rundt punktene for angitte kjøretidsverdier.",
    createViewshed:"Opprette Viewshed",
    createViewshedUsage:"Oppretter områder som er synlige basert på lokasjonene du angir.",
    createWatersheds:"Opprette Watersheds",
    createWatershedsUsage:"Oppretter nedbørsfeltområder basert på lokasjonene du oppgir.",
    deriveNewLocations:"Utled nye plasseringer",
    deriveNewLocationsUsage:"Utled nye geoobjekter fra datalagene som oppfyller en angitt spørring",
    dissolveBoundaries:"Visk ut grenser",
    dissolveBoundariesUsage:"Løs opp polygoner som overlapper eller deler en felles grense.",
    enrichLayer:"Berik Laget",
    enrichLayerUsage:"Berik geoobjekter med fakta om mennesker, steder og bedrifter i nærliggende områder.",
    extractData:"Trekk ut data",
    extractDataDesc:"Trekk ut data fra ett eller flere lag med en gitt utstrekning",
    findExistingLocations:"Finn eksisterende plasseringer",
    findExistingLocationsUsage:"Velg geoobjekter i datalaget som oppfyller en attributt og/eller geografisk spørring du angir",
    findHotSpots:"Finn hotspots",
    findHotSpotsUsage:"Finn statistisk signifikante klynger med geoobjekter eller høye/lave verdier.",
    findNearest:"Finn nærmeste",
    findNearestUsage:"For hvert geoobjekt i et datalag finner du dets nærmeste geoobjekt i et annet lag",
    findSimilarLocations:"Finn lignende lokasjoner",
    findSimilarLocationsUsage:"Mål likheten mellom kandidatlokasjoner til to eller flere referanselokasjoner.",
    interpolatePoints:"Interpoler punkter",
    interpolatePointsUsage:"Forutsi verdier på nye lokasjoner basert på målinger fra en samling punkter.",
    mergeLayers:"Slå sammen lag",
    mergeLayersUsage:"Slå sammen geoobjekter fra flere lag til et nytt lag.",
    overlayLayers:"Legg lag oppå",
    overlayLayersUsage:"Kombiner flere lag til ett enkelt lag der informasjonen fra de opprinnelige lagene beholdes.",
    planRoutes:"Planlegg ruter",
    planRoutesUsage:"Finn ut hvordan du effektivt fordeler oppgaver i en mobil arbeidsstyrke.",
    summarizeNearby:"Summer nærliggende",
    summarizeNearbyUsage:"For hvert geoobjekt i et datalag, summer data innenfor en avstand fra geoobjekter i et annet lag.",
    summarizeWithin:"Summer innenfor",
    summarizeWithinUsage:"For hver flate i et flatelag, summer data som befinner seg innenfor med geoobjekter fra et annet lag.",
    traceDownstream:"Spor medstrøm",
    traceDownstreamUsage:"Finner strømmelinjer i nedstrøms retning fra lokasjonene du oppgir."
  })
);
