define(
	 ({
		queries: "Operaţii de interogare",
		addNew: "Adăugare nou",
    queryLayer: "Strat tematic interogare",
		setSource: "Setare",
		setDataSource: "Setare sursă de date",
		name: "Nume",
		querySource: "Sursă date",
		queryName: "Nume operaţie",
		queryDefinition: "Definiţie filtru",
		resultsSetting: "Setare rezultate",
		symbolSetting: "Setare simbol",
		resultSettingTip: "Definiţi care sunt şi cum să fie afişate rezultatele.",
		resultItemTitle: "Titlu element rezultat",
		resultItemContent: "Conţinut element rezultat",
		fieldsSetTip: "Bifaţi câmpurile care doriţi să fie afişate. Selectaţi un câmp pentru a-i actualiza pseudonimul, pentru a-l reordona sau pentru a-l formata.",
		addField: "Adăugare câmp",
		visibility: "Vizibilitate",
		alias: "Pseudonim",
		specialType: "Tip special",
		actions: "Acţiuni",
		none: "Niciunul",
		link: "Link",
		image: "Imagine",
		noField: "Niciun câmp",
		operationalLayerTip: "Adăugare rezultat drept strat tematic operaţional",
		setLayerSymbolTip: "Setaţi simbolul pentru rezultatele interogării: ",
		setSelectedSymbolTip: "Setaţi simbolul pentru obiectul spaţial selectat.",
		notUseFilter: "Nu se utilizează filtrul",
		setSourceTip: "Setaţi sursa interogării.",
		setFilterTip: "Setaţi corect filtrul.",
		ok: "OK",
		cancel: "Anulare",
		noFilterTip: "Fără a avea expresia de filtrare definită, această operaţie de interogare va lista toate obiectele spaţiale din sursa de date specificată.",
    relationships: "Relaţii",
    addRelationshipLayer: "Adăugare relaţie nouă",
    relatedTo: "Referitor la",
    selectOption: "Selectaţi...",
    resultItemSorting: "Sortare elemente rezultate",
    field: "Câmp",
    sortingOrder: "Ordine",
    configureFieldsTip: "Configuraţi câmpurile după care vor fi sortate rezultatele interogării.",
    setSortingFields: "Configurarea câmpuri sortare",
    ascending: "Ascendent",
    descending: "Descendent",
    sortBy: "Sortare după",
    thenBy: "Apoi după",
    addTask: "Adăugare activitate",
    noTasksTip: 'Nicio activitate, faceţi clic pe \"${addTask}\" pentru a începe!',
    infoText: "Informaţii",
    filters: "Filtre",
    results: "Rezultate",
    optionsText: "Opţiuni",
    summaryText: "Rezumat",
    attributeFilter: "Filtru atribute",
    attributeFilterTip: "Definiţi expresiile atributelor pentru a fi utilizate în widget cu scopul de a filtra stratul tematic de interogări.",
    noExpressionDefinedTip: "Nu a fost definită nicio expresie.",
    needInputValuesTip: "Trebuie introduse valorile la runtime",
    setExpressions: "Setare expresii",
    spatialFilter: "Filtru spaţial",
    spatialFilterTip: "Alegeţi filtrele spaţiale utilizate în widget pentru limitarea rezultatelor.",
    defaultOption: "Implicit",
    useCurrentExtentTip: "Parţial sau complet în cadrul extinderii curente de hartă",
    useDrawGraphicTip: "Parţial sau complet în cadrul formei trasate pe hartă",
    useFeaturesTip: "În baza locaţiilor, în raport cu obiectele spaţiale din alt strat tematic",
    noSpatialLimitTip: "Nu limitaţi spaţial rezultatele",
    drawingTools: "Instrumente de trasare",
    bufferSettings: "Setări buffer",
    defaultDistance: "Distanţă implicită",
    bufferDistance: "Distanţă buffer",
    defaultUnit: "Unitate implicită",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    availableSpatialRelationships: "Relaţie spaţială disponibilă",
    setSpatialRelationships: "Setare relaţie spaţială",
    availability: "Disponibilitate",
    relationship: "Relaţie",
    label: "Etichetă",
    intersect: "intersectare",
    contain: "conţine",
    areContainedIn: "sunt conţinute de",
    cross: "cruce",
    envelopeIntersect: "intersectare plic",
    overlap: "suprapunere",
    areOverlapped: "sunt suprapuse",
    touche: "atins",
    within: "în",
    areWithin: "sunt la",
    indexIntersect: "intersectare index",
    itemTitle: "Titlu element",
    displayFields: "Câmpuri de afişare",
    sortingFields: "Câmpuri sortare",
    setDisplayFields: "Setare câmpuri de afişare",
    symbol: "Simbol",
    setSymbol: "Setare simbol",
    serviceSymbolTip: "Utilizaţi simbolurile definite de stratul tematic",
    exportTip: "Afişare buton Export",
    keepResultsTip: "Păstrare rezultate pe hartă după închiderea widgetului",
    queryRelatedRecords: "Înregistrări legate de interogări",
    createLayerForTaskTip: "Specificaţi modul în care activitatea creează straturi tematice",
    oneLayerForTaskTip: "Creaţi un singur strat tematic pentru această activitate",
    multipleLayerForTaskTip: "Creaţi un strat tematic nou de fiecare dată când este executată această activitate"
  })
);
