define(
	 ({
		queries: "Operaţii de interogare",
		addNew: "Adăugare nou",
		setSource: "Setare",
		setDataSource: "Setare sursă de date",
		name: "Nume",
		querySource: "Sursă date",
		queryName: "Nume operaţie",
		queryDefinition: "Definiţie filtru",
		resultsSetting: "Setare rezultate",
		symbolSetting: "Setare simbol",
		resultSettingTip: "Definiţi care sunt şi cum să fie afişate rezultatele.",
		resultItemTitle: "Titlu element rezultat",
		resultItemContent: "Conţinut element rezultat",
		fieldsSetTip: "Bifaţi câmpurile care doriţi să fie afişate. Selectaţi un câmp pentru a-i actualiza pseudonimul, pentru a-l reordona sau pentru a-l formata.",
		addField: "Adăugare câmp",
		visibility: "Vizibilitate",
		alias: "Pseudonim",
		specialType: "Tip special",
		actions: "Acţiuni",
		none: "Niciunul",
		link: "Link",
		image: "Imagine",
		noField: "Niciun câmp",
		operationalLayerTip: "Adăugare rezultat drept strat tematic operaţional",
		setLayerSymbolTip: "Setaţi simbolul pentru rezultatele interogării: ",
		setSelectedSymbolTip: "Setaţi simbolul pentru obiectul spaţial selectat.",
		notUseFilter: "Nu se utilizează filtrul",
		setSourceTip: "Setaţi sursa interogării.",
		setFilterTip: "Setaţi corect filtrul.",
		ok: "OK",
		cancel: "Anulare",
		noFilterTip: "Fără a avea expresia de filtrare definită, această operaţie de interogare va lista toate obiectele spaţiale din sursa de date specificată."
  })
);