define(
   ({
    taskUrl: "عنوان URL للمهمة",
    serviceURLPlaceholder: "الرجاء إدخال عنوان URL لمهمة المعالجة الجغرافية",
    ok: "موافق",
    cancel: "إلغاء الأمر",
    layer: "طبقة",
    action: "إجراء",
    input: "المُدخَل",
    output: "المخرجات",
    name: "الاسم",
    type: "نوع",
    required: "مطلوب",
    layerOrder: "ترتيب الطبقة",
    options: "خيارات",
    defaultValue: "القيمة الافتراضية",
    inputFeatureBy: "إدخال المعالم تبعًا لـ",
    renderer: "العارض",
    displayType: "نوع العرض",
    label: "لافتة التسمية",
    tooltip: "تلميح الأدوات",
    visible: "مرئي",
    helpUrl: "عنوان URL للتعليمات",
    useResultMapService: "استخدام خيارات الرسم لخدمة الخريطة الناتجة",
    drawOnMap: "الرسم التفاعلي على الخريطة",
    selectLayer: "تحديد الطبقة من الخريطة",
    url: "محدد موقع معلومات (URL)",
    symbol: "الرمز",
    shareResults: "إضافة النتيجة كطبقة تشغيلية",
    popup: "العناصر المنبثقة",
    setTask: "تعيين",
    setTaskTitle: "تعيين مهمة GP",
    enablePopup: "تمكين عنصر منبثق",
    unSupportGeometryType: "يتعذر تعيين المُقدّم نظرًا لأن نوع الشكل الهندسي غير معروف.",
    useUrlForGPInput: "عنوان URL",
    useUploadForGPInput: "تحميل الملف",
    selectFileToUpload: "حدد ملف...",
    upload: "تحميل",
    rasterFormat: "تنسيق البيانات النقطية",
    noFileSelected: "لم يتم تحديد أي ملف!",
    uploadSuccess:"تم تحميل الملف بنجاح!",
    showLayerContent: "عرض محتوى الطبقة",
    Feet: "قدم",
    Yards: "ياردة",
    Miles: "ميل",
    NauticalMiles: "الأميال البحرية",
    Meter: "متر",
    Kilometers: "كيلومترات",
    urlPlaceholder: "عنوان URL لمجموعة المعالم",
    allowToExport: "السماح بتصدير النتائج"
  })
);
