define(
   ({
    _widgetLabel: "Informe de entidades",
    select: "Seleccionar",
    draw: "Dibujar",
    chooseALayer: "Seleccionar una capa",
    clickAFeature: "Haz clic en una entidad del mapa para seleccionarla.",
    loadingFeatures: "Obteniendo detalles de la entidad seleccionada...",
    errorTitle: "Error",
    errorIdentify: "Error de identificación de entidades. Consulta el registro de la consola para conocer los detalles.",
    infoWindowTitle: "Detalles",
    layerLabel: "Nombre de la capa",
    reviewStatusLabel: "Estado de revisión",
    selectReviewStatusAdd: "Agregar entidad",
    selectReviewStatusDelete: "Eliminar Entidad",
    selectReviewStatusMove: "Mover entidad",
    selectReviewStatusReshape: "Volver a dar forma a la entidad",
    drawReviewStatusMissing: "Entidades no encontradas",
    drawReviewStatusPosition: "Error de posición",
    drawReviewStatusShape: "Error de forma",
    drawReviewStatusAttribute: "Error de atributo",
    notesLabel: "Notas",
    severityLabel: "Gravedad",
    reportedByLabel: "Informe de",
    reportedByDefault: "anónimo",
    reportButton: "Informe",
    reportMessage: "Informe recibido",
    errorReportMessage: "Se ha producido un error al informar sobre la entidad",
    drawErrorInstructions: "Selecciona un punto, una línea o un polígono y dibuja la geometría del error en el mapa:",
    errorMapService: "Se ha producido un error al obtener la información del servicio de mapas",
    noFeatureSelected : "No se han encontrado entidades en la ubicación en la que se ha hecho clic",
    selectFeatureMapPoint: "Haz clic para seleccionar una entidad",
    drawFeatureMapPoint: "Haga clic para agregar un punto",
    popupMessage:"Mensaje",
    popupError:"Error",
    manyFeaturesSelected: "Se ha encontrado más de una entidad. Haz zoom y selecciona una entidad para el informe."
  })
);
