define(
   ({
    _widgetLabel: "Γράφημα",
    executeChartTip: "Κάντε κλικ σε ένα από τα παρακάτω γραφήματα για να το ανοίξετε.",
    invalidConfig: "Μη έγκυρη διαμόρφωση.",
    noneChartTip: "Δεν έχουν καθοριστεί γραφήματα για αυτό το widget.",
    chartParams: "Επιλογές",
    charts: "ΓΡΑΦΗΜΑΤΑ",
    apply: "ΕΦΑΡΜΟΓΗ",
    useSpatialFilter: "Χρήση χωρικού φίλτρου για τον περιορισμό των στοιχείων",
    useCurrentMapExtent: "Μόνο στοιχεία που τέμνουν την τρέχουσα περιοχή χάρτη",
    drawGraphicOnMap: "Μόνο στοιχεία που τέμνουν μια περιοχή η οποία έχει οριστεί από το χρήστη",
    chartResults: "Αποτελέσματα γραφημάτων",
    clearResults: "Απαλοιφή αποτελεσμάτων",
    noPermissionsMsg: "Δεν έχετε άδεια πρόσβασης σε αυτή την υπηρεσία.",
    specifySpatialFilterMsg: "Ορίστε χωρικό φίλτρο για αυτήν την εργασία.",
    queryError: "Το ερώτημα απέτυχε.",
    noResults: "Δεν εντοπίστηκε κάποιο στοιχείο.",
    category: "Κατηγορία",
    count: "Πλήθος",
    label: "Ετικέτα",
    horizontalAxis: "Οριζόντιος άξονας",
    verticalAxis: "Κατακόρυφος άξονας",
    dataLabels: "Ετικέτες δεδομένων",
    color: "Χρώμα",
    colorful: "Πολύχρωμο",
    monochromatic: "Μονόχρωμο",
    tasks: "Εργασίες",
    results: "Αποτελέσματα",
    applySpatialFilterToLimitResults: "Εφαρμόστε ένα χωρικό φίλτρο για να περιορίσετε τα αποτελέσματα",
    useCurrentExtentTip: "Μερικώς ή πλήρως εντός της τρέχουσας έκτασης χάρτη",
    useDrawGraphicTip: "Μερικώς ή πλήρως εντός του σχήματος που έχει σχεδιαστεί στο χάρτη",
    useFeaturesTip: "Βάσει των τοποθεσιών που είναι σχετικές με στοιχεία άλλου θεματικού επιπέδου",
    noSpatialLimitTip: "Χωρίς χωρικό περιορισμό αποτελεσμάτων",
    applySearchDistance: "Εφαρμογή απόστασης αναζήτησης",
    spatialRelationship: "Χωρική συσχέτιση",
    relatedLayer: "Συσχετιζόμενο θεματικό επίπεδο",
    clear: "Απαλοιφή",
    bufferDistance: "Απόσταση ζώνης",
    miles: "Μίλια",
    kilometers: "Χιλιόμετρα",
    feet: "Πόδια",
    meters: "Μέτρα",
    yards: "Γιάρδες",
    nauticalMiles: "Ναυτικά μίλια",
    back: "Πίσω",
    execute: "Εκτέλεση"
  })
);