define(
   ({
    _widgetLabel: "Povědomí o situaci (Beta)",
    locate_incident: "Vyhledat událost",
    clear_incidents: "Vymazat události",
    reverse_geocoded_address: "Nejbližší adresa",
    reverse_geocoded_error: "Nedostupné",
    miles: "Míle",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    now: "NYNÍ",
    wind: "OKNO",
    SUN: "NE",
    MON: "PO",
    TUE: "ÚT",
    WED: "ST",
    THU: "ČT",
    FRI: "PÁ",
    SAT: "SO",
    defaultTabMsg: "Nebyly identifikovány žádné incidenty.",
    actionLabel: "Nastavit jako incident",
    drawPoint: "Nakreslit bod",
    drawLine: "Nakreslit linii",
    drawPolygon: "Kreslit polygon",
    saveIncident: "Uložit událost",
    clearIncident: "Vymazat událost",
    useMapExtent: "Použít současný rozsah mapy",
    noFeaturesFound: "Nebyly nalezeny žádné prvky.",
    downloadCSV: "STÁHNOUT CSV",
    editComplete: "Prvek byl úspěšně uložen.",
    updateComplete: "Prvek byl úspěšně aktualizován.",
    deleteComplete: "Prvek byl úspěšně smazán.",
    sum: "SUMA",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "POČET",
    area: "PLOCHA",
    length: "DÉLKA",
    notPolySave: "Před uložením zadejte šířku obalové zóny.",
    update_btn: "Aktualizovat",
    delete_btn: "Smazat"
  })
);
