define(
   ({
    selectAnalysisTools:"Vyberte nástroje analýzy, které si přejete používat ve widgetu.",
    selected: "vybrané",
    name: "Název",
    graphicalDisplay:"Grafické zobrazení",
    usage: "Použití",
    settings: "Nastavení",
    toolSetting: "Nastavte podrobnosti nástrojů",
    toolLabel: "Zobrazovaný název nástroje",
    showHelpTip: "Zobrazovat ve widgetu odkazy na nápovědu",
    showCurrentMapExtent: "Zobrazovat možnost použití aktuálního rozsahu mapy",
    showCredits: "Zobrazovat možnost <b>Zobrazit kredity</b>",
    saveAsFeatureService: "Uložit výsledky do uživatelského účtu",
    showReadyToUseLayers: "Zobrazovat vrstvy připravené k použití z živého atlasu světa ArcGIS Online",
    toolNotAvailable: "Tento nástroj není k dispozici, protože mapa neobsahuje požadované vrstvy prvků.",
    aggregatePoints:"Seskupit body",
    aggregatePointsUsage:"Umožňuje seskupit body do polygonů, ve kterých se tyto body nacházejí.",
    calculateDensity:"Vypočítat hustotu",
    calculateDensityUsage:"Umožňuje vytvářet mapu hustoty z bodových nebo liniových prvků rozprostřením známého množství určitého jevu (v podobě atributů bodů nebo linií) po mapě.",
    connectOriginsToDestinations: "Spojení počátků s cíli",
    connectOriginsToDestinationsUsage: "Umožňuje měřit čas cesty nebo vzdálenost mezi dvojicí bodů.",
    createBuffers:"Vytvořit obalové zóny",
    createBuffersUsage:"Umožňuje vytvářet polygony obalové zóny ze vstupních prvků.",
    createDriveTimeAreas:"Vytvořit oblasti podle doby jízdy",
    createDriveTimeAreasUsage:"Umožňuje vytvářet polygony doby jízdy (nebo jízdní vzdálenosti) okolo vstupních bodů pro zadané hodnoty doby jízdy.",
    createViewshed:"Vytvořit viditelnost",
    createViewshedUsage:"Umožňuje vytvářet oblasti, které jsou viditelné na základě vámi určených umístění.",
    createWatersheds:"Vytvořit povodí",
    createWatershedsUsage:"Umožňuje vytvářet oblasti povodí na základě vámi určených umístění.",
    deriveNewLocations:"Odvodit nové lokality",
    deriveNewLocationsUsage:"Umožňuje odvodit ze vstupních vrstev nové prvky, které splňují zadaná kritéria.",
    dissolveBoundaries:"Sloučit hranice",
    dissolveBoundariesUsage:"Umožňuje sloučit polygony, které se překrývají nebo mají společné hranice.",
    enrichLayer:"Obohatit vrstvu",
    enrichLayerUsage:"Umožňuje obohatit vstupní prvky informacemi o lidech, místech a obchodními údaji přilehlých oblastí.",
    extractData:"Extrahovat data",
    extractDataDesc:"Umožňuje extrahovat data z jedné nebo více vrstev v daném rozsahu.",
    findExistingLocations:"Najít existující umístění",
    findExistingLocationsUsage:"Umožňuje vybrat prvky ve vstupní vrstvě, které splňují požadavky zadaného atributu nebo prostorového dotazu.",
    findHotSpots:"Najít místa s vysokou intenzitou",
    findHotSpotsUsage:"Umožňuje najít statisticky významné shluky vstupních prvků nebo vysokých/nízkých hodnot.",
    findNearest:"Vyhledat nejbližší",
    findNearestUsage:"Umožňuje najít pro každý prvek vstupní vrstvy nejbližší prvek v jiné vrstvě.",
    findSimilarLocations:"Vyhledat podobná umístění",
    findSimilarLocationsUsage:"Umožňuje měřit podobnost kandidátských umístění s jedním nebo více referenčními umístěními.",
    interpolatePoints:"Interpolovat body",
    interpolatePointsUsage:"Umožňuje odhadovat hodnoty v nových místech na základě hodnot existujících bodů.",
    mergeLayers:"Sloučit vrstvy",
    mergeLayersUsage:"Umožňuje sloučit prvky z několika vrstev do nové vrstvy.",
    overlayLayers:"Překrýt vrstvy",
    overlayLayersUsage:"Umožňuje zkombinovat několik vrstev do jedné vrstvy se zachováním informací z původních vrstev.",
    planRoutes:"Plánovat trasy",
    planRoutesUsage:"Umožňuje určit efektivní rozdělení úkolů mezi mobilní pracovníky.",
    summarizeNearby:"Sumarizace v okolí",
    summarizeNearbyUsage:"Umožňuje pro všechny prvky vstupní vrstvy sumarizovat data v dané vzdálenosti od prvků v jiné vrstvě.",
    summarizeWithin:"Sumarizace v rozmezí",
    summarizeWithinUsage:"Umožňuje pro všechny polygony ve vstupní vrstvě sumarizovat obsažená data pomocí prvků v jiné vrstvě.",
    traceDownstream:"Sledovat po proudu",
    traceDownstreamUsage:"Umožňuje určit trasy toku směrem po proudu od vámi určených umístění."
  })
);
