define(
   ({
    selectAnalysisTools:"Vyberte nástroje analýzy, které si přejete vypsat ve widgetu.",
    selected: "vybrané",
    name: "Název",
    graphicalDisplay:"Grafické zobrazení",
    usage: "Použití",
    toolNotAvailable: "Tento nástroj není k dispozici, protože mapa neobsahuje požadované vrstvy prvků.",
    aggregatePoints:"Seskupit body",
    aggregatePointsUsage:"Umožňuje seskupit body do polygonů, ve kterých se tyto body nacházejí.",
    aggregatePointsInputTip: "Určete vrstvu bodových prvků, která bude seskupena do polygonů ve vrstvě polygonových prvků.",
    calculateDensity:"Vypočítat hustotu",
    calculateDensityUsage:"Umožňuje vytvářet mapu hustoty z bodových nebo liniových prvků rozprostřením známého množství určitého jevu (v podobě atributů bodů nebo linií) po mapě.",
    calculateDensityInputTip:"Určete bodové nebo liniové prvky, které se použijí pro výpočet hustoty.",
    connectOriginsToDestinations: "Spojení počátků s cíli",
    connectOriginsToDestinationsUsage: "Umožňuje měřit čas cesty nebo vzdálenost mezi dvojicí bodů.",
    connectOriginsToDestinationsInputTip: "Určete počáteční bod nebo body vytvářených tras.",
    createBuffers:"Vytvořit obalové zóny",
    createBuffersUsage:"Umožňuje vytvářet polygony obalové zóny ze vstupních prvků.",
    createBuffersInputTip:"Určete bodové, liniové nebo polygonové prvky, pro které mají být vytvořeny obalové zóny.",
    createDriveTimeAreas:"Vytvořit oblasti podle doby jízdy",
    createDriveTimeAreasUsage:"Umožňuje vytvářet polygony doby jízdy (nebo jízdní vzdálenosti) okolo vstupních bodů pro zadané hodnoty doby jízdy.",
    createDriveTimeAreasInputTip:"Určete body, které se použijí k vykreslení oblastí doby jízdy.",
    createViewshed:"Vytvořit viditelnost",
    createViewshedUsage:"Umožňuje vytvářet oblasti, které jsou viditelné na základě vámi určených umístění.",
    createViewshedInputTip:"Určete umístění pozorovatele, které se použije k určení viditelných oblastí.",
    createWatersheds:"Vytvořit povodí",
    createWatershedsUsage:"Umožňuje vytvářet oblasti povodí na základě vámi určených umístění.",
    createWatershedsInputTip:"Určete bodové prvky, které se použijí k výpočtu povodí.",
    deriveNewLocations:"Odvodit nové lokality",
    deriveNewLocationsUsage:"Umožňuje odvodit ze vstupních vrstev nové prvky, které splňují zadaná kritéria.",
    deriveNewLocationsInputTip:"Určete vrstvu analýzy, která se použije jako vstup.",
    dissolveBoundaries:"Sloučit hranice",
    dissolveBoundariesUsage:"Umožňuje sloučit polygony, které se překrývají nebo mají společné hranice.",
    dissolveBoundariesInputTip:"Určete vrstvu obsahující polygonové prvky, které chcete sloučit.",
    enrichLayer:"Obohatit vrstvu",
    enrichLayerUsage:"Umožňuje obohatit vstupní prvky informacemi o lidech, místech a obchodními údaji přilehlých oblastí.",
    enrichLayerInputTip:"Určete prvky, které chcete obohatit novými daty.",
    extractData:"Extrahovat data",
    extractDataDesc:"Umožňuje extrahovat data z jedné nebo více vrstev v daném rozsahu.",
    extractDataInputTip:"Určete vstupní vrstvu prvků, kterou chcete použít k extrahování.",
    findExistingLocations:"Najít existující umístění",
    findExistingLocationsUsage:"Umožňuje vybrat prvky ve vstupní vrstvě, které splňují požadavky zadaného atributu nebo prostorového dotazu.",
    findExistingLocationsInputTip:"Určete vrstvy analýzy, které chcete použít jako vstup.",
    findHotSpots:"Najít místa s vysokou intenzitou",
    findHotSpotsUsage:"Umožňuje najít statisticky významné shluky vstupních prvků nebo vysokých/nízkých hodnot.",
    findHotSpotsInputTip:"Určete vrstvu bodových nebo polygonových prvků, která se použije k výpočtu míst s vysokou intenzitou.",
    findNearest:"Vyhledat nejbližší",
    findNearestUsage:"Umožňuje najít pro každý prvek vstupní vrstvy nejbližší prvek v jiné vrstvě.",
    findNearestInputTip:"Určete bodové, liniové nebo polygonové prvky, které se použijí k vyhledání nejbližších umístění.",
    findSimilarLocations:"Vyhledat podobná umístění",
    findSimilarLocationsUsage:"Umožňuje měřit podobnost kandidátských umístění s jedním nebo více referenčními umístěními.",
    findSimilarLocationsInputTip:"Určete vrstvu prvků s jedním nebo několika referenčními umístěními, které se použijí k vyhodnocení podobnosti s prvky ve vyhledávané vrstvě.",
    interpolatePoints:"Interpolovat body",
    interpolatePointsUsage:"Umožňuje odhadovat hodnoty v nových místech na základě hodnot existujících bodů.",
    interpolatePointsInputTip:"Určete bodové prvky, které se použijí k interpolaci.",
    mergeLayers:"Sloučit vrstvy",
    mergeLayersUsage:"Umožňuje sloučit prvky z několika vrstev do nové vrstvy.",
    mergeLayersInputTip:"Určete vrstvu prvků, která se sloučí s cílovou vrstvou.",
    overlayLayers:"Překrýt vrstvy",
    overlayLayersUsage:"Umožňuje zkombinovat několik vrstev do jedné vrstvy se zachováním informací z původních vrstev.",
    overlayLayersInputTip:"Určete vrstvu prvků, která se překryje překryvnou vrstvou.",
    planRoutes:"Plánovat trasy",
    planRoutesUsage:"Umožňuje určit efektivní rozdělení úkolů mezi mobilní pracovníky.",
    planRoutesInputTip:"Určete body navštěvované vozidly, řidiči nebo trasami.",
    summarizeNearby:"Sumarizace v okolí",
    summarizeNearbyUsage:"Umožňuje pro všechny prvky vstupní vrstvy sumarizovat data v dané vzdálenosti od prvků v jiné vrstvě.",
    summarizeNearbyInputTip:"Určete vrstvu bodových, liniových nebo polygonových prvků, od které budou měřeny vzdálenosti k prvkům ve vrstvě sumarizace.",
    summarizeWithin:"Sumarizace v rozmezí",
    summarizeWithinUsage:"Umožňuje pro všechny polygony ve vstupní vrstvě sumarizovat obsažená data pomocí prvků v jiné vrstvě.",
    summarizeWithinInputTip:"Určete vrstvu polygonových prvků, která bude použita jako cíl sumarizace.",
    traceDownstream:"Sledovat po proudu",
    traceDownstreamUsage:"Umožňuje určit trasy toku směrem po proudu od vámi určených umístění.",
    traceDownstreamInputTip:"Určete bodové prvky, které se použijí k označení umístění počátku trasy sledované po proudu."
  })
);
