define(
   ({
    _widgetLabel: "Percepção da Situação (Beta)",
    locate_incident: "Localizar Incidente",
    clear_incidents: "Apagar Incidentes",
    reverse_geocoded_address: "Endereço mais próximo",
    reverse_geocoded_error: "Não disponível",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    now: "AGORA",
    wind: "VENTO",
    SUN: "DOM",
    MON: "SEG",
    TUE: "TER",
    WED: "QUA",
    THU: "QUI",
    FRI: "SEX",
    SAT: "SAB",
    defaultTabMsg: "Nenhum incidente identificado.",
    actionLabel: "Configurar como Incidente",
    drawPoint: "Desenhar Ponto",
    drawLine: "Desenhar Linha",
    drawPolygon: "Desenhar Polígono",
    saveIncident: "Salvar Incidente",
    clearIncident: "Apagar Incidente",
    useMapExtent: "Utilize a extensão de mapa atual",
    noFeaturesFound: "Nenhuma feição foi encontrada.",
    downloadCSV: "DOWNLOAD DE CSV",
    editComplete: "Feição salva com sucesso!",
    updateComplete: "Feição atualizada com sucesso!",
    deleteComplete: "Feição excluída com sucesso!",
    sum: "SOMA",
    min: "MÍN",
    max: "MÁX",
    avg: "MÉDIA",
    count: "CONTAGEM",
    area: "ÁREA",
    length: "COMPRIMENTO",
    notPolySave: "Especifique uma distância de buffer antes de salvar.",
    update_btn: "Atualizar",
    delete_btn: "Excluir"
  })
);
