define({
  root: ({
    geomServiceUrl: "Geometry Service URL",
    streetviewOptions: "Street View options",
    popWidth: "Width",
    popHeight: "Height",
    symbolOptions: "Symbol options",
    googleMapType: "Google Map Type",
    gRoadMap: "Road Map",
    gSatellite: "Satellite",
    gHybrid: "Hybrid",
    gTerrain: 'Terrain',
    bingMapType: "Bing Map Type",
    bRoadMap: "Road Map",
    bSatellite: "Satellite",
    bHybrid: "Hybrid",
    pMap: "Map",
    pStreetView: "Street View",
    pBirdseye: "Birdseye",
    pInfo: "Info",
    markerImage: "Marker Image",
    pmd: "Marker is raggable",
	symbolStyle: "Symbol style",
    diamond: "diamond",
	circle: "circle",
	cross: "cross",
	square: "square",
	symbolColor: "Symbol color",
	red: "Red",
	yellow: "Yellow",
	blue: "Blue",
	green: "Green",
	symbolSize: "Symbol size",
	parametersTip: 'Please set parameters correctly !'
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  'zh-cn': 0
});