define(
   ({
    _widgetLabel: "Świadomość sytuacyjna (Beta)",
    locate_incident: "Zlokalizuj zdarzenie",
    clear_incidents: "Wyczyść zdarzenia",
    reverse_geocoded_address: "Najbliższy adres",
    reverse_geocoded_error: "Niedostępny",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    now: "TERAZ",
    wind: "WIATR",
    SUN: "NIEDZ",
    MON: "PON",
    TUE: "WT",
    WED: "ŚR",
    THU: "CZW",
    FRI: "PT",
    SAT: "SOB",
    defaultTabMsg: "Nie znaleziono żadnych zdarzeń.",
    actionLabel: "Skonfiguruj jako zdarzenie",
    drawPoint: "Rysuj punkt",
    drawLine: "Rysuj linię",
    drawPolygon: "Rysuj poligon",
    saveIncident: "Zapisz incydent",
    clearIncident: "Wyczyść incydent",
    useMapExtent: "Użyj bieżącego zasięgu mapy",
    noFeaturesFound: "Nie odnaleziono obiektów.",
    downloadCSV: "POBIERZ PLIK CSV",
    editComplete: "Pomyślnie zapisano obiekt!",
    updateComplete: "Obiekt został zaktualizowany pomyślnie.",
    deleteComplete: "Obiekt został usunięty pomyślnie.",
    sum: "SUMA",
    min: "MIN.",
    max: "MAKS.",
    avg: "ŚRED.",
    count: "LICZBA",
    area: "POWIERZCHNIA",
    length: "DŁUGOŚĆ",
    notPolySave: "Podaj odległość buforowania przed zapisaniem.",
    update_btn: "Zmień",
    delete_btn: "Usuń"
  })
);
