define(
   ({
    selectAnalysisTools:"Välj vilka analysverktyg som ska användas i widgeten.",
    selected: "valt",
    name: "Namn",
    graphicalDisplay:"Grafisk visning",
    usage: "Användning",
    settings: "Inställningar",
    toolSetting: "Ange verktygsinformation",
    toolLabel: "Verktygets visningsnamn",
    showHelpTip: "Visa hjälplänkar i widgeten",
    showCurrentMapExtent: "Visa alternativ för att använda den aktuella kartutbredningen",
    showCredits: "Visa alternativet <b>Visa krediter</b>",
    saveAsFeatureService: "Visa resultatet i användarens konto",
    showReadyToUseLayers: "Visa lager som är redo att använda från ArcGIS Onlines levande världsatlas",
    toolNotAvailable: "Det här verktyget är inte tillgängligt eftersom kartan inte innehåller de geoobjektslager som krävs.",
    aggregatePoints:"Aggregera punkter",
    aggregatePointsUsage:"Aggregera punkterna till polygoner där punkterna är placerade.",
    calculateDensity:"Beräkna densitet",
    calculateDensityUsage:"Skapa en densitetskarta av punkt- eller linjegeoobjekt genom att sprida ut kända antal av något fenomen (som representeras som attribut för punkterna eller linjerna) över kartan.",
    connectOriginsToDestinations: "Koppla startplatser till destinationer",
    connectOriginsToDestinationsUsage: "Mät restiden eller avståndet mellan punktpar.",
    createBuffers:"Skapa buffertar",
    createBuffersUsage:"Skapa buffertpolygoner av indatageoobjekt.",
    createDriveTimeAreas:"Skapa körtidsområden",
    createDriveTimeAreasUsage:"Skapa polygoner för körtid (eller köravstånd) runt indatapunkter för de givna körtidsvärdena.",
    createViewshed:"Skapa siktområde",
    createViewshedUsage:"Skapar områden som är synliga baserat på de platser du anger.",
    createWatersheds:"Skapa avrinningsområden",
    createWatershedsUsage:"Skapar uppsamlingsområden baserat på de platser du anger.",
    deriveNewLocations:"Härled nya platser",
    deriveNewLocationsUsage:"Härled nya geoobjekt från de indatalager som motsvarar en fråga du anger",
    dissolveBoundaries:"Lös upp gränser",
    dissolveBoundariesUsage:"Lös upp polygoner som överlappar eller delar en gemensam gräns.",
    enrichLayer:"Berika lager",
    enrichLayerUsage:"Berika indatageoobjekten med människor, platser och företag i närliggande områden.",
    extractData:"Extrahera data",
    extractDataDesc:"Extrahera data från ett eller flera lager inom en given utbredning",
    findExistingLocations:"Hitta befintliga platser",
    findExistingLocationsUsage:"Välj geoobjekt i indatalagret som motsvarar ett attribut och/eller en geografisk fråga som du anger.",
    findHotSpots:"Hitta hotspots",
    findHotSpotsUsage:"Sök efter statistiskt signifikanta kluster av indatageoobjekt eller höga/låga värden.",
    findNearest:"Hitta närmaste",
    findNearestUsage:"Hitta närmaste geoobjekt i ett annat lager för varje geoobjekt i ett indatalager",
    findSimilarLocations:"Hitta liknande platser",
    findSimilarLocationsUsage:"Mät kandidatplatsers likhet med en eller flera referensplatser.",
    interpolatePoints:"Interpoleringspunkter",
    interpolatePointsUsage:"Förutsäg värden i nya platser baserat på mätningar från en samling punkter.",
    mergeLayers:"Sammanfoga lager",
    mergeLayersUsage:"Slå samman geoobjekt från flera lager till ett nytt lager",
    overlayLayers:"Överlagra lager",
    overlayLayersUsage:"Kombinera flera lager i ett enda lager med informationen bevarad från ursprungslagren.",
    planRoutes:"Planera rutter",
    planRoutesUsage:"Fastställer hur du effektivt fördelar uppgifter inom en mobil arbetsstyrka.",
    summarizeNearby:"Summera nära",
    summarizeNearbyUsage:"Sammanfatta data inom en viss distans från geoobjekt i ett annat lager för varje geoobjekt i ett indatalager.",
    summarizeWithin:"Summera inom",
    summarizeWithinUsage:"Sammanfatta data i ett indatapolygonlager från geoobjekt i ett annat lager för varje polygon i ett annat lager.",
    traceDownstream:"Spåra nedströms",
    traceDownstreamUsage:"Avgör flödesmönstren nedströms från de platser du anger."
  })
);
