define(
   ({
    selectAnalysisTools:"Välj vilka analysverktyg som ska visas i widgeten.",
    selected: "valt",
    name: "Namn",
    graphicalDisplay:"Grafisk visning",
    usage: "Användning",
    toolNotAvailable: "Det här verktyget är inte tillgängligt eftersom kartan inte innehåller de geoobjektslager som krävs.",
    aggregatePoints:"Aggregera punkter",
    aggregatePointsUsage:"Aggregera punkterna till polygoner där punkterna är placerade.",
    aggregatePointsInputTip: "Ange det punktgeoobjektslager som ska aggregeras till polygoner i polygongeoobjektslagret.",
    calculateDensity:"Beräkna densitet",
    calculateDensityUsage:"Skapa en densitetskarta av punkt- eller linjegeoobjekt genom att sprida ut kända antal av något fenomen (som representeras som attribut för punkterna eller linjerna) över kartan.",
    calculateDensityInputTip:"Ange de punkt- eller linjegeoobjekt som densiteten ska beräknas från.",
    connectOriginsToDestinations: "Koppla startplatser till destinationer",
    connectOriginsToDestinationsUsage: "Mät restiden eller avståndet mellan punktpar.",
    connectOriginsToDestinationsInputTip: "Ange startpunkten eller punkter på de rutter som ska genereras.",
    createBuffers:"Skapa buffertar",
    createBuffersUsage:"Skapa buffertpolygoner av indatageoobjekt.",
    createBuffersInputTip:"Ange det punkt-, linje- eller polygongeoobjektslager som ska bilda bufferten.",
    createDriveTimeAreas:"Skapa körtidsområden",
    createDriveTimeAreasUsage:"Skapa polygoner för körtid (eller köravstånd) runt indatapunkter för de givna körtidsvärdena.",
    createDriveTimeAreasInputTip:"Ange punkterna där körtidsområdena ska ritas.",
    createViewshed:"Skapa siktområde",
    createViewshedUsage:"Skapar områden som är synliga baserat på de platser du anger.",
    createViewshedInputTip:"Ange observatörsplatser för att identifiera synliga områden.",
    createWatersheds:"Skapa avrinningsområden",
    createWatershedsUsage:"Skapar uppsamlingsområden baserat på de platser du anger.",
    createWatershedsInputTip:"Ange de punktgeoobjekt som ska användas för beräkning av avrinningsområden.",
    deriveNewLocations:"Härled nya platser",
    deriveNewLocationsUsage:"Härled nya geoobjekt från de indatalager som motsvarar en fråga du anger",
    deriveNewLocationsInputTip:"Ange vilket analyslager som ska användas som indata.",
    dissolveBoundaries:"Lös upp gränser",
    dissolveBoundariesUsage:"Lös upp polygoner som överlappar eller delar en gemensam gräns.",
    dissolveBoundariesInputTip:"Ange det lager som innehåller polygongeoobjekt som ska lösas upp.",
    enrichLayer:"Berika lager",
    enrichLayerUsage:"Berika indatageoobjekten med människor, platser och företag i närliggande områden.",
    enrichLayerInputTip:"Ange vilka geoobjekt som ska berikas med nya data.",
    extractData:"Extrahera data",
    extractDataDesc:"Extrahera data från ett eller flera lager inom en given utbredning",
    extractDataInputTip:"Ange vilket indatageoobjektslager som ska extraheras.",
    findExistingLocations:"Hitta befintliga platser",
    findExistingLocationsUsage:"Välj geoobjekt i indatalagret som motsvarar ett attribut och/eller en geografisk fråga som du anger.",
    findExistingLocationsInputTip:"Ange vilka analyslager som ska användas som indata.",
    findHotSpots:"Hitta hotspots",
    findHotSpotsUsage:"Sök efter statistiskt signifikanta kluster av indatageoobjekt eller höga/låga värden.",
    findHotSpotsInputTip:"Ange det punkt- eller polygongeoobjektslager för vilka hot spots ska beräknas.",
    findNearest:"Hitta närmaste",
    findNearestUsage:"Hitta närmaste geoobjekt i ett annat lager för varje geoobjekt i ett indatalager",
    findNearestInputTip:"Ange de punkt-, linje- eller polygongeoobjekt från vilka närmaste platser ska sökas.",
    findSimilarLocations:"Hitta liknande platser",
    findSimilarLocationsUsage:"Mät kandidatplatsers likhet med en eller flera referensplatser.",
    findSimilarLocationsInputTip:"Ange ett geoobjektslager som innehåller en eller flera referensplatser mot vilka geoobjekt i söklagret ska utvärderas med avseende på likhet.",
    interpolatePoints:"Interpoleringspunkter",
    interpolatePointsUsage:"Förutsäg värden i nya platser baserat på mätningar från en samling punkter.",
    interpolatePointsInputTip:"Ange de punktgeoobjekt som ska interpoleras.",
    mergeLayers:"Sammanfoga lager",
    mergeLayersUsage:"Slå samman geoobjekt från flera lager till ett nytt lager",
    mergeLayersInputTip:"Ange det geoobjektslager som ska slås samman med sammanslagningslagret.",
    overlayLayers:"Överlagra lager",
    overlayLayersUsage:"Kombinera flera lager i ett enda lager med informationen bevarad från ursprungslagren.",
    overlayLayersInputTip:"Ange det geoobjektslager som ska överlagras med överlagringslagret.",
    planRoutes:"Planera rutter",
    planRoutesUsage:"Fastställer hur du effektivt fördelar uppgifter inom en mobil arbetsstyrka.",
    planRoutesInputTip:"Ange de punkter som fordonen, förarna eller rutterna ska besöka.",
    summarizeNearby:"Summera nära",
    summarizeNearbyUsage:"Sammanfatta data inom en viss distans från geoobjekt i ett annat lager för varje geoobjekt i ett indatalager.",
    summarizeNearbyInputTip:"Ange det punkt-, linje- eller polygongeoobjektslager från vilket avstånden ska mätas till geoobjekten i sammanfattningslagret.",
    summarizeWithin:"Summera inom",
    summarizeWithinUsage:"Sammanfatta data i ett indatapolygonlager från geoobjekt i ett annat lager för varje polygon i ett annat lager.",
    summarizeWithinInputTip:"Ange det polygongeoobjektslager mot vilket sammanfattningen ska ske.",
    traceDownstream:"Spåra nedströms",
    traceDownstreamUsage:"Avgör flödesmönstren nedströms från de platser du anger.",
    traceDownstreamInputTip:"Ange de punktgeoobjekt som ska användas som startpunkter för en nedströmsspårning."
  })
);
