define(
   ({
    _widgetLabel: "차트",
    executeChartTip: "차트를 실행하려면 다음 작업 항목 중 하나를 클릭하세요.",
    invalidConfig: "잘못된 구성입니다.",
    noneChartTip: "이 위젯에 구성된 차트 태스크가 없습니다.",
    chartParams: "옵션",
    charts: "차트",
    apply: "적용",
    useSpatialFilter: "공간 필터를 사용하여 피처 제한",
    useCurrentMapExtent: "현재 맵 영역과 교차하는 피처만",
    drawGraphicOnMap: "사용자 정의된 영역과 교차하는 피처만",
    chartResults: "차트 결과",
    clearResults: "결과 지우기",
    noPermissionsMsg: "이 서비스에 접근할 권한이 없습니다.",
    specifySpatialFilterMsg: "이 작업에 대한 공간 필터를 지정하세요.",
    queryError: "쿼리하지 못했습니다.",
    noResults: "피처를 찾을 수 없습니다.",
    category: "범주",
    count: "개수",
    label: "레이블",
    horizontalAxis: "수평축",
    verticalAxis: "수직축",
    dataLabels: "데이터 레이블",
    color: "색상",
    colorful: "색상형",
    monochromatic: "단색형",
    tasks: "태스크",
    results: "결과",
    applySpatialFilterToLimitResults: "결과 제한에 공간 필터 적용",
    useCurrentExtentTip: "현재 맵 범위 내 일부 또는 전체",
    useDrawGraphicTip: "맵에 그려진 모양 내 일부 또는 전체",
    useFeaturesTip: "다른 레이어의 피처로부터의 상대적인 위치를 기반으로 함",
    noSpatialLimitTip: "결과를 공간적으로 제한하지 않음",
    applySearchDistance: "검색 거리 적용",
    spatialRelationship: "공간 릴레이션십",
    relatedLayer: "릴레이트된 레이어",
    clear: "선택 해제",
    bufferDistance: "버퍼 거리",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    back: "뒤로",
    execute: "실행"
  })
);