define(
	 ({
		chartTasks: "Zadania diagramu",
		addNew: "Dodaj nowe",
		addNewTip: "Dodaj nowe zadanie diagramu",
		name: "Nazwa",
		set: "Ustaw",
		setDataSource: "Skonfiguruj źródło danych",
		generalSettingsTip: "Skonfiguruj źródła danych, tytuły i opisy diagramów.",
		chartModeSettingTip: "Wybierz metodę analizy i sposób wyświetlania danych w postaci diagramów.",
		detailsSettingTip: "Skonfiguruj wygląd diagramu, określając jego typ i kolor oraz wartości, które zostaną na nim przedstawione:",
		symbolSettingTip: "Skonfiguruj wyświetlanie mapy dla danych przedstawionych na diagramie.",
		addFilterTip: "Dodaj filtr do danych",
		dataSource: "Źródło danych",
		noResults: "Nie odnaleziono żadnego obiektu.",
		chartTitle: "Tytuł diagramu",
		description: "Opis",
		chartingMode: "Wyświetlanie diagramu",
		featureOption: "Wyświetlaj wartości dla każdego kolejnego obiektu",
		categoryOption: "Wyświetlaj wartości wg kategorii",
		countOption: "Wyświetlaj liczbę obiektów wg kategorii",
		fieldOption: "Wyświetlaj wartości atrybutów w postaci diagramów",
		category: "Kategoria",
		axisLabel: "Etykieta kategorii",
		categoryField: "Pole kategorii",
		operation: "Operacja",
		originalOption: "Użyj oryginalnych wartości",
		sumOption: "Suma",
		averageOption: "Średnia",
		minOption: "Minimum",
		maxOption: "Wartość maks.",
		valueFields: "Pola wartości",
		moveUp: "Przesuń w górę",
		moveDown: "Przesuń w dół",
		sortOrder: "Sortuj diagramy wg etykiet kategorii",
		ascending: "Rosnąco",
		descending: "Malejąco",
		chartType: "Typ diagramu",
		column: "Diagram kolumnowy",
		bar: "Diagram słupkowy grupowy",
		line: "Diagram liniowy",
		pie: "Diagram kołowy",
		chartColor: "Kolor diagramu",
		showDataLabels: "Pokaż etykiety danych",
		setSymbol: "Symbol selekcji",
		setHighLightColor: "Kolor wyróżnienia",
		settings: "Ustawienia",
		mapInterationOptions: "Opcje interakcji z mapą",
		preview: "Podgląd",
		ok: "OK",
		cancel: "Anuluj",
		close: "Zamknij",
		setFilterTip: "Skonfiguruj poprawnie filtr. ",
		setChartTitleTip: "Skonfiguruj tytuł diagramu.",
		setChartTypeTip: "Wybierz przynajmniej jeden typ diagramu.",
		setDataFieldTip: "Wybierz przynajmniej jedno pole wartości.",
		setOutputFieldTip: "Skonfiguruj pola wyjściowe.",
		count: "Liczba",
		label: "Etykieta",
		horizontalAxis: "Oś pozioma",
		verticalAxis: "Oś pionowa",
		dataLabels: "Etykiety danych",
		color: "Kolor",
		colorful: "Kolorowe",
		monochromatic: "Monochromatyczne",
    noTaskTip: "Kliknij opcję Dodaj nowe, aby dodać zadanie diagramu",
    info: "Informacje",
    charts: "Diagramy",
    options: "Opcje",
    taskName: "Nazwa zadania",
    summary: "Podsumowanie",
    resultDescription: "Opis wyników",
    spatialFilterTip: "Wybierz filtry przestrzenne używane w widżecie, aby ograniczyć liczbę wyników.",
    defaultOption: "Domyślne",
    useCurrentExtentTip: "Częściowo lub całkowicie w bieżącym zasięgu mapy",
    useDrawGraphicTip: "Częściowo lub całkowicie w zasięgu narysowanego na mapie obszaru",
    useFeaturesTip: "Na podstawie ich lokalizacji względem obiektów na innej warstwie",
    noSpatialLimitTip: "Nie ograniczaj przestrzennie wyników wyszukiwania",
    drawingTools: "Narzędzia rysowania",
    bufferSettings: "Ustawienia bufora",
    defaultDistance: "Domyślna odległość",
    bufferDistance: "Odległość buforowania",
    defaultUnit: "Jednostka domyślna",
    miles: "Mile",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Jardy",
    nauticalMiles: "Mile morskie",
    availableSpatialRelationships: "Dostępne zależności przestrzenne",
    setSpatialRelationships: "Skonfiguruj zależności przestrzenne",
    availability: "Dostępność",
    relationship: "Zależność",
    actions: "Działania",
    intersect: "przecinają",
    contain: "zawierają",
    areContainedIn: "są zawarte w",
    cross: "krzyżują się",
    envelopeIntersect: "przecinają obwiednię",
    overlap: "nachodzą",
    areOverlapped: "są zakryte",
    touche: "dotykają",
    within: "w zasięgu",
    areWithin: "są w zasięgu",
    indexIntersect: "przecinają indeks"
  })
);