define(
   ({
    _widgetLabel: "Įvykių analizė",
    incident: "Įvykis",
    weather: "Orai",
    locate_incident: "Rasti įvykį",
    clear_incidents: "Valyti įvykius",
    reverse_geocoded_address: "Artimiausias adresas",
    reverse_geocoded_error: "Negalimas",
    miles: "Mylios",
    kilometers: "Kilometrai",
    feet: "Pėdos",
    meters: "Metrai",
    yards: "Jardai",
    nauticalMiles: "Jūrmylės",
    now: "DABAR",
    wind: "VĖJAS",
    SUN: "SEK",
    MON: "PIR",
    TUE: "ANT",
    WED: "TRE",
    THU: "KET",
    FRI: "PEN",
    SAT: "ŠEŠ",
    defaultTabMsg: "Nurodytų įvykių nėra.",
    actionLabel: "Nustatyti kaip įvykį",
    useMapExtent: "Naudoti esamą žemėlapio plotą",
    noFeaturesFound: "Elementų nerasta.",
    downloadCSV: "ATSISIŲSTI CSV",
    sum: "SUMA",
    min: "MIN.",
    max: "MAKS.",
    avg: "VID.",
    count: "KIEKIS",
    area: "PLOTAS",
    length: "ILGIS"
  })
);
