define(
   ({
    _widgetLabel: "Diagram",
    executeChartTip: "Klik op een van de volgende items om het diagram uit te voeren.",
    invalidConfig: "Ongeldige configuratie.",
    noneChartTip: "Er is geen taak geconfigureerd voor deze widget.",
    chartParams: "Opties",
    charts: "DIAGRAMMEN",
    apply: "TOEPASSEN",
    useSpatialFilter: "Ruimtelijke filter gebruiken om objecten te beperken",
    useCurrentMapExtent: "Alleen objecten die het huidige kaartgebieden kruisen",
    drawGraphicOnMap: "Alleen objecten die een door de gebruiker gedefinieerd gebied kruisen",
    chartResults: "Diagramresultaten",
    clearResults: "Resultaten wissen",
    noPermissionsMsg: "U hebt geen toestemming voor toegang tot deze service.",
    specifySpatialFilterMsg: "Specificeer een ruimtelijke filter voor deze taak.",
    queryError: "Query is mislukt.",
    noResults: "Geen object gevonden",
    category: "Categorie",
    count: "Telling",
    label: "Label",
    horizontalAxis: "Horizontale as",
    verticalAxis: "Verticale as",
    dataLabels: "Datalabels",
    color: "Kleur",
    colorful: "Kleur",
    monochromatic: "Zwart-wit",
    tasks: "Taken",
    results: "Resultaten",
    applySpatialFilterToLimitResults: "Een ruimtelijk filter toepassen om resultaten te beperken",
    useCurrentExtentTip: "Gedeeltelijk of volledig in de actuele kaart",
    useDrawGraphicTip: "Gedeeltelijk of volledig in de vorm die op de kaart getekend is",
    useFeaturesTip: "Op basis van de locaties t.o.v. de objecten in een andere laag",
    noSpatialLimitTip: "Resultaten niet ruimtelijk beperken",
    applySearchDistance: "Een zoekafstand toepassen",
    spatialRelationship: "Ruimtelijke verhouding",
    relatedLayer: "Gerelateerde laag",
    clear: "Wissen",
    bufferDistance: "Bufferafstand",
    miles: "Mijl",
    kilometers: "Kilometer",
    feet: "Voet",
    meters: "Meter",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    back: "Vorige",
    execute: "Uitvoeren"
  })
);