define(
   ({
    _widgetLabel: "Análise de Incidente",
    incident: "Incidente",
    weather: "Tempo",
    locate_incident: "Localizar Incidente",
    clear_incidents: "Apagar Incidentes",
    reverse_geocoded_address: "Endereço mais próximo",
    reverse_geocoded_error: "Não Disponível",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    now: "AGORA",
    wind: "VENTO",
    SUN: "DOM",
    MON: "SEG",
    TUE: "TER",
    WED: "QUA",
    THU: "QUI",
    FRI: "SEX",
    SAT: "SAB",
    defaultTabMsg: "Nenhum incidente identificado.",
    actionLabel: "Configurar como Incidente",
    useMapExtent: "Utilize a extensão de mapa atual",
    noFeaturesFound: "Nenhuma feição foi encontrada.",
    downloadCSV: "DOWNLOAD DE CSV",
    sum: "SOMA",
    min: "MÍN",
    max: "MÁX",
    avg: "MÉDIA",
    count: "CONTAGEM",
    area: "ÁREA",
    length: "COMPRIMENTO"
  })
);
