define(
   ({
    routeUrl: "URL маршрута",
    locatorUrl: "URL-адрес геокодера",
    geocoderOptions: "Параметры геокодирования",
    autoComplete: "Автозавершение",
    maxLocations: "Максимум местоположений",
    minCharacters: "Минимум символов",
    searchDelay: "Задержка поиска",
    placeholder: "Заполнитель",
    routeOptions: "Параметры маршрута",
    directionsLanguage: "Язык путевого листа",
    directionsLengthUnits: "Единицы длины маршрута",
    directionsOutputType: "Тип выходных данных маршрутов",
    impedanceAttribute: "Атрибут импеданса",
    kilometers: "Километры",
    miles: "Мили",
    meters: "Метры",
    feet: "Футы",
    yards: "Ярды",
    nauticalMiles: "Морские мили",
    parametersTip: "Установите параметры корректно !",
    complete: "Завершено",
    completeNoEvents: "Завершено, событий нет",
    instructionsOnly: "Только инструкции",
    standard: "Стандартно",
    summaryOnly: "Только сводка",
    travelModesUrl: "URL-адрес режимов передвижения",
    searchPlaceholder: "Найти адрес или место",
    trafficLayerUrl: "URL-адрес слоя трафика"
  })
);