define(
   ({
    _widgetLabel: "Sorgu",
    executeQueryTip: "Sorguyu işlemek için aşağıdaki öğelerden birine tıklayın.",
    invalidConfig: "Geçersiz yapılandırma. Doğru yapılandırmayı almak için Sorgu ayarı sayfasını kullanın.",
    queryParams: "Seçenekler",
    parameters: "SEÇENEKLER",
    queries: "SORGULAR",
    apply: "UYGULA",
    queryResults: "Sonuçlar",
    clear: "Temizle",
    noResults: "Detay bulunamadı.",
    queryError: "Sorgu başarısız!",
    numberFound: "Bulunan detay sayısı",
    mapExtentTip: "Sonuçları geçerli harita yayılımı ile sınırlayın.",
    noValue: "Değer yok",
    and: "ve",
    stringOperatorIs: "alanı şu olanlar", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "alanı şu olmayanlar",
    stringOperatorStartsWith: "alanı şununla başlayanlar",
    stringOperatorEndsWith: "alanı şununla bitenler",
    stringOperatorContains: "alanı şunu içerenler",
    stringOperatorDoesNotContain: "alanı şunu içermeyenler",
    stringOperatorIsBlank: "alanı boş olanlar",
    stringOperatorIsNotBlank: "alanı boş olmayanlar",
    dateOperatorIsOn: "alanı şu tarihte olanlar", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "alanı şu tarihte olmayanlar",
    dateOperatorIsBefore: "alanı şu tarihten önce olanlar",
    dateOperatorIsAfter: "alanı şu tarihten sonra olanlar",
    dateOperatorDays: "gün içinde",
    dateOperatorWeeks: "hafta içinde", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "ay içinde",
    dateOperatorInTheLast: "alanı son şu dönemde olanlar",
    dateOperatorNotInTheLast: "alanı son şu dönemde olmayanlar",
    dateOperatorIsBetween: "alanı şu tarihler arasında olanlar",
    dateOperatorIsNotBetween: "alanı şu tarihler arasında olmayanlar",
    dateOperatorIsBlank: "alanı boş olanlar",
    dateOperatorIsNotBlank: "alanı boş olmayanlar",
    numberOperatorIs: "alanı şu olanlar", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "alanı şu olmayanlar",
    numberOperatorIsAtLeast: "alanı en az şu olanlar",
    numberOperatorIsLessThan: "alanı şundan küçük olanlar",
    numberOperatorIsAtMost: "alanı en çok şu olanlar",
    numberOperatorIsGreaterThan: "alanı şundan büyük olanlar",
    numberOperatorIsBetween: "alanı şu tarihler arasında olanlar",
    numberOperatorIsNotBetween: "alanı şu tarihler arasında olmayanlar",
    numberOperatorIsBlank: "alanı boş olanlar",
    numberOperatorIsNotBlank: "alanı boş olmayanlar",
    operationalLayerTip: "Sonucu işlemsel katman olarak ekle",
    queryResult: "Sorgu Sonucu",
    specifyParamsTip: "Bu görev için parametreleri belirle",
    useSpatialFilter: "Özellikleri sınırlandırmak için mekansal filtre kullan",
    useCurrentMapExtent: "Yalnızca detaylar geçerli harita yayılımına temas eder",
    drawGraphicOnMap: "Yalnızca özellikler kullanıcı tanımlı bir alana temas eder",
    specifySpatialFilterMsg: "Bu görev için mekansal filtreyi belirtin.",
    clearResults: "Sonuçları Temizle",
    operationalTip: 'Bu seçenek işaretlendiğinde, \"${clearResults}\" düğmesi tıklanana kadar sonuçlar haritada kalır.',
    noneQueryTip: "Önceden yapılandırılmış sorgu görevi yok.",
    noPermissionsMsg: "Bu servise erişmek için izniniz yok."
  })
);