define(
   ({
    _widgetLabel: "Диаграмма",
    executeChartTip: "Щелкните один из следующих элементов задания, чтобы выполнить диаграмму.",
    invalidConfig: "Недопустимая конфигурация.",
    noneChartTip: "Для данного виджета не настроены задачи.",
    chartParams: "Опции",
    charts: "ДИАГРАММЫ",
    apply: "ПРИМЕНИТЬ",
    useSpatialFilter: "Использовать пространственный фильтр для ограничения объектов",
    useCurrentMapExtent: "Только объекты, пересекающие область текущей карты",
    drawGraphicOnMap: "Только объекты, пересекающие заданную пользователем область",
    chartResults: "Нанести результаты на диаграмму",
    clearResults: "Очистить результаты",
    noPermissionsMsg: "У вас нет разрешения на доступ к этому сервису.",
    specifySpatialFilterMsg: "Укажите пространственный фильтр для этой задачи.",
    queryError: "Запрос не удался.",
    noResults: "Объекты не найдены.",
    category: "Категория",
    count: "Число",
    label: "Надпись",
    horizontalAxis: "Горизонтальная ось",
    verticalAxis: "Вертикальная ось",
    dataLabels: "Надписи данных",
    color: "Цвет",
    colorful: "Цветная",
    monochromatic: "Монохромная",
    tasks: "Задачи",
    results: "Результаты",
    applySpatialFilterToLimitResults: "Применить пространственный фильтр для ограничения результатов",
    useCurrentExtentTip: "Частично или полностью в пределах текущего экстента карты",
    useDrawGraphicTip: "Частично или полностью в пределах фигуры на карте",
    useFeaturesTip: "На основе местоположения относительно объектов другого слоя",
    noSpatialLimitTip: "Не ограничивать результаты пространственным фильтром",
    applySearchDistance: "Применить расстояние поиска",
    spatialRelationship: "Пространственное отношение",
    relatedLayer: "Связанный слой",
    clear: "Очистить",
    bufferDistance: "Буферное расстояние",
    miles: "Мили",
    kilometers: "Километры",
    feet: "Футы",
    meters: "Метры",
    yards: "Ярды",
    nauticalMiles: "Морские мили",
    back: "Назад",
    execute: "Выполнить"
  })
);