define(
   ({
    taskUrl: "Taak-URL",
    serviceURLPlaceholder: "Voer de URL van de geoprocessingtaak in",
    ok: "OK",
    cancel: "Annuleren",
    layer: "Kaartlaag",
    action: "Handeling",
    input: "Invoer",
    output: "Uitvoer",
    name: "Naam",
    type: "Type",
    required: "Vereist",
    layerOrder: "Laagvolgorde",
    options: "Opties",
    defaultValue: "Standaardwaarde",
    inputFeatureBy: "Invoerobject op",
    renderer: "Renderer",
    displayType: "Weeergavetype",
    label: "Label",
    tooltip: "Tooltip",
    visible: "Zichtbaar",
    helpUrl: "Help-URL",
    useResultMapService: "De tekenopties van de resultaatmapservice gebruiken",
    drawOnMap: "Interactief tekenen op de kaart",
    selectLayer: "Een kaartlaag selecteren vanaf de kaart",
    url: "URL",
    symbol: "Symbool",
    shareResults: "Resultaat toevoegen als operationele laag",
    popup: "Popup",
    setTask: "Instellen",
    setTaskTitle: "GP-taak instellen",
    enablePopup: "Pop-up inschakelen",
    unSupportGeometryType: "Kan geen renderer instellen vanwege onbekend geometrietype.",
    useUrlForGPInput: ".URL",
    useUploadForGPInput: "Bestand uploaden",
    selectFileToUpload: "Bestand selecteren...",
    upload: "Uploaden",
    rasterFormat: "Bestandsformaat rooster",
    noFileSelected: "Geen bestand geselecteerd!",
    uploadSuccess:"Bestand güpload!",
    showLayerContent: "Content van de laag weergeven",
    Feet: "Voet",
    Yards: "Yard",
    Miles: "Mijl",
    NauticalMiles: "Zeemijl",
    Meter: "Meter",
    Kilometers: "Kilometer",
    urlPlaceholder: "Feature set URL",
    allowToExport: "Resultaten exporteren"
  })
);
