define(
   ({
    taskUrl: "Taak-URL",
    serviceURLPlaceholder: "Voer de URL van de geoprocessingtaak in",
    ok: "OK",
    cancel: "Annuleren",
    layer: "Kaartlaag",
    action: "Handeling",
    input: "Invoer",
    output: "Uitvoer",
    name: "Naam",
    type: "Type",
    required: "Vereist",
    layerOrder: "Laagvolgorde",
    options: "Opties",
    defaultValue: "Standaardwaarde",
    inputFeatureBy: "Invoerobject op",
    renderer: "Renderer",
    displayType: "Weeergavetype",
    label: "Label",
    tooltip: "Tooltip",
    visible: "Zichtbaar",
    helpUrl: "Help-URL",
    useResultMapService: "De tekenopties van de resultaatmapservice gebruiken",
    drawOnMap: "Interactief tekenen op de kaart",
    selectLayer: "Een kaartlaag selecteren vanaf de kaart",
    url: "URL",
    symbol: "Symbool",
    shareResults: "Resultaat toevoegen als operationele laag",
    popup: "Popup",
    setTask: "Instellen",
    setTaskTitle: "GP-taak instellen",
    enablePopup: "Pop-up inschakelen"
  })
);