define(
   ({
    routeUrl: "Rotalama URL\'si",
    locatorUrl: "Coğrafi Kodlayıcı URL\'si",
    geocoderOptions: "Coğrafi kodlayıcı seçenekleri",
    autoComplete: "Otomatik Tamamla",
    maxLocations: "Maksimum konum sayısı",
    minCharacters: "Minimum karakter sayısı",
    searchDelay: "Arama gecikmesi",
    placeholder: "Yer Tutucu",
    routeOptions: "Rota seçenekleri",
    directionsLanguage: "Yol tarifi dili",
    directionsLengthUnits: "Yol tarifi uzunluk birimi",
    directionsOutputType: "Yol tarifi çıktı türü",
    impedanceAttribute: "Empedans özniteliği",
    kilometers: "Kilometre",
    miles: "Mil",
    meters: "Metre",
    feet: "Fit",
    yards: "Yarda",
    nauticalMiles: "Deniz Mili",
    parametersTip: "Parametreleri doğru ayarlayın!",
    complete: "Tamam",
    completeNoEvents: "Hiçbir Olayı Tamamlama",
    instructionsOnly: "Yalnızca Talimatlar",
    standard: "Standart",
    summaryOnly: "Yalnızca Özet",
    travelModesUrl: "Seyahat Modları URL\'si",
    searchPlaceholder: "Adres veya yer bul",
    trafficLayerUrl: "Trafik katmanı URL\'si"
  })
);