define(
   ({
    taskUrl: "작업 URL",
    serviceURLPlaceholder: "지오프로세싱 작업 URL을 입력하세요.",
    ok: "확인",
    cancel: "취소",
    layer: "레이어",
    action: "작업",
    input: "입력",
    output: "결과",
    name: "이름",
    type: "유형",
    required: "필요한 정보",
    layerOrder: "레이어 순서",
    options: "옵션",
    defaultValue: "기본 값",
    inputFeatureBy: "다음에 의한 피처 입력",
    renderer: "렌더러",
    displayType: "표시 유형",
    label: "레이블",
    tooltip: "도구 팁",
    visible: "표시",
    helpUrl: "도움말 URL",
    useResultMapService: "결과 맵 서비스의 그리기 옵션 사용",
    drawOnMap: "맵에 대화식으로 그리기",
    selectLayer: "맵에서 레이어 선택",
    url: "URL",
    symbol: "심볼",
    shareResults: "결과를 운영 레이어로 추가",
    popup: "팝업",
    setTask: "설정",
    setTaskTitle: "GP 작업 설정",
    enablePopup: "팝업 사용"
  })
);