define(
   ({
    taskUrl: "작업 URL",
    serviceURLPlaceholder: "지오프로세싱 작업 URL을 입력하세요.",
    ok: "확인",
    cancel: "취소",
    layer: "레이어",
    action: "작업",
    input: "입력",
    output: "결과",
    name: "이름",
    type: "유형",
    required: "필요한 정보",
    layerOrder: "레이어 순서",
    options: "옵션",
    defaultValue: "기본 값",
    inputFeatureBy: "다음에 의한 피처 입력",
    renderer: "렌더러",
    displayType: "표시 유형",
    label: "레이블",
    tooltip: "도구 팁",
    visible: "표시",
    helpUrl: "도움말 URL",
    useResultMapService: "결과 맵 서비스의 그리기 옵션 사용",
    drawOnMap: "맵에 대화식으로 그리기",
    selectLayer: "맵에서 레이어 선택",
    url: "URL",
    symbol: "심볼",
    shareResults: "결과를 운영 레이어로 추가",
    popup: "팝업",
    setTask: "설정",
    setTaskTitle: "GP 작업 설정",
    enablePopup: "팝업 사용",
    unSupportGeometryType: "알 수 없는 지오메트리 유형으로 인해 렌더러를 설정할 수 없습니다.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "파일 업로드",
    selectFileToUpload: "파일 선택...",
    upload: "업로드",
    rasterFormat: "래스터 데이터 형식",
    noFileSelected: "선택한 파일 없음",
    uploadSuccess:"파일 업로드 완료",
    showLayerContent: "레이어 콘텐츠 보기",
    Feet: "피트",
    Yards: "야드",
    Miles: "마일",
    NauticalMiles: "해리",
    Meter: "미터",
    Kilometers: "킬로미터",
    urlPlaceholder: "기능 모음 URL",
    allowToExport: "결과 내보내기 허용"
  })
);
