define(
   ({
    _widgetLabel: "Báo cáo Đối tượng",
    select: "Chọn",
    draw: "Vẽ",
    chooseALayer: "Chọn một lớp",
    clickAFeature: "Bấm vào đối tượng trên bản đồ để chọn đối tượng đó.",
    loadingFeatures: "Đang tải thông tin chi tiết về đối tượng được chọn...",
    errorTitle: "Lỗi",
    errorIdentify: "Lỗi xác định đối tượng. Vui lòng xem nhật ký trên bảng điều khiển để biết thông tin chi tiết.",
    infoWindowTitle: "Chi tiết",
    layerLabel: "Tên lớp",
    reviewStatusLabel: "Trạng thái Xem xét",
    selectReviewStatusAdd: "Thêm Đối tượng",
    selectReviewStatusDelete: "Xóa Đối tượng",
    selectReviewStatusMove: "Di chuyển Đối tượng",
    selectReviewStatusReshape: "Tạo lại hình dạng Đối tượng",
    drawReviewStatusMissing: "(Các) Đối tượng Bị thiếu",
    drawReviewStatusPosition: "Lỗi Vị trí",
    drawReviewStatusShape: "Lỗi Hình dạng",
    drawReviewStatusAttribute: "Lỗi Thuộc tính",
    notesLabel: "Lưu ý",
    severityLabel: "Mức độ nghiêm trọng",
    reportedByLabel: "Người Báo cáo",
    reportedByDefault: "ẩn danh",
    reportButton: "Báo cáo",
    reportMessage: "Báo cáo đã nhận được",
    errorReportMessage: "Đã xảy ra lỗi khi báo cáo đối tượng của bạn",
    drawErrorInstructions: "Chọn điểm, đường hoặc đa giác và vẽ mẫu hình học của lỗi trên bản đồ:",
    errorMapService: "Đã xảy ra lỗi khi tải thông tin dịch vụ bản đồ",
    noFeatureSelected : "Không tìm thấy đối tượng nào tại vị trí đã bấm",
    selectFeatureMapPoint: "Bấm để chọn một đối tượng",
    drawFeatureMapPoint: "Bấm để thêm điểm",
    popupMessage:"Thông báo",
    popupError:"Lỗi",
    manyFeaturesSelected: "Đã tìm thấy nhiều đối tượng. Vui lòng phóng to và chọn một đối tượng để báo cáo."
  })
);
