define(
   ({
    _widgetLabel: "Gráfico",
    executeChartTip: "Haz clic en una de las siguientes tareas para ejecutar el gráfico.",
    invalidConfig: "Configuración no válida.",
    noneChartTip: "No se ha configurado ninguna tarea de gráfico para este widget.",
    chartParams: "Opciones",
    charts: "GRÁFICOS",
    apply: "APLICAR",
    useSpatialFilter: "Usar filtro espacial para limitar las entidades",
    useCurrentMapExtent: "Solo entidades que intersequen el área de mapa actual",
    drawGraphicOnMap: "Solo entidades que intersequen un área definida por el usuario",
    chartResults: "Resultados del gráfico",
    clearResults: "Borrar resultados",
    noPermissionsMsg: "No tienes permisos para acceder a este servicio.",
    specifySpatialFilterMsg: "Especifica un filtro espacial para esta tarea.",
    queryError: "Error de la consulta.",
    noResults: "Ninguna entidad encontrada.",
    category: "Categoría",
    count: "Recuento",
    label: "Etiqueta",
    horizontalAxis: "Eje horizontal",
    verticalAxis: "Eje vertical",
    dataLabels: "Etiquetas de datos",
    color: "Color",
    colorful: "Multicolor",
    monochromatic: "Monocromático",
    tasks: "Tareas",
    results: "Resultados",
    applySpatialFilterToLimitResults: "Aplicar un filtro espacial para limitar los resultados",
    useCurrentExtentTip: "Parcial o totalmente dentro de la extensión de mapa actual",
    useDrawGraphicTip: "Parcial o totalmente dentro de la forma dibujada en el mapa",
    useFeaturesTip: "En función de sus ubicaciones con respecto a las entidades de otra capa",
    noSpatialLimitTip: "No limitar espacialmente los resultados",
    applySearchDistance: "Aplicar una distancia de búsqueda",
    spatialRelationship: "Relación espacial",
    relatedLayer: "Capa relacionada",
    clear: "Borrar",
    bufferDistance: "Distancia de zona de influencia",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    back: "Atrás",
    execute: "Ejecutar"
  })
);