define(
	 ({
		chartTasks: "차트 작업",
		addNew: "새로 추가",
		addNewTip: "새 차트 작업 추가",
		name: "이름",
		set: "설정",
		setDataSource: "데이터 원본 설정",
		generalSettingsTip: "차트에 대한 데이터 원본, 제목 및 설명을 설정합니다.",
		chartModeSettingTip: "데이터를 분석하고 차트로 표시할 방법을 선택합니다.",
		detailsSettingTip: "차트의 유형, 색상, 차트로 나타낼 값을 지정하여 차트 모양을 설정합니다.",
		symbolSettingTip: "차트로 표시될 데이터에 대한 맵 디스플레이를 설정합니다.",
		addFilterTip: "필터를 이 데이터에 추가",
		dataSource: "데이터 원본",
		noResults: "피처를 찾을 수 없습니다.",
		chartTitle: "차트 제목",
		description: "설명",
		chartingMode: "차트 디스플레이",
		featureOption: "각 피처별로 값 표시",
		categoryOption: "범주별로 값 표시",
		countOption: "범주별로 피처 개수 표시",
		fieldOption: "차트로 속성 값 표시",
		category: "범주",
		axisLabel: "범주 레이블",
		categoryField: "범주 필드",
		operation: "작업",
		originalOption: "원래 값 사용",
		sumOption: "합계",
		averageOption: "평균",
		minOption: "최소",
		maxOption: "최대",
		valueFields: "값 필드",
		moveUp: "위로 이동",
		moveDown: "아래로 이동",
		sortOrder: "범주 레이블로 차트 순서 정렬",
		ascending: "오름차순",
		descending: "내림차순",
		chartType: "차트 유형",
		column: "세로 막대형 차트",
		bar: "가로 막대형 차트",
		line: "꺾은선형 차트",
		pie: "파이 차트",
		chartColor: "차트 색상",
		showDataLabels: "데이터 레이블 표시",
		setSymbol: "선택 심볼",
		setHighLightColor: "강조 색상",
		settings: "설정",
		mapInterationOptions: "맵 상호 작용 옵션",
		preview: "미리보기",
		ok: "확인",
		cancel: "취소",
		close: "닫기",
		setFilterTip: "필터를 올바르게 설정하세요. ",
		setChartTitleTip: "차트 제목을 설정하세요.",
		setChartTypeTip: "적어도 차트 유형 한 개를 선택하세요.",
		setDataFieldTip: "적어도 값 필드 한 개를 선택하세요.",
		setOutputFieldTip: "출력 필드를 설정하세요.",
		count: "개수",
		label: "레이블",
		horizontalAxis: "수평축",
		verticalAxis: "수직축",
		dataLabels: "데이터 레이블",
		color: "색상",
		colorful: "색상형",
		monochromatic: "단색형",
    noTaskTip: "차트 태스크를 추가하려면 새로 추가를 클릭합니다.",
    info: "정보",
    charts: "차트",
    options: "옵션",
    taskName: "작업 이름",
    summary: "요약",
    resultDescription: "결과 설명",
    spatialFilterTip: "결과를 제한하는 위젯에 사용되는 공간 필터를 선택합니다.",
    defaultOption: "기본값",
    useCurrentExtentTip: "현재 맵 범위 내 일부 또는 전체",
    useDrawGraphicTip: "맵에 그려진 모양 내 일부 또는 전체",
    useFeaturesTip: "다른 레이어의 피처에서 상대적인 위치를 기반으로 함",
    noSpatialLimitTip: "결과를 공간적으로 제한하지 않음",
    drawingTools: "그리기 도구",
    bufferSettings: "버퍼 설정",
    defaultDistance: "기본 거리",
    bufferDistance: "버퍼 거리",
    defaultUnit: "기본 단위",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    availableSpatialRelationships: "사용 가능한 공간 릴레이션십",
    setSpatialRelationships: "공간 릴레이션십 설정",
    availability: "사용 가능 여부",
    relationship: "릴레이션십",
    actions: "동작",
    intersect: "교차",
    contain: "포함",
    areContainedIn: "은(는) 다음에 포함됨:",
    cross: "건너감",
    envelopeIntersect: "엔빌롭 교차",
    overlap: "겹치기",
    areOverlapped: "이(가) 겹침",
    touche: "접함",
    within: "내",
    areWithin: "이(가) 다음 내에 있음:",
    indexIntersect: "색인 교차"
  })
);