define({
  root: ({
    configError: "Widget is not properly configured.",
    clearButtonValue: "Clear",
    resultPanelhading: "Results",
    GPExecutionFailed: "The trace cannot be completed. Please try again.",
    lblExportToCSV: "Export to CSV",
    lblSaveToLayer: "Save to layer",
    backButtonValue: "Back",
    lblSaveButtonValue: "Save",
    btnSaveExportToLayer: "Save",
    summaryPanel: "Output summary",
    outageAreaLabel: "Overview",
    saveToLayerSuccess: "Save to layer is successfully completed.",
    ExportToCSVtooltip: "Export to CSV",
    exportToCSVSuccess: "Export to CSV is successfully completed.",
    noLayerSelectedForExportToCSV: "No layer is selected.",
    saveToLayertoolTip: "Save to layer",
    unableToSaveLayer: "Unable to save one or more of the selected layers.",
    noLayerToSave: "No layers selected to save.",
    noChangeToSave: "No changes to save.",
    unavailableLayersError: "Could not find ${0} layer(s) in webmap to save the results.",
    lblInputLocTab: "Input Locations",
    lblBlockLocTab: "Block Locations",
    lblInputLocation: "Input Feature",
    lblBlockLocation: "Block Feature",
    lblInputLocHeader: "Input Locations (0)",
    lblBlockLocHeader: "Block Locations (0)",
    atLeastOneInputLoc: "Atleast one Input Location is required",
    inputTabTitle: "Input",
    outputTabTitle: "Output"
  })
});
