define(
   ({
    _widgetLabel: "Relatório da Feição",
    select: "Selecionar",
    draw: "Desenhar",
    chooseALayer: "Selecione uma camada",
    clickAFeature: "Clique na feição no mapa para selecioná-la.",
    loadingFeatures: "Obtendo detalhes da feição selecionada...",
    errorTitle: "Erro",
    errorIdentify: "Identifique os erros de feições. Verifique log de console para detalhes.",
    infoWindowTitle: "Detalhes",
    layerLabel: "Nome da Camada",
    reviewStatusLabel: "Revisar Status",
    selectReviewStatusAdd: "Adicionar Feição",
    selectReviewStatusDelete: "Excluir Feição",
    selectReviewStatusMove: "Mover Feição",
    selectReviewStatusReshape: "Remodelar Feição",
    drawReviewStatusMissing: "Feições Ausentes",
    drawReviewStatusPosition: "Erro Posicional",
    drawReviewStatusShape: "Erro de Formato",
    drawReviewStatusAttribute: "Erro de Atributo",
    notesLabel: "Observações",
    severityLabel: "Severidade",
    reportedByLabel: "Reportado Por",
    reportedByDefault: "anônimo",
    reportButton: "Relatório",
    reportMessage: "Relatório recebido",
    errorReportMessage: "Ocorreu um erro ao reportar sua feição",
    drawErrorInstructions: "Selecione ponto, linha ou polígono e desenhe a geometria de erro no mapa:",
    errorMapService: "Ocorreu um erro ao obter informações de serviço do mapa",
    noFeatureSelected : "Nenhuma feição localizada na posição selecionada",
    selectFeatureMapPoint: "Clique para selecionar uma feição",
    drawFeatureMapPoint: "Clique para adicionar um ponto",
    popupMessage:"Mensagem",
    popupError:"Erro",
    manyFeaturesSelected: "Mais de uma feição localizada. Amplie e selecione uma feição para reportar."
  })
);
