define({
  root: ({
    placeholder: "Placeholder Text",
    url: "Geocoder URL",
    name: "Geocoder Name",
    example: "Example",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Can not get the configurations of geocoder from portal',
    actions: "Actions",
    warning: "Incorrect Service",
    instruction: "Establish the geocoders that will be used in this widget. Click Add Geocoder to reference a URL, specify a user friendly name, and set other properties. You can also reorder, configure, or delete your geocoders below.",
    add: "Add Geocoder",
    edit: "Edit Geocoder",
    ok: "OK",
    cancel: "Cancel",
    geocoderNamePlaceHolder: "My Geocoder",
    geocodePlaceHolder: "Find address or place",
    REPEATING_ERROR: "The following fields are repeated: "
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});