define(
   ({
    "tabs_section_Label": "tabbladen",
    "addTab": "Tabblad toevoegen",
    "layerName": "Kaartlaag",
    "layerType": "Analysetype",
    "layerLabel": "Label",
    "actions": "Acties",
    "closest": "Dichtstbijzijnde object",
    "proximity": "Nabijheid",
    "summary": "Samenvatting",
    "select_lbl": "-- Selecteren --",
    "general_setting_Label": "Algemene instellingen",
    "units_text_lbl": "Afstandseenheden",
    "miles": "Mijl",
    "kilometers": "Kilometer",
    "feet": "Voet",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Zeemijl",
    "maximum_distance_lbl": "Dichtstbijzijnde object maximale afstand",
    "buffer_text_lbl": "Bufferlabel",
    "buffer_lbl": "Bufferafstand",
    "buffer_max_lbl": "Maximale bufferafstand",
    "buffer_min_lbl": "Minimale bufferafstand",
    "routing_checkBox": "Routeren inschakelen",
    "weather_Label": "Weeropties",
    "weather_checkBox": "Weerberichten opnemen",
    "selectLayers": "Weerlagen selecteren",
    "currentlySelectedLayer": "Momenteel geselecteerde weerlagen",
    "missingTabLabel": "Er ontbreekt minstens één label in het tabblad",
    "cancel": "Annuleren",
    "ok": "OK",
    "missingLayerInWebMap": "Geen operationele lagen gevonden.",
    "selectFields": "Velden selecteren",
    "addField": "Veld toevoegen",
    "sum": "SOM",
    "min": "MIN",
    "max": "MAX",
    "avg": "GEM",
    "count": "TELLEN",
    "area": "GEBIED",
    "length": "LENGTE",
    "count_checkBox": "Aantal weergeven",
    "area_checkBox": "Oppervlakte weergeven",
    "length_checkBox": "Lengte weergeven",
    "max_records": "Maximumlimiet bereikt"
  })
);
