define(
   ({
    _widgetLabel: "Yazdır",
    title: "Harita Başlığı",
    format: "Biçim",
    layout: "Düzen",
    settings: "Gelişmiş",
    mapScaleExtent: "Harita ölçeği/yayılımı",
    preserve: "Koru",
    mapScale: "harita ölçeği",
    mapExtent: "harita yayılımı",
    forceScale: "Ölçeği zorla",
    getCurrentScale: "mevcut",
    mapMetadata: "Düzen meta verisi",
    author: "Yazar",
    copyright: "Telif Hakkı",
    fullLayoutOptions: "Tam düzen seçenekleri",
    scaleBarUnitsMetric: "Ölçek çubuğu birimi, metrik",
    scaleBarUnitsNonMetric: "Ölçek çubuğu birimi, metrik olmayan",
    unitsMiles: "Mil",
    unitsKilometers: "Kilometre",
    unitsMeters: "Metre",
    unitsFeet: "Fit",
    unitsYards: "Yarda",
    unitsNauticalMiles: "Deniz Mili",
    lncludeLegend: "Gösterim ekle",
    printQualityOptions: "Baskı kalitesi",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY boyutu",
    width: "Genişlik (px)",
    height: "Yükseklik (px)",
    print: "Yazdır",
    clearList: "Baskıları Temizle",
    creatingPrint: "Baskı Oluşturuluyor",
    printError: "Hata, yeniden deneyin"
  })
);