define(
   ({
    _widgetLabel: "Biểu đồ",
    executeChartTip: "Bấm vào một trong các mục tác vụ sau để chạy biểu đồ.",
    invalidConfig: "Cấu hình không hợp lệ.",
    noneChartTip: "Không có tác vụ biểu đồ nào được cấu hình cho tiện ích này.",
    chartParams: "Tùy chọn",
    charts: "BIỂU ĐỒ",
    apply: "ÁP DỤNG",
    useSpatialFilter: "Sử dụng bộ lọc không gian để giới hạn các đối tượng",
    useCurrentMapExtent: "Chỉ các đối tượng giao cắt với khu vực bản đồ hiện tại",
    drawGraphicOnMap: "Chỉ các đối tượng giao cắt với khu vực do người dùng xác định",
    chartResults: "Kết quả Biểu đồ",
    clearResults: "Xóa Kết quả",
    noPermissionsMsg: "Bạn không có quyền truy cập vào dịch vụ này.",
    specifySpatialFilterMsg: "Vui lòng chỉ định bộ lọc không gian cho tác vụ này.",
    queryError: "Truy vấn không thành công.",
    noResults: "Không tìm thấy đối tượng nào.",
    category: "Thể loại",
    count: "Số lượng",
    label: "Nhãn",
    horizontalAxis: "Trục ngang",
    verticalAxis: "Trục dọc",
    dataLabels: "Nhãn Dữ liệu",
    color: "Màu sắc",
    colorful: "Nhiều màu sắc",
    monochromatic: "Đơn sắc",
    tasks: "Tác vụ",
    results: "Kết quả",
    applySpatialFilterToLimitResults: "Áp dụng bộ lọc không gian để giới hạn kết quả",
    useCurrentExtentTip: "Từng phần hoặc toàn bộ trong kích thước bản đồ hiện tại",
    useDrawGraphicTip: "Từng phần hoặc toàn bộ trong hình dạng đã được vẽ trên bản đồ",
    useFeaturesTip: "Dựa trên vị trí của chúng liên quan đến các đối tượng trong lớp khác",
    noSpatialLimitTip: "Không giới hạn các kết quả theo không gian",
    applySearchDistance: "Áp dụng khoảng cách tìm kiếm",
    spatialRelationship: "Mối quan hệ về Không gian",
    relatedLayer: "Lớp có Liên quan",
    clear: "Xóa",
    bufferDistance: "Khoảng cách Đệm",
    miles: "Dặm",
    kilometers: "Kilômét",
    feet: "Feet",
    meters: "Mét",
    yards: "Thước",
    nauticalMiles: "Hải lý",
    back: "Quay lại",
    execute: "Thực hiện"
  })
);