define(
   ({
    _widgetLabel: "Conştientizare situaţie (Beta)",
    locate_incident: "Localizare incident",
    clear_incidents: "Golire incidente",
    reverse_geocoded_address: "Cea mai apropiată adresă",
    reverse_geocoded_error: "Indisponibil",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    now: "ACUM",
    wind: "VÂNT",
    SUN: "DUM",
    MON: "LUN",
    TUE: "MAR",
    WED: "MIE",
    THU: "JOI",
    FRI: "VIN",
    SAT: "SÂM",
    defaultTabMsg: "Niciun incident identificat.",
    actionLabel: "Setare ca incident",
    drawPoint: "Trasare punct",
    drawLine: "Trasare linie",
    drawPolygon: "Trasare poligon",
    saveIncident: "Salvare incident",
    clearIncident: "Golire incident",
    useMapExtent: "Utilizare extindere curentă a hărţii",
    noFeaturesFound: "Nu a fost găsit niciun obiect spaţial.",
    downloadCSV: "DESCĂRCARE CSV",
    editComplete: "Obiect spaţial salvat cu succes!",
    updateComplete: "Obiect spaţial actualizat cu succes!",
    deleteComplete: "Obiect spaţial şters cu succes!",
    sum: "SUMĂ",
    min: "MIN.",
    max: "MAX",
    avg: "MED.",
    count: "NUMĂR",
    area: "SUPRAFAŢĂ",
    length: "LUNGIME",
    notPolySave: "Specificaţi o distanţă de buffer înainte de a salva.",
    update_btn: "Actualizare",
    delete_btn: "Ştergere"
  })
);
