define(
   ({
    routeUrl: "路徑 URL",
    locatorUrl: "地理編碼器 URL",
    geocoderOptions: "地理編碼器選項",
    autoComplete: "自動完成",
    maxLocations: "最大位置數",
    minCharacters: "最小字元數",
    searchDelay: "搜尋延遲",
    placeholder: "占位符",
    routeOptions: "路線選項",
    directionsLanguage: "導航語言",
    directionsLengthUnits: "導航長度單位",
    directionsOutputType: "導航輸出類型",
    impedanceAttribute: "阻抗屬性",
    kilometers: "公里",
    miles: "英里",
    meters: "公尺",
    feet: "英呎",
    yards: "碼",
    nauticalMiles: "海哩",
    parametersTip: "請正確設置參數！",
    complete: "完成",
    completeNoEvents: "未完成任何事件",
    instructionsOnly: "僅說明",
    standard: "標準",
    summaryOnly: "僅摘要",
    travelModesUrl: "行進模式 URL",
    searchPlaceholder: "尋找位址或地點",
    trafficLayerUrl: "交通圖層 URL"
  })
);