define(
   ({
    routeUrl: "Rute-URL",
    locatorUrl: "Geokodnings-URL",
    geocoderOptions: "Indstillinger for geokodning",
    autoComplete: "Auto-fuldfør",
    maxLocations: "Maksimalt antal steder",
    minCharacters: "Minimalt antal tegn",
    searchDelay: "Søgeforsinkelse",
    placeholder: "Pladsholder",
    routeOptions: "Indstillinger for rute",
    directionsLanguage: "Sprog til kørselsvejledninger",
    directionsLengthUnits: "Længdeenheder til kørselsvejledninger",
    directionsOutputType: "Outputtype til kørselsvejledninger",
    impedanceAttribute: "Impedansattribut",
    kilometers: "Kilometer",
    miles: "Miles",
    meters: "Meter",
    feet: "Fod",
    yards: "Yards",
    nauticalMiles: "Sømil",
    parametersTip: "Angiv parametrene korrekt!",
    complete: "Fuldført",
    completeNoEvents: "Fuldført uden hændelser",
    instructionsOnly: "Kun instruktioner",
    standard: "Standard",
    summaryOnly: "Kun oversigt",
    travelModesUrl: "URL til rejsetilstande",
    searchPlaceholder: "Find adresse eller sted",
    trafficLayerUrl: "Trafiklag-URL"
  })
);