define(
   ({
    _widgetLabel: "Udskriv",
    title: "Kortets titel",
    format: "Formatér",
    layout: "Layout",
    settings: "Avanceret",
    mapScaleExtent: "Kortets målestok/udstrækning",
    preserve: "Bevar",
    mapScale: "kortets målestok",
    mapExtent: "kortets udstrækning",
    forceScale: "Gennemtving målestok",
    getCurrentScale: "nuværende",
    mapMetadata: "Layout for metadata",
    author: "Forfatter",
    copyright: "Ophavsret",
    fullLayoutOptions: "Indstillinger for fuldt layout",
    scaleBarUnitsMetric: "Målestokslinje metriske enheder",
    scaleBarUnitsNonMetric: "Målestokslinje ikke-metriske enheder",
    unitsMiles: "Miles",
    unitsKilometers: "Kilometer",
    unitsMeters: "Meter",
    unitsFeet: "Fod",
    unitsYards: "Yards",
    unitsNauticalMiles: "Sømil",
    lncludeLegend: "Medtag forklaring",
    printQualityOptions: "Udskriftskvalitet",
    dpi: "DPI",
    mapOnlyOptions: "Størrelse for KUN_KORT",
    width: "Bredde (px)",
    height: "Højde (px)",
    print: "Udskriv",
    clearList: "Ryd udskrifter",
    creatingPrint: "Opretter udskrift",
    printError: "Fejl. Prøv igen"
  })
);