define({
  root: ({
    _widgetLabel: "Stream",
    streamControls: "Streaming Controls",
    streamFilter: "Filter",
    startStreaming: "Start Streaming",
    stopStreaming: "Stop Streaming",
    streamLayers: "Stream Layers",
    startStopStream: "Enable Stop streaming or Start streaming option",
    clearStream: "Enable Clear previous observations option",
    attributeFilter: "Enable Attribute filter",
    spatialFilter: "Enable Spatial filter",
    name: "Name",
    configFilter: "Configure Stream Attribute Filter",
    drawPrevious: "Enable Draw previous observations option",
    addNew: "Add Filter",
    setFilterName: "Set Filter Name",
    filterNameExists: "Filter name exists in the table!",
    invalidFilterName: "The name should be a word containing a-z, A-Z, 0-9 or _.",
    noFilterTip: "No filter configured",
    addFilterFailed: "Failed to add filter",
    filterName: "Filter Name",
    limitMapExtent: "Limit observations in the current map area",
    limitDrawExtent: "Limit observations in the user-defined area",
    newFilter: "New Filter",
    filterReadOnly: "The filter inherited from webmap is read only."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
