define(
   ({
    _widgetLabel: "Joonistamine",
    selectDrawMode: "Valige joonistusrežiim",
    clear: "Puhasta",
    point: "Punkt",
    line: "Joon",
    polyline: "Murdjoon",
    freehandPolyline: "Vabakäeline murdjoon",
    triangle: "Kolmnurk",
    extent: "Ümbriskast",
    circle: "Ring",
    ellipse: "Ellips",
    polygon: "Pind",
    freehandPolygon: "Vabakäeline pind",
    text: "Tekst",
    style: "Stiil",
    alpha: "Läbipaistvus",
    width: "Laius",
    size: "Suurus",
    color: "Värv",
    markerColor: "Markeri värv",
    outlineColor: "Äärejoone värv",
    lineColor: "Joone värv",
    fillColor: "Täitevärv",
    showMeasurements: "Näita mõõtühikuid",
    areaUnits: "Pindalaühikud",
    distanceUnits: "Vahemaa ühikud",
    kilometers: "Kilomeetrit",
    miles: "Miili",
    meters: "Meetrit",
    feet: "Jalga",
    yards: "Jardi",
    squareKilometers: "Ruutkilomeetrit",
    squareMiles: "Ruutmiili",
    acres: "Aakrit",
    hectares: "Hektarit",
    squareMeters: "Ruutmeetrit",
    squareFeet: "Ruutjalga",
    squareYards: "Ruutjardi",
    undo: "Tühista",
    redo: "Ennista",
    results: "Tulemused",
    points: "Punktid",
    lines: "Jooned",
    areas: "Pindalad"
  })
);