define(
   ({
    _widgetLabel: "Отчет об объекте",
    select: "Выбор",
    draw: "Рисование",
    chooseALayer: "Выберите слой",
    clickAFeature: "Щелкните объект на карте, чтобы выбрать его.",
    loadingFeatures: "Получение сведений о выбранном объекте...",
    errorTitle: "Ошибка",
    errorIdentify: "Ошибка идентификации объектов. Обратитесь к журналу консоли за подробными сведениями.",
    infoWindowTitle: "Подробности",
    layerLabel: "Имя слоя",
    reviewStatusLabel: "Статус просмотра",
    selectReviewStatusAdd: "Добавить объект",
    selectReviewStatusDelete: "Удалить пространственный объект",
    selectReviewStatusMove: "Переместить объект",
    selectReviewStatusReshape: "Изменить форму объекта",
    drawReviewStatusMissing: "Пропущенные объекты",
    drawReviewStatusPosition: "Ошибка позиционирования",
    drawReviewStatusShape: "Ошибка геометрии",
    drawReviewStatusAttribute: "Ошибка атрибута",
    notesLabel: "Примечания",
    severityLabel: "Степень серьезности",
    reportedByLabel: "Сообщено",
    reportedByDefault: "анонимный",
    reportButton: "Отчет",
    reportMessage: "Отчет получен",
    errorReportMessage: "Ошибка создания отчета об объекте",
    drawErrorInstructions: "Выберите точку, линию или полигон, чтобы отобразить на карте геометрию с ошибкой:",
    errorMapService: "Произошла ошибка при получении информации о картографическом сервисе",
    noFeatureSelected : "В указанном месте объекты не найдены.",
    selectFeatureMapPoint: "Щелкните, чтобы выбрать объект",
    drawFeatureMapPoint: "Щелкните, чтобы добавить точку",
    popupMessage:"Сообщение",
    popupError:"Ошибка",
    manyFeaturesSelected: "Найдено более одного объекта. Приблизьтесь и выберите объект для отчета."
  })
);
