define(
   ({
    "tabs_section_Label": "Záložky",
    "addTab": "Přidat kartu",
    "layerName": "Vrstva",
    "layerType": "Typ analýzy",
    "layerLabel": "Štítek",
    "actions": "Akce",
    "closest": "Nejbližší prvek",
    "proximity": "Obalové zóny, vzdálenost",
    "summary": "Souhrn",
    "select_lbl": "– Vybrat –",
    "general_setting_Label": "Obecná nastavení",
    "units_text_lbl": "Jednotky vzdálenosti",
    "miles": "Míle",
    "kilometers": "Kilometry",
    "feet": "Stopy",
    "meters": "Metry",
    "yards": "Yardy",
    "nauticalMiles": "Námořní míle",
    "maximum_distance_lbl": "Maximální vzdálenost k nejbližšímu prvku",
    "buffer_text_lbl": "Popisek obalové zóny",
    "buffer_lbl": "Vzdálenost obalové zóny",
    "buffer_max_lbl": "Maximální šířka obalové zóny",
    "buffer_min_lbl": "Minimální šířka obalové zóny",
    "routing_checkBox": "Povolit vyhledávání trasy",
    "weather_Label": "Možnosti počasí",
    "weather_checkBox": "Zahrnout informace o počasí",
    "selectLayers": "Vybrat vrstvy počasí",
    "currentlySelectedLayer": "Aktuálně vybrané vrstvy počasí",
    "missingTabLabel": "Nejméně jedna karta neobsahuje popisek.",
    "cancel": "Storno",
    "ok": "OK",
    "missingLayerInWebMap": "Nebyly nalezeny žádné operační vrstvy.",
    "selectFields": "Vybrat pole",
    "addField": "Přidat pole (Add Field)",
    "sum": "SUMA",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "POČET",
    "area": "PLOCHA",
    "length": "DÉLKA",
    "count_checkBox": "Zobrazit počet",
    "area_checkBox": "Zobrazit plochu",
    "length_checkBox": "Zobrazit délku",
    "max_records": "Byl dosažen maximální limit"
  })
);
