define(
   ({
    taskUrl: "URL của tác vụ",
    serviceURLPlaceholder: "Vui lòng nhập URL của tác vụ Địa xử lý",
    ok: "OK",
    cancel: "Hủy",
    layer: "Lớp",
    action: "Hành động",
    input: "Đầu vào",
    output: "Đầu ra",
    name: "Tên",
    type: "Loại",
    required: "Được yêu cầu",
    layerOrder: "Thứ tự lớp",
    options: "Tùy chọn",
    defaultValue: "Giá trị Mặc định",
    inputFeatureBy: "Nhập Đối tượng theo",
    renderer: "Trình kết xuất",
    displayType: "Loại hiển thị",
    label: "Nhãn",
    tooltip: "Chú giải công cụ",
    visible: "Hiển thị",
    helpUrl: "URL trợ giúp",
    useResultMapService: "Sử dụng các tùy chọn vẽ của kết quả dịch vụ bản đồ",
    drawOnMap: "Vẽ tương tác trên bản đồ",
    selectLayer: "Chọn một lớp từ bản đồ",
    url: "URL",
    symbol: "Ký hiệu",
    shareResults: "Thêm kết quả như lớp hoạt động",
    popup: "Cửa sổ pop-up",
    setTask: "Thiết lập",
    setTaskTitle: "Thiết lập Tác vụ GP",
    enablePopup: "Bật cửa sổ pop-up"
  })
);