define(
	 ({
		queries: "مهام الاستعلامات",
		addNew: "إضافة أخرى جديدة",
    queryLayer: "الاستعلام عن الطبقة",
		setSource: "تعيين",
		setDataSource: "تعيين مصدر البيانات",
		name: "الاسم",
		querySource: "مصدر البيانات",
		queryName: "اسم المهمة",
		queryDefinition: "تعريف عوامل التصفية",
		resultsSetting: "إعدادات النتائج",
		symbolSetting: "إعدادات الرمز",
		resultSettingTip: "تعريف ماهية وكيفية عرض النتائج المُخرَجة.",
		resultItemTitle: "عنوان عنصر النتائج",
		resultItemContent: "محتويات عنصر النتيجة",
		fieldsSetTip: "قم بالتأشير على الحقول المُراد عرضها. حدد الحقل لتحديث اسمه المستعار وترتيبه وتنسيقه.",
		addField: "إضافة حقل",
		visibility: "رؤية",
		alias: "اسم مستعار",
		specialType: "نوع خاص",
		actions: "الأفعال",
		none: "بلا",
		link: "رابط",
		image: "صورة",
		noField: "لا توجد حقول",
		operationalLayerTip: "إضافة النتيجة كطبقة تشغيلية",
		setLayerSymbolTip: "تعيين الرمز لنتائج الاستعلام: ",
		setSelectedSymbolTip: "حدد رمز المعالم المحددة.",
		notUseFilter: "لا يتم استخدام عوامل التصفية",
		setSourceTip: "يرجى تعيين مصدر الاستعلام.",
		setFilterTip: "يرجى تعيين عامل التصفية بشكل صحيح.",
		ok: "موافق",
		cancel: "إلغاء الأمر",
		noFilterTip: "بدون تعريف تعبير عوامل التصفية، ستقوم هذه المهمة بإدراج جميع المعالم في مصدر البيانات المًحدد.",
    relationships: "علاقات",
    addRelationshipLayer: "إضافة علاقة جديدة",
    relatedTo: "متصل بـ",
    selectOption: "يرجى تحديد...",
    resultItemSorting: "نتيجة فرز العنصر",
    field: "حقل",
    sortingOrder: "ترتيب",
    configureFieldsTip: "يرجى تكوين الحقول التي سيتم فرز الاستعلام حسبها.",
    setSortingFields: "تحديد فرز الحقول",
    ascending: "تصاعدي",
    descending: "تنازليًا",
    sortBy: "الفرز حسب",
    thenBy: "بعد ذلك",
    addTask: "إضافة مهمة",
    noTasksTip: 'لا توجد مهام، يرجى النقر على \"${addTask}\" للبدء!',
    infoText: "معلومات",
    filters: "عوامل تصفية",
    results: "النتائج",
    optionsText: "خيارات",
    summaryText: "الملخص",
    attributeFilter: "تصفية البيانات الجدولية",
    attributeFilterTip: "تعريف تعبيرات البيانات الجدولية للاستخدام في عنصر واجهة الاستخدام لتصفية طبقة الاستعلام.",
    noExpressionDefinedTip: "تم تعريف التعبير",
    needInputValuesTip: "نحتاج قيم إدخال في وقت التشغيل",
    setExpressions: "تحديد التعبيرات",
    spatialFilter: "الفلتر المكاني",
    spatialFilterTip: "اختر عوامل التصفية المكانية المستخدمة في عنصر واجهة الاستخدام لتحديد النتائج.",
    defaultOption: "الافتراضي",
    useCurrentExtentTip: "جزئيًا أو بالكامل ضمن مدى الخريطة الحالي",
    useDrawGraphicTip: "جزئيًا أو بالكامل ضمن الشكل المرسوم في الخريطة",
    useFeaturesTip: "يستند إلى المواقع المرتبطة بالمعالم في طبقة أخرى",
    noSpatialLimitTip: "ليست نتائج حدود مكانية",
    drawingTools: "أدوات الرسم",
    bufferSettings: "إعدادات النطاق",
    defaultDistance: "مسافة افتراضية",
    bufferDistance: "مسافة النطاق",
    defaultUnit: "وحدة افتراضية",
    miles: "ميل",
    kilometers: "كيلومترات",
    feet: "قدم",
    meters: "متر",
    yards: "ياردة",
    nauticalMiles: "الأميال البحرية",
    availableSpatialRelationships: "العلاقات المكانية متوفرة",
    setSpatialRelationships: "تحديد العلاقات المكانية",
    availability: "التوفر",
    relationship: "علاقة",
    label: "التسمية",
    intersect: "intersect",
    contain: "contain",
    areContainedIn: "يتم تضمينها في",
    cross: "تقاطع",
    envelopeIntersect: "تقاطع المُغلف",
    overlap: "تراكب",
    areOverlapped: "تم التراكب",
    touche: "لمس",
    within: "ضمن",
    areWithin: "ضمن",
    indexIntersect: "تقاطع الفهرس",
    itemTitle: "عنوان العنصر",
    displayFields: "حقول العرض",
    sortingFields: "فرز الحقول",
    setDisplayFields: "تحديد عرض الحقول",
    symbol: "رمز",
    setSymbol: "تحديد الرمز",
    serviceSymbolTip: "استخدام الرموز المُعرفة بواسطة الطبقة",
    exportTip: "عرض زر تصدير",
    keepResultsTip: "الحفاظ على نتائج الخريطة بعد غلق عنصر واجهة الاستخدام",
    queryRelatedRecords: "الاستعلام عن التسجيلات المرتبطة",
    createLayerForTaskTip: "تحديد كيفية إنشاء المهام للطبقات",
    oneLayerForTaskTip: "إنشاء بقة واحدة فقط للمهمة",
    multipleLayerForTaskTip: "إنشاء طبقة جديدة كل مرة يتم تنفيذ المهمة الحالية"
  })
);
