define(
	 ({
		queries: "مهام الاستعلامات",
		addNew: "إضافة أخرى جديدة",
		setSource: "تعيين",
		setDataSource: "تعيين مصدر البيانات",
		name: "الاسم",
		querySource: "مصدر البيانات",
		queryName: "اسم المهمة",
		queryDefinition: "تعريف عوامل التصفية",
		resultsSetting: "إعدادات النتائج",
		symbolSetting: "إعدادات الرمز",
		resultSettingTip: "تعريف ماهية وكيفية عرض النتائج المُخرَجة.",
		resultItemTitle: "عنوان عنصر النتائج",
		resultItemContent: "محتويات عنصر النتيجة",
		fieldsSetTip: "قم بالتأشير على الحقول المُراد عرضها. حدد الحقل لتحديث اسمه المستعار وترتيبه وتنسيقه.",
		addField: "إضافة حقل",
		visibility: "رؤية",
		alias: "اسم مستعار",
		specialType: "نوع خاص",
		actions: "الأفعال",
		none: "بلا",
		link: "رابط",
		image: "صورة",
		noField: "لا توجد حقول",
		operationalLayerTip: "إضافة النتيجة كطبقة تشغيلية",
		setLayerSymbolTip: "تعيين الرمز لنتائج الاستعلام: ",
		setSelectedSymbolTip: "حدد رمز المعالم المحددة.",
		notUseFilter: "لا يتم استخدام عوامل التصفية",
		setSourceTip: "يرجى تعيين مصدر الاستعلام.",
		setFilterTip: "يرجى تعيين عامل التصفية بشكل صحيح.",
		ok: "موافق",
		cancel: "إلغاء الأمر",
		noFilterTip: "بدون تعريف تعبير عوامل التصفية، ستقوم هذه المهمة بإدراج جميع المعالم في مصدر البيانات المًحدد."
  })
);