define(
   ({
    _widgetLabel: "Imprimare",
    title: "Titlu hartă",
    format: "Formatare",
    layout: "Configuraţie",
    settings: "Avansat",
    mapScaleExtent: "Scară/Extindere hartă",
    preserve: "Menţinere",
    mapScale: "scară hartă",
    mapExtent: "extindere hartă",
    forceScale: "Forţare scară",
    getCurrentScale: "actual",
    mapMetadata: "Metadate configuraţie",
    author: "Autor",
    copyright: "Drepturi de autor",
    fullLayoutOptions: "Opţiuni de configurare complete",
    scaleBarUnitsMetric: "Unităţi metrice pentru bara de scară",
    scaleBarUnitsNonMetric: "Unităţi nemetrice pentru bara de scară",
    unitsMiles: "Mile",
    unitsKilometers: "Kilometri",
    unitsMeters: "Metri",
    unitsFeet: "Ft",
    unitsYards: "Yarzi",
    unitsNauticalMiles: "Mile marine",
    lncludeLegend: "Includere legendă",
    printQualityOptions: "Calitate imprimare",
    dpi: "PPI",
    mapOnlyOptions: "Dimensiune MAP_ONLY",
    width: "Lăţime (px)",
    height: "Înălţime (px)",
    print: "Imprimare",
    clearList: "Golire imprimări",
    creatingPrint: "În curs de creare imprimare",
    printError: "Eroare, reîncercaţi"
  })
);