define(
	 ({
		charts: "Grafik Görevleri",
		addNew: "Yeni Ekle",
		addNewTip: "Yeni Bir Grafik Görevi Ekle",
		name: "Ad",
		set: "Ayarla",
		setDataSource: "Veri Kaynağını Belirt",
		generalSettingsTip: "Grafikler için veri kaynağı, başlık ve açıklama belirtin.",
		chartModeSettingTip: "Veriyi grafik olarak analiz edip görüntüleme yöntemini belirleyin.",
		detailsSettingTip: "Türlerini, rengini ve hangi değerlerin grafiğe döküleceğini belirterek grafik görünümünü ayarlayın.",
		symbolSettingTip: "Grafiğe dökülen veri için harita gösterimini ayarlayın.",
		addFilterTip: "Bu Veriye Filtre Ekle",
		dataSource: "Veri Kaynağı",
		noResults: "Detay bulunamadı.",
		chartTitle: "Grafik Başlığı",
		description: "Açıklama",
		chartingMode: "Grafik Gösterimi",
		featureOption: "Değerleri özelliğe göre görüntüle",
		categoryOption: "Değerleri kategoriye göre görüntüle",
		countOption: "Özellik sayımlarını kategoriye göre görüntüle",
		fieldOption: "Öznitelik değerlerini grafik olarak görüntüle",
		category: "Kategori",
		axisLabel: "Kategori Etiketi",
		categoryField: "Kategori Alanı",
		operation: "İşlem",
		originalOption: "Orijinal değerleri kullan",
		sumOption: "Toplam",
		averageOption: "Ortalama",
		minOption: "Minimum",
		maxOption: "Maksimum",
		valueFields: "Değer Alanları",
		moveUp: "Yukarı taşı",
		moveDown: "Aşağı taşı",
		sortOrder: "Grafik Sırasını Kategori Etiketleriyle Sırala",
		ascending: "Artan",
		descending: "Azalan",
		chartType: "Grafik Türü",
		column: "Sütun Grafiği",
		bar: "Çubuk Grafik",
		line: "Çizgi Grafik",
		pie: "Pasta Grafik",
		chartColor: "Grafik Rengi",
		showDataLabels: "Veri Etiketlerini Göster",
		setSymbol: "Seçim Simgesi",
		setHighLightColor: "Rengi Vurgula",
		settings: "Ayarlar",
		mapInterationOptions: "Harita Etkileşim Seçenekleri",
		preview: "Önizleme",
		ok: "Tamam",
		cancel: "İptal",
		close: "Kapat",
		setFilterTip: "Filtreyi düzgün ayarlayın. ",
		setChartTitleTip: "Grafik başlığını ayarlayın.",
		setChartTypeTip: "En az bir grafik türü seçin.",
		setDataFieldTip: "En az bir değer alanı seçin.",
		setOutputFieldTip: "Çıktı alanlarını belirtin.",
		count: "Sayım",
		label: "Etiket",
		horizontalAxis: "Yatay Eksen",
		verticalAxis: "Dikey Eksen",
		dataLabels: "Veri Etiketleri",
		color: "Renk",
		colorful: "Renkli",
		monochromatic: "Monokromatik"
  })
);