define(
   ({
    _widgetLabel: "Diagramme",
    executeChartTip: "Cliquez sur une des tâches suivantes pour exécuter le diagramme.",
    invalidConfig: "Configuration non valide.",
    noneChartTip: "Aucune tâche de diagramme n\'a été configurée pour ce widget.",
    chartParams: "Options",
    charts: "DIAGRAMMES",
    apply: "APPLIQUER",
    useSpatialFilter: "Utiliser un filtre spatial pour limiter les entités",
    useCurrentMapExtent: "Uniquement les entités qui intersectent la zone cartographique actuelle",
    drawGraphicOnMap: "Uniquement les entités qui intersectent une zone définie par l\'utilisateur",
    chartResults: "Diagramme",
    clearResults: "Effacer les résultats",
    noPermissionsMsg: "Vous n’êtes pas autorisé à accéder à ce service.",
    specifySpatialFilterMsg: "Spécifiez un filtre spatial pour cette tâche.",
    queryError: "La requête a échoué.",
    noResults: "Aucune entité trouvée.",
    category: "Catégorie",
    count: "Total",
    label: "Etiquette",
    horizontalAxis: "Axe horizontal",
    verticalAxis: "Axe vertical",
    dataLabels: "Etiquettes de données",
    color: "Couleur",
    colorful: "Coloré",
    monochromatic: "Monochromatique",
    tasks: "Tâches",
    results: "Résultats",
    applySpatialFilterToLimitResults: "Appliquer un filtre spatial pour limiter les résultats",
    useCurrentExtentTip: "Partiellement ou entièrement dans l\'étendue de la carte actuelle",
    useDrawGraphicTip: "Partiellement ou entièrement dans la forme dessinée sur la carte",
    useFeaturesTip: "En fonction de leurs emplacements par rapport aux entités d\'une autre couche",
    noSpatialLimitTip: "Ne pas limiter spatialement les résultats",
    applySearchDistance: "Appliquer une distance de recherche",
    spatialRelationship: "Relation spatiale",
    relatedLayer: "Couche associée",
    clear: "Effacer",
    bufferDistance: "Distance de la zone tampon",
    miles: "Miles",
    kilometers: "Kilomètres",
    feet: "Pieds",
    meters: "Mètres",
    yards: "Yards",
    nauticalMiles: "Milles nautiques",
    back: "Retour",
    execute: "Exécuter"
  })
);