define(
   ({
    _widgetLabel: "Diagramă",
    executeChartTip: "Faceţi clic pe unul din următoarele elemente sarcină pentru a genera diagrama.",
    invalidConfig: "Configuraţie nevalidă.",
    noneChartTip: "Pentru acest widget nu a fost configurată nicio activitate pentru diagrame.",
    chartParams: "Opţiuni",
    charts: "DIAGRAME",
    apply: "APLICARE",
    useSpatialFilter: "Utilizare filtru spaţial pentru limitarea obiectelor spaţiale",
    useCurrentMapExtent: "Numai obiectele spaţiale care se intersectează cu suprafaţa curentă a hărţii",
    drawGraphicOnMap: "Numai obiectele spaţiale care se intersectează cu o suprafaţă definită de utilizator",
    chartResults: "Rezultate diagramă",
    clearResults: "Golire rezultate",
    noPermissionsMsg: "Nu deţineţi permisiuni pentru accesarea acestui serviciu.",
    specifySpatialFilterMsg: "Specificaţi filtrul spaţial pentru această operaţie.",
    queryError: "Interogare eşuată.",
    noResults: "Nu a fost găsit niciun obiect spaţial.",
    category: "Categorie",
    count: "Număr",
    label: "Etichetă",
    horizontalAxis: "Axă orizontală",
    verticalAxis: "Axă verticală",
    dataLabels: "Etichete date",
    color: "Culoare",
    colorful: "Color",
    monochromatic: "Monocrom",
    tasks: "Sarcini",
    results: "Rezultate",
    applySpatialFilterToLimitResults: "Aplicaţi un filtru spaţial pentru limitarea rezultatelor",
    useCurrentExtentTip: "Parţial sau complet în cadrul extinderii curente de hartă",
    useDrawGraphicTip: "Parţial sau complet în cadrul formei trasate pe hartă",
    useFeaturesTip: "În baza locaţiilor, în raport cu obiectele spaţiale din alt strat tematic",
    noSpatialLimitTip: "Nu limitaţi spaţial rezultatele",
    applySearchDistance: "Aplicaţi o distanţă de căutare",
    spatialRelationship: "Relaţie spaţială",
    relatedLayer: "Strat tematic corelat",
    clear: "Golire",
    bufferDistance: "Distanţă buffer",
    miles: "Mile",
    kilometers: "Kilometri",
    feet: "Ft",
    meters: "Metri",
    yards: "Iarzi",
    nauticalMiles: "Mile marine",
    back: "Înapoi",
    execute: "Executare"
  })
);