define(
   ({
    _widgetLabel: "Геообработка",
    execute: "Выполнить",
    help: "Справка",
    input: "Входные данные",
    output: "Выходные данные",
    executing: "Выполнение",
    requiredInfo: "требуется.",
    drawnOnMap: "Результат отображается на карте.",
    clear: "Очистить",
    error: "Ошибка",
    noToolConfig: "Нет доступных предварительно настроенных задач геообработки.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Загрузить файл",
    selectFileToUpload: 'Выбрать файл...',
    upload: 'Загрузить',
    rasterFormat: 'Формат растровых данных',
    noFileSelected: 'Нет выбранных файлов!',
    uploadSuccess:'Выгрузка файла выполнена успешно!',
    url: "URL",
    showLayerContent: "Показать ресурсы слоя",
    invalidUrl: "Неверный url-адрес сервиса объектов",
    Feet: "Футы",
    Yards: "Ярды",
    Miles: "Мили",
    NauticalMiles: "Морские мили",
    Meter: "Метры",
    Kilometers: "Километры",
    urlPlaceholder: "URL-адрес группы объектов"
  })
);
