define(
   ({
    _widgetLabel: "Päring",
    executeQueryTip: "Päringu käivitamiseks klõpsake ühte järgmistest sisuobjekti toimingutest.",
    invalidConfig: "Vigane seadistus. Õige seadistuse hankimiseks kasutage päringu seadete lehte.",
    queryParams: "Valikud",
    parameters: "VALIKUD",
    queries: "PÄRINGUD",
    apply: "RAKENDA",
    queryResults: "Tulemused",
    clear: "Puhasta",
    noResults: "Objekte ei leitud.",
    queryError: "Päring ebaõnnestus!",
    numberFound: "Leitud objektide arv",
    mapExtentTip: "Piira tulemusi kaardi praeguse kuvaulatusega.",
    noValue: "Väärtus puudub",
    and: "ja",
    stringOperatorIs: "on", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ei ole",
    stringOperatorStartsWith: "algab",
    stringOperatorEndsWith: "lõpeb",
    stringOperatorContains: "sisaldab",
    stringOperatorDoesNotContain: "ei sisalda",
    stringOperatorIsBlank: "on tühi",
    stringOperatorIsNotBlank: "ei ole tühi",
    dateOperatorIsOn: "on", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ei ole",
    dateOperatorIsBefore: "on enne",
    dateOperatorIsAfter: "on pärast",
    dateOperatorDays: "päeva",
    dateOperatorWeeks: "nädalat", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "kuud",
    dateOperatorInTheLast: "viimases",
    dateOperatorNotInTheLast: "mitte viimases",
    dateOperatorIsBetween: "on vahemikus",
    dateOperatorIsNotBetween: "ei ole vahemikus",
    dateOperatorIsBlank: "on tühi",
    dateOperatorIsNotBlank: "ei ole tühi",
    numberOperatorIs: "on", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ei ole",
    numberOperatorIsAtLeast: "on vähemalt",
    numberOperatorIsLessThan: "on väiksem kui",
    numberOperatorIsAtMost: "on kõige",
    numberOperatorIsGreaterThan: "on suurem kui",
    numberOperatorIsBetween: "on vahemikus",
    numberOperatorIsNotBetween: "ei ole vahemikus",
    numberOperatorIsBlank: "on tühi",
    numberOperatorIsNotBlank: "ei ole tühi",
    operationalLayerTip: "Lisa tulemus töökihina",
    queryResult: "Päringu tulemus",
    specifyParamsTip: "Määra selle ülesande jaoks parameetrid",
    useSpatialFilter: "Kasuta objektide piiramiseks ruumifiltrit",
    useCurrentMapExtent: "Vaid praeguse kaardiulatusega lõikuvad objektid",
    drawGraphicOnMap: "Vaid kasutaja poolt määratletud alaga lõikuvad objektid",
    specifySpatialFilterMsg: "Määrake selle ülesande jaoks ruumifilter.",
    clearResults: "Kustuta tulemused",
    operationalTip: 'Kui see valik on märgitud, kuvatakse tulemused kaardil seni, kuni klikite nuppu \"${clearResults}\".',
    noneQueryTip: "Selle vidina jaoks pole konfigureeritud päringu toimingut.",
    noPermissionsMsg: "Teil puudub juurdepääs sellele teenusele.",
    attributesFromRelationship: "Atribuudid seotud tabelist",
    tasks: "Toimingud",
    applySpatialFilterToLimitResults: "Rakenda tulemuste piiramiseks ruumifilter",
    useCurrentExtentTip: "Osaliselt või täielikult praeguses kaardi kuvaulatuses",
    useDrawGraphicTip: "Osaliselt või täielikult kaardile joonistatud kujundis",
    useFeaturesTip: "Vastavalt nende asukohale teise kihi objektide suhtes",
    noSpatialLimitTip: "Ära piira tulemusi ruumiliselt",
    applySearchDistance: "Rakenda otsingu vahemaad",
    spatialRelationship: "Ruumiline seos",
    relatedLayer: "Seotud kiht",
    bufferDistance: "Puhvri ulatus",
    miles: "Miilid",
    kilometers: "Kilomeetrid",
    feet: "Jalad",
    meters: "Meetrid",
    yards: "Jardid",
    nauticalMiles: "Meremiilid",
    back: "Tagasi",
    execute: "Käivita"
  })
);