define(
   ({
    _widgetLabel: "Päring",
    executeQueryTip: "Päringu teostamiseks klikkige ühte järgmistest ülesande objektidest.",
    invalidConfig: "Vigane seadistus. Õige seadistuse hankimiseks kasutage päringu seadete lehte.",
    queryParams: "Valikud",
    parameters: "VALIKUD",
    queries: "PÄRINGUD",
    apply: "RAKENDA",
    queryResults: "Tulemused",
    clear: "Puhasta",
    noResults: "Objekte ei leitud.",
    queryError: "Päring ebaõnnestus!",
    numberFound: "Leitud objektide arv",
    mapExtentTip: "Näita tulemusi ainult praeguse kaardi ulatuse kohta.",
    noValue: "Väärtus puudub",
    and: "ja",
    stringOperatorIs: "on", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "ei ole",
    stringOperatorStartsWith: "algab",
    stringOperatorEndsWith: "lõpeb",
    stringOperatorContains: "sisaldab",
    stringOperatorDoesNotContain: "ei sisalda",
    stringOperatorIsBlank: "on tühi",
    stringOperatorIsNotBlank: "ei ole tühi",
    dateOperatorIsOn: "on", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "ei ole",
    dateOperatorIsBefore: "on enne",
    dateOperatorIsAfter: "on pärast",
    dateOperatorDays: "päeva",
    dateOperatorWeeks: "nädalat", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "kuud",
    dateOperatorInTheLast: "viimases",
    dateOperatorNotInTheLast: "mitte viimases",
    dateOperatorIsBetween: "on vahemikus",
    dateOperatorIsNotBetween: "ei ole vahemikus",
    dateOperatorIsBlank: "on tühi",
    dateOperatorIsNotBlank: "ei ole tühi",
    numberOperatorIs: "on", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "ei ole",
    numberOperatorIsAtLeast: "on vähemalt",
    numberOperatorIsLessThan: "on väiksem kui",
    numberOperatorIsAtMost: "on kõige",
    numberOperatorIsGreaterThan: "on suurem kui",
    numberOperatorIsBetween: "on vahemikus",
    numberOperatorIsNotBetween: "ei ole vahemikus",
    numberOperatorIsBlank: "on tühi",
    numberOperatorIsNotBlank: "ei ole tühi",
    operationalLayerTip: "Lisa tulemus töökihina",
    queryResult: "Päringu tulemus",
    specifyParamsTip: "Määra selle ülesande jaoks parameetrid",
    useSpatialFilter: "Kasuta objektide piiramiseks ruumifiltrit",
    useCurrentMapExtent: "Vaid praegust kaardi ulatust puudutavad objektid",
    drawGraphicOnMap: "Vaid kasutaja määratletud ala puudutavad objektid",
    specifySpatialFilterMsg: "Määrake selle ülesande jaoks ruumifilter.",
    clearResults: "Kustuta tulemused",
    operationalTip: 'Kui see valik on märgitud, kuvatakse tulemused kaardil seni, kuni klikite nuppu "${clearResults}".',
    noneQueryTip: "Eelseadistatud päringuülesanded pole saadaval.",
    noPermissionsMsg: "Teil puudub juurdepääs sellele teenusele."
  })
);