define(
	 ({
		charts: "Diagramoppgaver",
		addNew: "Legg til ny",
		addNewTip: "Legg til en ny diagramoppgave",
		name: "Navn",
		set: "Angi",
		setDataSource: "Angi datakilde",
		generalSettingsTip: "Angi datakilde, tittel og beskrivelse for diagrammer.",
		chartModeSettingTip: "Velg hvordan data skal analyseres og vises som diagrammer.",
		detailsSettingTip: "Angi diagramutformingen ved å velge type og farge og hvilke verdier som skal vises i diagrammet.",
		symbolSettingTip: "Angi kartvisning for diagramdata.",
		addFilterTip: "Legg til filter for disse dataene",
		dataSource: "Datakilde",
		noResults: "Fant ingen geoobjekter.",
		chartTitle: "Diagramtittel",
		description: "Beskrivelse",
		chartingMode: "Diagramvisning",
		featureOption: "Vis verdier geoobjekt for geoobjekt",
		categoryOption: "Vis verdier etter kategori",
		countOption: "Vis geoobjektantall etter kategori",
		fieldOption: "Vis attributtverdier som diagrammer",
		category: "Kategori",
		axisLabel: "Kategorietikett",
		categoryField: "Kategorifelt",
		operation: "Oppgave",
		originalOption: "Bruk opprinnelige verdier",
		sumOption: "Sum",
		averageOption: "Gjennomsnittlig",
		minOption: "Minimum",
		maxOption: "Maksimum",
		valueFields: "Verdifelter",
		moveUp: "Flytt opp",
		moveDown: "Flytt ned",
		sortOrder: "Sorter diagramrekkefølgen via kategorietiketter",
		ascending: "Stigende",
		descending: "Synkende",
		chartType: "Diagramtype",
		column: "Kolonnediagram",
		bar: "Stolpediagram",
		line: "Linjediagram",
		pie: "Sektordiagram",
		chartColor: "Diagramfarge",
		showDataLabels: "Vis dataetiketter",
		setSymbol: "Utvalgsymbol",
		setHighLightColor: "Uthevingsfarge",
		settings: "Innstillinger",
		mapInterationOptions: "Alternativer for kartinteraksjon",
		preview: "Forhåndsvisning",
		ok: "OK",
		cancel: "Avbryt",
		close: "Lukk",
		setFilterTip: "Angi filteret på riktig måte. ",
		setChartTitleTip: "Du må angi en diagramtittel.",
		setChartTypeTip: "Du må velge minst én diagramtype.",
		setDataFieldTip: "Du må velge minst ett verdifelt.",
		setOutputFieldTip: "Du må angi utdatafelter.",
		count: "Antall",
		label: "Etikett",
		horizontalAxis: "Horisontal akse",
		verticalAxis: "Vertikal akse",
		dataLabels: "Datapåskrifter",
		color: "Farge",
		colorful: "Med flere farger",
		monochromatic: "Med bare én farge"
  })
);