define(
   ({
    _widgetLabel: "Печать",
    title: "Название карты",
    format: "Формат",
    layout: "Компоновка",
    settings: "Расширенный",
    mapScaleExtent: "Масштаб/экстент карты",
    preserve: "Сохранить",
    mapScale: "масштаб карты",
    mapExtent: "экстент карты",
    forceScale: "Шкала силы",
    getCurrentScale: "текущий",
    mapMetadata: "Метаданные компоновки",
    author: "Автор",
    copyright: "Авторские права",
    fullLayoutOptions: "Указать параметры компоновки",
    scaleBarUnitsMetric: "Метрические единицы шкалы масштабов",
    scaleBarUnitsNonMetric: "Неметрические единицы шкалы масштабов",
    unitsMiles: "Мили",
    unitsKilometers: "Километры",
    unitsMeters: "Метры",
    unitsFeet: "Футы",
    unitsYards: "Ярды",
    unitsNauticalMiles: "Морские мили",
    lncludeLegend: "Включать легенду",
    printQualityOptions: "Качество печати",
    dpi: "DPI",
    mapOnlyOptions: "размер MAP_ONLY",
    width: "Ширина (в пикселях)",
    height: "Высота (в пикселях)",
    print: "Печать",
    clearList: "Очистить список печати",
    creatingPrint: "Создание документа печати",
    printError: "Ошибка, попробуйте еще раз"
  })
);