define(
   ({
    taskUrl: "URL de la tâche",
    serviceURLPlaceholder: "Saisissez l’URL de la tâche de géotraitement",
    ok: "OK",
    cancel: "Annuler",
    layer: "Couche",
    action: "Opération",
    input: "Entrée",
    output: "Sortie",
    name: "Nom",
    type: "Type",
    required: "Obligatoire",
    layerOrder: "Ordre des couches",
    options: "Options",
    defaultValue: "Valeur par défaut",
    inputFeatureBy: "Saisir l’entité par",
    renderer: "Représentation",
    displayType: "Type d’affichage",
    label: "Etiquette",
    tooltip: "Info-bulle",
    visible: "Visible",
    helpUrl: "URL de l’aide",
    useResultMapService: "Utiliser les options de dessin du service de carte obtenu",
    drawOnMap: "Dessin interactif sur la carte",
    selectLayer: "Sélection d’une couche sur la carte",
    url: "URL",
    symbol: "Symbole",
    shareResults: "Ajouter le résultat en tant que couche opérationnelle",
    popup: "Fenêtre contextuelle",
    setTask: "Définir",
    setTaskTitle: "Définir une tâche de géotraitement",
    enablePopup: "Activer la fenêtre contextuelle",
    unSupportGeometryType: "Impossible de définir le moteur de rendu, car le type de géométrie est inconnu.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Télécharger le fichier",
    selectFileToUpload: "Sélectionner un fichier...",
    upload: "Charger",
    rasterFormat: "Format de données raster",
    noFileSelected: "Aucun fichier sélectionné !",
    uploadSuccess:"Fichier chargé correctement !",
    showLayerContent: "Afficher le contenu de la couche",
    Feet: "Pieds",
    Yards: "Yards",
    Miles: "Miles",
    NauticalMiles: "Milles nautiques",
    Meter: "Mètres",
    Kilometers: "Kilomètres",
    urlPlaceholder: "URL du jeu d\'entités",
    allowToExport: "Autoriser l\'exportation des résultats"
  })
);
