define(
   ({
    _widgetLabel: "查询",
    executeQueryTip: "单击以下任一任务项目执行查询。",
    invalidConfig: "配置无效。请使用\“查询\”设置页面获取正确配置。",
    queryParams: "选项",
    parameters: "选项",
    queries: "查询",
    apply: "应用",
    queryResults: "结果",
    clear: "清除",
    noResults: "未找到任何要素。",
    queryError: "查询失败!",
    numberFound: "找到的要素数",
    mapExtentTip: "将结果限制为当前地图区域。",
    noValue: "没有值",
    and: "和",
    stringOperatorIs: "等于", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "不等于",
    stringOperatorStartsWith: "开头是",
    stringOperatorEndsWith: "结尾是",
    stringOperatorContains: "包含",
    stringOperatorDoesNotContain: "不包含",
    stringOperatorIsBlank: "为空",
    stringOperatorIsNotBlank: "不为空",
    dateOperatorIsOn: "在", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "不在",
    dateOperatorIsBefore: "早于",
    dateOperatorIsAfter: "晚于",
    dateOperatorDays: "天",
    dateOperatorWeeks: "周", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "月",
    dateOperatorInTheLast: "最后",
    dateOperatorNotInTheLast: "不是最后",
    dateOperatorIsBetween: "介于",
    dateOperatorIsNotBetween: "不介于",
    dateOperatorIsBlank: "为空",
    dateOperatorIsNotBlank: "不为空",
    numberOperatorIs: "等于", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "不等于",
    numberOperatorIsAtLeast: "最小为",
    numberOperatorIsLessThan: "小于",
    numberOperatorIsAtMost: "最大为",
    numberOperatorIsGreaterThan: "大于",
    numberOperatorIsBetween: "介于",
    numberOperatorIsNotBetween: "不介于",
    numberOperatorIsBlank: "为空",
    numberOperatorIsNotBlank: "不为空",
    operationalLayerTip: "将结果添加为业务图层",
    queryResult: "查询结果",
    specifyParamsTip: "为此任务指定参数",
    useSpatialFilter: "使用空间过滤器限制要素",
    useCurrentMapExtent: "仅与当前地图区域相交的要素",
    drawGraphicOnMap: "仅与用户自定义区域相交的要素",
    specifySpatialFilterMsg: "请为此任务指定空间过滤器。",
    clearResults: "清除结果",
    operationalTip: '选中此选项后，结果将始终保留在地图上，直至单击 \"${clearResults}\" 按钮。',
    noneQueryTip: "此微件未配置查询任务。",
    noPermissionsMsg: "您没有访问此服务的权限。",
    attributesFromRelationship: "相关表中的属性",
    tasks: "任务",
    applySpatialFilterToLimitResults: "应用空间过滤器以限定结果",
    useCurrentExtentTip: "部分或完全位于当前地图范围内",
    useDrawGraphicTip: "部分或完全位于在地图上绘制的形状内",
    useFeaturesTip: "根据其相对于另一图层中要素的位置",
    noSpatialLimitTip: "不会在空间上限制结果",
    applySearchDistance: "应用搜索距离",
    spatialRelationship: "空间关系",
    relatedLayer: "相关图层",
    bufferDistance: "缓冲距离",
    miles: "英里",
    kilometers: "公里",
    feet: "英尺",
    meters: "米",
    yards: "码",
    nauticalMiles: "海里",
    back: "后退",
    execute: "执行"
  })
);