define(
   ({
    taskUrl: "URL operaţie",
    serviceURLPlaceholder: "Introduceţi URL-ul operaţiei de geoprocesare",
    ok: "OK",
    cancel: "Anulare",
    layer: "Strat tematic",
    action: "Acţiune",
    input: "Introducere",
    output: "Ieşire",
    name: "Nume",
    type: "Tip",
    required: "Obligatoriu",
    layerOrder: "Ordine straturi tematice",
    options: "Opţiuni",
    defaultValue: "Valoare implicită",
    inputFeatureBy: "Introducere obiect spaţial după",
    renderer: "Autor reproducere",
    displayType: "Tip afişare",
    label: "Etichetă",
    tooltip: "Tooltip",
    visible: "Vizibil",
    helpUrl: "URL ajutor",
    useResultMapService: "Utilizaţi opţiunile de trasare ale serviciului de hărţi rezultat",
    drawOnMap: "Se trasează interactiv pe hartă",
    selectLayer: "Se selectează un strat tematic din hartă",
    url: "URL",
    symbol: "Simbol",
    shareResults: "Adăugare rezultat drept strat tematic operaţional",
    popup: "Pop-up",
    setTask: "Setare",
    setTaskTitle: "Setare operaţie GP",
    enablePopup: "Activare pop-up",
    unSupportGeometryType: "Nu se poate seta autorul reproducerii deoarece tipul de geometrie este necunoscut.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Încărcare fişier",
    selectFileToUpload: "Selectare fişier...",
    upload: "Încărcare",
    rasterFormat: "Format date raster",
    noFileSelected: "Niciun fişier selectat!",
    uploadSuccess:"Fişier încărcat cu succes!",
    showLayerContent: "Afişare conţinut strat tematic",
    Feet: "Ft",
    Yards: "Iarzi",
    Miles: "Mile",
    NauticalMiles: "Mile marine",
    Meter: "Metri",
    Kilometers: "Kilometri",
    urlPlaceholder: "URL set de obiecte spaţiale",
    allowToExport: "Permitere exportare rezultate"
  })
);
