define(
	 ({
		queries: "Kyselytehtävät",
		addNew: "Lisää uusi",
		setSource: "Aseta",
		setDataSource: "Määritä aineistolähde",
		name: "Nimi",
		querySource: "Tietolähde",
		queryName: "Tehtävän nimi",
		queryDefinition: "Suodatinmääritelmä",
		resultsSetting: "Tulosten asetus",
		symbolSetting: "Symboliasetus",
		resultSettingTip: "Määritä, mitä tuloksesta näytetään ja miten.",
		resultItemTitle: "Tuloksen kohteen nimi",
		resultItemContent: "Tuloskohteen sisältö",
		fieldsSetTip: "Valitse näytettävät kentät. Valitse tietty kenttä, kun haluat päivittää sen aliaksen, järjestyksen tai muodon.",
		addField: "Lisää kenttä",
		visibility: "Näkyvyys",
		alias: "Alias",
		specialType: "Erikoistyyppi",
		actions: "Toimet",
		none: "Ei mitään",
		link: "Linkki",
		image: "Kuva",
		noField: "Ei kenttää",
		operationalLayerTip: "Lisää tulos toiminnalliseksi karttatasoksi",
		setLayerSymbolTip: "Määritä kyselytulosten symboli: ",
		setSelectedSymbolTip: "Määritä valitun kohteen symboli.",
		notUseFilter: "Älä käytä suodatinta",
		setSourceTip: "Määritä kyselyn lähde.",
		setFilterTip: "Määritä suodatin oikein.",
		ok: "OK",
		cancel: "Peruuta",
		noFilterTip: "Jos suodatinlauseketta ei määritetä, kyselytehtävä luetteloi kaikki määritetyn tietolähteen kohteet."
  })
);