define(
	 ({
		queries: "Kyselytehtävät",
		addNew: "Lisää uusi",
    queryLayer: "Kyselytaso",
		setSource: "Aseta",
		setDataSource: "Määritä aineistolähde",
		name: "Nimi",
		querySource: "Tietolähde",
		queryName: "Tehtävän nimi",
		queryDefinition: "Suodatinmääritelmä",
		resultsSetting: "Tulosten asetus",
		symbolSetting: "Symboliasetus",
		resultSettingTip: "Määritä, mitä tuloksesta näytetään ja miten.",
		resultItemTitle: "Tuloksen kohteen nimi",
		resultItemContent: "Tuloskohteen sisältö",
		fieldsSetTip: "Valitse näytettävät kentät. Valitse tietty kenttä, kun haluat päivittää sen aliaksen, järjestyksen tai muodon.",
		addField: "Lisää kenttä",
		visibility: "Näkyvyys",
		alias: "Alias",
		specialType: "Erikoistyyppi",
		actions: "Toimet",
		none: "Ei mitään",
		link: "Linkki",
		image: "Kuva",
		noField: "Ei kenttää",
		operationalLayerTip: "Lisää tulos toiminnalliseksi karttatasoksi",
		setLayerSymbolTip: "Määritä kyselytulosten symboli: ",
		setSelectedSymbolTip: "Määritä valitun kohteen symboli.",
		notUseFilter: "Älä käytä suodatinta",
		setSourceTip: "Määritä kyselyn lähde.",
		setFilterTip: "Määritä suodatin oikein.",
		ok: "OK",
		cancel: "Peruuta",
		noFilterTip: "Jos suodatinlauseketta ei määritetä, kyselytehtävä luetteloi kaikki määritetyn tietolähteen kohteet.",
    relationships: "Suhteet",
    addRelationshipLayer: "Lisää uusi suhde",
    relatedTo: "Liittyy kohteeseen",
    selectOption: "Valitse...",
    resultItemSorting: "Tuloskohteen lajittelu",
    field: "Kenttä",
    sortingOrder: "Järjestä",
    configureFieldsTip: "Määritä kentät,  joiden perusteella kyselyn tulokset lajitellaan.",
    setSortingFields: "Määritä lajittelukentät",
    ascending: "Nouseva",
    descending: "Laskeva",
    sortBy: "Lajitteluperuste",
    thenBy: "Seuraava lajitteluperuste",
    addTask: "Lisää tehtävä",
    noTasksTip: 'Tehtäviä ei ole. Aloita valitsemalla \"${addTask}\".',
    infoText: "Tiedot",
    filters: "Suodattimet",
    results: "Tulokset",
    optionsText: "Valinnat",
    summaryText: "Yhteenveto",
    attributeFilter: "Määritteen suodatin",
    attributeFilterTip: "Määritä määritelausekkeet, joita käytetään pienoisohjelmassa kyselytason suodattamiseen.",
    noExpressionDefinedTip: "Lauseketta ei ole määritetty.",
    needInputValuesTip: "Arvot on syötettävä suorituksen aikana",
    setExpressions: "Määritä lausekkeet",
    spatialFilter: "Sijaintisuodatin",
    spatialFilterTip: "Valitse sijaintisuodattimet, joita käytetään pienoisohjelmassa tulosten rajoittamiseen.",
    defaultOption: "Oletus",
    useCurrentExtentTip: "Osittain tai kokonaan nykyisessä karttalaajuudessa",
    useDrawGraphicTip: "Osittain tai kokonaan karttaan piirretyn muodon sisällä",
    useFeaturesTip: "Niiden sijaintien perusteella suhteessa toisen karttatason kohteisiin",
    noSpatialLimitTip: "Älä rajoita tuloksia sijaintitietojen mukaan",
    drawingTools: "Piirtotyökalut",
    bufferSettings: "Puskurin asetukset",
    defaultDistance: "Oletusetäisyys",
    bufferDistance: "Puskurin etäisyys",
    defaultUnit: "Oletusyksikkö",
    miles: "Mailia",
    kilometers: "Kilometriä",
    feet: "Jalkaa",
    meters: "Metriä",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    availableSpatialRelationships: "Käytettävissä olevat sijaintisuhteet",
    setSpatialRelationships: "Määritä sijaintisuhteet",
    availability: "Saatavuus",
    relationship: "Suhde",
    label: "Tunnusteksti",
    intersect: "leikkaa",
    contain: "sisältää",
    areContainedIn: "sisältyvät",
    cross: "risti",
    envelopeIntersect: "rajojen leikkaus",
    overlap: "limittyy",
    areOverlapped: "on päällekkäin",
    touche: "koskettaa",
    within: "sisässä",
    areWithin: "on sisässä",
    indexIntersect: "indeksin leikkaus",
    itemTitle: "kohteen otsikko",
    displayFields: "Näytä kentät",
    sortingFields: "Lajitellaan kenttiä",
    setDisplayFields: "Määritä näyttökentät",
    symbol: "Symboli",
    setSymbol: "Määritä symboli",
    serviceSymbolTip: "Käytä karttatason määrittämiä symboleja",
    exportTip: "Näytä Vie-painike",
    keepResultsTip: "Näytä tulokset kartassa pienoisohjelman sulkemisen jälkeen",
    queryRelatedRecords: "Kyselyyn liittyvät tietueet",
    createLayerForTaskTip: "Määritä, miten tehtävä luo karttatasot",
    oneLayerForTaskTip: "Luo vain yksi karttataso tälle tehtävälle",
    multipleLayerForTaskTip: "Luo uusi karttataso aina, kun tämä tehtävä suoritetaan"
  })
);
