define(
	 ({
		queries: "การตั้งคำถาม",
		addNew: "เพิ่มใหม่",
    queryLayer: "สอบถามชั้นข้อมูล",
		setSource: "ตั้งค่า",
		setDataSource: "ตั้งค่าแหล่งข้อมูล",
		name: "ชื่อ",
		querySource: "ที่มาของคำถาม",
		queryName: "ชื่อคำถาม",
		queryDefinition: "นิยามคำถาม",
		resultsSetting: "การตั้งค่าผลลัพธ์",
		symbolSetting: "การตั้งค่าสัญลักษณ์",
		resultSettingTip: "ระบุความหมายและวิธีการแสดงผลลัพธ์",
		resultItemTitle: "ชื่อของผลลัพธ์",
		resultItemContent: "เนื้อหาผลลัพธ์ข้อมูล",
		fieldsSetTip: "เลือกฟิลด์ที่คุณต้องการแสดง เลือกฟิลด์ที่จะเปลี่ยนชื่อแฝง ลำดับ หรือรูปแบบ",
		addField: "เพิ่มฟิลด์",
		visibility: "มองเห็นได้",
		alias: "นามแฝง",
		specialType: "ประเภทประเภท",
		actions: "กระทำ",
		none: "ไม่มี",
		link: "ลิงก์",
		image: "รูปภาพ",
		noField: "ไม่มีฟิลด์",
		operationalLayerTip: "เพิ่มผลลัพธ์เป็นชั้นข้อมูลเกี่ยวกับการดำเนินงาน",
		setLayerSymbolTip: "ตั้งค่าสัญลักษณ์สำหรับผลลัพธ์การตั้งคำถาม ",
		setSelectedSymbolTip: "ตั้งค่าสัญลักษณ์ของฟีเจอร์ที่เลือก",
		notUseFilter: "ห้ามใช้ตัวกรอง",
		setSourceTip: "โปรดตั้งค่าที่มาของคำถาม",
		setFilterTip: "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
		ok: "ตกลง",
		cancel: "ยกเลิก",
		noFilterTip: "หากไม่กำหนดตัวกรอง  แบบสอบถามนี้จะแสดงรายการคุณลักษณะทั้งหมดในแหล่งข้อมูลที่ระบุ",
    relationships: "ความสัมพันธ์",
    addRelationshipLayer: "เพิ่มความสัมพันธ์ใหม่",
    relatedTo: "สัมพันธ์กับ",
    selectOption: "กรุณาเลือก..",
    resultItemSorting: "เรียงลำดับผลลัพธ์",
    field: "ฟิลด์",
    sortingOrder: "ลำดับ",
    configureFieldsTip: "กรุณาตั้งค่าฟิลด์ซึ่งผลลัพธ์การค้นหาจะเรียงลำดับตาม",
    setSortingFields: "ตั้งค่าการเรียงลำดับ",
    ascending: "เรียงจากน้อยไปมาก",
    descending: "เรียงจากมากไปน้อย",
    sortBy: "จัดลำดับตาม",
    thenBy: "แล้วตามด้วย",
    addTask: "เพิ่มงาน",
    noTasksTip: 'ไม่มีงาน กรุณาคลิกที่ \"${addTask}\" เพื่อเริ่มต้น !',
    infoText: "ข้อมูล",
    filters: "ตัวกรองข้อมูล",
    results: "ผลลัพธ์",
    optionsText: "ตัวเลือก",
    summaryText: "สรุป",
    attributeFilter: "คุณสมบัติของตัวกรอง",
    attributeFilterTip: "กำหนดสมการในการเลือกตามแอตทริบิวต์ สำหรับใช้งานในเครื่องมือวิจเก็ต เพื่อกรองข้อมูลจากชั้นข้อมูลที่ต้องการสอบถาม",
    noExpressionDefinedTip: "ไม่มีการแสดงผลลัพธ์ที่ถูกกำหนด",
    needInputValuesTip: "ต้องป้อนค่าขณะรัน",
    setExpressions: "ชุดการแสดงผล",
    spatialFilter: "ตัวกรองเชิงพื้นที่",
    spatialFilterTip: "เลือกตัวกรองเชิงพื้นที่(s) ที่ใช้ในเครื่องมือเพื่อจำกัดการแสดงผล",
    defaultOption: "ค่าตั้งต้น",
    useCurrentExtentTip: "บางส่วนหรือทั้งหมดภายในขอบเขตแผนที่ปัจจุบัน",
    useDrawGraphicTip: "บางส่วนหรือทั้งหมดที่อยู่ภายในภาพบนแผนที่",
    useFeaturesTip: "ขึ้นอยู่กับตำแหน่งที่ตั้งที่สัมพันธ์กับลักษณะการทำงานในเลเยอร์อื่น",
    noSpatialLimitTip: "ไม่จำกัดผลการค้นหาตำแหน่ง",
    drawingTools: "เครื่องมือสำหรับวาด",
    bufferSettings: "การตั้งค่าบัฟเฟอร์",
    defaultDistance: "ระยะเริ่มต้น",
    bufferDistance: "ระยะทางขยายออกไป",
    defaultUnit: "หน่วยเริ่มต้น",
    miles: "ไมล์",
    kilometers: "กิโลเมตร",
    feet: "ฟุต",
    meters: "เมตร",
    yards: "หลา",
    nauticalMiles: "ไมล์ทะเล",
    availableSpatialRelationships: "ความสัมพันธ์เชิงพื้นที่ที่เหมาะสม",
    setSpatialRelationships: "ตั้งค่าความสัมพันธ์ของพื้นที่",
    availability: "สภาพพร้อมใช้งาน",
    relationship: "ความสัมพันธ์",
    label: "ป้ายชื่อ",
    intersect: "พื้นที่ร่วมกัน",
    contain: "ประกอบด้วย",
    areContainedIn: "ที่ประกอบด้วย",
    cross: "กากบาท",
    envelopeIntersect: "การตัดขวาง",
    overlap: "ซ้อนทับ",
    areOverlapped: "ที่ซ้อนทับกัน",
    touche: "สัมผัส",
    within: "ภายใน",
    areWithin: "ที่อยู่ภายใน",
    indexIntersect: "ค่าที่ intersect",
    itemTitle: "หัวข้อรายการ",
    displayFields: "แสดงฟิลด์",
    sortingFields: "เรียงลำดับฟิลด์",
    setDisplayFields: "ตั้งค่าแสดงฟิลด์",
    symbol: "สัญลักษณ์",
    setSymbol: "ตั้งค่าสัญลักษณ์",
    serviceSymbolTip: "ใช้สัญลักษณ์ที่กำหนดโดยชั้นของข้อมูล",
    exportTip: "แสดงปุ่มส่งออก",
    keepResultsTip: "เก็บผลลัพธ์บนแผนที่หลังจากเครื่องมือถูกปิด",
    queryRelatedRecords: "สอบถามความสัมพันธ์ของ records",
    createLayerForTaskTip: "ระบุวิธีการสร้างเลเยอร์",
    oneLayerForTaskTip: "สร้างเลเยอร์สำหรับงานนี้เท่านั้น",
    multipleLayerForTaskTip: "สร้างเลเยอร์ใหม่ทุกครั้งที่รันงานนี้"
  })
);
