define(
	 ({
		queries: "การตั้งคำถาม",
		addNew: "เพิ่มใหม่",
		setSource: "ตั้งค่า",
		setDataSource: "ตั้งค่าแหล่งข้อมูล",
		name: "ชื่อ",
		querySource: "ที่มาของคำถาม",
		queryName: "ชื่อคำถาม",
		queryDefinition: "นิยามคำถาม",
		resultsSetting: "การตั้งค่าผลลัพธ์",
		symbolSetting: "การตั้งค่าสัญลักษณ์",
		resultSettingTip: "ระบุความหมายและวิธีการแสดงผลลัพธ์",
		resultItemTitle: "ชื่อของผลลัพธ์",
		resultItemContent: "เนื้อหาผลลัพธ์ข้อมูล",
		fieldsSetTip: "เลือกฟิลด์ที่คุณต้องการแสดง เลือกฟิลด์ที่จะเปลี่ยนชื่อแฝง ลำดับ หรือรูปแบบ",
		addField: "เพิ่มฟิลด์",
		visibility: "มองเห็นได้",
		alias: "นามแฝง",
		specialType: "ประเภทประเภท",
		actions: "กระทำ",
		none: "ไม่มี",
		link: "ลิงก์",
		image: "รูปภาพ",
		noField: "ไม่มีฟิลด์",
		operationalLayerTip: "เพิ่มผลลัพธ์เป็นชั้นข้อมูลเกี่ยวกับการดำเนินงาน",
		setLayerSymbolTip: "ตั้งค่าสัญลักษณ์สำหรับผลลัพธ์การตั้งคำถาม ",
		setSelectedSymbolTip: "ตั้งค่าสัญลักษณ์ของฟีเจอร์ที่เลือก",
		notUseFilter: "ห้ามใช้ตัวกรอง",
		setSourceTip: "โปรดตั้งค่าที่มาของคำถาม",
		setFilterTip: "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
		ok: "ตกลง",
		cancel: "ยกเลิก",
		noFilterTip: "หากไม่กำหนดตัวกรอง  แบบสอบถามนี้จะแสดงรายการคุณลักษณะทั้งหมดในแหล่งข้อมูลที่ระบุ"
  })
);