define(
   ({
    taskUrl: "Task-URL",
    serviceURLPlaceholder: "Geben Sie die URL des Geoverarbeitungs-Task ein",
    ok: "OK",
    cancel: "Abbrechen",
    layer: "Layer",
    action: "Aktion",
    input: "Eingabe",
    output: "Ausgabe",
    name: "Name",
    type: "Typ",
    required: "Erforderlich",
    layerOrder: "Layer-Reihenfolge",
    options: "Optionen",
    defaultValue: "Standardwert",
    inputFeatureBy: "Eingabe-Feature nach",
    renderer: "Renderer",
    displayType: "Anzeigetyp",
    label: "Beschriftung",
    tooltip: "QuickInfo",
    visible: "Sichtbar",
    helpUrl: "Hilfe-URL",
    useResultMapService: "Zeichenoptionen des Ergebnis-Kartenservice verwenden",
    drawOnMap: "Interaktives Zeichnen auf der Karte",
    selectLayer: "Auswahl eines Layers auf der Karte",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Ergebnis als operationalen Layer hinzufügen",
    popup: "Pop-up",
    setTask: "Festlegen",
    setTaskTitle: "GV-Task festlegen",
    enablePopup: "Pop-up aktivieren",
    unSupportGeometryType: "Renderer kann aufgrund des unbekannten Geometrietyps nicht festgelegt werden.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Datei hochladen",
    selectFileToUpload: "Datei auswählen...",
    upload: "Hochladen",
    rasterFormat: "Raster-Datenformat",
    noFileSelected: "Keine Datei ausgewählt!",
    uploadSuccess:"Datei wurde erfolgreich hochgeladen!",
    showLayerContent: "Layer-Inhalt anzeigen",
    Feet: "Fuß",
    Yards: "Yard",
    Miles: "Meilen",
    NauticalMiles: "Seemeilen",
    Meter: "Meter",
    Kilometers: "Kilometer",
    urlPlaceholder: "Feature-Set-URL",
    allowToExport: "Exportieren von Ergebnissen zulassen"
  })
);
