define(
   ({
    taskUrl: "Task-URL",
    serviceURLPlaceholder: "Geben Sie die URL des Geoverarbeitungs-Task ein",
    ok: "OK",
    cancel: "Abbrechen",
    layer: "Layer",
    action: "Aktion",
    input: "Eingabe",
    output: "Ausgabe",
    name: "Name",
    type: "Typ",
    required: "Erforderlich",
    layerOrder: "Layer-Reihenfolge",
    options: "Optionen",
    defaultValue: "Standardwert",
    inputFeatureBy: "Eingabe-Feature nach",
    renderer: "Renderer",
    displayType: "Anzeigetyp",
    label: "Beschriftung",
    tooltip: "QuickInfo",
    visible: "Sichtbar",
    helpUrl: "Hilfe-URL",
    useResultMapService: "Zeichenoptionen des Ergebnis-Karten-Service verwenden",
    drawOnMap: "Interaktives Zeichnen auf der Karte",
    selectLayer: "Auswahl eines Layers auf der Karte",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Ergebnis als operationalen Layer hinzufügen",
    popup: "Pop-up",
    setTask: "Festlegen",
    setTaskTitle: "GV-Task festlegen",
    enablePopup: "Pop-up aktivieren"
  })
);