define(
   ({
    _widgetLabel: "Requête",
    executeQueryTip: "Cliquez sur un des éléments de tâches suivants pour exécuter la requête.",
    invalidConfig: "Configuration non valide. Utilisez la page Paramètres de la requête pour obtenir une configuration appropriée.",
    queryParams: "Options",
    parameters: "OPTIONS",
    queries: "REQUETES",
    apply: "APPLIQUER",
    queryResults: "Résultats",
    clear: "Effacer",
    noResults: "Aucune entité trouvée.",
    queryError: "La requête a échoué !",
    numberFound: "Nombre d’entités trouvées",
    mapExtentTip: "Limitez les résultats à la zone cartographique actuelle.",
    noValue: "Aucune valeur",
    and: "et",
    stringOperatorIs: "est", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "n\'est pas",
    stringOperatorStartsWith: "commence par",
    stringOperatorEndsWith: "se termine par",
    stringOperatorContains: "contient",
    stringOperatorDoesNotContain: "ne contient pas",
    stringOperatorIsBlank: "est vide",
    stringOperatorIsNotBlank: "n\'est pas vide",
    dateOperatorIsOn: "est le", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "n\'est pas le",
    dateOperatorIsBefore: "est avant",
    dateOperatorIsAfter: "est après",
    dateOperatorDays: "jours",
    dateOperatorWeeks: "semaines", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "mois",
    dateOperatorInTheLast: "au cours des derniers",
    dateOperatorNotInTheLast: "pas au cours des derniers",
    dateOperatorIsBetween: "est entre",
    dateOperatorIsNotBetween: "n\'est pas entre",
    dateOperatorIsBlank: "est vide",
    dateOperatorIsNotBlank: "n\'est pas vide",
    numberOperatorIs: "est", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "n\'est pas",
    numberOperatorIsAtLeast: "est au moins",
    numberOperatorIsLessThan: "est inférieur à",
    numberOperatorIsAtMost: "est au plus",
    numberOperatorIsGreaterThan: "est supérieur à",
    numberOperatorIsBetween: "est entre",
    numberOperatorIsNotBetween: "n\'est pas entre",
    numberOperatorIsBlank: "est vide",
    numberOperatorIsNotBlank: "n\'est pas vide",
    operationalLayerTip: "Ajouter le résultat comme couche opérationnelle",
    queryResult: "Résultat de la requête",
    specifyParamsTip: "Spécifier les paramètres de cette tâche",
    useSpatialFilter: "Utiliser un filtre spatial pour limiter les entités",
    useCurrentMapExtent: "Uniquement les entités qui intersectent la zone cartographique actuelle",
    drawGraphicOnMap: "Uniquement les entités qui intersectent la zone définie par l\'utilisateur",
    specifySpatialFilterMsg: "Spécifiez un filtre spatial pour cette tâche.",
    clearResults: "Effacer les résultats",
    operationalTip: 'Lorsque cette option est sélectionnée, les résultats sont conservés sur la carte jusqu’à l’activation du bouton \"${clearResults}\".',
    noneQueryTip: "Aucune tâche de requête n\'a été configurée pour ce widget.",
    noPermissionsMsg: "Vous n’êtes pas autorisé à accéder à ce service.",
    attributesFromRelationship: "Attributs de la table associée",
    tasks: "Tâches",
    applySpatialFilterToLimitResults: "Appliquer un filtre spatial pour limiter les résultats",
    useCurrentExtentTip: "Partiellement ou entièrement dans l\'étendue de la carte actuelle",
    useDrawGraphicTip: "Partiellement ou entièrement dans la forme dessinée sur la carte",
    useFeaturesTip: "En fonction de leurs emplacements par rapport aux entités d\'une autre couche",
    noSpatialLimitTip: "Ne pas limiter spatialement les résultats",
    applySearchDistance: "Appliquer une distance de recherche",
    spatialRelationship: "Relation spatiale",
    relatedLayer: "Couche associée",
    bufferDistance: "Distance de la zone tampon",
    miles: "Miles",
    kilometers: "Kilomètres",
    feet: "Pieds",
    meters: "Mètres",
    yards: "Yards",
    nauticalMiles: "Milles nautiques",
    back: "Retour",
    execute: "Exécuter"
  })
);