define(
   ({
    _widgetLabel: "Tilannekuva (Beeta-versio)",
    locate_incident: "Paikanna tapahtuma",
    clear_incidents: "Tyhjennä tapahtumat",
    reverse_geocoded_address: "Lähin osoite",
    reverse_geocoded_error: "Ei käytettävissä",
    miles: "Mailia",
    kilometers: "Kilometriä",
    feet: "Jalkaa",
    meters: "Metriä",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    now: "NYT",
    wind: "TUULI",
    SUN: "SU",
    MON: "MA",
    TUE: "TI",
    WED: "KE",
    THU: "TO",
    FRI: "PE",
    SAT: "LA",
    defaultTabMsg: "Yhtään tapahtumaa ei ole tunnistettu.",
    actionLabel: "Määritä tapahtumaksi",
    drawPoint: "Piirrä piste",
    drawLine: "Piirrä viiva",
    drawPolygon: "Piirrä polygoni",
    saveIncident: "Tallenna tapaus",
    clearIncident: "Tyhjennä tapaus",
    useMapExtent: "Käytä nykyistä kartan laajuutta",
    noFeaturesFound: "Kohteita ei löytynyt.",
    downloadCSV: "LATAA CSV-TIEDOSTO",
    editComplete: "Kohteen tallennus onnistui.",
    updateComplete: "Kohteen päivitys onnistui.",
    deleteComplete: "Kohteen poisto onnistui.",
    sum: "SUMMA",
    min: "VÄHINT.",
    max: "ENINT.",
    avg: "KESKIARVO",
    count: "MÄÄRÄ",
    area: "ALUE",
    length: "PITUUS",
    notPolySave: "Määritä puskurin etäisyys ennen tallennusta.",
    update_btn: "Päivitä",
    delete_btn: "Poista"
  })
);
