define(
   ({
    "tabs_section_Label": "Registerkarten",
    "addTab": "Registerkarte hinzufügen",
    "layerName": "Layer",
    "layerType": "Analysetyp",
    "layerLabel": "Beschriftung",
    "actions": "Aktionen",
    "closest": "Nächstgelegenes Feature",
    "proximity": "Nachbarschaftsanalyse (Proximity)",
    "summary": "Zusammenfassung",
    "select_lbl": "-- Auswählen --",
    "general_setting_Label": "Allgemeine Einstellungen",
    "units_text_lbl": "Entfernungseinheiten",
    "miles": "Meilen",
    "kilometers": "Kilometer",
    "feet": "Fuß",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Seemeilen",
    "maximum_distance_lbl": "Maximale Entfernung zum nächstgelegenen Feature",
    "buffer_text_lbl": "Pufferbeschriftung",
    "buffer_lbl": "Pufferabstand",
    "buffer_max_lbl": "Maximaler Pufferabstand",
    "buffer_min_lbl": "Minimaler Pufferabstand",
    "routing_checkBox": "Routing aktivieren",
    "weather_Label": "Wetteroptionen",
    "weather_checkBox": "Wetterdaten einbeziehen",
    "selectLayers": "Wetter-Layer auswählen",
    "currentlySelectedLayer": "Aktuell ausgewählte Wetter-Layer",
    "missingTabLabel": "Mindestens eine Registerkarte weist keine Beschriftung auf",
    "cancel": "Abbrechen",
    "ok": "OK",
    "missingLayerInWebMap": "Keine operationalen Layer gefunden.",
    "selectFields": "Felder auswählen",
    "addField": "Feld hinzufügen",
    "sum": "SUMME",
    "min": "MINIMUM",
    "max": "MAXIMUM",
    "avg": "DURCHSCHNITT",
    "count": "ANZAHL",
    "area": "FLÄCHE",
    "length": "LÄNGE",
    "count_checkBox": "Anzahl anzeigen",
    "area_checkBox": "Bereich anzeigen",
    "length_checkBox": "Länge anzeigen",
    "max_records": "Maximaler Grenzwert erreicht"
  })
);
