define(
   ({
    _widgetLabel: "المعالجة الجغرافية",
    execute: "تنفيذ",
    help: "تعليمات",
    input: "المُدخَل",
    output: "المخرجات",
    executing: "تنفيذ",
    requiredInfo: "مطلوب.",
    drawnOnMap: "النتيجة مرسومة على الخريطة.",
    clear: "مسح",
    error: "خطأ",
    noToolConfig: "لا تتوفر مهمة المعالجة الجغرافية مُعرفة مُسبقًا.",
    useUrlForGPInput: "عنوان URL",
    useUploadForGPInput: "تحميل الملف",
    selectFileToUpload: 'حدد ملف...',
    upload: 'تحميل',
    rasterFormat: 'تنسيق البيانات النقطية',
    noFileSelected: 'لم يتم تحديد أي ملف!',
    uploadSuccess:'تم تحميل الملف بنجاح!',
    url: "عنوان URL",
    showLayerContent: "عرض محتوى الطبقة",
    invalidUrl: "عنوان url لخدمة معالم غير صحيحة",
    Feet: "قدم",
    Yards: "ياردة",
    Miles: "ميل",
    NauticalMiles: "الأميال البحرية",
    Meter: "متر",
    Kilometers: "كيلومترات",
    urlPlaceholder: "عنوان URL لمجموعة المعالم"
  })
);
