define(
	 ({
		chartTasks: "משימות תרשים",
		addNew: "הוסף חדש",
		addNewTip: "הוסף משימת תרשים חדשה",
		name: "שם",
		set: "הגדר",
		setDataSource: "הגדר מקור נתונים",
		generalSettingsTip: "הגדר מקור נתונים, כותרת ותיאור עבור תרשימים.",
		chartModeSettingTip: "בחר דרך לניתוח והצגה של נתונים כתרשימים.",
		detailsSettingTip: "קבע את מראה התרשים על-ידי הגדרת הסוגים והצבע, ואילו ערכים יוצגו בתרשים:",
		symbolSettingTip: "הגדר את תצוגת המפה עבור הנתונים בתרשים.",
		addFilterTip: "הוסף סינון לנתונים הללו",
		dataSource: "מקור נתונים",
		noResults: "לא נמצאה ישות.",
		chartTitle: "כותרת תרשים",
		description: "תיאור",
		chartingMode: "תצוגת תרשים",
		featureOption: "הצג ערכים עבור כל ישות בנפרד",
		categoryOption: "הצג ערכים לפי קטגוריות",
		countOption: "הצג מספרי ישויות לפי קטגוריות",
		fieldOption: "הצג ערכי מאפיינים כתרשימים",
		category: "קטגוריה",
		axisLabel: "תווית קטגוריה",
		categoryField: "שדה קטגוריה",
		operation: "תפעולי",
		originalOption: "השתמש בערכים מקוריים",
		sumOption: "סכום",
		averageOption: "ממוצע",
		minOption: "מינימום",
		maxOption: "מקסימום",
		valueFields: "שדות ערכים",
		moveUp: "הזז למעלה",
		moveDown: "הזז למטה",
		sortOrder: "מיין סדר תרשימים לפי תוויות קטגוריות",
		ascending: "סדר עולה",
		descending: "סדר יורד",
		chartType: "סוג תרשים",
		column: "תרשים טורים",
		bar: "תרשים עמודות",
		line: "תרשים קווים",
		pie: "תרשים עוגה",
		chartColor: "צבע תרשים",
		showDataLabels: "הצג תוויות נתונים",
		setSymbol: "סמל בחירה",
		setHighLightColor: "צבע הדגשה",
		settings: "הגדרות",
		mapInterationOptions: "אפשרויות לאינטראקציה עם המפה",
		preview: "תצוגה מקדימה",
		ok: "אישור",
		cancel: "ביטול",
		close: "סגור",
		setFilterTip: "הגדר בבקשה סינון תקין. ",
		setChartTitleTip: "הגדר את כותרת התרשים.",
		setChartTypeTip: "בחר לפחות סוג תרשים אחד.",
		setDataFieldTip: "בחר לפחות שדה ערך אחד.",
		setOutputFieldTip: "הגדר שדות פלט.",
		count: "ספירה",
		label: "תווית",
		horizontalAxis: "ציר אופקי",
		verticalAxis: "ציר אנכי",
		dataLabels: "תוויות נתונים",
		color: "צבע",
		colorful: "צבעוני",
		monochromatic: "צבע אחד",
    noTaskTip: "לחץ על \'הוסף חדש\' כדי להוסיף משימת תרשים",
    info: "מידע",
    charts: "תרשימים",
    options: "אפשרויות",
    taskName: "שם משימה",
    summary: "תקציר",
    resultDescription: "תאור התוצאה",
    spatialFilterTip: "בחר את הפילטרים המרחביים שיעשה בהם שימוש בווידג\'ט כדי להגביל את התוצאות.",
    defaultOption: "ברירת מחדל",
    useCurrentExtentTip: "חלקית או לחלוטין בתיחום המפה הנוכחי",
    useDrawGraphicTip: "חלקית או לחלוטין בגבולות הצורה המצוירת במפה",
    useFeaturesTip: "בהתבסס על המיקום שלהם ביחס לישויות בשכבה אחרת",
    noSpatialLimitTip: "ללא הגבלה מרחבית של התוצאות",
    drawingTools: "כלי שרטוט",
    bufferSettings: "הגדרות חיץ",
    defaultDistance: "מרחק המוגדר כברירת מחדל",
    bufferDistance: "מרחק חיץ",
    defaultUnit: "יחידה המוגדרת כברירת מחדל",
    miles: "מיילים",
    kilometers: "קילומטרים",
    feet: "רגל",
    meters: "מטרים",
    yards: "יארד",
    nauticalMiles: "מיילים ימיים",
    availableSpatialRelationships: "קישורים מרחביים זמינים",
    setSpatialRelationships: "הגדר קישורים מרחביים",
    availability: "זמינות",
    relationship: "קישור",
    actions: "פעולות",
    intersect: "חיתוך",
    contain: "הכלה",
    areContainedIn: "כלולים בתוך",
    cross: "צלב",
    envelopeIntersect: "אזור תיחום לחיתוך",
    overlap: "חפיפה",
    areOverlapped: "חופפים",
    touche: "נוגע",
    within: "בתוך",
    areWithin: "כלולים",
    indexIntersect: "חיתוך אינדקס"
  })
);