define({
  root: ({
    drsSOEURL: "Data Reviewer Server URL",
    chartSection:"Number of Slices/Bars in the chart",
    selectByGeography:"Include filter by geography",
    selectUrl: "Service layer for filter by geography",
    selectMapUrl: "Service for filter by geography",
    geometryServiceURL: "Geometry service URL",
    includeFieldNames:"Select Fields",
    fieldNames:"Field Names",
    lifecyclePhaseFieldName:"LIFECYCLEPHASE",
    setSource:"Set",
    defaultFieldName:"severity",
    warning: "Incorrect input",
    includeDefaultFieldName:"Default field name must be selected",
    selectFieldWarning:"Alteast one field should be visible",
    defaultFieldNotVisible: "Default field must be visible",
    batchJobCheckGroup:"batchjobcheckgroup",
    defaultColumn:"Default",
    visibleColumn:"Visible",
    fieldNameColumn:"Dashboard Field Name",
    aliasColumn:"Alias"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});