define({
  root: ({
    add: "Click to Add a New Bookmark",
    title: "Title",
    placeholderBookmarkName: "Bookmark Name",
    ok: "OK",
    cancel: "Cancel",
    warning: "Please finish the edit!",
    edit: "Edit bookmark",
    editFolder: "Edit folder",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",
    addBookmark: "Create a New Bookmark",
    titlebookmarks: "Bookmarks",
    labelDelete: "Delete",
    labelEdit: "Edit",
    webmapfoldername: "Webmap Bookmarks",
    addBookmarks: "Allow adding bookmarks in widget",
    addFolder: "Add Folder",
    _addBookmark: "Add Bookmark",
    clearSelected: "Clear Selected",
    clearToolTip: "The selected node in the tree will determine where a new bookmark is added. To add a new bookmark in the root of the tree you need to clear the current selected node.",
    expanded: "Folder expanded"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});
