define(
	 ({
		charts: "Diagrammu uzdevumi",
		addNew: "Pievienot jaunu",
		addNewTip: "Pievienot jaunu diagrammu uzdevumu",
		name: "Nosaukums",
		set: "Kopa",
		setDataSource: "Iestatīt datu avotu",
		generalSettingsTip: "Iestatiet diagrammu datu avotu, nosaukumu un aprakstu.",
		chartModeSettingTip: "Izvēlieties veidu, kā analizēt un parādīt datus kā diagrammas.",
		detailsSettingTip: "Iestatiet diagrammas izskatu, norādot tās tipus un krāsu, kā arī diagrammā parādāmās vērtības.",
		symbolSettingTip: "Iesatiet diagrammas datu rādīšanu kartē.",
		addFilterTip: "Pievienot filtru šiem datiem",
		dataSource: "Datu avots",
		noResults: "Nav atrasts neviens elements.",
		chartTitle: "Diagrammas nosaukums",
		description: "Apraksts",
		chartingMode: "Diagrammas rādīšana",
		featureOption: "Rādīt vērtības pēc elementa",
		categoryOption: "Rādīt vērtības pēc kategorijas",
		countOption: "Rādīt elementu skaitus pēc kategorijas",
		fieldOption: "Rādīt atribūtu vērtības kā diagrammas",
		category: "Kategorija",
		axisLabel: "Kategorijas etiķete",
		categoryField: "Kategorijas lauks",
		operation: "Darbība",
		originalOption: "Lietot sākotnējās vērtības",
		sumOption: "Summa",
		averageOption: "Vidējais",
		minOption: "Minimums",
		maxOption: "Maksimālais",
		valueFields: "Vērtību lauki",
		moveUp: "Pārvietot uz augšu",
		moveDown: "Pārvietot uz leju",
		sortOrder: "Kārtot diagrammu secību pēc kategoriju etiķetēm",
		ascending: "Augošā secībā",
		descending: "Dilstošā secībā",
		chartType: "Digarammas tips",
		column: "Stabiņu diagramma",
		bar: "Joslu diagramma",
		line: "Līniju diagramma",
		pie: "Sektoru diagramma",
		chartColor: "Diagrammas krāsa",
		showDataLabels: "Rādīt datu etiķetes",
		setSymbol: "Izvēles simbols",
		setHighLightColor: "Marķiera krāsa",
		settings: "Iestatījumi",
		mapInterationOptions: "Kartes darbību opcijas",
		preview: "Priekšskatījums",
		ok: "Labi",
		cancel: "Atcelt",
		close: "Aizvērt",
		setFilterTip: "Lūdzu, pareizi iestatiet filtru. ",
		setChartTitleTip: "Lūdzu, iestatiet diagrammas nosaukumu.",
		setChartTypeTip: "Lūdzu, izvēlieties vismaz vienu diagrammas tipu.",
		setDataFieldTip: "Lūdzu, izvēlieties vismaz vienu vērtību lauku.",
		setOutputFieldTip: "Lūdzu, izvēlieties izvades laukus.",
		count: "Skaitīt",
		label: "Kartes teksts",
		horizontalAxis: "Horizontālā ass",
		verticalAxis: "Vertikālā ass",
		dataLabels: "Datu teksti",
		color: "Krāsa",
		colorful: "Krāsains",
		monochromatic: "Melnbalts"
  })
);