define(
	 ({
		chartTasks: "Diagrammu uzdevumi",
		addNew: "Pievienot jaunu",
		addNewTip: "Pievienot jaunu diagrammu uzdevumu",
		name: "Nosaukums",
		set: "Kopa",
		setDataSource: "Iestatīt datu avotu",
		generalSettingsTip: "Iestatiet diagrammu datu avotu, nosaukumu un aprakstu.",
		chartModeSettingTip: "Izvēlieties veidu, kā analizēt un parādīt datus kā diagrammas.",
		detailsSettingTip: "Iestatiet diagrammas izskatu, norādot tās veidu un krāsu, kā arī diagrammā iekļaujamās vērtības:",
		symbolSettingTip: "Iesatiet diagrammas datu rādīšanu kartē.",
		addFilterTip: "Pievienot filtru šiem datiem",
		dataSource: "Datu avots",
		noResults: "Nav atrasts neviens elements.",
		chartTitle: "Diagrammas nosaukums",
		description: "Apraksts",
		chartingMode: "Diagrammas rādīšana",
		featureOption: "Rādīt vērtības pēc elementa",
		categoryOption: "Rādīt vērtības pēc kategorijas",
		countOption: "Rādīt elementu skaitus pēc kategorijas",
		fieldOption: "Rādīt atribūtu vērtības kā diagrammas",
		category: "Kategorija",
		axisLabel: "Kategorijas etiķete",
		categoryField: "Kategorijas lauks",
		operation: "Darbība",
		originalOption: "Lietot sākotnējās vērtības",
		sumOption: "Summa",
		averageOption: "Vidējais",
		minOption: "Minimums",
		maxOption: "Maksimālais",
		valueFields: "Vērtību lauki",
		moveUp: "Pārvietot uz augšu",
		moveDown: "Pārvietot uz leju",
		sortOrder: "Kārtot diagrammu secību pēc kategoriju etiķetēm",
		ascending: "Augošā secībā",
		descending: "Dilstošā secībā",
		chartType: "Digarammas tips",
		column: "Stabiņu diagramma",
		bar: "Joslu diagramma",
		line: "Līniju diagramma",
		pie: "Sektoru diagramma",
		chartColor: "Diagrammas krāsa",
		showDataLabels: "Rādīt datu etiķetes",
		setSymbol: "Izvēles simbols",
		setHighLightColor: "Marķiera krāsa",
		settings: "Iestatījumi",
		mapInterationOptions: "Kartes darbību opcijas",
		preview: "Priekšskatījums",
		ok: "Labi",
		cancel: "Atcelt",
		close: "Aizvērt",
		setFilterTip: "Lūdzu, pareizi iestatiet filtru. ",
		setChartTitleTip: "Lūdzu, iestatiet diagrammas nosaukumu.",
		setChartTypeTip: "Lūdzu, izvēlieties vismaz vienu diagrammas tipu.",
		setDataFieldTip: "Lūdzu, izvēlieties vismaz vienu vērtību lauku.",
		setOutputFieldTip: "Lūdzu, izvēlieties izvades laukus.",
		count: "Skaitīt",
		label: "Kartes teksts",
		horizontalAxis: "Horizontālā ass",
		verticalAxis: "Vertikālā ass",
		dataLabels: "Datu teksti",
		color: "Krāsa",
		colorful: "Krāsains",
		monochromatic: "Melnbalts",
    noTaskTip: "Noklikšķiniet uz Pievienot jaunu, lai pievienotu diagrammas uzdevumu",
    info: "Informācija",
    charts: "Diagrammas",
    options: "Opcijas",
    taskName: "Uzdevuma nosaukums",
    summary: "Kopsavilkums",
    resultDescription: "Rezultāta apraksts",
    spatialFilterTip: "Izvēlieties logrīkā izmantoto(-s) telpisko(-s) filtru(-s), lai ierobežotu rezultātus.",
    defaultOption: "Noklusējums",
    useCurrentExtentTip: "Daļēji vai pilnībā pašreizējā kartes pārklājumā",
    useDrawGraphicTip: "Daļēji vai pilnībā uz kartes uzzīmētajā formā",
    useFeaturesTip: "Pēc to atrašanās vietās attiecībā pret elementiem citā slānī",
    noSpatialLimitTip: "Neierobežot rezultātus telpiski",
    drawingTools: "Zīmēšanas rīki",
    bufferSettings: "Bufera iestatījumi",
    defaultDistance: "Noklusējuma attālums",
    bufferDistance: "Bufera distance",
    defaultUnit: "Noklusējuma vienība",
    miles: "Jūdzes",
    kilometers: "Kilometri",
    feet: "Pēdas",
    meters: "Metri",
    yards: "Jardi",
    nauticalMiles: "Jūras jūdzes",
    availableSpatialRelationships: "Pieejamās telpiskās attiecības",
    setSpatialRelationships: "Iestatīt telpiskās attiecības",
    availability: "Pieejamība",
    relationship: "Attiecības",
    actions: "Darbības",
    intersect: "šķērso",
    contain: "satur",
    areContainedIn: "ietilpst",
    cross: "krustojums",
    envelopeIntersect: "aploksne šķērso",
    overlap: "pārklāj",
    areOverlapped: "ir pārklāts",
    touche: "skar",
    within: "ietver",
    areWithin: "ietverts",
    indexIntersect: "indekss šķērso"
  })
);