define({
  root: ({
    selectAnalysisTools:"Select analysis tools to be listed in the widget.",
    selected: "selected",
    name: "Name",
    graphicalDisplay:"Graphical display",
    usage: "Usage",
    toolNotAvailable: "This tool is not available because the map doesn't contain required feature layer(s).",
    aggregatePoints:"Aggregate Points",
    aggregatePointsUsage:"Aggregate points into polygons where the points are located.",
    aggregatePointsInputTip: "Specify the point feature layer that will be aggregated into the polygons in the polygon feature layer.",
    calculateDensity:"Calculate Density",
    calculateDensityUsage:"Create a density map from point or line features by spreading known quantities of some phenomenon(represented as attributes of the points or lines) across the map.",
    calculateDensityInputTip:"Specify the point or line features from which to calculate density.",
    connectOriginsToDestinations: "Connect Origins To Destinations",
    connectOriginsToDestinationsUsage: "Measure the travel time or distance between pairs of points.",
    connectOriginsToDestinationsInputTip: "Specify the starting point or points of the routes to be generated.",
    createBuffers:"Create Buffers",
    createBuffersUsage:"Create buffer polygons from input features.",
    createBuffersInputTip:"Specify the point, line, or polygon feature layer to be buffered.",
    createDriveTimeAreas:"Create Drive Time Areas",
    createDriveTimeAreasUsage:"Create drive-time (or drive-distance) polygons around input points for the given drive-time values.",
    createDriveTimeAreasInputTip:"Specify the points where drive-time areas will be drawn.",
    createViewshed:"Create Viewshed",
    createViewshedUsage:"Creates areas that are visible based on locations you specify.",
    createViewshedInputTip:"Specify the observer locations to identify visible areas.",
    createWatersheds:"Create Watersheds",
    createWatershedsUsage:"Creates catchment areas based on locations you specify.",
    createWatershedsInputTip:"Specify the point features used for calculating watersheds.",
    deriveNewLocations:"Derive New Locations",
    deriveNewLocationsUsage:"Derive new features from the input layers that meet a query you specify",
    deriveNewLocationsInputTip:"Specify the analysis layer to use as input.",
    dissolveBoundaries:"Dissolve Boundaries",
    dissolveBoundariesUsage:"Dissolve polygons that overlap or share a common boundary.",
    dissolveBoundariesInputTip:"Specify the layer containing polygon features that will be dissolved.",
    enrichLayer:"Enrich Layer",
    enrichLayerUsage:"Enrich input features with people, places and businesses facts about nearby areas.",
    enrichLayerInputTip:"Specify the features to enrich with new data.",
    extractData:"Extract Data",
    extractDataDesc:"Extract data from one or more layers within a given extent",
    extractDataInputTip:"Specify the input feature layer to extract.",
    findExistingLocations:"Find Existing Locations",
    findExistingLocationsUsage:"Select features in the input layer that meet an attribute and/or spatial query you specify",
    findExistingLocationsInputTip:"Specify the analysis layers to use as input.",
    findHotSpots:"Find Hot Spots",
    findHotSpotsUsage:"Find statistically signficant clusters of input features or high/low values.",
    findHotSpotsInputTip:"Specify the point or polygon feature layer for which hot spots will be calculated.",
    findNearest:"Find Nearest",
    findNearestUsage:"For each feature on an input layer, find its closest feature on another layer",
    findNearestInputTip:"Specify the point, line, or polygon features from which the nearest locations are found.",
    findSimilarLocations:"Find Similar Locations",
    findSimilarLocationsUsage:"Measure the similarity of candidate locations to one or more reference locations.",
    findSimilarLocationsInputTip:"Specify a feature layer that contains one or more reference locations against which features in the search layer will be evaluated for similarity.",
    interpolatePoints:"Interpolate Points",
    interpolatePointsUsage:"Predict values at new locations based on measurements from a collection of points.",
    interpolatePointsInputTip:"Specify the point features that will be interpolated.",
    mergeLayers:"Merge Layers",
    mergeLayersUsage:"Merge features from multiple layers into a new layer",
    mergeLayersInputTip:"Specify the feature layer to be merged with the merge layer.",
    overlayLayers:"Overlay Layers",
    overlayLayersUsage:"Combine multiple layers into one single layer with information from the original layers preserved.",
    overlayLayersInputTip:"Specify the feature layer that will be overlayed with the overlay layer.",
    planRoutes:"Plan Routes",
    planRoutesUsage:"Determine how to efficiently divide tasks among a mobile workforce.",
    planRoutesInputTip:"Specify the points that the vehicles, drivers, or routes, should visit.",
    summarizeNearby:"Summarize Nearby",
    summarizeNearbyUsage:"For each feature on an input layer, summarize data within a distance from features on another layer.",
    summarizeNearbyInputTip:"Specify the point, line, or polygon feature layer from which distances will be measured to features in summarize layer.",
    summarizeWithin:"Summarize Within",
    summarizeWithinUsage:"For each polygon on an input polygon layer, summarize data located within it from features on another layer.",
    summarizeWithinInputTip:"Specify the polygon feature layer to be summarized toward.",
    traceDownstream:"Trace Downstream",
    traceDownstreamUsage:"Determine the flow paths in a downstream direction from the locations you specify.",
    traceDownstreamInputTip:"Specify the point features used for the starting location of a downstream trace."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});
