define(
   ({
    _widgetLabel: "Diagram",
    executeChartTip: "Klik på en af følgende opgaveelementer for at oprette diagrammet.",
    invalidConfig: "Ugyldig konfiguration.",
    noneChartTip: "Der er ikke blevet konfigureret nogen diagramopgave for denne widget.",
    chartParams: "Indstillinger",
    charts: "DIAGRAMMER",
    apply: "ANVEND",
    useSpatialFilter: "Brug spatialt filter til at begrænse objekter",
    useCurrentMapExtent: "Kun objekter, der gennemskærer det aktuelle kortområde",
    drawGraphicOnMap: "Kun objekter, der gennemskærer et brugerdefineret område",
    chartResults: "Diagramresultater",
    clearResults: "Ryd resultater",
    noPermissionsMsg: "Du har ikke adgang til denne tjeneste.",
    specifySpatialFilterMsg: "Angiv et spatialt filter til denne opgave.",
    queryError: "Forespørgslen mislykkedes.",
    noResults: "Ingen resultater fundet.",
    category: "Kategori",
    count: "Tælling",
    label: "Mærke",
    horizontalAxis: "Horisontal akse",
    verticalAxis: "Vertikal akse",
    dataLabels: "Dataetiketter",
    color: "Farve",
    colorful: "Farverig",
    monochromatic: "Monokrom",
    tasks: "Opgaver",
    results: "Resultater",
    applySpatialFilterToLimitResults: "Anvend et spatialt filter til at begrænse resultaterne",
    useCurrentExtentTip: "Delvist eller helt inden for den aktuelle kortudstrækning",
    useDrawGraphicTip: "Delvist eller helt inden for den form, der et tegnet på kortet",
    useFeaturesTip: "Baseret på deres positioner i forhold til objekterne i et andet lag",
    noSpatialLimitTip: "Begræns ikke resultaterne spatialt",
    applySearchDistance: "Anvend en søgeafstand",
    spatialRelationship: "Spatial relation",
    relatedLayer: "Relateret lag",
    clear: "Ryd",
    bufferDistance: "Bufferafstand",
    miles: "Miles",
    kilometers: "Kilometer",
    feet: "Fod",
    meters: "Meter",
    yards: "Yards",
    nauticalMiles: "Sømil",
    back: "Tilbage",
    execute: "Udfør"
  })
);