define(
   ({
    routeUrl: "URL rută",
    locatorUrl: "URL geocodificator",
    geocoderOptions: "Opţiuni geocodificator",
    autoComplete: "Completare automată",
    maxLocations: "Număr maxim locaţii",
    minCharacters: "Număr minim caractere",
    searchDelay: "Decalaj căutare",
    placeholder: "Substituent",
    routeOptions: "Opţiuni rută",
    directionsLanguage: "Limbă instrucţiuni de deplasare",
    directionsLengthUnits: "Unităţi de lungime pentru instrucţiunile de deplasare",
    directionsOutputType: "Tip de ieşire pentru instrucţiunile de deplasare",
    impedanceAttribute: "Atribut impedanţă",
    kilometers: "Kilometri",
    miles: "Mile",
    meters: "Metri",
    feet: "Ft",
    yards: "Yarzi",
    nauticalMiles: "Mile marine",
    parametersTip: "Setaţi parametrii corect!",
    complete: "Finalizat",
    completeNoEvents: "Finalizat fără evenimente",
    instructionsOnly: "Doar instrucţiuni",
    standard: "Standard",
    summaryOnly: "Doar rezumat",
    travelModesUrl: "URL moduri de deplasare",
    searchPlaceholder: "Găsire adresă sau loc",
    trafficLayerUrl: "URL strat tematic trafic"
  })
);