define(
   ({
    "tabs_section_Label": "Cilnes",
    "addTab": "Pievienot cilni",
    "layerName": "Slānis",
    "layerType": "Analīzes tips",
    "layerLabel": "Etiķete",
    "actions": "Darbības",
    "closest": "Tuvākais elements",
    "proximity": "Tuvums",
    "summary": "Kopsavilkums",
    "select_lbl": "-- Atlasīt --",
    "general_setting_Label": "Vispārējie iestatījumi",
    "units_text_lbl": "Garuma vienības",
    "miles": "Jūdzes",
    "kilometers": "Kilometri",
    "feet": "Pēdas",
    "meters": "Metri",
    "yards": "Jardi",
    "nauticalMiles": "Jūras jūdzes",
    "maximum_distance_lbl": "Tuvākā elementa maksimālais attālums",
    "buffer_text_lbl": "Bufera kartes teksts",
    "buffer_lbl": "Bufera distance",
    "buffer_max_lbl": "Maksimālais bufera attālums",
    "buffer_min_lbl": "Minimālais bufera attālums",
    "routing_checkBox": "Iespējot maršrutēšanu",
    "weather_Label": "Laikapstākļu opcijas",
    "weather_checkBox": "Iekļaut informāciju par laikapstākļiem",
    "selectLayers": "Atlasīt laikapstākļu slāņus",
    "currentlySelectedLayer": "Pašreiz atlasītie laikapstākļu slāņi",
    "missingTabLabel": "Vismaz vienai cilnei nav marķējuma",
    "cancel": "Atcelt",
    "ok": "Labi",
    "missingLayerInWebMap": "Nav atrasti darbības slāņi.",
    "selectFields": "Atlasīt laukus",
    "addField": "Pievienot lauku",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAKS.",
    "avg": "VID",
    "count": "SKAITĪT",
    "area": "APGABALS",
    "length": "GARUMS",
    "count_checkBox": "Rādīt skaitu",
    "area_checkBox": "Rādīt apgabalu",
    "length_checkBox": "Rādīt garumu",
    "max_records": "Sasniegts maksimālais ierobežojums"
  })
);
