define({
  root: ({
    _widgetLabel: "Situation Awareness (Beta)",
    locate_incident: "Locate Incident",
    clear_incidents: "Clear Incidents",
    reverse_geocoded_address: "Closest address",
    reverse_geocoded_error: "Not available",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical Miles",
    now: "NOW",
    wind: "WIND",
    SUN: "SUN",
    MON: "MON",
    TUE: "TUE",
    WED: "WED",
    THU: "THU",
    FRI: "FRI",
    SAT: "SAT",
    defaultTabMsg: "No incidents identified.",
    actionLabel: "Set As Incident",
    drawPoint: "Draw Point",
    drawLine: "Draw Line",
    drawPolygon: "Draw Polygon",
    saveIncident: "Save Incident",
    clearIncident: "Clear Incident",
    useMapExtent: "Use the current map extent",
    noFeaturesFound: "No features found.",
    downloadCSV: "DOWNLOAD CSV",
    editComplete: "Feature saved sucessfully!",
    updateComplete: "Feature updated sucessfully!",
    deleteComplete: "Feature deleted sucessfully!",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH",
    notPolySave: "Please specify a buffer distance before saving.",
    update_btn: "Update",
    delete_btn: "Delete"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
