define(
   ({
    _widgetLabel: "Reportar Elemento",
    select: "Selecionar",
    draw: "Desenhar",
    chooseALayer: "Selecione uma camada",
    clickAFeature: "Clique num elemento no mapa para o selecionar.",
    loadingFeatures: "A obter detalhes de elementos selecionados...",
    errorTitle: "Erro",
    errorIdentify: "Identificar erros em elementos. Por favor, verifique o registo da consola para obter detalhes.",
    infoWindowTitle: "Detalhes",
    layerLabel: "Nome da Camada",
    reviewStatusLabel: "Rever Estado",
    selectReviewStatusAdd: "Adicionar Elemento",
    selectReviewStatusDelete: "Eliminar Elemento",
    selectReviewStatusMove: "Mover Elemento",
    selectReviewStatusReshape: "Remodelar Elemento",
    drawReviewStatusMissing: "Elemento(s) em Falta",
    drawReviewStatusPosition: "Erro Posicional",
    drawReviewStatusShape: "Erro de Forma",
    drawReviewStatusAttribute: "Erro de Atributo",
    notesLabel: "Notas",
    severityLabel: "Severidade",
    reportedByLabel: "Reportado Por",
    reportedByDefault: "anónimo",
    reportButton: "Relatório",
    reportMessage: "Relatório recebido",
    errorReportMessage: "Houve um erro ao reportar o seu elemento",
    drawErrorInstructions: "Selecione um ponto, linha ou polígono e desenhe a geometria de erro no mapa:",
    errorMapService: "Houve um erro ao obter as informações de serviço de mapa",
    noFeatureSelected : "Não foram encontrados elementos na localização clicada",
    selectFeatureMapPoint: "Clique para selecionar um elemento",
    drawFeatureMapPoint: "Clique para adicionar um ponto",
    popupMessage:"Mensagem",
    popupError:"Erro",
    manyFeaturesSelected: "Mais do que um elemento encontrado. Por favor, aplique zoom e selecione um elemento para reportar."
  })
);
