define(
   ({
    "tabs_section_Label": "Separadores",
    "addTab": "Adicionar Separador",
    "layerName": "Camada",
    "layerType": "TiTipo de Análise",
    "layerLabel": "Rótulo",
    "actions": "Ações",
    "closest": "Elemento Mais Próximo",
    "proximity": "Proximidade",
    "summary": "Resumo",
    "select_lbl": "-- Seleccionar --",
    "general_setting_Label": "Configurações Gerais",
    "units_text_lbl": "Unidades de Distância",
    "miles": "Milhas",
    "kilometers": "Quilômetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas Náuticas",
    "maximum_distance_lbl": "Escolher Máxima Distancia de Elemento",
    "buffer_text_lbl": "Etiqueta de Buffer",
    "buffer_lbl": "Distância do Buffer",
    "buffer_max_lbl": "Distancia Máxima de Buffer",
    "buffer_min_lbl": "Distancia Mínima de Buffer",
    "routing_checkBox": "Activar Roteamento",
    "weather_Label": "Opções de Condições Atmosféricas",
    "weather_checkBox": "Incluir Informações de Condições Atmosféricas",
    "selectLayers": "Seleccionar Camadas de Condições Atmosféricas",
    "currentlySelectedLayer": "Camadas de condições atmosféricas actualmente seleccionadas",
    "missingTabLabel": "Está a faltar uma etiqueta a pelo menos um separador",
    "cancel": "Cancelar",
    "ok": "Ok",
    "missingLayerInWebMap": "Nenhuma camada operacional encontrada.",
    "selectFields": "Selecionar Campos",
    "addField": "Adicionar Campo",
    "sum": "SUM",
    "min": "MIN",
    "max": "MAX",
    "avg": "AVG",
    "count": "CONTAGEM",
    "area": "ÁREA",
    "length": "LENGTH",
    "count_checkBox": "Exibir Contagem",
    "area_checkBox": "Exibir Área",
    "length_checkBox": "Exibir Comprimento",
    "max_records": "Limite máximo atingido"
  })
);
