define(
   ({
    selectAnalysisTools:"Vælg de analyseværktøjer, der skal være angivet i widget'en.",
    selected: "valgt",
    name: "Navn",
    graphicalDisplay:"Grafisk visning",
    usage: "Brug",
    toolNotAvailable: "Dette værktøj er ikke tilgængeligt, fordi kortet ikke indeholder de påkrævede vektorlag.",
    aggregatePoints:"Aggregér punkter",
    aggregatePointsUsage:"Aggregér punkter til polygoner, hvor punkterne findes.",
    aggregatePointsInputTip: "Angiv det punktvektorlag, der skal aggregeres til polygoner i polygonvektorlaget.",
    calculateDensity:"Beregn tæthed",
    calculateDensityUsage:"Opret et tæthedskort ud fra punkt- eller linjeobjekter ved at sprede kendte mængder af et fænomen (repræsenteret som attributter af punkter eller linjer) på tværs af kortet.",
    calculateDensityInputTip:"Angiv de punkt- eller linjeobjekter, som tætheden skal beregnes ud fra.",
    connectOriginsToDestinations: "Forbind udgangspunkter med destinationer",
    connectOriginsToDestinationsUsage: "Mål rejsetiden eller -afstanden mellem punktpar.",
    connectOriginsToDestinationsInputTip: "Angiv startpunktet eller -punkterne for de ruter, der skal genereres.",
    createBuffers:"Opret buffere",
    createBuffersUsage:"Opret bufferpolygoner ud fra inputobjekter.",
    createBuffersInputTip:"Angiv de punkt-, linje eller polygonvektorlag, der skal placeres i bufferen.",
    createDriveTimeAreas:"Opret køretidsområder",
    createDriveTimeAreasUsage:"Opret køretids- (eller køreafstands-) polygoner omkring inputpunkterne for de givne køretidsværdier.",
    createDriveTimeAreasInputTip:"Angiv de punkter, hvor køretidsområdene skal tegnes.",
    createViewshed:"Opret udsigtsområde",
    createViewshedUsage:"Opretter områder, der er synlige baseret på steder, som du angiver.",
    createViewshedInputTip:"Angiv observationspunkter for at identificere synlige områder.",
    createWatersheds:"Opret vandskel",
    createWatershedsUsage:"Opretter vandopsamlingsområder baseret på steder, som du angiver.",
    createWatershedsInputTip:"Angiv de punktobjekter, der skal bruges til at beregne vandskel.",
    deriveNewLocations:"Udled nye steder",
    deriveNewLocationsUsage:"Udled nye objekter fra de inputlag, der opfylder en forespørgsel, som du angiver",
    deriveNewLocationsInputTip:"Angiv det analyselag, der skal bruges som input.",
    dissolveBoundaries:"Opløs grænser",
    dissolveBoundariesUsage:"Opløs de polygoner, der overlapper eller deler en fælles grænse.",
    dissolveBoundariesInputTip:"Angiv det lag, der indeholder de polygonobjekter, der skal opløses.",
    enrichLayer:"Berig lag",
    enrichLayerUsage:"Berig inputobjekter med person-, sted- og virksomhedsfakta om nærliggende områder.",
    enrichLayerInputTip:"Angiv de objekter, der skal beriges med nye data.",
    extractData:"Udtræk data",
    extractDataDesc:"Udtræk data fra et eller flere lag inden for en given udstrækning",
    extractDataInputTip:"Angiv de inputvektorlag, der skal udtrækkes.",
    findExistingLocations:"Find eksisterende steder",
    findExistingLocationsUsage:"Vælg objekter i det inputlag, der opfylder en attribut- og/eller spatial forespørgsel, du angiver",
    findExistingLocationsInputTip:"Angiv de analyselag, der skal bruges som input.",
    findHotSpots:"Find hotspots",
    findHotSpotsUsage:"Find statistisk signifikante, spatiale klyngedannelser med inputobjekter eller høje/lave værdier.",
    findHotSpotsInputTip:"Angiv det punkt- eller polygonvektorlag, som der skal beregnes hotspots for.",
    findNearest:"Find nærmeste",
    findNearestUsage:"For hvert objekt i et inputlag skal du finde det nærmeste objekt i et andet lag",
    findNearestInputTip:"Angiv de punkt-, linje eller polygonobjekter, hvorfra de nærmeste steder findes.",
    findSimilarLocations:"Find lignende steder",
    findSimilarLocationsUsage:"Mål ensartetheden for kandidatstederne i forhold til et eller flere referencesteder.",
    findSimilarLocationsInputTip:"Angiv et vektorlag, der indeholder et eller flere referencesteder, over for hvilke objekterne i søgelaget kan evalueres med henblik på ensartethed.",
    interpolatePoints:"Interpolér punkter",
    interpolatePointsUsage:"Forudsig værdier på nye placeringer baseret på målinger ud fra en samling af punkter.",
    interpolatePointsInputTip:"Angiv punktobjekter, der skal interpoleres.",
    mergeLayers:"Flet lag",
    mergeLayersUsage:"Flet objekter fra flere lag til ét nyt lag",
    mergeLayersInputTip:"Vælg det vektorlag, der skal flettes med det flettede lag.",
    overlayLayers:"Overlay af lag",
    overlayLayersUsage:"Kombinér flere lag til et enkelt lag med oplysninger fra de oprindeligt gemte lag.",
    overlayLayersInputTip:"Angiv det vektorlag, der skal dækkes med overlay-laget.",
    planRoutes:"Planlæg ruter",
    planRoutesUsage:"Bestem, hvordan du effektivt kan fordele opgaver blandt en mobil arbejdsstyrke.",
    planRoutesInputTip:"Angiv de punkter, som køretøjer, chauffører eller ruter skal besøge.",
    summarizeNearby:"Opsummér i nærheden",
    summarizeNearbyUsage:"For hvert objekt i et inputlag skal du summere data inden for en bestemt afstand fra objekterne i et andet lag.",
    summarizeNearbyInputTip:"Angiv det punkt-, linje- eller polygonvektorlag, hvorfra afstandene skal måles til objekterne i det summerede lag.",
    summarizeWithin:"Summér inden for",
    summarizeWithinUsage:"For hver polygon i et inputpolygonlag skal du summere data inden for en bestemt afstand fra objekterne i et andet lag.",
    summarizeWithinInputTip:"Angiv de polygonvektorlag, der skal summeres.",
    traceDownstream:"Gå med strømmen",
    traceDownstreamUsage:"Bestemmer vandløbsretninger i \"nedstrøms-retning\" fra de placeringer, som du angiver.",
    traceDownstreamInputTip:"Angiv de punktobjekter, der skal bruges som udgangspunkt for en \"nedstrøms\"-sporing."
  })
);
