define(
   ({
    selectAnalysisTools:"Vælg de analyseværktøjer, der skal bruges i widget\'en.",
    selected: "valgt",
    name: "Navn",
    graphicalDisplay:"Grafisk visning",
    usage: "Brug",
    settings: "Indstillinger",
    toolSetting: "Angiv værktøjsoplysninger",
    toolLabel: "Værktøjets visningsnavn",
    showHelpTip: "Vis hjælp-links i widget\'en",
    showCurrentMapExtent: "Vis den indstilling, der skal bruges til den aktuelle kortudstrækning",
    showCredits: "Vis indstillingen <b>Vis credits</b>",
    saveAsFeatureService: "Gem resultatet i brugerens konto",
    showReadyToUseLayers: "Vis lag, der er klar til brug, fra ArcGIS Online Living Atlas of the World",
    toolNotAvailable: "Dette værktøj er ikke tilgængeligt, fordi kortet ikke indeholder de påkrævede vektorlag.",
    aggregatePoints:"Aggregér punkter",
    aggregatePointsUsage:"Aggregér punkter til polygoner, hvor punkterne findes.",
    calculateDensity:"Beregn tæthed",
    calculateDensityUsage:"Opret et tæthedskort ud fra punkt- eller linjeobjekter ved at sprede kendte mængder af et fænomen (repræsenteret som attributter af punkter eller linjer) på tværs af kortet.",
    connectOriginsToDestinations: "Forbind udgangspunkter med destinationer",
    connectOriginsToDestinationsUsage: "Mål rejsetiden eller -afstanden mellem punktpar.",
    createBuffers:"Opret buffere",
    createBuffersUsage:"Opret bufferpolygoner ud fra inputobjekter.",
    createDriveTimeAreas:"Opret køretidsområder",
    createDriveTimeAreasUsage:"Opret køretids- (eller køreafstands-) polygoner omkring inputpunkterne for de givne køretidsværdier.",
    createViewshed:"Opret udsigtsområde",
    createViewshedUsage:"Opretter områder, der er synlige baseret på steder, som du angiver.",
    createWatersheds:"Opret vandskel",
    createWatershedsUsage:"Opretter vandopsamlingsområder baseret på steder, som du angiver.",
    deriveNewLocations:"Udled nye steder",
    deriveNewLocationsUsage:"Udled nye objekter fra de inputlag, der opfylder en forespørgsel, som du angiver",
    dissolveBoundaries:"Opløs grænser",
    dissolveBoundariesUsage:"Opløs de polygoner, der overlapper eller deler en fælles grænse.",
    enrichLayer:"Berig lag",
    enrichLayerUsage:"Berig inputobjekter med person-, sted- og virksomhedsfakta om nærliggende områder.",
    extractData:"Udtræk data",
    extractDataDesc:"Udtræk data fra et eller flere lag inden for en given udstrækning",
    findExistingLocations:"Find eksisterende steder",
    findExistingLocationsUsage:"Vælg objekter i det inputlag, der opfylder en attribut- og/eller spatial forespørgsel, du angiver",
    findHotSpots:"Find hotspots",
    findHotSpotsUsage:"Find statistisk signifikante, spatiale klyngedannelser med inputobjekter eller høje/lave værdier.",
    findNearest:"Find nærmeste",
    findNearestUsage:"For hvert objekt i et inputlag skal du finde det nærmeste objekt i et andet lag",
    findSimilarLocations:"Find lignende steder",
    findSimilarLocationsUsage:"Mål ensartetheden for kandidatstederne i forhold til et eller flere referencesteder.",
    interpolatePoints:"Interpolér punkter",
    interpolatePointsUsage:"Forudsig værdier på nye placeringer baseret på målinger ud fra en samling af punkter.",
    mergeLayers:"Flet lag",
    mergeLayersUsage:"Flet objekter fra flere lag til ét nyt lag",
    overlayLayers:"Overlay af lag",
    overlayLayersUsage:"Kombinér flere lag til et enkelt lag med oplysninger fra de oprindeligt gemte lag.",
    planRoutes:"Planlæg ruter",
    planRoutesUsage:"Bestem, hvordan du effektivt kan fordele opgaver blandt en mobil arbejdsstyrke.",
    summarizeNearby:"Opsummér i nærheden",
    summarizeNearbyUsage:"For hvert objekt i et inputlag skal du summere data inden for en bestemt afstand fra objekterne i et andet lag.",
    summarizeWithin:"Summér inden for",
    summarizeWithinUsage:"For hver polygon i et inputpolygonlag skal du summere data inden for en bestemt afstand fra objekterne i et andet lag.",
    traceDownstream:"Gå med strømmen",
    traceDownstreamUsage:"Bestemmer vandløbsretninger i \"nedstrøms-retning\" fra de placeringer, som du angiver."
  })
);
