define(
   ({
    routeUrl: "Route-URL",
    locatorUrl: "Geocoder-URL",
    geocoderOptions: "Geocodingopties",
    autoComplete: "Automatisch invullen",
    maxLocations: "Maximale locaties",
    minCharacters: "Minimale tekens",
    searchDelay: "Zoekvertraging",
    placeholder: "Tijdelijke aanduiding",
    routeOptions: "Routeopties",
    directionsLanguage: "Taal van de routebeschrijving",
    directionsLengthUnits: "Lengte-eenheden van de routebeschrijving",
    directionsOutputType: "Uitvoertype van de routebeschrijving",
    impedanceAttribute: "Impedantieattribuut",
    kilometers: "Kilometer",
    miles: "Mijl",
    meters: "Meter",
    feet: "Voet",
    yards: "Yard",
    nauticalMiles: "Zeemijl",
    parametersTip: "Stel de parameters correct in!",
    complete: "Voltooid",
    completeNoEvents: "Voltooid geen gebeurtenissen",
    instructionsOnly: "Alleen instructies",
    standard: "Standaard",
    summaryOnly: "Alleen samenvatting",
    travelModesUrl: "URL Reismodi",
    searchPlaceholder: "Adres of plaats zoeken",
    trafficLayerUrl: "URL van verkeerlaag"
  })
);