define(
   ({
    _widgetLabel: "보고서 피처",
    select: "선택",
    draw: "그리기",
    chooseALayer: "레이어 선택",
    clickAFeature: "맵의 피처를 클릭하여 선택합니다.",
    loadingFeatures: "선택된 피처 세부정보를 가져오는 중...",
    errorTitle: "오류",
    errorIdentify: "피처 오류를 식별합니다. 자세한 내용은 콘솔 로그를 확인하세요.",
    infoWindowTitle: "세부정보",
    layerLabel: "레이어 이름",
    reviewStatusLabel: "검토 상태",
    selectReviewStatusAdd: "피처 추가",
    selectReviewStatusDelete: "피처 삭제",
    selectReviewStatusMove: "피처 이동",
    selectReviewStatusReshape: "피처 모양 변형",
    drawReviewStatusMissing: "피처 누락",
    drawReviewStatusPosition: "위치 오류",
    drawReviewStatusShape: "모양 오류",
    drawReviewStatusAttribute: "속성 오류",
    notesLabel: "참고",
    severityLabel: "심각도",
    reportedByLabel: "보고자:",
    reportedByDefault: "익명",
    reportButton: "보고서",
    reportMessage: "받은 보고서",
    errorReportMessage: "피처를 보고하는 동안 오류가 발생했습니다.",
    drawErrorInstructions: "포인트, 라인 또는 폴리곤을 선택하고 맵에 오류 지오메트리를 그리세요.",
    errorMapService: "맵 서비스 정보를 가져오는 동안 오류가 발생했습니다.",
    noFeatureSelected : "클릭한 위치에서 피처를 찾을 수 없습니다.",
    selectFeatureMapPoint: "클릭하여 피처 선택",
    drawFeatureMapPoint: "포인트를 추가하려면 클릭",
    popupMessage:"메시지",
    popupError:"오류",
    manyFeaturesSelected: "여러 개의 피처를 찾았습니다. 확대하여 보고할 피처를 선택하세요."
  })
);
