define(
	 ({
		queries: "Tarefas de Consulta",
		addNew: "Adicionar Novo",
    queryLayer: "Camada de Consulta",
		setSource: "Configurar",
		setDataSource: "Configurar Fonte de Dados",
		name: "Nome",
		querySource: "Fonte de Dados",
		queryName: "Nome da Tarefa",
		queryDefinition: "Definição de Filtro",
		resultsSetting: "Configuração dos Resultados",
		symbolSetting: "Configuração do Símbolo",
		resultSettingTip: "Define quais e como exibir os resultados de saída.",
		resultItemTitle: "Título do Item Resultante",
		resultItemContent: "Conteúdos do Item Resultante",
		fieldsSetTip: "Verifique os campos que você deseja exibir. Selecione um campo para atualizar seu nome alternativo, ordem e formato.",
		addField: "Adicionar Campo",
		visibility: "Visibilidade",
		alias: "Nome Alternativo",
		specialType: "Tipo Especial",
		actions: "Ações",
		none: "Nenhum",
		link: "Link",
		image: "Imagem",
		noField: "Nenhum campo",
		operationalLayerTip: "Adicionar resultado como camada operacional",
		setLayerSymbolTip: "Configure o símbolo para resultados da consulta: ",
		setSelectedSymbolTip: "Configurar símbolo da feição selecionada.",
		notUseFilter: "Não utilizar filtro",
		setSourceTip: "Configure a origem da consulta.",
		setFilterTip: "Configure o filtro corretamente.",
		ok: "Ok",
		cancel: "Cancelar",
		noFilterTip: "Sem expressão de filtro definida, esta tarefa de consulta listará todas as feições na fonte de dados especificada.",
    relationships: "Relacionamentos",
    addRelationshipLayer: "Adicionar Novo Relacionamento",
    relatedTo: "Relacionado Para",
    selectOption: "Selecione..",
    resultItemSorting: "Classificação de Item do Resultado",
    field: "Campo",
    sortingOrder: "Ordenar",
    configureFieldsTip: "Configure os campos que o resultado da consulta será classificado.",
    setSortingFields: "Configurar Campos de Classificação",
    ascending: "Crescente",
    descending: "Descendente",
    sortBy: "Classificar por",
    thenBy: "Então por",
    addTask: "Adicionar tarefa",
    noTasksTip: 'Nenhuma tarefa, clique em \"${addTask}\" para iniciar!',
    infoText: "Info",
    filters: "Filtros",
    results: "Resultados",
    optionsText: "Opções",
    summaryText: "Resumo",
    attributeFilter: "Filtro de Atributo",
    attributeFilterTip: "Defina expressões de atributo para utilizar no widget para filtrar a camada de consulta.",
    noExpressionDefinedTip: "Nenhuma expressão foi definida.",
    needInputValuesTip: "Necessário valores de entrada no tempo de execução",
    setExpressions: "Configurar Expressões",
    spatialFilter: "Filtro Espacial",
    spatialFilterTip: "Escolha o filtro espacial utilizado no widget para limitar resultados.",
    defaultOption: "Padrão",
    useCurrentExtentTip: "Parcialmente ou completamente dentro da extensão de mapa atual",
    useDrawGraphicTip: "Parcialmente ou completamente dentro da forma desenhada no mapa",
    useFeaturesTip: "Baseado em suas localizações em relação às feições em outra camada",
    noSpatialLimitTip: "Não limitar espacialmente os resultados",
    drawingTools: "Ferramentas de desenho",
    bufferSettings: "Configurações do Buffer",
    defaultDistance: "Distância Padrão",
    bufferDistance: "Distância do Buffer",
    defaultUnit: "Unidade Padrão",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    availableSpatialRelationships: "Relacionamentos Espaciais Disponíveis",
    setSpatialRelationships: "Configurar Relacionamentos Espaciais",
    availability: "Disponibilidade",
    relationship: "Relacionamento",
    label: "Rótulo",
    intersect: "interseccionar",
    contain: "contém",
    areContainedIn: "estão contidos em",
    cross: "cruz",
    envelopeIntersect: "intersecção de envelope",
    overlap: "sobreposição",
    areOverlapped: "estão sobrepostos",
    touche: "toca",
    within: "dentro",
    areWithin: "estão dentro",
    indexIntersect: "intersecção de índice",
    itemTitle: "Título do Item",
    displayFields: "Campos de Visualização",
    sortingFields: "Campos de Classificação",
    setDisplayFields: "Configurar Campos de Visualização",
    symbol: "Símbolo",
    setSymbol: "Configurar símbolo",
    serviceSymbolTip: "Utilizar símbolos definidos pela camada",
    exportTip: "Mostrar botão Exportar",
    keepResultsTip: "Manter resultados no mapa após o widget ser fechado",
    queryRelatedRecords: "Consultar registros relacionados",
    createLayerForTaskTip: "Especificar como a tarefa cria camadas",
    oneLayerForTaskTip: "Somente criar uma camada desta tarefa",
    multipleLayerForTaskTip: "Criar uma nova camada toda vez que esta tarefa executar"
  })
);
