define(
	 ({
		queries: "Tarefas de Consulta",
		addNew: "Adicionar Novo",
		setSource: "Configurar",
		setDataSource: "Configurar Fonte de Dados",
		name: "Nome",
		querySource: "Fonte de Dados",
		queryName: "Nome da Tarefa",
		queryDefinition: "Definição de Filtro",
		resultsSetting: "Configuração dos Resultados",
		symbolSetting: "Configuração do Símbolo",
		resultSettingTip: "Define quais e como exibir os resultados de saída.",
		resultItemTitle: "Título do Item Resultante",
		resultItemContent: "Conteúdos do Item Resultante",
		fieldsSetTip: "Verifique os campos que você deseja exibir. Selecione um campo para atualizar seu nome alternativo, ordem e formato.",
		addField: "Adicionar Campo",
		visibility: "Visibilidade",
		alias: "Nome Alternativo",
		specialType: "Tipo Especial",
		actions: "Ações",
		none: "Nenhum",
		link: "Link",
		image: "Imagem",
		noField: "Nenhum campo",
		operationalLayerTip: "Adicionar resultado como camada operacional",
		setLayerSymbolTip: "Configure o símbolo para resultados da consulta: ",
		setSelectedSymbolTip: "Configurar símbolo da feição selecionada.",
		notUseFilter: "Não utilizar filtro",
		setSourceTip: "Configure a origem da consulta.",
		setFilterTip: "Configure o filtro corretamente.",
		ok: "Ok",
		cancel: "Cancelar",
		noFilterTip: "Sem expressão de filtro definida, esta tarefa de consulta listará todas as feições na fonte de dados especificada."
  })
);