define(
   ({
    _widgetLabel: "Situation Awareness (เบต้า)",
    locate_incident: "ค้นหาเหตุการณ์",
    clear_incidents: "เหตุการณ์ที่ชัดเจน",
    reverse_geocoded_address: "ที่อยู่ใกล้ที่สุด",
    reverse_geocoded_error: "ไม่สามารถ",
    miles: "ไมล์",
    kilometers: "กิโลเมตร",
    feet: "ฟุต",
    meters: "เมตร",
    yards: "หลา",
    nauticalMiles: "ไมล์ทะเล",
    now: "ขณะนี้",
    wind: "ลม",
    SUN: "อา.",
    MON: "จ.",
    TUE: "อ.",
    WED: "พ.",
    THU: "พฤ.",
    FRI: "ศ.",
    SAT: "ส.",
    defaultTabMsg: "เหตุการณ์ที่เกิดขึ้นไม่มีการระบุ",
    actionLabel: "ตั้งเป็นเหตุการณ์ที่เกิดขึ้น",
    drawPoint: "วาดจุด",
    drawLine: "วาดเส้น",
    drawPolygon: "วาดรูปหลายเหลี่ยม",
    saveIncident: "บันทึกเหตุการณ์",
    clearIncident: "ล้างเหตุการณ์",
    useMapExtent: "ใช้ขอบเขตแผนที่ปัจจุบัน",
    noFeaturesFound: "ไม่พบฟีเจอร์",
    downloadCSV: "ดาวน์โหลด CSV",
    editComplete: "บันทึกคุณลักษณะเรียบร้อยแล้ว!",
    updateComplete: "ปรับปรุงฟีเจอร์เสร็จสมบูรณ์!",
    deleteComplete: "ลบฟีเจอร์เสร็จสมบูรณ์!",
    sum: "รวม",
    min: "น้อยที่สุด",
    max: "ข้อมูลทั้งหมด",
    avg: "เฉลี่ย",
    count: "จำนวน",
    area: "พื้นที่",
    length: "ความยาว",
    notPolySave: "โปรดระบุระยะกันชนก่อนที่จะบันทึก",
    update_btn: "ปรับปรุง",
    delete_btn: "ลบ"
  })
);
