define(
	 ({
		chartTasks: "Tareas de gráficos",
		addNew: "Agregar nueva",
		addNewTip: "Agregar una nueva tarea de gráfico",
		name: "Nombre",
		set: "Establecer",
		setDataSource: "Definir fuente de datos",
		generalSettingsTip: "Define la fuente de datos, el título y la descripción de los gráficos.",
		chartModeSettingTip: "Selecciona una forma de analizar y visualizar los datos como gráficos.",
		detailsSettingTip: "Define el aspecto del gráfico especificando su tipo y su color, así como los valores que se deben representar:",
		symbolSettingTip: "Define la vista del mapa para los datos representados.",
		addFilterTip: "Agregar filtro a estos datos",
		dataSource: "Fuente de datos",
		noResults: "Ninguna entidad encontrada.",
		chartTitle: "Título del gráfico",
		description: "Descripción",
		chartingMode: "Vista del gráfico",
		featureOption: "Mostrar valores entidad por entidad",
		categoryOption: "Mostrar valores por categoría",
		countOption: "Mostrar recuentos de entidades por categoría",
		fieldOption: "Mostrar valores de atributos como gráficos",
		category: "Categoría",
		axisLabel: "Etiqueta de categoría",
		categoryField: "Campo de categoría",
		operation: "Operación",
		originalOption: "Usar valores originales",
		sumOption: "Suma",
		averageOption: "Promedio",
		minOption: "Mínimo",
		maxOption: "Máximo",
		valueFields: "Campos de valores",
		moveUp: "Mover hacia arriba",
		moveDown: "Mover hacia abajo",
		sortOrder: "Ordenar gráficos por medio de etiquetas de categorías",
		ascending: "Ascendente",
		descending: "Descendente",
		chartType: "Tipo de gráfico",
		column: "Gráfico de columnas",
		bar: "Gráfico de barras",
		line: "Gráfico de líneas",
		pie: "Gráfico circular",
		chartColor: "Color del gráfico",
		showDataLabels: "Mostrar etiquetas de datos",
		setSymbol: "Símbolo de selección",
		setHighLightColor: "Color de resaltado",
		settings: "Configuración",
		mapInterationOptions: "Opciones de interacción del mapa",
		preview: "Presentación preliminar",
		ok: "Aceptar",
		cancel: "Cancelar",
		close: "Cerrar",
		setFilterTip: "Define correctamente el filtro. ",
		setChartTitleTip: "Define el título del gráfico.",
		setChartTypeTip: "Selecciona al menos un tipo de gráfico.",
		setDataFieldTip: "Selecciona al menos un campo de valor.",
		setOutputFieldTip: "Define los campos de salida.",
		count: "Recuento",
		label: "Etiqueta",
		horizontalAxis: "Eje horizontal",
		verticalAxis: "Eje vertical",
		dataLabels: "Etiquetas de datos",
		color: "Color",
		colorful: "Multicolor",
		monochromatic: "Monocromático",
    noTaskTip: "Haz clic en Agregar nuevo para agregar una tarea de gráfico",
    info: "Información",
    charts: "Cartas",
    options: "Opciones",
    taskName: "Nombre de tarea",
    summary: "Resumen",
    resultDescription: "Descripción del resultado",
    spatialFilterTip: "Elige los filtros espaciales utilizados en el widget para limitar los resultados.",
    defaultOption: "Predeterminado",
    useCurrentExtentTip: "Parcial o totalmente dentro de la extensión de mapa actual",
    useDrawGraphicTip: "Parcial o totalmente dentro de la forma dibujada en el mapa",
    useFeaturesTip: "En función de sus ubicaciones con respecto a las entidades de otra capa",
    noSpatialLimitTip: "No limitar espacialmente los resultados",
    drawingTools: "Herramientas de dibujo",
    bufferSettings: "Configuración de la zona de influencia",
    defaultDistance: "Distancia predeterminada",
    bufferDistance: "Distancia de zona de influencia",
    defaultUnit: "Unidad predeterminada",
    miles: "Millas",
    kilometers: "Kilómetros",
    feet: "Pies",
    meters: "Metros",
    yards: "Yardas",
    nauticalMiles: "Millas Náuticas",
    availableSpatialRelationships: "Relaciones espaciales disponibles",
    setSpatialRelationships: "Definir relaciones espaciales",
    availability: "Disponibilidad",
    relationship: "Relación",
    actions: "Acciones",
    intersect: "intersecar",
    contain: "contienen",
    areContainedIn: "están contenidas en",
    cross: "cruz",
    envelopeIntersect: "intersección con el contorno",
    overlap: "superponer",
    areOverlapped: "se superponen",
    touche: "se tocan",
    within: "dentro de",
    areWithin: "están dentro de",
    indexIntersect: "con intersección de índice"
  })
);