define(
	 ({
		charts: "Tareas de gráficos",
		addNew: "Agregar nueva",
		addNewTip: "Agregar una nueva tarea de gráfico",
		name: "Nombre",
		set: "Establecer",
		setDataSource: "Definir fuente de datos",
		generalSettingsTip: "Define la fuente de datos, el título y la descripción de los gráficos.",
		chartModeSettingTip: "Selecciona una forma de analizar y visualizar los datos como gráficos.",
		detailsSettingTip: "Define el aspecto del gráfico especificando sus tipos y su color, así como los valores que se deben representar.",
		symbolSettingTip: "Define la vista del mapa para los datos representados.",
		addFilterTip: "Agregar filtro a estos datos",
		dataSource: "Fuente de datos",
		noResults: "Ninguna entidad encontrada.",
		chartTitle: "Título del gráfico",
		description: "Descripción",
		chartingMode: "Vista del gráfico",
		featureOption: "Mostrar valores entidad por entidad",
		categoryOption: "Mostrar valores por categoría",
		countOption: "Mostrar recuentos de entidades por categoría",
		fieldOption: "Mostrar valores de atributos como gráficos",
		category: "Categoría",
		axisLabel: "Etiqueta de categoría",
		categoryField: "Campo de categoría",
		operation: "Operación",
		originalOption: "Usar valores originales",
		sumOption: "Suma",
		averageOption: "Promedio",
		minOption: "Mínimo",
		maxOption: "Máximo",
		valueFields: "Campos de valores",
		moveUp: "Mover hacia arriba",
		moveDown: "Mover hacia abajo",
		sortOrder: "Ordenar gráficos por medio de etiquetas de categorías",
		ascending: "Ascendente",
		descending: "Descendente",
		chartType: "Tipo de gráfico",
		column: "Gráfico de columnas",
		bar: "Gráfico de barras",
		line: "Gráfico de líneas",
		pie: "Gráfico circular",
		chartColor: "Color del gráfico",
		showDataLabels: "Mostrar etiquetas de datos",
		setSymbol: "Símbolo de selección",
		setHighLightColor: "Color de resaltado",
		settings: "Configuración",
		mapInterationOptions: "Opciones de interacción del mapa",
		preview: "Presentación preliminar",
		ok: "Aceptar",
		cancel: "Cancelar",
		close: "Cerrar",
		setFilterTip: "Define correctamente el filtro. ",
		setChartTitleTip: "Define el título del gráfico.",
		setChartTypeTip: "Selecciona al menos un tipo de gráfico.",
		setDataFieldTip: "Selecciona al menos un campo de valor.",
		setOutputFieldTip: "Define los campos de salida.",
		count: "Recuento",
		label: "Etiqueta",
		horizontalAxis: "Eje horizontal",
		verticalAxis: "Eje vertical",
		dataLabels: "Etiquetas de datos",
		color: "Color",
		colorful: "Multicolor",
		monochromatic: "Monocromático"
  })
);