define(
   ({
    _widgetLabel: "사건 분석",
    incident: "사건",
    weather: "날씨",
    locate_incident: "사건 찾기",
    clear_incidents: "사건 지우기",
    reverse_geocoded_address: "가장 가까운 주소",
    reverse_geocoded_error: "사용할 수 없음",
    miles: "마일",
    kilometers: "킬로미터",
    feet: "피트",
    meters: "미터",
    yards: "야드",
    nauticalMiles: "해리",
    now: "지금",
    wind: "풍력",
    SUN: "일",
    MON: "월",
    TUE: "화",
    WED: "수",
    THU: "목",
    FRI: "금",
    SAT: "토",
    defaultTabMsg: "식별된 사건이 없습니다.",
    actionLabel: "사건으로 설정",
    useMapExtent: "현재 맵 범위 사용",
    noFeaturesFound: "피처를 찾을 수 없습니다.",
    downloadCSV: "CSV 다운로드",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "COUNT",
    area: "AREA",
    length: "LENGTH"
  })
);
