define(
   ({
    _widgetLabel: "Detayı Bildir",
    select: "Seç",
    draw: "Çiz",
    chooseALayer: "Katman seçin",
    clickAFeature: "Seçmek için haritada bir detaya tıklayın.",
    loadingFeatures: "Seçilen detay bilgileri alınıyor...",
    errorTitle: "Hata",
    errorIdentify: "Detay hatasını tanımlayın. Ayrıntılar için konsol günlüğünü denetleyin.",
    infoWindowTitle: "Ayrıntılar",
    layerLabel: "Katman Adı",
    reviewStatusLabel: "Durumu İncele",
    selectReviewStatusAdd: "Detay Ekle",
    selectReviewStatusDelete: "Detay Sil",
    selectReviewStatusMove: "Detayı Taşı",
    selectReviewStatusReshape: "Detayı Yeniden Şekillendir",
    drawReviewStatusMissing: "Eksik Detaylar",
    drawReviewStatusPosition: "Konumsal Hatası",
    drawReviewStatusShape: "Şekil Hatası",
    drawReviewStatusAttribute: "Öznitelik Hatası",
    notesLabel: "Notlar",
    severityLabel: "Önem",
    reportedByLabel: "Bildiren",
    reportedByDefault: "anonim",
    reportButton: "Rapor",
    reportMessage: "Bildirim alındı",
    errorReportMessage: "Detayınız bildirilirken bir hata oluştu",
    drawErrorInstructions: "Nokta, çizgi veya alan seçin ve haritada hata geometrisini çizin:",
    errorMapService: "Harita hizmeti bilgileri alınırken bir hata oluştu",
    noFeatureSelected : "Tıklanan konumda detay bulunamadı",
    selectFeatureMapPoint: "Detay seçmek için tıklayın",
    drawFeatureMapPoint: "Nokta eklemek için tıklayın",
    popupMessage:"Mesaj",
    popupError:"Hata",
    manyFeaturesSelected: "Birden çok detay bulundu. Yaklaştırın ve bildirilecek detayı seçin."
  })
);
