define(
   ({
    _widgetLabel: "Raportowanie obiektów",
    select: "Zaznacz",
    draw: "Wyświetl",
    chooseALayer: "Wybierz warstwę",
    clickAFeature: "Kliknij obiekt na mapie, aby go wybrać.",
    loadingFeatures: "Pozyskiwanie wybranych danych szczegółowych obiektu...",
    errorTitle: "Błąd",
    errorIdentify: "Zidentyfikuj błąd obiektu. Aby zdobyć więcej szczegółów, sprawdź dziennik konsoli.",
    infoWindowTitle: "Szczegóły",
    layerLabel: "Nazwa warstwy tematycznej",
    reviewStatusLabel: "Przeglądaj status",
    selectReviewStatusAdd: "Dodaj obiekt",
    selectReviewStatusDelete: "Usuń obiekt",
    selectReviewStatusMove: "Przenieś obiekt",
    selectReviewStatusReshape: "Zmień kształt obiektu",
    drawReviewStatusMissing: "Brakujące obiekty",
    drawReviewStatusPosition: "Błąd pozycji",
    drawReviewStatusShape: "Błąd kształtu",
    drawReviewStatusAttribute: "Błąd atrybutu",
    notesLabel: "Uwagi",
    severityLabel: "Waga",
    reportedByLabel: "Zgłoszony przez",
    reportedByDefault: "anonimowo",
    reportButton: "Raport",
    reportMessage: "Otrzymano raport",
    errorReportMessage: "Wystąpił błąd podczas raportowania obiektu",
    drawErrorInstructions: "Wybierz punkt, linię lub poligon i narysuj na mapie błędną geometrię:",
    errorMapService: "Wystąpił błąd podczas pozyskiwania danych o usłudze mapowej",
    noFeatureSelected : "We wskazanej lokalizacji nie znaleziono obiektów",
    selectFeatureMapPoint: "Kliknij, aby wybrać obiekt",
    drawFeatureMapPoint: "Kliknij, aby dodać punkt",
    popupMessage:"Komunikat",
    popupError:"Błąd",
    manyFeaturesSelected: "Znaleziono więcej niż jeden obiekt. Przybliż widok i wybierz obiekt do raportowania."
  })
);
