define(
   ({
    "tabs_section_Label": "Schede",
    "addTab": "Aggiungi scheda",
    "layerName": "Layer",
    "layerType": "Tipo di analisi",
    "layerLabel": "Etichetta",
    "actions": "Azioni",
    "closest": "Feature più vicina",
    "proximity": "Prossimità",
    "summary": "Riepilogo",
    "select_lbl": "-- Seleziona --",
    "general_setting_Label": "Impostazioni generali",
    "units_text_lbl": "Unità Distanza",
    "miles": "Miglia",
    "kilometers": "Chilometri",
    "feet": "Piede",
    "meters": "Metri",
    "yards": "Iarde",
    "nauticalMiles": "Miglia nautiche",
    "maximum_distance_lbl": "Distanza massima della feature più vicina",
    "buffer_text_lbl": "Etichetta del buffer",
    "buffer_lbl": "Distanza di buffer",
    "buffer_max_lbl": "Distanza massima del buffer",
    "buffer_min_lbl": "Distanza minima del buffer",
    "routing_checkBox": "Abilita itinerario",
    "weather_Label": "Opzioni meteo",
    "weather_checkBox": "Includi informazioni meteo",
    "selectLayers": "Seleziona layer meteo",
    "currentlySelectedLayer": "Layer meteo attualmente selezionati",
    "missingTabLabel": "Manca l\'etichetta ad almeno una scheda",
    "cancel": "Annulla",
    "ok": "OK",
    "missingLayerInWebMap": "Nessun layer operativo trovato.",
    "selectFields": "Seleziona campi",
    "addField": "Aggiungi Campo",
    "sum": "SOMMA",
    "min": "MIN",
    "max": "MAX",
    "avg": "MEDIA",
    "count": "COUNT",
    "area": "AREA",
    "length": "LENGTH",
    "count_checkBox": "Mostra conteggio",
    "area_checkBox": "Mostra area",
    "length_checkBox": "Mostra lunghezza",
    "max_records": "Raggiunto limite massimo"
  })
);
