define(
   ({
    selectAnalysisTools:"Selecciona las herramientas de análisis para usar en el widget.",
    selected: "seleccionado",
    name: "Nombre",
    graphicalDisplay:"Visualización gráfica",
    usage: "Uso",
    settings: "Configuración",
    toolSetting: "Establecer detalles de la herramienta",
    toolLabel: "Nombre para mostrar de la herramienta",
    showHelpTip: "Mostrar vínculos de ayuda en el widget",
    showCurrentMapExtent: "Mostrar la opción para usar la extensión de mapa actual",
    showCredits: "Visualizar la opción <b>Mostrar créditos</b>",
    saveAsFeatureService: "Guardar el resultado en la cuenta del usuario",
    showReadyToUseLayers: "Mostrar las capas listas para usar del living atlas del mundo de ArcGIS Online",
    toolNotAvailable: "Esta herramienta no está disponible porque el mapa no contiene las capas de entidades necesarias.",
    aggregatePoints:"Agregar puntos",
    aggregatePointsUsage:"Agrega puntos en los polígonos donde estén situados los puntos.",
    calculateDensity:"Calcular densidad",
    calculateDensityUsage:"Crea un mapa de densidad a partir de entidades de puntos o líneas propagando cantidades conocidas de algún fenómeno(representadas como atributos de los puntos o líneas) en el mapa.",
    connectOriginsToDestinations: "Conectar orígenes con destinos",
    connectOriginsToDestinationsUsage: "Mide el tiempo o la distancia de viaje entre pares de puntos.",
    createBuffers:"Crear áreas de influencia",
    createBuffersUsage:"Crea áreas de influencia poligonales a partir de entidades de entrada.",
    createDriveTimeAreas:"Crear áreas de tiempo de viaje",
    createDriveTimeAreasUsage:"Crea polígonos de tiempo de viaje (o distancia de viaje) alrededor de los puntos de entrada para los valores de tiempo de viaje especificados.",
    createViewshed:"Crear cuenca visual",
    createViewshedUsage:"Crea áreas que están visibles en función de las ubicaciones que se especifiquen.",
    createWatersheds:"Crear cuencas",
    createWatershedsUsage:"Crea áreas de captación en función de las ubicaciones que especifiques.",
    deriveNewLocations:"Derivar nuevas ubicaciones",
    deriveNewLocationsUsage:"Deriva entidades nuevas a partir de las capas de entrada que cumplan una consulta que especifiques",
    dissolveBoundaries:"Disolver límites",
    dissolveBoundariesUsage:"Disuelve los polígonos que se superpongan o compartan un límite.",
    enrichLayer:"Enriquecer capa",
    enrichLayerUsage:"Enriquece las entidades de entrada con datos de personas, lugares y empresas de las áreas cercanas.",
    extractData:"Extraer datos",
    extractDataDesc:"Extrae datos de una o varias capas dentro de una extensión dada",
    findExistingLocations:"Buscar ubicaciones existentes",
    findExistingLocationsUsage:"Selecciona entidades en la capa de entrada que cumplan una consulta de atributo y/o espacial que especifiques",
    findHotSpots:"Buscar puntos calientes",
    findHotSpotsUsage:"Busca clústeres estadísticamente significativos de entidades de entrada o valores altos/bajos.",
    findNearest:"Buscar más cercano",
    findNearestUsage:"Para cada entidad de una capa de entrada, busca su entidad más próxima en otra capa",
    findSimilarLocations:"Buscar ubicaciones similares",
    findSimilarLocationsUsage:"Mide la similitud de las ubicaciones candidatas con respecto a una o varias ubicaciones de referencia.",
    interpolatePoints:"Interpolar puntos",
    interpolatePointsUsage:"Predice los valores en ubicaciones nuevas en función de las mediciones de un conjunto de puntos.",
    mergeLayers:"Fusionar capas",
    mergeLayersUsage:"Fusiona varias capas en una sola",
    overlayLayers:"Superponer capas",
    overlayLayersUsage:"Combina varias capas en una sola capa conservando la información de las capas originales.",
    planRoutes:"Planear rutas",
    planRoutesUsage:"Determina cómo dividir tareas con eficiencia entre un equipo de trabajo móvil.",
    summarizeNearby:"Resumir cercano",
    summarizeNearbyUsage:"Para cada entidad de una capa de entrada, resume los datos dentro de una distancia desde las entidades de otra capa.",
    summarizeWithin:"Resumir dentro",
    summarizeWithinUsage:"Para cada polígono de una capa de polígonos de entrada, resume los datos ubicados dentro del mismo a partir de las entidades de otra capa.",
    traceDownstream:"Trazado aguas abajo",
    traceDownstreamUsage:"Determina los recorridos del flujo aguas abajo desde las ubicaciones que especifiques."
  })
);
