define(
   ({
    selectAnalysisTools:"Selecciona las herramientas de análisis para incluir en el widget.",
    selected: "seleccionado",
    name: "Nombre",
    graphicalDisplay:"Visualización gráfica",
    usage: "Uso",
    toolNotAvailable: "Esta herramienta no está disponible porque el mapa no contiene las capas de entidades necesarias.",
    aggregatePoints:"Agregar puntos",
    aggregatePointsUsage:"Agrega puntos en los polígonos donde estén situados los puntos.",
    aggregatePointsInputTip: "Especifica la capa de entidades de puntos que se agregará a los polígonos en la capa de entidades de polígono.",
    calculateDensity:"Calcular densidad",
    calculateDensityUsage:"Crea un mapa de densidad a partir de entidades de puntos o líneas propagando cantidades conocidas de algún fenómeno(representadas como atributos de los puntos o líneas) en el mapa.",
    calculateDensityInputTip:"Especifica las entidades de puntos o líneas a partir de las cuales se debe calcular la densidad.",
    connectOriginsToDestinations: "Conectar orígenes con destinos",
    connectOriginsToDestinationsUsage: "Mide el tiempo o la distancia de viaje entre pares de puntos.",
    connectOriginsToDestinationsInputTip: "Especifica los puntos de partida de las rutas que se van a generar.",
    createBuffers:"Crear áreas de influencia",
    createBuffersUsage:"Crea áreas de influencia poligonales a partir de entidades de entrada.",
    createBuffersInputTip:"Especifica la capa de entidad de puntos, líneas o polígonos que se debe incluir en el área.",
    createDriveTimeAreas:"Crear áreas de tiempo de viaje",
    createDriveTimeAreasUsage:"Crea polígonos de tiempo de viaje (o distancia de viaje) alrededor de los puntos de entrada para los valores de tiempo de viaje especificados.",
    createDriveTimeAreasInputTip:"Especifica los puntos en los cuales se dibujarán las áreas de tiempo de viaje.",
    createViewshed:"Crear cuenca visual",
    createViewshedUsage:"Crea áreas que están visibles en función de las ubicaciones que se especifiquen.",
    createViewshedInputTip:"Especifica las ubicaciones de observador para identificar áreas visibles.",
    createWatersheds:"Crear cuencas",
    createWatershedsUsage:"Crea áreas de captación en función de las ubicaciones que especifiques.",
    createWatershedsInputTip:"Especifica las entidades de puntos utilizadas para calcular las cuencas.",
    deriveNewLocations:"Derivar nuevas ubicaciones",
    deriveNewLocationsUsage:"Deriva entidades nuevas a partir de las capas de entrada que cumplan una consulta que especifiques",
    deriveNewLocationsInputTip:"Especifica la capa de análisis para usar como entrada.",
    dissolveBoundaries:"Disolver límites",
    dissolveBoundariesUsage:"Disuelve los polígonos que se superpongan o compartan un límite.",
    dissolveBoundariesInputTip:"Especifica la capa que contenga las entidades de polígonos que se van a disolver.",
    enrichLayer:"Enriquecer capa",
    enrichLayerUsage:"Enriquece las entidades de entrada con datos de personas, lugares y empresas de las áreas cercanas.",
    enrichLayerInputTip:"Especifica las entidades para enriquecer con datos nuevos.",
    extractData:"Extraer datos",
    extractDataDesc:"Extrae datos de una o varias capas dentro de una extensión dada",
    extractDataInputTip:"Especifica la capa de entidades de entrada para extraer.",
    findExistingLocations:"Buscar ubicaciones existentes",
    findExistingLocationsUsage:"Selecciona entidades en la capa de entrada que cumplan una consulta de atributo y/o espacial que especifiques",
    findExistingLocationsInputTip:"Especifica las capas de análisis para usar como entrada.",
    findHotSpots:"Buscar puntos calientes",
    findHotSpotsUsage:"Busca clústeres estadísticamente significativos de entidades de entrada o valores altos/bajos.",
    findHotSpotsInputTip:"Especifica la capa de entidades de puntos o polígonos cuyos puntos calientes se van a calcular.",
    findNearest:"Buscar más cercano",
    findNearestUsage:"Para cada entidad de una capa de entrada, busca su entidad más próxima en otra capa",
    findNearestInputTip:"Especifica las entidades de puntos, líneas o polígonos con respecto a las cuales se encuentran las ubicaciones más próximas.",
    findSimilarLocations:"Buscar ubicaciones similares",
    findSimilarLocationsUsage:"Mide la similitud de las ubicaciones candidatas con respecto a una o varias ubicaciones de referencia.",
    findSimilarLocationsInputTip:"Especifica una capa de entidades que contenga una o varias ubicaciones de referencia para evaluar la similitud de las entidades de la capa de búsqueda.",
    interpolatePoints:"Interpolar puntos",
    interpolatePointsUsage:"Predice los valores en ubicaciones nuevas en función de las mediciones de un conjunto de puntos.",
    interpolatePointsInputTip:"Especifica las entidades de puntos que se van a interpolar.",
    mergeLayers:"Fusionar capas",
    mergeLayersUsage:"Fusiona varias capas en una sola",
    mergeLayersInputTip:"Especifica la capa de entidades que se va a fusionar con la capa de fusión.",
    overlayLayers:"Superponer capas",
    overlayLayersUsage:"Combina varias capas en una sola capa conservando la información de las capas originales.",
    overlayLayersInputTip:"Especifica la capa de entidades que se superpondrá a la capa de superposición.",
    planRoutes:"Planear rutas",
    planRoutesUsage:"Determina cómo dividir tareas con eficiencia entre un equipo de trabajo móvil.",
    planRoutesInputTip:"Especifica los puntos por los que deben pasar los vehículos, conductores o rutas.",
    summarizeNearby:"Resumir cercano",
    summarizeNearbyUsage:"Para cada entidad de una capa de entrada, resume los datos dentro de una distancia desde las entidades de otra capa.",
    summarizeNearbyInputTip:"Especifica la capa de entidades de puntos, líneas o polígonos desde la cual se medirán las distancias a las entidades de la capa de resumen.",
    summarizeWithin:"Resumir dentro",
    summarizeWithinUsage:"Para cada polígono de una capa de polígonos de entrada, resume los datos ubicados dentro del mismo a partir de las entidades de otra capa.",
    summarizeWithinInputTip:"Especifica la capa de entidades de polígono sobre la que se va a resumir.",
    traceDownstream:"Trazado aguas abajo",
    traceDownstreamUsage:"Determina los recorridos del flujo aguas abajo desde las ubicaciones que especifiques.",
    traceDownstreamInputTip:"Especifica las entidades de puntos usadas para la ubicación de partida de un trazado aguas abajo."
  })
);
