define(
   ({
    _widgetLabel: "Rapportér objekt",
    select: "Vælg",
    draw: "Tegn",
    chooseALayer: "Vælg et lag",
    clickAFeature: "Klik på et objekt på kortet for at vælge det.",
    loadingFeatures: "Henter udvalgte objektoplysninger...",
    errorTitle: "Error",
    errorIdentify: "Fejl ved identifikation af objekter. Kontrollér konsol-log for oplysninger.",
    infoWindowTitle: "Oplysninger",
    layerLabel: "Navn på lag",
    reviewStatusLabel: "Gennemsynsstatus",
    selectReviewStatusAdd: "Tilføj objekt",
    selectReviewStatusDelete: "Slet objekt",
    selectReviewStatusMove: "Flyt objekt",
    selectReviewStatusReshape: "Omform objekt",
    drawReviewStatusMissing: "Manglende objekt(er)",
    drawReviewStatusPosition: "Positionsfejl",
    drawReviewStatusShape: "Formfejl",
    drawReviewStatusAttribute: "Attributfejl",
    notesLabel: "Notater",
    severityLabel: "Alvorlighed",
    reportedByLabel: "Rapporteret af",
    reportedByDefault: "anonym",
    reportButton: "Rapport",
    reportMessage: "Rapport modtaget",
    errorReportMessage: "Der opstod en fejl under rapportering af dit objekt",
    drawErrorInstructions: "Vælg punkt, linje eller polygon, og tegn geometrifejlen på kortet:",
    errorMapService: "Der opstod en fejl ved hentning af oplysninger om korttjenesten",
    noFeatureSelected : "Der blev ikke fundet nogen objekter på den position, der blev klikket på",
    selectFeatureMapPoint: "Klik for at vælge et objekt",
    drawFeatureMapPoint: "Klik for at tilføje et punkt",
    popupMessage:"Meddelelse",
    popupError:"Error",
    manyFeaturesSelected: "Der blev fundet mere end ét objekt. Zoom ind, og vælg et objekt, der skal rapporteres."
  })
);
