define(
   ({
    _widgetLabel: "Situācijas apzināšana (Beta)",
    locate_incident: "Atrast gadījumu",
    clear_incidents: "Notīrīt gadījumus",
    reverse_geocoded_address: "Tuvākā adrese",
    reverse_geocoded_error: "Nav pieejami",
    miles: "Jūdzes",
    kilometers: "Kilometri",
    feet: "Pēdas",
    meters: "Metri",
    yards: "Jardi",
    nauticalMiles: "Jūras jūdzes",
    now: "TŪLĪT",
    wind: "VĒJŠ",
    SUN: "SVĒTD.",
    MON: "PIRMD.",
    TUE: "OTRD.",
    WED: "TREŠD.",
    THU: "CETURTD.",
    FRI: "PIEKTD.",
    SAT: "SESTD.",
    defaultTabMsg: "Nav noteikts neviens gadījums.",
    actionLabel: "Iestatīt kā gadījumu",
    drawPoint: "Zīmēt punktu",
    drawLine: "Zīmēt līniju",
    drawPolygon: "Zīmēt daudzstūri",
    saveIncident: "Saglabāt gadījumu",
    clearIncident: "Notīrīt gadījumu",
    useMapExtent: "Lietot pašreizējo kartes apmēru",
    noFeaturesFound: "Nav atrasts neviens elements.",
    downloadCSV: "LEJUPIELĀDĒT CSV",
    editComplete: "Elements sekmīgi saglabāts.",
    updateComplete: "Elements sekmīgi atjaunināts.",
    deleteComplete: "Elements sekmīgi izdzēsts.",
    sum: "SUM",
    min: "MIN",
    max: "MAKS.",
    avg: "VID",
    count: "SKAITĪT",
    area: "APGABALS",
    length: "GARUMS",
    notPolySave: "Lūdzu, pirms saglabāšanas norādiet bufera attālumu.",
    update_btn: "Atjaunināt",
    delete_btn: "Dzēst"
  })
);
