define(
   ({
    _widgetLabel: "事件点分析",
    incident: "事件",
    weather: "天气",
    locate_incident: "查找事件点",
    clear_incidents: "清除事件点",
    reverse_geocoded_address: "最近的地址",
    reverse_geocoded_error: "不可用",
    miles: "英里",
    kilometers: "千米",
    feet: "英尺",
    meters: "米",
    yards: "码",
    nauticalMiles: "海里",
    now: "当前",
    wind: "风力",
    SUN: "星期日",
    MON: "星期一",
    TUE: "星期二",
    WED: "星期三",
    THU: "星期四",
    FRI: "星期五",
    SAT: "星期六",
    defaultTabMsg: "未识别任何事件点。",
    actionLabel: "设为事件点",
    useMapExtent: "使用当前地图范围",
    noFeaturesFound: "未找到任何要素。",
    downloadCSV: "下载 CSV",
    sum: "总和",
    min: "最小值",
    max: "最大值",
    avg: "平均值",
    count: "计数",
    area: "面积",
    length: "长度"
  })
);
