define(
   ({
    selectAnalysisTools:"ウィジェットで使用する解析ツールを選択してください。",
    selected: "選択済み",
    name: "名前",
    graphicalDisplay:"グラフィカル表示",
    usage: "使用法",
    settings: "設定",
    toolSetting: "ツールの詳細の設定",
    toolLabel: "ツールの表示名",
    showHelpTip: "ウィジェットにヘルプ リンクを表示",
    showCurrentMapExtent: "現在のマップ範囲を使用するオプションを表示",
    showCredits: "<b>クレジットの表示</b> オプションの表示",
    saveAsFeatureService: "結果をユーザーのアカウントに保存",
    showReadyToUseLayers: "ArcGIS Online のワールド リビング アトラスからすぐに使用できるレイヤーを表示",
    toolNotAvailable: "このツールは、必須のフィーチャ レイヤーがマップに含まれていないため利用できません。",
    aggregatePoints:"ポイントの集約",
    aggregatePointsUsage:"ポイントが配置されるポリゴンにポイントを集約します。",
    calculateDensity:"密度の計算",
    calculateDensityUsage:"ある現象の既知の数量 (ポイントまたはラインの属性として表す) をマップ上に分布することによって、ポイント フィーチャまたはライン フィーチャから密度マップを作成します。",
    connectOriginsToDestinations: "起点から終点の計測",
    connectOriginsToDestinationsUsage: "2 つのポイント間の移動時間または移動距離を計測します。",
    createBuffers:"バッファーの作成",
    createBuffersUsage:"入力フィーチャからバッファー ポリゴンを作成します。",
    createDriveTimeAreas:"到達圏レイヤーの作成",
    createDriveTimeAreasUsage:"指定した到達圏の値に関して、入力ポイントの周囲に到達圏 (または走行距離) ポリゴンを作成します。",
    createViewshed:"可視領域の作成",
    createViewshedUsage:"指定した位置に基づき、表示されるエリアを作成します。",
    createWatersheds:"集水域の作成",
    createWatershedsUsage:"指定した位置に基づき、集水域を作成します。",
    deriveNewLocations:"新規フィーチャの作成",
    deriveNewLocationsUsage:"指定したクエリに一致する入力レイヤーから新規のフィーチャを作成します。",
    dissolveBoundaries:"境界のディゾルブ",
    dissolveBoundariesUsage:"重なり合うエリアや共有の境界を共有するポリゴンをディゾルブします。",
    enrichLayer:"レイヤーへの情報付加",
    enrichLayerUsage:"近傍エリア周囲における人々、場所、およびビジネスに関する情報を入力フィーチャに付加します。",
    extractData:"データの抽出",
    extractDataDesc:"指定の範囲内にある 1 つ以上のレイヤーからデータを抽出します。",
    findExistingLocations:"既存フィーチャの検索",
    findExistingLocationsUsage:"指定した属性検索/空間検索に一致するフィーチャを入力レイヤー内で選択します。",
    findHotSpots:"ホット スポット分析",
    findHotSpotsUsage:"入力フィーチャの中で統計的に有意なクラスター、つまり、高い値/低い値を見つけます。",
    findNearest:"最寄りの検索",
    findNearestUsage:"入力レイヤーにある各フィーチャについて、別のレイヤーにあるその最近接フィーチャを見つけます。",
    findSimilarLocations:"類似フィーチャの検索",
    findSimilarLocationsUsage:"1 つまたは複数の参照場所と候補地との類似性を計測します。",
    interpolatePoints:"ポイントの内挿",
    interpolatePointsUsage:"一連のポイントからの計測値に基づいて、新しい場所の値を推定します。",
    mergeLayers:"レイヤーのマージ",
    mergeLayersUsage:"複数のレイヤーのフィーチャを 1 つの新しいレイヤーにマージします。",
    overlayLayers:"オーバーレイ",
    overlayLayersUsage:"維持される元のレイヤーからの情報を使用して、複数のレイヤーを 1 つのレイヤーに結合します。",
    planRoutes:"ルートの計画",
    planRoutesUsage:"移動を伴う人員のタスクを効率的に分配する方法を決定します。",
    summarizeNearby:"近接範囲内での集計",
    summarizeNearbyUsage:"入力レイヤーにある各フィーチャについて、別のレイヤーにあるフィーチャからの距離内のデータを集計します。",
    summarizeWithin:"エリア内での集計",
    summarizeWithinUsage:"入力ポリゴン レイヤーにある各ポリゴンについて、ポリゴン内にあるデータを別のレイヤーにあるフィーチャから集計します。",
    traceDownstream:"下流解析",
    traceDownstreamUsage:"指定した場所から下流方向へ向かうフロー パスを決定します。"
  })
);
