define(
   ({
    selectAnalysisTools:"ウィジェットに表示されている解析ツールを選択してください。",
    selected: "選択済み",
    name: "名前",
    graphicalDisplay:"グラフィカル表示",
    usage: "使用法",
    toolNotAvailable: "このツールは、必須のフィーチャ レイヤーがマップに含まれていないため利用できません。",
    aggregatePoints:"ポイントの集約",
    aggregatePointsUsage:"ポイントが配置されるポリゴンにポイントを集約します。",
    aggregatePointsInputTip: "ポリゴン フィーチャ レイヤー内のポリゴンへと集約されるポイント フィーチャ レイヤーを指定してください。",
    calculateDensity:"密度の計算",
    calculateDensityUsage:"ある現象の既知の数量 (ポイントまたはラインの属性として表す) をマップ上に分布することによって、ポイント フィーチャまたはライン フィーチャから密度マップを作成します。",
    calculateDensityInputTip:"密度の計算に使用するポイント フィーチャまたはライン フィーチャを指定してください。",
    connectOriginsToDestinations: "起点から終点の計測",
    connectOriginsToDestinationsUsage: "2 つのポイント間の移動時間または移動距離を計測します。",
    connectOriginsToDestinationsInputTip: "生成されるルートの開始点を 1 つまたは複数指定してください。",
    createBuffers:"バッファーの作成",
    createBuffersUsage:"入力フィーチャからバッファー ポリゴンを作成します。",
    createBuffersInputTip:"バッファーを作成するポイント、ライン、またはポリゴン フィーチャを指定してください。",
    createDriveTimeAreas:"到達圏レイヤーの作成",
    createDriveTimeAreasUsage:"指定した到達圏の値に関して、入力ポイントの周囲に到達圏 (または走行距離) ポリゴンを作成します。",
    createDriveTimeAreasInputTip:"到達圏レイヤーが描画されるポイントを指定してください。",
    createViewshed:"可視領域の作成",
    createViewshedUsage:"指定した位置に基づき、表示されるエリアを作成します。",
    createViewshedInputTip:"表示エリアを識別する観測点を指定してください。",
    createWatersheds:"集水域の作成",
    createWatershedsUsage:"指定した位置に基づき、集水域を作成します。",
    createWatershedsInputTip:"集水域の計算に使用されるポイント フィーチャを指定してください。",
    deriveNewLocations:"新規フィーチャの作成",
    deriveNewLocationsUsage:"指定したクエリに一致する入力レイヤーから新規のフィーチャを作成します。",
    deriveNewLocationsInputTip:"入力として使用する解析レイヤーを指定してください。",
    dissolveBoundaries:"境界のディゾルブ",
    dissolveBoundariesUsage:"重なり合うエリアや共有の境界を共有するポリゴンをディゾルブします。",
    dissolveBoundariesInputTip:"ディゾルブされるポリゴン フィーチャを含むレイヤーを指定してください。",
    enrichLayer:"レイヤーへの情報付加",
    enrichLayerUsage:"近傍エリア周囲における人々、場所、およびビジネスに関する情報を入力フィーチャに付加します。",
    enrichLayerInputTip:"新しいデータを付加するフィーチャを指定してください。",
    extractData:"データの抽出",
    extractDataDesc:"指定の範囲内にある 1 つ以上のレイヤーからデータを抽出します。",
    extractDataInputTip:"抽出元の入力フィーチャ レイヤーを指定してください。",
    findExistingLocations:"既存フィーチャの検索",
    findExistingLocationsUsage:"指定した属性検索/空間検索に一致するフィーチャを入力レイヤー内で選択します。",
    findExistingLocationsInputTip:"入力として使用する解析レイヤーを指定してください。",
    findHotSpots:"ホット スポット分析",
    findHotSpotsUsage:"入力フィーチャの中で統計的に有意なクラスター、つまり、高い値/低い値を見つけます。",
    findHotSpotsInputTip:"ホット スポットを計算するポイントまたはポリゴン フィーチャ レイヤーを指定してください。",
    findNearest:"最寄りの検索",
    findNearestUsage:"入力レイヤーにある各フィーチャについて、別のレイヤーにあるその最近接フィーチャを見つけます。",
    findNearestInputTip:"最近接位置を検出するポイント、ライン、またはポリゴン フィーチャを指定してください。",
    findSimilarLocations:"類似フィーチャの検索",
    findSimilarLocationsUsage:"1 つまたは複数の参照場所と候補地との類似性を計測します。",
    findSimilarLocationsInputTip:"検索レイヤー内のフィーチャの類似性を評価する際の基準となる 1 つまたは複数の参照場所を含むフィーチャ レイヤーを指定してください。",
    interpolatePoints:"ポイントの内挿",
    interpolatePointsUsage:"一連のポイントからの計測値に基づいて、新しい場所の値を推定します。",
    interpolatePointsInputTip:"内挿されるポイント フィーチャを指定してください。",
    mergeLayers:"レイヤーのマージ",
    mergeLayersUsage:"複数のレイヤーのフィーチャを 1 つの新しいレイヤーにマージします。",
    mergeLayersInputTip:"[レイヤーのマージ] でマージされるフィーチャ レイヤーを指定してください。",
    overlayLayers:"オーバーレイ",
    overlayLayersUsage:"維持される元のレイヤーからの情報を使用して、複数のレイヤーを 1 つのレイヤーに結合します。",
    overlayLayersInputTip:"[オーバーレイ] でオーバーレイされるフィーチャ レイヤーを指定してください。",
    planRoutes:"ルートの計画",
    planRoutesUsage:"移動を伴う人員のタスクを効率的に分配する方法を決定します。",
    planRoutesInputTip:"車両、運転手、またはルートについて訪問先となるポイントを指定してください。",
    summarizeNearby:"近接範囲内での集計",
    summarizeNearbyUsage:"入力レイヤーにある各フィーチャについて、別のレイヤーにあるフィーチャからの距離内のデータを集計します。",
    summarizeNearbyInputTip:"[レイヤーの集計] でフィーチャまでの距離を計測する際の始点となるポイント、ライン、またはポリゴン フィーチャ レイヤーを指定してください。",
    summarizeWithin:"エリア内での集計",
    summarizeWithinUsage:"入力ポリゴン レイヤーにある各ポリゴンについて、ポリゴン内にあるデータを別のレイヤーにあるフィーチャから集計します。",
    summarizeWithinInputTip:"集計の対象となるポリゴン フィーチャ レイヤーを指定してください。",
    traceDownstream:"下流解析",
    traceDownstreamUsage:"指定した場所から下流方向へ向かうフロー パスを決定します。",
    traceDownstreamInputTip:"下流解析の開始場所に使用されるポイント フィーチャを指定してください。"
  })
);
