define({
    showArcgisBasemaps: "Portaal-basiskaarten opnemen",
    settings: "Instellingen",
    add: "Klik om een nieuwe basiskaart toe te voegen",
    edit: "Eigenschappen",
    title: "Titel",
    titlePH: "Titel van basiskaart",
    thumbnail: "Thumbnail",
    thumbnailHint: "Klik op de afbeelding om bij te werken",
    url: "URL",
    urlPH: "Laag-URL",
    addlayer: "Basiskaart toevoegen",
    actions: "Handelingen",
    warning: "Onjuiste invoer",
    save: "Terug en opslaan",
    back: "Terug en annuleren",
    addUrl: "URL toevoegen",
    autoCheck: "Automatisch controleren",
    checking: "Controleren...",
    ok: "OK",
    cancel: "Annuleren",
    result: "Opslaan is gelukt",
    spError: "Alle basiskaarten die aan de galerij zijn toegevoegd, vereisen dezelfde ruimtelijke referenties.",
    invalidTitle1:"Een basiskaart '",
    invalidTitle2:"' bestaat al. Kies een andere titel.",
    invalidBasemapUrl1: "Dit laagtype kan niet worden gebruikt als een basiskaart.",
    invalidBasemapUrl2: "Verschillende ruimtelijke referentie met huidige kaart.",
    addBaselayer: "Basiskaartlaag toevoegen"

});