define(
   ({
    _widgetLabel: "معلم التقرير",
    select: "تحديد",
    draw: "رسم",
    chooseALayer: "حدد الطبقة",
    clickAFeature: "انقر على معلم على الخريطة لتحديده.",
    loadingFeatures: "جارِ الحصول على تفاصيل المعالم المحددة...",
    errorTitle: "خطأ",
    errorIdentify: "تعريف خطأ المعالم. يرجى مراجعة سجل وحدة التحكم للحصول على التفاصيل.",
    infoWindowTitle: "التفاصيل",
    layerLabel: "اسم الطبقة",
    reviewStatusLabel: "مراجعة الحالة",
    selectReviewStatusAdd: "إضافة معلم",
    selectReviewStatusDelete: "حذف معلم",
    selectReviewStatusMove: "نقل المعلم",
    selectReviewStatusReshape: "تعديل شكل المعلم",
    drawReviewStatusMissing: "معالم مفقودة",
    drawReviewStatusPosition: "خطأ موضعي",
    drawReviewStatusShape: "خط في الشكل",
    drawReviewStatusAttribute: "خطأ في جدول البيانات",
    notesLabel: "ملاحظات",
    severityLabel: "مستوى الخطأ",
    reportedByLabel: "تم الإبلاغ بواسطة",
    reportedByDefault: "مجهول",
    reportButton: "تقرير",
    reportMessage: "تم استلام التقرير",
    errorReportMessage: "حدث خطأ في الإبلاغ عن المعلم",
    drawErrorInstructions: "تحديد نقطة أو خط أو مضلع ورسم الشكل الهندسي للخطأ على الخريطة:",
    errorMapService: "حدث خطأ في الحصول على معلومات خدمة الخريطة",
    noFeatureSelected : "لم يتم العثور على أي معالم في الموقع الذي تم النقر عليه",
    selectFeatureMapPoint: "انقر لتحديد المعلم",
    drawFeatureMapPoint: "انقر لإضافة نقطة.",
    popupMessage:"رسالة",
    popupError:"خطأ",
    manyFeaturesSelected: "تم العثور على أكثر من معلم واحد. يرجى التكبير وتحديد المعلم للإبلاغ عنه."
  })
);
