define(
   ({
    _widgetLabel: "Tapahtuma-analyysi",
    incident: "Tapahtuma",
    weather: "Sää",
    locate_incident: "Paikanna tapahtuma",
    clear_incidents: "Tyhjennä tapahtumat",
    reverse_geocoded_address: "Lähin osoite",
    reverse_geocoded_error: "Ei käytettävissä",
    miles: "Mailia",
    kilometers: "Kilometriä",
    feet: "Jalka",
    meters: "Metriä",
    yards: "Jaardia",
    nauticalMiles: "Meripeninkulmaa",
    now: "NYT",
    wind: "TUULI",
    SUN: "SU",
    MON: "MA",
    TUE: "TI",
    WED: "KE",
    THU: "TO",
    FRI: "PE",
    SAT: "LA",
    defaultTabMsg: "Yhtään tapahtumaa ei ole tunnistettu.",
    actionLabel: "Määritä tapahtumaksi",
    useMapExtent: "Käytä nykyistä kartan laajuutta",
    noFeaturesFound: "Kohteita ei löytynyt.",
    downloadCSV: "LATAA CSV-TIEDOSTO",
    sum: "SUMMA",
    min: "VÄHINT.",
    max: "ENINT.",
    avg: "KESKIARVO",
    count: "MÄÄRÄ",
    area: "ALUE",
    length: "PITUUS"
  })
);
