define(
   ({
    _widgetLabel: "查詢",
    executeQueryTip: "按一下以下其中一個任務項目執行查詢。",
    invalidConfig: "配置無效。請使用\“查詢\”設定頁面取得正確配置。",
    queryParams: "選項",
    parameters: "選項",
    queries: "查詢",
    apply: "套用",
    queryResults: "結果",
    clear: "清除",
    noResults: "未找到任何圖徵。",
    queryError: "查詢失敗！",
    numberFound: "找到的圖徵數",
    mapExtentTip: "將結果限制為目前地圖區域。",
    noValue: "沒有值",
    and: "and",
    stringOperatorIs: "等於", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "不等於",
    stringOperatorStartsWith: "開頭是",
    stringOperatorEndsWith: "結尾是",
    stringOperatorContains: "包含",
    stringOperatorDoesNotContain: "不包含",
    stringOperatorIsBlank: "為空",
    stringOperatorIsNotBlank: "不為空",
    dateOperatorIsOn: "在", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "不在",
    dateOperatorIsBefore: "早於",
    dateOperatorIsAfter: "晚於",
    dateOperatorDays: "天",
    dateOperatorWeeks: "週", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "月",
    dateOperatorInTheLast: "最後",
    dateOperatorNotInTheLast: "不是最後",
    dateOperatorIsBetween: "介於",
    dateOperatorIsNotBetween: "不介於",
    dateOperatorIsBlank: "為空",
    dateOperatorIsNotBlank: "不為空",
    numberOperatorIs: "等於", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "不等於",
    numberOperatorIsAtLeast: "最小為",
    numberOperatorIsLessThan: "小於",
    numberOperatorIsAtMost: "最大為",
    numberOperatorIsGreaterThan: "大於",
    numberOperatorIsBetween: "介於",
    numberOperatorIsNotBetween: "不介於",
    numberOperatorIsBlank: "為空",
    numberOperatorIsNotBlank: "不為空",
    operationalLayerTip: "將結果新增為操作圖層",
    queryResult: "查詢結果",
    specifyParamsTip: "為此任務指定參數",
    useSpatialFilter: "使用空間篩選器限制圖徵",
    useCurrentMapExtent: "僅與目前地圖區域相交的圖徵",
    drawGraphicOnMap: "僅與使用者自訂區域相交的圖徵",
    specifySpatialFilterMsg: "請為此任務指定空間篩選器。",
    clearResults: "清除結果",
    operationalTip: '勾選此選項後，結果將始終保留在地圖上，直至按一下 \"${clearResults}\" 按鈕。',
    noneQueryTip: "未針對此 widget 配置查詢任務。",
    noPermissionsMsg: "您沒有存取此服務的權限。",
    attributesFromRelationship: "相關表格中的屬性",
    tasks: "任務",
    applySpatialFilterToLimitResults: "套用空間篩選器以限制結果",
    useCurrentExtentTip: "部分或全部位於目前的地圖範圍內",
    useDrawGraphicTip: "部分或全部位於地圖上繪製的形狀內",
    useFeaturesTip: "根據其與另一個圖層中圖徵的相對位置",
    noSpatialLimitTip: "不限制空間結果",
    applySearchDistance: "套用搜尋距離",
    spatialRelationship: "空間關係",
    relatedLayer: "相關圖層",
    bufferDistance: "緩衝距離",
    miles: "英里",
    kilometers: "公里",
    feet: "英呎",
    meters: "公尺",
    yards: "碼",
    nauticalMiles: "海浬",
    back: "返回",
    execute: "執行"
  })
);