define(
   ({
    layerSelect: "Den Image-Layer auswählen",
    displayMeasureResultInPopup: "Messergebnisse in einem Pop-up anzeigen",
    angularUnitSelect: "Standardwinkeleinheit",
    linearUnitSelect: "Lineare Standardeinheit",
    areaUnitSelect: "Standardflächeneinheit",
    displayOperationSelect: "Messvorgänge auswählen",
    errorSectionMeasage: "Keiner der Layer unterstützt Messfunktionen.",
    unitLabel: {
      esriInches: "Zoll",
      esriFeet: "Fuß",
      esriYards: "Yard",
      esriMiles: "Meilen",
      esriNauticalMiles: "Seemeilen",
      esriMillimeters: "Millimeter",
      esriCentimeters: "Zentimeter",
      esriDecimeters: "Dezimeter",
      esriMeters: "Meter",
      esriKilometers: "Kilometer",
      esriDURadians: "Bogenmaß",
      esriDUDecimalDegrees: "Grad",
      esriSquareInches: "Quadratinch",
      esriSquareFeet: "Quadratfuß",
      esriSquareYards: "Quadratyards",
      esriAcres: "Acres",
      esriSquareMiles: "Quadratmeilen",
      esriSquareMillimeters: "Quadratmillimeter",
      esriSquareCentimeters: "Quadratzentimeter",
      esriSquareDecimeters: "Quadratdezimeter",
      esriSquareMeters: "Quadratmeter",
      esriAres: "Ar",
      esriHectares: "Hektar",
      esriSquareKilometers: "Quadratkilometer"
    },
    operationLabel: {
      esriMensurationPoint: "Punkt",
      esriMensurationDistanceAndAngle: "Entfernung und Winkel",
      esriMensurationAreaAndPerimeter: "Fläche und Umfang",
      esriMensurationHeightFromBaseAndTop: "Basis bis Spitze",
      esriMensurationHeightFromBaseAndTopShadow: "Basis zur Schattenspitze",
      esriMensurationHeightFromTopAndTopShadow: "Spitze zur Schattenspitze",
      esriMensurationCentroid: "Schwerpunkt",
      esriMensurationPoint3D: "Punkt (3D)",
      esriMensurationDistanceAndAngle3D: "Entfernung und Winkel (3D)",
      esriMensurationAreaAndPerimeter3D: "Fläche und Umfang (3D)",
      esriMensurationCentroid3D: "Schwerpunkt (3D)"
    }
  })
);