define(
   ({
    taskUrl: "任務 URL",
    serviceURLPlaceholder: "請輸入地理處理任務 URL",
    ok: "確定",
    cancel: "取消",
    layer: "圖層",
    action: "操作",
    input: "輸入",
    output: "輸出",
    name: "名稱",
    type: "類型",
    required: "必填資訊",
    layerOrder: "圖層順序",
    options: "選項",
    defaultValue: "預設值",
    inputFeatureBy: "輸入圖徵",
    renderer: "著色器",
    displayType: "顯示類型",
    label: "標籤",
    tooltip: "工具提示",
    visible: "可見",
    helpUrl: "說明 URL",
    useResultMapService: "使用結果地圖服務的繪製選項",
    drawOnMap: "在地圖上互動繪製",
    selectLayer: "從地圖選擇圖層",
    url: "URL",
    symbol: "符號",
    shareResults: "將結果新增為操作圖層",
    popup: "彈出訊息",
    setTask: "設定",
    setTaskTitle: "設定 GP 任務",
    enablePopup: "啟用彈出訊息",
    unSupportGeometryType: "由於幾何類型未知，因此無法設定著色器。",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "上傳檔案",
    selectFileToUpload: "選擇檔案...",
    upload: "上傳",
    rasterFormat: "光柵資料格式",
    noFileSelected: "未選擇任何檔案!",
    uploadSuccess:"檔案上傳成功!",
    showLayerContent: "顯示圖層內容",
    Feet: "英呎",
    Yards: "碼",
    Miles: "英里",
    NauticalMiles: "海浬",
    Meter: "公尺",
    Kilometers: "公里",
    urlPlaceholder: "圖徵設定 URL",
    allowToExport: "允許匯出結果"
  })
);
