define(
   ({
    taskUrl: "משימת URL",
    serviceURLPlaceholder: "אנא הכנס URL של משימת geoprocessing",
    ok: "אישור",
    cancel: "ביטול",
    layer: "שכבה",
    action: "פעולה",
    input: "קלט",
    output: "פלט",
    name: "שם",
    type: "סוג",
    required: "דרוש",
    layerOrder: "סדר שכבה",
    options: "אפשרויות",
    defaultValue: "ערך ברירת מחדל",
    inputFeatureBy: "ישויות קלט לפי",
    renderer: "Renderer",
    displayType: "הצג סוג",
    label: "תווית",
    tooltip: "הסבר לכלי",
    visible: "ניראה",
    helpUrl: "URL עזרה",
    useResultMapService: "השתמש באופציות ציור של שרות המפה תוצאה",
    drawOnMap: "ציור אינטראקטיבי במפה",
    selectLayer: "בחירת שכבה מהמפה",
    url: "URL",
    symbol: "סמל",
    shareResults: "הוסף תוצאה כשכבה תפעולית",
    popup: "חלון קופץ",
    setTask: "הגדר",
    setTaskTitle: "הגדר משימת GP",
    enablePopup: "אפשר חלון קופץ"
  })
);