define(
   ({
    taskUrl: "משימת URL",
    serviceURLPlaceholder: "אנא הכנס URL של משימת geoprocessing",
    ok: "אישור",
    cancel: "ביטול",
    layer: "שכבה",
    action: "פעולה",
    input: "קלט",
    output: "פלט",
    name: "שם",
    type: "סוג",
    required: "דרוש",
    layerOrder: "סדר שכבה",
    options: "אפשרויות",
    defaultValue: "ערך ברירת מחדל",
    inputFeatureBy: "ישויות קלט לפי",
    renderer: "Renderer",
    displayType: "הצג סוג",
    label: "תווית",
    tooltip: "הסבר לכלי",
    visible: "ניראה",
    helpUrl: "URL עזרה",
    useResultMapService: "השתמש באופציות ציור של שרות המפה תוצאה",
    drawOnMap: "ציור אינטראקטיבי במפה",
    selectLayer: "בחירת שכבה מהמפה",
    url: "URL",
    symbol: "סמל",
    shareResults: "הוסף תוצאה כשכבה תפעולית",
    popup: "חלון קופץ",
    setTask: "הגדר",
    setTaskTitle: "הגדר משימת GP",
    enablePopup: "אפשר חלון קופץ",
    unSupportGeometryType: "לא ניתן להגדיר Renderer בשל סוג גיאומטריה לא מוכר.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "טעינת קובץ",
    selectFileToUpload: "בחר קובץ...",
    upload: "העלאה",
    rasterFormat: "פורמט נתוני רסטר",
    noFileSelected: "לא נבחר קובץ!",
    uploadSuccess:"טעינת הקובץ בוצעה בהצלחה!",
    showLayerContent: "הצג תוכן שכבה",
    Feet: "רגל",
    Yards: "יארד",
    Miles: "מיילים",
    NauticalMiles: "מיילים ימיים",
    Meter: "מטרים",
    Kilometers: "קילומטרים",
    urlPlaceholder: "URL של סט ישויות",
    allowToExport: "אפשר לייצא תוצאות"
  })
);
