define(
	 ({
		queries: "Dotazovací úlohy",
		addNew: "Přidat nový",
    queryLayer: "Vrstva dotazu",
		setSource: "Nastavit",
		setDataSource: "Nastavit zdroj dat",
		name: "Název",
		querySource: "Zdroj dat",
		queryName: "Název úlohy",
		queryDefinition: "Definice filtru",
		resultsSetting: "Nastavení výsledků",
		symbolSetting: "Nastavení symbolů",
		resultSettingTip: "Definujte způsob zobrazování výstupních výsledků.",
		resultItemTitle: "Název výsledné položky",
		resultItemContent: "Obsah výsledné položky",
		fieldsSetTip: "Zaškrtněte pole, která chcete zobrazit. Zvolte pole, jehož přezdívku chcete změnit, případně pole, které chcete uspořádat nebo naformátovat.",
		addField: "Přidat pole",
		visibility: "Viditelnost",
		alias: "Přezdívka",
		specialType: "Speciální typ",
		actions: "Akce",
		none: "Žádné",
		link: "Odkaz",
		image: "Obrázek",
		noField: "Žádná pole",
		operationalLayerTip: "Přidat výsledek jako operační vrstvu",
		setLayerSymbolTip: "Nastavte symboliku pro výsledky dotazu: ",
		setSelectedSymbolTip: "Nastavte symbol pro vybraný prvek.",
		notUseFilter: "Nepoužívat filtr",
		setSourceTip: "Nastavte zdroj dotazu.",
		setFilterTip: "Nastavte filtr správně.",
		ok: "OK",
		cancel: "Storno",
		noFilterTip: "Pokud nedefinujete výraz filtru, tato dotazovací úloha zobrazí všechny prvky v zadaném zdroji dat.",
    relationships: "Relace",
    addRelationshipLayer: "Přidat novou relaci",
    relatedTo: "Související s",
    selectOption: "Proveďte výběr…",
    resultItemSorting: "Řazení výsledných položek",
    field: "Pole",
    sortingOrder: "Pořadí",
    configureFieldsTip: "Nastavte pole, která se použijí k seřazení výsledků dotazu.",
    setSortingFields: "Nastavit pole řazení",
    ascending: "Vzestupně",
    descending: "Sestupně",
    sortBy: "Seřadit podle",
    thenBy: "Poté podle",
    addTask: "Přidat úlohu",
    noTasksTip: 'Žádné úlohy, začněte kliknutím na tlačítko ${addTask}.',
    infoText: "Informace",
    filters: "Filtry",
    results: "Výsledky",
    optionsText: "Možnosti",
    summaryText: "Souhrn",
    attributeFilter: "Filtr atributů",
    attributeFilterTip: "Definujte atributové výrazy, které se použijí ve widgetu k filtrování vrstvy dotazů.",
    noExpressionDefinedTip: "Nebyl definován žádný výraz.",
    needInputValuesTip: "Je nutné zadat hodnoty při spuštění",
    setExpressions: "Nastavit výrazy",
    spatialFilter: "Prostorový filtr",
    spatialFilterTip: "Zvolte prostorové filtry, které se ve widgetu použijí k omezení výsledků.",
    defaultOption: "Výchozí",
    useCurrentExtentTip: "Zčásti nebo zcela v aktuálním rozsahu mapy",
    useDrawGraphicTip: "Zčásti nebo zcela v obrazci nakresleném v mapě",
    useFeaturesTip: "Na základě umístění prvků v jiné vrstvě",
    noSpatialLimitTip: "Neomezovat výsledky podle polohy",
    drawingTools: "Nástroje kreslení",
    bufferSettings: "Nastavení obalové zóny",
    defaultDistance: "Výchozí vzdálenost",
    bufferDistance: "Šířka obalové zóny",
    defaultUnit: "Výchozí jednotka",
    miles: "Míle",
    kilometers: "Kilometry",
    feet: "Stopy",
    meters: "Metry",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    availableSpatialRelationships: "Dostupné prostorové vztahy",
    setSpatialRelationships: "Nastavit prostorové vztahy",
    availability: "Dostupnost",
    relationship: "Relace",
    label: "Štítek",
    intersect: "protínají",
    contain: "obsahují",
    areContainedIn: "jsou obsaženy v",
    cross: "křížek",
    envelopeIntersect: "protínají obálku",
    overlap: "překrývají",
    areOverlapped: "jsou překryté",
    touche: "dotýkají se",
    within: "v dosahu",
    areWithin: "jsou v dosahu",
    indexIntersect: "protínají index",
    itemTitle: "Název položky",
    displayFields: "Pole zobrazení",
    sortingFields: "Pole třídění",
    setDisplayFields: "Nastavit pole zobrazení",
    symbol: "Symbol",
    setSymbol: "Nastavit symbol",
    serviceSymbolTip: "Používat symboly definované vrstvou",
    exportTip: "Zobrazit tlačítko pro export",
    keepResultsTip: "Uchovat výsledky na mapě po zavření widgetu",
    queryRelatedRecords: "Záznamy související s dotazy",
    createLayerForTaskTip: "Určete způsob vytváření vrstev úlohou",
    oneLayerForTaskTip: "Vytvořit pouze jednu vrstvu pro tuto úlohu",
    multipleLayerForTaskTip: "Vytvořit novou vrstvu po každém spuštění této úlohy"
  })
);
