define(
	 ({
		queries: "Dotazovací úlohy",
		addNew: "Přidat nový",
		setSource: "Nastavit",
		setDataSource: "Nastavit zdroj dat",
		name: "Název",
		querySource: "Zdroj dat",
		queryName: "Název úlohy",
		queryDefinition: "Definice filtru",
		resultsSetting: "Nastavení výsledků",
		symbolSetting: "Nastavení symbolů",
		resultSettingTip: "Definujte způsob zobrazování výstupních výsledků.",
		resultItemTitle: "Název výsledné položky",
		resultItemContent: "Obsah výsledné položky",
		fieldsSetTip: "Zaškrtněte pole, která chcete zobrazit. Zvolte pole, jehož přezdívku chcete změnit, případně pole, které chcete uspořádat nebo naformátovat.",
		addField: "Přidat pole",
		visibility: "Viditelnost",
		alias: "Přezdívka",
		specialType: "Speciální typ",
		actions: "Akce",
		none: "Žádné",
		link: "Odkaz",
		image: "Obrázek",
		noField: "Žádná pole",
		operationalLayerTip: "Přidat výsledek jako operační vrstvu",
		setLayerSymbolTip: "Nastavte symboliku pro výsledky dotazu: ",
		setSelectedSymbolTip: "Nastavte symbol pro vybraný prvek.",
		notUseFilter: "Nepoužívat filtr",
		setSourceTip: "Nastavte zdroj dotazu.",
		setFilterTip: "Nastavte filtr správně.",
		ok: "OK",
		cancel: "Storno",
		noFilterTip: "Pokud nedefinujete výraz filtru, tato dotazovací úloha zobrazí všechny prvky v zadaném zdroji dat."
  })
);