define(
   ({
    "tabs_section_Label": "索引標籤",
    "addTab": "新增索引標籤",
    "layerName": "圖層",
    "layerType": "分析類型",
    "layerLabel": "標籤",
    "actions": "操作",
    "closest": "最近的圖徵",
    "proximity": "鄰域分析",
    "summary": "摘要",
    "select_lbl": "-- 選擇 --",
    "general_setting_Label": "一般設定",
    "units_text_lbl": "距離單位",
    "miles": "英里",
    "kilometers": "公里",
    "feet": "英呎",
    "meters": "公尺",
    "yards": "碼",
    "nauticalMiles": "海浬",
    "maximum_distance_lbl": "最近的圖徵最大距離",
    "buffer_text_lbl": "緩衝區標籤",
    "buffer_lbl": "緩衝距離",
    "buffer_max_lbl": "最大緩衝距離",
    "buffer_min_lbl": "最小緩衝距離",
    "routing_checkBox": "啟用路徑尋找",
    "weather_Label": "天氣選項",
    "weather_checkBox": "包括天氣資訊",
    "selectLayers": "選擇天氣圖層",
    "currentlySelectedLayer": "目前選擇的天氣圖層",
    "missingTabLabel": "至少一個索引標籤缺失標籤",
    "cancel": "取消",
    "ok": "確定",
    "missingLayerInWebMap": "未找到業務圖層。",
    "selectFields": "選擇欄位",
    "addField": "增加欄位",
    "sum": "總和",
    "min": "最小值",
    "max": "最大值",
    "avg": "平均值",
    "count": "計數",
    "area": "區域",
    "length": "長度",
    "count_checkBox": "顯示計數",
    "area_checkBox": "顯示區域",
    "length_checkBox": "顯示長度",
    "max_records": "已達上限"
  })
);
