define(
   ({
    _widgetLabel: "Skriv ut",
    title: "Karttittel",
    format: "Format",
    layout: "Layout",
    settings: "Avansert",
    mapScaleExtent: "Kartmålestokk/-utstrekning",
    preserve: "Bevar",
    mapScale: "målestokk",
    mapExtent: "kartutstrekning",
    forceScale: "Tving målestokk",
    getCurrentScale: "gjeldende",
    mapMetadata: "Layout metadata",
    author: "Oppretter",
    copyright: "Copyright",
    fullLayoutOptions: "Komplette layoutalternativer",
    scaleBarUnitsMetric: "Målestokklinjal metriske måleenheter",
    scaleBarUnitsNonMetric: "Målestokklinjal ikke-metriske måleenheter",
    unitsMiles: "Miles",
    unitsKilometers: "Kilometer",
    unitsMeters: "Meter",
    unitsFeet: "Fot",
    unitsYards: "Yards",
    unitsNauticalMiles: "Nautiske mil",
    lncludeLegend: "Inkluder tegnforklaring",
    printQualityOptions: "Utskriftskvalitet",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY størrelse",
    width: "Bredde (px)",
    height: "Høyde (px)",
    print: "Skriv ut",
    clearList: "Fjern utskrifter",
    creatingPrint: "Oppretter utskrfit",
    printError: "Feil, prøv igjen"
  })
);