define(
   ({
    _widgetLabel: "クエリ",
    executeQueryTip: "以下のタスク アイテムのいずれかをクリックしてクエリを実行します。",
    invalidConfig: "構成が無効です。クエリ設定ページで構成を修正してください。",
    queryParams: "オプション",
    parameters: "オプション",
    queries: "クエリ",
    apply: "適用",
    queryResults: "結果",
    clear: "消去",
    noResults: "フィーチャは見つかりませんでした。",
    queryError: "クエリが失敗しました",
    numberFound: "検出されたフィーチャの数",
    mapExtentTip: "結果を現在のマップ エリアに制限します。",
    noValue: "値がありません",
    and: "から",
    stringOperatorIs: "に等しい", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "に等しくない",
    stringOperatorStartsWith: "で始まる",
    stringOperatorEndsWith: "で終わる",
    stringOperatorContains: "を含む",
    stringOperatorDoesNotContain: "を含まない",
    stringOperatorIsBlank: "空である",
    stringOperatorIsNotBlank: "空でない",
    dateOperatorIsOn: "である", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "でない",
    dateOperatorIsBefore: "より前である",
    dateOperatorIsAfter: "より後である",
    dateOperatorDays: "日",
    dateOperatorWeeks: "週", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "月",
    dateOperatorInTheLast: "以内である",
    dateOperatorNotInTheLast: "以内でない",
    dateOperatorIsBetween: "の間にある",
    dateOperatorIsNotBetween: "の間にない",
    dateOperatorIsBlank: "空である",
    dateOperatorIsNotBlank: "空でない",
    numberOperatorIs: "に等しい", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "に等しくない",
    numberOperatorIsAtLeast: "以上",
    numberOperatorIsLessThan: "より小さい",
    numberOperatorIsAtMost: "以下",
    numberOperatorIsGreaterThan: "より大きい",
    numberOperatorIsBetween: "の間にある",
    numberOperatorIsNotBetween: "の間にない",
    numberOperatorIsBlank: "空である",
    numberOperatorIsNotBlank: "空でない",
    operationalLayerTip: "操作レイヤーとして結果を追加",
    queryResult: "クエリ結果",
    specifyParamsTip: "このタスクのパラメーターを指定",
    useSpatialFilter: "空間フィルターを使用してフィーチャを制限",
    useCurrentMapExtent: "現在のマップ エリアと交差するフィーチャのみ",
    drawGraphicOnMap: "ユーザー指定エリアと交差するフィーチャのみ",
    specifySpatialFilterMsg: "このタスクの空間フィルターを指定してください。",
    clearResults: "結果の消去",
    operationalTip: 'このオプションをオンにすると、結果は、\"${clearResults}\" ボタンがクリックされるまでマップ上に維持されます。',
    noneQueryTip: "このウィジェット用のクエリ タスクが構成されていません。",
    noPermissionsMsg: "このサービスにアクセスできる権限がありません。",
    attributesFromRelationship: "関連テーブルの属性",
    tasks: "タスク",
    applySpatialFilterToLimitResults: "空間フィルターを適用して結果を制限する",
    useCurrentExtentTip: "現在のマップ範囲に部分的または完全に含まれる",
    useDrawGraphicTip: "マップに描画された図形に部分的または完全に含まれる",
    useFeaturesTip: "別のレイヤー内のフィーチャを基準にした位置に基づく",
    noSpatialLimitTip: "結果を空間的に制限しない",
    applySearchDistance: "検索距離の適用",
    spatialRelationship: "空間リレーションシップ",
    relatedLayer: "関連レイヤー",
    bufferDistance: "バッファー距離",
    miles: "マイル",
    kilometers: "キロメートル",
    feet: "フィート",
    meters: "メートル",
    yards: "ヤード",
    nauticalMiles: "海里",
    back: "戻る",
    execute: "実行"
  })
);