define(
   ({
    _widgetLabel: "クエリ",
    executeQueryTip: "以下のタスク アイテムのいずれかをクリックしてクエリを実行します。",
    invalidConfig: "構成が無効です。クエリ設定ページで構成を修正してください。",
    queryParams: "オプション",
    parameters: "オプション",
    queries: "クエリ",
    apply: "適用",
    queryResults: "結果",
    clear: "消去",
    noResults: "フィーチャは見つかりませんでした。",
    queryError: "クエリが失敗しました",
    numberFound: "検出されたフィーチャの数",
    mapExtentTip: "結果を現在のマップ範囲に制限します。",
    noValue: "値がありません",
    and: "から",
    stringOperatorIs: "に等しい", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "に等しくない",
    stringOperatorStartsWith: "で始まる",
    stringOperatorEndsWith: "で終わる",
    stringOperatorContains: "を含む",
    stringOperatorDoesNotContain: "を含まない",
    stringOperatorIsBlank: "空である",
    stringOperatorIsNotBlank: "空でない",
    dateOperatorIsOn: "である", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "でない",
    dateOperatorIsBefore: "より前である",
    dateOperatorIsAfter: "より後である",
    dateOperatorDays: "日",
    dateOperatorWeeks: "週", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "月",
    dateOperatorInTheLast: "以内である",
    dateOperatorNotInTheLast: "以内でない",
    dateOperatorIsBetween: "の間にある",
    dateOperatorIsNotBetween: "の間にない",
    dateOperatorIsBlank: "空である",
    dateOperatorIsNotBlank: "空でない",
    numberOperatorIs: "に等しい", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "に等しくない",
    numberOperatorIsAtLeast: "以上",
    numberOperatorIsLessThan: "より小さい",
    numberOperatorIsAtMost: "以下",
    numberOperatorIsGreaterThan: "より大きい",
    numberOperatorIsBetween: "の間にある",
    numberOperatorIsNotBetween: "の間にない",
    numberOperatorIsBlank: "空である",
    numberOperatorIsNotBlank: "空でない",
    operationalLayerTip: "操作レイヤとして結果を追加",
    queryResult: "クエリ結果",
    specifyParamsTip: "このタスクのパラメータを指定",
    useSpatialFilter: "空間フィルタを使用してフィーチャを制限",
    useCurrentMapExtent: "現在のマップ範囲の境界にあるフィーチャのみ",
    drawGraphicOnMap: "ユーザ指定エリアの境界にあるフィーチャのみ",
    specifySpatialFilterMsg: "このタスクの空間フィルタを指定してください。",
    clearResults: "結果の消去",
    operationalTip: 'このオプションをオンにすると、結果は、"${clearResults}" ボタンがクリックされるまでマップ上に維持されます。',
    noneQueryTip: "あらかじめ構成されているクエリ タスクは利用できません。",
    noPermissionsMsg: "このサービスにアクセスできる権限がありません。"
  })
);