define(
   ({
    _widgetLabel: "Gadījumu analīze",
    incident: "Gadījums",
    weather: "Laikapstākļi",
    locate_incident: "Atrast gadījumu",
    clear_incidents: "Notīrīt gadījumus",
    reverse_geocoded_address: "Tuvākā adrese",
    reverse_geocoded_error: "Nav pieejami",
    miles: "Jūdzes",
    kilometers: "Kilometri",
    feet: "Pēdas",
    meters: "Metri",
    yards: "Jardi",
    nauticalMiles: "Jūras jūdzes",
    now: "TŪLĪT",
    wind: "VĒJŠ",
    SUN: "SVĒTD.",
    MON: "PIRMD.",
    TUE: "OTRD.",
    WED: "TREŠD.",
    THU: "CETURTD.",
    FRI: "PIEKTD.",
    SAT: "SESTD.",
    defaultTabMsg: "Nav noteikts neviens gadījums.",
    actionLabel: "Iestatīt kā gadījumu",
    useMapExtent: "Lietot pašreizējo kartes apmēru",
    noFeaturesFound: "Nav atrasts neviens elements.",
    downloadCSV: "LEJUPIELĀDĒT CSV",
    sum: "SUM",
    min: "MIN",
    max: "MAKS.",
    avg: "VID",
    count: "SKAITĪT",
    area: "APGABALS",
    length: "GARUMS"
  })
);
