define({
  root: ({
    _widgetLabel: "Print",
    title: "Map Title",
    format: "Format",
    layout: "Layout",
    settings: "Advanced",
    mapScaleExtent: "Map scale/extent",
    preserve: "Preserve",
    mapScale: "map scale",
    mapExtent: "map extent",
    forceScale: "Force scale",
    getCurrentScale: "current",
    mapMetadata: "Layout metadata",
    author: "Author",
    copyright: "Copyright",
    fullLayoutOptions: "Full layout options",
    scaleBarUnitsMetric: "Scale bar units metric",
    scaleBarUnitsNonMetric: "Scale bar units non-metric",
    unitsMiles: "Miles",
    unitsKilometers: "Kilometers",
    unitsMeters: "Meters",
    unitsFeet: "Feet",
    unitsYards: "Yards",
    unitsNauticalMiles: "Nautical Miles",
    lncludeLegend: "Include legend",
    printQualityOptions: "Print quality",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY size",
    width: "Width (px)",
    height: "Height (px)",
    print: "Print",
    clearList: "Clear Prints",
    creatingPrint: "Creating Print",
    printError: "Error, try again"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});