define(
   ({
    _widgetLabel: "Vaicājums",
    executeQueryTip: "Noklikšķiet uz kādas no tālāk esošajām uzdevuma vienībām, lai izpildītu vaicājumu.",
    invalidConfig: "Nederīga konfigurācija. Izmantojiet vaicājumu iestatījumu lapu, lai iegūtu pareizu konfigurāciju.",
    queryParams: "Opcijas",
    parameters: "OPCIJAS",
    queries: "VAICĀJUMI",
    apply: "LIETOT",
    queryResults: "Rezultāti",
    clear: "Notīrīt",
    noResults: "Nav atrasts neviens elements.",
    queryError: "Vaicājums neizdevās.",
    numberFound: "Atrasto elementu skaits",
    mapExtentTip: "Ierobežot rezultātus līdz pašreizējam kartes pārklājumam.",
    noValue: "Nav vērtības",
    and: "un",
    stringOperatorIs: "ir", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "nav",
    stringOperatorStartsWith: "sākas ar",
    stringOperatorEndsWith: "beidzas ar",
    stringOperatorContains: "ietver",
    stringOperatorDoesNotContain: "neietver",
    stringOperatorIsBlank: "ir tukšs",
    stringOperatorIsNotBlank: "nav tukšs",
    dateOperatorIsOn: "ir šajā datumā", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "nav šajā datumā",
    dateOperatorIsBefore: "ir pirms",
    dateOperatorIsAfter: "ir pēc",
    dateOperatorDays: "dienas",
    dateOperatorWeeks: "nedēļas", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "mēneši",
    dateOperatorInTheLast: "pagātnē",
    dateOperatorNotInTheLast: "nav pagātnē",
    dateOperatorIsBetween: "ir starp",
    dateOperatorIsNotBetween: "nav starp",
    dateOperatorIsBlank: "ir tukšs",
    dateOperatorIsNotBlank: "nav tukšs",
    numberOperatorIs: "ir", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "nav",
    numberOperatorIsAtLeast: "ir vismaz",
    numberOperatorIsLessThan: "ir mazāks nekā",
    numberOperatorIsAtMost: "ir visvairāk",
    numberOperatorIsGreaterThan: "ir lielāks nekā",
    numberOperatorIsBetween: "ir starp",
    numberOperatorIsNotBetween: "nav starp",
    numberOperatorIsBlank: "ir tukšs",
    numberOperatorIsNotBlank: "nav tukšs",
    operationalLayerTip: "Pievienot rezultātu kā darbības slāni",
    queryResult: "Vaicājuma rezultāts",
    specifyParamsTip: "Norādiet šī uzdevuma parametrus",
    useSpatialFilter: "Izmantot telpisko filtru, lai ierobežotu elementus",
    useCurrentMapExtent: "Tikai elementi, kas saskaras ar pašreizējās kartes pārklājumu",
    drawGraphicOnMap: "Tikai elementi, kas saskaras ar lietotāja definēto teritoriju",
    specifySpatialFilterMsg: "Norādiet šī uzdevuma telpisko filtru.",
    clearResults: "Notīrīt rezultātus",
    operationalTip: 'Ja šī opcija ir atzīmēta, rezultāti paliek kartē, līdz tiek noklikšķināts uz pogas "${clearResults}".',
    noneQueryTip: "Nav pieejams neviens iepriekš konfigurēts vaicājuma uzdevums.",
    noPermissionsMsg: "Jums nav atļauju piekļūt šim pakalpojumam."
  })
);