define(
   ({
    routeUrl: "URL trasy",
    locatorUrl: "URL geokodéru",
    geocoderOptions: "Možnosti geokodéru",
    autoComplete: "Automatické dokončování",
    maxLocations: "Maximální počet umístění",
    minCharacters: "Minimální počet znaků",
    searchDelay: "Prodleva vyhledávání",
    placeholder: "Zástupný znak",
    routeOptions: "Možnosti trasy",
    directionsLanguage: "Jazyk pokynů",
    directionsLengthUnits: "Jednotky délky v pokynech",
    directionsOutputType: "Typ výstupu pokynů",
    impedanceAttribute: "Atribut impedance",
    kilometers: "Kilometry",
    miles: "Míle",
    meters: "Metry",
    feet: "Stopy",
    yards: "Yardy",
    nauticalMiles: "Námořní míle",
    parametersTip: "Prosím, nastavte parametry správně.",
    complete: "Dokončeno",
    completeNoEvents: "Dokončeno, žádné události",
    instructionsOnly: "Pouze instrukce",
    standard: "Standardní",
    summaryOnly: "Pouze shrnutí",
    travelModesUrl: "Adresa URL způsobů přepravy",
    searchPlaceholder: "Najít adresu nebo místo",
    trafficLayerUrl: "Adresa URL vrstvy provozu"
  })
);