define(
   ({
    _widgetLabel: "Situation Awareness (Beta)",
    locate_incident: "Localizar Incidente",
    clear_incidents: "Limpar Incidentes",
    reverse_geocoded_address: "Endereço mais próximo",
    reverse_geocoded_error: "Não disponível",
    miles: "Milhas",
    kilometers: "Quilômetros",
    feet: "Pés",
    meters: "Metros",
    yards: "Jardas",
    nauticalMiles: "Milhas Náuticas",
    now: "AGORA",
    wind: "VENTO",
    SUN: "DOM",
    MON: "SEG",
    TUE: "TER",
    WED: "QUA",
    THU: "QUI",
    FRI: "SEX",
    SAT: "SÁB",
    defaultTabMsg: "Nenhum incidente identificado.",
    actionLabel: "Definir Como Incidente",
    drawPoint: "Desenhar Ponto",
    drawLine: "Desenhar Linha",
    drawPolygon: "Desenhar Polígono",
    saveIncident: "Guardar Incidente",
    clearIncident: "Limpar Incidente",
    useMapExtent: "Usar a extensão de mapa actual",
    noFeaturesFound: "Não foram encontrados nenhuns elementos.",
    downloadCSV: "DESCARREGAR CSV",
    editComplete: "Elemento guardado com sucesso!",
    updateComplete: "Elemento atualizado com sucesso!",
    deleteComplete: "Elemento eliminado com sucesso!",
    sum: "SUM",
    min: "MIN",
    max: "MAX",
    avg: "AVG",
    count: "CONTAGEM",
    area: "ÁREA",
    length: "LENGTH",
    notPolySave: "Por favor especifique uma distância de buffer antes de guardar.",
    update_btn: "Atualização",
    delete_btn: "Eliminar"
  })
);
