define({
  root: ({
    taskUrl: "Task URL",
    serviceURLPlaceholder: "Please input Geoprocessing task URL",
    ok: "OK",
    cancel: "Cancel",
    layer: "Layer",
    action: "Action",
    input: "Input",
    output: "Output",
    name: "Name",
    type: "Type",
    required: "Required",
    layerOrder: "Layer order",
    options: "Options",
    defaultValue: "Default Value",
    inputFeatureBy: "Input Feature by",
    renderer: "Renderer",
    displayType: "Display type",
    label: "Label",
    tooltip: "Tooltip",
    visible: "Visible",
    helpUrl: "Help URL",
    useResultMapService: "Use the drawing options of result map service",
    drawOnMap: "Interactively drawing on the map",
    selectLayer: "Selecting a layer from the map",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Add result as operational layer",
    popup: "Popup",
    setTask: "Set",
    setTaskTitle: "Set GP Task",
    enablePopup: "Enable popup",
    unSupportGeometryType: "Can not set renderer because of unknown geometry type.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Upload file",
    selectFileToUpload: "Select file...",
    upload: "Upload",
    rasterFormat: "Raster data format",
    noFileSelected: "No file selected!",
    uploadSuccess:"Uploaded file successfully!",
    showLayerContent: "Show layer content",
    Feet: "Feet",
    Yards: "Yards",
    Miles: "Miles",
    NauticalMiles: "Nautical Miles",
    Meter: "Meters",
    Kilometers: "Kilometers",
    urlPlaceholder: "feature set URL",
    allowToExport: "Allow to export results"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
