define(
   ({
    _widgetLabel: "Drucken",
    title: "Kartentitel",
    format: "Format",
    layout: "Layout",
    settings: "Erweitert",
    mapScaleExtent: "Maßstab/Ausdehnung der Karte",
    preserve: "Beibehalten",
    mapScale: "Kartenmaßstab",
    mapExtent: "Kartenausdehnung",
    forceScale: "Maßstab erzwingen",
    getCurrentScale: "aktuell",
    mapMetadata: "Layout-Metadaten",
    author: "Autor",
    copyright: "Copyright",
    fullLayoutOptions: "Optionen für vollständiges Layout",
    scaleBarUnitsMetric: "Metrik der Maßstabsleisteneinheiten",
    scaleBarUnitsNonMetric: "Nicht metrische Maßstabsleisteneinheiten",
    unitsMiles: "Meilen",
    unitsKilometers: "Kilometer",
    unitsMeters: "Meter",
    unitsFeet: "Fuß",
    unitsYards: "Yards",
    unitsNauticalMiles: "Seemeilen",
    lncludeLegend: "Legende einbeziehen",
    printQualityOptions: "Druckqualität",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY-Größe",
    width: "Breite (Px)",
    height: "Höhe (Px)",
    print: "Drucken",
    clearList: "Ausdrucke löschen",
    creatingPrint: "Ausdruck wird erstellt",
    printError: "Fehler, versuchen Sie es erneut"
  })
);