define(
   ({
    _widgetLabel: "Signaler une entité",
    select: "Sélectionner",
    draw: "Dessin",
    chooseALayer: "Sélectionner une couche",
    clickAFeature: "Cliquez sur une entité de la carte pour la sélectionner.",
    loadingFeatures: "Obtention des détails de l\'entité...",
    errorTitle: "Erreur",
    errorIdentify: "Erreur d\'identification des entités. Consultez le journal de la console pour en savoir plus.",
    infoWindowTitle: "Détails",
    layerLabel: "Nom de la couche",
    reviewStatusLabel: "Examiner le statut",
    selectReviewStatusAdd: "Ajouter une entité",
    selectReviewStatusDelete: "Supprimer l’entité",
    selectReviewStatusMove: "Déplacer l\'entité",
    selectReviewStatusReshape: "Remodeler l\'entité",
    drawReviewStatusMissing: "Entité(s) manquante(s)",
    drawReviewStatusPosition: "Erreur de position",
    drawReviewStatusShape: "Erreur de forme",
    drawReviewStatusAttribute: "Erreur d\'attribut",
    notesLabel: "Remarques",
    severityLabel: "Gravité",
    reportedByLabel: "Signalé par",
    reportedByDefault: "anonyme",
    reportButton: "Rapport",
    reportMessage: "Rapport reçu",
    errorReportMessage: "Une erreur s\'est produite lors du signalement de votre entité",
    drawErrorInstructions: "Sélectionnez un point, une ligne ou un polygone et dessinez la géométrie d\'erreur sur la carte :",
    errorMapService: "Une erreur s\'est produite lors de l\'obtention des informations sur le service de carte",
    noFeatureSelected : "Aucune entité n\'a été trouvée à l\'emplacement sur lequel vous avez cliqué",
    selectFeatureMapPoint: "Cliquez pour sélectionner une entité",
    drawFeatureMapPoint: "Cliquez pour ajouter un point",
    popupMessage:"Message",
    popupError:"Erreur",
    manyFeaturesSelected: "Plusieurs entités ont été trouvées. Appliquez un zoom avant et sélectionnez une entité à signaler."
  })
);
